.TH "__htftp_t" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__htftp_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_sp\fP"
.br
.ti -1c
.RI "struct \fB__htftp_request_header_t\fP * \fB_hfhdr\fP"
.br
.ti -1c
.RI "struct sockaddr_in * \fB_insaddr\fP"
.br
.ti -1c
.RI "struct pollfd \fB_spoll\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fB__htftp_request_header_t\fP* __htftp_t::_hfhdr"

.SS "struct sockaddr_in* __htftp_t::_insaddr"

.SS "int __htftp_t::_sp"

.SS "struct pollfd __htftp_t::_spoll"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
