.TH "__htftp_protocol_header_t" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__htftp_protocol_header_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char method \fB_rblock\fP (100)"
.br
.ti -1c
.RI "char request \fB_rblock\fP (100)"
.br
.ti -1c
.RI "char htftp_version \fB_rblock\fP (100)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "char method __htftp_protocol_header_t::_rblock (100)"

.SS "char request __htftp_protocol_header_t::_rblock (100)"

.SS "char htftp_version __htftp_protocol_header_t::_rblock (100)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
