.TH "__lsck_t" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__lsck_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'mksck\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fB_sckfn\fP [\fBMAX_BUFFER\fP]"
.br
.ti -1c
.RI "\fBsfd_t\fP \fB_sckfd\fP"
.br
.ti -1c
.RI "\fB__SUN_ADDR\fP \fB_sun\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsfd_t\fP __lsck_t::_sckfd"

.SS "char __lsck_t::_sckfn[\fBMAX_BUFFER\fP]"

.SS "\fB__SUN_ADDR\fP __lsck_t::_sun"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
