.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/truststore/_api.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/truststore/_api.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._vendor\&.truststore\&._api\&.SSLContext\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.truststore\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.truststore\&._api\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBpip\&._vendor\&.truststore\&._api\&.inject_into_ssl\fP ()"
.br
.ti -1c
.RI "None \fBpip\&._vendor\&.truststore\&._api\&.extract_from_ssl\fP ()"
.br
.ti -1c
.RI "list[bytes] \fBpip\&._vendor\&.truststore\&._api\&._get_unverified_chain_bytes\fP (ssl\&.SSLObject sslobj)"
.br
.ti -1c
.RI "None \fBpip\&._vendor\&.truststore\&._api\&._verify_peercerts\fP (ssl\&.SSLSocket|ssl\&.SSLObject sock_or_sslobj, str|None server_hostname)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "typing \fBpip\&._vendor\&.truststore\&._api\&._StrOrBytesPath\fP = str | bytes | os\&.PathLike[str] | os\&.PathLike[bytes]"
.br
.ti -1c
.RI "typing \fBpip\&._vendor\&.truststore\&._api\&._PasswordType\fP = str | bytes | typing\&.Callable[[], str | bytes]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
