.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/bs4/builder/_html5lib.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/bs4/builder/_html5lib.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbs4\&.builder\&._html5lib\&.HTML5TreeBuilder\fP"
.br
.ti -1c
.RI "class \fBbs4\&.builder\&._html5lib\&.TreeBuilderForHtml5lib\fP"
.br
.ti -1c
.RI "class \fBbs4\&.builder\&._html5lib\&.AttrList\fP"
.br
.ti -1c
.RI "class \fBbs4\&.builder\&._html5lib\&.BeautifulSoupNode\fP"
.br
.ti -1c
.RI "class \fBbs4\&.builder\&._html5lib\&.Element\fP"
.br
.ti -1c
.RI "class \fBbs4\&.builder\&._html5lib\&.TextNode\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbs4\fP"
.br
.ti -1c
.RI "namespace \fBbs4\&.builder\fP"
.br
.ti -1c
.RI "namespace \fBbs4\&.builder\&._html5lib\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
