.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/requests/_internal_utils.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/requests/_internal_utils.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrequests\fP"
.br
.ti -1c
.RI "namespace \fBrequests\&._internal_utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrequests\&._internal_utils\&.to_native_string\fP (string, encoding='ascii')"
.br
.ti -1c
.RI "\fBrequests\&._internal_utils\&.unicode_is_ascii\fP (u_string)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBrequests\&._internal_utils\&._VALID_HEADER_NAME_RE_BYTE\fP = re\&.compile(rb'^[^:\\s][^:\\r\\n]*$')"
.br
.ti -1c
.RI "\fBrequests\&._internal_utils\&._VALID_HEADER_NAME_RE_STR\fP = re\&.compile(r'^[^:\\s][^:\\r\\n]*$')"
.br
.ti -1c
.RI "\fBrequests\&._internal_utils\&._VALID_HEADER_VALUE_RE_BYTE\fP = re\&.compile(rb'^\\S[^\\r\\n]*$|^$')"
.br
.ti -1c
.RI "\fBrequests\&._internal_utils\&._VALID_HEADER_VALUE_RE_STR\fP = re\&.compile(r'^\\S[^\\r\\n]*$|^$')"
.br
.ti -1c
.RI "tuple \fBrequests\&._internal_utils\&._HEADER_VALIDATORS_STR\fP = (\fB_VALID_HEADER_NAME_RE_STR\fP, \fB_VALID_HEADER_VALUE_RE_STR\fP)"
.br
.ti -1c
.RI "tuple \fBrequests\&._internal_utils\&._HEADER_VALIDATORS_BYTE\fP = (\fB_VALID_HEADER_NAME_RE_BYTE\fP, \fB_VALID_HEADER_VALUE_RE_BYTE\fP)"
.br
.ti -1c
.RI "dict \fBrequests\&._internal_utils\&.HEADER_VALIDATORS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
