.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/lexers/_lilypond_builtins.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/lexers/_lilypond_builtins.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpygments\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.lexers\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.lexers\&._lilypond_builtins\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.keywords\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.clefs\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.scales\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.repeat_types\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.units\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.chord_modifiers\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.pitch_language_names\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.pitches\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.music_functions\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.dynamics\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.articulations\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.music_commands\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.markup_commands\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.grobs\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.contexts\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.translators\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.scheme_functions\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.context_properties\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.grob_properties\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.paper_variables\fP"
.br
.ti -1c
.RI "list \fBpygments\&.lexers\&._lilypond_builtins\&.header_variables\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
