.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/rich/_ratio.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/rich/_ratio.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._vendor\&.rich\&._ratio\&.Edge\fP"
.br
.ti -1c
.RI "class \fBpip\&._vendor\&.rich\&._ratio\&.E\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.rich\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.rich\&._ratio\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "List[int] \fBpip\&._vendor\&.rich\&._ratio\&.ratio_resolve\fP (int total, Sequence[\fBEdge\fP] edges)"
.br
.ti -1c
.RI "List[int] \fBpip\&._vendor\&.rich\&._ratio\&.ratio_reduce\fP (int total, List[int] ratios, List[int] maximums, List[int] values)"
.br
.ti -1c
.RI "List[int] \fBpip\&._vendor\&.rich\&._ratio\&.ratio_distribute\fP (int total, List[int] ratios, Optional[List[int]] minimums=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._vendor\&.rich\&._ratio\&.resolved\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
