.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/tomli/_re.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/tomli/_re.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.tomli\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.tomli\&._re\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "datetime|date \fBpip\&._vendor\&.tomli\&._re\&.match_to_datetime\fP (re\&.Match match)"
.br
.ti -1c
.RI "timezone \fBpip\&._vendor\&.tomli\&._re\&.cached_tz\fP (str hour_str, str minute_str, str sign_str)"
.br
.ti -1c
.RI "time \fBpip\&._vendor\&.tomli\&._re\&.match_to_localtime\fP (re\&.Match match)"
.br
.ti -1c
.RI "Any \fBpip\&._vendor\&.tomli\&._re\&.match_to_number\fP (re\&.Match match, ParseFloat parse_float)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBpip\&._vendor\&.tomli\&._re\&._TIME_RE_STR\fP = r'([01][0\-9]|2[0\-3]):([0\-5][0\-9]):([0\-5][0\-9])(?:\\\&.([0\-9]{1,6})[0\-9]*)?'"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.tomli\&._re\&.RE_NUMBER\fP"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.tomli\&._re\&.RE_LOCALTIME\fP = re\&.compile(\fB_TIME_RE_STR\fP)"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.tomli\&._re\&.RE_DATETIME\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
