.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/ext/intersphinx/_resolve.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/ext/intersphinx/_resolve.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.ext\&.intersphinx\&._resolve\&.IntersphinxDispatcher\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.ext\&.intersphinx\&._resolve\&.IntersphinxRole\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.ext\&.intersphinx\&._resolve\&.IntersphinxRoleResolver\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.ext\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.ext\&.intersphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.ext\&.intersphinx\&._resolve\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "nodes\&.reference \fBsphinx\&.ext\&.intersphinx\&._resolve\&._create_element_from_result\fP (str domain_name, InventoryName|None inv_name, \fB_InventoryItem\fP inv_item, \fBpending_xref\fP node, \fBTextElement\fP contnode)"
.br
.ti -1c
.RI "nodes\&.reference|None \fBsphinx\&.ext\&.intersphinx\&._resolve\&._resolve_reference_in_domain_by_target\fP (InventoryName|None inv_name, Inventory inventory, str domain_name, Iterable[str] objtypes, str target, \fBpending_xref\fP node, \fBTextElement\fP contnode)"
.br
.ti -1c
.RI "nodes\&.reference|None \fBsphinx\&.ext\&.intersphinx\&._resolve\&._resolve_reference_in_domain\fP (InventoryName|None inv_name, Inventory inventory, bool honor_disabled_refs, Set[str] disabled_reftypes, \fBDomain\fP domain, Iterable[str] objtypes, \fBpending_xref\fP node, \fBTextElement\fP contnode)"
.br
.ti -1c
.RI "nodes\&.reference|None \fBsphinx\&.ext\&.intersphinx\&._resolve\&._resolve_reference\fP (InventoryName|None inv_name, \fB_DomainsContainer\fP domains, Inventory inventory, bool honor_disabled_refs, Set[str] disabled_reftypes, \fBpending_xref\fP node, \fBTextElement\fP contnode)"
.br
.ti -1c
.RI "bool \fBsphinx\&.ext\&.intersphinx\&._resolve\&.inventory_exists\fP (\fBBuildEnvironment\fP env, InventoryName inv_name)"
.br
.ti -1c
.RI "nodes\&.reference|None \fBsphinx\&.ext\&.intersphinx\&._resolve\&.resolve_reference_in_inventory\fP (\fBBuildEnvironment\fP env, InventoryName inv_name, \fBpending_xref\fP node, \fBTextElement\fP contnode)"
.br
.ti -1c
.RI "nodes\&.reference|None \fBsphinx\&.ext\&.intersphinx\&._resolve\&.resolve_reference_any_inventory\fP (\fBBuildEnvironment\fP env, bool honor_disabled_refs, \fBpending_xref\fP node, \fBTextElement\fP contnode)"
.br
.ti -1c
.RI "nodes\&.reference|None \fBsphinx\&.ext\&.intersphinx\&._resolve\&.resolve_reference_detect_inventory\fP (\fBBuildEnvironment\fP env, \fBpending_xref\fP node, \fBTextElement\fP contnode)"
.br
.ti -1c
.RI "nodes\&.reference|None \fBsphinx\&.ext\&.intersphinx\&._resolve\&.missing_reference\fP (\fBSphinx\fP app, \fBBuildEnvironment\fP env, \fBpending_xref\fP node, \fBTextElement\fP contnode)"
.br
.ti -1c
.RI "None \fBsphinx\&.ext\&.intersphinx\&._resolve\&.install_dispatcher\fP (\fBSphinx\fP app, str docname, list[str] source)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
