.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/util/_uri.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/util/_uri.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.util\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.util\&._uri\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBsphinx\&.util\&._uri\&.encode_uri\fP (str uri)"
.br
.ti -1c
.RI "bool \fBsphinx\&.util\&._uri\&.is_url\fP (str url)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
