.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/localtime/_win32.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/localtime/_win32.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbabel\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.localtime\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.localtime\&._win32\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "dict[str, Any] \fBbabel\&.localtime\&._win32\&.valuestodict\fP (key)"
.br
.ti -1c
.RI "str \fBbabel\&.localtime\&._win32\&.get_localzone_name\fP ()"
.br
.ti -1c
.RI "datetime\&.tzinfo \fBbabel\&.localtime\&._win32\&._get_localzone\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbabel\&.localtime\&._win32\&.winreg\fP = None"
.br
.ti -1c
.RI "dict \fBbabel\&.localtime\&._win32\&.tz_names\fP = cast(Dict[str, str], get_global('windows_zone_mapping'))"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
