.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/requests/api.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/requests/api.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrequests\fP"
.br
.ti -1c
.RI "namespace \fBrequests\&.api\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrequests\&.api\&.request\fP (method, url, **kwargs)"
.br
.ti -1c
.RI "\fBrequests\&.api\&.get\fP (url, params=None, **kwargs)"
.br
.ti -1c
.RI "\fBrequests\&.api\&.options\fP (url, **kwargs)"
.br
.ti -1c
.RI "\fBrequests\&.api\&.head\fP (url, **kwargs)"
.br
.ti -1c
.RI "\fBrequests\&.api\&.post\fP (url, data=None, json=None, **kwargs)"
.br
.ti -1c
.RI "\fBrequests\&.api\&.put\fP (url, data=None, **kwargs)"
.br
.ti -1c
.RI "\fBrequests\&.api\&.patch\fP (url, data=None, **kwargs)"
.br
.ti -1c
.RI "\fBrequests\&.api\&.delete\fP (url, **kwargs)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
