.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/snowballstemmer/arabic_stemmer.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/snowballstemmer/arabic_stemmer.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.ArabicStemmer\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab0\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab1\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab2\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab3\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab4\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab5\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab6\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab7\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab8\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab9\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab10\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab11\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab12\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab13\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab14\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab15\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab16\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab17\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab18\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab19\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab20\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab21\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab22\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab23\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab24\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab25\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab26\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab27\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab28\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab29\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab30\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab31\fP"
.br
.ti -1c
.RI "class \fBsnowballstemmer\&.arabic_stemmer\&.lab32\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsnowballstemmer\fP"
.br
.ti -1c
.RI "namespace \fBsnowballstemmer\&.arabic_stemmer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
