.TH "arghlp" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arghlp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'arghlp\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBsynopsys_t\fP \fBsynopsys\fP"
.br
.ti -1c
.RI "struct \fBoptionx\fP * \fBoptions\fP"
.br
.ti -1c
.RI "\fBarghlp_handler\fP \fBah_handler\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBarghlp_handler\fP arghlp::ah_handler"

.SS "struct \fBoptionx\fP * arghlp::options"

.SS "struct \fBsynopsys_t\fP arghlp::synopsys"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
