.TH "/home/umar/Desktop/WorkShop/GLL/libarghlp/arghlp.c" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/libarghlp/arghlp.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <libgen\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'arghlp\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__flags_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBarghlp_context\fP (int ac, char *const *av, const struct \fBarghlp\fP *\fBarghlp\fP, void *ax)"
.br
.ti -1c
.RI "char * \fBoptentry\fP (char *const *av, int ac, int optindex)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fB__usage\fP [\fBUSAGE_BUFF\fP] = {0}"
.br
.RI "Opaque type of flags\&. "
.ti -1c
.RI "char \fB__shopt\fP [\fBMAX_BUFF\fP] ={0}"
.br
.ti -1c
.RI "int \fB__nargp\fP = 0"
.br
.ti -1c
.RI "struct option \fB__optl\fP [\fBMAX_BUFF\fP]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * arghlp_context (int ac, char *const * av, const struct \fBarghlp\fP * arghlp, void * ax)"

.SS "char * optentry (char *const * av, int ac, int optindex)"
looking for equal symbol '='
.PP
--option=argument
.PP
--option =args
.PP
--option= args
.SH "Variable Documentation"
.PP 
.SS "int __nargp = 0"

.SS "struct option __optl[\fBMAX_BUFF\fP]"

.SS "char __shopt[\fBMAX_BUFF\fP] ={0}"

.SS "char __usage[\fBUSAGE_BUFF\fP] = {0}"

.PP
Opaque type of flags\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
