.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/lexers/asm.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/lexers/asm.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.GasLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.ObjdumpLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.DObjdumpLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.CppObjdumpLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.CObjdumpLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.HsailLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.LlvmLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.LlvmMirBodyLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.LlvmMirLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.NasmLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.NasmObjdumpLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.TasmLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.Ca65Lexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.asm\&.Dasm16Lexer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpygments\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.lexers\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.lexers\&.asm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpygments\&.lexers\&.asm\&._objdump_lexer_tokens\fP (asm_lexer)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
