.TH "babel.messages.pofile._NormalizedString" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.messages.pofile._NormalizedString
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, *str args)"
.br
.ti -1c
.RI "None \fBappend\fP (self, str s)"
.br
.ti -1c
.RI "str \fBdenormalize\fP (self)"
.br
.ti -1c
.RI "bool \fB__bool__\fP (self)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "int \fB__cmp__\fP (self, object other)"
.br
.ti -1c
.RI "bool \fB__gt__\fP (self, object other)"
.br
.ti -1c
.RI "bool \fB__lt__\fP (self, object other)"
.br
.ti -1c
.RI "bool \fB__ge__\fP (self, object other)"
.br
.ti -1c
.RI "bool \fB__le__\fP (self, object other)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, object other)"
.br
.ti -1c
.RI "bool \fB__ne__\fP (self, object other)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_strs\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None babel\&.messages\&.pofile\&._NormalizedString\&.__init__ ( self, *str args)"

.SH "Member Function Documentation"
.PP 
.SS " bool babel\&.messages\&.pofile\&._NormalizedString\&.__bool__ ( self)"

.SS " int babel\&.messages\&.pofile\&._NormalizedString\&.__cmp__ ( self, object other)"

.SS " bool babel\&.messages\&.pofile\&._NormalizedString\&.__eq__ ( self, object other)"

.SS " bool babel\&.messages\&.pofile\&._NormalizedString\&.__ge__ ( self, object other)"

.SS " bool babel\&.messages\&.pofile\&._NormalizedString\&.__gt__ ( self, object other)"

.SS " bool babel\&.messages\&.pofile\&._NormalizedString\&.__le__ ( self, object other)"

.SS " bool babel\&.messages\&.pofile\&._NormalizedString\&.__lt__ ( self, object other)"

.SS " bool babel\&.messages\&.pofile\&._NormalizedString\&.__ne__ ( self, object other)"

.SS " str babel\&.messages\&.pofile\&._NormalizedString\&.__repr__ ( self)"

.SS " None babel\&.messages\&.pofile\&._NormalizedString\&.append ( self, str s)"

.SS " str babel\&.messages\&.pofile\&._NormalizedString\&.denormalize ( self)"

.SH "Member Data Documentation"
.PP 
.SS "babel\&.messages\&.pofile\&._NormalizedString\&._strs\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
