.TH "babel.core.UnknownLocaleError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.core.UnknownLocaleError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBidentifier\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBidentifier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Exception thrown when a locale is requested for which no locale data
is available\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None babel\&.core\&.UnknownLocaleError\&.__init__ ( self, str identifier)"

.PP
.nf
Create the exception\&.

:param identifier: the identifier string of the unsupported locale

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "babel\&.core\&.UnknownLocaleError\&.identifier"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
