.TH "babel.plural.PluralRule" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.plural.PluralRule
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, Mapping[str, str]|Iterable[tuple[str, str]] \fBrules\fP)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBPluralRule\fP \fBparse\fP (cls, Mapping[str, str]|Iterable[tuple[str, str]]|\fBPluralRule\fP \fBrules\fP)"
.br
.ti -1c
.RI "Mapping[str, str] \fBrules\fP (self)"
.br
.ti -1c
.RI "frozenset[str] \fBtags\fP (self)"
.br
.ti -1c
.RI "list[tuple[str, Any]] \fB__getstate__\fP (self)"
.br
.ti -1c
.RI "None \fB__setstate__\fP (self, list[tuple[str, Any]] \fBabstract\fP)"
.br
.ti -1c
.RI "str \fB__call__\fP (self, float|decimal\&.Decimal n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBabstract\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_func\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a set of language pluralization rules\&.  The constructor
accepts a list of (tag, expr) tuples or a dict of `CLDR rules`_\&. The
resulting object is callable and accepts one parameter with a positive or
negative number (both integer and float) for the number that indicates the
plural form for a string and returns the tag for the format:

>>> rule = PluralRule({'one': 'n is 1'})
>>> rule(1)
'one'
>>> rule(2)
'other'

Currently the CLDR defines these tags: zero, one, two, few, many and
other where other is an implicit default\&.  Rules should be mutually
exclusive; for a given numeric value, only one rule should apply (i\&.e\&.
the condition should only be true for one of the plural rule elements\&.

\&.\&. _`CLDR rules`: https://www\&.unicode\&.org/reports/tr35/tr35-33/tr35-numbers\&.html#Language_Plural_Rules

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None babel\&.plural\&.PluralRule\&.__init__ ( self, Mapping[str, str] | Iterable[tuple[str, str]] rules)"

.PP
.nf
Initialize the rule instance\&.

:param rules: a list of ``(tag, expr)``) tuples with the rules
              conforming to UTS #35 or a dict with the tags as keys
              and expressions as values\&.
:raise RuleError: if the expression is malformed

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str babel\&.plural\&.PluralRule\&.__call__ ( self, float | decimal\&.Decimal n)"

.SS " list[tuple[str, Any]] babel\&.plural\&.PluralRule\&.__getstate__ ( self)"

.SS " str babel\&.plural\&.PluralRule\&.__repr__ ( self)"

.SS " None babel\&.plural\&.PluralRule\&.__setstate__ ( self, list[tuple[str, Any]] abstract)"

.SS " \fBPluralRule\fP babel\&.plural\&.PluralRule\&.parse ( cls, Mapping[str, str] | Iterable[tuple[str, str]] | \fBPluralRule\fP rules)"

.PP
.nf
Create a `PluralRule` instance for the given rules\&.  If the rules
are a `PluralRule` object, that object is returned\&.

:param rules: the rules as list or dict, or a `PluralRule` object
:raise RuleError: if the expression is malformed

.fi
.PP
 
.SS " Mapping[str, str] babel\&.plural\&.PluralRule\&.rules ( self)"

.PP
.nf
The `PluralRule` as a dict of unicode plural rules\&.

>>> rule = PluralRule({'one': 'n is 1'})
>>> rule\&.rules
{'one': 'n is 1'}

.fi
.PP
 
.SS " frozenset[str] babel\&.plural\&.PluralRule\&.tags ( self)"

.PP
.nf
A set of explicitly defined tags in this rule\&.  The implicit default
``'other'`` rules is not part of this set unless there is an explicit
rule for it\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "babel\&.plural\&.PluralRule\&._func\fC [protected]\fP"

.SS "babel\&.plural\&.PluralRule\&.abstract"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
