.TH "babel.messages.frontend.InitCatalog" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.messages.frontend.InitCatalog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbabel\&.messages\&.frontend\&.CommandMixin\fP\&.
.PP
Inherited by \fBbabel\&.messages\&.setuptools_frontend\&.init_catalog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinitialize_options\fP (self)"
.br
.ti -1c
.RI "\fBfinalize_options\fP (self)"
.br
.ti -1c
.RI "\fBrun\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBbabel\&.messages\&.frontend\&.CommandMixin\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, dist=None)"
.br
.ti -1c
.RI "\fBensure_finalized\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoutput_dir\fP"
.br
.ti -1c
.RI "\fBoutput_file\fP"
.br
.ti -1c
.RI "\fBinput_file\fP"
.br
.ti -1c
.RI "\fBlocale\fP"
.br
.ti -1c
.RI "\fBdomain\fP"
.br
.ti -1c
.RI "\fBno_wrap\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.in -1c

Public Attributes inherited from \fBbabel\&.messages\&.frontend\&.CommandMixin\fP
.in +1c
.ti -1c
.RI "\fBdistribution\fP"
.br
.ti -1c
.RI "\fBverbose\fP"
.br
.ti -1c
.RI "\fBforce\fP"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.ti -1c
.RI "\fBfinalized\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBdescription\fP = 'create a new catalog based on a POT file'"
.br
.ti -1c
.RI "list \fBuser_options\fP"
.br
.ti -1c
.RI "list \fBboolean_options\fP = ['no\-wrap']"
.br
.in -1c

Static Public Attributes inherited from \fBbabel\&.messages\&.frontend\&.CommandMixin\fP
.in +1c
.ti -1c
.RI "\fBas_args\fP = None"
.br
.ti -1c
.RI "tuple \fBmultiple_value_options\fP = ()"
.br
.ti -1c
.RI "tuple \fBboolean_options\fP = ()"
.br
.ti -1c
.RI "dict \fBoption_aliases\fP = {}"
.br
.ti -1c
.RI "dict \fBoption_choices\fP = {}"
.br
.ti -1c
.RI "\fBlog\fP = log"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_locale\fP"
.br
.in -1c

Protected Attributes inherited from \fBbabel\&.messages\&.frontend\&.CommandMixin\fP
.in +1c
.ti -1c
.RI "\fB_dry_run\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "babel\&.messages\&.frontend\&.InitCatalog\&.finalize_options ( self)"

.PP
Reimplemented from \fBbabel\&.messages\&.frontend\&.CommandMixin\fP\&.
.SS "babel\&.messages\&.frontend\&.InitCatalog\&.initialize_options ( self)"

.PP
Reimplemented from \fBbabel\&.messages\&.frontend\&.CommandMixin\fP\&.
.SS "babel\&.messages\&.frontend\&.InitCatalog\&.run ( self)"

.SH "Member Data Documentation"
.PP 
.SS "babel\&.messages\&.frontend\&.InitCatalog\&._locale\fC [protected]\fP"

.SS "list babel\&.messages\&.frontend\&.InitCatalog\&.boolean_options = ['no\-wrap']\fC [static]\fP"

.SS "str babel\&.messages\&.frontend\&.InitCatalog\&.description = 'create a new catalog based on a POT file'\fC [static]\fP"

.SS "babel\&.messages\&.frontend\&.InitCatalog\&.domain"

.SS "babel\&.messages\&.frontend\&.InitCatalog\&.input_file"

.SS "babel\&.messages\&.frontend\&.InitCatalog\&.locale"

.SS "babel\&.messages\&.frontend\&.InitCatalog\&.no_wrap"

.SS "babel\&.messages\&.frontend\&.InitCatalog\&.output_dir"

.SS "babel\&.messages\&.frontend\&.InitCatalog\&.output_file"

.SS "list babel\&.messages\&.frontend\&.InitCatalog\&.user_options\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        ('domain=', 'D',
         "domain of PO file (default 'messages')"),
        ('input\-file=', 'i',
         'name of the input file'),
        ('output\-dir=', 'd',
         'path to output directory'),
        ('output\-file=', 'o',
         "name of the output file (default "
         "'<output_dir>/<locale>/LC_MESSAGES/<domain>\&.po')"),
        ('locale=', 'l',
         'locale for the new localized catalog'),
        ('width=', 'w',
         'set output line width (default 76)'),
        ('no\-wrap', None,
         'do not break long message lines, longer than the output line width, '
         'into several lines'),
    ]
.fi

.SS "babel\&.messages\&.frontend\&.InitCatalog\&.width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
