.TH "babel.messages.frontend" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.messages.frontend
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseError\fP"
.br
.ti -1c
.RI "class \fBCommandLineInterface\fP"
.br
.ti -1c
.RI "class \fBCommandMixin\fP"
.br
.ti -1c
.RI "class \fBCompileCatalog\fP"
.br
.ti -1c
.RI "class \fBConfigurationError\fP"
.br
.ti -1c
.RI "class \fBExtractMessages\fP"
.br
.ti -1c
.RI "class \fBInitCatalog\fP"
.br
.ti -1c
.RI "class \fBOptionError\fP"
.br
.ti -1c
.RI "class \fBSetupError\fP"
.br
.ti -1c
.RI "class \fBUpdateCatalog\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlistify_value\fP (arg, split=None)"
.br
.ti -1c
.RI "\fB_make_directory_filter\fP (ignore_patterns)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.ti -1c
.RI "\fBparse_mapping\fP (fileobj, filename=None)"
.br
.ti -1c
.RI "\fBparse_mapping_cfg\fP (fileobj, filename=None)"
.br
.ti -1c
.RI "\fB_parse_config_object\fP (dict config, *filename='(unknown)')"
.br
.ti -1c
.RI "\fB_parse_mapping_toml\fP (BinaryIO fileobj, str filename='(unknown)', Literal['standalone', 'pyproject\&.toml'] style='standalone')"
.br
.ti -1c
.RI "tuple[int|None, tuple[int|tuple[int, str],\&.\&.\&.]] \fB_parse_spec\fP (str s)"
.br
.ti -1c
.RI "\fBparse_keywords\fP (Iterable[str] strings=())"
.br
.ti -1c
.RI "\fB__getattr__\fP (str name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlog\fP = logging\&.getLogger('babel')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    babel\&.messages\&.frontend
    ~~~~~~~~~~~~~~~~~~~~~~~

    Frontends for the message extraction functionality\&.

    :copyright: (c) 2013-2025 by the Babel Team\&.
    :license: BSD, see LICENSE for more details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "babel\&.messages\&.frontend\&.__getattr__ (str name)"

.SS "babel\&.messages\&.frontend\&._make_directory_filter ( ignore_patterns)\fC [protected]\fP"

.PP
.nf
Build a directory_filter function based on a list of ignore patterns\&.

.fi
.PP
 
.SS "babel\&.messages\&.frontend\&._parse_config_object (dict config, * filename = \fC'(unknown)'\fP)\fC [protected]\fP"

.SS "babel\&.messages\&.frontend\&._parse_mapping_toml (BinaryIO fileobj, str  filename = \fC'(unknown)'\fP, Literal['standalone', 'pyproject\&.toml']  style = \fC'standalone'\fP)\fC [protected]\fP"

.PP
.nf
Parse an extraction method mapping from a binary file-like object\&.

\&.\&. warning: As of this version of Babel, this is a private API subject to changes\&.

:param fileobj: a readable binary file-like object containing the configuration TOML to parse
:param filename: the name of the file being parsed, for error messages
:param style: whether the file is in the style of a `pyproject\&.toml` file, i\&.e\&. whether to look for `tool\&.babel`\&.

.fi
.PP
 
.SS " tuple[int | None, tuple[int | tuple[int, str], \&.\&.\&.]] babel\&.messages\&.frontend\&._parse_spec (str s)\fC [protected]\fP"

.SS "babel\&.messages\&.frontend\&.listify_value ( arg,  split = \fCNone\fP)"

.PP
.nf
Make a list out of an argument\&.

Values from `distutils` argument parsing are always single strings;
values from `optparse` parsing may be lists of strings that may need
to be further split\&.

No matter the input, this function returns a flat list of whitespace-trimmed
strings, with `None` values filtered out\&.

>>> listify_value('foo bar')
['foo', 'bar']
>>> listify_value(['foo bar'])
['foo', 'bar']
>>> listify_value([['foo'], 'bar'])
['foo', 'bar']
>>> listify_value([['foo'], ['bar', None, 'foo']])
['foo', 'bar', 'foo']
>>> listify_value('foo, bar, quux', ',')
['foo', 'bar', 'quux']

:param arg: A string or a list of strings
:param split: The argument to pass to `str\&.split()`\&.
:return:

.fi
.PP
 
.SS "babel\&.messages\&.frontend\&.main (void           )"

.SS "babel\&.messages\&.frontend\&.parse_keywords (Iterable[str]  strings = \fC()\fP)"

.PP
.nf
Parse keywords specifications from the given list of strings\&.

>>> import pprint
>>> keywords = ['_', 'dgettext:2', 'dngettext:2,3', 'pgettext:1c,2',
\&.\&.\&.             'polymorphic:1', 'polymorphic:2,2t', 'polymorphic:3c,3t']
>>> pprint\&.pprint(parse_keywords(keywords))
{'_': None,
 'dgettext': (2,),
 'dngettext': (2, 3),
 'pgettext': ((1, 'c'), 2),
 'polymorphic': {None: (1,), 2: (2,), 3: ((3, 'c'),)}}

The input keywords are in GNU Gettext style; see :doc:`cmdline` for details\&.

The output is a dictionary mapping keyword names to a dictionary of specifications\&.
Keys in this dictionary are numbers of arguments, where ``None`` means that all numbers
of arguments are matched, and a number means only calls with that number of arguments
are matched (which happens when using the 't' specifier)\&. However, as a special
case for backwards compatibility, if the dictionary of specifications would
be ``{None: x}``, i\&.e\&., there is only one specification and it matches all argument
counts, then it is collapsed into just ``x``\&.

A specification is either a tuple or None\&. If a tuple, each element can be either a number
``n``, meaning that the nth argument should be extracted as a message, or the tuple
``(n, 'c')``, meaning that the nth argument should be extracted as context for the
messages\&. A ``None`` specification is equivalent to ``(1,)``, extracting the first
argument\&.

.fi
.PP
 
.SS "babel\&.messages\&.frontend\&.parse_mapping ( fileobj,  filename = \fCNone\fP)"

.SS "babel\&.messages\&.frontend\&.parse_mapping_cfg ( fileobj,  filename = \fCNone\fP)"

.PP
.nf
Parse an extraction method mapping from a file-like object\&.

:param fileobj: a readable file-like object containing the configuration
                text to parse
:param filename: the name of the file being parsed, for error messages

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "babel\&.messages\&.frontend\&.log = logging\&.getLogger('babel')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
