.TH "babel.localedata" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.localedata
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlias\fP"
.br
.ti -1c
.RI "class \fBLocaleDataDict\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str|None \fBnormalize_locale\fP (str name)"
.br
.ti -1c
.RI "str \fBresolve_locale_filename\fP (os\&.PathLike[str]|str name)"
.br
.ti -1c
.RI "bool \fBexists\fP (str name)"
.br
.ti -1c
.RI "list[str] \fBlocale_identifiers\fP ()"
.br
.ti -1c
.RI "bool \fB_is_non_likely_script\fP (str name)"
.br
.ti -1c
.RI "dict[str, Any] \fBload\fP (os\&.PathLike[str]|str name, bool merge_inherited=True)"
.br
.ti -1c
.RI "None \fBmerge\fP (MutableMapping[Any, Any] dict1, Mapping[Any, Any] dict2)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fB_cache\fP = {}"
.br
.ti -1c
.RI "\fB_cache_lock\fP = threading\&.RLock()"
.br
.ti -1c
.RI "\fB_dirname\fP = os\&.path\&.join(os\&.path\&.dirname(__file__), 'locale\-data')"
.br
.ti -1c
.RI "\fB_windows_reserved_name_re\fP = re\&.compile('^(con|prn|aux|nul|com[0\-9]|lpt[0\-9])$', re\&.I)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    babel\&.localedata
    ~~~~~~~~~~~~~~~~

    Low-level locale data access\&.

    :note: The `Locale` class, which uses this module under the hood, provides a
           more convenient interface for accessing the locale data\&.

    :copyright: (c) 2013-2025 by the Babel Team\&.
    :license: BSD, see LICENSE for more details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " bool babel\&.localedata\&._is_non_likely_script (str name)\fC [protected]\fP"

.PP
.nf
Return whether the locale is of the form ``lang_Script``,
and the script is not the likely script for the language\&.

This implements the behavior of the ``nonlikelyScript`` value of the
``localRules`` attribute for parent locales added in CLDR 45\&.

.fi
.PP
 
.SS " bool babel\&.localedata\&.exists (str name)"

.PP
.nf
Check whether locale data is available for the given locale\&.

Returns `True` if it exists, `False` otherwise\&.

:param name: the locale identifier string

.fi
.PP
 
.SS " dict[str, Any] babel\&.localedata\&.load (os\&.PathLike[str] | str name, bool  merge_inherited = \fCTrue\fP)"

.PP
.nf
Load the locale data for the given locale\&.

The locale data is a dictionary that contains much of the data defined by
the Common Locale Data Repository (CLDR)\&. This data is stored as a
collection of pickle files inside the ``babel`` package\&.

>>> d = load('en_US')
>>> d['languages']['sv']
u'Swedish'

Note that the results are cached, and subsequent requests for the same
locale return the same dictionary:

>>> d1 = load('en_US')
>>> d2 = load('en_US')
>>> d1 is d2
True

:param name: the locale identifier string (or 'root')
:param merge_inherited: whether the inherited data should be merged into
                        the data of the requested locale
:raise `IOError`: if no locale data file is found for the given locale
                  identifier, or one of the locales it inherits from

.fi
.PP
 
.SS " list[str] babel\&.localedata\&.locale_identifiers ()"

.PP
.nf
Return a list of all locale identifiers for which locale data is
available\&.

This data is cached after the first invocation\&.
You can clear the cache by calling `locale_identifiers\&.cache_clear()`\&.

\&.\&. versionadded:: 0\&.8\&.1

:return: a list of locale identifiers (strings)

.fi
.PP
 
.SS " None babel\&.localedata\&.merge (MutableMapping[Any, Any] dict1, Mapping[Any, Any] dict2)"

.PP
.nf
Merge the data from `dict2` into the `dict1` dictionary, making copies
of nested dictionaries\&.

>>> d = {1: 'foo', 3: 'baz'}
>>> merge(d, {1: 'Foo', 2: 'Bar'})
>>> sorted(d\&.items())
[(1, 'Foo'), (2, 'Bar'), (3, 'baz')]

:param dict1: the dictionary to merge into
:param dict2: the dictionary containing the data that should be merged

.fi
.PP
 
.SS " str | None babel\&.localedata\&.normalize_locale (str name)"

.PP
.nf
Normalize a locale ID by stripping spaces and apply proper casing\&.

Returns the normalized locale ID string or `None` if the ID is not
recognized\&.

.fi
.PP
 
.SS " str babel\&.localedata\&.resolve_locale_filename (os\&.PathLike[str] | str name)"

.PP
.nf
Resolve a locale identifier to a `\&.dat` path on disk\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict babel\&.localedata\&._cache = {}\fC [protected]\fP"

.SS "babel\&.localedata\&._cache_lock = threading\&.RLock()\fC [protected]\fP"

.SS "babel\&.localedata\&._dirname = os\&.path\&.join(os\&.path\&.dirname(__file__), 'locale\-data')\fC [protected]\fP"

.SS "babel\&.localedata\&._windows_reserved_name_re = re\&.compile('^(con|prn|aux|nul|com[0\-9]|lpt[0\-9])$', re\&.I)\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
