.TH "babel.plural._UnicodeCompiler" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.plural._UnicodeCompiler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbabel\&.plural\&._Compiler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcompile_not\fP (self, relation)"
.br
.ti -1c
.RI "\fBcompile_relation\fP (self, method, expr, range_list, negated=False)"
.br
.in -1c

Public Member Functions inherited from \fBbabel\&.plural\&._Compiler\fP
.in +1c
.ti -1c
.RI "\fBcompile\fP (self, arg)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBcompile_is\fP = \fB_binary_compiler\fP('%s is %s')"
.br
.ti -1c
.RI "\fBcompile_isnot\fP = \fB_binary_compiler\fP('%s is not %s')"
.br
.ti -1c
.RI "\fBcompile_and\fP = \fB_binary_compiler\fP('%s and %s')"
.br
.ti -1c
.RI "\fBcompile_or\fP = \fB_binary_compiler\fP('%s or %s')"
.br
.ti -1c
.RI "\fBcompile_mod\fP = \fB_binary_compiler\fP('%s mod %s')"
.br
.in -1c

Static Public Attributes inherited from \fBbabel\&.plural\&._Compiler\fP
.in +1c
.ti -1c
.RI "str \fBcompile_n\fP = lambda x: 'n'"
.br
.ti -1c
.RI "str \fBcompile_i\fP = lambda x: 'i'"
.br
.ti -1c
.RI "str \fBcompile_v\fP = lambda x: 'v'"
.br
.ti -1c
.RI "str \fBcompile_w\fP = lambda x: 'w'"
.br
.ti -1c
.RI "str \fBcompile_f\fP = lambda x: 'f'"
.br
.ti -1c
.RI "str \fBcompile_t\fP = lambda x: 't'"
.br
.ti -1c
.RI "str \fBcompile_c\fP = lambda x: 'c'"
.br
.ti -1c
.RI "str \fBcompile_e\fP = lambda x: 'e'"
.br
.ti -1c
.RI "str \fBcompile_value\fP = lambda x, v(v)"
.br
.ti -1c
.RI "\fBcompile_and\fP = \fB_binary_compiler\fP('(%s && %s)')"
.br
.ti -1c
.RI "\fBcompile_or\fP = \fB_binary_compiler\fP('(%s || %s)')"
.br
.ti -1c
.RI "\fBcompile_mod\fP = \fB_binary_compiler\fP('(%s %% %s)')"
.br
.ti -1c
.RI "\fBcompile_is\fP = \fB_binary_compiler\fP('(%s == %s)')"
.br
.ti -1c
.RI "\fBcompile_isnot\fP = \fB_binary_compiler\fP('(%s != %s)')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Returns a unicode pluralization rule again\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "babel\&.plural\&._UnicodeCompiler\&.compile_not ( self,  relation)"

.PP
Reimplemented from \fBbabel\&.plural\&._Compiler\fP\&.
.SS "babel\&.plural\&._UnicodeCompiler\&.compile_relation ( self,  method,  expr,  range_list,  negated = \fCFalse\fP)"

.PP
Reimplemented from \fBbabel\&.plural\&._Compiler\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "babel\&.plural\&._UnicodeCompiler\&.compile_and = \fB_binary_compiler\fP('%s and %s')\fC [static]\fP"

.SS "babel\&.plural\&._UnicodeCompiler\&.compile_is = \fB_binary_compiler\fP('%s is %s')\fC [static]\fP"

.SS "babel\&.plural\&._UnicodeCompiler\&.compile_isnot = \fB_binary_compiler\fP('%s is not %s')\fC [static]\fP"

.SS "babel\&.plural\&._UnicodeCompiler\&.compile_mod = \fB_binary_compiler\fP('%s mod %s')\fC [static]\fP"

.SS "babel\&.plural\&._UnicodeCompiler\&.compile_or = \fB_binary_compiler\fP('%s or %s')\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
