.TH "babel.numbers.UnknownCurrencyError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.numbers.UnknownCurrencyError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBidentifier\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBidentifier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Exception thrown when a currency is requested for which no data is available\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None babel\&.numbers\&.UnknownCurrencyError\&.__init__ ( self, str identifier)"

.PP
.nf
Create the exception\&.
:param identifier: the identifier string of the unsupported currency

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "babel\&.numbers\&.UnknownCurrencyError\&.identifier"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
