.TH "babel.dates" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
babel.dates
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDateTimeFormat\fP"
.br
.ti -1c
.RI "class \fBDateTimePattern\fP"
.br
.ti -1c
.RI "class \fBParseError\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "datetime\&.datetime \fB_localize\fP (datetime\&.tzinfo tz, datetime\&.datetime dt)"
.br
.ti -1c
.RI "tuple[datetime\&.datetime|None, datetime\&.tzinfo] \fB_get_dt_and_tzinfo\fP (\fB_DtOrTzinfo\fP dt_or_tzinfo)"
.br
.ti -1c
.RI "str \fB_get_tz_name\fP (\fB_DtOrTzinfo\fP dt_or_tzinfo)"
.br
.ti -1c
.RI "datetime\&.datetime \fB_get_datetime\fP (\fB_Instant\fP instant)"
.br
.ti -1c
.RI "datetime\&.datetime \fB_ensure_datetime_tzinfo\fP (datetime\&.datetime dt, datetime\&.tzinfo|None tzinfo=None)"
.br
.ti -1c
.RI "datetime\&.time \fB_get_time\fP (datetime\&.time|datetime\&.datetime|None time, datetime\&.tzinfo|None tzinfo=None)"
.br
.ti -1c
.RI "datetime\&.tzinfo \fBget_timezone\fP (str|datetime\&.tzinfo|None zone=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBget_period_names\fP (Literal['abbreviated', 'narrow', 'wide'] width='wide', \fB_Context\fP context='stand\-alone', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBget_day_names\fP (Literal['abbreviated', 'narrow', 'short', 'wide'] width='wide', \fB_Context\fP context='format', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBget_month_names\fP (Literal['abbreviated', 'narrow', 'wide'] width='wide', \fB_Context\fP context='format', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBget_quarter_names\fP (Literal['abbreviated', 'narrow', 'wide'] width='wide', \fB_Context\fP context='format', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBget_era_names\fP (Literal['abbreviated', 'narrow', 'wide'] width='wide', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBget_date_format\fP (\fB_PredefinedTimeFormat\fP format='medium', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBget_datetime_format\fP (\fB_PredefinedTimeFormat\fP format='medium', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBget_time_format\fP (\fB_PredefinedTimeFormat\fP format='medium', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBget_timezone_gmt\fP (\fB_Instant\fP datetime=None, Literal['long', 'short', 'iso8601', 'iso8601_short'] width='long', \fBLocale\fP|str|None locale=None, bool return_z=False)"
.br
.ti -1c
.RI "str \fBget_timezone_location\fP (\fB_DtOrTzinfo\fP dt_or_tzinfo=None, \fBLocale\fP|str|None locale=None, bool return_city=False)"
.br
.ti -1c
.RI "str \fBget_timezone_name\fP (\fB_DtOrTzinfo\fP dt_or_tzinfo=None, Literal['long', 'short'] width='long', bool uncommon=False, \fBLocale\fP|str|None locale=None, Literal['generic', 'daylight', 'standard']|None zone_variant=None, bool return_zone=False)"
.br
.ti -1c
.RI "str \fBformat_date\fP (datetime\&.date|None date=None, \fB_PredefinedTimeFormat\fP|str format='medium', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBformat_datetime\fP (\fB_Instant\fP datetime=None, \fB_PredefinedTimeFormat\fP|str format='medium', datetime\&.tzinfo|None tzinfo=None, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBformat_time\fP (datetime\&.time|datetime\&.datetime|float|None time=None, \fB_PredefinedTimeFormat\fP|str format='medium', datetime\&.tzinfo|None tzinfo=None, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBformat_skeleton\fP (str skeleton, \fB_Instant\fP datetime=None, datetime\&.tzinfo|None tzinfo=None, bool fuzzy=True, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBformat_timedelta\fP (datetime\&.timedelta|int delta, Literal['year', 'month', 'week', 'day', 'hour', 'minute', 'second'] granularity='second', float threshold=\&.85, bool add_direction=False, Literal['narrow', 'short', 'medium', 'long'] format='long', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fB_format_fallback_interval\fP (\fB_Instant\fP start, \fB_Instant\fP end, str|None skeleton, datetime\&.tzinfo|None tzinfo, \fBLocale\fP locale)"
.br
.ti -1c
.RI "str \fBformat_interval\fP (\fB_Instant\fP start, \fB_Instant\fP end, str|None skeleton=None, datetime\&.tzinfo|None tzinfo=None, bool fuzzy=True, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBget_period_id\fP (\fB_Instant\fP time, datetime\&.tzinfo|None tzinfo=None, Literal['selection']|None type=None, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "datetime\&.date \fBparse_date\fP (str string, \fBLocale\fP|str|None locale=None, \fB_PredefinedTimeFormat\fP|str format='medium')"
.br
.ti -1c
.RI "datetime\&.time \fBparse_time\fP (str string, \fBLocale\fP|str|None locale=None, \fB_PredefinedTimeFormat\fP|str format='medium')"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBparse_pattern\fP (str|\fBDateTimePattern\fP pattern)"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fB_cached_parse_pattern\fP (str pattern)"
.br
.ti -1c
.RI "list[tuple[str, str|tuple[str, int]]] \fBtokenize_pattern\fP (str pattern)"
.br
.ti -1c
.RI "str \fBuntokenize_pattern\fP (Iterable[tuple[str, str|tuple[str, int]]] tokens)"
.br
.ti -1c
.RI "list[str] \fBsplit_interval_pattern\fP (str pattern)"
.br
.ti -1c
.RI "str|None \fBmatch_skeleton\fP (str skeleton, Iterable[str] options, bool allow_different_fields=False)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpytz\fP = None"
.br
.ti -1c
.RI "TypeAlias \fB_Instant\fP = datetime\&.date | datetime\&.time | float | None"
.br
.ti -1c
.RI "TypeAlias \fB_PredefinedTimeFormat\fP = Literal['full', 'long', 'medium', 'short']"
.br
.ti -1c
.RI "TypeAlias \fB_Context\fP = Literal['format', 'stand\-alone']"
.br
.ti -1c
.RI "TypeAlias \fB_DtOrTzinfo\fP = datetime\&.datetime | datetime\&.tzinfo | str | int | datetime\&.time | None"
.br
.ti -1c
.RI "str \fBNO_INHERITANCE_MARKER\fP = '\\u2205\\u2205\\u2205'"
.br
.ti -1c
.RI "\fBUTC\fP = datetime\&.timezone\&.utc"
.br
.ti -1c
.RI "\fBLOCALTZ\fP = localtime\&.LOCALTZ"
.br
.ti -1c
.RI "\fBLC_TIME\fP = default_locale('LC_TIME')"
.br
.ti -1c
.RI "tuple \fBTIMEDELTA_UNITS\fP"
.br
.ti -1c
.RI "str \fBPATTERN_CHAR_ORDER\fP = 'GyYuUQqMLlwWdDFgEecabBChHKkjJmsSAzZOvVXx'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    babel\&.dates
    ~~~~~~~~~~~

    Locale dependent formatting and parsing of dates and times\&.

    The default locale for the functions in this module is determined by the
    following environment variables, in that order:

     * ``LC_TIME``,
     * ``LC_ALL``, and
     * ``LANG``

    :copyright: (c) 2013-2025 by the Babel Team\&.
    :license: BSD, see LICENSE for more details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fBDateTimePattern\fP babel\&.dates\&._cached_parse_pattern (str pattern)\fC [protected]\fP"

.SS " datetime\&.datetime babel\&.dates\&._ensure_datetime_tzinfo (datetime\&.datetime dt, datetime\&.tzinfo | None  tzinfo = \fCNone\fP)\fC [protected]\fP"

.PP
.nf
Ensure the datetime passed has an attached tzinfo\&.

If the datetime is tz-naive to begin with, UTC is attached\&.

If a tzinfo is passed in, the datetime is normalized to that timezone\&.

>>> from datetime import datetime
>>> _get_tz_name(_ensure_datetime_tzinfo(datetime(2015, 1, 1)))
'UTC'

>>> tz = get_timezone('Europe/Stockholm')
>>> _ensure_datetime_tzinfo(datetime(2015, 1, 1, 13, 15, tzinfo=UTC), tzinfo=tz)\&.hour
14

:param datetime: Datetime to augment\&.
:param tzinfo: optional tzinfo
:return: datetime with tzinfo
:rtype: datetime

.fi
.PP
 
.SS " str babel\&.dates\&._format_fallback_interval (\fB_Instant\fP start, \fB_Instant\fP end, str | None skeleton, datetime\&.tzinfo | None tzinfo, \fBLocale\fP locale)\fC [protected]\fP"

.SS " datetime\&.datetime babel\&.dates\&._get_datetime (\fB_Instant\fP instant)\fC [protected]\fP"

.PP
.nf
Get a datetime out of an 'instant' (date, time, datetime, number)\&.

\&.\&. warning:: The return values of this function may depend on the system clock\&.

If the instant is None, the current moment is used\&.
If the instant is a time, it's augmented with today's date\&.

Dates are converted to naive datetimes with midnight as the time component\&.

>>> from datetime import date, datetime
>>> _get_datetime(date(2015, 1, 1))
datetime\&.datetime(2015, 1, 1, 0, 0)

UNIX timestamps are converted to datetimes\&.

>>> _get_datetime(1400000000)
datetime\&.datetime(2014, 5, 13, 16, 53, 20)

Other values are passed through as-is\&.

>>> x = datetime(2015, 1, 1)
>>> _get_datetime(x) is x
True

:param instant: date, time, datetime, integer, float or None
:type instant: date|time|datetime|int|float|None
:return: a datetime
:rtype: datetime

.fi
.PP
 
.SS " tuple[datetime\&.datetime | None, datetime\&.tzinfo] babel\&.dates\&._get_dt_and_tzinfo (\fB_DtOrTzinfo\fP dt_or_tzinfo)\fC [protected]\fP"

.PP
.nf
Parse a `dt_or_tzinfo` value into a datetime and a tzinfo\&.

See the docs for this function's callers for semantics\&.

:rtype: tuple[datetime, tzinfo]

.fi
.PP
 
.SS " datetime\&.time babel\&.dates\&._get_time (datetime\&.time | datetime\&.datetime | None time, datetime\&.tzinfo | None  tzinfo = \fCNone\fP)\fC [protected]\fP"

.PP
.nf
Get a timezoned time from a given instant\&.

\&.\&. warning:: The return values of this function may depend on the system clock\&.

:param time: time, datetime or None
:rtype: time

.fi
.PP
 
.SS " str babel\&.dates\&._get_tz_name (\fB_DtOrTzinfo\fP dt_or_tzinfo)\fC [protected]\fP"

.PP
.nf
Get the timezone name out of a time, datetime, or tzinfo object\&.

:rtype: str

.fi
.PP
 
.SS " datetime\&.datetime babel\&.dates\&._localize (datetime\&.tzinfo tz, datetime\&.datetime dt)\fC [protected]\fP"

.SS " str babel\&.dates\&.format_date (datetime\&.date | None  date = \fCNone\fP, \fB_PredefinedTimeFormat\fP | str  format = \fC'medium'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return a date formatted according to the given pattern\&.

>>> from datetime import date
>>> d = date(2007, 4, 1)
>>> format_date(d, locale='en_US')
u'Apr 1, 2007'
>>> format_date(d, format='full', locale='de_DE')
u'Sonntag, 1\&. April 2007'

If you don't want to use the locale default formats, you can specify a
custom date pattern:

>>> format_date(d, 'EEE, MMM d, ''yy', locale='en')
u'Sun, Apr 1, '07'

:param date: the ``date`` or ``datetime`` object; if `None`, the current
             date is used
:param format: one of 'full', 'long', 'medium', or 'short', or a custom
               date/time pattern
:param locale: a `Locale` object or a locale identifier\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " str babel\&.dates\&.format_datetime (\fB_Instant\fP  datetime = \fCNone\fP, \fB_PredefinedTimeFormat\fP | str  format = \fC'medium'\fP, datetime\&.tzinfo | None  tzinfo = \fCNone\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return a date formatted according to the given pattern\&.

>>> from datetime import datetime
>>> dt = datetime(2007, 4, 1, 15, 30)
>>> format_datetime(dt, locale='en_US')
u'Apr 1, 2007, 3:30:00\\u202fPM'

For any pattern requiring the display of the timezone:

>>> format_datetime(dt, 'full', tzinfo=get_timezone('Europe/Paris'),
\&.\&.\&.                 locale='fr_FR')
'dimanche 1 avril 2007, 17:30:00 heure d’été d’Europe centrale'
>>> format_datetime(dt, 'yyyy\&.MM\&.dd G 'at' HH:mm:ss zzz',
\&.\&.\&.                 tzinfo=get_timezone('US/Eastern'), locale='en')
u'2007\&.04\&.01 AD at 11:30:00 EDT'

:param datetime: the `datetime` object; if `None`, the current date and
                 time is used
:param format: one of 'full', 'long', 'medium', or 'short', or a custom
               date/time pattern
:param tzinfo: the timezone to apply to the time for display
:param locale: a `Locale` object or a locale identifier\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " str babel\&.dates\&.format_interval (\fB_Instant\fP start, \fB_Instant\fP end, str | None  skeleton = \fCNone\fP, datetime\&.tzinfo | None  tzinfo = \fCNone\fP, bool  fuzzy = \fCTrue\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Format an interval between two instants according to the locale's rules\&.

>>> from datetime import date, time
>>> format_interval(date(2016, 1, 15), date(2016, 1, 17), 'yMd', locale='fi')
u'15\&.\\u201317\&.1\&.2016'

>>> format_interval(time(12, 12), time(16, 16), 'Hm', locale='en_GB')
'12:12\\u201316:16'

>>> format_interval(time(5, 12), time(16, 16), 'hm', locale='en_US')
'5:12\\u202fAM\\u2009–\\u20094:16\\u202fPM'

>>> format_interval(time(16, 18), time(16, 24), 'Hm', locale='it')
'16:18\\u201316:24'

If the start instant equals the end instant, the interval is formatted like the instant\&.

>>> format_interval(time(16, 18), time(16, 18), 'Hm', locale='it')
'16:18'

Unknown skeletons fall back to 'default' formatting\&.

>>> format_interval(date(2015, 1, 1), date(2017, 1, 1), 'wzq', locale='ja')
'2015/01/01\\uff5e2017/01/01'

>>> format_interval(time(16, 18), time(16, 24), 'xxx', locale='ja')
'16:18:00\\uff5e16:24:00'

>>> format_interval(date(2016, 1, 15), date(2016, 1, 17), 'xxx', locale='de')
'15\&.01\&.2016\\u2009–\\u200917\&.01\&.2016'

:param start: First instant (datetime/date/time)
:param end: Second instant (datetime/date/time)
:param skeleton: The 'skeleton format' to use for formatting\&.
:param tzinfo: tzinfo to use (if none is already attached)
:param fuzzy: If the skeleton is not found, allow choosing a skeleton that's
              close enough to it\&.
:param locale: A locale object or identifier\&. Defaults to the system time locale\&.
:return: Formatted interval

.fi
.PP
 
.SS " str babel\&.dates\&.format_skeleton (str skeleton, \fB_Instant\fP  datetime = \fCNone\fP, datetime\&.tzinfo | None  tzinfo = \fCNone\fP, bool  fuzzy = \fCTrue\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return a time and/or date formatted according to the given pattern\&.

The skeletons are defined in the CLDR data and provide more flexibility
than the simple short/long/medium formats, but are a bit harder to use\&.
The are defined using the date/time symbols without order or punctuation
and map to a suitable format for the given locale\&.

>>> from datetime import datetime
>>> t = datetime(2007, 4, 1, 15, 30)
>>> format_skeleton('MMMEd', t, locale='fr')
u'dim\&. 1 avr\&.'
>>> format_skeleton('MMMEd', t, locale='en')
u'Sun, Apr 1'
>>> format_skeleton('yMMd', t, locale='fi')  # yMMd is not in the Finnish locale; yMd gets used
u'1\&.4\&.2007'
>>> format_skeleton('yMMd', t, fuzzy=False, locale='fi')  # yMMd is not in the Finnish locale, an error is thrown
Traceback (most recent call last):
    \&.\&.\&.
KeyError: yMMd
>>> format_skeleton('GH', t, fuzzy=True, locale='fi_FI')  # GH is not in the Finnish locale and there is no close match, an error is thrown
Traceback (most recent call last):
    \&.\&.\&.
KeyError: None

After the skeleton is resolved to a pattern `format_datetime` is called so
all timezone processing etc is the same as for that\&.

:param skeleton: A date time skeleton as defined in the cldr data\&.
:param datetime: the ``time`` or ``datetime`` object; if `None`, the current
             time in UTC is used
:param tzinfo: the time-zone to apply to the time for display
:param fuzzy: If the skeleton is not found, allow choosing a skeleton that's
              close enough to it\&. If there is no close match, a `KeyError`
              is thrown\&.
:param locale: a `Locale` object or a locale identifier\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " str babel\&.dates\&.format_time (datetime\&.time | datetime\&.datetime | float | None  time = \fCNone\fP, \fB_PredefinedTimeFormat\fP | str  format = \fC'medium'\fP, datetime\&.tzinfo | None  tzinfo = \fCNone\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return a time formatted according to the given pattern\&.

>>> from datetime import datetime, time
>>> t = time(15, 30)
>>> format_time(t, locale='en_US')
u'3:30:00\\u202fPM'
>>> format_time(t, format='short', locale='de_DE')
u'15:30'

If you don't want to use the locale default formats, you can specify a
custom time pattern:

>>> format_time(t, 'hh 'o''clock' a', locale='en')
u'03 o'clock PM'

For any pattern requiring the display of the time-zone a
timezone has to be specified explicitly:

>>> t = datetime(2007, 4, 1, 15, 30)
>>> tzinfo = get_timezone('Europe/Paris')
>>> t = _localize(tzinfo, t)
>>> format_time(t, format='full', tzinfo=tzinfo, locale='fr_FR')
'15:30:00 heure d’été d’Europe centrale'
>>> format_time(t, 'hh 'o''clock' a, zzzz', tzinfo=get_timezone('US/Eastern'),
\&.\&.\&.             locale='en')
u'09 o'clock AM, Eastern Daylight Time'

As that example shows, when this function gets passed a
``datetime\&.datetime`` value, the actual time in the formatted string is
adjusted to the timezone specified by the `tzinfo` parameter\&. If the
``datetime`` is 'naive' (i\&.e\&. it has no associated timezone information),
it is assumed to be in UTC\&.

These timezone calculations are **not** performed if the value is of type
``datetime\&.time``, as without date information there's no way to determine
what a given time would translate to in a different timezone without
information about whether daylight savings time is in effect or not\&. This
means that time values are left as-is, and the value of the `tzinfo`
parameter is only used to display the timezone name if needed:

>>> t = time(15, 30)
>>> format_time(t, format='full', tzinfo=get_timezone('Europe/Paris'),
\&.\&.\&.             locale='fr_FR')  # doctest: +SKIP
u'15:30:00 heure normale d\\u2019Europe centrale'
>>> format_time(t, format='full', tzinfo=get_timezone('US/Eastern'),
\&.\&.\&.             locale='en_US')  # doctest: +SKIP
u'3:30:00\\u202fPM Eastern Standard Time'

:param time: the ``time`` or ``datetime`` object; if `None`, the current
     time in UTC is used
:param format: one of 'full', 'long', 'medium', or 'short', or a custom
       date/time pattern
:param tzinfo: the time-zone to apply to the time for display
:param locale: a `Locale` object or a locale identifier\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " str babel\&.dates\&.format_timedelta (datetime\&.timedelta | int delta, Literal['year', 'month', 'week', 'day', 'hour', 'minute', 'second']  granularity = \fC'second'\fP, float  threshold = \fC\&.85\fP, bool  add_direction = \fCFalse\fP, Literal['narrow', 'short', 'medium', 'long']  format = \fC'long'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return a time delta according to the rules of the given locale\&.

>>> from datetime import timedelta
>>> format_timedelta(timedelta(weeks=12), locale='en_US')
u'3 months'
>>> format_timedelta(timedelta(seconds=1), locale='es')
u'1 segundo'

The granularity parameter can be provided to alter the lowest unit
presented, which defaults to a second\&.

>>> format_timedelta(timedelta(hours=3), granularity='day', locale='en_US')
u'1 day'

The threshold parameter can be used to determine at which value the
presentation switches to the next higher unit\&. A higher threshold factor
means the presentation will switch later\&. For example:

>>> format_timedelta(timedelta(hours=23), threshold=0\&.9, locale='en_US')
u'1 day'
>>> format_timedelta(timedelta(hours=23), threshold=1\&.1, locale='en_US')
u'23 hours'

In addition directional information can be provided that informs
the user if the date is in the past or in the future:

>>> format_timedelta(timedelta(hours=1), add_direction=True, locale='en')
u'in 1 hour'
>>> format_timedelta(timedelta(hours=-1), add_direction=True, locale='en')
u'1 hour ago'

The format parameter controls how compact or wide the presentation is:

>>> format_timedelta(timedelta(hours=3), format='short', locale='en')
u'3 hr'
>>> format_timedelta(timedelta(hours=3), format='narrow', locale='en')
u'3h'

:param delta: a ``timedelta`` object representing the time difference to
              format, or the delta in seconds as an `int` value
:param granularity: determines the smallest unit that should be displayed,
                    the value can be one of 'year', 'month', 'week', 'day',
                    'hour', 'minute' or 'second'
:param threshold: factor that determines at which point the presentation
                  switches to the next higher unit
:param add_direction: if this flag is set to `True` the return value will
                      include directional information\&.  For instance a
                      positive timedelta will include the information about
                      it being in the future, a negative will be information
                      about the value being in the past\&.
:param format: the format, can be 'narrow', 'short' or 'long'\&. (
               'medium' is deprecated, currently converted to 'long' to
               maintain compatibility)
:param locale: a `Locale` object or a locale identifier\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " \fBDateTimePattern\fP babel\&.dates\&.get_date_format (\fB_PredefinedTimeFormat\fP  format = \fC'medium'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return the date formatting patterns used by the locale for the specified
format\&.

>>> get_date_format(locale='en_US')
<DateTimePattern u'MMM d, y'>
>>> get_date_format('full', locale='de_DE')
<DateTimePattern u'EEEE, d\&. MMMM y'>

:param format: the format to use, one of 'full', 'long', 'medium', or
               'short'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " \fBDateTimePattern\fP babel\&.dates\&.get_datetime_format (\fB_PredefinedTimeFormat\fP  format = \fC'medium'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return the datetime formatting patterns used by the locale for the
specified format\&.

>>> get_datetime_format(locale='en_US')
u'{1}, {0}'

:param format: the format to use, one of 'full', 'long', 'medium', or
               'short'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " \fBLocaleDataDict\fP babel\&.dates\&.get_day_names (Literal['abbreviated', 'narrow', 'short', 'wide']  width = \fC'wide'\fP, \fB_Context\fP  context = \fC'format'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return the day names used by the locale for the specified format\&.

>>> get_day_names('wide', locale='en_US')[1]
u'Tuesday'
>>> get_day_names('short', locale='en_US')[1]
u'Tu'
>>> get_day_names('abbreviated', locale='es')[1]
u'mar'
>>> get_day_names('narrow', context='stand-alone', locale='de_DE')[1]
u'D'

:param width: the width to use, one of 'wide', 'abbreviated', 'short' or 'narrow'
:param context: the context, either 'format' or 'stand-alone'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " \fBLocaleDataDict\fP babel\&.dates\&.get_era_names (Literal['abbreviated', 'narrow', 'wide']  width = \fC'wide'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return the era names used by the locale for the specified format\&.

>>> get_era_names('wide', locale='en_US')[1]
u'Anno Domini'
>>> get_era_names('abbreviated', locale='de_DE')[1]
u'n\&. Chr\&.'

:param width: the width to use, either 'wide', 'abbreviated', or 'narrow'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " \fBLocaleDataDict\fP babel\&.dates\&.get_month_names (Literal['abbreviated', 'narrow', 'wide']  width = \fC'wide'\fP, \fB_Context\fP  context = \fC'format'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return the month names used by the locale for the specified format\&.

>>> get_month_names('wide', locale='en_US')[1]
u'January'
>>> get_month_names('abbreviated', locale='es')[1]
u'ene'
>>> get_month_names('narrow', context='stand-alone', locale='de_DE')[1]
u'J'

:param width: the width to use, one of 'wide', 'abbreviated', or 'narrow'
:param context: the context, either 'format' or 'stand-alone'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " str babel\&.dates\&.get_period_id (\fB_Instant\fP time, datetime\&.tzinfo | None  tzinfo = \fCNone\fP, Literal['selection'] | None  type = \fCNone\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Get the day period ID for a given time\&.

This ID can be used as a key for the period name dictionary\&.

>>> from datetime import time
>>> get_period_names(locale='de')[get_period_id(time(7, 42), locale='de')]
u'Morgen'

>>> get_period_id(time(0), locale='en_US')
u'midnight'

>>> get_period_id(time(0), type='selection', locale='en_US')
u'night1'

:param time: The time to inspect\&.
:param tzinfo: The timezone for the time\&. See ``format_time``\&.
:param type: The period type to use\&. Either 'selection' or None\&.
             The selection type is used for selecting among phrases such as
             “Your email arrived yesterday evening” or “Your email arrived last night”\&.
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.
:return: period ID\&. Something is always returned -- even if it's just 'am' or 'pm'\&.

.fi
.PP
 
.SS " \fBLocaleDataDict\fP babel\&.dates\&.get_period_names (Literal['abbreviated', 'narrow', 'wide']  width = \fC'wide'\fP, \fB_Context\fP  context = \fC'stand\-alone'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return the names for day periods (AM/PM) used by the locale\&.

>>> get_period_names(locale='en_US')['am']
u'AM'

:param width: the width to use, one of 'abbreviated', 'narrow', or 'wide'
:param context: the context, either 'format' or 'stand-alone'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " \fBLocaleDataDict\fP babel\&.dates\&.get_quarter_names (Literal['abbreviated', 'narrow', 'wide']  width = \fC'wide'\fP, \fB_Context\fP  context = \fC'format'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return the quarter names used by the locale for the specified format\&.

>>> get_quarter_names('wide', locale='en_US')[1]
u'1st quarter'
>>> get_quarter_names('abbreviated', locale='de_DE')[1]
u'Q1'
>>> get_quarter_names('narrow', locale='de_DE')[1]
u'1'

:param width: the width to use, one of 'wide', 'abbreviated', or 'narrow'
:param context: the context, either 'format' or 'stand-alone'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " \fBDateTimePattern\fP babel\&.dates\&.get_time_format (\fB_PredefinedTimeFormat\fP  format = \fC'medium'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP)"

.PP
.nf
Return the time formatting patterns used by the locale for the specified
format\&.

>>> get_time_format(locale='en_US')
<DateTimePattern u'h:mm:ss\\u202fa'>
>>> get_time_format('full', locale='de_DE')
<DateTimePattern u'HH:mm:ss zzzz'>

:param format: the format to use, one of 'full', 'long', 'medium', or
               'short'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.

.fi
.PP
 
.SS " datetime\&.tzinfo babel\&.dates\&.get_timezone (str | datetime\&.tzinfo | None  zone = \fCNone\fP)"

.PP
.nf
Looks up a timezone by name and returns it\&.  The timezone object
returned comes from ``pytz`` or ``zoneinfo``, whichever is available\&.
It corresponds to the `tzinfo` interface and can be used with all of
the functions of Babel that operate with dates\&.

If a timezone is not known a :exc:`LookupError` is raised\&.  If `zone`
is ``None`` a local zone object is returned\&.

:param zone: the name of the timezone to look up\&.  If a timezone object
             itself is passed in, it's returned unchanged\&.

.fi
.PP
 
.SS " str babel\&.dates\&.get_timezone_gmt (\fB_Instant\fP  datetime = \fCNone\fP, Literal['long', 'short', 'iso8601', 'iso8601_short']  width = \fC'long'\fP, \fBLocale\fP | str | None  locale = \fCNone\fP, bool  return_z = \fCFalse\fP)"

.PP
.nf
Return the timezone associated with the given `datetime` object formatted
as string indicating the offset from GMT\&.

>>> from datetime import datetime
>>> dt = datetime(2007, 4, 1, 15, 30)
>>> get_timezone_gmt(dt, locale='en')
u'GMT+00:00'
>>> get_timezone_gmt(dt, locale='en', return_z=True)
'Z'
>>> get_timezone_gmt(dt, locale='en', width='iso8601_short')
u'+00'
>>> tz = get_timezone('America/Los_Angeles')
>>> dt = _localize(tz, datetime(2007, 4, 1, 15, 30))
>>> get_timezone_gmt(dt, locale='en')
u'GMT-07:00'
>>> get_timezone_gmt(dt, 'short', locale='en')
u'-0700'
>>> get_timezone_gmt(dt, locale='en', width='iso8601_short')
u'-07'

The long format depends on the locale, for example in France the acronym
UTC string is used instead of GMT:

>>> get_timezone_gmt(dt, 'long', locale='fr_FR')
u'UTC-07:00'

\&.\&. versionadded:: 0\&.9

:param datetime: the ``datetime`` object; if `None`, the current date and
                 time in UTC is used
:param width: either 'long' or 'short' or 'iso8601' or 'iso8601_short'
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.
:param return_z: True or False; Function returns indicator 'Z'
                 when local time offset is 0

.fi
.PP
 
.SS " str babel\&.dates\&.get_timezone_location (\fB_DtOrTzinfo\fP  dt_or_tzinfo = \fCNone\fP, \fBLocale\fP | str | None  locale = \fCNone\fP, bool  return_city = \fCFalse\fP)"

.PP
.nf
Return a representation of the given timezone using 'location format'\&.

The result depends on both the local display name of the country and the
city associated with the time zone:

>>> tz = get_timezone('America/St_Johns')
>>> print(get_timezone_location(tz, locale='de_DE'))
Kanada (St\&. John’s) (Ortszeit)
>>> print(get_timezone_location(tz, locale='en'))
Canada (St\&. John’s) Time
>>> print(get_timezone_location(tz, locale='en', return_city=True))
St\&. John’s
>>> tz = get_timezone('America/Mexico_City')
>>> get_timezone_location(tz, locale='de_DE')
u'Mexiko (Mexiko-Stadt) (Ortszeit)'

If the timezone is associated with a country that uses only a single
timezone, just the localized country name is returned:

>>> tz = get_timezone('Europe/Berlin')
>>> get_timezone_name(tz, locale='de_DE')
u'Mitteleurop\\\\xe4ische Zeit'

\&.\&. versionadded:: 0\&.9

:param dt_or_tzinfo: the ``datetime`` or ``tzinfo`` object that determines
                     the timezone; if `None`, the current date and time in
                     UTC is assumed
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.
:param return_city: True or False, if True then return exemplar city (location)
                    for the time zone
:return: the localized timezone name using location format
.fi
.PP
 
.SS " str babel\&.dates\&.get_timezone_name (\fB_DtOrTzinfo\fP  dt_or_tzinfo = \fCNone\fP, Literal['long', 'short']  width = \fC'long'\fP, bool  uncommon = \fCFalse\fP, \fBLocale\fP | str | None  locale = \fCNone\fP, Literal['generic', 'daylight', 'standard'] | None  zone_variant = \fCNone\fP, bool  return_zone = \fCFalse\fP)"

.PP
.nf
Return the localized display name for the given timezone\&. The timezone
may be specified using a ``datetime`` or `tzinfo` object\&.

>>> from datetime import time
>>> dt = time(15, 30, tzinfo=get_timezone('America/Los_Angeles'))
>>> get_timezone_name(dt, locale='en_US')  # doctest: +SKIP
u'Pacific Standard Time'
>>> get_timezone_name(dt, locale='en_US', return_zone=True)
'America/Los_Angeles'
>>> get_timezone_name(dt, width='short', locale='en_US')  # doctest: +SKIP
u'PST'

If this function gets passed only a `tzinfo` object and no concrete
`datetime`,  the returned display name is independent of daylight savings
time\&. This can be used for example for selecting timezones, or to set the
time of events that recur across DST changes:

>>> tz = get_timezone('America/Los_Angeles')
>>> get_timezone_name(tz, locale='en_US')
u'Pacific Time'
>>> get_timezone_name(tz, 'short', locale='en_US')
u'PT'

If no localized display name for the timezone is available, and the timezone
is associated with a country that uses only a single timezone, the name of
that country is returned, formatted according to the locale:

>>> tz = get_timezone('Europe/Berlin')
>>> get_timezone_name(tz, locale='de_DE')
u'Mitteleurop\\xe4ische Zeit'
>>> get_timezone_name(tz, locale='pt_BR')
u'Hor\\xe1rio da Europa Central'

On the other hand, if the country uses multiple timezones, the city is also
included in the representation:

>>> tz = get_timezone('America/St_Johns')
>>> get_timezone_name(tz, locale='de_DE')
u'Neufundland-Zeit'

Note that short format is currently not supported for all timezones and
all locales\&.  This is partially because not every timezone has a short
code in every locale\&.  In that case it currently falls back to the long
format\&.

For more information see `LDML Appendix J: Time Zone Display Names
<https://www\&.unicode\&.org/reports/tr35/#Time_Zone_Fallback>`_

\&.\&. versionadded:: 0\&.9

\&.\&. versionchanged:: 1\&.0
   Added `zone_variant` support\&.

:param dt_or_tzinfo: the ``datetime`` or ``tzinfo`` object that determines
                     the timezone; if a ``tzinfo`` object is used, the
                     resulting display name will be generic, i\&.e\&.
                     independent of daylight savings time; if `None`, the
                     current date in UTC is assumed
:param width: either 'long' or 'short'
:param uncommon: deprecated and ignored
:param zone_variant: defines the zone variation to return\&.  By default the
                       variation is defined from the datetime object
                       passed in\&.  If no datetime object is passed in, the
                       ``'generic'`` variation is assumed\&.  The following
                       values are valid: ``'generic'``, ``'daylight'`` and
                       ``'standard'``\&.
:param locale: the `Locale` object, or a locale string\&. Defaults to the system time locale\&.
:param return_zone: True or False\&. If true then function
                    returns long time zone ID

.fi
.PP
 
.SS " str | None babel\&.dates\&.match_skeleton (str skeleton, Iterable[str] options, bool  allow_different_fields = \fCFalse\fP)"

.PP
.nf
Find the closest match for the given datetime skeleton among the options given\&.

This uses the rules outlined in the TR35 document\&.

>>> match_skeleton('yMMd', ('yMd', 'yMMMd'))
'yMd'

>>> match_skeleton('yMMd', ('jyMMd',), allow_different_fields=True)
'jyMMd'

>>> match_skeleton('yMMd', ('qyMMd',), allow_different_fields=False)

>>> match_skeleton('hmz', ('hmv',))
'hmv'

:param skeleton: The skeleton to match
:type skeleton: str
:param options: An iterable of other skeletons to match against
:type options: Iterable[str]
:param allow_different_fields: Whether to allow a match that uses different fields
                               than the skeleton requested\&.
:type allow_different_fields: bool

:return: The closest skeleton match, or if no match was found, None\&.
:rtype: str|None

.fi
.PP
 
.SS " datetime\&.date babel\&.dates\&.parse_date (str string, \fBLocale\fP | str | None  locale = \fCNone\fP, \fB_PredefinedTimeFormat\fP | str  format = \fC'medium'\fP)"

.PP
.nf
Parse a date from a string\&.

If an explicit format is provided, it is used to parse the date\&.

>>> parse_date('01\&.04\&.2004', format='dd\&.MM\&.yyyy')
datetime\&.date(2004, 4, 1)

If no format is given, or if it is one of 'full', 'long', 'medium',
or 'short', the function first tries to interpret the string as
ISO-8601 date format and then uses the date format for the locale
as a hint to determine the order in which the date fields appear in
the string\&.

>>> parse_date('4/1/04', locale='en_US')
datetime\&.date(2004, 4, 1)
>>> parse_date('01\&.04\&.2004', locale='de_DE')
datetime\&.date(2004, 4, 1)
>>> parse_date('2004-04-01', locale='en_US')
datetime\&.date(2004, 4, 1)
>>> parse_date('2004-04-01', locale='de_DE')
datetime\&.date(2004, 4, 1)
>>> parse_date('01\&.04\&.04', locale='de_DE', format='short')
datetime\&.date(2004, 4, 1)

:param string: the string containing the date
:param locale: a `Locale` object or a locale identifier
:param locale: a `Locale` object or a locale identifier\&. Defaults to the system time locale\&.
:param format: the format to use, either an explicit date format,
               or one of 'full', 'long', 'medium', or 'short'
               (see ``get_time_format``)

.fi
.PP
 
.SS " \fBDateTimePattern\fP babel\&.dates\&.parse_pattern (str | \fBDateTimePattern\fP pattern)"

.PP
.nf
Parse date, time, and datetime format patterns\&.

>>> parse_pattern('MMMMd')\&.format
u'%(MMMM)s%(d)s'
>>> parse_pattern('MMM d, yyyy')\&.format
u'%(MMM)s %(d)s, %(yyyy)s'

Pattern can contain literal strings in single quotes:

>>> parse_pattern('H:mm' Uhr 'z')\&.format
u'%(H)s:%(mm)s Uhr %(z)s'

An actual single quote can be used by using two adjacent single quote
characters:

>>> parse_pattern('hh' o''clock'')\&.format
u'%(hh)s o'clock'

:param pattern: the formatting pattern to parse

.fi
.PP
 
.SS " datetime\&.time babel\&.dates\&.parse_time (str string, \fBLocale\fP | str | None  locale = \fCNone\fP, \fB_PredefinedTimeFormat\fP | str  format = \fC'medium'\fP)"

.PP
.nf
Parse a time from a string\&.

This function uses the time format for the locale as a hint to determine
the order in which the time fields appear in the string\&.

If an explicit format is provided, the function will use it to parse
the time instead\&.

>>> parse_time('15:30:00', locale='en_US')
datetime\&.time(15, 30)
>>> parse_time('15:30:00', format='H:mm:ss')
datetime\&.time(15, 30)

:param string: the string containing the time
:param locale: a `Locale` object or a locale identifier\&. Defaults to the system time locale\&.
:param format: the format to use, either an explicit time format,
               or one of 'full', 'long', 'medium', or 'short'
               (see ``get_time_format``)
:return: the parsed time
:rtype: `time`

.fi
.PP
 
.SS " list[str] babel\&.dates\&.split_interval_pattern (str pattern)"

.PP
.nf
Split an interval-describing datetime pattern into multiple pieces\&.

> The pattern is then designed to be broken up into two pieces by determining the first repeating field\&.
- https://www\&.unicode\&.org/reports/tr35/tr35-dates\&.html#intervalFormats

>>> split_interval_pattern(u'E d\&.M\&. \\u2013 E d\&.M\&.')
[u'E d\&.M\&. \\u2013 ', 'E d\&.M\&.']
>>> split_interval_pattern('Y 'text' Y 'more text'')
['Y 'text '', 'Y 'more text'']
>>> split_interval_pattern(u'E, MMM d \\u2013 E')
[u'E, MMM d \\u2013 ', u'E']
>>> split_interval_pattern('MMM d')
['MMM d']
>>> split_interval_pattern('y G')
['y G']
>>> split_interval_pattern(u'MMM d \\u2013 d')
[u'MMM d \\u2013 ', u'd']

:param pattern: Interval pattern string
:return: list of 'subpatterns'

.fi
.PP
 
.SS " list[tuple[str, str | tuple[str, int]]] babel\&.dates\&.tokenize_pattern (str pattern)"

.PP
.nf
Tokenize date format patterns\&.

Returns a list of (token_type, token_value) tuples\&.

``token_type`` may be either 'chars' or 'field'\&.

For 'chars' tokens, the value is the literal value\&.

For 'field' tokens, the value is a tuple of (field character, repetition count)\&.

:param pattern: Pattern string
:type pattern: str
:rtype: list[tuple]

.fi
.PP
 
.SS " str babel\&.dates\&.untokenize_pattern (Iterable[tuple[str, str | tuple[str, int]]] tokens)"

.PP
.nf
Turn a date format pattern token stream back into a string\&.

This is the reverse operation of ``tokenize_pattern``\&.

:type tokens: Iterable[tuple]
:rtype: str

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "TypeAlias babel\&.dates\&._Context = Literal['format', 'stand\-alone']\fC [protected]\fP"

.SS "TypeAlias babel\&.dates\&._DtOrTzinfo = datetime\&.datetime | datetime\&.tzinfo | str | int | datetime\&.time | None\fC [protected]\fP"

.SS "TypeAlias babel\&.dates\&._Instant = datetime\&.date | datetime\&.time | float | None\fC [protected]\fP"

.SS "TypeAlias babel\&.dates\&._PredefinedTimeFormat = Literal['full', 'long', 'medium', 'short']\fC [protected]\fP"

.SS "babel\&.dates\&.LC_TIME = default_locale('LC_TIME')"

.SS "babel\&.dates\&.LOCALTZ = localtime\&.LOCALTZ"

.SS "str babel\&.dates\&.NO_INHERITANCE_MARKER = '\\u2205\\u2205\\u2205'"

.SS "str babel\&.dates\&.PATTERN_CHAR_ORDER = 'GyYuUQqMLlwWdDFgEecabBChHKkjJmsSAzZOvVXx'"

.SS "babel\&.dates\&.pytz = None"

.SS "tuple babel\&.dates\&.TIMEDELTA_UNITS"
\fBInitial value:\fP.PP
.nf
1 =  (
2     ('year', 3600 * 24 * 365),
3     ('month', 3600 * 24 * 30),
4     ('week', 3600 * 24 * 7),
5     ('day', 3600 * 24),
6     ('hour', 3600),
7     ('minute', 60),
8     ('second', 1),
9 )
.fi

.SS "babel\&.dates\&.UTC = datetime\&.timezone\&.utc"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
