.TH "breathe.parser.compoundsuper.paramType" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.compoundsuper.paramType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.parser\&.compoundsuper\&.GeneratedsSuper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBtype_\fP=None, \fBdeclname\fP=None, \fBdefname\fP=None, \fBarray\fP=None, \fBdefval\fP=None, \fBbriefdescription\fP=None)"
.br
.ti -1c
.RI "\fBfactory\fP (*args_, **kwargs_)"
.br
.ti -1c
.RI "\fBget_type\fP (self)"
.br
.ti -1c
.RI "\fBset_type\fP (self, \fBtype_\fP)"
.br
.ti -1c
.RI "\fBget_declname\fP (self)"
.br
.ti -1c
.RI "\fBset_declname\fP (self, \fBdeclname\fP)"
.br
.ti -1c
.RI "\fBget_defname\fP (self)"
.br
.ti -1c
.RI "\fBset_defname\fP (self, \fBdefname\fP)"
.br
.ti -1c
.RI "\fBget_array\fP (self)"
.br
.ti -1c
.RI "\fBset_array\fP (self, \fBarray\fP)"
.br
.ti -1c
.RI "\fBget_defval\fP (self)"
.br
.ti -1c
.RI "\fBset_defval\fP (self, \fBdefval\fP)"
.br
.ti -1c
.RI "\fBget_briefdescription\fP (self)"
.br
.ti -1c
.RI "\fBset_briefdescription\fP (self, \fBbriefdescription\fP)"
.br
.ti -1c
.RI "\fBhasContent_\fP (self)"
.br
.ti -1c
.RI "\fBbuild\fP (self, node_)"
.br
.ti -1c
.RI "\fBbuildAttributes\fP (self, attrs)"
.br
.ti -1c
.RI "\fBbuildChildren\fP (self, child_, nodeName_)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.parser\&.compoundsuper\&.GeneratedsSuper\fP
.in +1c
.ti -1c
.RI "\fBformat_string\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_integer\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_float\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_double\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_boolean\fP (self, input_data, input_name='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtype_\fP"
.br
.ti -1c
.RI "\fBdeclname\fP"
.br
.ti -1c
.RI "\fBdefname\fP"
.br
.ti -1c
.RI "\fBarray\fP"
.br
.ti -1c
.RI "\fBdefval\fP"
.br
.ti -1c
.RI "\fBbriefdescription\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsubclass\fP = None"
.br
.ti -1c
.RI "\fBsuperclass\fP = None"
.br
.ti -1c
.RI "\fBfactory\fP = staticmethod(factory)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.__init__ ( self,  type_ = \fCNone\fP,  declname = \fCNone\fP,  defname = \fCNone\fP,  array = \fCNone\fP,  defval = \fCNone\fP,  briefdescription = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.build ( self,  node_)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.buildAttributes ( self,  attrs)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.buildChildren ( self,  child_,  nodeName_)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.factory (* args_, ** kwargs_)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.get_array ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.get_briefdescription ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.get_declname ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.get_defname ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.get_defval ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.get_type ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.hasContent_ ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.set_array ( self,  array)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.set_briefdescription ( self,  briefdescription)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.set_declname ( self,  declname)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.set_defname ( self,  defname)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.set_defval ( self,  defval)"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.set_type ( self,  type_)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.array"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.briefdescription"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.declname"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.defname"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.defval"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.factory = staticmethod(factory)\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.subclass = None\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.superclass = None\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.paramType\&.type_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
