.TH "breathe.renderer.target._RealTargetHandler" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.renderer.target._RealTargetHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.renderer\&.target\&.TargetHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBProjectInfo\fP \fBproject_info\fP, nodes\&.document \fBdocument\fP)"
.br
.ti -1c
.RI "list[\fBElement\fP] \fBcreate_target\fP (self, str refid)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBproject_info\fP"
.br
.ti -1c
.RI "\fBdocument\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.renderer\&.target\&._RealTargetHandler\&.__init__ ( self, \fBProjectInfo\fP project_info, nodes\&.document document)"

.SH "Member Function Documentation"
.PP 
.SS " list[\fBElement\fP] breathe\&.renderer\&.target\&._RealTargetHandler\&.create_target ( self, str refid)"

.PP
.nf
Creates a target node and registers it with the document and returns it in a list
.fi
.PP
 
.PP
Reimplemented from \fBbreathe\&.renderer\&.target\&.TargetHandler\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "breathe\&.renderer\&.target\&._RealTargetHandler\&.document"

.SS "breathe\&.renderer\&.target\&._RealTargetHandler\&.project_info"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
