.TH "breathe.parser.Parser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.Parser
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbreathe\&.parser\&.DoxygenCompoundParser\fP, and \fBbreathe\&.parser\&.DoxygenIndexParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBSphinx\fP \fBapp\fP, \fBcache\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBapp\fP"
.br
.ti -1c
.RI "\fBcache\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.Parser\&.__init__ ( self, \fBSphinx\fP app,  cache)"

.PP
Reimplemented in \fBbreathe\&.parser\&.DoxygenCompoundParser\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "breathe\&.parser\&.Parser\&.app"

.SS "breathe\&.parser\&.Parser\&.cache"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
