.TH "breathe.parser.indexsuper.MemberType" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.indexsuper.MemberType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.parser\&.indexsuper\&.GeneratedsSuper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBkind\fP=None, \fBrefid\fP=None, \fBname\fP=None)"
.br
.ti -1c
.RI "\fBfactory\fP (*args_, **kwargs_)"
.br
.ti -1c
.RI "\fBget_name\fP (self)"
.br
.ti -1c
.RI "\fBset_name\fP (self, \fBname\fP)"
.br
.ti -1c
.RI "\fBget_kind\fP (self)"
.br
.ti -1c
.RI "\fBset_kind\fP (self, \fBkind\fP)"
.br
.ti -1c
.RI "\fBget_refid\fP (self)"
.br
.ti -1c
.RI "\fBset_refid\fP (self, \fBrefid\fP)"
.br
.ti -1c
.RI "\fBhasContent_\fP (self)"
.br
.ti -1c
.RI "\fBbuild\fP (self, node_)"
.br
.ti -1c
.RI "\fBbuildAttributes\fP (self, attrs)"
.br
.ti -1c
.RI "\fBbuildChildren\fP (self, child_, nodeName_)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.parser\&.indexsuper\&.GeneratedsSuper\fP
.in +1c
.ti -1c
.RI "\fBformat_string\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_integer\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_float\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_double\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_boolean\fP (self, input_data, input_name='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBkind\fP"
.br
.ti -1c
.RI "\fBrefid\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsubclass\fP = None"
.br
.ti -1c
.RI "\fBsuperclass\fP = None"
.br
.ti -1c
.RI "\fBfactory\fP = staticmethod(factory)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.__init__ ( self,  kind = \fCNone\fP,  refid = \fCNone\fP,  name = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.build ( self,  node_)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.buildAttributes ( self,  attrs)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.buildChildren ( self,  child_,  nodeName_)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.factory (* args_, ** kwargs_)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.get_kind ( self)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.get_name ( self)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.get_refid ( self)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.hasContent_ ( self)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.set_kind ( self,  kind)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.set_name ( self,  name)"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.set_refid ( self,  refid)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.factory = staticmethod(factory)\fC [static]\fP"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.kind"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.name"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.refid"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.subclass = None\fC [static]\fP"

.SS "breathe\&.parser\&.indexsuper\&.MemberType\&.superclass = None\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
