.TH "breathe.apidoc" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.apidoc
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTypeAction\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBprint_info\fP (msg, args)"
.br
.ti -1c
.RI "\fBwrite_file\fP (name, text, args)"
.br
.ti -1c
.RI "\fBformat_heading\fP (level, text)"
.br
.ti -1c
.RI "\fBformat_directive\fP (package_type, package, args)"
.br
.ti -1c
.RI "\fBcreate_package_file\fP (package, package_type, package_id, args)"
.br
.ti -1c
.RI "\fBcreate_modules_toc_file\fP (key, value, args)"
.br
.ti -1c
.RI "\fBrecurse_tree\fP (args)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBTYPEDICT\fP"
.br
.ti -1c
.RI "list \fBMEMBERS_TYPES\fP = ['class', 'group', 'interface', 'namespace', 'struct']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
breathe\&.apidoc
~~~~~~~~~~~~~~

Parses doxygen XML tree looking for C/C++ modules and creates ReST files
appropriately to create code documentation with Sphinx\&. It also creates a
modules index (See TYPEDICT below\&.)\&.

This is derived from the 'sphinx-autopackage' script, which is:
Copyright 2008 Société des arts technologiques (SAT),
http://www\&.sat\&.qc\&.ca/

:copyright: Originally by Sphinx Team, C++ modifications by Tatsuyuki Ishi
:license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "breathe\&.apidoc\&.create_modules_toc_file ( key,  value,  args)"

.PP
.nf
Create the module's index\&.
.fi
.PP
 
.SS "breathe\&.apidoc\&.create_package_file ( package,  package_type,  package_id,  args)"

.PP
.nf
Build the text of the file and write the file\&.
.fi
.PP
 
.SS "breathe\&.apidoc\&.format_directive ( package_type,  package,  args)"

.PP
.nf
Create the breathe directive and add the options\&.
.fi
.PP
 
.SS "breathe\&.apidoc\&.format_heading ( level,  text)"

.PP
.nf
Create a heading of <level> [1, 2 or 3 supported]\&.
.fi
.PP
 
.SS "breathe\&.apidoc\&.main (void           )"

.PP
.nf
Parse and check the command line arguments\&.
.fi
.PP
 
.SS "breathe\&.apidoc\&.print_info ( msg,  args)"

.SS "breathe\&.apidoc\&.recurse_tree ( args)"

.PP
.nf
Look for every file in the directory tree and create the corresponding
ReST files\&.

.fi
.PP
 
.SS "breathe\&.apidoc\&.write_file ( name,  text,  args)"

.PP
.nf
Write the output file for module/package <name>\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list breathe\&.apidoc\&.MEMBERS_TYPES = ['class', 'group', 'interface', 'namespace', 'struct']"

.SS "dict breathe\&.apidoc\&.TYPEDICT"
\fBInitial value:\fP.PP
.nf
1 =  {
2     "class": "Class",
3     "interface": "Interface",
4     "struct": "Struct",
5     "union": "Union",
6     "file": "File",
7     "namespace": "Namespace",
8     "group": "Group",
9 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
