.TH "breathe.parser.compoundsuper.graphType" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.compoundsuper.graphType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.parser\&.compoundsuper\&.GeneratedsSuper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBnode\fP=None, str \fBdirection\fP='forward', str \fBcaption\fP='')"
.br
.ti -1c
.RI "\fBfactory\fP (*args_, **kwargs_)"
.br
.ti -1c
.RI "\fBget_direction\fP (self)"
.br
.ti -1c
.RI "\fBset_direction\fP (self, \fBdirection\fP)"
.br
.ti -1c
.RI "\fBget_caption\fP (self)"
.br
.ti -1c
.RI "\fBset_caption\fP (self, \fBcaption\fP)"
.br
.ti -1c
.RI "\fBget_node\fP (self)"
.br
.ti -1c
.RI "\fBset_node\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "\fBadd_node\fP (self, value)"
.br
.ti -1c
.RI "\fBinsert_node\fP (self, index, value)"
.br
.ti -1c
.RI "\fBhasContent_\fP (self)"
.br
.ti -1c
.RI "\fBbuild\fP (self, node_)"
.br
.ti -1c
.RI "\fBbuildAttributes\fP (self, attrs)"
.br
.ti -1c
.RI "\fBbuildChildren\fP (self, child_, nodeName_)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.parser\&.compoundsuper\&.GeneratedsSuper\fP
.in +1c
.ti -1c
.RI "\fBformat_string\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_integer\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_float\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_double\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_boolean\fP (self, input_data, input_name='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnode\fP"
.br
.ti -1c
.RI "\fBdirection\fP"
.br
.ti -1c
.RI "\fBcaption\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsubclass\fP = None"
.br
.ti -1c
.RI "\fBsuperclass\fP = None"
.br
.ti -1c
.RI "\fBfactory\fP = staticmethod(factory)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.__init__ ( self,  node = \fCNone\fP, str  direction = \fC'forward'\fP, str  caption = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.add_node ( self,  value)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.build ( self,  node_)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.buildAttributes ( self,  attrs)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.buildChildren ( self,  child_,  nodeName_)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.factory (* args_, ** kwargs_)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.get_caption ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.get_direction ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.get_node ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.hasContent_ ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.insert_node ( self,  index,  value)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.set_caption ( self,  caption)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.set_direction ( self,  direction)"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.set_node ( self,  node)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.caption"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.direction"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.factory = staticmethod(factory)\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.node"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.subclass = None\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.graphType\&.superclass = None\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
