.TH "breathe.finder.ItemFinder" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.finder.ItemFinder
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbreathe\&.finder\&.compound\&.CompoundDefTypeSubItemFinder\fP, \fBbreathe\&.finder\&.compound\&.DoxygenTypeSubItemFinder\fP, \fBbreathe\&.finder\&.compound\&.MemberDefTypeSubItemFinder\fP, \fBbreathe\&.finder\&.compound\&.RefTypeSubItemFinder\fP, \fBbreathe\&.finder\&.compound\&.SectionDefTypeSubItemFinder\fP, \fBbreathe\&.finder\&.index\&.CompoundTypeSubItemFinder\fP, \fBbreathe\&.finder\&.index\&.DoxygenTypeSubItemFinder\fP, and \fBbreathe\&.finder\&.index\&.MemberTypeSubItemFinder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBProjectInfo\fP \fBproject_info\fP, \fBdata_object\fP, \fBitem_finder_factory\fP)"
.br
.ti -1c
.RI "None \fBfilter_\fP (self, ancestors, \fBFilter\fP filter_, matches)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdata_object\fP"
.br
.ti -1c
.RI "\fBitem_finder_factory\fP"
.br
.ti -1c
.RI "\fBproject_info\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.finder\&.ItemFinder\&.__init__ ( self, \fBProjectInfo\fP project_info,  data_object,  item_finder_factory)"

.PP
Reimplemented in \fBbreathe\&.finder\&.index\&.CompoundTypeSubItemFinder\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " None breathe\&.finder\&.ItemFinder\&.filter_ ( self,  ancestors, \fBFilter\fP filter_,  matches)"

.PP
Reimplemented in \fBbreathe\&.finder\&.compound\&.DoxygenTypeSubItemFinder\fP, \fBbreathe\&.finder\&.compound\&.CompoundDefTypeSubItemFinder\fP, \fBbreathe\&.finder\&.compound\&.SectionDefTypeSubItemFinder\fP, \fBbreathe\&.finder\&.compound\&.MemberDefTypeSubItemFinder\fP, \fBbreathe\&.finder\&.compound\&.RefTypeSubItemFinder\fP, \fBbreathe\&.finder\&.index\&.DoxygenTypeSubItemFinder\fP, \fBbreathe\&.finder\&.index\&.CompoundTypeSubItemFinder\fP, and \fBbreathe\&.finder\&.index\&.MemberTypeSubItemFinder\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "breathe\&.finder\&.ItemFinder\&.data_object"

.SS "breathe\&.finder\&.ItemFinder\&.item_finder_factory"

.SS "breathe\&.finder\&.ItemFinder\&.project_info"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
