.TH "breathe.parser.compoundsuper.docMarkupType" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.compoundsuper.docMarkupType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.parser\&.compoundsuper\&.GeneratedsSuper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBvalueOf_\fP='', \fBmixedclass_\fP=None, \fBcontent_\fP=None)"
.br
.ti -1c
.RI "\fBfactory\fP (*args_, **kwargs_)"
.br
.ti -1c
.RI "\fBgetValueOf_\fP (self)"
.br
.ti -1c
.RI "\fBsetValueOf_\fP (self, \fBvalueOf_\fP)"
.br
.ti -1c
.RI "\fBexport\fP (self, outfile, level, namespace_='', name_='docMarkupType', namespacedef_='')"
.br
.ti -1c
.RI "\fBexportAttributes\fP (self, outfile, level, namespace_='', name_='docMarkupType')"
.br
.ti -1c
.RI "\fBexportChildren\fP (self, outfile, level, namespace_='', name_='docMarkupType')"
.br
.ti -1c
.RI "\fBhasContent_\fP (self)"
.br
.ti -1c
.RI "\fBbuild\fP (self, node_)"
.br
.ti -1c
.RI "\fBbuildAttributes\fP (self, attrs)"
.br
.ti -1c
.RI "\fBbuildChildren\fP (self, child_, nodeName_)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.parser\&.compoundsuper\&.GeneratedsSuper\fP
.in +1c
.ti -1c
.RI "\fBformat_string\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_integer\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_float\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_double\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_boolean\fP (self, input_data, input_name='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmixedclass_\fP"
.br
.ti -1c
.RI "\fBcontent_\fP"
.br
.ti -1c
.RI "\fBvalueOf_\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsubclass\fP = None"
.br
.ti -1c
.RI "\fBsuperclass\fP = None"
.br
.ti -1c
.RI "\fBfactory\fP = staticmethod(factory)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.__init__ ( self,  valueOf_ = \fC''\fP,  mixedclass_ = \fCNone\fP,  content_ = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.build ( self,  node_)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.buildAttributes ( self,  attrs)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.buildChildren ( self,  child_,  nodeName_)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.export ( self,  outfile,  level,  namespace_ = \fC''\fP,  name_ = \fC'docMarkupType'\fP,  namespacedef_ = \fC''\fP)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.exportAttributes ( self,  outfile,  level,  namespace_ = \fC''\fP,  name_ = \fC'docMarkupType'\fP)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.exportChildren ( self,  outfile,  level,  namespace_ = \fC''\fP,  name_ = \fC'docMarkupType'\fP)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.factory (* args_, ** kwargs_)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.getValueOf_ ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.hasContent_ ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.setValueOf_ ( self,  valueOf_)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.content_"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.factory = staticmethod(factory)\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.mixedclass_"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.subclass = None\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.superclass = None\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.docMarkupType\&.valueOf_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
