.TH "breathe.renderer.sphinxrenderer.SphinxRenderer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.renderer.sphinxrenderer.SphinxRenderer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBSphinx\fP \fBapp\fP, \fBProjectInfo\fP \fBproject_info\fP, node_stack, \fBstate\fP, nodes\&.document \fBdocument\fP, \fBTargetHandler\fP \fBtarget_handler\fP, \fBDoxygenCompoundParser\fP \fBcompound_parser\fP, \fBFilter\fP \fBfilter_\fP)"
.br
.ti -1c
.RI "None \fBset_context\fP (self, \fBRenderContext\fP \fBcontext\fP)"
.br
.ti -1c
.RI "str \fBget_refid\fP (self, str refid)"
.br
.ti -1c
.RI "str \fBget_domain\fP (self)"
.br
.ti -1c
.RI "str \fBjoin_nested_name\fP (self, list[str] names)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBrun_directive\fP (self, str obj_type, str declaration, \fBContentCallback\fP contentCallback, options={})"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBhandle_declaration\fP (self, node, str declaration, *str|None obj_type=None, \fBContentCallback\fP|None content_callback=None, str|None display_obj_type=None, \fBDeclaratorCallback\fP|None declarator_callback=None, options={})"
.br
.ti -1c
.RI "list[str] \fBget_qualification\fP (self)"
.br
.ti -1c
.RI "\fBget_fully_qualified_name\fP (self)"
.br
.ti -1c
.RI "str \fBcreate_template_prefix\fP (self, decl)"
.br
.ti -1c
.RI "\fBrun_domain_directive\fP (self, kind, names)"
.br
.ti -1c
.RI "\fBcreate_doxygen_target\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBtitle\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBdescription\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBdetaileddescription\fP (self, node)"
.br
.ti -1c
.RI "\fBupdate_signature\fP (self, signature, obj_type)"
.br
.ti -1c
.RI "\fBrender_declaration\fP (self, node, declaration=None, \fBdescription\fP=None, **kwargs)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_doxygen\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_doxygendef\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_union\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_class\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_namespace\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_compound\fP (self, node, render_empty_node=True, **kwargs)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_file\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_compounddef\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_sectiondef\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docreftext\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docheading\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docpara\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docparblock\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docblockquote\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docimage\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docurllink\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docmarkup\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docsectN\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docsimplesect\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_doctitle\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docformula\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_listing\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_codeline\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_highlight\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_verbatim\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_inc\fP (self, compoundsuper\&.incType node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_ref\fP (self, compoundsuper\&.refType node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_doclistitem\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBrender_unordered\fP (self, children)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBrender_enumerated\fP (self, children, \fBnesting_level\fP)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_doclist\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_compoundref\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docxrefsect\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docvariablelist\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docvarlistentry\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docanchor\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docentry\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docrow\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_doctable\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_mixedcontainer\fP (self, compoundsuper\&.MixedContainer node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_description\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_linkedtext\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_function\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_define\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_enum\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_enumvalue\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_typedef\fP (self, node)"
.br
.ti -1c
.RI "str \fBmake_initializer\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_variable\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_friendclass\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_templateparam\fP (self, compound\&.paramTypeSub node, *bool insertDeclNameByParsing=False)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_templateparamlist\fP (self, compound\&.templateparamlistTypeSub node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docparamlist\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docdot\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docdotfile\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_docgraph\fP (self, compoundsuper\&.graphType node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBvisit_unknown\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBdispatch_compound\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBdispatch_memberdef\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBrender_string\fP (self, str node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBrender\fP (self, node, \fBRenderContext\fP|None \fBcontext\fP=None)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBrender_optional\fP (self, node)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fBrender_iterable\fP (self, list iterable)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBapp\fP"
.br
.ti -1c
.RI "\fBproject_info\fP"
.br
.ti -1c
.RI "\fBqualification_stack\fP"
.br
.ti -1c
.RI "\fBnesting_level\fP"
.br
.ti -1c
.RI "\fBstate\fP"
.br
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBtarget_handler\fP"
.br
.ti -1c
.RI "\fBcompound_parser\fP"
.br
.ti -1c
.RI "\fBfilter_\fP"
.br
.ti -1c
.RI "\fBoutput_defname\fP"
.br
.ti -1c
.RI "\fBcontext\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBsections\fP"
.br
.ti -1c
.RI "\fBsection_titles\fP = dict(\fBsections\fP)"
.br
.ti -1c
.RI "list \fBnumeral_kind\fP = ['arabic', 'loweralpha', 'lowerroman', 'upperalpha', 'upperroman']"
.br
.ti -1c
.RI "dict \fBmethods\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_fixup_separate_member_pages\fP (self, str refid)"
.br
.ti -1c
.RI "str \fB_nested_inline_parse_with_titles\fP (self, content, node)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Doxygen node visitor that converts input into Sphinx/RST representation\&.
Each visit method takes a Doxygen node as an argument and returns a list of RST nodes\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.__init__ ( self, \fBSphinx\fP app, \fBProjectInfo\fP project_info,  node_stack,  state, nodes\&.document document, \fBTargetHandler\fP target_handler, \fBDoxygenCompoundParser\fP compound_parser, \fBFilter\fP filter_)"

.SH "Member Function Documentation"
.PP 
.SS " str breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&._fixup_separate_member_pages ( self, str refid)\fC [protected]\fP"

.SS " str breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&._nested_inline_parse_with_titles ( self,  content,  node)\fC [protected]\fP"

.PP
.nf
This code is basically a customized nested_parse_with_titles from
docutils, using the InlineText class on the statemachine\&.

.fi
.PP
 
.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.create_doxygen_target ( self,  node)"

.PP
.nf
Can be overridden to create a target node which uses the doxygen refid information
which can be used for creating links between internal doxygen elements\&.

The default implementation should suffice most of the time\&.

.fi
.PP
 
.SS " str breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.create_template_prefix ( self,  decl)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.description ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.detaileddescription ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.dispatch_compound ( self,  node)"

.PP
.nf
Dispatch handling of a compound node to a suitable visit method\&.
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.dispatch_memberdef ( self,  node)"

.PP
.nf
Dispatch handling of a memberdef node to a suitable visit method\&.
.fi
.PP
 
.SS " str breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.get_domain ( self)"

.PP
.nf
Returns the domain for the current node\&.
.fi
.PP
 
.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.get_fully_qualified_name ( self)"

.SS " list[str] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.get_qualification ( self)"

.SS " str breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.get_refid ( self, str refid)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.handle_declaration ( self,  node, str declaration, *str | None  obj_type = \fCNone\fP, \fBContentCallback\fP | None  content_callback = \fCNone\fP, str | None  display_obj_type = \fCNone\fP, \fBDeclaratorCallback\fP | None  declarator_callback = \fCNone\fP,  options = \fC{}\fP)"

.SS " str breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.join_nested_name ( self, list[str] names)"

.SS " str breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.make_initializer ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.render ( self,  node, \fBRenderContext\fP | None  context = \fCNone\fP)"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.render_declaration ( self,  node,  declaration = \fCNone\fP,  description = \fCNone\fP, ** kwargs)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.render_enumerated ( self,  children,  nesting_level)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.render_iterable ( self, list iterable)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.render_optional ( self,  node)"

.PP
.nf
Render a node that can be None\&.
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.render_string ( self, str node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.render_unordered ( self,  children)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.run_directive ( self, str obj_type, str declaration, \fBContentCallback\fP contentCallback,  options = \fC{}\fP)"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.run_domain_directive ( self,  kind,  names)"

.SS " None breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.set_context ( self, \fBRenderContext\fP context)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.title ( self,  node)"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.update_signature ( self,  signature,  obj_type)"

.PP
.nf
Update the signature node if necessary, e\&.g\&. add qualifiers\&.
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_class ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_codeline ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_compound ( self,  node,  render_empty_node = \fCTrue\fP, ** kwargs)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_compounddef ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_compoundref ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_define ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_description ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docanchor ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docblockquote ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docdot ( self,  node)"

.PP
.nf
Translate node from doxygen's dot command to sphinx's graphviz directive\&.
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docdotfile ( self,  node)"

.PP
.nf
Translate node from doxygen's dotfile command to sphinx's graphviz directive\&.
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docentry ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docformula ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docgraph ( self, compoundsuper\&.graphType node)"

.PP
.nf
Create a graph (generated by doxygen - not user-defined) from XML using dot
syntax\&.
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docheading ( self,  node)"

.PP
.nf
Heading renderer\&.

Renders embedded headlines as emphasized text\&. Different heading levels
are not supported\&.

.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docimage ( self,  node)"

.PP
.nf
Output docutils image node using name attribute from xml as the uri
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_doclist ( self,  node)"

.PP
.nf
List renderer

The specifics of the actual list rendering are handled by the
decorator around the generic render function\&.
Render all the children depth-first\&.
.fi
.PP
.PP
.PP
.nf
 Call the wrapped render function\&. Update the nesting level for the enumerated lists\&. .fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_doclistitem ( self,  node)"

.PP
.nf
List item renderer\&. Render all the children depth-first\&.
Upon return expand the children node list into a docutils list-item\&.

.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docmarkup ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docpara ( self,  node)"

.PP
.nf
<para> tags in the Doxygen output tend to contain either text or a single other tag of
interest\&. So whilst it looks like we're combined descriptions and program listings and
other things, in the end we generally only deal with one per para tag\&. Multiple
neighbouring instances of these things tend to each be in a separate neighbouring para tag\&.

.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docparamlist ( self,  node)"

.PP
.nf
Parameter/Exception/TemplateParameter documentation
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docparblock ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docreftext ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docrow ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docsectN ( self,  node)"

.PP
.nf
Docutils titles are defined by their level inside the document so
the proper structure is only guaranteed by the Doxygen XML\&.

Doxygen command mapping to XML element name:
@section == sect1, @subsection == sect2, @subsubsection == sect3

.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docsimplesect ( self,  node)"

.PP
.nf
Other Type documentation such as Warning, Note, Returns, etc
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_doctable ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_doctitle ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docurllink ( self,  node)"

.PP
.nf
Url Link Renderer
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docvariablelist ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docvarlistentry ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_docxrefsect ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_doxygen ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_doxygendef ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_enum ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_enumvalue ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_file ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_friendclass ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_function ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_highlight ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_inc ( self, compoundsuper\&.incType node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_linkedtext ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_listing ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_mixedcontainer ( self, compoundsuper\&.MixedContainer node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_namespace ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_ref ( self, compoundsuper\&.refType node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_sectiondef ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_templateparam ( self, compound\&.paramTypeSub node, *bool  insertDeclNameByParsing = \fCFalse\fP)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_templateparamlist ( self, compound\&.templateparamlistTypeSub node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_typedef ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_union ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_unknown ( self,  node)"

.PP
.nf
Visit a node of unknown type\&.
.fi
.PP
 
.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_variable ( self,  node)"

.SS " list[\fBNode\fP] breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.visit_verbatim ( self,  node)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.app"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.compound_parser"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.context"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.document"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.filter_"

.SS "dict breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.methods\fC [static]\fP"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.nesting_level"

.SS "list breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.numeral_kind = ['arabic', 'loweralpha', 'lowerroman', 'upperalpha', 'upperroman']\fC [static]\fP"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.output_defname"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.project_info"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.qualification_stack"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.section_titles = dict(\fBsections\fP)\fC [static]\fP"

.SS "list breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.sections\fC [static]\fP"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.state"

.SS "breathe\&.renderer\&.sphinxrenderer\&.SphinxRenderer\&.target_handler"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
