.TH "breathe" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBapidoc\fP"
.br
.ti -1c
.RI "namespace \fBdirectives\fP"
.br
.ti -1c
.RI "namespace \fBexception\fP"
.br
.ti -1c
.RI "namespace \fBfile_state_cache\fP"
.br
.ti -1c
.RI "namespace \fBfiletypes\fP"
.br
.ti -1c
.RI "namespace \fBfinder\fP"
.br
.ti -1c
.RI "namespace \fBparser\fP"
.br
.ti -1c
.RI "namespace \fBpath_handler\fP"
.br
.ti -1c
.RI "namespace \fBprocess\fP"
.br
.ti -1c
.RI "namespace \fBproject\fP"
.br
.ti -1c
.RI "namespace \fBrenderer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "breathe\&.setup (\fBSphinx\fP app)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
