.TH "breathe.renderer.filter.FilterFactory" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.renderer.filter.FilterFactory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBSphinx\fP \fBapp\fP)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_render_filter\fP (self, str kind, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_class_filter\fP (self, str target, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_innerclass_filter\fP (self, dict[str, Any] options, str outerclass='')"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_show_filter\fP (self, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_class_member_filter\fP (self, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_outline_filter\fP (self, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_file_filter\fP (self, str filename, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_content_filter\fP (self, str kind, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_index_filter\fP (self, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_open_filter\fP (self)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_id_filter\fP (self, str node_type, str refid)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_file_finder_filter\fP (self, str filename)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_member_finder_filter\fP (self, str namespace, str name, str kind)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_function_and_all_friend_finder_filter\fP (self, str namespace, str name)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_enumvalue_finder_filter\fP (self, str name)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_compound_finder_filter\fP (self, str name, str kind)"
.br
.ti -1c
.RI "\fBFilter\fP \fBcreate_finder_filter\fP (self, str kind, str name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBapp\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dict \fBpublic_kinds\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBFilter\fP \fB_create_description_filter\fP (self, bool allow, str level, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fB_create_public_members_filter\fP (self, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fB_create_non_public_members_filter\fP (self, str prot, str option_name, dict[str, Any] options)"
.br
.ti -1c
.RI "\fBFilter\fP \fB_create_undoc_members_filter\fP (self, dict[str, Any] options)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None breathe\&.renderer\&.filter\&.FilterFactory\&.__init__ ( self, \fBSphinx\fP app)"

.SH "Member Function Documentation"
.PP 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&._create_description_filter ( self, bool allow, str level, dict[str, Any]
     options)\fC [protected]\fP"

.PP
.nf
Whether or not we allow descriptions is determined by the calling function and we just do
whatever the 'allow' function parameter tells us\&.

.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&._create_non_public_members_filter ( self, str prot, str option_name, dict[str, Any]
     options)\fC [protected]\fP"

.PP
.nf
'prot' is the doxygen xml term for 'public', 'protected' and 'private' categories\&.
.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&._create_public_members_filter ( self, dict[str, Any] options)\fC [protected]\fP"

.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&._create_undoc_members_filter ( self, dict[str, Any] options)\fC [protected]\fP"

.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_class_filter ( self, str target, dict[str, Any] options)"

.PP
.nf
Content filter for classes based on various directive options
.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_class_member_filter ( self, dict[str, Any] options)"

.PP
.nf
Content filter based on :members: and :private-members: classes
.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_compound_finder_filter ( self, str name, str kind)"

.PP
.nf
Returns a filter which looks for a compound with the specified name and kind\&.
.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_content_filter ( self, str kind, dict[str, Any] options)"

.PP
.nf
Returns a filter which matches the contents of the or namespace but not the group or
namespace name or description\&.

This allows the groups to be used to structure sections of the documentation rather than to
structure and further document groups of documentation

As a finder/content filter we only need to match exactly what we're interested in\&.

.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_enumvalue_finder_filter ( self, str name)"

.PP
.nf
Returns a filter which looks for an enumvalue with the specified name\&.
.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_file_filter ( self, str filename, dict[str, Any] options)"

.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_file_finder_filter ( self, str filename)"

.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_finder_filter ( self, str kind, str name)"

.PP
.nf
Returns a filter which looks for the compound node from the index which is a group node
(kind=group) and has the appropriate name

The compound node should reference the group file which we can parse for the group
contents\&.

.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_function_and_all_friend_finder_filter ( self, str namespace, str name)"

.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_id_filter ( self, str node_type, str refid)"

.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_index_filter ( self, dict[str, Any] options)"

.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_innerclass_filter ( self, dict[str, Any] options, str  outerclass = \fC''\fP)"

.PP
.nf
:param outerclass: Should be the class/struct being target by the directive calling this
                   code\&. If it is a group or namespace directive then it should be left
                   blank\&. It is used when looking for names listed in the :members: option\&.

                   The name should include any additional namespaces that the target class
                   is in\&.

.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_member_finder_filter ( self, str namespace, str name, str kind)"

.PP
.nf
Returns a filter which looks for a member with the specified name and kind\&.
.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_open_filter ( self)"

.PP
.nf
Returns a completely open filter which matches everything
.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_outline_filter ( self, dict[str, Any] options)"

.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_render_filter ( self, str kind, dict[str, Any] options)"

.PP
.nf
Render filter for group & namespace blocks
.fi
.PP
 
.SS " \fBFilter\fP breathe\&.renderer\&.filter\&.FilterFactory\&.create_show_filter ( self, dict[str, Any] options)"

.PP
.nf
Currently only handles the header-file entry
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "breathe\&.renderer\&.filter\&.FilterFactory\&.app"

.SS "dict breathe\&.renderer\&.filter\&.FilterFactory\&.public_kinds\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  {
        "public\-type",
        "public\-func",
        "public\-attrib",
        "public\-slot",
        "public\-static\-func",
        "public\-static\-attrib",
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
