.TH "breathe.renderer.mask.NoParameterNamesMask" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.renderer.mask.NoParameterNamesMask
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBdata_object\fP)"
.br
.ti -1c
.RI "\fB__getattr__\fP (self, attr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdata_object\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None breathe\&.renderer\&.mask\&.NoParameterNamesMask\&.__init__ ( self,  data_object)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.renderer\&.mask\&.NoParameterNamesMask\&.__getattr__ ( self,  attr)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.renderer\&.mask\&.NoParameterNamesMask\&.data_object"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
