.TH "breathe.parser.compoundsuper.docXRefSectType" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.compoundsuper.docXRefSectType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.parser\&.compoundsuper\&.GeneratedsSuper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBid\fP=None, \fBxreftitle\fP=None, \fBxrefdescription\fP=None)"
.br
.ti -1c
.RI "\fBfactory\fP (*args_, **kwargs_)"
.br
.ti -1c
.RI "\fBget_xreftitle\fP (self)"
.br
.ti -1c
.RI "\fBset_xreftitle\fP (self, \fBxreftitle\fP)"
.br
.ti -1c
.RI "\fBadd_xreftitle\fP (self, value)"
.br
.ti -1c
.RI "\fBinsert_xreftitle\fP (self, index, value)"
.br
.ti -1c
.RI "\fBget_xrefdescription\fP (self)"
.br
.ti -1c
.RI "\fBset_xrefdescription\fP (self, \fBxrefdescription\fP)"
.br
.ti -1c
.RI "\fBget_id\fP (self)"
.br
.ti -1c
.RI "\fBset_id\fP (self, \fBid\fP)"
.br
.ti -1c
.RI "\fBexport\fP (self, outfile, level, namespace_='', name_='docXRefSectType', namespacedef_='')"
.br
.ti -1c
.RI "\fBexportAttributes\fP (self, outfile, level, namespace_='', name_='docXRefSectType')"
.br
.ti -1c
.RI "\fBexportChildren\fP (self, outfile, level, namespace_='', name_='docXRefSectType')"
.br
.ti -1c
.RI "\fBhasContent_\fP (self)"
.br
.ti -1c
.RI "\fBbuild\fP (self, node_)"
.br
.ti -1c
.RI "\fBbuildAttributes\fP (self, attrs)"
.br
.ti -1c
.RI "\fBbuildChildren\fP (self, child_, nodeName_)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.parser\&.compoundsuper\&.GeneratedsSuper\fP
.in +1c
.ti -1c
.RI "\fBformat_string\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_integer\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_float\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_double\fP (self, input_data, input_name='')"
.br
.ti -1c
.RI "\fBformat_boolean\fP (self, input_data, input_name='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBxreftitle\fP"
.br
.ti -1c
.RI "\fBxrefdescription\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsubclass\fP = None"
.br
.ti -1c
.RI "\fBsuperclass\fP = None"
.br
.ti -1c
.RI "\fBfactory\fP = staticmethod(factory)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.__init__ ( self,  id = \fCNone\fP,  xreftitle = \fCNone\fP,  xrefdescription = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.add_xreftitle ( self,  value)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.build ( self,  node_)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.buildAttributes ( self,  attrs)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.buildChildren ( self,  child_,  nodeName_)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.export ( self,  outfile,  level,  namespace_ = \fC''\fP,  name_ = \fC'docXRefSectType'\fP,  namespacedef_ = \fC''\fP)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.exportAttributes ( self,  outfile,  level,  namespace_ = \fC''\fP,  name_ = \fC'docXRefSectType'\fP)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.exportChildren ( self,  outfile,  level,  namespace_ = \fC''\fP,  name_ = \fC'docXRefSectType'\fP)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.factory (* args_, ** kwargs_)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.get_id ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.get_xrefdescription ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.get_xreftitle ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.hasContent_ ( self)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.insert_xreftitle ( self,  index,  value)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.set_id ( self,  id)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.set_xrefdescription ( self,  xrefdescription)"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.set_xreftitle ( self,  xreftitle)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.factory = staticmethod(factory)\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.id"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.subclass = None\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.superclass = None\fC [static]\fP"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.xrefdescription"

.SS "breathe\&.parser\&.compoundsuper\&.docXRefSectType\&.xreftitle"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
