.TH "breathe.parser.compound.docParamListTypeSub" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.compound.docParamListTypeSub
.SH SYNOPSIS
.br
.PP
.PP
Inherits supermod\&.docParamListType\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, kind=None, parameteritem=None)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBnode_type\fP = 'docparamlist'"
.br
.ti -1c
.RI "\fBsubclass\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.compound\&.docParamListTypeSub\&.__init__ ( self,  kind = \fCNone\fP,  parameteritem = \fCNone\fP)"

.SH "Member Data Documentation"
.PP 
.SS "str breathe\&.parser\&.compound\&.docParamListTypeSub\&.node_type = 'docparamlist'\fC [static]\fP"

.SS "breathe\&.parser\&.compound\&.docParamListTypeSub\&.subclass\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
