.TH "breathe.parser.DoxygenCompoundParser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.DoxygenCompoundParser
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.parser\&.Parser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBSphinx\fP \fBapp\fP, \fBcache\fP, \fBProjectInfo\fP \fBproject_info\fP)"
.br
.ti -1c
.RI "\fBparse\fP (self, str refid)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBproject_info\fP"
.br
.ti -1c
.RI "\fBapp\fP"
.br
.in -1c

Public Attributes inherited from \fBbreathe\&.parser\&.Parser\fP
.in +1c
.ti -1c
.RI "\fBapp\fP"
.br
.ti -1c
.RI "\fBcache\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None breathe\&.parser\&.DoxygenCompoundParser\&.__init__ ( self, \fBSphinx\fP app,  cache, \fBProjectInfo\fP project_info)"

.PP
Reimplemented from \fBbreathe\&.parser\&.Parser\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "breathe\&.parser\&.DoxygenCompoundParser\&.parse ( self, str refid)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.parser\&.DoxygenCompoundParser\&.app"

.SS "breathe\&.parser\&.DoxygenCompoundParser\&.project_info"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
