.TH "breathe.parser.indexsuper" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.indexsuper
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_MemberSpec\fP"
.br
.ti -1c
.RI "class \fBCompoundType\fP"
.br
.ti -1c
.RI "class \fBDoxygenType\fP"
.br
.ti -1c
.RI "class \fBGeneratedsSuper\fP"
.br
.ti -1c
.RI "class \fBMemberType\fP"
.br
.ti -1c
.RI "class \fBMixedContainer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBshowIndent\fP (outfile, level)"
.br
.ti -1c
.RI "\fBquote_xml\fP (inStr)"
.br
.ti -1c
.RI "\fBquote_attrib\fP (inStr)"
.br
.ti -1c
.RI "\fBquote_python\fP (inStr)"
.br
.ti -1c
.RI "\fBusage\fP ()"
.br
.ti -1c
.RI "\fBparse\fP (inFileName)"
.br
.ti -1c
.RI "\fBparseString\fP (inString)"
.br
.ti -1c
.RI "\fBparseLiteral\fP (inFileName)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBExternalEncoding\fP = 'ascii'"
.br
.RI "from IPython\&.Shell import IPShellEmbed args = '' ipshell = IPShellEmbed(args, banner = 'Dropping into IPython', exit_msg = 'Leaving Interpreter, back to program\&. "
.ti -1c
.RI "str \fBUSAGE_TEXT\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "breathe\&.parser\&.indexsuper\&.main (void           )"

.SS "breathe\&.parser\&.indexsuper\&.parse ( inFileName)"

.SS "breathe\&.parser\&.indexsuper\&.parseLiteral ( inFileName)"

.SS "breathe\&.parser\&.indexsuper\&.parseString ( inString)"

.SS "breathe\&.parser\&.indexsuper\&.quote_attrib ( inStr)"

.SS "breathe\&.parser\&.indexsuper\&.quote_python ( inStr)"

.SS "breathe\&.parser\&.indexsuper\&.quote_xml ( inStr)"

.SS "breathe\&.parser\&.indexsuper\&.showIndent ( outfile,  level)"

.SS "breathe\&.parser\&.indexsuper\&.usage ()"

.SH "Variable Documentation"
.PP 
.SS "str breathe\&.parser\&.indexsuper\&.ExternalEncoding = 'ascii'"

.PP
from IPython\&.Shell import IPShellEmbed args = '' ipshell = IPShellEmbed(args, banner = 'Dropping into IPython', exit_msg = 'Leaving Interpreter, back to program\&. ') 
.SS "str breathe\&.parser\&.indexsuper\&.USAGE_TEXT"
\fBInitial value:\fP.PP
.nf
1 =  """
2 Usage: python <Parser>\&.py [ \-s ] <in_xml_file>
3 Options:
4     \-s        Use the SAX parser, not the minidom parser\&.
5 """
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
