.TH "breathe.parser.compound.docHeadingTypeSub" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.compound.docHeadingTypeSub
.SH SYNOPSIS
.br
.PP
.PP
Inherits supermod\&.docHeadingType\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, level=None, valueOf_='', mixedclass_=None, content_=None)"
.br
.ti -1c
.RI "\fBbuildChildren\fP (self, child_, nodeName_)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBnode_type\fP = 'docheading'"
.br
.ti -1c
.RI "\fBsubclass\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.compound\&.docHeadingTypeSub\&.__init__ ( self,  level = \fCNone\fP,  valueOf_ = \fC''\fP,  mixedclass_ = \fCNone\fP,  content_ = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.parser\&.compound\&.docHeadingTypeSub\&.buildChildren ( self,  child_,  nodeName_)"

.SH "Member Data Documentation"
.PP 
.SS "str breathe\&.parser\&.compound\&.docHeadingTypeSub\&.node_type = 'docheading'\fC [static]\fP"

.SS "breathe\&.parser\&.compound\&.docHeadingTypeSub\&.subclass\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
