.TH "breathe.renderer.filter.Node" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.renderer.filter.Node
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.renderer\&.filter\&.Selector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__call__\fP (self, node_stack)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.renderer\&.filter\&.Selector\fP
.in +1c
.ti -1c
.RI "\fBnode_type\fP (self)"
.br
.ti -1c
.RI "\fBkind\fP (self)"
.br
.ti -1c
.RI "\fBnode_name\fP (self)"
.br
.ti -1c
.RI "\fBname\fP (self)"
.br
.ti -1c
.RI "\fBbriefdescription\fP (self)"
.br
.ti -1c
.RI "\fBdetaileddescription\fP (self)"
.br
.ti -1c
.RI "\fBprot\fP (self)"
.br
.ti -1c
.RI "\fBvalueOf\fP (self)"
.br
.ti -1c
.RI "\fBid\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "breathe\&.renderer\&.filter\&.Node\&.__call__ ( self,  node_stack)"

.PP
Reimplemented from \fBbreathe\&.renderer\&.filter\&.Selector\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
