.TH "breathe.finder.factory._CreateCompoundTypeSubFinder" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.finder.factory._CreateCompoundTypeSubFinder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBSphinx\fP \fBapp\fP, \fBDoxygenParserFactory\fP \fBparser_factory\fP)"
.br
.ti -1c
.RI "\fB__call__\fP (self, \fBProjectInfo\fP project_info, *args)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBapp\fP"
.br
.ti -1c
.RI "\fBparser_factory\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.finder\&.factory\&._CreateCompoundTypeSubFinder\&.__init__ ( self, \fBSphinx\fP app, \fBDoxygenParserFactory\fP parser_factory)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.finder\&.factory\&._CreateCompoundTypeSubFinder\&.__call__ ( self, \fBProjectInfo\fP project_info, * args)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.finder\&.factory\&._CreateCompoundTypeSubFinder\&.app"

.SS "breathe\&.finder\&.factory\&._CreateCompoundTypeSubFinder\&.parser_factory"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
