.TH "breathe.directives.item.DoxygenConceptDirective" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.directives.item.DoxygenConceptDirective
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.directives\&.item\&._DoxygenBaseItemDirective\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilter\fP \fBcreate_finder_filter\fP (self, str namespace, str \fBname\fP)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.directives\&.item\&._DoxygenBaseItemDirective\fP
.in +1c
.ti -1c
.RI "list[\fBNode\fP] \fBrun\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.directives\&.BaseDirective\fP
.in +1c
.ti -1c
.RI "list \fBdirective_args\fP (self)"
.br
.ti -1c
.RI "\fBProjectInfoFactory\fP \fBproject_info_factory\fP (self)"
.br
.ti -1c
.RI "\fBDoxygenParserFactory\fP \fBparser_factory\fP (self)"
.br
.ti -1c
.RI "\fBFinderFactory\fP \fBfinder_factory\fP (self)"
.br
.ti -1c
.RI "\fBFilterFactory\fP \fBfilter_factory\fP (self)"
.br
.ti -1c
.RI "str \fBkind\fP (self)"
.br
.ti -1c
.RI "\fB_WarningHandler\fP \fBcreate_warning\fP (self, \fBProjectInfo\fP|None project_info, **kwargs)"
.br
.ti -1c
.RI "list[nodes\&.Node] \fBrender\fP (self, node_stack, \fBProjectInfo\fP project_info, \fBFilter\fP filter_, \fBTargetHandler\fP target_handler, \fBMaskFactoryBase\fP mask_factory, \fBdirective_args\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBkind\fP = 'concept'"
.br
.in -1c

Static Public Attributes inherited from \fBbreathe\&.directives\&.item\&._DoxygenBaseItemDirective\fP
.in +1c
.ti -1c
.RI "int \fBrequired_arguments\fP = 1"
.br
.ti -1c
.RI "int \fBoptional_arguments\fP = 1"
.br
.ti -1c
.RI "dict \fBoption_spec\fP"
.br
.ti -1c
.RI "bool \fBhas_content\fP = False"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBbreathe\&.directives\&.item\&._DoxygenBaseItemDirective\fP
.in +1c
.ti -1c
.RI "\fBkind\fP"
.br
.in -1c

Public Attributes inherited from \fBbreathe\&.directives\&.BaseDirective\fP
.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBarguments\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBcontent\fP"
.br
.ti -1c
.RI "\fBlineno\fP"
.br
.ti -1c
.RI "\fBcontent_offset\fP"
.br
.ti -1c
.RI "\fBblock_text\fP"
.br
.ti -1c
.RI "\fBstate\fP"
.br
.ti -1c
.RI "\fBstate_machine\fP"
.br
.ti -1c
.RI "\fBparser_factory\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " \fBFilter\fP breathe\&.directives\&.item\&.DoxygenConceptDirective\&.create_finder_filter ( self, str namespace, str name)"

.PP
.nf
Creates a filter to find the node corresponding to this item\&.
.fi
.PP
 
.PP
Reimplemented from \fBbreathe\&.directives\&.item\&._DoxygenBaseItemDirective\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str breathe\&.directives\&.item\&.DoxygenConceptDirective\&.kind = 'concept'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
