.TH "breathe.renderer.mask.MaskFactory" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.renderer.mask.MaskFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.renderer\&.mask\&.MaskFactoryBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBlookup\fP)"
.br
.ti -1c
.RI "\fBmask\fP (self, data_object)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlookup\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.renderer\&.mask\&.MaskFactory\&.__init__ ( self,  lookup)"

.SH "Member Function Documentation"
.PP 
.SS "breathe\&.renderer\&.mask\&.MaskFactory\&.mask ( self,  data_object)"

.PP
Reimplemented from \fBbreathe\&.renderer\&.mask\&.MaskFactoryBase\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "breathe\&.renderer\&.mask\&.MaskFactory\&.lookup"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
