.TH "breathe.parser.compound.locationTypeSub" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.parser.compound.locationTypeSub
.SH SYNOPSIS
.br
.PP
.PP
Inherits supermod\&.locationType\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, bodystart=None, line=None, bodyend=None, bodyfile=None, file=None, valueOf_='')"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBnode_type\fP = 'location'"
.br
.ti -1c
.RI "\fBsubclass\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "breathe\&.parser\&.compound\&.locationTypeSub\&.__init__ ( self,  bodystart = \fCNone\fP,  line = \fCNone\fP,  bodyend = \fCNone\fP,  bodyfile = \fCNone\fP,  file = \fCNone\fP,  valueOf_ = \fC''\fP)"

.SH "Member Data Documentation"
.PP 
.SS "str breathe\&.parser\&.compound\&.locationTypeSub\&.node_type = 'location'\fC [static]\fP"

.SS "breathe\&.parser\&.compound\&.locationTypeSub\&.subclass\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
