.TH "breathe.renderer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.renderer
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBfilter\fP"
.br
.ti -1c
.RI "namespace \fBmask\fP"
.br
.ti -1c
.RI "namespace \fBsphinxrenderer\fP"
.br
.ti -1c
.RI "namespace \fBtarget\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRenderContext\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBformat_parser_error\fP (name, error, filename, state, lineno, do_unicode_warning)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "breathe\&.renderer\&.format_parser_error ( name,  error,  filename,  state,  lineno,  do_unicode_warning)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
