.TH "breathe.directives.function.DoxygenFunctionDirective" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
breathe.directives.function.DoxygenFunctionDirective
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbreathe\&.directives\&.BaseDirective\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "list[\fBNode\fP] \fBrun\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBbreathe\&.directives\&.BaseDirective\fP
.in +1c
.ti -1c
.RI "list \fBdirective_args\fP (self)"
.br
.ti -1c
.RI "\fBProjectInfoFactory\fP \fBproject_info_factory\fP (self)"
.br
.ti -1c
.RI "\fBDoxygenParserFactory\fP \fBparser_factory\fP (self)"
.br
.ti -1c
.RI "\fBFinderFactory\fP \fBfinder_factory\fP (self)"
.br
.ti -1c
.RI "\fBFilterFactory\fP \fBfilter_factory\fP (self)"
.br
.ti -1c
.RI "str \fBkind\fP (self)"
.br
.ti -1c
.RI "\fB_WarningHandler\fP \fBcreate_warning\fP (self, \fBProjectInfo\fP|None project_info, **kwargs)"
.br
.ti -1c
.RI "list[nodes\&.Node] \fBrender\fP (self, node_stack, \fBProjectInfo\fP project_info, \fBFilter\fP filter_, \fBTargetHandler\fP target_handler, \fBMaskFactoryBase\fP mask_factory, \fBdirective_args\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdirective_args\fP"
.br
.ti -1c
.RI "\fBstate\fP"
.br
.ti -1c
.RI "\fBlineno\fP"
.br
.in -1c

Public Attributes inherited from \fBbreathe\&.directives\&.BaseDirective\fP
.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBarguments\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBcontent\fP"
.br
.ti -1c
.RI "\fBlineno\fP"
.br
.ti -1c
.RI "\fBcontent_offset\fP"
.br
.ti -1c
.RI "\fBblock_text\fP"
.br
.ti -1c
.RI "\fBstate\fP"
.br
.ti -1c
.RI "\fBstate_machine\fP"
.br
.ti -1c
.RI "\fBparser_factory\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBrequired_arguments\fP = 1"
.br
.ti -1c
.RI "dict \fBoption_spec\fP"
.br
.ti -1c
.RI "bool \fBhas_content\fP = False"
.br
.ti -1c
.RI "bool \fBfinal_argument_whitespace\fP = True"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "cpp\&.ASTParametersQualifiers|None \fB_parse_args\fP (self, str function_description)"
.br
.ti -1c
.RI "str \fB_create_function_signature\fP (self, node_stack, project_info, filter_, target_handler, mask_factory, \fBdirective_args\fP)"
.br
.ti -1c
.RI "\fB_resolve_function\fP (self, matches, cpp\&.ASTParametersQualifiers|None args, project_info)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " str breathe\&.directives\&.function\&.DoxygenFunctionDirective\&._create_function_signature ( self,  node_stack,  project_info,  filter_,  target_handler,  mask_factory,  directive_args)\fC [protected]\fP"

.SS " cpp\&.ASTParametersQualifiers | None breathe\&.directives\&.function\&.DoxygenFunctionDirective\&._parse_args ( self, str function_description)\fC [protected]\fP"

.SS "breathe\&.directives\&.function\&.DoxygenFunctionDirective\&._resolve_function ( self,  matches, cpp\&.ASTParametersQualifiers | None args,  project_info)\fC [protected]\fP"

.SS " list[\fBNode\fP] breathe\&.directives\&.function\&.DoxygenFunctionDirective\&.run ( self)"

.SH "Member Data Documentation"
.PP 
.SS "breathe\&.directives\&.function\&.DoxygenFunctionDirective\&.directive_args"

.SS "bool breathe\&.directives\&.function\&.DoxygenFunctionDirective\&.final_argument_whitespace = True\fC [static]\fP"

.SS "bool breathe\&.directives\&.function\&.DoxygenFunctionDirective\&.has_content = False\fC [static]\fP"

.SS "breathe\&.directives\&.function\&.DoxygenFunctionDirective\&.lineno"

.SS "dict breathe\&.directives\&.function\&.DoxygenFunctionDirective\&.option_spec\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  {
        "path": unchanged_required,
        "project": unchanged_required,
        "outline": flag,
        "no\-link": flag,
    }
.fi

.SS "int breathe\&.directives\&.function\&.DoxygenFunctionDirective\&.required_arguments = 1\fC [static]\fP"

.SS "breathe\&.directives\&.function\&.DoxygenFunctionDirective\&.state"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
