.TH "bs4.formatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.formatter
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFormatter\fP"
.br
.ti -1c
.RI "class \fBHTMLFormatter\fP"
.br
.ti -1c
.RI "class \fBXMLFormatter\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_FormatterOrName\fP = Union[\fBFormatter\fP, str]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bs4\&.formatter\&._FormatterOrName = Union[\fBFormatter\fP, str]\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
