.TH "bs4.css.CSS" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.css.CSS
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBelement\&.Tag\fP \fBtag\fP, Optional[ModuleType] \fBapi\fP=None)"
.br
.ti -1c
.RI "str \fBescape\fP (self, str ident)"
.br
.ti -1c
.RI "SoupSieve \fBcompile\fP (self, str \fBselect\fP, Optional[_NamespaceMapping] namespaces=None, int flags=0, **Any kwargs)"
.br
.ti -1c
.RI "\fBelement\&.Tag\fP|None \fBselect_one\fP (self, str \fBselect\fP, Optional[_NamespaceMapping] namespaces=None, int flags=0, **Any kwargs)"
.br
.ti -1c
.RI "\fBResultSet\fP[\fBelement\&.Tag\fP] \fBselect\fP (self, str select, Optional[_NamespaceMapping] namespaces=None, int limit=0, int flags=0, **Any kwargs)"
.br
.ti -1c
.RI "Iterator[\fBelement\&.Tag\fP] \fBiselect\fP (self, str \fBselect\fP, Optional[_NamespaceMapping] namespaces=None, int limit=0, int flags=0, **Any kwargs)"
.br
.ti -1c
.RI "Optional[\fBelement\&.Tag\fP] \fBclosest\fP (self, str \fBselect\fP, Optional[_NamespaceMapping] namespaces=None, int flags=0, **Any kwargs)"
.br
.ti -1c
.RI "bool \fBmatch\fP (self, str \fBselect\fP, Optional[_NamespaceMapping] namespaces=None, int flags=0, **Any kwargs)"
.br
.ti -1c
.RI "\fBResultSet\fP[\fBelement\&.Tag\fP] \fBfilter\fP (self, str \fBselect\fP, Optional[_NamespaceMapping] namespaces=None, int flags=0, **Any kwargs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBapi\fP"
.br
.ti -1c
.RI "\fBtag\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Optional[_NamespaceMapping] \fB_ns\fP (self, Optional[_NamespaceMapping] ns, str \fBselect\fP)"
.br
.ti -1c
.RI "\fBResultSet\fP[\fBTag\fP] \fB_rs\fP (self, Iterable[\fBTag\fP] results)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A proxy object against the ``soupsieve`` library, to simplify its
CSS selector API\&.

You don't need to instantiate this class yourself; instead, use
`element\&.Tag\&.css`\&.

:param tag: All CSS selectors run by this object will use this as
    their starting point\&.

:param api: An optional drop-in replacement for the ``soupsieve`` module,
    intended for use in unit tests\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bs4\&.css\&.CSS\&.__init__ ( self, \fBelement\&.Tag\fP tag, Optional[ModuleType]  api = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS " Optional[_NamespaceMapping] bs4\&.css\&.CSS\&._ns ( self, Optional[_NamespaceMapping] ns, str
     select)\fC [protected]\fP"

.PP
.nf
Normalize a dictionary of namespaces\&.
.fi
.PP
 
.SS " \fBResultSet\fP[\fBTag\fP] bs4\&.css\&.CSS\&._rs ( self, Iterable[\fBTag\fP] results)\fC [protected]\fP"

.PP
.nf
Normalize a list of results to a py:class:`ResultSet`\&.

A py:class:`ResultSet` is more consistent with the rest of
Beautiful Soup's API, and :py:meth:`ResultSet\&.__getattr__` has
a helpful error message if you try to treat a list of results
as a single result (a common mistake)\&.

.fi
.PP
 
.SS " Optional[\fBelement\&.Tag\fP] bs4\&.css\&.CSS\&.closest ( self, str select, Optional[_NamespaceMapping]  namespaces = \fCNone\fP, int  flags = \fC0\fP, **Any kwargs)"

.PP
.nf
Find the `element\&.Tag` closest to this one that matches the given selector\&.

This uses the Soup Sieve library\&. For more information, see
that library's documentation for the `soupsieve\&.closest()
<https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveclosest>`_
method\&.

:param selector: A string containing a CSS selector\&.

:param namespaces: A dictionary mapping namespace prefixes
    used in the CSS selector to namespace URIs\&. By default,
    Beautiful Soup will pass in the prefixes it encountered while
    parsing the document\&.

:param flags: Flags to be passed into Soup Sieve's
    `soupsieve\&.closest() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveclosest>`_ method\&.

:param kwargs: Keyword arguments to be passed into Soup Sieve's
   `soupsieve\&.closest() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveclosest>`_ method\&.
.fi
.PP
 
.SS " SoupSieve bs4\&.css\&.CSS\&.compile ( self, str select, Optional[_NamespaceMapping]  namespaces = \fCNone\fP, int  flags = \fC0\fP, **Any kwargs)"

.PP
.nf
Pre-compile a selector and return the compiled object\&.

:param selector: A CSS selector\&.

:param namespaces: A dictionary mapping namespace prefixes
   used in the CSS selector to namespace URIs\&. By default,
   Beautiful Soup will use the prefixes it encountered while
   parsing the document\&.

:param flags: Flags to be passed into Soup Sieve's
    `soupsieve\&.compile() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsievecompile>`_ method\&.

:param kwargs: Keyword arguments to be passed into Soup Sieve's
   `soupsieve\&.compile() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsievecompile>`_ method\&.

:return: A precompiled selector object\&.
:rtype: soupsieve\&.SoupSieve

.fi
.PP
 
.SS " str bs4\&.css\&.CSS\&.escape ( self, str ident)"

.PP
.nf
Escape a CSS identifier\&.

This is a simple wrapper around `soupsieve\&.escape() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveescape>`_\&. See the
documentation for that function for more information\&.

.fi
.PP
 
.SS " \fBResultSet\fP[\fBelement\&.Tag\fP] bs4\&.css\&.CSS\&.filter ( self, str select, Optional[_NamespaceMapping]  namespaces = \fCNone\fP, int  flags = \fC0\fP, **Any kwargs)"

.PP
.nf
Filter this `element\&.Tag`'s direct children based on the given CSS selector\&.

This uses the Soup Sieve library\&. It works the same way as
passing a `element\&.Tag` into that library's `soupsieve\&.filter()
<https://facelessuser\&.github\&.io/soupsieve/api/#soupsievefilter>`_
method\&. For more information, see the documentation for
`soupsieve\&.filter()
<https://facelessuser\&.github\&.io/soupsieve/api/#soupsievefilter>`_\&.

:param namespaces: A dictionary mapping namespace prefixes
    used in the CSS selector to namespace URIs\&. By default,
    Beautiful Soup will pass in the prefixes it encountered while
    parsing the document\&.

:param flags: Flags to be passed into Soup Sieve's
    `soupsieve\&.filter()
    <https://facelessuser\&.github\&.io/soupsieve/api/#soupsievefilter>`_
    method\&.

:param kwargs: Keyword arguments to be passed into SoupSieve's
    `soupsieve\&.filter()
    <https://facelessuser\&.github\&.io/soupsieve/api/#soupsievefilter>`_
    method\&.

.fi
.PP
 
.SS " Iterator[\fBelement\&.Tag\fP] bs4\&.css\&.CSS\&.iselect ( self, str select, Optional[_NamespaceMapping]  namespaces = \fCNone\fP, int  limit = \fC0\fP, int  flags = \fC0\fP, **Any kwargs)"

.PP
.nf
Perform a CSS selection operation on the current `element\&.Tag`\&.

This uses the Soup Sieve library\&. For more information, see
that library's documentation for the `soupsieve\&.iselect()
<https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveiselect>`_
method\&. It is the same as select(), but it returns a generator
instead of a list\&.

:param selector: A string containing a CSS selector\&.

:param namespaces: A dictionary mapping namespace prefixes
    used in the CSS selector to namespace URIs\&. By default,
    Beautiful Soup will pass in the prefixes it encountered while
    parsing the document\&.

:param limit: After finding this number of results, stop looking\&.

:param flags: Flags to be passed into Soup Sieve's
    `soupsieve\&.iselect() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveiselect>`_ method\&.

:param kwargs: Keyword arguments to be passed into Soup Sieve's
   `soupsieve\&.iselect() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveiselect>`_ method\&.

.fi
.PP
 
.SS " bool bs4\&.css\&.CSS\&.match ( self, str select, Optional[_NamespaceMapping]  namespaces = \fCNone\fP, int  flags = \fC0\fP, **Any kwargs)"

.PP
.nf
Check whether or not this `element\&.Tag` matches the given CSS selector\&.

This uses the Soup Sieve library\&. For more information, see
that library's documentation for the `soupsieve\&.match()
<https://facelessuser\&.github\&.io/soupsieve/api/#soupsievematch>`_
method\&.

:param: a CSS selector\&.

:param namespaces: A dictionary mapping namespace prefixes
    used in the CSS selector to namespace URIs\&. By default,
    Beautiful Soup will pass in the prefixes it encountered while
    parsing the document\&.

:param flags: Flags to be passed into Soup Sieve's
    `soupsieve\&.match()
    <https://facelessuser\&.github\&.io/soupsieve/api/#soupsievematch>`_
    method\&.

:param kwargs: Keyword arguments to be passed into SoupSieve's
    `soupsieve\&.match()
    <https://facelessuser\&.github\&.io/soupsieve/api/#soupsievematch>`_
    method\&.

.fi
.PP
 
.SS " \fBResultSet\fP[\fBelement\&.Tag\fP] bs4\&.css\&.CSS\&.select ( self, str select, Optional[_NamespaceMapping]  namespaces = \fCNone\fP, int  limit = \fC0\fP, int  flags = \fC0\fP, **Any kwargs)"

.PP
.nf
Perform a CSS selection operation on the current `element\&.Tag`\&.

This uses the Soup Sieve library\&. For more information, see
that library's documentation for the `soupsieve\&.select() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveselect>`_ method\&.

:param selector: A CSS selector\&.

:param namespaces: A dictionary mapping namespace prefixes
    used in the CSS selector to namespace URIs\&. By default,
    Beautiful Soup will pass in the prefixes it encountered while
    parsing the document\&.

:param limit: After finding this number of results, stop looking\&.

:param flags: Flags to be passed into Soup Sieve's
    `soupsieve\&.select() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveselect>`_ method\&.

:param kwargs: Keyword arguments to be passed into Soup Sieve's
   `soupsieve\&.select() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveselect>`_ method\&.

.fi
.PP
 
.SS " \fBelement\&.Tag\fP | None bs4\&.css\&.CSS\&.select_one ( self, str select, Optional[_NamespaceMapping]  namespaces = \fCNone\fP, int  flags = \fC0\fP, **Any kwargs)"

.PP
.nf
Perform a CSS selection operation on the current Tag and return the
first result, if any\&.

This uses the Soup Sieve library\&. For more information, see
that library's documentation for the `soupsieve\&.select_one() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveselect_one>`_ method\&.

:param selector: A CSS selector\&.

:param namespaces: A dictionary mapping namespace prefixes
   used in the CSS selector to namespace URIs\&. By default,
   Beautiful Soup will use the prefixes it encountered while
   parsing the document\&.

:param flags: Flags to be passed into Soup Sieve's
    `soupsieve\&.select_one() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveselect_one>`_ method\&.

:param kwargs: Keyword arguments to be passed into Soup Sieve's
   `soupsieve\&.select_one() <https://facelessuser\&.github\&.io/soupsieve/api/#soupsieveselect_one>`_ method\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "bs4\&.css\&.CSS\&.api"

.SS "bs4\&.css\&.CSS\&.tag"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
