.TH "bs4.tests.test_dammit.TestUnicodeDammit" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_dammit.TestUnicodeDammit
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_unicode_input\fP (self)"
.br
.ti -1c
.RI "\fBtest_smart_quotes_to\fP (self, smart_quotes_to, expect_converted)"
.br
.ti -1c
.RI "\fBtest_detect_utf8\fP (self)"
.br
.ti -1c
.RI "\fBtest_convert_hebrew\fP (self)"
.br
.ti -1c
.RI "\fBtest_dont_see_smart_quotes_where_there_are_none\fP (self)"
.br
.ti -1c
.RI "\fBtest_ignore_inappropriate_codecs\fP (self)"
.br
.ti -1c
.RI "\fBtest_ignore_invalid_codecs\fP (self)"
.br
.ti -1c
.RI "\fBtest_exclude_encodings\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Standalone tests of UnicodeDammit\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "bs4\&.tests\&.test_dammit\&.TestUnicodeDammit\&.test_convert_hebrew ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestUnicodeDammit\&.test_detect_utf8 ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestUnicodeDammit\&.test_dont_see_smart_quotes_where_there_are_none ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestUnicodeDammit\&.test_exclude_encodings ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestUnicodeDammit\&.test_ignore_inappropriate_codecs ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestUnicodeDammit\&.test_ignore_invalid_codecs ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestUnicodeDammit\&.test_smart_quotes_to ( self,  smart_quotes_to,  expect_converted)"

.PP
.nf
Verify the functionality of the smart_quotes_to argument
to the UnicodeDammit constructor\&.
.fi
.PP
 
.SS "bs4\&.tests\&.test_dammit\&.TestUnicodeDammit\&.test_unicode_input ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
