.TH "bs4.tests.test_tree.TestFindAll" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_tree.TestFindAll
.SH SYNOPSIS
.br
.PP
.PP
Inherits SoupTest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_find_all_with_no_arguments_only_finds_tags\fP (self)"
.br
.ti -1c
.RI "\fBtest_find_all_text_nodes\fP (self)"
.br
.ti -1c
.RI "\fBtest_find_all_limit\fP (self)"
.br
.ti -1c
.RI "\fBtest_calling_a_tag_is_calling_findall\fP (self)"
.br
.ti -1c
.RI "\fBtest_find_all_with_self_referential_data_structure_does_not_cause_infinite_recursion\fP (self)"
.br
.ti -1c
.RI "\fBtest_find_all_resultset\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Basic tests of the find_all() method\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "bs4\&.tests\&.test_tree\&.TestFindAll\&.test_calling_a_tag_is_calling_findall ( self)"

.SS "bs4\&.tests\&.test_tree\&.TestFindAll\&.test_find_all_limit ( self)"

.PP
.nf
You can limit the number of items returned by find_all\&.
.fi
.PP
 
.SS "bs4\&.tests\&.test_tree\&.TestFindAll\&.test_find_all_resultset ( self)"

.PP
.nf
All find_all calls return a ResultSet
.fi
.PP
 
.SS "bs4\&.tests\&.test_tree\&.TestFindAll\&.test_find_all_text_nodes ( self)"

.PP
.nf
You can search the tree for text nodes\&.
.fi
.PP
 
.SS "bs4\&.tests\&.test_tree\&.TestFindAll\&.test_find_all_with_no_arguments_only_finds_tags ( self)"

.SS "bs4\&.tests\&.test_tree\&.TestFindAll\&.test_find_all_with_self_referential_data_structure_does_not_cause_infinite_recursion ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
