.TH "bs4.filter.TagNameMatchRule" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.filter.TagNameMatchRule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbs4\&.filter\&.MatchRule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBmatches_tag\fP (self, \fBTag\fP tag)"
.br
.in -1c

Public Member Functions inherited from \fBbs4\&.filter\&.MatchRule\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, Optional[Union[str, bytes]] \fBstring\fP=None, Optional[\fB_RegularExpressionProtocol\fP] \fBpattern\fP=None, Optional[Callable] \fBfunction\fP=None, Optional[bool] \fBpresent\fP=None, Optional[bool] \fBexclude_everything\fP=None)"
.br
.ti -1c
.RI "bool \fBmatches_string\fP (self, Optional[str] \fBstring\fP)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, Any other)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "Optional \fBfunction\fP [_TagMatchFunction]"
.br
.in -1c

Static Public Attributes inherited from \fBbs4\&.filter\&.MatchRule\fP
.in +1c
.ti -1c
.RI "Optional \fBstring\fP [str]"
.br
.ti -1c
.RI "Optional \fBpattern\fP [\fB_RegularExpressionProtocol\fP]"
.br
.ti -1c
.RI "Optional \fBpresent\fP [bool]"
.br
.ti -1c
.RI "Optional \fBexclude_everything\fP [bool]"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBbs4\&.filter\&.MatchRule\fP
.in +1c
.ti -1c
.RI "\fBstring\fP"
.br
.ti -1c
.RI "\fBpattern\fP"
.br
.ti -1c
.RI "\fBfunction\fP"
.br
.ti -1c
.RI "\fBpresent\fP"
.br
.ti -1c
.RI "\fBexclude_everything\fP"
.br
.in -1c

Protected Member Functions inherited from \fBbs4\&.filter\&.MatchRule\fP
.in +1c
.ti -1c
.RI "Optional[bool] \fB_base_match\fP (self, Optional[str] \fBstring\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A MatchRule implementing the rules for matches against tag name\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " bool bs4\&.filter\&.TagNameMatchRule\&.matches_tag ( self, \fBTag\fP tag)"

.SH "Member Data Documentation"
.PP 
.SS "Optional bs4\&.filter\&.TagNameMatchRule\&.function [_TagMatchFunction]\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
