.TH "bs4.dammit.EntitySubstitution" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.dammit.EntitySubstitution
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBbs4\&.formatter\&.Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "str \fBquoted_attribute_value\fP (cls, str value)"
.br
.ti -1c
.RI "str \fBsubstitute_xml\fP (cls, str value, bool make_quoted_attribute=False)"
.br
.ti -1c
.RI "str \fBsubstitute_xml_containing_entities\fP (cls, str value, bool make_quoted_attribute=False)"
.br
.ti -1c
.RI "str \fBsubstitute_html\fP (cls, str s)"
.br
.ti -1c
.RI "str \fBsubstitute_html5\fP (cls, str s)"
.br
.ti -1c
.RI "str \fBsubstitute_html5_raw\fP (cls, str s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCHARACTER_TO_HTML_ENTITY\fP"
.br
.ti -1c
.RI "\fBHTML_ENTITY_TO_CHARACTER\fP"
.br
.ti -1c
.RI "\fBCHARACTER_TO_HTML_ENTITY_RE\fP"
.br
.ti -1c
.RI "\fBCHARACTER_TO_HTML_ENTITY_WITH_AMPERSAND_RE\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "Dict \fBHTML_ENTITY_TO_CHARACTER\fP [str, str]"
.br
.ti -1c
.RI "Dict \fBCHARACTER_TO_HTML_ENTITY\fP [str, str]"
.br
.ti -1c
.RI "Pattern \fBCHARACTER_TO_HTML_ENTITY_RE\fP [str]"
.br
.ti -1c
.RI "Pattern \fBCHARACTER_TO_HTML_ENTITY_WITH_AMPERSAND_RE\fP [str]"
.br
.ti -1c
.RI "dict \fBCHARACTER_TO_XML_ENTITY\fP"
.br
.ti -1c
.RI "\fBANY_ENTITY_RE\fP = re\&.compile('&(#\\\\d+|#x[0\-9a\-fA\-F]+|\\\\w+);', re\&.I)"
.br
.ti -1c
.RI "Pattern \fBBARE_AMPERSAND_OR_BRACKET\fP"
.br
.ti -1c
.RI "Pattern \fBAMPERSAND_OR_BRACKET\fP = re\&.compile('([<>&])')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "None \fB_populate_class_variables\fP (cls)"
.br
.ti -1c
.RI "str \fB_substitute_html_entity\fP (cls, re\&.Match matchobj)"
.br
.ti -1c
.RI "str \fB_substitute_xml_entity\fP (cls, re\&.Match matchobj)"
.br
.ti -1c
.RI "str \fB_escape_entity_name\fP (cls, re\&.Match matchobj)"
.br
.ti -1c
.RI "str \fB_escape_unrecognized_entity_name\fP (cls, re\&.Match matchobj)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_substitute_html_entity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The ability to substitute XML or HTML entities for certain characters\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str bs4\&.dammit\&.EntitySubstitution\&._escape_entity_name ( cls, re\&.Match matchobj)\fC [protected]\fP"

.SS " str bs4\&.dammit\&.EntitySubstitution\&._escape_unrecognized_entity_name ( cls, re\&.Match matchobj)\fC [protected]\fP"

.SS " None bs4\&.dammit\&.EntitySubstitution\&._populate_class_variables ( cls)\fC [protected]\fP"

.PP
.nf
Initialize variables used by this class to manage the plethora of
HTML5 named entities\&.

This function sets the following class variables:

CHARACTER_TO_HTML_ENTITY - A mapping of Unicode strings like '⦨' to
entity names like 'angmsdaa'\&. When a single Unicode string has
multiple entity names, we try to choose the most commonly-used
name\&.

HTML_ENTITY_TO_CHARACTER: A mapping of entity names like 'angmsdaa' to
Unicode strings like '⦨'\&.

CHARACTER_TO_HTML_ENTITY_RE: A regular expression matching (almost) any
Unicode string that corresponds to an HTML5 named entity\&.

CHARACTER_TO_HTML_ENTITY_WITH_AMPERSAND_RE: A very similar
regular expression to CHARACTER_TO_HTML_ENTITY_RE, but which
also matches unescaped ampersands\&. This is used by the 'html'
formatted to provide backwards-compatibility, even though the HTML5
spec allows most ampersands to go unescaped\&.

.fi
.PP
 
.SS " str bs4\&.dammit\&.EntitySubstitution\&._substitute_html_entity ( cls, re\&.Match matchobj)\fC [protected]\fP"

.PP
.nf
Used with a regular expression to substitute the
appropriate HTML entity for a special character string\&.
.fi
.PP
 
.SS " str bs4\&.dammit\&.EntitySubstitution\&._substitute_xml_entity ( cls, re\&.Match matchobj)\fC [protected]\fP"

.PP
.nf
Used with a regular expression to substitute the
appropriate XML entity for a special character string\&.
.fi
.PP
 
.SS " str bs4\&.dammit\&.EntitySubstitution\&.quoted_attribute_value ( cls, str value)"

.PP
.nf
Make a value into a quoted XML attribute, possibly escaping it\&.

 Most strings will be quoted using double quotes\&.

  Bob's Bar -> 'Bob's Bar'

 If a string contains double quotes, it will be quoted using
 single quotes\&.

  Welcome to 'my bar' -> 'Welcome to 'my bar''

 If a string contains both single and double quotes, the
 double quotes will be escaped, and the string will be quoted
 using double quotes\&.

  Welcome to 'Bob's Bar' -> Welcome to &quot;Bob's bar&quot;

:param value: The XML attribute value to quote
:return: The quoted value

.fi
.PP
 
.SS " str bs4\&.dammit\&.EntitySubstitution\&.substitute_html ( cls, str s)"

.PP
.nf
Replace certain Unicode characters with named HTML entities\&.

This differs from ``data\&.encode(encoding, 'xmlcharrefreplace')``
in that the goal is to make the result more readable (to those
with ASCII displays) rather than to recover from
errors\&. There's absolutely nothing wrong with a UTF-8 string
containg a LATIN SMALL LETTER E WITH ACUTE, but replacing that
character with '&eacute;' will make it more readable to some
people\&.

:param s: The string to be modified\&.
:return: The string with some Unicode characters replaced with
   HTML entities\&.

.fi
.PP
 
.SS " str bs4\&.dammit\&.EntitySubstitution\&.substitute_html5 ( cls, str s)"

.PP
.nf
Replace certain Unicode characters with named HTML entities
using HTML5 rules\&.

Specifically, this method is much less aggressive about
escaping ampersands than substitute_html\&. Only ambiguous
ampersands are escaped, per the HTML5 standard:

'An ambiguous ampersand is a U+0026 AMPERSAND character (&)
that is followed by one or more ASCII alphanumerics, followed
by a U+003B SEMICOLON character (;), where these characters do
not match any of the names given in the named character
references section\&.'

Unlike substitute_html5_raw, this method assumes HTML entities
were converted to Unicode characters on the way in, as
Beautiful Soup does\&. By the time Beautiful Soup does its work,
the only ambiguous ampersands that need to be escaped are the
ones that were escaped in the original markup when mentioning
HTML entities\&.

:param s: The string to be modified\&.
:return: The string with some Unicode characters replaced with
   HTML entities\&.

.fi
.PP
 
.SS " str bs4\&.dammit\&.EntitySubstitution\&.substitute_html5_raw ( cls, str s)"

.PP
.nf
Replace certain Unicode characters with named HTML entities
using HTML5 rules\&.

substitute_html5_raw is similar to substitute_html5 but it is
designed for standalone use (whereas substitute_html5 is
designed for use with Beautiful Soup)\&.

:param s: The string to be modified\&.
:return: The string with some Unicode characters replaced with
   HTML entities\&.

.fi
.PP
 
.SS " str bs4\&.dammit\&.EntitySubstitution\&.substitute_xml ( cls, str value, bool  make_quoted_attribute = \fCFalse\fP)"

.PP
.nf
Replace special XML characters with named XML entities\&.

The less-than sign will become &lt;, the greater-than sign
will become &gt;, and any ampersands will become &amp;\&. If you
want ampersands that seem to be part of an entity definition
to be left alone, use `substitute_xml_containing_entities`
instead\&.

:param value: A string to be substituted\&.

:param make_quoted_attribute: If True, then the string will be
 quoted, as befits an attribute value\&.

:return: A version of ``value`` with special characters replaced
 with named entities\&.

.fi
.PP
 
.SS " str bs4\&.dammit\&.EntitySubstitution\&.substitute_xml_containing_entities ( cls, str value, bool  make_quoted_attribute = \fCFalse\fP)"

.PP
.nf
Substitute XML entities for special XML characters\&.

:param value: A string to be substituted\&. The less-than sign will
  become &lt;, the greater-than sign will become &gt;, and any
  ampersands that are not part of an entity defition will
  become &amp;\&.

:param make_quoted_attribute: If True, then the string will be
 quoted, as befits an attribute value\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "bs4\&.dammit\&.EntitySubstitution\&._substitute_html_entity\fC [protected]\fP"

.SS "Pattern bs4\&.dammit\&.EntitySubstitution\&.AMPERSAND_OR_BRACKET = re\&.compile('([<>&])')\fC [static]\fP"

.SS "bs4\&.dammit\&.EntitySubstitution\&.ANY_ENTITY_RE = re\&.compile('&(#\\\\d+|#x[0\-9a\-fA\-F]+|\\\\w+);', re\&.I)\fC [static]\fP"

.SS "Pattern bs4\&.dammit\&.EntitySubstitution\&.BARE_AMPERSAND_OR_BRACKET\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  re\&.compile(
        "([<>]|" "&(?!#\\\\d+;|#x[0\-9a\-fA\-F]+;|\\\\w+;)" ")"
    )
.fi

.SS "Dict bs4\&.dammit\&.EntitySubstitution\&.CHARACTER_TO_HTML_ENTITY [str, str]\fC [static]\fP"

.SS "bs4\&.dammit\&.EntitySubstitution\&.CHARACTER_TO_HTML_ENTITY"

.SS "Pattern bs4\&.dammit\&.EntitySubstitution\&.CHARACTER_TO_HTML_ENTITY_RE [str]\fC [static]\fP"

.SS "bs4\&.dammit\&.EntitySubstitution\&.CHARACTER_TO_HTML_ENTITY_RE"

.SS "Pattern bs4\&.dammit\&.EntitySubstitution\&.CHARACTER_TO_HTML_ENTITY_WITH_AMPERSAND_RE [str]\fC [static]\fP"

.SS "bs4\&.dammit\&.EntitySubstitution\&.CHARACTER_TO_HTML_ENTITY_WITH_AMPERSAND_RE"

.SS "dict bs4\&.dammit\&.EntitySubstitution\&.CHARACTER_TO_XML_ENTITY\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  {
        "'": "apos",
        '"': "quot",
        "&": "amp",
        "<": "lt",
        ">": "gt",
    }
.fi

.SS "Dict bs4\&.dammit\&.EntitySubstitution\&.HTML_ENTITY_TO_CHARACTER [str, str]\fC [static]\fP"

.SS "bs4\&.dammit\&.EntitySubstitution\&.HTML_ENTITY_TO_CHARACTER"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
