.TH "bs4.tests.test_pageelement.TestFormatters" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_pageelement.TestFormatters
.SH SYNOPSIS
.br
.PP
.PP
Inherits SoupTest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_default_formatter_is_minimal\fP (self)"
.br
.ti -1c
.RI "\fBtest_formatter_html\fP (self)"
.br
.ti -1c
.RI "\fBtest_formatter_html5\fP (self)"
.br
.ti -1c
.RI "\fBtest_formatter_minimal\fP (self)"
.br
.ti -1c
.RI "\fBtest_formatter_null\fP (self)"
.br
.ti -1c
.RI "\fBtest_formatter_custom\fP (self)"
.br
.ti -1c
.RI "\fBtest_formatter_is_run_on_attribute_values\fP (self)"
.br
.ti -1c
.RI "\fBtest_formatter_skips_script_tag_for_html_documents\fP (self)"
.br
.ti -1c
.RI "\fBtest_formatter_skips_style_tag_for_html_documents\fP (self)"
.br
.ti -1c
.RI "\fBtest_prettify_leaves_preformatted_text_alone\fP (self)"
.br
.ti -1c
.RI "\fBtest_prettify_handles_nested_string_literal_tags\fP (self)"
.br
.ti -1c
.RI "\fBtest_prettify_accepts_formatter_function\fP (self)"
.br
.ti -1c
.RI "\fBtest_prettify_outputs_unicode_by_default\fP (self)"
.br
.ti -1c
.RI "\fBtest_prettify_can_encode_data\fP (self)"
.br
.ti -1c
.RI "\fBtest_html_entity_substitution_off_by_default\fP (self)"
.br
.ti -1c
.RI "\fBtest_encoding_substitution\fP (self)"
.br
.ti -1c
.RI "\fBtest_encoding_substitution_doesnt_happen_if_tag_is_strained\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Test the formatting feature, used by methods like decode() and
prettify(), and the formatters themselves\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_default_formatter_is_minimal ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_encoding_substitution ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_encoding_substitution_doesnt_happen_if_tag_is_strained ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_formatter_custom ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_formatter_html ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_formatter_html5 ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_formatter_is_run_on_attribute_values ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_formatter_minimal ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_formatter_null ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_formatter_skips_script_tag_for_html_documents ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_formatter_skips_style_tag_for_html_documents ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_html_entity_substitution_off_by_default ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_prettify_accepts_formatter_function ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_prettify_can_encode_data ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_prettify_handles_nested_string_literal_tags ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_prettify_leaves_preformatted_text_alone ( self)"

.SS "bs4\&.tests\&.test_pageelement\&.TestFormatters\&.test_prettify_outputs_unicode_by_default ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
