.TH "bs4.tests.test_formatter.TestFormatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_formatter.TestFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits SoupTest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_default_attributes\fP (self)"
.br
.ti -1c
.RI "\fBtest_sort_attributes\fP (self)"
.br
.ti -1c
.RI "\fBtest_empty_attributes_are_booleans\fP (self)"
.br
.ti -1c
.RI "\fBtest_indent\fP (self, indent, expect)"
.br
.ti -1c
.RI "\fBtest_default_indent_value\fP (self)"
.br
.ti -1c
.RI "\fBtest_indent_subclasses\fP (self, formatter, expect)"
.br
.ti -1c
.RI "\fBtest_entity_substitution\fP (self, s, expect_html, expect_html5)"
.br
.ti -1c
.RI "\fBtest_entity_round_trip\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcalled_with\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.test_default_attributes ( self)"

.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.test_default_indent_value ( self)"

.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.test_empty_attributes_are_booleans ( self)"

.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.test_entity_round_trip ( self)"

.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.test_entity_substitution ( self,  s,  expect_html,  expect_html5)"

.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.test_indent ( self,  indent,  expect)"

.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.test_indent_subclasses ( self,  formatter,  expect)"

.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.test_sort_attributes ( self)"

.SH "Member Data Documentation"
.PP 
.SS "bs4\&.tests\&.test_formatter\&.TestFormatter\&.called_with"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
