.TH "bs4.builder._htmlparser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.builder._htmlparser
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBeautifulSoupHTMLParser\fP"
.br
.ti -1c
.RI "class \fBHTMLParserTreeBuilder\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBHTMLPARSER\fP = 'html\&.parser'"
.br
.ti -1c
.RI "\fB_DuplicateAttributeHandler\fP = Callable[[Dict[str, str], str, str], None]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Use the HTMLParser library to parse HTML files that aren't too bad\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "bs4\&.builder\&._htmlparser\&._DuplicateAttributeHandler = Callable[[Dict[str, str], str, str], None]\fC [protected]\fP"

.SS "str bs4\&.builder\&._htmlparser\&.HTMLPARSER = 'html\&.parser'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
