.TH "bs4.tests.test_navigablestring.TestNavigableStringSubclasses" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_navigablestring.TestNavigableStringSubclasses
.SH SYNOPSIS
.br
.PP
.PP
Inherits SoupTest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_cdata\fP (self)"
.br
.ti -1c
.RI "\fBtest_cdata_is_never_formatted\fP (self)"
.br
.ti -1c
.RI "\fBtest_doctype_ends_in_newline\fP (self)"
.br
.ti -1c
.RI "\fBtest_declaration\fP (self)"
.br
.ti -1c
.RI "\fBtest_default_string_containers\fP (self)"
.br
.ti -1c
.RI "\fBtest_ruby_strings\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcount\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bs4\&.tests\&.test_navigablestring\&.TestNavigableStringSubclasses\&.test_cdata ( self)"

.SS "bs4\&.tests\&.test_navigablestring\&.TestNavigableStringSubclasses\&.test_cdata_is_never_formatted ( self)"

.PP
.nf
Text inside a CData object is passed into the formatter\&.

But the return value is ignored\&.

.fi
.PP
 
.SS "bs4\&.tests\&.test_navigablestring\&.TestNavigableStringSubclasses\&.test_declaration ( self)"

.SS "bs4\&.tests\&.test_navigablestring\&.TestNavigableStringSubclasses\&.test_default_string_containers ( self)"

.SS "bs4\&.tests\&.test_navigablestring\&.TestNavigableStringSubclasses\&.test_doctype_ends_in_newline ( self)"

.SS "bs4\&.tests\&.test_navigablestring\&.TestNavigableStringSubclasses\&.test_ruby_strings ( self)"

.SH "Member Data Documentation"
.PP 
.SS "bs4\&.tests\&.test_navigablestring\&.TestNavigableStringSubclasses\&.count"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
