.TH "bs4.builder._html5lib.Element" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.builder._html5lib.Element
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbs4\&.builder\&._html5lib\&.BeautifulSoupNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBTag\fP \fBelement\fP, 'BeautifulSoup' \fBsoup\fP, Optional[_NamespaceURL] \fBnamespace\fP)"
.br
.ti -1c
.RI "None \fBappendChild\fP (self, 'BeautifulSoupNode' node)"
.br
.ti -1c
.RI "\fBAttrList\fP \fBgetAttributes\fP (self)"
.br
.ti -1c
.RI "None \fBsetAttributes\fP (self, Optional[\fB_Html5libAttributes\fP] \fBattributes\fP)"
.br
.ti -1c
.RI "None \fBinsertText\fP (self, str data, Optional['BeautifulSoupNode'] \fBinsertBefore\fP=None)"
.br
.ti -1c
.RI "None \fBinsertBefore\fP (self, 'BeautifulSoupNode' node, 'BeautifulSoupNode' refNode)"
.br
.ti -1c
.RI "None \fBremoveChild\fP (self, 'Element' node)"
.br
.ti -1c
.RI "None \fBreparentChildren\fP (self, 'Element' new_parent)"
.br
.ti -1c
.RI "bool \fBhasContent\fP (self)"
.br
.ti -1c
.RI "treebuilder_base\&.Node \fBcloneNode\fP (self)"
.br
.ti -1c
.RI "Tuple[Optional[_NamespaceURL], str] \fBgetNameTuple\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBbs4\&.builder\&._html5lib\&.BeautifulSoupNode\fP
.in +1c
.ti -1c
.RI "int \fBnodeType\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBelement\fP"
.br
.ti -1c
.RI "\fBsoup\fP"
.br
.ti -1c
.RI "\fBnamespace\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBTag\fP \fBelement\fP"
.br
.ti -1c
.RI "Optional \fBnamespace\fP [_NamespaceURL]"
.br
.in -1c

Static Public Attributes inherited from \fBbs4\&.builder\&._html5lib\&.BeautifulSoupNode\fP
.in +1c
.ti -1c
.RI "\fBPageElement\fP \fBelement\fP"
.br
.ti -1c
.RI "str \fBsoup\fP : 'BeautifulSoup'"
.br
.ti -1c
.RI "Optional \fBnamespace\fP [_NamespaceURL]"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "TypeAlias \fB_Html5libAttributeName\fP = Union[str, Tuple[str, str]]"
.br
.ti -1c
.RI "TypeAlias \fB_Html5libAttributes\fP = Dict[\fB_Html5libAttributeName\fP, str]"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBattributes\fP = property(\fBgetAttributes\fP, \fBsetAttributes\fP)"
.br
.ti -1c
.RI "\fBnameTuple\fP = property(\fBgetNameTuple\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bs4\&.builder\&._html5lib\&.Element\&.__init__ ( self, \fBTag\fP element, 'BeautifulSoup' soup, Optional[_NamespaceURL]
     namespace)"

.SH "Member Function Documentation"
.PP 
.SS " None bs4\&.builder\&._html5lib\&.Element\&.appendChild ( self, 'BeautifulSoupNode' node)"

.SS " treebuilder_base\&.Node bs4\&.builder\&._html5lib\&.Element\&.cloneNode ( self)"

.PP
Reimplemented from \fBbs4\&.builder\&._html5lib\&.BeautifulSoupNode\fP\&.
.SS " \fBAttrList\fP bs4\&.builder\&._html5lib\&.Element\&.getAttributes ( self)"

.SS " Tuple[Optional[_NamespaceURL], str] bs4\&.builder\&._html5lib\&.Element\&.getNameTuple ( self)"

.SS " bool bs4\&.builder\&._html5lib\&.Element\&.hasContent ( self)"

.SS " None bs4\&.builder\&._html5lib\&.Element\&.insertBefore ( self, 'BeautifulSoupNode' node, 'BeautifulSoupNode'
     refNode)"

.SS " None bs4\&.builder\&._html5lib\&.Element\&.insertText ( self, str data, Optional['BeautifulSoupNode']  insertBefore = \fCNone\fP)"

.SS " None bs4\&.builder\&._html5lib\&.Element\&.removeChild ( self, 'Element' node)"

.SS " None bs4\&.builder\&._html5lib\&.Element\&.reparentChildren ( self, 'Element' new_parent)"

.PP
.nf
Move all of this tag's children into another tag\&.
.fi
.PP
 
.SS " None bs4\&.builder\&._html5lib\&.Element\&.setAttributes ( self, Optional[\fB_Html5libAttributes\fP] attributes)"

.SH "Member Data Documentation"
.PP 
.SS "TypeAlias bs4\&.builder\&._html5lib\&.Element\&._Html5libAttributeName = Union[str, Tuple[str, str]]\fC [static]\fP, \fC [protected]\fP"

.SS "TypeAlias bs4\&.builder\&._html5lib\&.Element\&._Html5libAttributes = Dict[\fB_Html5libAttributeName\fP, str]\fC [static]\fP, \fC [protected]\fP"

.SS "\fBTag\fP bs4\&.builder\&._html5lib\&.Element\&.element\fC [static]\fP"

.SS "bs4\&.builder\&._html5lib\&.Element\&.element"

.SS "bs4\&.builder\&._html5lib\&.Element\&.name"

.SS "Optional bs4\&.builder\&._html5lib\&.Element\&.namespace [_NamespaceURL]\fC [static]\fP"

.SS "bs4\&.builder\&._html5lib\&.Element\&.namespace"

.SS "bs4\&.builder\&._html5lib\&.Element\&.soup"

.SH "Property Documentation"
.PP 
.SS "bs4\&.builder\&._html5lib\&.Element\&.attributes = property(\fBgetAttributes\fP, \fBsetAttributes\fP)\fC [static]\fP"

.SS "bs4\&.builder\&._html5lib\&.Element\&.nameTuple = property(\fBgetNameTuple\fP)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
