.TH "bs4.element.PageElement" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.element.PageElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBbs4\&.element\&.NavigableString\fP, and \fBbs4\&.element\&.Tag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fBsetup\fP (self, Optional[\fBTag\fP] \fBparent\fP=None, _AtMostOneElement \fBprevious_element\fP=None, _AtMostOneElement \fBnext_element\fP=None, _AtMostOneElement \fBprevious_sibling\fP=None, _AtMostOneElement \fBnext_sibling\fP=None)"
.br
.ti -1c
.RI "str \fBformat_string\fP (self, str s, Optional[_FormatterOrName] formatter)"
.br
.ti -1c
.RI "\fBFormatter\fP \fBformatter_for_name\fP (self, Union[_FormatterOrName, _EntitySubstitutionFunction] formatter_name)"
.br
.ti -1c
.RI "Self \fB__deepcopy__\fP (self, Dict[Any, Any] memo, bool recursive=False)"
.br
.ti -1c
.RI "Self \fB__copy__\fP (self)"
.br
.ti -1c
.RI "Iterator[str] \fBstripped_strings\fP (self)"
.br
.ti -1c
.RI "str \fBget_text\fP (self, str separator='', bool strip=False, Iterable[Type[\fBNavigableString\fP]] types=\fBdefault\fP)"
.br
.ti -1c
.RI "Self \fBreplace_with\fP (self, *\fBPageElement\fP args)"
.br
.ti -1c
.RI "\fBTag\fP \fBwrap\fP (self, \fBTag\fP wrap_inside)"
.br
.ti -1c
.RI "Self \fBextract\fP (self, Optional[int] _self_index=None)"
.br
.ti -1c
.RI "None \fBdecompose\fP (self)"
.br
.ti -1c
.RI "List[\fBPageElement\fP] \fBinsert_before\fP (self, *_InsertableElement args)"
.br
.ti -1c
.RI "List[\fBPageElement\fP] \fBinsert_after\fP (self, *_InsertableElement args)"
.br
.ti -1c
.RI "_AtMostOneElement \fBfind_next\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[_StrainableString] string=None, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_QueryResults \fBfind_all_next\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[_StrainableString] string=None, Optional[int] limit=None, int _stacklevel=2, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_AtMostOneElement \fBfind_next_sibling\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[_StrainableString] string=None, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_QueryResults \fBfind_next_siblings\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[_StrainableString] string=None, Optional[int] limit=None, int _stacklevel=2, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_AtMostOneElement \fBfind_previous\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[_StrainableString] string=None, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_QueryResults \fBfind_all_previous\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[_StrainableString] string=None, Optional[int] limit=None, int _stacklevel=2, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_AtMostOneElement \fBfind_previous_sibling\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[_StrainableString] string=None, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_QueryResults \fBfind_previous_siblings\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[_StrainableString] string=None, Optional[int] limit=None, int _stacklevel=2, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_AtMostOneElement \fBfind_parent\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_QueryResults \fBfind_parents\fP (self, \fB_FindMethodName\fP name=None, _StrainableAttributes attrs={}, Optional[int] limit=None, int _stacklevel=2, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_AtMostOneElement \fBnext\fP (self)"
.br
.ti -1c
.RI "_AtMostOneElement \fBprevious\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBnext_elements\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBself_and_next_elements\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBnext_siblings\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBself_and_next_siblings\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBprevious_elements\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBself_and_previous_elements\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBprevious_siblings\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBself_and_previous_siblings\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBTag\fP] \fBparents\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBself_and_parents\fP (self)"
.br
.ti -1c
.RI "bool \fBdecomposed\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBnextGenerator\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBnextSiblingGenerator\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBpreviousGenerator\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBpreviousSiblingGenerator\fP (self)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fBparentGenerator\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparent\fP"
.br
.ti -1c
.RI "\fBprevious_element\fP"
.br
.ti -1c
.RI "\fBnext_element\fP"
.br
.ti -1c
.RI "\fBnext_sibling\fP"
.br
.ti -1c
.RI "\fBprevious_sibling\fP"
.br
.ti -1c
.RI "\fBfind_all_next\fP"
.br
.ti -1c
.RI "\fBnext_elements\fP"
.br
.ti -1c
.RI "\fBfind_next_siblings\fP"
.br
.ti -1c
.RI "\fBnext_siblings\fP"
.br
.ti -1c
.RI "\fBfind_all_previous\fP"
.br
.ti -1c
.RI "\fBprevious_elements\fP"
.br
.ti -1c
.RI "\fBfind_previous_siblings\fP"
.br
.ti -1c
.RI "\fBprevious_siblings\fP"
.br
.ti -1c
.RI "\fBparents\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "Optional \fBknown_xml\fP = None"
.br
.ti -1c
.RI "Optional \fBparent\fP [\fBTag\fP]"
.br
.ti -1c
.RI "_AtMostOneElement \fBnext_element\fP"
.br
.ti -1c
.RI "_AtMostOneElement \fBprevious_element\fP"
.br
.ti -1c
.RI "_AtMostOneElement \fBnext_sibling\fP"
.br
.ti -1c
.RI "_AtMostOneElement \fBprevious_sibling\fP"
.br
.ti -1c
.RI "bool \fBhidden\fP = False"
.br
.ti -1c
.RI "\fBnextSibling\fP = _deprecated_alias('nextSibling', 'next_sibling', '4\&.0\&.0')"
.br
.ti -1c
.RI "\fBpreviousSibling\fP = _deprecated_alias('previousSibling', 'previous_sibling', '4\&.0\&.0')"
.br
.ti -1c
.RI "Iterable \fBdefault\fP = tuple()"
.br
.ti -1c
.RI "str \fBgetText\fP = \fBget_text\fP"
.br
.ti -1c
.RI "\fBreplaceWith\fP = _deprecated_function_alias('replaceWith', 'replace_with', '4\&.0\&.0')"
.br
.ti -1c
.RI "\fBfindNext\fP = _deprecated_function_alias('findNext', 'find_next', '4\&.0\&.0')"
.br
.ti -1c
.RI "\fBfindAllNext\fP = _deprecated_function_alias('findAllNext', 'find_all_next', '4\&.0\&.0')"
.br
.ti -1c
.RI "\fBfindNextSibling\fP"
.br
.ti -1c
.RI "\fBfindNextSiblings\fP"
.br
.ti -1c
.RI "\fBfetchNextSiblings\fP"
.br
.ti -1c
.RI "\fBfindPrevious\fP = _deprecated_function_alias('findPrevious', 'find_previous', '3\&.0\&.0')"
.br
.ti -1c
.RI "\fBfindAllPrevious\fP"
.br
.ti -1c
.RI "\fBfetchAllPrevious\fP"
.br
.ti -1c
.RI "\fBfindPreviousSibling\fP"
.br
.ti -1c
.RI "\fBfindPreviousSiblings\fP"
.br
.ti -1c
.RI "\fBfetchPreviousSiblings\fP"
.br
.ti -1c
.RI "\fBfindParent\fP = _deprecated_function_alias('findParent', 'find_parent', '4\&.0\&.0')"
.br
.ti -1c
.RI "\fBfindParents\fP = _deprecated_function_alias('findParents', 'find_parents', '4\&.0\&.0')"
.br
.ti -1c
.RI "\fBfetchParents\fP = _deprecated_function_alias('fetchParents', 'find_parents', '3\&.0\&.0')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fB_is_xml\fP (self)"
.br
.ti -1c
.RI "Iterator[str] \fB_all_strings\fP (self, bool strip=False, Iterable[type[\fBNavigableString\fP]] types=\fBdefault\fP)"
.br
.ti -1c
.RI "_AtMostOneElement \fB_last_descendant\fP (self, bool is_initialized=True, bool accept_self=True)"
.br
.ti -1c
.RI "_AtMostOneElement \fB_find_one\fP (self, Callable method, \fB_FindMethodName\fP name, _StrainableAttributes attrs, Optional[_StrainableString] string, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "_QueryResults \fB_find_all\fP (self, \fB_FindMethodName\fP name, _StrainableAttributes attrs, Optional[_StrainableString] string, Optional[int] limit, Iterator[\fBPageElement\fP] generator, int _stacklevel=3, **_StrainableAttribute kwargs)"
.br
.ti -1c
.RI "Iterator[\fBPageElement\fP] \fB_self_and\fP (self, Iterator[\fBPageElement\fP] other_generator)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fB_decomposed\fP"
.br
.ti -1c
.RI "\fB_lastRecursiveChild\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBtext\fP = property(\fBget_text\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An abstract class representing a single element in the parse tree\&.

`NavigableString`, `Tag`, etc\&. are all subclasses of
`PageElement`\&. For this reason you'll see a lot of methods that
return `PageElement`, but you'll never see an actual `PageElement`
object\&. For the most part you can think of `PageElement` as
meaning 'a `Tag` or a `NavigableString`\&.'

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " Self bs4\&.element\&.PageElement\&.__copy__ ( self)"

.PP
.nf
A copy of a PageElement can only be a deep copy, because
only one PageElement can occupy a given place in a parse tree\&.

.fi
.PP
 
.SS " Self bs4\&.element\&.PageElement\&.__deepcopy__ ( self, Dict[Any, Any] memo, bool  recursive = \fCFalse\fP)"

.PP
Reimplemented in \fBbs4\&.element\&.NavigableString\fP, and \fBbs4\&.element\&.Tag\fP\&.
.SS " Iterator[str] bs4\&.element\&.PageElement\&._all_strings ( self, bool  strip = \fCFalse\fP, Iterable[type[\fBNavigableString\fP]]  types = \fC\fBdefault\fP\fP)\fC [protected]\fP"

.PP
.nf
Yield all strings of certain classes, possibly stripping them\&.

This is implemented differently in `Tag` and `NavigableString`\&.

.fi
.PP
 
.PP
Reimplemented in \fBbs4\&.element\&.NavigableString\fP, and \fBbs4\&.element\&.Tag\fP\&.
.SS " _QueryResults bs4\&.element\&.PageElement\&._find_all ( self, \fB_FindMethodName\fP name, _StrainableAttributes attrs, Optional[_StrainableString] string, Optional[int] limit, Iterator[\fBPageElement\fP] generator, int  _stacklevel = \fC3\fP, **_StrainableAttribute kwargs)\fC [protected]\fP"

.PP
.nf
Iterates over a generator looking for things that match\&.
.fi
.PP
 
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&._find_one ( self, Callable method, \fB_FindMethodName\fP name, _StrainableAttributes attrs, Optional[_StrainableString] string, **_StrainableAttribute kwargs)\fC [protected]\fP"

.SS " bool bs4\&.element\&.PageElement\&._is_xml ( self)\fC [protected]\fP"

.PP
.nf
Is this element part of an XML tree or an HTML tree?

This is used in formatter_for_name, when deciding whether an
XMLFormatter or HTMLFormatter is more appropriate\&. It can be
inefficient, but it should be called very rarely\&.

.fi
.PP
 
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&._last_descendant ( self, bool  is_initialized = \fCTrue\fP, bool  accept_self = \fCTrue\fP)\fC [protected]\fP"

.PP
.nf
Finds the last element beneath this object to be parsed\&.

Special note to help you figure things out if your type
checking is tripped up by the fact that this method returns
_AtMostOneElement instead of PageElement: the only time
this method returns None is if `accept_self` is False and the
`PageElement` has no children--either it's a NavigableString
or an empty Tag\&.

:param is_initialized: Has `PageElement\&.setup` been called on
    this `PageElement` yet?

:param accept_self: Is ``self`` an acceptable answer to the
    question?

.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&._self_and ( self, Iterator[\fBPageElement\fP] other_generator)\fC [protected]\fP"

.PP
.nf
Modify a generator by yielding this element, then everything
yielded by the other generator\&.

.fi
.PP
 
.SS " None bs4\&.element\&.PageElement\&.decompose ( self)"

.PP
.nf
Recursively destroys this `PageElement` and its children\&.

The element will be removed from the tree and wiped out; so
will everything beneath it\&.

The behavior of a decomposed `PageElement` is undefined and you
should never use one for anything, but if you need to *check*
whether an element has been decomposed, you can use the
`PageElement\&.decomposed` property\&.

.fi
.PP
 
.SS " bool bs4\&.element\&.PageElement\&.decomposed ( self)"

.PP
.nf
Check whether a PageElement has been decomposed\&.
.fi
.PP
 
.SS " Self bs4\&.element\&.PageElement\&.extract ( self, Optional[int]  _self_index = \fCNone\fP)"

.PP
.nf
Destructively rips this element out of the tree\&.

:param _self_index: The location of this element in its parent's
   \&.contents, if known\&. Passing this in allows for a performance
   optimization\&.

:return: this `PageElement`, no longer part of the tree\&.

.fi
.PP
 
.SS " _QueryResults bs4\&.element\&.PageElement\&.find_all_next ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[_StrainableString]  string = \fCNone\fP, Optional[int]  limit = \fCNone\fP, int  _stacklevel = \fC2\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Find all `PageElement` objects that match the given criteria and
appear later in the document than this `PageElement`\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param string: A filter for a NavigableString with specific text\&.
:param limit: Stop looking after finding this many results\&.
:param _stacklevel: Used internally to improve warning messages\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _QueryResults bs4\&.element\&.PageElement\&.find_all_previous ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[_StrainableString]  string = \fCNone\fP, Optional[int]  limit = \fCNone\fP, int  _stacklevel = \fC2\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Look backwards in the document from this `PageElement` and find all
`PageElement` that match the given criteria\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param string: A filter for a `NavigableString` with specific text\&.
:param limit: Stop looking after finding this many results\&.
:param _stacklevel: Used internally to improve warning messages\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&.find_next ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[_StrainableString]  string = \fCNone\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Find the first PageElement that matches the given criteria and
appears later in the document than this PageElement\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param string: A filter for a NavigableString with specific text\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&.find_next_sibling ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[_StrainableString]  string = \fCNone\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Find the closest sibling to this PageElement that matches the
given criteria and appears later in the document\&.

All find_* methods take a common set of arguments\&. See the
online documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param string: A filter for a `NavigableString` with specific text\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _QueryResults bs4\&.element\&.PageElement\&.find_next_siblings ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[_StrainableString]  string = \fCNone\fP, Optional[int]  limit = \fCNone\fP, int  _stacklevel = \fC2\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Find all siblings of this `PageElement` that match the given criteria
and appear later in the document\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param string: A filter for a `NavigableString` with specific text\&.
:param limit: Stop looking after finding this many results\&.
:param _stacklevel: Used internally to improve warning messages\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&.find_parent ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Find the closest parent of this PageElement that matches the given
criteria\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param self: Whether the PageElement itself should be considered
   as one of its 'parents'\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _QueryResults bs4\&.element\&.PageElement\&.find_parents ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[int]  limit = \fCNone\fP, int  _stacklevel = \fC2\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Find all parents of this `PageElement` that match the given criteria\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param limit: Stop looking after finding this many results\&.
:param _stacklevel: Used internally to improve warning messages\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&.find_previous ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[_StrainableString]  string = \fCNone\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Look backwards in the document from this `PageElement` and find the
first `PageElement` that matches the given criteria\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param string: A filter for a `NavigableString` with specific text\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&.find_previous_sibling ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[_StrainableString]  string = \fCNone\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Returns the closest sibling to this `PageElement` that matches the
given criteria and appears earlier in the document\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param string: A filter for a `NavigableString` with specific text\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " _QueryResults bs4\&.element\&.PageElement\&.find_previous_siblings ( self, \fB_FindMethodName\fP  name = \fCNone\fP, _StrainableAttributes  attrs = \fC{}\fP, Optional[_StrainableString]  string = \fCNone\fP, Optional[int]  limit = \fCNone\fP, int  _stacklevel = \fC2\fP, **_StrainableAttribute kwargs)"

.PP
.nf
Returns all siblings to this PageElement that match the
given criteria and appear earlier in the document\&.

All find_* methods take a common set of arguments\&. See the online
documentation for detailed explanations\&.

:param name: A filter on tag name\&.
:param attrs: Additional filters on attribute values\&.
:param string: A filter for a NavigableString with specific text\&.
:param limit: Stop looking after finding this many results\&.
:param _stacklevel: Used internally to improve warning messages\&.
:kwargs: Additional filters on attribute values\&.

.fi
.PP
 
.SS " str bs4\&.element\&.PageElement\&.format_string ( self, str s, Optional[_FormatterOrName] formatter)"

.PP
.nf
Format the given string using the given formatter\&.

:param s: A string\&.
:param formatter: A Formatter object, or a string naming one of the standard formatters\&.

.fi
.PP
 
.SS " \fBFormatter\fP bs4\&.element\&.PageElement\&.formatter_for_name ( self, Union[_FormatterOrName, _EntitySubstitutionFunction]
     formatter_name)"

.PP
.nf
Look up or create a Formatter for the given identifier,
if necessary\&.

:param formatter: Can be a `Formatter` object (used as-is), a
    function (used as the entity substitution hook for an
    `bs4\&.formatter\&.XMLFormatter` or
    `bs4\&.formatter\&.HTMLFormatter`), or a string (used to look
    up an `bs4\&.formatter\&.XMLFormatter` or
    `bs4\&.formatter\&.HTMLFormatter` in the appropriate registry\&.
.fi
.PP
 
.SS " str bs4\&.element\&.PageElement\&.get_text ( self, str  separator = \fC''\fP, bool  strip = \fCFalse\fP, Iterable[Type[\fBNavigableString\fP]]  types = \fC\fBdefault\fP\fP)"

.PP
.nf
Get all child strings of this PageElement, concatenated using the
given separator\&.

:param separator: Strings will be concatenated using this separator\&.

:param strip: If True, strings will be stripped before being
    concatenated\&.

:param types: A tuple of NavigableString subclasses\&. Any
    strings of a subclass not found in this list will be
    ignored\&. Although there are exceptions, the default
    behavior in most cases is to consider only NavigableString
    and CData objects\&. That means no comments, processing
    instructions, etc\&.

:return: A string\&.

.fi
.PP
 
.SS " List[\fBPageElement\fP] bs4\&.element\&.PageElement\&.insert_after ( self, *_InsertableElement args)"

.PP
.nf
Makes the given element(s) the immediate successor of this one\&.

The elements will have the same `PageElement\&.parent` as this
one, and the given elements will occur immediately after this
one\&.

:param args: One or more PageElements\&.

:return The list of PageElements that were inserted\&.

.fi
.PP
 
.PP
Reimplemented in \fBbs4\&.BeautifulSoup\fP\&.
.SS " List[\fBPageElement\fP] bs4\&.element\&.PageElement\&.insert_before ( self, *_InsertableElement args)"

.PP
.nf
Makes the given element(s) the immediate predecessor of this one\&.

All the elements will have the same `PageElement\&.parent` as
this one, and the given elements will occur immediately before
this one\&.

:param args: One or more PageElements\&.

:return The list of PageElements that were inserted\&.

.fi
.PP
 
.PP
Reimplemented in \fBbs4\&.BeautifulSoup\fP\&.
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&.next ( self)"

.PP
.nf
The `PageElement`, if any, that was parsed just after this one\&.
.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.next_elements ( self)"

.PP
.nf
All PageElements that were parsed after this one\&.
.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.next_siblings ( self)"

.PP
.nf
All PageElements that are siblings of this one but were parsed
later\&.

.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.nextGenerator ( self)"

.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.nextSiblingGenerator ( self)"

.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.parentGenerator ( self)"

.SS " Iterator[\fBTag\fP] bs4\&.element\&.PageElement\&.parents ( self)"

.PP
.nf
All elements that are parents of this PageElement\&.

:yield: A sequence of Tags, ending with a BeautifulSoup object\&.

.fi
.PP
 
.SS " _AtMostOneElement bs4\&.element\&.PageElement\&.previous ( self)"

.PP
.nf
The `PageElement`, if any, that was parsed just before this one\&.
.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.previous_elements ( self)"

.PP
.nf
All PageElements that were parsed before this one\&.

:yield: A sequence of PageElements\&.

.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.previous_siblings ( self)"

.PP
.nf
All PageElements that are siblings of this one but were parsed
earlier\&.

:yield: A sequence of PageElements\&.

.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.previousGenerator ( self)"

.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.previousSiblingGenerator ( self)"

.SS " Self bs4\&.element\&.PageElement\&.replace_with ( self, *\fBPageElement\fP args)"

.PP
.nf
Replace this `PageElement` with one or more other `PageElement`,
objects, keeping the rest of the tree the same\&.

:return: This `PageElement`, no longer part of the tree\&.

.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.self_and_next_elements ( self)"

.PP
.nf
This PageElement, then all PageElements that were parsed after it\&.
.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.self_and_next_siblings ( self)"

.PP
.nf
This PageElement, then all of its siblings\&.
.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.self_and_parents ( self)"

.PP
.nf
This element, then all of its parents\&.

:yield: A sequence of PageElements, ending with a BeautifulSoup object\&.

.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.self_and_previous_elements ( self)"

.PP
.nf
This PageElement, then all elements that were parsed
earlier\&.
.fi
.PP
 
.SS " Iterator[\fBPageElement\fP] bs4\&.element\&.PageElement\&.self_and_previous_siblings ( self)"

.PP
.nf
This PageElement, then all of its siblings that were parsed
earlier\&.
.fi
.PP
 
.SS " None bs4\&.element\&.PageElement\&.setup ( self, Optional[\fBTag\fP]  parent = \fCNone\fP, _AtMostOneElement  previous_element = \fCNone\fP, _AtMostOneElement  next_element = \fCNone\fP, _AtMostOneElement  previous_sibling = \fCNone\fP, _AtMostOneElement  next_sibling = \fCNone\fP)"

.PP
.nf
Sets up the initial relations between this element and
other elements\&.

:param parent: The parent of this element\&.

:param previous_element: The element parsed immediately before
    this one\&.

:param next_element: The element parsed immediately after
    this one\&.

:param previous_sibling: The most recently encountered element
    on the same level of the parse tree as this one\&.

:param previous_sibling: The next element to be encountered
    on the same level of the parse tree as this one\&.

.fi
.PP
 
.SS " Iterator[str] bs4\&.element\&.PageElement\&.stripped_strings ( self)"

.PP
.nf
Yield all interesting strings in this PageElement, stripping them
first\&.

See `Tag` for information on which strings are considered
interesting in a given context\&.

.fi
.PP
 
.SS " \fBTag\fP bs4\&.element\&.PageElement\&.wrap ( self, \fBTag\fP wrap_inside)"

.PP
.nf
Wrap this `PageElement` inside a `Tag`\&.

:return: ``wrap_inside``, occupying the position in the tree that used
   to be occupied by this object, and with this object now inside it\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "bool bs4\&.element\&.PageElement\&._decomposed\fC [static]\fP, \fC [protected]\fP"

.SS "bs4\&.element\&.PageElement\&._lastRecursiveChild\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_alias(
        "_lastRecursiveChild", "_last_descendant", "4\&.0\&.0"
    )
.fi

.SS "Iterable bs4\&.element\&.PageElement\&.default = tuple()\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.fetchAllPrevious\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_function_alias(
        "fetchAllPrevious", "find_all_previous", "3\&.0\&.0"
    )
.fi

.SS "bs4\&.element\&.PageElement\&.fetchNextSiblings\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_function_alias(
        "fetchNextSiblings", "find_next_siblings", "3\&.0\&.0"
    )
.fi

.SS "bs4\&.element\&.PageElement\&.fetchParents = _deprecated_function_alias('fetchParents', 'find_parents', '3\&.0\&.0')\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.fetchPreviousSiblings\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_function_alias(
        "fetchPreviousSiblings", "find_previous_siblings", "3\&.0\&.0"
    )
.fi

.SS "bs4\&.element\&.PageElement\&.find_all_next"

.SS "bs4\&.element\&.PageElement\&.find_all_previous"

.SS "bs4\&.element\&.PageElement\&.find_next_siblings"

.SS "bs4\&.element\&.PageElement\&.find_previous_siblings"

.SS "bs4\&.element\&.PageElement\&.findAllNext = _deprecated_function_alias('findAllNext', 'find_all_next', '4\&.0\&.0')\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.findAllPrevious\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_function_alias(
        "findAllPrevious", "find_all_previous", "4\&.0\&.0"
    )
.fi

.SS "bs4\&.element\&.PageElement\&.findNext = _deprecated_function_alias('findNext', 'find_next', '4\&.0\&.0')\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.findNextSibling\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_function_alias(
        "findNextSibling", "find_next_sibling", "4\&.0\&.0"
    )
.fi

.SS "bs4\&.element\&.PageElement\&.findNextSiblings\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_function_alias(
        "findNextSiblings", "find_next_siblings", "4\&.0\&.0"
    )
.fi

.SS "bs4\&.element\&.PageElement\&.findParent = _deprecated_function_alias('findParent', 'find_parent', '4\&.0\&.0')\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.findParents = _deprecated_function_alias('findParents', 'find_parents', '4\&.0\&.0')\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.findPrevious = _deprecated_function_alias('findPrevious', 'find_previous', '3\&.0\&.0')\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.findPreviousSibling\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_function_alias(
        "findPreviousSibling", "find_previous_sibling", "4\&.0\&.0"
    )
.fi

.SS "bs4\&.element\&.PageElement\&.findPreviousSiblings\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  _deprecated_function_alias(
        "findPreviousSiblings", "find_previous_siblings", "4\&.0\&.0"
    )
.fi

.SS "str bs4\&.element\&.PageElement\&.getText = \fBget_text\fP\fC [static]\fP"

.SS "bool bs4\&.element\&.PageElement\&.hidden = False\fC [static]\fP"

.SS "Optional bs4\&.element\&.PageElement\&.known_xml = None\fC [static]\fP"

.SS "_AtMostOneElement bs4\&.element\&.PageElement\&.next_element\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.next_element"

.SS "bs4\&.element\&.PageElement\&.next_elements"

.SS "_AtMostOneElement bs4\&.element\&.PageElement\&.next_sibling\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.next_sibling"

.SS "bs4\&.element\&.PageElement\&.next_siblings"

.SS "bs4\&.element\&.PageElement\&.nextSibling = _deprecated_alias('nextSibling', 'next_sibling', '4\&.0\&.0')\fC [static]\fP"

.SS "Optional bs4\&.element\&.PageElement\&.parent [\fBTag\fP]\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.parent"

.SS "bs4\&.element\&.PageElement\&.parents"

.SS "_AtMostOneElement bs4\&.element\&.PageElement\&.previous_element\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.previous_element"

.SS "bs4\&.element\&.PageElement\&.previous_elements"

.SS "_AtMostOneElement bs4\&.element\&.PageElement\&.previous_sibling\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.previous_sibling"

.SS "bs4\&.element\&.PageElement\&.previous_siblings"

.SS "bs4\&.element\&.PageElement\&.previousSibling = _deprecated_alias('previousSibling', 'previous_sibling', '4\&.0\&.0')\fC [static]\fP"

.SS "bs4\&.element\&.PageElement\&.replaceWith = _deprecated_function_alias('replaceWith', 'replace_with', '4\&.0\&.0')\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "bs4\&.element\&.PageElement\&.text = property(\fBget_text\fP)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
