.TH "bs4.tests.test_filter.TestMatchRule" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_filter.TestMatchRule
.SH SYNOPSIS
.br
.PP
.PP
Inherits SoupTest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_constructor\fP (self, constructor_args, constructor_kwargs, result)"
.br
.ti -1c
.RI "\fBtest_empty_match_not_allowed\fP (self)"
.br
.ti -1c
.RI "\fBtest_full_match_not_allowed\fP (self)"
.br
.ti -1c
.RI "\fBtest_matches_string\fP (self, rule_kwargs, match_against, result)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBtag_function\fP (\fBTag\fP x)"
.br
.ti -1c
.RI "bool \fBstring_function\fP (str x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtag_function\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Tuple[Optional[str], Optional[str], Optional[Callable], Optional[bool]] \fB_tuple\fP (self, \fBMatchRule\fP rule)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " Tuple[Optional[str], Optional[str], Optional[Callable], Optional[bool]] bs4\&.tests\&.test_filter\&.TestMatchRule\&._tuple ( self, \fBMatchRule\fP
     rule)\fC [protected]\fP"

.SS " bool bs4\&.tests\&.test_filter\&.TestMatchRule\&.string_function (str x)\fC [static]\fP"

.SS " bool bs4\&.tests\&.test_filter\&.TestMatchRule\&.tag_function (\fBTag\fP x)\fC [static]\fP"

.SS "bs4\&.tests\&.test_filter\&.TestMatchRule\&.test_constructor ( self,  constructor_args,  constructor_kwargs,  result)"

.SS "bs4\&.tests\&.test_filter\&.TestMatchRule\&.test_empty_match_not_allowed ( self)"

.SS "bs4\&.tests\&.test_filter\&.TestMatchRule\&.test_full_match_not_allowed ( self)"

.SS "bs4\&.tests\&.test_filter\&.TestMatchRule\&.test_matches_string ( self,  rule_kwargs,  match_against,  result)"

.SH "Member Data Documentation"
.PP 
.SS "bs4\&.tests\&.test_filter\&.TestMatchRule\&.tag_function"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
