.TH "bs4.builder" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.builder
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_html5lib\fP"
.br
.ti -1c
.RI "namespace \fB_htmlparser\fP"
.br
.ti -1c
.RI "namespace \fB_lxml\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDetectsXMLParsedAsHTML\fP"
.br
.ti -1c
.RI "class \fBHTMLTreeBuilder\fP"
.br
.ti -1c
.RI "class \fBSAXTreeBuilder\fP"
.br
.ti -1c
.RI "class \fBTreeBuilder\fP"
.br
.ti -1c
.RI "class \fBTreeBuilderRegistry\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBregister_treebuilders_from\fP (ModuleType module)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBFAST\fP = 'fast'"
.br
.ti -1c
.RI "str \fBPERMISSIVE\fP = 'permissive'"
.br
.ti -1c
.RI "str \fBSTRICT\fP = 'strict'"
.br
.ti -1c
.RI "str \fBXML\fP = 'xml'"
.br
.ti -1c
.RI "str \fBHTML\fP = 'html'"
.br
.ti -1c
.RI "str \fBHTML_5\fP = 'html5'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " None bs4\&.builder\&.register_treebuilders_from (ModuleType module)"

.PP
.nf
Copy TreeBuilders from the given module into this module\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "str bs4\&.builder\&.FAST = 'fast'"

.SS "str bs4\&.builder\&.HTML = 'html'"

.SS "str bs4\&.builder\&.HTML_5 = 'html5'"

.SS "str bs4\&.builder\&.PERMISSIVE = 'permissive'"

.SS "str bs4\&.builder\&.STRICT = 'strict'"

.SS "str bs4\&.builder\&.XML = 'xml'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
