.TH "bs4.tests.test_css" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_css
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestCSSSelectors\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Type \fBSOUPSIEVE_EXCEPTION_ON_UNSUPPORTED_PSEUDOCLASS\fP [Exception]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bs4\&.tests\&.test_css\&.SOUPSIEVE_EXCEPTION_ON_UNSUPPORTED_PSEUDOCLASS [Exception]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
