.TH "bs4.tests.test_htmlparser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_htmlparser
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestHTMLParserTreeBuilder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tests to ensure that the html\&.parser tree builder generates good
trees\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
