.TH "bs4.css" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.css
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCSS\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Optional \fBsoupsieve\fP [ModuleType]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Integration code for CSS selectors using `Soup Sieve <https://facelessuser\&.github\&.io/soupsieve/>`_ (pypi: ``soupsieve``)\&.

Acquire a `CSS` object through the `element\&.Tag\&.css` attribute of
the starting point of your CSS selector, or (if you want to run a
selector against the entire document) of the `BeautifulSoup` object
itself\&.

The main advantage of doing this instead of using ``soupsieve``
functions is that you don't need to keep passing the `element\&.Tag` to be
selected against, since the `CSS` object is permanently scoped to that
`element\&.Tag`\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "bs4\&.css\&.soupsieve [ModuleType]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
