.TH "bs4.tests.test_soup.TestEncodingConversion" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_soup.TestEncodingConversion
.SH SYNOPSIS
.br
.PP
.PP
Inherits SoupTest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetup_method\fP (self)"
.br
.ti -1c
.RI "\fBtest_ascii_in_unicode_out\fP (self)"
.br
.ti -1c
.RI "\fBtest_unicode_in_unicode_out\fP (self)"
.br
.ti -1c
.RI "\fBtest_utf8_in_unicode_out\fP (self)"
.br
.ti -1c
.RI "\fBtest_utf8_out\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBunicode_data\fP"
.br
.ti -1c
.RI "\fButf8_data\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bs4\&.tests\&.test_soup\&.TestEncodingConversion\&.setup_method ( self)"

.SS "bs4\&.tests\&.test_soup\&.TestEncodingConversion\&.test_ascii_in_unicode_out ( self)"

.SS "bs4\&.tests\&.test_soup\&.TestEncodingConversion\&.test_unicode_in_unicode_out ( self)"

.SS "bs4\&.tests\&.test_soup\&.TestEncodingConversion\&.test_utf8_in_unicode_out ( self)"

.SS "bs4\&.tests\&.test_soup\&.TestEncodingConversion\&.test_utf8_out ( self)"

.SH "Member Data Documentation"
.PP 
.SS "bs4\&.tests\&.test_soup\&.TestEncodingConversion\&.unicode_data"

.SS "bs4\&.tests\&.test_soup\&.TestEncodingConversion\&.utf8_data"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
