.TH "bs4.tests.test_dammit.TestEncodingDetector" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bs4.tests.test_dammit.TestEncodingDetector
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_encoding_detector_replaces_junk_in_encoding_name_with_replacement_character\fP (self)"
.br
.ti -1c
.RI "\fBtest_detect_html5_style_meta_tag\fP (self)"
.br
.ti -1c
.RI "\fBtest_last_ditch_entity_replacement\fP (self)"
.br
.ti -1c
.RI "\fBtest_byte_order_mark_removed\fP (self)"
.br
.ti -1c
.RI "\fBtest_known_definite_versus_user_encodings\fP (self)"
.br
.ti -1c
.RI "\fBtest_deprecated_override_encodings\fP (self)"
.br
.ti -1c
.RI "\fBtest_detwingle\fP (self)"
.br
.ti -1c
.RI "\fBtest_detwingle_ignores_multibyte_characters\fP (self)"
.br
.ti -1c
.RI "\fBtest_find_declared_encoding\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_byte_order_mark_removed ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_deprecated_override_encodings ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_detect_html5_style_meta_tag ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_detwingle ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_detwingle_ignores_multibyte_characters ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_encoding_detector_replaces_junk_in_encoding_name_with_replacement_character ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_find_declared_encoding ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_known_definite_versus_user_encodings ( self)"

.SS "bs4\&.tests\&.test_dammit\&.TestEncodingDetector\&.test_last_ditch_entity_replacement ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
