.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/cmd/build.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/cmd/build.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.cmd\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.cmd\&.build\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBsphinx\&.cmd\&.build\&.handle_exception\fP (\fBSphinx\fP|None app, Any args, BaseException exception, TextIO stderr=sys\&.stderr)"
.br
.ti -1c
.RI "int \fBsphinx\&.cmd\&.build\&.jobs_argument\fP (str value)"
.br
.ti -1c
.RI "argparse\&.ArgumentParser \fBsphinx\&.cmd\&.build\&.get_parser\fP ()"
.br
.ti -1c
.RI "int \fBsphinx\&.cmd\&.build\&.make_main\fP (Sequence[str] argv)"
.br
.ti -1c
.RI "argparse\&.Namespace \fBsphinx\&.cmd\&.build\&._parse_arguments\fP (argparse\&.ArgumentParser parser, Sequence[str] argv)"
.br
.ti -1c
.RI "str|None \fBsphinx\&.cmd\&.build\&._parse_confdir\fP (bool noconfig, str confdir, str sourcedir)"
.br
.ti -1c
.RI "\fB_StrPath\fP \fBsphinx\&.cmd\&.build\&._parse_doctreedir\fP (str doctreedir, str outputdir)"
.br
.ti -1c
.RI "None \fBsphinx\&.cmd\&.build\&._validate_filenames\fP (argparse\&.ArgumentParser parser, bool force_all, list[str] filenames)"
.br
.ti -1c
.RI "None \fBsphinx\&.cmd\&.build\&._validate_colour_support\fP (str colour)"
.br
.ti -1c
.RI "tuple[TextIO|None, TextIO|None, TextIO, TextIO|None] \fBsphinx\&.cmd\&.build\&._parse_logging\fP (argparse\&.ArgumentParser parser, bool quiet, bool really_quiet, str|None warnfile)"
.br
.ti -1c
.RI "dict[str, Any] \fBsphinx\&.cmd\&.build\&._parse_confoverrides\fP (argparse\&.ArgumentParser parser, list[str] define, list[str] htmldefine, bool nitpicky)"
.br
.ti -1c
.RI "int \fBsphinx\&.cmd\&.build\&.build_main\fP (Sequence[str] argv)"
.br
.ti -1c
.RI "int \fBsphinx\&.cmd\&.build\&._bug_report_info\fP ()"
.br
.ti -1c
.RI "int \fBsphinx\&.cmd\&.build\&.main\fP (Sequence[str] argv=())"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
