.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/messages/catalog.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/messages/catalog.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbabel\&.messages\&.catalog\&.Message\fP"
.br
.ti -1c
.RI "class \fBbabel\&.messages\&.catalog\&.TranslationError\fP"
.br
.ti -1c
.RI "class \fBbabel\&.messages\&.catalog\&.Catalog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbabel\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.messages\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.messages\&.catalog\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbabel\&.messages\&.catalog\&.get_close_matches\fP (word, possibilities, n=3, cutoff=0\&.6)"
.br
.ti -1c
.RI "bool \fBbabel\&.messages\&.catalog\&._has_python_brace_format\fP (str string)"
.br
.ti -1c
.RI "datetime\&.datetime \fBbabel\&.messages\&.catalog\&._parse_datetime_header\fP (str value)"
.br
.ti -1c
.RI "dict[str, str] \fBbabel\&.messages\&.catalog\&.parse_separated_header\fP (str value)"
.br
.ti -1c
.RI "str \fBbabel\&.messages\&.catalog\&._force_text\fP (str|bytes s, str encoding='utf\-8', str errors='strict')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "TypeAlias \fBbabel\&.messages\&.catalog\&._MessageID\fP = str | tuple[str, \&.\&.\&.] | list[str]"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.catalog\&.PYTHON_FORMAT\fP = re\&.compile(, re\&.VERBOSE)"
.br
.ti -1c
.RI "str \fBbabel\&.messages\&.catalog\&.DEFAULT_HEADER\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
