.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/charset_normalizer/cd.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/charset_normalizer/cd.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcharset_normalizer\fP"
.br
.ti -1c
.RI "namespace \fBcharset_normalizer\&.cd\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "list[str] \fBcharset_normalizer\&.cd\&.encoding_unicode_range\fP (str iana_name)"
.br
.ti -1c
.RI "list[str] \fBcharset_normalizer\&.cd\&.unicode_range_languages\fP (str primary_range)"
.br
.ti -1c
.RI "list[str] \fBcharset_normalizer\&.cd\&.encoding_languages\fP (str iana_name)"
.br
.ti -1c
.RI "list[str] \fBcharset_normalizer\&.cd\&.mb_encoding_languages\fP (str iana_name)"
.br
.ti -1c
.RI "tuple[bool, bool] \fBcharset_normalizer\&.cd\&.get_target_features\fP (str language)"
.br
.ti -1c
.RI "list[str] \fBcharset_normalizer\&.cd\&.alphabet_languages\fP (list[str] characters, bool ignore_non_latin=False)"
.br
.ti -1c
.RI "float \fBcharset_normalizer\&.cd\&.characters_popularity_compare\fP (str language, list[str] ordered_characters)"
.br
.ti -1c
.RI "list[str] \fBcharset_normalizer\&.cd\&.alpha_unicode_split\fP (str decoded_sequence)"
.br
.ti -1c
.RI "CoherenceMatches \fBcharset_normalizer\&.cd\&.merge_coherence_ratios\fP (list[CoherenceMatches] results)"
.br
.ti -1c
.RI "CoherenceMatches \fBcharset_normalizer\&.cd\&.filter_alt_coherence_matches\fP (CoherenceMatches results)"
.br
.ti -1c
.RI "CoherenceMatches \fBcharset_normalizer\&.cd\&.coherence_ratio\fP (str decoded_sequence, float threshold=0\&.1, str|None lg_inclusion=None)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
