.TH "/home/umar/Desktop/WorkShop/GLL/centry/centry.h" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/centry/centry.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__ns_info_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__nptr\fP   (void *) 0"
.br
.ti -1c
.RI "#define \fB__ctor\fP   /* Nothing */"
.br
.ti -1c
.RI "#define \fB__noreturn\fP   /* Nothing */"
.br
.ti -1c
.RI "#define \fB__BEGIN_SPAWN_CONTEXT\fP(__sbp_identifier)   if( 0 ==__sbp_identifier ) {"
.br
.ti -1c
.RI "#define \fB__END_SPAWN_CONTEXT\fP   }"
.br
.ti -1c
.RI "#define \fB__OTHERWISE\fP   else"
.br
.ti -1c
.RI "#define \fBUSUALSYS_UNIX_PATH\fP"
.br
.ti -1c
.RI "#define \fB_Nullable\fP"
.br
.ti -1c
.RI "#define \fBDEFAULT_SHELL\fP   '/bin/sh'"
.br
.ti -1c
.RI "#define \fBDOCKER_INSPECT\fP(__cid)     'docker','inspect','\-\-format','{{\&.State\&.Pid}}',__cid,\fB__nptr\fP"
.br
.ti -1c
.RI "#define \fBperr\fP(__fcall)     do { perror(#__fcall); exit(EXIT_FAILURE); }while(0)"
.br
.ti -1c
.RI "#define \fB__inline_char\fP(__charval)   (const char[]){ (__charval) & 0xff}"
.br
.ti -1c
.RI "#define \fBNS_DEFINITIONS\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__ns_info_t\fP \fBns_info_t\fP"
.br
.ti -1c
.RI "typedef pid_t \fBcpid_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBhas_command\fP (const char *__restrict__ __host_command)"
.br
.ti -1c
.RI "\fBcpid_t\fP \fBcontainer_process_id\fP (char *__container_id)"
.br
.ti -1c
.RI "void \fBload_ns_for\fP (\fBcpid_t\fP)"
.br
.ti -1c
.RI "char * \fBcentry_check_running_container_for\fP (const char *__container_engine)"
.br
.ti -1c
.RI "void \fBcentry_curses_select\fP (char(*__buffer_result)[0xff], int size)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fB__ns_info_t\fP \fBnsinfo\fP [6]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __BEGIN_SPAWN_CONTEXT(__sbp_identifier)   if( 0 ==__sbp_identifier ) {"

.SS "#define __ctor   /* Nothing */"

.SS "#define __END_SPAWN_CONTEXT   }"

.SS "#define __inline_char(__charval)   (const char[]){ (__charval) & 0xff}"

.SS "#define __noreturn   /* Nothing */"

.SS "#define __nptr   (void *) 0"

.SS "#define __OTHERWISE   else"

.SS "#define _Nullable"

.SS "#define DEFAULT_SHELL   '/bin/sh'"

.SS "#define DOCKER_INSPECT(__cid)     'docker','inspect','\-\-format','{{\&.State\&.Pid}}',__cid,\fB__nptr\fP"

.SS "#define NS_DEFINITIONS"
\fBValue:\fP.PP
.nf
  {  \\
  {"ipc" , CLONE_NEWIPC} , \\
  {"uts" , CLONE_NEWUTS} , \\
  {"net" , CLONE_NEWNET} , \\
  {"pid" , CLONE_NEWPID} , \\
  {"mnt" , CLONE_NEWNS}  , \\
  {__nptr,~0}\\
}
.fi

.SS "#define perr(__fcall)     do { perror(#__fcall); exit(EXIT_FAILURE); }while(0)"

.SS "#define USUALSYS_UNIX_PATH"
\fBValue:\fP.PP
.nf
  {\\
  "/usr/bin/",                 \\
  "/usr/sbin/",                \\
  "/usr/local/bin/",           \\
  "/sbin/",                    \\
  "/bin/",                     \\
  __nptr                       \\
}
.fi

.SH "Typedef Documentation"
.PP 
.SS "typedef pid_t \fBcpid_t\fP"

.SS "typedef struct \fB__ns_info_t\fP \fBns_info_t\fP"

.SH "Function Documentation"
.PP 
.SS "char * centry_check_running_container_for (const char * __container_engine)"
shorten outbuffer i just need the container id and images name TODO : put this in speciale function
.SS "void centry_curses_select (char(*) __buffer_result[0xff], int size)"
Initialising polling on keyboard 
.br
.PP
Term dimension
.PP
Initial setup
.PP
start listening in keyboard
.PP
Big apologies to azerty users TODO :Implement navigation keys for AZERTY users or
.PP
TODO : Make more clear
.SS "\fBcpid_t\fP container_process_id (char * __container_id)"

.SS "int has_command (const char *__restrict__ __host_command)"

.SS "void load_ns_for (\fBcpid_t\fP container_process_id)"

.SH "Variable Documentation"
.PP 
.SS "struct \fB__ns_info_t\fP nsinfo[6]\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
