.TH "cgi.FieldStorage" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cgi.FieldStorage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBfp\fP=None, \fBheaders\fP=None, \fBouterboundary\fP=b'', environ=os\&.environ, \fBkeep_blank_values\fP=0, \fBstrict_parsing\fP=0, \fBlimit\fP=None, \fBencoding\fP='utf\-8', \fBerrors\fP='replace', \fBmax_num_fields\fP=None, \fBseparator\fP='&')"
.br
.ti -1c
.RI "\fB__del__\fP (self)"
.br
.ti -1c
.RI "\fB__enter__\fP (self)"
.br
.ti -1c
.RI "\fB__exit__\fP (self, *args)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__iter__\fP (self)"
.br
.ti -1c
.RI "\fB__getattr__\fP (self, \fBname\fP)"
.br
.ti -1c
.RI "\fB__getitem__\fP (self, key)"
.br
.ti -1c
.RI "\fBgetvalue\fP (self, key, default=None)"
.br
.ti -1c
.RI "\fBgetfirst\fP (self, key, default=None)"
.br
.ti -1c
.RI "\fBgetlist\fP (self, key)"
.br
.ti -1c
.RI "\fBkeys\fP (self)"
.br
.ti -1c
.RI "\fB__contains__\fP (self, key)"
.br
.ti -1c
.RI "\fB__len__\fP (self)"
.br
.ti -1c
.RI "\fB__bool__\fP (self)"
.br
.ti -1c
.RI "\fBread_urlencoded\fP (self)"
.br
.ti -1c
.RI "\fBread_multi\fP (self, environ, \fBkeep_blank_values\fP, \fBstrict_parsing\fP)"
.br
.ti -1c
.RI "\fBread_single\fP (self)"
.br
.ti -1c
.RI "\fBread_binary\fP (self)"
.br
.ti -1c
.RI "\fBread_lines\fP (self)"
.br
.ti -1c
.RI "\fBread_lines_to_eof\fP (self)"
.br
.ti -1c
.RI "\fBread_lines_to_outerboundary\fP (self)"
.br
.ti -1c
.RI "\fBskip_lines\fP (self)"
.br
.ti -1c
.RI "\fBmake_file\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBkeep_blank_values\fP"
.br
.ti -1c
.RI "\fBstrict_parsing\fP"
.br
.ti -1c
.RI "\fBmax_num_fields\fP"
.br
.ti -1c
.RI "\fBseparator\fP"
.br
.ti -1c
.RI "\fBqs_on_post\fP"
.br
.ti -1c
.RI "\fBheaders\fP"
.br
.ti -1c
.RI "\fBfp\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBerrors\fP"
.br
.ti -1c
.RI "\fBouterboundary\fP"
.br
.ti -1c
.RI "\fBbytes_read\fP"
.br
.ti -1c
.RI "\fBlimit\fP"
.br
.ti -1c
.RI "\fBdisposition\fP"
.br
.ti -1c
.RI "\fBdisposition_options\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBtype_options\fP"
.br
.ti -1c
.RI "\fBinnerboundary\fP"
.br
.ti -1c
.RI "\fBlength\fP"
.br
.ti -1c
.RI "\fBlist\fP"
.br
.ti -1c
.RI "\fBdone\fP"
.br
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBfile\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBFieldStorageClass\fP = None"
.br
.ti -1c
.RI "int \fBbufsize\fP = 8*1024"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_binary_file\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Store a sequence of fields, reading multipart/form-data\&.

This class provides naming, typing, files stored on disk, and
more\&.  At the top level, it is accessible like a dictionary, whose
keys are the field names\&.  (Note: None can occur as a field name\&.)
The items are either a Python list (if there's multiple values) or
another FieldStorage or MiniFieldStorage object\&.  If it's a single
object, it has the following attributes:

name: the field name, if specified; otherwise None

filename: the filename, if specified; otherwise None; this is the
    client side filename, *not* the file name on which it is
    stored (that's a temporary file you don't deal with)

value: the value as a *string*; for file uploads, this
    transparently reads the file every time you request the value
    and returns *bytes*

file: the file(-like) object from which you can read the data *as
    bytes* ; None if the data is stored a simple string

type: the content-type, or None if not specified

type_options: dictionary of options specified on the content-type
    line

disposition: content-disposition, or None if not specified

disposition_options: dictionary of corresponding options

headers: a dictionary(-like) object (sometimes email\&.message\&.Message or a
    subclass thereof) containing *all* headers

The class is subclassable, mostly for the purpose of overriding
the make_file() method, which is called internally to come up with
a file open for reading and writing\&.  This makes it possible to
override the default choice of storing all files in a temporary
directory and unlinking them as soon as they have been opened\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cgi\&.FieldStorage\&.__init__ ( self,  fp = \fCNone\fP,  headers = \fCNone\fP,  outerboundary = \fCb''\fP,  environ = \fCos\&.environ\fP,  keep_blank_values = \fC0\fP,  strict_parsing = \fC0\fP,  limit = \fCNone\fP,  encoding = \fC'utf\-8'\fP,  errors = \fC'replace'\fP,  max_num_fields = \fCNone\fP,  separator = \fC'&'\fP)"

.PP
.nf
Constructor\&.  Read multipart/* until last part\&.

Arguments, all optional:

fp              : file pointer; default: sys\&.stdin\&.buffer
    (not used when the request method is GET)
    Can be :
    1\&. a TextIOWrapper object
    2\&. an object whose read() and readline() methods return bytes

headers         : header dictionary-like object; default:
    taken from environ as per CGI spec

outerboundary   : terminating multipart boundary
    (for internal use only)

environ         : environment dictionary; default: os\&.environ

keep_blank_values: flag indicating whether blank values in
    percent-encoded forms should be treated as blank strings\&.
    A true value indicates that blanks should be retained as
    blank strings\&.  The default false value indicates that
    blank values are to be ignored and treated as if they were
    not included\&.

strict_parsing: flag indicating what to do with parsing errors\&.
    If false (the default), errors are silently ignored\&.
    If true, errors raise a ValueError exception\&.

limit : used internally to read parts of multipart/form-data forms,
    to exit from the reading loop when reached\&. It is the difference
    between the form content-length and the number of bytes already
    read

encoding, errors : the encoding and error handler used to decode the
    binary stream to strings\&. Must be the same as the charset defined
    for the page sending the form (content-type : meta http-equiv or
    header)

max_num_fields: int\&. If set, then __init__ throws a ValueError
    if there are more than n fields read by parse_qsl()\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.__del__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "cgi\&.FieldStorage\&.__bool__ ( self)"

.SS "cgi\&.FieldStorage\&.__contains__ ( self,  key)"

.PP
.nf
Dictionary style __contains__ method\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.__enter__ ( self)"

.SS "cgi\&.FieldStorage\&.__exit__ ( self, * args)"

.SS "cgi\&.FieldStorage\&.__getattr__ ( self,  name)"

.SS "cgi\&.FieldStorage\&.__getitem__ ( self,  key)"

.PP
.nf
Dictionary style indexing\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.__iter__ ( self)"

.SS "cgi\&.FieldStorage\&.__len__ ( self)"

.PP
.nf
Dictionary style len(x) support\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.__repr__ ( self)"

.PP
.nf
Return a printable representation\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.getfirst ( self,  key,  default = \fCNone\fP)"

.PP
.nf
 Return the first value received\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.getlist ( self,  key)"

.PP
.nf
 Return list of received values\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.getvalue ( self,  key,  default = \fCNone\fP)"

.PP
.nf
Dictionary style get() method, including 'value' lookup\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.keys ( self)"

.PP
.nf
Dictionary style keys() method\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.make_file ( self)"

.PP
.nf
Overridable: return a readable & writable file\&.

The file will be used as follows:
- data is written to it
- seek(0)
- data is read from it

The file is opened in binary mode for files, in text mode
for other fields

This version opens a temporary file for reading and writing,
and immediately deletes (unlinks) it\&.  The trick (on Unix!) is
that the file can still be used, but it can't be opened by
another process, and it will automatically be deleted when it
is closed or when the current process terminates\&.

If you want a more permanent file, you derive a class which
overrides this method\&.  If you want a visible temporary file
that is nevertheless automatically deleted when the script
terminates, try defining a __del__ method in a derived class
which unlinks the temporary files you have created\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.read_binary ( self)"

.PP
.nf
Internal: read binary data\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.read_lines ( self)"

.PP
.nf
Internal: read lines until EOF or outerboundary\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.read_lines_to_eof ( self)"

.PP
.nf
Internal: read lines until EOF\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.read_lines_to_outerboundary ( self)"

.PP
.nf
Internal: read lines until outerboundary\&.
Data is read as bytes: boundaries and line ends must be converted
to bytes for comparisons\&.

.fi
.PP
 
.SS "cgi\&.FieldStorage\&.read_multi ( self,  environ,  keep_blank_values,  strict_parsing)"

.PP
.nf
Internal: read a part that is itself multipart\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.read_single ( self)"

.PP
.nf
Internal: read an atomic part\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.read_urlencoded ( self)"

.PP
.nf
Internal: read data in query string format\&.
.fi
.PP
 
.SS "cgi\&.FieldStorage\&.skip_lines ( self)"

.PP
.nf
Internal: skip lines until outer boundary if defined\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "cgi\&.FieldStorage\&._binary_file\fC [protected]\fP"

.SS "int cgi\&.FieldStorage\&.bufsize = 8*1024\fC [static]\fP"

.SS "cgi\&.FieldStorage\&.bytes_read"

.SS "cgi\&.FieldStorage\&.disposition"

.SS "cgi\&.FieldStorage\&.disposition_options"

.SS "cgi\&.FieldStorage\&.done"

.SS "cgi\&.FieldStorage\&.encoding"

.SS "cgi\&.FieldStorage\&.errors"

.SS "cgi\&.FieldStorage\&.FieldStorageClass = None\fC [static]\fP"

.SS "cgi\&.FieldStorage\&.file"

.SS "cgi\&.FieldStorage\&.filename"

.SS "cgi\&.FieldStorage\&.fp"

.SS "cgi\&.FieldStorage\&.headers"

.SS "cgi\&.FieldStorage\&.innerboundary"

.SS "cgi\&.FieldStorage\&.keep_blank_values"

.SS "cgi\&.FieldStorage\&.length"

.SS "cgi\&.FieldStorage\&.limit"

.SS "cgi\&.FieldStorage\&.list"

.SS "cgi\&.FieldStorage\&.max_num_fields"

.SS "cgi\&.FieldStorage\&.name"

.SS "cgi\&.FieldStorage\&.outerboundary"

.SS "cgi\&.FieldStorage\&.qs_on_post"

.SS "cgi\&.FieldStorage\&.separator"

.SS "cgi\&.FieldStorage\&.strict_parsing"

.SS "cgi\&.FieldStorage\&.type"

.SS "cgi\&.FieldStorage\&.type_options"

.SS "cgi\&.FieldStorage\&.value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
