.TH "cgitb.Hook" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cgitb.Hook
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBdisplay\fP=1, \fBlogdir\fP=None, \fBcontext\fP=5, \fBfile\fP=None, \fBformat\fP='html')"
.br
.ti -1c
.RI "\fB__call__\fP (self, etype, evalue, etb)"
.br
.ti -1c
.RI "\fBhandle\fP (self, info=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdisplay\fP"
.br
.ti -1c
.RI "\fBlogdir\fP"
.br
.ti -1c
.RI "\fBcontext\fP"
.br
.ti -1c
.RI "\fBfile\fP"
.br
.ti -1c
.RI "\fBformat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A hook to replace sys\&.excepthook that shows tracebacks in HTML\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cgitb\&.Hook\&.__init__ ( self,  display = \fC1\fP,  logdir = \fCNone\fP,  context = \fC5\fP,  file = \fCNone\fP,  format = \fC'html'\fP)"

.SH "Member Function Documentation"
.PP 
.SS "cgitb\&.Hook\&.__call__ ( self,  etype,  evalue,  etb)"

.SS "cgitb\&.Hook\&.handle ( self,  info = \fCNone\fP)"

.SH "Member Data Documentation"
.PP 
.SS "cgitb\&.Hook\&.context"

.SS "cgitb\&.Hook\&.display"

.SS "cgitb\&.Hook\&.file"

.SS "cgitb\&.Hook\&.format"

.SS "cgitb\&.Hook\&.logdir"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
