.TH "charset_normalizer.constant" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
charset_normalizer.constant
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBENCODING_MARKS\fP"
.br
.ti -1c
.RI "int \fBTOO_SMALL_SEQUENCE\fP = 32"
.br
.ti -1c
.RI "int \fBTOO_BIG_SEQUENCE\fP = int(10e6)"
.br
.ti -1c
.RI "int \fBUTF8_MAXIMAL_ALLOCATION\fP = 1_112_064"
.br
.ti -1c
.RI "dict \fBUNICODE_RANGES_COMBINED\fP"
.br
.ti -1c
.RI "list \fBUNICODE_SECONDARY_RANGE_KEYWORD\fP"
.br
.ti -1c
.RI "\fBRE_POSSIBLE_ENCODING_INDICATION\fP"
.br
.ti -1c
.RI "list \fBIANA_NO_ALIASES\fP"
.br
.ti -1c
.RI "list \fBIANA_SUPPORTED\fP"
.br
.ti -1c
.RI "int \fBIANA_SUPPORTED_COUNT\fP = len(\fBIANA_SUPPORTED\fP)"
.br
.ti -1c
.RI "dict \fBIANA_SUPPORTED_SIMILAR\fP"
.br
.ti -1c
.RI "dict \fBCHARDET_CORRESPONDENCE\fP"
.br
.ti -1c
.RI "dict \fBCOMMON_SAFE_ASCII_CHARACTERS\fP"
.br
.ti -1c
.RI "str \fBCOMMON_CHINESE_CHARACTERS\fP = '的一是在不了有和人这中大为上个国我以要他时来用们生到作地于出就分对成会可主发年动同工也能下过子说产种面而方后多定行学法所民得经十三之进着等部度家电力里如水化高自二理起小物现实加量都两体制机当使点从业本去把性好应开它合还因由其些然前外天政四日那社义事平形相全表间样与关各重新线内数正心反你明看原又么利比或但质气第向道命此变条只没结解问意建月公无系军很情者最立代想已通并提直题党程展五果料象员革位入常文总次品式活设及管特件长求老头基资边流路级少图山统接知较将组见计别她手角期根论运农指几九区强放决西被干做必战先回则任取据处队南给色光门即保治北造百规热领七海口东导器压志世金增争济阶油思术极交受联什认六共权收证改清己美再采转更单风切打白教速花带安场身车例真务具万每目至达走积示议声报斗完类八离华名确才科张信马节话米整空元况今集温传土许步群广石记需段研界拉林律叫且究观越织装影算低持音众书布复容儿须际商非验连断深难近矿千周委素技备半办青省列习响约支般史感劳便团往酸历市克何除消构府太准精值号率族维划选标写存候毛亲快效斯院查江型眼王按格养易置派层片始却专状育厂京识适属圆包火住调满县局照参红细引听该铁价严龙飞'"
.br
.ti -1c
.RI "str \fBCOMMON_JAPANESE_CHARACTERS\fP = '日一国年大十二本中長出三時行見月分後前生五間上東四今金九入学高円子外八六下来気小七山話女北午百書先名川千水半男西電校語土木聞食車何南万毎白天母火右読友左休父雨'"
.br
.ti -1c
.RI "str \fBCOMMON_KOREAN_CHARACTERS\fP = '一二三四五六七八九十百千萬上下左右中人女子大小山川日月火水木金土父母天地國名年時文校學生'"
.br
.ti -1c
.RI "\fBCOMMON_CJK_CHARACTERS\fP"
.br
.ti -1c
.RI "dict \fBKO_NAMES\fP = {'johab', 'cp949', 'euc_kr'}"
.br
.ti -1c
.RI "dict \fBZH_NAMES\fP = {'big5', 'cp950', 'big5hkscs', 'hz'}"
.br
.ti -1c
.RI "int \fBTRACE\fP = 5"
.br
.ti -1c
.RI "dict \fBFREQUENCIES\fP"
.br
.ti -1c
.RI "int \fBLANGUAGE_SUPPORTED_COUNT\fP = len(\fBFREQUENCIES\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "dict charset_normalizer\&.constant\&.CHARDET_CORRESPONDENCE"

.SS "str charset_normalizer\&.constant\&.COMMON_CHINESE_CHARACTERS = '的一是在不了有和人这中大为上个国我以要他时来用们生到作地于出就分对成会可主发年动同工也能下过子说产种面而方后多定行学法所民得经十三之进着等部度家电力里如水化高自二理起小物现实加量都两体制机当使点从业本去把性好应开它合还因由其些然前外天政四日那社义事平形相全表间样与关各重新线内数正心反你明看原又么利比或但质气第向道命此变条只没结解问意建月公无系军很情者最立代想已通并提直题党程展五果料象员革位入常文总次品式活设及管特件长求老头基资边流路级少图山统接知较将组见计别她手角期根论运农指几九区强放决西被干做必战先回则任取据处队南给色光门即保治北造百规热领七海口东导器压志世金增争济阶油思术极交受联什认六共权收证改清己美再采转更单风切打白教速花带安场身车例真务具万每目至达走积示议声报斗完类八离华名确才科张信马节话米整空元况今集温传土许步群广石记需段研界拉林律叫且究观越织装影算低持音众书布复容儿须际商非验连断深难近矿千周委素技备半办青省列习响约支般史感劳便团往酸历市克何除消构府太准精值号率族维划选标写存候毛亲快效斯院查江型眼王按格养易置派层片始却专状育厂京识适属圆包火住调满县局照参红细引听该铁价严龙飞'"

.SS "charset_normalizer\&.constant\&.COMMON_CJK_CHARACTERS"
\fBInitial value:\fP.PP
.nf
1 =  set(
2     ""\&.join(
3         [
4             COMMON_CHINESE_CHARACTERS,
5             COMMON_JAPANESE_CHARACTERS,
6             COMMON_KOREAN_CHARACTERS,
7         ]
8     )
9 )
.fi

.SS "str charset_normalizer\&.constant\&.COMMON_JAPANESE_CHARACTERS = '日一国年大十二本中長出三時行見月分後前生五間上東四今金九入学高円子外八六下来気小七山話女北午百書先名川千水半男西電校語土木聞食車何南万毎白天母火右読友左休父雨'"

.SS "str charset_normalizer\&.constant\&.COMMON_KOREAN_CHARACTERS = '一二三四五六七八九十百千萬上下左右中人女子大小山川日月火水木金土父母天地國名年時文校學生'"

.SS "dict charset_normalizer\&.constant\&.COMMON_SAFE_ASCII_CHARACTERS"
\fBInitial value:\fP.PP
.nf
1 =  {
2     "<",
3     ">",
4     "=",
5     ":",
6     "/",
7     "&",
8     ";",
9     "{",
10     "}",
11     "[",
12     "]",
13     ",",
14     "|",
15     '"',
16     "\-",
17     "(",
18     ")",
19 }
.fi

.SS "dict charset_normalizer\&.constant\&.ENCODING_MARKS"
\fBInitial value:\fP.PP
.nf
1 =  {
2     "utf_8": BOM_UTF8,
3     "utf_7": [
4         b"\\x2b\\x2f\\x76\\x38",
5         b"\\x2b\\x2f\\x76\\x39",
6         b"\\x2b\\x2f\\x76\\x2b",
7         b"\\x2b\\x2f\\x76\\x2f",
8         b"\\x2b\\x2f\\x76\\x38\\x2d",
9     ],
10     "gb18030": b"\\x84\\x31\\x95\\x33",
11     "utf_32": [BOM_UTF32_BE, BOM_UTF32_LE],
12     "utf_16": [BOM_UTF16_BE, BOM_UTF16_LE],
13 }
.fi

.SS "dict charset_normalizer\&.constant\&.FREQUENCIES"

.SS "list charset_normalizer\&.constant\&.IANA_NO_ALIASES"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "cp720",
3     "cp737",
4     "cp856",
5     "cp874",
6     "cp875",
7     "cp1006",
8     "koi8_r",
9     "koi8_t",
10     "koi8_u",
11 ]
.fi

.SS "list charset_normalizer\&.constant\&.IANA_SUPPORTED"
\fBInitial value:\fP.PP
.nf
1 =  sorted(
2     filter(
3         lambda x: x\&.endswith("_codec") is False
4         and x not in {"rot_13", "tactis", "mbcs"},
5         list(set(aliases\&.values())) + IANA_NO_ALIASES,
6     )
7 )
.fi

.SS "int charset_normalizer\&.constant\&.IANA_SUPPORTED_COUNT = len(\fBIANA_SUPPORTED\fP)"

.SS "dict charset_normalizer\&.constant\&.IANA_SUPPORTED_SIMILAR"

.SS "dict charset_normalizer\&.constant\&.KO_NAMES = {'johab', 'cp949', 'euc_kr'}"

.SS "int charset_normalizer\&.constant\&.LANGUAGE_SUPPORTED_COUNT = len(\fBFREQUENCIES\fP)"

.SS "charset_normalizer\&.constant\&.RE_POSSIBLE_ENCODING_INDICATION"
\fBInitial value:\fP.PP
.nf
1 =  re_compile(
2     r"(?:(?:encoding)|(?:charset)|(?:coding))(?:[\\:= ]{1,10})(?:[\\"\\']?)([a\-zA\-Z0\-9\\\-_]+)(?:[\\"\\']?)",
3     IGNORECASE,
4 )
.fi

.SS "int charset_normalizer\&.constant\&.TOO_BIG_SEQUENCE = int(10e6)"

.SS "int charset_normalizer\&.constant\&.TOO_SMALL_SEQUENCE = 32"

.SS "int charset_normalizer\&.constant\&.TRACE = 5"

.SS "dict charset_normalizer\&.constant\&.UNICODE_RANGES_COMBINED"

.SS "list charset_normalizer\&.constant\&.UNICODE_SECONDARY_RANGE_KEYWORD"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "Supplement",
3     "Extended",
4     "Extensions",
5     "Modifier",
6     "Marks",
7     "Punctuation",
8     "Symbols",
9     "Forms",
10     "Operators",
11     "Miscellaneous",
12     "Drawing",
13     "Block",
14     "Shapes",
15     "Supplemental",
16     "Tags",
17 ]
.fi

.SS "int charset_normalizer\&.constant\&.UTF8_MAXIMAL_ALLOCATION = 1_112_064"

.SS "dict charset_normalizer\&.constant\&.ZH_NAMES = {'big5', 'cp950', 'big5hkscs', 'hz'}"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
