.TH "charset_normalizer.models" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
charset_normalizer.models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCharsetMatch\fP"
.br
.ti -1c
.RI "class \fBCharsetMatches\fP"
.br
.ti -1c
.RI "class \fBCliDetectionResult\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCoherenceMatch\fP = Tuple[str, float]"
.br
.ti -1c
.RI "\fBCoherenceMatches\fP = List[\fBCoherenceMatch\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "charset_normalizer\&.models\&.CoherenceMatch = Tuple[str, float]"

.SS "charset_normalizer\&.models\&.CoherenceMatches = List[\fBCoherenceMatch\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
