.TH "charset_normalizer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
charset_normalizer
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__main__\fP"
.br
.ti -1c
.RI "namespace \fBapi\fP"
.br
.ti -1c
.RI "namespace \fBcd\fP"
.br
.ti -1c
.RI "namespace \fBcli\fP"
.br
.ti -1c
.RI "namespace \fBconstant\fP"
.br
.ti -1c
.RI "namespace \fBlegacy\fP"
.br
.ti -1c
.RI "namespace \fBmd\fP"
.br
.ti -1c
.RI "namespace \fBmodels\fP"
.br
.ti -1c
.RI "namespace \fButils\fP"
.br
.ti -1c
.RI "namespace \fBversion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Charset-Normalizer
~~~~~~~~~~~~~~
The Real First Universal Charset Detector\&.
A library that helps you read text from an unknown charset encoding\&.
Motivated by chardet, This package is trying to resolve the issue by taking a new approach\&.
All IANA character set names for which the Python core library provides codecs are supported\&.

Basic usage:
   >>> from charset_normalizer import from_bytes
   >>> results = from_bytes('Bсеки човек има право на образование\&. Oбразованието!'\&.encode('utf_8'))
   >>> best_guess = results\&.best()
   >>> str(best_guess)
   'Bсеки човек има право на образование\&. Oбразованието!'

Others methods and usages are available - see the full documentation
at <https://github\&.com/Ousret/charset_normalizer>\&.
:copyright: (c) 2021 by Ahmed TAHRI
:license: MIT, see LICENSE for more details\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
