.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/jinja2/compiler.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/jinja2/compiler.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjinja2\&.compiler\&.MacroRef\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.compiler\&.Frame\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.compiler\&.VisitorExit\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.compiler\&.DependencyFinderVisitor\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.compiler\&.UndeclaredNameVisitor\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.compiler\&.CompilerExit\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.compiler\&.CodeGenerator\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.compiler\&.CodeGenerator\&._FinalizeInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBjinja2\fP"
.br
.ti -1c
.RI "namespace \fBjinja2\&.compiler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBF\fP \fBjinja2\&.compiler\&.optimizeconst\fP (\fBF\fP f)"
.br
.ti -1c
.RI "t\&.Callable[['CodeGenerator', \fBnodes\&.BinExpr\fP, 'Frame'], None] \fBjinja2\&.compiler\&._make_binop\fP (str op)"
.br
.ti -1c
.RI "t\&.Callable[['CodeGenerator', \fBnodes\&.UnaryExpr\fP, 'Frame'], None] \fBjinja2\&.compiler\&._make_unop\fP (str op)"
.br
.ti -1c
.RI "t\&.Optional[str] \fBjinja2\&.compiler\&.generate\fP (\fBnodes\&.Template\fP node, 'Environment' environment, t\&.Optional[str] name, t\&.Optional[str] filename, t\&.Optional[t\&.TextIO] stream=None, bool defer_init=False, bool optimized=True)"
.br
.ti -1c
.RI "bool \fBjinja2\&.compiler\&.has_safe_repr\fP (t\&.Any value)"
.br
.ti -1c
.RI "t\&.Set[str] \fBjinja2\&.compiler\&.find_undeclared\fP (t\&.Iterable[\fBnodes\&.Node\fP] nodes, t\&.Iterable[str] names)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBjinja2\&.compiler\&.F\fP = t\&.TypeVar('F', bound=t\&.Callable[\&.\&.\&., t\&.Any])"
.br
.ti -1c
.RI "dict \fBjinja2\&.compiler\&.operators\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
