.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/config.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/config.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.config\&.ConfigValue\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.config\&.ENUM\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.config\&._Opt\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.config\&.Config\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.config\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsphinx\&.config\&.is_serializable\fP (object obj, *frozenset[int] _seen=frozenset())"
.br
.ti -1c
.RI "dict[str, Any] \fBsphinx\&.config\&.eval_config_file\fP (str|os\&.PathLike[str] filename, \fBTags\fP|None tags)"
.br
.ti -1c
.RI "frozenset[type]|\fBENUM\fP \fBsphinx\&.config\&._validate_valid_types\fP (type|Collection[type]|\fBENUM\fP valid_types)"
.br
.ti -1c
.RI "None \fBsphinx\&.config\&.convert_source_suffix\fP (\fBSphinx\fP app, \fBConfig\fP config)"
.br
.ti -1c
.RI "None \fBsphinx\&.config\&.convert_highlight_options\fP (\fBSphinx\fP app, \fBConfig\fP config)"
.br
.ti -1c
.RI "None \fBsphinx\&.config\&.init_numfig_format\fP (\fBSphinx\fP app, \fBConfig\fP config)"
.br
.ti -1c
.RI "None \fBsphinx\&.config\&.evaluate_copyright_placeholders\fP (\fBSphinx\fP _app, \fBConfig\fP config)"
.br
.ti -1c
.RI "None \fBsphinx\&.config\&.correct_copyright_year\fP (\fBSphinx\fP _app, \fBConfig\fP config)"
.br
.ti -1c
.RI "str \fBsphinx\&.config\&._substitute_copyright_year\fP (str copyright_line, str current_year, str replace_year)"
.br
.ti -1c
.RI "None \fBsphinx\&.config\&.check_confval_types\fP (\fBSphinx\fP|None app, \fBConfig\fP config)"
.br
.ti -1c
.RI "None \fBsphinx\&.config\&.check_primary_domain\fP (\fBSphinx\fP app, \fBConfig\fP config)"
.br
.ti -1c
.RI "Iterable[str] \fBsphinx\&.config\&.check_master_doc\fP (\fBSphinx\fP app, \fBBuildEnvironment\fP env, Set[str] added, Set[str] changed, Set[str] removed)"
.br
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsphinx\&.config\&.setup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsphinx\&.config\&.logger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "TypeAlias \fBsphinx\&.config\&._ConfigRebuild\fP"
.br
.ti -1c
.RI "str \fBsphinx\&.config\&.CONFIG_FILENAME\fP = 'conf\&.py'"
.br
.ti -1c
.RI "tuple \fBsphinx\&.config\&.UNSERIALIZABLE_TYPES\fP = (type, types\&.ModuleType, types\&.FunctionType)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
