.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/configuration.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/configuration.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._internal\&.configuration\&.Configuration\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.configuration\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBpip\&._internal\&.configuration\&._normalize_name\fP (str name)"
.br
.ti -1c
.RI "List[str] \fBpip\&._internal\&.configuration\&._disassemble_key\fP (str name)"
.br
.ti -1c
.RI "Dict[\fBKind\fP, List[str]] \fBpip\&._internal\&.configuration\&.get_configuration_files\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._internal\&.configuration\&.RawConfigParser\fP = configparser\&.RawConfigParser"
.br
.ti -1c
.RI "\fBpip\&._internal\&.configuration\&.Kind\fP = NewType('Kind', str)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.configuration\&.CONFIG_BASENAME\fP = 'pip\&.ini' if WINDOWS else 'pip\&.conf'"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.configuration\&.ENV_NAMES_IGNORED\fP = 'version', 'help'"
.br
.ti -1c
.RI "\fBpip\&._internal\&.configuration\&.kinds\fP"
.br
.ti -1c
.RI "\fBpip\&._internal\&.configuration\&.OVERRIDE_ORDER\fP = kinds\&.GLOBAL, kinds\&.USER, kinds\&.SITE, kinds\&.ENV, kinds\&.ENV_VAR"
.br
.ti -1c
.RI "\fBpip\&._internal\&.configuration\&.VALID_LOAD_ONLY\fP = kinds\&.USER, kinds\&.GLOBAL, kinds\&.SITE"
.br
.ti -1c
.RI "\fBpip\&._internal\&.configuration\&.logger\fP = getLogger(__name__)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
