.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/lexers/configs.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/lexers/configs.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.IniLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.DesktopLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.SystemdLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.RegeditLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.PropertiesLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.KconfigLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.Cfengine3Lexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.ApacheConfLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.SquidConfLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.NginxConfLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.LighttpdConfLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.DockerLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.TerraformLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.TermcapLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.TerminfoLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.PkgConfigLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.PacmanConfLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.AugeasLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.TOMLLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.NestedTextLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.SingularityLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.configs\&.UnixConfigLexer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpygments\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.lexers\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.lexers\&.configs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpygments\&.lexers\&.configs\&._rx_indent\fP (level)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
