.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/dates.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/dates.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbabel\&.dates\&.ParseError\fP"
.br
.ti -1c
.RI "class \fBbabel\&.dates\&.DateTimePattern\fP"
.br
.ti -1c
.RI "class \fBbabel\&.dates\&.DateTimeFormat\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbabel\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.dates\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "datetime\&.datetime \fBbabel\&.dates\&._localize\fP (datetime\&.tzinfo tz, datetime\&.datetime dt)"
.br
.ti -1c
.RI "tuple[datetime\&.datetime|None, datetime\&.tzinfo] \fBbabel\&.dates\&._get_dt_and_tzinfo\fP (\fB_DtOrTzinfo\fP dt_or_tzinfo)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&._get_tz_name\fP (\fB_DtOrTzinfo\fP dt_or_tzinfo)"
.br
.ti -1c
.RI "datetime\&.datetime \fBbabel\&.dates\&._get_datetime\fP (\fB_Instant\fP instant)"
.br
.ti -1c
.RI "datetime\&.datetime \fBbabel\&.dates\&._ensure_datetime_tzinfo\fP (datetime\&.datetime dt, datetime\&.tzinfo|None tzinfo=None)"
.br
.ti -1c
.RI "datetime\&.time \fBbabel\&.dates\&._get_time\fP (datetime\&.time|datetime\&.datetime|None time, datetime\&.tzinfo|None tzinfo=None)"
.br
.ti -1c
.RI "datetime\&.tzinfo \fBbabel\&.dates\&.get_timezone\fP (str|datetime\&.tzinfo|None zone=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBbabel\&.dates\&.get_period_names\fP (Literal['abbreviated', 'narrow', 'wide'] width='wide', \fB_Context\fP context='stand\-alone', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBbabel\&.dates\&.get_day_names\fP (Literal['abbreviated', 'narrow', 'short', 'wide'] width='wide', \fB_Context\fP context='format', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBbabel\&.dates\&.get_month_names\fP (Literal['abbreviated', 'narrow', 'wide'] width='wide', \fB_Context\fP context='format', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBbabel\&.dates\&.get_quarter_names\fP (Literal['abbreviated', 'narrow', 'wide'] width='wide', \fB_Context\fP context='format', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBLocaleDataDict\fP \fBbabel\&.dates\&.get_era_names\fP (Literal['abbreviated', 'narrow', 'wide'] width='wide', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBbabel\&.dates\&.get_date_format\fP (\fB_PredefinedTimeFormat\fP format='medium', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBbabel\&.dates\&.get_datetime_format\fP (\fB_PredefinedTimeFormat\fP format='medium', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBbabel\&.dates\&.get_time_format\fP (\fB_PredefinedTimeFormat\fP format='medium', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.get_timezone_gmt\fP (\fB_Instant\fP datetime=None, Literal['long', 'short', 'iso8601', 'iso8601_short'] width='long', \fBLocale\fP|str|None locale=None, bool return_z=False)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.get_timezone_location\fP (\fB_DtOrTzinfo\fP dt_or_tzinfo=None, \fBLocale\fP|str|None locale=None, bool return_city=False)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.get_timezone_name\fP (\fB_DtOrTzinfo\fP dt_or_tzinfo=None, Literal['long', 'short'] width='long', bool uncommon=False, \fBLocale\fP|str|None locale=None, Literal['generic', 'daylight', 'standard']|None zone_variant=None, bool return_zone=False)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.format_date\fP (datetime\&.date|None date=None, \fB_PredefinedTimeFormat\fP|str format='medium', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.format_datetime\fP (\fB_Instant\fP datetime=None, \fB_PredefinedTimeFormat\fP|str format='medium', datetime\&.tzinfo|None tzinfo=None, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.format_time\fP (datetime\&.time|datetime\&.datetime|float|None time=None, \fB_PredefinedTimeFormat\fP|str format='medium', datetime\&.tzinfo|None tzinfo=None, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.format_skeleton\fP (str skeleton, \fB_Instant\fP datetime=None, datetime\&.tzinfo|None tzinfo=None, bool fuzzy=True, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.format_timedelta\fP (datetime\&.timedelta|int delta, Literal['year', 'month', 'week', 'day', 'hour', 'minute', 'second'] granularity='second', float threshold=\&.85, bool add_direction=False, Literal['narrow', 'short', 'medium', 'long'] format='long', \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&._format_fallback_interval\fP (\fB_Instant\fP start, \fB_Instant\fP end, str|None skeleton, datetime\&.tzinfo|None tzinfo, \fBLocale\fP locale)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.format_interval\fP (\fB_Instant\fP start, \fB_Instant\fP end, str|None skeleton=None, datetime\&.tzinfo|None tzinfo=None, bool fuzzy=True, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.get_period_id\fP (\fB_Instant\fP time, datetime\&.tzinfo|None tzinfo=None, Literal['selection']|None type=None, \fBLocale\fP|str|None locale=None)"
.br
.ti -1c
.RI "datetime\&.date \fBbabel\&.dates\&.parse_date\fP (str string, \fBLocale\fP|str|None locale=None, \fB_PredefinedTimeFormat\fP|str format='medium')"
.br
.ti -1c
.RI "datetime\&.time \fBbabel\&.dates\&.parse_time\fP (str string, \fBLocale\fP|str|None locale=None, \fB_PredefinedTimeFormat\fP|str format='medium')"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBbabel\&.dates\&.parse_pattern\fP (str|\fBDateTimePattern\fP pattern)"
.br
.ti -1c
.RI "\fBDateTimePattern\fP \fBbabel\&.dates\&._cached_parse_pattern\fP (str pattern)"
.br
.ti -1c
.RI "list[tuple[str, str|tuple[str, int]]] \fBbabel\&.dates\&.tokenize_pattern\fP (str pattern)"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.untokenize_pattern\fP (Iterable[tuple[str, str|tuple[str, int]]] tokens)"
.br
.ti -1c
.RI "list[str] \fBbabel\&.dates\&.split_interval_pattern\fP (str pattern)"
.br
.ti -1c
.RI "str|None \fBbabel\&.dates\&.match_skeleton\fP (str skeleton, Iterable[str] options, bool allow_different_fields=False)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbabel\&.dates\&.pytz\fP = None"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.dates\&._Instant\fP = datetime\&.date | datetime\&.time | float | None"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.dates\&._PredefinedTimeFormat\fP = Literal['full', 'long', 'medium', 'short']"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.dates\&._Context\fP = Literal['format', 'stand\-alone']"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.dates\&._DtOrTzinfo\fP = datetime\&.datetime | datetime\&.tzinfo | str | int | datetime\&.time | None"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.NO_INHERITANCE_MARKER\fP = '\\u2205\\u2205\\u2205'"
.br
.ti -1c
.RI "\fBbabel\&.dates\&.UTC\fP = datetime\&.timezone\&.utc"
.br
.ti -1c
.RI "\fBbabel\&.dates\&.LOCALTZ\fP = localtime\&.LOCALTZ"
.br
.ti -1c
.RI "\fBbabel\&.dates\&.LC_TIME\fP = default_locale('LC_TIME')"
.br
.ti -1c
.RI "tuple \fBbabel\&.dates\&.TIMEDELTA_UNITS\fP"
.br
.ti -1c
.RI "str \fBbabel\&.dates\&.PATTERN_CHAR_ORDER\fP = 'GyYuUQqMLlwWdDFgEecabBChHKkjJmsSAzZOvVXx'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
