.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/webtest/debugapp.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/webtest/debugapp.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwebtest\&.debugapp\&.DebugApp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwebtest\fP"
.br
.ti -1c
.RI "namespace \fBwebtest\&.debugapp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwebtest\&.debugapp\&.make_debug_app\fP (global_conf, **local_conf)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBwebtest\&.debugapp\&.debug_app\fP = \fBDebugApp\fP(form=b)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
