.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/utils/direct_url_helpers.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/utils/direct_url_helpers.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.utils\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.utils\&.direct_url_helpers\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.direct_url_helpers\&.direct_url_as_pep440_direct_reference\fP (\fBDirectUrl\fP direct_url, str name)"
.br
.ti -1c
.RI "\fBDirectUrl\fP \fBpip\&._internal\&.utils\&.direct_url_helpers\&.direct_url_for_editable\fP (str source_dir)"
.br
.ti -1c
.RI "\fBDirectUrl\fP \fBpip\&._internal\&.utils\&.direct_url_helpers\&.direct_url_from_link\fP (\fBLink\fP link, Optional[str] source_dir=None, bool link_is_in_wheel_cache=False)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
