.TH "docutils.nodes.Body" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.nodes.Body
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdocutils\&.nodes\&.Admonition\fP, \fBdocutils\&.nodes\&.General\fP, \fBdocutils\&.nodes\&.Sequential\fP, and \fBdocutils\&.nodes\&.Special\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
