.TH "docutils.transforms.parts" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.transforms.parts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContents\fP"
.br
.ti -1c
.RI "class \fBContentsFilter\fP"
.br
.ti -1c
.RI "class \fBSectNum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Transforms related to document parts\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
