.TH "docutils.writers._html_base.SimpleListChecker" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.writers._html_base.SimpleListChecker
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.nodes\&.GenericNodeVisitor\fP\&.
.PP
Inherited by \fBdocutils\&.writers\&.html4css1\&.SimpleListChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdefault_visit\fP (self, node)"
.br
.ti -1c
.RI "\fBvisit_list_item\fP (self, node)"
.br
.ti -1c
.RI "\fBpass_node\fP (self, node)"
.br
.ti -1c
.RI "\fBignore_node\fP (self, node)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.nodes\&.GenericNodeVisitor\fP
.in +1c
.ti -1c
.RI "\fBdefault_departure\fP (self, node)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.nodes\&.NodeVisitor\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBdocument\fP)"
.br
.ti -1c
.RI "\fBdispatch_visit\fP (self, node)"
.br
.ti -1c
.RI "\fBdispatch_departure\fP (self, node)"
.br
.ti -1c
.RI "\fBunknown_visit\fP (self, node)"
.br
.ti -1c
.RI "\fBunknown_departure\fP (self, node)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBvisit_Text\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_paragraph\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_bullet_list\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_enumerated_list\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_docinfo\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_author\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_authors\fP = \fBvisit_list_item\fP"
.br
.ti -1c
.RI "\fBvisit_address\fP = \fBvisit_list_item\fP"
.br
.ti -1c
.RI "\fBvisit_contact\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_copyright\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_date\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_organization\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_status\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_version\fP = \fBvisit_list_item\fP"
.br
.ti -1c
.RI "\fBvisit_definition_list\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_definition_list_item\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_term\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_classifier\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_definition\fP = \fBvisit_list_item\fP"
.br
.ti -1c
.RI "\fBvisit_field_list\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_field\fP = \fBpass_node\fP"
.br
.ti -1c
.RI "\fBvisit_field_body\fP = \fBvisit_list_item\fP"
.br
.ti -1c
.RI "\fBvisit_field_name\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_comment\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_substitution_definition\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_target\fP = \fBignore_node\fP"
.br
.ti -1c
.RI "\fBvisit_pending\fP = \fBignore_node\fP"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.nodes\&.NodeVisitor\fP
.in +1c
.ti -1c
.RI "tuple \fBoptional\fP = ('\fBmeta\fP',)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBdocutils\&.nodes\&.NodeVisitor\fP
.in +1c
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBoptional\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raise `nodes\&.NodeFound` if non-simple list item is encountered\&.

Here 'simple' means a list item containing nothing other than a single
paragraph, a simple list, or a paragraph followed by a simple list\&.

This version also checks for simple field lists and docinfo\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.default_visit ( self,  node)"

.PP
.nf
Override for generic, uniform traversals\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.nodes\&.GenericNodeVisitor\fP\&.
.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.ignore_node ( self,  node)"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.pass_node ( self,  node)"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_list_item ( self,  node)"

.PP
Reimplemented in \fBdocutils\&.writers\&.html4css1\&.SimpleListChecker\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_address = \fBvisit_list_item\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_author = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_authors = \fBvisit_list_item\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_bullet_list = \fBpass_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_classifier = \fBpass_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_comment = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_contact = \fBpass_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_copyright = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_date = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_definition = \fBvisit_list_item\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_definition_list = \fBpass_node\fP\fC [static]\fP"

.PP
Reimplemented in \fBdocutils\&.writers\&.html4css1\&.SimpleListChecker\fP\&.
.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_definition_list_item = \fBpass_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_docinfo = \fBpass_node\fP\fC [static]\fP"

.PP
Reimplemented in \fBdocutils\&.writers\&.html4css1\&.SimpleListChecker\fP\&.
.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_enumerated_list = \fBpass_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_field = \fBpass_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_field_body = \fBvisit_list_item\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_field_list = \fBpass_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_field_name = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_organization = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_paragraph = \fBignore_node\fP\fC [static]\fP"

.PP
Reimplemented in \fBdocutils\&.writers\&.html4css1\&.SimpleListChecker\fP\&.
.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_pending = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_status = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_substitution_definition = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_target = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_term = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_Text = \fBignore_node\fP\fC [static]\fP"

.SS "docutils\&.writers\&._html_base\&.SimpleListChecker\&.visit_version = \fBvisit_list_item\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
