.TH "docutils.writers.docutils_xml.TestXml" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.writers.docutils_xml.TestXml
.SH SYNOPSIS
.br
.PP
.PP
Inherits xml\&.sax\&.handler\&.ContentHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetDocumentLocator\fP (self, \fBlocator\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlocator\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.writers\&.docutils_xml\&.TestXml\&.setDocumentLocator ( self,  locator)"

.SH "Member Data Documentation"
.PP 
.SS "docutils\&.writers\&.docutils_xml\&.TestXml\&.locator"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
