.TH "docutils.parsers.null.Parser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.null.Parser
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.parsers\&.Parser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparse\fP (self, \fBinputstring\fP, \fBdocument\fP)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.parsers\&.Parser\fP
.in +1c
.ti -1c
.RI "\fBsetup_parse\fP (self, \fBinputstring\fP, \fBdocument\fP)"
.br
.ti -1c
.RI "\fBfinish_parse\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.Component\fP
.in +1c
.ti -1c
.RI "\fBsupports\fP (self, format)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "\fBget_transforms\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBsupported\fP = ('null',)"
.br
.ti -1c
.RI "str \fBconfig_section\fP = 'null parser'"
.br
.ti -1c
.RI "tuple \fBconfig_section_dependencies\fP = ('parsers',)"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.parsers\&.Parser\fP
.in +1c
.ti -1c
.RI "tuple \fBsettings_spec\fP"
.br
.ti -1c
.RI "str \fBcomponent_type\fP = 'parser'"
.br
.ti -1c
.RI "str \fBconfig_section\fP = 'parsers'"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.Component\fP
.in +1c
.ti -1c
.RI "\fBcomponent_type\fP = None"
.br
.ti -1c
.RI "tuple \fBsupported\fP = ()"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.SettingsSpec\fP
.in +1c
.ti -1c
.RI "tuple \fBsettings_spec\fP = ()"
.br
.ti -1c
.RI "\fBsettings_defaults\fP = None"
.br
.ti -1c
.RI "\fBsettings_default_overrides\fP = None"
.br
.ti -1c
.RI "tuple \fBrelative_path_settings\fP = ()"
.br
.ti -1c
.RI "\fBconfig_section\fP = None"
.br
.ti -1c
.RI "\fBconfig_section_dependencies\fP = None"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "tuple \fBdefault_transforms\fP = ()"
.br
.ti -1c
.RI "tuple \fBunknown_reference_resolvers\fP = ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBdocutils\&.parsers\&.Parser\fP
.in +1c
.ti -1c
.RI "\fBinputstring\fP"
.br
.ti -1c
.RI "\fBdocument\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "\fBdefault_transforms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A do-nothing parser\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.parsers\&.null\&.Parser\&.parse ( self,  inputstring,  document)"

.PP
.nf
Override to parse `inputstring` into document tree `document`\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.parsers\&.Parser\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str docutils\&.parsers\&.null\&.Parser\&.config_section = 'null parser'\fC [static]\fP"

.SS "tuple docutils\&.parsers\&.null\&.Parser\&.config_section_dependencies = ('parsers',)\fC [static]\fP"

.SS "tuple docutils\&.parsers\&.null\&.Parser\&.supported = ('null',)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
