.TH "docutils.io" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.io
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBinaryFileOutput\fP"
.br
.ti -1c
.RI "class \fBDocTreeInput\fP"
.br
.ti -1c
.RI "class \fBErrorOutput\fP"
.br
.ti -1c
.RI "class \fBFileInput\fP"
.br
.ti -1c
.RI "class \fBFileOutput\fP"
.br
.ti -1c
.RI "class \fBInput\fP"
.br
.ti -1c
.RI "class \fBInputError\fP"
.br
.ti -1c
.RI "class \fBNullInput\fP"
.br
.ti -1c
.RI "class \fBNullOutput\fP"
.br
.ti -1c
.RI "class \fBOutput\fP"
.br
.ti -1c
.RI "class \fBOutputError\fP"
.br
.ti -1c
.RI "class \fBStringInput\fP"
.br
.ti -1c
.RI "class \fBStringOutput\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcheck_encoding\fP (stream, encoding)"
.br
.ti -1c
.RI "\fBerror_string\fP (err)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fB_locale_encoding\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
I/O classes provide a uniform API for low-level input and output\&.  Subclasses
exist for a variety of input/output mechanisms\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "docutils\&.io\&.check_encoding ( stream,  encoding)"

.PP
.nf
Test, whether the encoding of `stream` matches `encoding`\&.

Returns

:None:  if `encoding` or `stream\&.encoding` are not a valid encoding
        argument (e\&.g\&. ``None``) or `stream\&.encoding is missing\&.
:True:  if the encoding argument resolves to the same value as `encoding`,
:False: if the encodings differ\&.

.fi
.PP
 
.SS "docutils\&.io\&.error_string ( err)"

.PP
.nf
Return string representation of Exception `err`\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "tuple docutils\&.io\&._locale_encoding\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  (locale\&.getlocale()[1]
2                             or locale\&.getdefaultlocale()[1])
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
