.TH "docutils.transforms.frontmatter.SectionSubTitle" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.transforms.frontmatter.SectionSubTitle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.transforms\&.frontmatter\&.TitlePromoter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBapply\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.transforms\&.frontmatter\&.TitlePromoter\fP
.in +1c
.ti -1c
.RI "\fBpromote_title\fP (self, node)"
.br
.ti -1c
.RI "\fBpromote_subtitle\fP (self, node)"
.br
.ti -1c
.RI "\fBcandidate_index\fP (self, node)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBdocument\fP, \fBstartnode\fP=None)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdefault_priority\fP = 350"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdefault_priority\fP = None"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBstartnode\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This works like document subtitles, but for sections\&.  For example, ::

    <section>
        <title>
            Title
        <section>
            <title>
                Subtitle
            \&.\&.\&.

is transformed into ::

    <section>
        <title>
            Title
        <subtitle>
            Subtitle
        \&.\&.\&.

For details refer to the docstring of DocTitle\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.transforms\&.frontmatter\&.SectionSubTitle\&.apply ( self)"

.PP
.nf
Override to apply the transform to the document tree\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.transforms\&.Transform\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int docutils\&.transforms\&.frontmatter\&.SectionSubTitle\&.default_priority = 350\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
