.TH "docutils.parsers.rst.languages.sv" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.languages.sv
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBdirectives\fP"
.br
.ti -1c
.RI "dict \fBroles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Swedish language mappings for language-dependent features of reStructuredText\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict docutils\&.parsers\&.rst\&.languages\&.sv\&.directives"

.SS "dict docutils\&.parsers\&.rst\&.languages\&.sv\&.roles"
\fBInitial value:\fP.PP
.nf
1 =  {
2       'förkortning': 'abbreviation',
3       'akronym': 'acronym',
4       'kod': 'code',
5       'index': 'index',
6       'nedsänkt': 'subscript',
7       'upphöjd': 'superscript',
8       'titel\-referens': 'title\-reference',
9       'pep\-referens': 'pep\-reference',
10       'rfc\-referens': 'rfc\-reference',
11       'betoning': 'emphasis',
12       'stark': 'strong',
13       'bokstavlig': 'literal',  # also 'ordagranna'
14       'matematik': 'math',
15       'namngiven\-referens': 'named\-reference',
16       'anonym\-referens': 'anonymous\-reference',
17       'fotnot\-referens': 'footnote\-reference',
18       'citat\-referens': 'citation\-reference',
19       'ersättnings\-referens': 'substitution\-reference',
20       'mål': 'target',
21       'uri\-referens': 'uri\-reference',
22       'rå': 'raw',
23       }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
