.TH "docutils.utils.math.math2html.Bracket" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.utils.math.math2html.Bracket
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.utils\&.math\&.math2html\&.FormulaBit\fP\&.
.PP
Inherited by \fBdocutils\&.utils\&.math\&.math2html\&.SquareBracket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBdetect\fP (self, pos)"
.br
.ti -1c
.RI "\fBparsebit\fP (self, pos)"
.br
.ti -1c
.RI "\fBparsetext\fP (self, pos)"
.br
.ti -1c
.RI "\fBparseliteral\fP (self, pos)"
.br
.ti -1c
.RI "\fBparsecomplete\fP (self, pos, innerparser)"
.br
.ti -1c
.RI "\fBinnerformula\fP (self, pos)"
.br
.ti -1c
.RI "\fBinnertext\fP (self, pos)"
.br
.ti -1c
.RI "\fBinnerliteral\fP (self, pos)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.utils\&.math\&.math2html\&.FormulaBit\fP
.in +1c
.ti -1c
.RI "\fBsetfactory\fP (self, \fBfactory\fP)"
.br
.ti -1c
.RI "\fBadd\fP (self, bit)"
.br
.ti -1c
.RI "\fBskiporiginal\fP (self, string, pos)"
.br
.ti -1c
.RI "\fBcomputesize\fP (self)"
.br
.ti -1c
.RI "\fBclone\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.utils\&.math\&.math2html\&.Container\fP
.in +1c
.ti -1c
.RI "\fBprocess\fP (self)"
.br
.ti -1c
.RI "\fBgethtml\fP (self)"
.br
.ti -1c
.RI "\fBescape\fP (self, line, replacements=\fBEscapeConfig\&.entities\fP)"
.br
.ti -1c
.RI "\fBescapeentities\fP (self, line)"
.br
.ti -1c
.RI "\fBsearchall\fP (self, type)"
.br
.ti -1c
.RI "\fBsearchremove\fP (self, type)"
.br
.ti -1c
.RI "\fBsearchprocess\fP (self, type, \fBprocess\fP)"
.br
.ti -1c
.RI "\fBlocateprocess\fP (self, locate, \fBprocess\fP)"
.br
.ti -1c
.RI "\fBrecursivesearch\fP (self, locate, recursive, \fBprocess\fP)"
.br
.ti -1c
.RI "\fBextracttext\fP (self)"
.br
.ti -1c
.RI "\fBgroup\fP (self, index, group, isingroup)"
.br
.ti -1c
.RI "\fBremove\fP (self, index)"
.br
.ti -1c
.RI "\fBtree\fP (self, level=0)"
.br
.ti -1c
.RI "\fBgetparameter\fP (self, name)"
.br
.ti -1c
.RI "\fBgetparameterlist\fP (self, name)"
.br
.ti -1c
.RI "\fBhasemptyoutput\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBinner\fP"
.br
.ti -1c
.RI "\fBinnerformula\fP"
.br
.ti -1c
.RI "\fBinnertext\fP"
.br
.ti -1c
.RI "\fBinnerliteral\fP"
.br
.ti -1c
.RI "\fBliteral\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.utils\&.math\&.math2html\&.FormulaBit\fP
.in +1c
.ti -1c
.RI "\fBcontents\fP"
.br
.ti -1c
.RI "\fBoutput\fP"
.br
.ti -1c
.RI "\fBfactory\fP"
.br
.ti -1c
.RI "\fBsize\fP"
.br
.ti -1c
.RI "\fBoriginal\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.utils\&.math\&.math2html\&.Container\fP
.in +1c
.ti -1c
.RI "\fBcontents\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstart\fP = \fBFormulaConfig\&.starts\fP['bracket']"
.br
.ti -1c
.RI "\fBending\fP = \fBFormulaConfig\&.endings\fP['bracket']"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.utils\&.math\&.math2html\&.FormulaBit\fP
.in +1c
.ti -1c
.RI "\fBtype\fP = None"
.br
.ti -1c
.RI "int \fBsize\fP = 1"
.br
.ti -1c
.RI "str \fBoriginal\fP = ''"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.utils\&.math\&.math2html\&.Container\fP
.in +1c
.ti -1c
.RI "\fBpartkey\fP = None"
.br
.ti -1c
.RI "\fBparent\fP = None"
.br
.ti -1c
.RI "\fBbegin\fP = None"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.__init__ ( self)"

.PP
Reimplemented from \fBdocutils\&.utils\&.math\&.math2html\&.FormulaBit\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.detect ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.innerformula ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.innerliteral ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.innertext ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.parsebit ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.parsecomplete ( self,  pos,  innerparser)"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.parseliteral ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.parsetext ( self,  pos)"

.SH "Member Data Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.ending = \fBFormulaConfig\&.endings\fP['bracket']\fC [static]\fP"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.inner"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.innerformula"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.innerliteral"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.innertext"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.literal"

.SS "docutils\&.utils\&.math\&.math2html\&.Bracket\&.start = \fBFormulaConfig\&.starts\fP['bracket']\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
