.TH "docutils.utils.math.math2html.BracketProcessor" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.utils.math.math2html.BracketProcessor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.utils\&.math\&.math2html\&.MathsProcessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprocess\fP (self, contents, index)"
.br
.ti -1c
.RI "\fBprocessleft\fP (self, contents, index)"
.br
.ti -1c
.RI "\fBcheckleft\fP (self, contents, index)"
.br
.ti -1c
.RI "\fBcheckright\fP (self, contents, index)"
.br
.ti -1c
.RI "\fBcheckdirection\fP (self, bit, command)"
.br
.ti -1c
.RI "\fBfindright\fP (self, contents, index)"
.br
.ti -1c
.RI "\fBfindmax\fP (self, contents, leftindex, rightindex)"
.br
.ti -1c
.RI "\fBresize\fP (self, command, size)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.utils\&.math\&.math2html\&.MathsProcessor\fP
.in +1c
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.math2html\&.BracketProcessor\&.checkdirection ( self,  bit,  command)"

.SS "docutils\&.utils\&.math\&.math2html\&.BracketProcessor\&.checkleft ( self,  contents,  index)"

.SS "docutils\&.utils\&.math\&.math2html\&.BracketProcessor\&.checkright ( self,  contents,  index)"

.SS "docutils\&.utils\&.math\&.math2html\&.BracketProcessor\&.findmax ( self,  contents,  leftindex,  rightindex)"

.SS "docutils\&.utils\&.math\&.math2html\&.BracketProcessor\&.findright ( self,  contents,  index)"

.SS "docutils\&.utils\&.math\&.math2html\&.BracketProcessor\&.process ( self,  contents,  index)"

.PP
Reimplemented from \fBdocutils\&.utils\&.math\&.math2html\&.MathsProcessor\fP\&.
.SS "docutils\&.utils\&.math\&.math2html\&.BracketProcessor\&.processleft ( self,  contents,  index)"

.SS "docutils\&.utils\&.math\&.math2html\&.BracketProcessor\&.resize ( self,  command,  size)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
