.TH "docutils.utils.error_reporting.ErrorOutput" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.utils.error_reporting.ErrorOutput
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBstream\fP=None, \fBencoding\fP=None, \fBencoding_errors\fP='backslashreplace', \fBdecoding_errors\fP='replace')"
.br
.ti -1c
.RI "\fBwrite\fP (self, data)"
.br
.ti -1c
.RI "\fBclose\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstream\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBencoding_errors\fP"
.br
.ti -1c
.RI "\fBdecoding_errors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Wrapper class for file-like error streams with
failsafe de- and encoding of `str`, `bytes`, `unicode` and
`Exception` instances\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.utils\&.error_reporting\&.ErrorOutput\&.__init__ ( self,  stream = \fCNone\fP,  encoding = \fCNone\fP,  encoding_errors = \fC'backslashreplace'\fP,  decoding_errors = \fC'replace'\fP)"

.PP
.nf
:Parameters:
    - `stream`: a file-like object,
                a string (path to a file),
                `None` (write to `sys\&.stderr`, default), or
                evaluating to `False` (write() requests are ignored)\&.
    - `encoding`: `stream` text encoding\&. Guessed if None\&.
    - `encoding_errors`: how to treat encoding errors\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.utils\&.error_reporting\&.ErrorOutput\&.close ( self)"

.PP
.nf
Close the error-output stream\&.

Ignored if the stream is` sys\&.stderr` or `sys\&.stdout` or has no
close() method\&.

.fi
.PP
 
.SS "docutils\&.utils\&.error_reporting\&.ErrorOutput\&.write ( self,  data)"

.PP
.nf
Write `data` to self\&.stream\&. Ignore, if self\&.stream is False\&.

`data` can be a `string`, `unicode`, or `Exception` instance\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "docutils\&.utils\&.error_reporting\&.ErrorOutput\&.decoding_errors"

.SS "docutils\&.utils\&.error_reporting\&.ErrorOutput\&.encoding"

.SS "docutils\&.utils\&.error_reporting\&.ErrorOutput\&.encoding_errors"

.SS "docutils\&.utils\&.error_reporting\&.ErrorOutput\&.stream"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
