.TH "docutils.languages.sv" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.sv
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Swedish language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.sv\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.sv\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2     # 'Author' and 'Authors' identical in Swedish; assume the plural:
3     'författare': 'authors',
4     ' n/a': 'author',  # removing leads to (spurious) test failure
5     'organisation': 'organization',
6     'adress': 'address',
7     'kontakt': 'contact',
8     'version': 'version',
9     'revision': 'revision',
10     'status': 'status',
11     'datum': 'date',
12     'copyright': 'copyright',
13     'dedikation': 'dedication',
14     'sammanfattning': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.sv\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'author': 'Författare',
3     'authors': 'Författare',
4     'organization': 'Organisation',
5     'address': 'Adress',
6     'contact': 'Kontakt',
7     'version': 'Version',
8     'revision': 'Revision',
9     'status': 'Status',
10     'date': 'Datum',
11     'copyright': 'Copyright',
12     'dedication': 'Dedikation',
13     'abstract': 'Sammanfattning',
14     'attention': 'Observera!',
15     'caution': 'Akta!',  # 'Varning' already used for 'warning'
16     'danger': 'FARA!',
17     'error': 'Fel',
18     'hint': 'Vink',
19     'important': 'Viktigt',
20     'note': 'Notera',
21     'tip': 'Tips',
22     'warning': 'Varning',
23     'contents': 'Innehåll'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
