.TH "docutils.parsers.rst.roles.CustomRole" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.roles.CustomRole
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, role_name, \fBbase_role\fP, \fBoptions\fP=None, \fBcontent\fP=None)"
.br
.ti -1c
.RI "\fB__call__\fP (self, \fBrole\fP, rawtext, text, \fBlineno\fP, inliner, \fBoptions\fP=None, \fBcontent\fP=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBbase_role\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBcontent\fP"
.br
.ti -1c
.RI "\fBsupplied_options\fP"
.br
.ti -1c
.RI "\fBsupplied_content\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Wrapper for custom interpreted text roles\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.roles\&.CustomRole\&.__init__ ( self,  role_name,  base_role,  options = \fCNone\fP,  content = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.roles\&.CustomRole\&.__call__ ( self,  role,  rawtext,  text,  lineno,  inliner,  options = \fCNone\fP,  content = \fCNone\fP)"

.SH "Member Data Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.roles\&.CustomRole\&.base_role"

.SS "docutils\&.parsers\&.rst\&.roles\&.CustomRole\&.content"

.SS "docutils\&.parsers\&.rst\&.roles\&.CustomRole\&.name"

.SS "docutils\&.parsers\&.rst\&.roles\&.CustomRole\&.options"

.SS "docutils\&.parsers\&.rst\&.roles\&.CustomRole\&.supplied_content"

.SS "docutils\&.parsers\&.rst\&.roles\&.CustomRole\&.supplied_options"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
