.TH "docutils.languages.fa" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.fa
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = ['؛', '،']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Persian-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.fa\&.author_separators = ['؛', '،']"

.SS "dict docutils\&.languages\&.fa\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # language\-dependent: fixed
3       'نویسنده': 'author',
4       'نویسندگان': 'authors',
5       'سازمان': 'organization',
6       'آدرس': 'address',
7       'تماس': 'contact',
8       'نسخه': 'version',
9       'بازبینی': 'revision',
10       'وضعیت': 'status',
11       'تاریخ': 'date',
12       'کپی‌رایت': 'copyright',
13       'تخصیص': 'dedication',
14       'چکیده': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.fa\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # fixed: language\-dependent
3       'author': 'نویسنده',
4       'authors': 'نویسندگان',
5       'organization': 'سازمان',
6       'address': 'آدرس',
7       'contact': 'تماس',
8       'version': 'نسخه',
9       'revision': 'بازبینی',
10       'status': 'وضعیت',
11       'date': 'تاریخ',
12       'copyright': 'کپی‌رایت',
13       'dedication': 'تخصیص',
14       'abstract': 'چکیده',
15       'attention': 'توجه!',
16       'caution': 'احتیاط!',
17       'danger': 'خطر!',
18       'error': 'خطا',
19       'hint': 'راهنما',
20       'important': 'مهم',
21       'note': 'یادداشت',
22       'tip': 'نکته',
23       'warning': 'اخطار',
24       'contents': 'محتوا'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
