.TH "docutils.languages.lv" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.lv
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Latvian-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.lv\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.lv\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # language\-dependent: fixed
3       'autors': 'author',
4       'autori': 'authors',
5       'organizācija': 'organization',
6       'adrese': 'address',
7       'kontakti': 'contact',
8       'versija': 'version',
9       'revīzija': 'revision',
10       'statuss': 'status',
11       'datums': 'date',
12       'copyright': 'copyright',
13       'veltījums': 'dedication',
14       'atreferējums': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.lv\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # fixed: language\-dependent
3       'author': 'Autors',
4       'authors': 'Autori',
5       'organization': 'Organizācija',
6       'address': 'Adrese',
7       'contact': 'Kontakti',
8       'version': 'Versija',
9       'revision': 'Revīzija',
10       'status': 'Statuss',
11       'date': 'Datums',
12       'copyright': 'Copyright',
13       'dedication': 'Veltījums',
14       'abstract': 'Atreferējums',
15       'attention': 'Uzmanību!',
16       'caution': 'Piesardzību!',
17       'danger': '!BĪSTAMI!',
18       'error': 'Kļūda',
19       'hint': 'Ieteikums',
20       'important': 'Svarīgi',
21       'note': 'Piezīme',
22       'tip': 'Padoms',
23       'warning': 'Brīdinājums',
24       'contents': 'Saturs'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
