.TH "docutils.transforms" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.transforms
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcomponents\fP"
.br
.ti -1c
.RI "namespace \fBfrontmatter\fP"
.br
.ti -1c
.RI "namespace \fBmisc\fP"
.br
.ti -1c
.RI "namespace \fBparts\fP"
.br
.ti -1c
.RI "namespace \fBpeps\fP"
.br
.ti -1c
.RI "namespace \fBreferences\fP"
.br
.ti -1c
.RI "namespace \fBuniversal\fP"
.br
.ti -1c
.RI "namespace \fBwriter_aux\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransform\fP"
.br
.ti -1c
.RI "class \fBTransformer\fP"
.br
.ti -1c
.RI "class \fBTransformError\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This package contains modules for standard tree transforms available
to Docutils components\&. Tree transforms serve a variety of purposes:

- To tie up certain syntax-specific 'loose ends' that remain after the
  initial parsing of the input plaintext\&. These transforms are used to
  supplement a limited syntax\&.

- To automate the internal linking of the document tree (hyperlink
  references, footnote references, etc\&.)\&.

- To extract useful information from the document tree\&. These
  transforms may be used to construct (for example) indexes and tables
  of contents\&.

Each transform is an optional step that a Docutils component may
choose to perform on the parsed document\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
