.TH "docutils.statemachine.StateCorrection" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.statemachine.StateCorrection
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Raise from within a transition method to switch to another state\&.

Raise with one or two arguments: new state name, and an optional new
transition name\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
