.TH "docutils.writers.odf_odt.ListLevel" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.writers.odf_odt.ListLevel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBlevel\fP, \fBsibling_level\fP=True, \fBnested_level\fP=True)"
.br
.ti -1c
.RI "\fBset_sibling\fP (self, \fBsibling_level\fP)"
.br
.ti -1c
.RI "\fBget_sibling\fP (self)"
.br
.ti -1c
.RI "\fBset_nested\fP (self, \fBnested_level\fP)"
.br
.ti -1c
.RI "\fBget_nested\fP (self)"
.br
.ti -1c
.RI "\fBset_level\fP (self, \fBlevel\fP)"
.br
.ti -1c
.RI "\fBget_level\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlevel\fP"
.br
.ti -1c
.RI "\fBsibling_level\fP"
.br
.ti -1c
.RI "\fBnested_level\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.__init__ ( self,  level,  sibling_level = \fCTrue\fP,  nested_level = \fCTrue\fP)"

.SH "Member Function Documentation"
.PP 
.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.get_level ( self)"

.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.get_nested ( self)"

.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.get_sibling ( self)"

.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.set_level ( self,  level)"

.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.set_nested ( self,  nested_level)"

.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.set_sibling ( self,  sibling_level)"

.SH "Member Data Documentation"
.PP 
.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.level"

.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.nested_level"

.SS "docutils\&.writers\&.odf_odt\&.ListLevel\&.sibling_level"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
