.TH "docutils.languages.he" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.he
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Hebrew-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.he\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.he\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2     # language\-dependent: fixed
3     'מחבר': 'author',
4     'מחברי': 'authors',
5     'ארגון': 'organization',
6     'כתובת': 'address',
7     'איש קשר': 'contact',
8     'גרסה': 'version',
9     'מהדורה': 'revision',
10     'סטטוס': 'status',
11     'תאריך': 'date',
12     'זכויות שמורות': 'copyright',
13     'הקדשה': 'dedication',
14     'תקציר': 'abstract',
15     }
.fi

.SS "dict docutils\&.languages\&.he\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2     # fixed: language\-dependent
3     'author': 'מחבר',
4     'authors': 'מחברי',
5     'organization': 'ארגון',
6     'address': 'כתובת',
7     'contact': 'איש קשר',
8     'version': 'גרסה',
9     'revision': 'מהדורה',
10     'status': 'סטטוס',
11     'date': 'תאריך',
12     'copyright': 'זכויות שמורות',
13     'dedication': 'הקדשה',
14     'abstract': 'תקציר',
15     'attention': 'תשומת לב',
16     'caution': 'זהירות',
17     'danger': 'סכנה',
18     'error': 'שגיאה',
19     'hint': 'רמז',
20     'important': 'חשוב',
21     'note': 'הערה',
22     'tip': 'טיפ',
23     'warning': 'אזהרה',
24     'contents': 'תוכן',
25     }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
