.TH "docutils.parsers.rst.directives.misc" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.directives.misc
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClass\fP"
.br
.ti -1c
.RI "class \fBDate\fP"
.br
.ti -1c
.RI "class \fBDefaultRole\fP"
.br
.ti -1c
.RI "class \fBInclude\fP"
.br
.ti -1c
.RI "class \fBMeta\fP"
.br
.ti -1c
.RI "class \fBMetaBody\fP"
.br
.ti -1c
.RI "class \fBRaw\fP"
.br
.ti -1c
.RI "class \fBReplace\fP"
.br
.ti -1c
.RI "class \fBRole\fP"
.br
.ti -1c
.RI "class \fBTestDirective\fP"
.br
.ti -1c
.RI "class \fBTitle\fP"
.br
.ti -1c
.RI "class \fBUnicode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBadapt_path\fP (\fBpath\fP, source='', root_prefix='/')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Miscellaneous directives\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.directives\&.misc\&.adapt_path ( path,  source = \fC''\fP,  root_prefix = \fC'/'\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
