.TH "docutils.nodes.Titular" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.nodes.Titular
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdocutils\&.nodes\&.rubric\fP, \fBdocutils\&.nodes\&.subtitle\fP, and \fBdocutils\&.nodes\&.title\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
