.TH "docutils.parsers.rst.DirectiveError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.DirectiveError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBlevel\fP, message)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlevel\fP"
.br
.ti -1c
.RI "\fBmsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Store a message and a system message level\&.

To be thrown from inside directive code\&.

Do not instantiate directly -- use `Directive\&.directive_error()`
instead!

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.DirectiveError\&.__init__ ( self,  level,  message)"

.PP
.nf
Set error `message` and `level`
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.DirectiveError\&.level"

.SS "docutils\&.parsers\&.rst\&.DirectiveError\&.msg"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
