.TH "docutils.parsers.rst.languages.fi" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.languages.fi
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBdirectives\fP"
.br
.ti -1c
.RI "dict \fBroles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Finnish-language mappings for language-dependent features of
reStructuredText\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict docutils\&.parsers\&.rst\&.languages\&.fi\&.directives"

.SS "dict docutils\&.parsers\&.rst\&.languages\&.fi\&.roles"
\fBInitial value:\fP.PP
.nf
1 =  {
2     # language\-dependent: fixed
3     'lyhennys': 'abbreviation',
4     'akronyymi': 'acronym',
5     'kirjainsana': 'acronym',
6     'code (translation required)': 'code',
7     'hakemisto': 'index',
8     'luettelo': 'index',
9     'alaindeksi': 'subscript',
10     'indeksi': 'subscript',
11     'yläindeksi': 'superscript',
12     'title\-reference (translation required)': 'title\-reference',
13     'title (translation required)': 'title\-reference',
14     'pep\-reference (translation required)': 'pep\-reference',
15     'rfc\-reference (translation required)': 'rfc\-reference',
16     'korostus': 'emphasis',
17     'vahvistus': 'strong',
18     'tasalevyinen': 'literal',
19     'math (translation required)': 'math',
20     'named\-reference (translation required)': 'named\-reference',
21     'anonymous\-reference (translation required)': 'anonymous\-reference',
22     'footnote\-reference (translation required)': 'footnote\-reference',
23     'citation\-reference (translation required)': 'citation\-reference',
24     'substitution\-reference (translation required)': 'substitution\-reference',
25     'kohde': 'target',
26     'uri\-reference (translation required)': 'uri\-reference',
27     'raw (translation required)': 'raw',
28     }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
