.TH "docutils.transforms.writer_aux" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.transforms.writer_aux
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdmonitions\fP"
.br
.ti -1c
.RI "class \fBCompound\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Auxiliary transforms mainly to be used by Writer components\&.

This module is called 'writer_aux' because otherwise there would be
conflicting imports like this one::

    from docutils import writers
    from docutils\&.transforms import writers

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
