.TH "docutils.nodes.TreePruningException" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.nodes.TreePruningException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBdocutils\&.nodes\&.NodeFound\fP, \fBdocutils\&.nodes\&.SkipChildren\fP, \fBdocutils\&.nodes\&.SkipDeparture\fP, \fBdocutils\&.nodes\&.SkipNode\fP, \fBdocutils\&.nodes\&.SkipSiblings\fP, and \fBdocutils\&.nodes\&.StopTraversal\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Base class for `NodeVisitor`-related tree pruning exceptions\&.

Raise subclasses from within ``visit_\&.\&.\&.`` or ``depart_\&.\&.\&.`` methods
called from `Node\&.walk()` and `Node\&.walkabout()` tree traversals to prune
the tree traversed\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
