.TH "docutils.languages.sk" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.sk
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Slovak-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.sk\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.sk\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       'autor': 'author',
3       'autori': 'authors',
4       'organizácia': 'organization',
5       'adresa': 'address',
6       'kontakt': 'contact',
7       'verzia': 'version',
8       'revízia': 'revision',
9       'stav': 'status',
10       'dátum': 'date',
11       'copyright': 'copyright',
12       'venovanie': 'dedication',
13       'abstraktne': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.sk\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       'author': 'Autor',
3       'authors': 'Autori',
4       'organization': 'Organizácia',
5       'address': 'Adresa',
6       'contact': 'Kontakt',
7       'version': 'Verzia',
8       'revision': 'Revízia',
9       'status': 'Stav',
10       'date': 'Dátum',
11       'copyright': 'Copyright',
12       'dedication': 'Venovanie',
13       'abstract': 'Abstraktne',
14       'attention': 'Pozor!',
15       'caution': 'Opatrne!',
16       'danger': '!NEBEZPEČENSTVO!',
17       'error': 'Chyba',
18       'hint': 'Rada',
19       'important': 'Dôležité',
20       'note': 'Poznámka',
21       'tip': 'Tip',
22       'warning': 'Varovanie',
23       'contents': 'Obsah'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
