.TH "docutils.utils.code_analyzer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.utils.code_analyzer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLexer\fP"
.br
.ti -1c
.RI "class \fBLexerError\fP"
.br
.ti -1c
.RI "class \fBNumberLines\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBwith_pygments\fP = True"
.br
.ti -1c
.RI "list \fBunstyled_tokens\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Lexical analysis of formal languages (i\&.e\&. code) using Pygments\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.utils\&.code_analyzer\&.unstyled_tokens"
\fBInitial value:\fP.PP
.nf
1 =  ['token',  # Token (base token type)
2                    'text',   # Token\&.Text
3                    '']
.fi

.SS "bool docutils\&.utils\&.code_analyzer\&.with_pygments = True"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
