.TH "docutils.readers.Reader" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.readers.Reader
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.Component\fP\&.
.PP
Inherited by \fBdocutils\&.readers\&.ReReader\fP, and \fBdocutils\&.readers\&.standalone\&.Reader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBget_transforms\fP (self)"
.br
.ti -1c
.RI "\fB__init__\fP (self, \fBparser\fP=None, parser_name=None)"
.br
.ti -1c
.RI "\fBset_parser\fP (self, parser_name)"
.br
.ti -1c
.RI "\fBread\fP (self, \fBsource\fP, \fBparser\fP, \fBsettings\fP)"
.br
.ti -1c
.RI "\fBparse\fP (self)"
.br
.ti -1c
.RI "\fBnew_document\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.Component\fP
.in +1c
.ti -1c
.RI "\fBsupports\fP (self, format)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparser\fP"
.br
.ti -1c
.RI "\fBsource\fP"
.br
.ti -1c
.RI "\fBinput\fP"
.br
.ti -1c
.RI "\fBsettings\fP"
.br
.ti -1c
.RI "\fBdocument\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "\fBdefault_transforms\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBcomponent_type\fP = 'reader'"
.br
.ti -1c
.RI "str \fBconfig_section\fP = 'readers'"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.Component\fP
.in +1c
.ti -1c
.RI "\fBcomponent_type\fP = None"
.br
.ti -1c
.RI "tuple \fBsupported\fP = ()"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.SettingsSpec\fP
.in +1c
.ti -1c
.RI "tuple \fBsettings_spec\fP = ()"
.br
.ti -1c
.RI "\fBsettings_defaults\fP = None"
.br
.ti -1c
.RI "\fBsettings_default_overrides\fP = None"
.br
.ti -1c
.RI "tuple \fBrelative_path_settings\fP = ()"
.br
.ti -1c
.RI "\fBconfig_section\fP = None"
.br
.ti -1c
.RI "\fBconfig_section_dependencies\fP = None"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "tuple \fBdefault_transforms\fP = ()"
.br
.ti -1c
.RI "tuple \fBunknown_reference_resolvers\fP = ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Abstract base class for docutils Readers\&.

Each reader module or package must export a subclass also called 'Reader'\&.

The two steps of a Reader's responsibility are to read data from the
source Input object and parse the data with the Parser object\&.
Call `read()` to process a document\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.readers\&.Reader\&.__init__ ( self,  parser = \fCNone\fP,  parser_name = \fCNone\fP)"

.PP
.nf
Initialize the Reader instance\&.

Several instance attributes are defined with dummy initial values\&.
Subclasses may use these attributes as they wish\&.

.fi
.PP
 
.PP
Reimplemented in \fBdocutils\&.readers\&.pep\&.Reader\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.readers\&.Reader\&.get_transforms ( self)"

.PP
.nf
Transforms required by this class\&.  Override in subclasses\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.TransformSpec\fP\&.
.PP
Reimplemented in \fBdocutils\&.readers\&.ReReader\fP, \fBdocutils\&.readers\&.pep\&.Reader\fP, and \fBdocutils\&.readers\&.standalone\&.Reader\fP\&.
.SS "docutils\&.readers\&.Reader\&.new_document ( self)"

.PP
.nf
Create and return a new empty document tree (root node)\&.
.fi
.PP
 
.SS "docutils\&.readers\&.Reader\&.parse ( self)"

.PP
.nf
Parse `self\&.input` into a document tree\&.
.fi
.PP
 
.PP
Reimplemented in \fBdocutils\&.readers\&.doctree\&.Reader\fP\&.
.SS "docutils\&.readers\&.Reader\&.read ( self,  source,  parser,  settings)"

.SS "docutils\&.readers\&.Reader\&.set_parser ( self,  parser_name)"

.PP
.nf
Set `self\&.parser` by name\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "str docutils\&.readers\&.Reader\&.component_type = 'reader'\fC [static]\fP"

.SS "str docutils\&.readers\&.Reader\&.config_section = 'readers'\fC [static]\fP"

.SS "docutils\&.readers\&.Reader\&.document"

.SS "docutils\&.readers\&.Reader\&.input"

.SS "docutils\&.readers\&.Reader\&.parser"

.SS "docutils\&.readers\&.Reader\&.settings"

.SS "docutils\&.readers\&.Reader\&.source"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
