.TH "docutils.languages.fi" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.fi
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Finnish-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.fi\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.fi\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # language\-dependent: fixed
3       'tekijä': 'author',
4       'tekijät': 'authors',
5       'yhteisö': 'organization',
6       'osoite': 'address',
7       'yhteystiedot': 'contact',
8       'versio': 'version',
9       'vedos': 'revision',
10       'tila': 'status',
11       'päiväys': 'date',
12       'tekijänoikeudet': 'copyright',
13       'omistuskirjoitus': 'dedication',
14       'tiivistelmä': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.fi\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # fixed: language\-dependent
3       'author': 'Tekijä',
4       'authors': 'Tekijät',
5       'organization': 'Yhteisö',
6       'address': 'Osoite',
7       'contact': 'Yhteystiedot',
8       'version': 'Versio',
9       'revision': 'Vedos',
10       'status': 'Tila',
11       'date': 'Päiväys',
12       'copyright': 'Tekijänoikeudet',
13       'dedication': 'Omistuskirjoitus',
14       'abstract': 'Tiivistelmä',
15       'attention': 'Huomio!',
16       'caution': 'Varo!',
17       'danger': '!VAARA!',
18       'error': 'Virhe',
19       'hint': 'Vihje',
20       'important': 'Tärkeää',
21       'note': 'Huomautus',
22       'tip': 'Neuvo',
23       'warning': 'Varoitus',
24       'contents': 'Sisällys'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
