.TH "docutils.parsers.rst.languages.fr" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.languages.fr
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBdirectives\fP"
.br
.ti -1c
.RI "dict \fBroles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
French-language mappings for language-dependent features of
reStructuredText\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict docutils\&.parsers\&.rst\&.languages\&.fr\&.directives"

.SS "dict docutils\&.parsers\&.rst\&.languages\&.fr\&.roles"
\fBInitial value:\fP.PP
.nf
1 =  {
2       'abréviation': 'abbreviation',
3       'acronyme': 'acronym',
4       'sigle': 'acronym',
5       'code': 'code',
6       'emphase': 'emphasis',
7       'littéral': 'literal',
8       'math (translation required)': 'math',
9       'pep\-référence': 'pep\-reference',
10       'rfc\-référence': 'rfc\-reference',
11       'fort': 'strong',
12       'indice': 'subscript',
13       'ind': 'subscript',
14       'exposant': 'superscript',
15       'exp': 'superscript',
16       'titre\-référence': 'title\-reference',
17       'titre': 'title\-reference',
18       'brut': 'raw',
19       # the following roles are not implemented in Docutils
20       'index': 'index',
21       'nommée\-référence': 'named\-reference',
22       'anonyme\-référence': 'anonymous\-reference',
23       'note\-référence': 'footnote\-reference',
24       'citation\-référence': 'citation\-reference',
25       'substitution\-référence': 'substitution\-reference',
26       'lien': 'target',
27       'uri\-référence': 'uri\-reference',
28       }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
