.TH "docutils.statemachine" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.statemachine
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_SearchOverride\fP"
.br
.ti -1c
.RI "class \fBDuplicateStateError\fP"
.br
.ti -1c
.RI "class \fBDuplicateTransitionError\fP"
.br
.ti -1c
.RI "class \fBSearchStateMachine\fP"
.br
.ti -1c
.RI "class \fBSearchStateMachineWS\fP"
.br
.ti -1c
.RI "class \fBState\fP"
.br
.ti -1c
.RI "class \fBStateCorrection\fP"
.br
.ti -1c
.RI "class \fBStateMachine\fP"
.br
.ti -1c
.RI "class \fBStateMachineError\fP"
.br
.ti -1c
.RI "class \fBStateMachineWS\fP"
.br
.ti -1c
.RI "class \fBStateWS\fP"
.br
.ti -1c
.RI "class \fBStringList\fP"
.br
.ti -1c
.RI "class \fBTransitionCorrection\fP"
.br
.ti -1c
.RI "class \fBTransitionMethodNotFound\fP"
.br
.ti -1c
.RI "class \fBTransitionPatternNotFound\fP"
.br
.ti -1c
.RI "class \fBUnexpectedIndentationError\fP"
.br
.ti -1c
.RI "class \fBUnknownStateError\fP"
.br
.ti -1c
.RI "class \fBUnknownTransitionError\fP"
.br
.ti -1c
.RI "class \fBViewList\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstring2lines\fP (astring, tab_width=8, convert_whitespace=False, whitespace=re\&.compile('[\\v\\f]'))"
.br
.ti -1c
.RI "\fB_exception_data\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A finite state machine specialized for regular-expression-based text filters,
this module defines the following classes:

- `StateMachine`, a state machine
- `State`, a state superclass
- `StateMachineWS`, a whitespace-sensitive version of `StateMachine`
- `StateWS`, a state superclass for use with `StateMachineWS`
- `SearchStateMachine`, uses `re\&.search()` instead of `re\&.match()`
- `SearchStateMachineWS`, uses `re\&.search()` instead of `re\&.match()`
- `ViewList`, extends standard Python lists\&.
- `StringList`, string-specific ViewList\&.

Exception classes:

- `StateMachineError`
- `UnknownStateError`
- `DuplicateStateError`
- `UnknownTransitionError`
- `DuplicateTransitionError`
- `TransitionPatternNotFound`
- `TransitionMethodNotFound`
- `UnexpectedIndentationError`
- `TransitionCorrection`: Raised to switch to another transition\&.
- `StateCorrection`: Raised to switch to another state & transition\&.

Functions:

- `string2lines()`: split a multi-line string into a list of one-line strings


How To Use This Module
======================
(See the individual classes, methods, and attributes for details\&.)

1\&. Import it: ``import statemachine`` or ``from statemachine import \&.\&.\&.``\&.
   You will also need to ``import re``\&.

2\&. Derive a subclass of `State` (or `StateWS`) for each state in your state
   machine::

       class MyState(statemachine\&.State):

   Within the state's class definition:

   a) Include a pattern for each transition, in `State\&.patterns`::

          patterns = {'atransition': r'pattern', \&.\&.\&.}

   b) Include a list of initial transitions to be set up automatically, in
      `State\&.initial_transitions`::

          initial_transitions = ['atransition', \&.\&.\&.]

   c) Define a method for each transition, with the same name as the
      transition pattern::

          def atransition(self, match, context, next_state):
              # do something
              result = [\&.\&.\&.]  # a list
              return context, next_state, result
              # context, next_state may be altered

      Transition methods may raise an `EOFError` to cut processing short\&.

   d) You may wish to override the `State\&.bof()` and/or `State\&.eof()` implicit
      transition methods, which handle the beginning- and end-of-file\&.

   e) In order to handle nested processing, you may wish to override the
      attributes `State\&.nested_sm` and/or `State\&.nested_sm_kwargs`\&.

      If you are using `StateWS` as a base class, in order to handle nested
      indented blocks, you may wish to:

      - override the attributes `StateWS\&.indent_sm`,
        `StateWS\&.indent_sm_kwargs`, `StateWS\&.known_indent_sm`, and/or
        `StateWS\&.known_indent_sm_kwargs`;
      - override the `StateWS\&.blank()` method; and/or
      - override or extend the `StateWS\&.indent()`, `StateWS\&.known_indent()`,
        and/or `StateWS\&.firstknown_indent()` methods\&.

3\&. Create a state machine object::

       sm = StateMachine(state_classes=[MyState, \&.\&.\&.],
                         initial_state='MyState')

4\&. Obtain the input text, which needs to be converted into a tab-free list of
   one-line strings\&. For example, to read text from a file called
   'inputfile'::

       with open('inputfile', encoding='utf-8') as fp:
           input_string = fp\&.read()
       input_lines = statemachine\&.string2lines(input_string)

5\&. Run the state machine on the input text and collect the results, a list::

       results = sm\&.run(input_lines)

6\&. Remove any lingering circular references::

       sm\&.unlink()

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "docutils\&.statemachine\&._exception_data ()\fC [protected]\fP"

.PP
.nf
Return exception information:

- the exception's class name;
- the exception object;
- the name of the file containing the offending code;
- the line number of the offending code;
- the function name of the offending code\&.

.fi
.PP
 
.SS "docutils\&.statemachine\&.string2lines ( astring,  tab_width = \fC8\fP,  convert_whitespace = \fCFalse\fP,  whitespace = \fCre\&.compile('[\\v\\f]')\fP)"

.PP
.nf
Return a list of one-line strings with tabs expanded, no newlines, and
trailing whitespace stripped\&.

Each tab is expanded with between 1 and `tab_width` spaces, so that the
next character's index becomes a multiple of `tab_width` (8 by default)\&.

Parameters:

- `astring`: a multi-line string\&.
- `tab_width`: the number of columns between tab stops\&.
- `convert_whitespace`: convert form feeds and vertical tabs to spaces?
- `whitespace`: pattern object with the to-be-converted
  whitespace characters (default [\\\\v\\\\f])\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
