.TH "docutils.languages.ca" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.ca
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Catalan-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.ca\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.ca\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # language\-dependent: fixed
3       'autor': 'author',
4       'autors': 'authors',
5       'organització': 'organization',
6       'adreça': 'address',
7       'contacte': 'contact',
8       'versió': 'version',
9       'revisió': 'revision',
10       'estat': 'status',
11       'data': 'date',
12       'copyright': 'copyright',
13       'dedicatòria': 'dedication',
14       'resum': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.ca\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # fixed: language\-dependent
3       'author': 'Autor',
4       'authors': 'Autors',
5       'organization': 'Organització',
6       'address': 'Adreça',
7       'contact': 'Contacte',
8       'version': 'Versió',
9       'revision': 'Revisió',
10       'status': 'Estat',
11       'date': 'Data',
12       'copyright': 'Copyright',
13       'dedication': 'Dedicatòria',
14       'abstract': 'Resum',
15       'attention': 'Atenció!',
16       'caution': 'Compte!',
17       'danger': 'PERILL!',
18       'error': 'Error',
19       'hint': 'Suggeriment',
20       'important': 'Important',
21       'note': 'Nota',
22       'tip': 'Consell',
23       'warning': 'Avís',
24       'contents': 'Contingut'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
