.TH "docutils.readers.pep" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.readers.pep
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Python Enhancement Proposal (PEP) Reader\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
