.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/util/docutils.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/util/docutils.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&._LanguageModule\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&._DirectivesDispatcher\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&._RolesDispatcher\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.CustomReSTDispatcher\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.ElementLookupError\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.sphinx_domains\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.WarningStream\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.LoggingReporter\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.NullReporter\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.SphinxFileOutput\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.SphinxDirective\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.SphinxRole\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.ReferenceRole\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.util\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.util\&.docutils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Iterator[None] \fBsphinx\&.util\&.docutils\&.docutils_namespace\fP ()"
.br
.ti -1c
.RI "bool \fBsphinx\&.util\&.docutils\&.is_directive_registered\fP (str name)"
.br
.ti -1c
.RI "None \fBsphinx\&.util\&.docutils\&.register_directive\fP (str name, type[\fBDirective\fP] directive)"
.br
.ti -1c
.RI "bool \fBsphinx\&.util\&.docutils\&.is_role_registered\fP (str name)"
.br
.ti -1c
.RI "None \fBsphinx\&.util\&.docutils\&.register_role\fP (str name, \fBRoleFunction\fP role)"
.br
.ti -1c
.RI "None \fBsphinx\&.util\&.docutils\&.unregister_role\fP (str name)"
.br
.ti -1c
.RI "bool \fBsphinx\&.util\&.docutils\&.is_node_registered\fP (type[\fBElement\fP] node)"
.br
.ti -1c
.RI "None \fBsphinx\&.util\&.docutils\&.register_node\fP (type[\fBElement\fP] node)"
.br
.ti -1c
.RI "None \fBsphinx\&.util\&.docutils\&.unregister_node\fP (type[\fBElement\fP] node)"
.br
.ti -1c
.RI "Iterator[None] \fBsphinx\&.util\&.docutils\&.patched_get_language\fP ()"
.br
.ti -1c
.RI "Iterator[None] \fBsphinx\&.util\&.docutils\&.patched_rst_get_language\fP ()"
.br
.ti -1c
.RI "Iterator[None] \fBsphinx\&.util\&.docutils\&.using_user_docutils_conf\fP (str|os\&.PathLike[str]|None confdir)"
.br
.ti -1c
.RI "Iterator[None] \fBsphinx\&.util\&.docutils\&.patch_docutils\fP (str|os\&.PathLike[str]|None confdir=None)"
.br
.ti -1c
.RI "Iterator[None] \fBsphinx\&.util\&.docutils\&.switch_source_input\fP (\fBState\fP[list[str]] state, \fBStringList\fP content)"
.br
.ti -1c
.RI "nodes\&.document \fBsphinx\&.util\&.docutils\&.new_document\fP (str source_path, Any settings=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsphinx\&.util\&.docutils\&.logger\fP = \fBlogging\&.getLogger\fP(__name__)"
.br
.ti -1c
.RI "\fBsphinx\&.util\&.docutils\&.report_re\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
