.TH "docutils.languages.en" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.en
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
English-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.en\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.en\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # language\-dependent: fixed
3       'author': 'author',
4       'authors': 'authors',
5       'organization': 'organization',
6       'address': 'address',
7       'contact': 'contact',
8       'version': 'version',
9       'revision': 'revision',
10       'status': 'status',
11       'date': 'date',
12       'copyright': 'copyright',
13       'dedication': 'dedication',
14       'abstract': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.en\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # fixed: language\-dependent
3       'author': 'Author',
4       'authors': 'Authors',
5       'organization': 'Organization',
6       'address': 'Address',
7       'contact': 'Contact',
8       'version': 'Version',
9       'revision': 'Revision',
10       'status': 'Status',
11       'date': 'Date',
12       'copyright': 'Copyright',
13       'dedication': 'Dedication',
14       'abstract': 'Abstract',
15       'attention': 'Attention!',
16       'caution': 'Caution!',
17       'danger': '!DANGER!',
18       'error': 'Error',
19       'hint': 'Hint',
20       'important': 'Important',
21       'note': 'Note',
22       'tip': 'Tip',
23       'warning': 'Warning',
24       'contents': 'Contents'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
