.TH "docutils.writers.latex2e.Writer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.writers.latex2e.Writer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.writers\&.Writer\fP\&.
.PP
Inherited by \fBdocutils\&.writers\&.xetex\&.Writer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBget_transforms\fP (self)"
.br
.ti -1c
.RI "\fBtranslate\fP (self)"
.br
.ti -1c
.RI "\fBassemble_parts\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.writers\&.Writer\fP
.in +1c
.ti -1c
.RI "\fBwrite\fP (self, \fBdocument\fP, \fBdestination\fP)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.Component\fP
.in +1c
.ti -1c
.RI "\fBsupports\fP (self, format)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtranslator_class\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.writers\&.Writer\fP
.in +1c
.ti -1c
.RI "\fBparts\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "\fBdefault_transforms\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBsupported\fP = ('latex', 'latex2e')"
.br
.ti -1c
.RI "str \fBdefault_template\fP = 'default\&.tex'"
.br
.ti -1c
.RI "\fBdefault_template_path\fP = \fBLATEX_WRITER_DIR\fP"
.br
.ti -1c
.RI "tuple \fBdefault_preamble\fP"
.br
.ti -1c
.RI "list \fBtable_style_values\fP"
.br
.ti -1c
.RI "tuple \fBsettings_spec\fP"
.br
.ti -1c
.RI "tuple \fBrelative_path_settings\fP = ('template',)"
.br
.ti -1c
.RI "dict \fBsettings_defaults\fP = {'sectnum_depth': 0}"
.br
.ti -1c
.RI "str \fBconfig_section\fP = 'latex2e writer'"
.br
.ti -1c
.RI "tuple \fBconfig_section_dependencies\fP = ('writers', 'latex writers')"
.br
.ti -1c
.RI "tuple \fBhead_parts\fP"
.br
.ti -1c
.RI "tuple \fBvisitor_attributes\fP"
.br
.ti -1c
.RI "\fBoutput\fP = None"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.writers\&.Writer\fP
.in +1c
.ti -1c
.RI "str \fBcomponent_type\fP = 'writer'"
.br
.ti -1c
.RI "str \fBconfig_section\fP = 'writers'"
.br
.ti -1c
.RI "\fBdocument\fP = None"
.br
.ti -1c
.RI "\fBoutput\fP = None"
.br
.ti -1c
.RI "\fBlanguage\fP = None"
.br
.ti -1c
.RI "\fBdestination\fP = None"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.Component\fP
.in +1c
.ti -1c
.RI "\fBcomponent_type\fP = None"
.br
.ti -1c
.RI "tuple \fBsupported\fP = ()"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.SettingsSpec\fP
.in +1c
.ti -1c
.RI "tuple \fBsettings_spec\fP = ()"
.br
.ti -1c
.RI "\fBsettings_defaults\fP = None"
.br
.ti -1c
.RI "\fBsettings_default_overrides\fP = None"
.br
.ti -1c
.RI "tuple \fBrelative_path_settings\fP = ()"
.br
.ti -1c
.RI "\fBconfig_section\fP = None"
.br
.ti -1c
.RI "\fBconfig_section_dependencies\fP = None"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "tuple \fBdefault_transforms\fP = ()"
.br
.ti -1c
.RI "tuple \fBunknown_reference_resolvers\fP = ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.writers\&.latex2e\&.Writer\&.__init__ ( self)"

.PP
Reimplemented from \fBdocutils\&.writers\&.Writer\fP\&.
.PP
Reimplemented in \fBdocutils\&.writers\&.xetex\&.Writer\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.writers\&.latex2e\&.Writer\&.assemble_parts ( self)"

.PP
.nf
Assemble the `self\&.parts` dictionary of output fragments\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.writers\&.Writer\fP\&.
.SS "docutils\&.writers\&.latex2e\&.Writer\&.get_transforms ( self)"

.PP
.nf
Transforms required by this class\&.  Override in subclasses\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.writers\&.Writer\fP\&.
.SS "docutils\&.writers\&.latex2e\&.Writer\&.translate ( self)"

.PP
.nf
Do final translation of `self\&.document` into `self\&.output`\&.  Called
from `write`\&.  Override in subclasses\&.

Usually done with a `docutils\&.nodes\&.NodeVisitor` subclass, in
combination with a call to `docutils\&.nodes\&.Node\&.walk()` or
`docutils\&.nodes\&.Node\&.walkabout()`\&.  The ``NodeVisitor`` subclass must
support all standard elements (listed in
`docutils\&.nodes\&.node_class_names`) and possibly non-standard elements
used by the current Reader as well\&.

.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.writers\&.Writer\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str docutils\&.writers\&.latex2e\&.Writer\&.config_section = 'latex2e writer'\fC [static]\fP"

.SS "tuple docutils\&.writers\&.latex2e\&.Writer\&.config_section_dependencies = ('writers', 'latex writers')\fC [static]\fP"

.SS "tuple docutils\&.writers\&.latex2e\&.Writer\&.default_preamble\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  ('% PDF Standard Fonts\\n'
                        '\\\\usepackage{mathptmx} % Times\\n'
                        '\\\\usepackage[scaled=\&.90]{helvet}\\n'
                        '\\\\usepackage{courier}')
.fi

.SS "str docutils\&.writers\&.latex2e\&.Writer\&.default_template = 'default\&.tex'\fC [static]\fP"

.SS "docutils\&.writers\&.latex2e\&.Writer\&.default_template_path = \fBLATEX_WRITER_DIR\fP\fC [static]\fP"

.SS "tuple docutils\&.writers\&.latex2e\&.Writer\&.head_parts\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  ('head_prefix', 'requirements', 'latex_preamble',
                  'stylesheet', 'fallbacks', 'pdfsetup', 'titledata')
.fi

.SS "docutils\&.writers\&.latex2e\&.Writer\&.output = None\fC [static]\fP"

.SS "tuple docutils\&.writers\&.latex2e\&.Writer\&.relative_path_settings = ('template',)\fC [static]\fP"

.SS "dict docutils\&.writers\&.latex2e\&.Writer\&.settings_defaults = {'sectnum_depth': 0}\fC [static]\fP"

.SS "tuple docutils\&.writers\&.latex2e\&.Writer\&.settings_spec\fC [static]\fP"

.SS "tuple docutils\&.writers\&.latex2e\&.Writer\&.supported = ('latex', 'latex2e')\fC [static]\fP"

.SS "list docutils\&.writers\&.latex2e\&.Writer\&.table_style_values\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [  # TODO: align\-left, align\-center, align\-right, ??
                          'booktabs', 'borderless', 'colwidths\-auto',
                          'nolines', 'standard']
.fi

.SS "docutils\&.writers\&.latex2e\&.Writer\&.translator_class"

.SS "tuple docutils\&.writers\&.latex2e\&.Writer\&.visitor_attributes\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  head_parts + ('title', 'subtitle',
                                       'body_pre_docinfo', 'docinfo',
                                       'dedication', 'abstract', 'body')
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
