.TH "docutils.utils.math.mathml_elements.MathElement" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.utils.math.mathml_elements.MathElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits ET\&.Element\&.
.PP
Inherited by \fBdocutils\&.utils\&.math\&.mathml_elements\&.MathRow\fP, \fBdocutils\&.utils\&.math\&.mathml_elements\&.MathSchema\fP, \fBdocutils\&.utils\&.math\&.mathml_elements\&.MathToken\fP, \fBdocutils\&.utils\&.math\&.mathml_elements\&.mspace\fP, and \fBdocutils\&.utils\&.math\&.mathml_elements\&.mtable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, *children, **attributes)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.ti -1c
.RI "\fBset\fP (self, key, value)"
.br
.ti -1c
.RI "\fB__setitem__\fP (self, key, value)"
.br
.ti -1c
.RI "\fBis_full\fP (self)"
.br
.ti -1c
.RI "\fBclose\fP (self)"
.br
.ti -1c
.RI "\fBappend\fP (self, element)"
.br
.ti -1c
.RI "\fBextend\fP (self, elements)"
.br
.ti -1c
.RI "\fBpop\fP (self, index=\-1)"
.br
.ti -1c
.RI "\fBin_block\fP (self)"
.br
.ti -1c
.RI "\fBindent_xml\fP (self, space=' ', level=0)"
.br
.ti -1c
.RI "\fBunindent_xml\fP (self)"
.br
.ti -1c
.RI "\fBtoxml\fP (self, encoding=None)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBa_str\fP (v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtext\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBnchildren\fP = None"
.br
.ti -1c
.RI "\fBparent\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base class for MathML elements\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.__init__ ( self, * children, ** attributes)"

.PP
.nf
Set up node with `children` and `attributes`\&.

Attribute names are normalised to lowercase\&.
You may use 'CLASS' to set a 'class' attribute\&.
Attribute values are converted to strings
(with True -> 'true' and False -> 'false')\&.

>>> math(CLASS='test', level=3, split=True)
math(class='test', level='3', split='true')
>>> math(CLASS='test', level=3, split=True)\&.toxml()
'<math class='test' level='3' split='true'></math>'
.fi
.PP
 
.PP
Reimplemented in \fBdocutils\&.utils\&.math\&.mathml_elements\&.MathSchema\fP, and \fBdocutils\&.utils\&.math\&.mathml_elements\&.MathToken\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.__repr__ ( self)"

.PP
.nf
Return full string representation\&.
.fi
.PP
 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.__setitem__ ( self,  key,  value)"

.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.__str__ ( self)"

.PP
.nf
Return concise, informal string representation\&.
.fi
.PP
 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.a_str ( v)\fC [static]\fP"

.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.append ( self,  element)"

.PP
.nf
Append `element` and return new 'current node' (insertion point)\&.

Append as child element and set the internal `parent` attribute\&.

If self is already full, raise TypeError\&.

If self is full after appending, call `self\&.close()`
(returns first non-full anchestor or None) else return `self`\&.

.fi
.PP
 
.PP
Reimplemented in \fBdocutils\&.utils\&.math\&.mathml_elements\&.MathSchema\fP\&.
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.close ( self)"

.PP
.nf
Close element and return first non-full anchestor or None\&.
.fi
.PP
 
.PP
Reimplemented in \fBdocutils\&.utils\&.math\&.mathml_elements\&.mrow\fP\&.
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.extend ( self,  elements)"

.PP
.nf
Sequentially append `elements`\&. Return new 'current node'\&.

Raise TypeError if overfull\&.

.fi
.PP
 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.in_block ( self)"

.PP
.nf
Return True, if `self` or an ancestor has ``display='block'``\&.

Used to find out whether we are in inline vs\&. displayed maths\&.

.fi
.PP
 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.indent_xml ( self,  space = \fC'  '\fP,  level = \fC0\fP)"

.PP
.nf
Format XML output with indents\&.

Use with care:
  Formatting whitespace is permanently added to the
  `text` and `tail` attributes of `self` and anchestors!

.fi
.PP
 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.is_full ( self)"

.PP
.nf
Return boolean indicating whether children may be appended\&.
.fi
.PP
 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.pop ( self,  index = \fC\-1\fP)"

.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.set ( self,  key,  value)"

.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.toxml ( self,  encoding = \fCNone\fP)"

.PP
.nf
Return an XML representation of the element\&.

By default, the return value is a `str` instance\&. With an explicit
`encoding` argument, the result is a `bytes` instance in the
specified encoding\&. The XML default encoding is UTF-8, any other
encoding must be specified in an XML document header\&.

Name and encoding handling match `xml\&.dom\&.minidom\&.Node\&.toxml()`
while `etree\&.Element\&.tostring()` returns `bytes` by default\&.

.fi
.PP
 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.unindent_xml ( self)"

.PP
.nf
Strip whitespace at the end of `text` and `tail` attributes\&.\&.\&.

to revert changes made by the `indent_xml()` method\&.
Use with care, trailing whitespace from the original may be lost\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.nchildren = None\fC [static]\fP"

.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.parent = None\fC [static]\fP"

.SS "docutils\&.utils\&.math\&.mathml_elements\&.MathElement\&.text"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
