.TH "docutils.utils.math.math2html.EndingList" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.utils.math.math2html.EndingList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBadd\fP (self, ending, optional=False)"
.br
.ti -1c
.RI "\fBpickpending\fP (self, pos)"
.br
.ti -1c
.RI "\fBcheckin\fP (self, pos)"
.br
.ti -1c
.RI "\fBpop\fP (self, pos)"
.br
.ti -1c
.RI "\fBfindending\fP (self, pos)"
.br
.ti -1c
.RI "\fBcheckpending\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBendings\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.__str__ ( self)"

.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.add ( self,  ending,  optional = \fCFalse\fP)"

.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.checkin ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.checkpending ( self)"

.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.findending ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.pickpending ( self,  pos)"

.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.pop ( self,  pos)"

.SH "Member Data Documentation"
.PP 
.SS "docutils\&.utils\&.math\&.math2html\&.EndingList\&.endings"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
