.TH "docutils.nodes.Sequential" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.nodes.Sequential
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.nodes\&.Body\fP\&.
.PP
Inherited by \fBdocutils\&.nodes\&.bullet_list\fP, \fBdocutils\&.nodes\&.definition_list\fP, \fBdocutils\&.nodes\&.enumerated_list\fP, \fBdocutils\&.nodes\&.field_list\fP, and \fBdocutils\&.nodes\&.option_list\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
List-like elements\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
