.TH "docutils.nodes.SkipNode" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.nodes.SkipNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.nodes\&.TreePruningException\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Do not visit the current node's children, and do not call the current
node's ``depart_\&.\&.\&.`` method\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
