.TH "docutils.languages.pt_br" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.pt_br
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Brazilian Portuguese-language mappings for language-dependent features\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.pt_br\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.pt_br\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # language\-dependent: fixed
3       'autor': 'author',
4       'autores': 'authors',
5       'organização': 'organization',
6       'endereço': 'address',
7       'contato': 'contact',
8       'versão': 'version',
9       'revisão': 'revision',
10       'estado': 'status',
11       'data': 'date',
12       'copyright': 'copyright',
13       'dedicatória': 'dedication',
14       'resumo': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.pt_br\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # fixed: language\-dependent
3       'author': 'Autor',
4       'authors': 'Autores',
5       'organization': 'Organização',
6       'address': 'Endereço',
7       'contact': 'Contato',
8       'version': 'Versão',
9       'revision': 'Revisão',
10       'status': 'Estado',
11       'date': 'Data',
12       'copyright': 'Copyright',
13       'dedication': 'Dedicatória',
14       'abstract': 'Resumo',
15       'attention': 'Atenção!',
16       'caution': 'Cuidado!',
17       'danger': 'PERIGO!',
18       'error': 'Erro',
19       'hint': 'Sugestão',
20       'important': 'Importante',
21       'note': 'Nota',
22       'tip': 'Dica',
23       'warning': 'Aviso',
24       'contents': 'Sumário'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
