.TH "docutils.parsers.rst.directives.images" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.directives.images
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFigure\fP"
.br
.ti -1c
.RI "class \fBImage\fP"
.br
.ti -1c
.RI "class \fBPIL\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBImage\fP"
.br
.ti -1c
.RI "\fBPIL\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Directives for figures and simple images\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "\fBdocutils\&.parsers\&.rst\&.directives\&.images\&.Image\fP"

.SS "\fBdocutils\&.parsers\&.rst\&.directives\&.images\&.PIL\fP = None"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
