.TH "docutils.languages.it" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.it
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Italian-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.it\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.it\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       'autore': 'author',
3       'autori': 'authors',
4       'organizzazione': 'organization',
5       'indirizzo': 'address',
6       'contatto': 'contact',
7       'versione': 'version',
8       'revisione': 'revision',
9       'status': 'status',
10       'data': 'date',
11       'copyright': 'copyright',
12       'dedica': 'dedication',
13       'riassunto': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.it\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       'author': 'Autore',
3       'authors': 'Autori',
4       'organization': 'Organizzazione',
5       'address': 'Indirizzo',
6       'contact': 'Contatti',
7       'version': 'Versione',
8       'revision': 'Revisione',
9       'status': 'Status',
10       'date': 'Data',
11       'copyright': 'Copyright',
12       'dedication': 'Dedica',
13       'abstract': 'Riassunto',
14       'attention': 'Attenzione!',
15       'caution': 'Cautela!',
16       'danger': '!PERICOLO!',
17       'error': 'Errore',
18       'hint': 'Suggerimento',
19       'important': 'Importante',
20       'note': 'Nota',
21       'tip': 'Consiglio',
22       'warning': 'Avvertenza',
23       'contents': 'Indice'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
