.TH "docutils.writers.xetex.Babel" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.writers.xetex.Babel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.writers\&.latex2e\&.Babel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBlanguage_code\fP, \fBreporter\fP)"
.br
.ti -1c
.RI "\fB__call__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage_code\fP"
.br
.ti -1c
.RI "\fBreporter\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBotherlanguages\fP"
.br
.ti -1c
.RI "\fBwarn_msg\fP"
.br
.ti -1c
.RI "\fBquote_index\fP"
.br
.ti -1c
.RI "\fBquotes\fP"
.br
.ti -1c
.RI "\fBliteral_double_quote\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage_codes\fP = latex2e\&.Babel\&.language_codes\&.copy()"
.br
.ti -1c
.RI "dict \fBlanguage_codes\fP = {k\&.lower(): v for k, v in language_codes\&.items()}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Language specifics for XeTeX\&.

Use `polyglossia` instead of `babel` and adapt settings\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.writers\&.xetex\&.Babel\&.__init__ ( self,  language_code,  reporter)"

.SH "Member Function Documentation"
.PP 
.SS "docutils\&.writers\&.xetex\&.Babel\&.__call__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "docutils\&.writers\&.xetex\&.Babel\&.language"

.SS "docutils\&.writers\&.xetex\&.Babel\&.language_code"

.SS "docutils\&.writers\&.xetex\&.Babel\&.language_codes = latex2e\&.Babel\&.language_codes\&.copy()\fC [static]\fP"

.SS "dict docutils\&.writers\&.xetex\&.Babel\&.language_codes = {k\&.lower(): v for k, v in language_codes\&.items()}\fC [static]\fP"

.SS "docutils\&.writers\&.xetex\&.Babel\&.literal_double_quote"

.SS "docutils\&.writers\&.xetex\&.Babel\&.otherlanguages"

.SS "docutils\&.writers\&.xetex\&.Babel\&.quote_index"

.SS "docutils\&.writers\&.xetex\&.Babel\&.quotes"

.SS "docutils\&.writers\&.xetex\&.Babel\&.reporter"

.SS "docutils\&.writers\&.xetex\&.Babel\&.warn_msg"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
