.TH "docutils.transforms.frontmatter.DocInfo" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.transforms.frontmatter.DocInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.transforms\&.Transform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBapply\fP (self)"
.br
.ti -1c
.RI "\fBextract_bibliographic\fP (self, field_list)"
.br
.ti -1c
.RI "\fBcheck_empty_biblio_field\fP (self, field, name)"
.br
.ti -1c
.RI "\fBcheck_compound_biblio_field\fP (self, field, name)"
.br
.ti -1c
.RI "\fBextract_authors\fP (self, field, name, docinfo)"
.br
.ti -1c
.RI "\fBauthors_from_one_paragraph\fP (self, field)"
.br
.ti -1c
.RI "\fBauthors_from_bullet_list\fP (self, field)"
.br
.ti -1c
.RI "\fBauthors_from_paragraphs\fP (self, field)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBdocument\fP, \fBstartnode\fP=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrcs_keyword_substitutions\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBstartnode\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdefault_priority\fP = 340"
.br
.ti -1c
.RI "dict \fBbiblio_nodes\fP"
.br
.ti -1c
.RI "list \fBrcs_keyword_substitutions\fP"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdefault_priority\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This transform is specific to the reStructuredText_ markup syntax;
see 'Bibliographic Fields' in the `reStructuredText Markup
Specification`_ for a high-level description\&. This transform
should be run *after* the `DocTitle` transform\&.

If the document contains a field list as the first element (instances
of `nodes\&.PreBibliographic` are ignored), registered bibliographic
field names are transformed to the corresponding DTD elements,
becoming child elements of the <docinfo> element (except for a
dedication and/or an abstract, which become <topic> elements after
<docinfo>)\&.

For example, given this document fragment after parsing::

    <document>
        <title>
            Document Title
        <field_list>
            <field>
                <field_name>
                    Author
                <field_body>
                    <paragraph>
                        A\&. Name
            <field>
                <field_name>
                    Status
                <field_body>
                    <paragraph>
                        $RCSfile$
        \&.\&.\&.

After running the bibliographic field list transform, the
resulting document tree would look like this::

    <document>
        <title>
            Document Title
        <docinfo>
            <author>
                A\&. Name
            <status>
                frontmatter\&.py
        \&.\&.\&.

The 'Status' field contained an expanded RCS keyword, which is
normally (but optionally) cleaned up by the transform\&. The sole
contents of the field body must be a paragraph containing an
expanded RCS keyword of the form '$keyword: expansion text $'\&. Any
RCS keyword can be processed in any bibliographic field\&. The
dollar signs and leading RCS keyword name are removed\&. Extra
processing is done for the following RCS keywords:

- 'RCSfile' expands to the name of the file in the RCS or CVS
  repository, which is the name of the source file with a ',v'
  suffix appended\&. The transform will remove the ',v' suffix\&.

- 'Date' expands to the format 'YYYY/MM/DD hh:mm:ss' (in the UTC
  time zone)\&. The RCS Keywords transform will extract just the
  date itself and transform it to an ISO 8601 format date, as in
  '2000-12-31'\&.

  (Since the source file for this text is itself stored under CVS,
  we can't show an example of the 'Date' RCS keyword because we
  can't prevent any RCS keywords used in this explanation from
  being expanded\&. Only the 'RCSfile' keyword is stable; its
  expansion text changes only if the file name changes\&.)

\&.\&. _reStructuredText: https://docutils\&.sourceforge\&.io/rst\&.html
\&.\&. _reStructuredText Markup Specification:
   https://docutils\&.sourceforge\&.io/docs/ref/rst/restructuredtext\&.html

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.apply ( self)"

.PP
.nf
Override to apply the transform to the document tree\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.transforms\&.Transform\fP\&.
.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.authors_from_bullet_list ( self,  field)"

.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.authors_from_one_paragraph ( self,  field)"

.PP
.nf
Return list of Text nodes with author names in `field`\&.

Author names must be separated by one of the 'autor separators'
defined for the document language (default: ';' or ',')\&.

.fi
.PP
 
.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.authors_from_paragraphs ( self,  field)"

.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.check_compound_biblio_field ( self,  field,  name)"

.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.check_empty_biblio_field ( self,  field,  name)"

.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.extract_authors ( self,  field,  name,  docinfo)"

.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.extract_bibliographic ( self,  field_list)"

.SH "Member Data Documentation"
.PP 
.SS "dict docutils\&.transforms\&.frontmatter\&.DocInfo\&.biblio_nodes\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  {
          'author': nodes\&.author,
          'authors': nodes\&.authors,
          'organization': nodes\&.organization,
          'address': nodes\&.address,
          'contact': nodes\&.contact,
          'version': nodes\&.version,
          'revision': nodes\&.revision,
          'status': nodes\&.status,
          'date': nodes\&.date,
          'copyright': nodes\&.copyright,
          'dedication': nodes\&.topic,
          'abstract': nodes\&.topic}
.fi

.SS "int docutils\&.transforms\&.frontmatter\&.DocInfo\&.default_priority = 340\fC [static]\fP"

.SS "docutils\&.transforms\&.frontmatter\&.DocInfo\&.rcs_keyword_substitutions"

.SS "list docutils\&.transforms\&.frontmatter\&.DocInfo\&.rcs_keyword_substitutions\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
          (re\&.compile(r'\\$' r'Date: (\\d\\d\\d\\d)[\-/](\\d\\d)[\-/](\\d\\d)[ T][\\d:]+'
                      r'[^$]* \\$', re\&.IGNORECASE), r'\\1\-\\2\-\\3'),
          (re\&.compile(r'\\$' r'RCSfile: (\&.+),v \\$', re\&.IGNORECASE), r'\\1'),
          (re\&.compile(r'\\$[a\-zA\-Z]+: (\&.+) \\$'), r'\\1')]
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
