.TH "docutils.writers.docutils_xml.XMLTranslator" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.writers.docutils_xml.XMLTranslator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.nodes\&.GenericNodeVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBdocument\fP)"
.br
.ti -1c
.RI "\fBdefault_visit\fP (self, node)"
.br
.ti -1c
.RI "\fBdefault_departure\fP (self, node)"
.br
.ti -1c
.RI "\fBvisit_Text\fP (self, node)"
.br
.ti -1c
.RI "\fBdepart_Text\fP (self, node)"
.br
.ti -1c
.RI "\fBvisit_raw\fP (self, node)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.nodes\&.NodeVisitor\fP
.in +1c
.ti -1c
.RI "\fBdispatch_visit\fP (self, node)"
.br
.ti -1c
.RI "\fBdispatch_departure\fP (self, node)"
.br
.ti -1c
.RI "\fBunknown_visit\fP (self, node)"
.br
.ti -1c
.RI "\fBunknown_departure\fP (self, node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwarn\fP"
.br
.ti -1c
.RI "\fBerror\fP"
.br
.ti -1c
.RI "\fBsettings\fP"
.br
.ti -1c
.RI "\fBindent\fP"
.br
.ti -1c
.RI "\fBnewline\fP"
.br
.ti -1c
.RI "\fBlevel\fP"
.br
.ti -1c
.RI "\fBin_simple\fP"
.br
.ti -1c
.RI "\fBfixed_text\fP"
.br
.ti -1c
.RI "\fBoutput\fP"
.br
.ti -1c
.RI "\fBdoctype\fP"
.br
.ti -1c
.RI "\fBthe_handle\fP"
.br
.ti -1c
.RI "\fBsimple_nodes\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.nodes\&.NodeVisitor\fP
.in +1c
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBoptional\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBdoctype\fP"
.br
.ti -1c
.RI "str \fBgenerator\fP = '<!\-\- Generated by Docutils %s \-\->\\n'"
.br
.ti -1c
.RI "\fBxmlparser\fP = xml\&.sax\&.make_parser()"
.br
.ti -1c
.RI "tuple \fBsimple_nodes\fP"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.nodes\&.NodeVisitor\fP
.in +1c
.ti -1c
.RI "tuple \fBoptional\fP = ('\fBmeta\fP',)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.__init__ ( self,  document)"

.PP
Reimplemented from \fBdocutils\&.nodes\&.NodeVisitor\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.default_departure ( self,  node)"

.PP
.nf
Default node depart method\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.nodes\&.GenericNodeVisitor\fP\&.
.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.default_visit ( self,  node)"

.PP
.nf
Default node visit method\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.nodes\&.GenericNodeVisitor\fP\&.
.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.depart_Text ( self,  node)"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.visit_raw ( self,  node)"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.visit_Text ( self,  node)"

.SH "Member Data Documentation"
.PP 
.SS "tuple docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.doctype\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        '<!DOCTYPE document PUBLIC'
        ' "+//IDN docutils\&.sourceforge\&.net//DTD Docutils Generic//EN//XML"'
        ' "http://docutils\&.sourceforge\&.net/docs/ref/docutils\&.dtd">\\n')
.fi

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.doctype"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.error"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.fixed_text"

.SS "str docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.generator = '<!\-\- Generated by Docutils %s \-\->\\n'\fC [static]\fP"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.in_simple"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.indent"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.level"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.newline"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.output"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.settings"

.SS "tuple docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.simple_nodes\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (nodes\&.TextElement, nodes\&.meta,
                    nodes\&.image, nodes\&.colspec, nodes\&.transition)
.fi

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.simple_nodes"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.the_handle"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.warn"

.SS "docutils\&.writers\&.docutils_xml\&.XMLTranslator\&.xmlparser = xml\&.sax\&.make_parser()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
