.TH "docutils.nodes.Labeled" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.nodes.Labeled
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdocutils\&.nodes\&.citation\fP, and \fBdocutils\&.nodes\&.footnote\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Contains a `label` as its first element\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
