.TH "docutils.parsers.rst.states.Text" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.states.Text
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.parsers\&.rst\&.states\&.RSTState\fP\&.
.PP
Inherited by \fBbreathe\&.renderer\&.sphinxrenderer\&.InlineText\fP, and \fBdocutils\&.parsers\&.rst\&.states\&.SpecializedText\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBblank\fP (self, match, context, next_state)"
.br
.ti -1c
.RI "\fBeof\fP (self, context)"
.br
.ti -1c
.RI "\fBindent\fP (self, match, context, next_state)"
.br
.ti -1c
.RI "\fBunderline\fP (self, match, context, next_state)"
.br
.ti -1c
.RI "\fBtext\fP (self, match, context, next_state)"
.br
.ti -1c
.RI "\fBliteral_block\fP (self)"
.br
.ti -1c
.RI "\fBquoted_literal_block\fP (self)"
.br
.ti -1c
.RI "\fBdefinition_list_item\fP (self, termline)"
.br
.ti -1c
.RI "\fBterm\fP (self, lines, \fBlineno\fP)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.parsers\&.rst\&.states\&.RSTState\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBstate_machine\fP, \fBdebug\fP=False)"
.br
.ti -1c
.RI "\fBruntime_init\fP (self)"
.br
.ti -1c
.RI "\fBgoto_line\fP (self, abs_line_offset)"
.br
.ti -1c
.RI "\fBno_match\fP (self, context, \fBtransitions\fP)"
.br
.ti -1c
.RI "\fBbof\fP (self, context)"
.br
.ti -1c
.RI "\fBnested_parse\fP (self, block, input_offset, node, match_titles=False, state_machine_class=None, state_machine_kwargs=None)"
.br
.ti -1c
.RI "\fBnested_list_parse\fP (self, block, input_offset, node, initial_state, blank_finish, blank_finish_state=None, extra_settings={}, match_titles=False, state_machine_class=None, state_machine_kwargs=None)"
.br
.ti -1c
.RI "\fBsection\fP (self, title, source, style, \fBlineno\fP, messages)"
.br
.ti -1c
.RI "\fBcheck_subsection\fP (self, source, style, \fBlineno\fP)"
.br
.ti -1c
.RI "\fBtitle_inconsistent\fP (self, sourcetext, \fBlineno\fP)"
.br
.ti -1c
.RI "\fBnew_subsection\fP (self, title, \fBlineno\fP, messages)"
.br
.ti -1c
.RI "\fBparagraph\fP (self, lines, \fBlineno\fP)"
.br
.ti -1c
.RI "\fBinline_text\fP (self, text, \fBlineno\fP)"
.br
.ti -1c
.RI "\fBunindent_warning\fP (self, node_name)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.statemachine\&.StateWS\fP
.in +1c
.ti -1c
.RI "\fBadd_initial_transitions\fP (self)"
.br
.ti -1c
.RI "\fBknown_indent\fP (self, match, context, next_state)"
.br
.ti -1c
.RI "\fBfirst_known_indent\fP (self, match, context, next_state)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.statemachine\&.State\fP
.in +1c
.ti -1c
.RI "\fBunlink\fP (self)"
.br
.ti -1c
.RI "\fBadd_transitions\fP (self, names, \fBtransitions\fP)"
.br
.ti -1c
.RI "\fBadd_transition\fP (self, name, transition)"
.br
.ti -1c
.RI "\fBremove_transition\fP (self, name)"
.br
.ti -1c
.RI "\fBmake_transition\fP (self, name, next_state=None)"
.br
.ti -1c
.RI "\fBmake_transitions\fP (self, name_list)"
.br
.ti -1c
.RI "\fBnop\fP (self, match, context, next_state)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dict \fBpatterns\fP"
.br
.ti -1c
.RI "list \fBinitial_transitions\fP = [('\fBunderline\fP', '\fBBody\fP'), ('\fBtext\fP', '\fBBody\fP')]"
.br
.ti -1c
.RI "\fBclassifier_delimiter\fP = re\&.compile(' +: +')"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.parsers\&.rst\&.states\&.RSTState\fP
.in +1c
.ti -1c
.RI "\fBnested_sm\fP = \fBNestedStateMachine\fP"
.br
.ti -1c
.RI "list \fBnested_sm_cache\fP = []"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.statemachine\&.StateWS\fP
.in +1c
.ti -1c
.RI "\fBindent_sm\fP = None"
.br
.ti -1c
.RI "\fBindent_sm_kwargs\fP = None"
.br
.ti -1c
.RI "\fBknown_indent_sm\fP = None"
.br
.ti -1c
.RI "\fBknown_indent_sm_kwargs\fP = None"
.br
.ti -1c
.RI "dict \fBws_patterns\fP"
.br
.ti -1c
.RI "tuple \fBws_initial_transitions\fP = ('\fBblank\fP', '\fBindent\fP')"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.statemachine\&.State\fP
.in +1c
.ti -1c
.RI "\fBpatterns\fP = None"
.br
.ti -1c
.RI "\fBinitial_transitions\fP = None"
.br
.ti -1c
.RI "\fBnested_sm\fP = None"
.br
.ti -1c
.RI "\fBnested_sm_kwargs\fP = None"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBdocutils\&.parsers\&.rst\&.states\&.RSTState\fP
.in +1c
.ti -1c
.RI "\fBnested_sm_kwargs\fP"
.br
.ti -1c
.RI "\fBmemo\fP"
.br
.ti -1c
.RI "\fBreporter\fP"
.br
.ti -1c
.RI "\fBinliner\fP"
.br
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.statemachine\&.StateWS\fP
.in +1c
.ti -1c
.RI "\fBpatterns\fP"
.br
.ti -1c
.RI "\fBws_patterns\fP"
.br
.ti -1c
.RI "\fBws_initial_transitions\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.statemachine\&.State\fP
.in +1c
.ti -1c
.RI "\fBtransition_order\fP"
.br
.ti -1c
.RI "\fBtransitions\fP"
.br
.ti -1c
.RI "\fBstate_machine\fP"
.br
.ti -1c
.RI "\fBdebug\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Classifier of second line of a text block\&.

Could be a paragraph, a definition list item, or a title\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.blank ( self,  match,  context,  next_state)"

.PP
.nf
End of paragraph\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.statemachine\&.StateWS\fP\&.
.PP
Reimplemented in \fBdocutils\&.parsers\&.rst\&.states\&.Line\fP\&.
.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.definition_list_item ( self,  termline)"

.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.eof ( self,  context)"

.PP
.nf
Handle end-of-file\&. Return empty result\&.

Override in subclasses\&.

Parameter `context`: application-defined storage\&.

.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.statemachine\&.State\fP\&.
.PP
Reimplemented in \fBbreathe\&.renderer\&.sphinxrenderer\&.InlineText\fP, \fBdocutils\&.parsers\&.rst\&.states\&.SpecializedText\fP, \fBdocutils\&.parsers\&.rst\&.states\&.Definition\fP, and \fBdocutils\&.parsers\&.rst\&.states\&.Line\fP\&.
.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.indent ( self,  match,  context,  next_state)"

.PP
.nf
Definition list item\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.statemachine\&.StateWS\fP\&.
.PP
Reimplemented in \fBbreathe\&.renderer\&.sphinxrenderer\&.InlineText\fP, and \fBdocutils\&.parsers\&.rst\&.states\&.Definition\fP\&.
.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.literal_block ( self)"

.PP
.nf
Return a list of nodes\&.
.fi
.PP
 
.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.quoted_literal_block ( self)"

.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.term ( self,  lines,  lineno)"

.PP
.nf
Return a definition_list's term and optional classifiers\&.
.fi
.PP
 
.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.text ( self,  match,  context,  next_state)"

.PP
.nf
Paragraph\&.
.fi
.PP
 
.PP
Reimplemented in \fBdocutils\&.parsers\&.rst\&.states\&.Line\fP\&.
.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.underline ( self,  match,  context,  next_state)"

.PP
.nf
Section title\&.
.fi
.PP
 
.PP
Reimplemented in \fBdocutils\&.parsers\&.rst\&.states\&.Line\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.states\&.Text\&.classifier_delimiter = re\&.compile(' +: +')\fC [static]\fP"

.SS "list docutils\&.parsers\&.rst\&.states\&.Text\&.initial_transitions = [('\fBunderline\fP', '\fBBody\fP'), ('\fBtext\fP', '\fBBody\fP')]\fC [static]\fP"

.SS "dict docutils\&.parsers\&.rst\&.states\&.Text\&.patterns\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  {'underline': Body\&.patterns['line'],
                'text': r''}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
