.TH "docutils.languages.zh_cn" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.zh_cn
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',', '；', '，', '、']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Simplified Chinese language mappings for language-dependent features
of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.zh_cn\&.author_separators = [';', ',', '；', '，', '、']"

.SS "dict docutils\&.languages\&.zh_cn\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # language\-dependent: fixed
3       '作者': 'author',
4       '作者群': 'authors',
5       '组织': 'organization',
6       '地址': 'address',
7       '联系': 'contact',
8       '版本': 'version',
9       '修订': 'revision',
10       '状态': 'status',
11       '时间': 'date',
12       '版权': 'copyright',
13       '献辞': 'dedication',
14       '摘要': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.zh_cn\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # fixed: language\-dependent
3       'author': '作者',
4       'authors': '作者群',
5       'organization': '组织',
6       'address': '地址',
7       'contact': '联系',
8       'version': '版本',
9       'revision': '修订',
10       'status': '状态',
11       'date': '日期',
12       'copyright': '版权',
13       'dedication': '献辞',
14       'abstract': '摘要',
15       'attention': '注意',
16       'caution': '小心',
17       'danger': '危险',
18       'error': '错误',
19       'hint': '提示',
20       'important': '重要',
21       'note': '注解',
22       'tip': '技巧',
23       'warning': '警告',
24       'contents': '目录',
25 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
