.TH "docutils.DataError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.DataError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.ApplicationError\fP\&.
.PP
Inherited by \fBdocutils\&.parsers\&.rst\&.states\&.InterpretedRoleNotImplementedError\fP, \fBdocutils\&.parsers\&.rst\&.states\&.MarkupError\fP, \fBdocutils\&.parsers\&.rst\&.states\&.UnknownInterpretedRoleError\fP, \fBdocutils\&.parsers\&.rst\&.tableparser\&.TableMarkupError\fP, \fBdocutils\&.utils\&.ExtensionOptionError\fP, and \fBdocutils\&.utils\&.NameValueError\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
