.TH "docutils.languages.ka" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.ka
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Georgian-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.ka\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.ka\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       'ანოტაცია': 'abstract',
3       'მისამართი': 'address',
4       'ავტორი': 'author',
5       'ავტორები': 'authors',
6       'კონტაქტი': 'contact',
7       'საავტორო უფლებები': 'copyright',
8       'თარიღი': 'date',
9       'მიძღვნა': 'dedication',
10       'ორგანიზაცია': 'organization',
11       'რევიზია': 'revision',
12       'სტატუსი': 'status',
13       'ვერსია': 'version'}
.fi

.SS "dict docutils\&.languages\&.ka\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       'abstract': 'ანოტაცია',
3       'address': 'მისამართი',
4       'attention': 'ყურადღება!',
5       'author': 'ავტორი',
6       'authors': 'ავტორები',
7       'caution': 'ფრთხილად!',
8       'contact': 'კონტაქტი',
9       'contents': 'შემცველობა',
10       'copyright': 'საავტორო უფლებები',
11       'danger': 'საშიშია!',
12       'date': 'თარიღი',
13       'dedication': 'მიძღვნა',
14       'error': 'შეცდომა',
15       'hint': 'რჩევა',
16       'important': 'მნიშვნელოვანია',
17       'note': 'შენიშვნა',
18       'organization': 'ორგანიზაცია',
19       'revision': 'რევიზია',
20       'status': 'სტატუსი',
21       'tip': 'მინიშნება',
22       'version': 'ვერსია',
23       'warning': 'გაფრთხილება'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
