.TH "docutils.writers.latex2e.Babel" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.writers.latex2e.Babel
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdocutils\&.writers\&.xetex\&.Babel\fP, and \fBsphinx\&.builders\&.latex\&.util\&.ExtBabel\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Language specifics for LaTeX\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
