.TH "docutils.writers.manpage" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.writers.manpage
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTable\fP"
.br
.ti -1c
.RI "class \fBTranslator\fP"
.br
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBFIELD_LIST_INDENT\fP = 7"
.br
.ti -1c
.RI "int \fBDEFINITION_LIST_INDENT\fP = 7"
.br
.ti -1c
.RI "int \fBOPTION_LIST_INDENT\fP = 7"
.br
.ti -1c
.RI "float \fBBLOCKQOUTE_INDENT\fP = 3\&.5"
.br
.ti -1c
.RI "float \fBLITERAL_BLOCK_INDENT\fP = 3\&.5"
.br
.ti -1c
.RI "tuple \fBMACRO_DEF\fP = ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Simple man page writer for reStructuredText\&.

Man pages (short for 'manual pages') contain system documentation on unix-like
systems\&. The pages are grouped in numbered sections:

 1 executable programs and shell commands
 2 system calls
 3 library functions
 4 special files
 5 file formats
 6 games
 7 miscellaneous
 8 system administration

Man pages are written *troff*, a text file formatting system\&.

See https://www\&.tldp\&.org/HOWTO/Man-Page for a start\&.

Man pages have no subsection only parts\&.
Standard parts

  NAME ,
  SYNOPSIS ,
  DESCRIPTION ,
  OPTIONS ,
  FILES ,
  SEE ALSO ,
  BUGS ,

and

  AUTHOR \&.

A unix-like system keeps an index of the DESCRIPTIONs, which is accessible
by the command whatis or apropos\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "float docutils\&.writers\&.manpage\&.BLOCKQOUTE_INDENT = 3\&.5"

.SS "int docutils\&.writers\&.manpage\&.DEFINITION_LIST_INDENT = 7"

.SS "int docutils\&.writers\&.manpage\&.FIELD_LIST_INDENT = 7"

.SS "float docutils\&.writers\&.manpage\&.LITERAL_BLOCK_INDENT = 3\&.5"

.SS "tuple docutils\&.writers\&.manpage\&.MACRO_DEF = ()"

.SS "int docutils\&.writers\&.manpage\&.OPTION_LIST_INDENT = 7"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
