.TH "docutils.parsers.recommonmark_wrapper" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.recommonmark_wrapper
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParser\fP"
.br
.ti -1c
.RI "class \fBpending_xref\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBis_literal\fP (node)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsphinx\fP"
.br
.ti -1c
.RI "\fBaddnodes\fP"
.br
.ti -1c
.RI "\fBpending_xref\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A parser for CommonMark Markdown text using `recommonmark`__\&.

__ https://pypi\&.org/project/recommonmark/

\&.\&. important:: This module is provisional

   * The 'recommonmark' package is unmaintained and deprecated\&.
     This wrapper module will be removed in a future Docutils version\&.

   * The API is not settled and may change with any minor Docutils version\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "docutils\&.parsers\&.recommonmark_wrapper\&.is_literal ( node)"

.SH "Variable Documentation"
.PP 
.SS "docutils\&.parsers\&.recommonmark_wrapper\&.addnodes"

.SS "\fBdocutils\&.parsers\&.recommonmark_wrapper\&.pending_xref\fP"

.SS "docutils\&.parsers\&.recommonmark_wrapper\&.sphinx"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
