.TH "docutils.languages.pl" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.languages.pl
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBlabels\fP"
.br
.ti -1c
.RI "dict \fBbibliographic_fields\fP"
.br
.ti -1c
.RI "list \fBauthor_separators\fP = [';', ',']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Polish-language mappings for language-dependent features of Docutils\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list docutils\&.languages\&.pl\&.author_separators = [';', ',']"

.SS "dict docutils\&.languages\&.pl\&.bibliographic_fields"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # language\-dependent: fixed
3       'autor': 'author',
4       'autorzy': 'authors',
5       'organizacja': 'organization',
6       'adres': 'address',
7       'kontakt': 'contact',
8       'wersja': 'version',
9       'korekta': 'revision',
10       'status': 'status',
11       'data': 'date',
12       'copyright': 'copyright',
13       'dedykacja': 'dedication',
14       'streszczenie': 'abstract'}
.fi

.SS "dict docutils\&.languages\&.pl\&.labels"
\fBInitial value:\fP.PP
.nf
1 =  {
2       # fixed: language\-dependent
3       'author': 'Autor',
4       'authors': 'Autorzy',
5       'organization': 'Organizacja',
6       'address': 'Adres',
7       'contact': 'Kontakt',
8       'version': 'Wersja',
9       'revision': 'Korekta',
10       'status': 'Status',
11       'date': 'Data',
12       'copyright': 'Copyright',
13       'dedication': 'Dedykacja',
14       'abstract': 'Streszczenie',
15       'attention': 'Uwaga!',
16       'caution': 'Ostrożnie!',
17       'danger': '!Niebezpieczeństwo!',
18       'error': 'Błąd',
19       'hint': 'Wskazówka',
20       'important': 'Ważne',
21       'note': 'Przypis',
22       'tip': 'Rada',
23       'warning': 'Ostrzeżenie',
24       'contents': 'Treść'}
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
