.TH "docutils.statemachine.StateMachineError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.statemachine.StateMachineError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBdocutils\&.statemachine\&.DuplicateStateError\fP, \fBdocutils\&.statemachine\&.DuplicateTransitionError\fP, \fBdocutils\&.statemachine\&.TransitionMethodNotFound\fP, \fBdocutils\&.statemachine\&.TransitionPatternNotFound\fP, \fBdocutils\&.statemachine\&.UnexpectedIndentationError\fP, \fBdocutils\&.statemachine\&.UnknownStateError\fP, and \fBdocutils\&.statemachine\&.UnknownTransitionError\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
