.TH "docutils.transforms.references.TargetNotes" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.transforms.references.TargetNotes
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.transforms\&.Transform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBdocument\fP, \fBstartnode\fP)"
.br
.ti -1c
.RI "\fBapply\fP (self)"
.br
.ti -1c
.RI "\fBmake_target_footnote\fP (self, refuri, refs, notes)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBclasses\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBstartnode\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdefault_priority\fP = 540"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdefault_priority\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Creates a footnote for each external target in the text, and corresponding
footnote references after each reference\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "docutils\&.transforms\&.references\&.TargetNotes\&.__init__ ( self,  document,  startnode)"

.PP
.nf
Initial setup for in-place document transforms\&.

.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.transforms\&.Transform\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "docutils\&.transforms\&.references\&.TargetNotes\&.apply ( self)"

.PP
.nf
Override to apply the transform to the document tree\&.
.fi
.PP
 
.PP
Reimplemented from \fBdocutils\&.transforms\&.Transform\fP\&.
.SS "docutils\&.transforms\&.references\&.TargetNotes\&.make_target_footnote ( self,  refuri,  refs,  notes)"

.SH "Member Data Documentation"
.PP 
.SS "docutils\&.transforms\&.references\&.TargetNotes\&.classes"

.SS "int docutils\&.transforms\&.references\&.TargetNotes\&.default_priority = 540\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
