.TH "docutils.parsers.rst.states" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.parsers.rst.states
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBody\fP"
.br
.ti -1c
.RI "class \fBBulletList\fP"
.br
.ti -1c
.RI "class \fBDefinition\fP"
.br
.ti -1c
.RI "class \fBDefinitionList\fP"
.br
.ti -1c
.RI "class \fBEnumeratedList\fP"
.br
.ti -1c
.RI "class \fBExplicit\fP"
.br
.ti -1c
.RI "class \fBExtensionOptions\fP"
.br
.ti -1c
.RI "class \fBFieldList\fP"
.br
.ti -1c
.RI "class \fBInliner\fP"
.br
.ti -1c
.RI "class \fBInterpretedRoleNotImplementedError\fP"
.br
.ti -1c
.RI "class \fBLine\fP"
.br
.ti -1c
.RI "class \fBLineBlock\fP"
.br
.ti -1c
.RI "class \fBMarkupError\fP"
.br
.ti -1c
.RI "class \fBMarkupMismatch\fP"
.br
.ti -1c
.RI "class \fBNestedStateMachine\fP"
.br
.ti -1c
.RI "class \fBOptionList\fP"
.br
.ti -1c
.RI "class \fBParserError\fP"
.br
.ti -1c
.RI "class \fBQuotedLiteralBlock\fP"
.br
.ti -1c
.RI "class \fBRFC2822Body\fP"
.br
.ti -1c
.RI "class \fBRFC2822List\fP"
.br
.ti -1c
.RI "class \fBRSTState\fP"
.br
.ti -1c
.RI "class \fBRSTStateMachine\fP"
.br
.ti -1c
.RI "class \fBSpecializedBody\fP"
.br
.ti -1c
.RI "class \fBSpecializedText\fP"
.br
.ti -1c
.RI "class \fBStruct\fP"
.br
.ti -1c
.RI "class \fBSubstitutionDef\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.ti -1c
.RI "class \fBUnknownInterpretedRoleError\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbuild_regexp\fP (definition, compile=True)"
.br
.ti -1c
.RI "\fB_loweralpha_to_int\fP (s, _zero=(ord('a') \-1))"
.br
.ti -1c
.RI "\fB_upperalpha_to_int\fP (s, _zero=(ord('A') \-1))"
.br
.ti -1c
.RI "\fB_lowerroman_to_int\fP (s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBstate_classes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This is the ``docutils\&.parsers\&.rst\&.states`` module, the core of
the reStructuredText parser\&.  It defines the following:

:Classes:
    - `RSTStateMachine`: reStructuredText parser's entry point\&.
    - `NestedStateMachine`: recursive StateMachine\&.
    - `RSTState`: reStructuredText State superclass\&.
    - `Inliner`: For parsing inline markup\&.
    - `Body`: Generic classifier of the first line of a block\&.
    - `SpecializedBody`: Superclass for compound element members\&.
    - `BulletList`: Second and subsequent bullet_list list_items
    - `DefinitionList`: Second+ definition_list_items\&.
    - `EnumeratedList`: Second+ enumerated_list list_items\&.
    - `FieldList`: Second+ fields\&.
    - `OptionList`: Second+ option_list_items\&.
    - `RFC2822List`: Second+ RFC2822-style fields\&.
    - `ExtensionOptions`: Parses directive option fields\&.
    - `Explicit`: Second+ explicit markup constructs\&.
    - `SubstitutionDef`: For embedded directives in substitution definitions\&.
    - `Text`: Classifier of second line of a text block\&.
    - `SpecializedText`: Superclass for continuation lines of Text-variants\&.
    - `Definition`: Second line of potential definition_list_item\&.
    - `Line`: Second line of overlined section title or transition marker\&.
    - `Struct`: An auxiliary collection class\&.

:Exception classes:
    - `MarkupError`
    - `ParserError`
    - `MarkupMismatch`

:Functions:
    - `escape2null()`: Return a string, escape-backslashes converted to nulls\&.
    - `unescape()`: Return a string, nulls removed or restored to backslashes\&.

:Attributes:
    - `state_classes`: set of State classes used with `RSTStateMachine`\&.

Parser Overview
===============

The reStructuredText parser is implemented as a recursive state machine,
examining its input one line at a time\&.  To understand how the parser works,
please first become familiar with the `docutils\&.statemachine` module\&.  In the
description below, references are made to classes defined in this module;
please see the individual classes for details\&.

Parsing proceeds as follows:

1\&. The state machine examines each line of input, checking each of the
   transition patterns of the state `Body`, in order, looking for a match\&.
   The implicit transitions (blank lines and indentation) are checked before
   any others\&.  The 'text' transition is a catch-all (matches anything)\&.

2\&. The method associated with the matched transition pattern is called\&.

   A\&. Some transition methods are self-contained, appending elements to the
      document tree (`Body\&.doctest` parses a doctest block)\&.  The parser's
      current line index is advanced to the end of the element, and parsing
      continues with step 1\&.

   B\&. Other transition methods trigger the creation of a nested state machine,
      whose job is to parse a compound construct ('indent' does a block quote,
      'bullet' does a bullet list, 'overline' does a section [first checking
      for a valid section header], etc\&.)\&.

      - In the case of lists and explicit markup, a one-off state machine is
        created and run to parse contents of the first item\&.

      - A new state machine is created and its initial state is set to the
        appropriate specialized state (`BulletList` in the case of the
        'bullet' transition; see `SpecializedBody` for more detail)\&.  This
        state machine is run to parse the compound element (or series of
        explicit markup elements), and returns as soon as a non-member element
        is encountered\&.  For example, the `BulletList` state machine ends as
        soon as it encounters an element which is not a list item of that
        bullet list\&.  The optional omission of inter-element blank lines is
        enabled by this nested state machine\&.

      - The current line index is advanced to the end of the elements parsed,
        and parsing continues with step 1\&.

   C\&. The result of the 'text' transition depends on the next line of text\&.
      The current state is changed to `Text`, under which the second line is
      examined\&.  If the second line is:

      - Indented: The element is a definition list item, and parsing proceeds
        similarly to step 2\&.B, using the `DefinitionList` state\&.

      - A line of uniform punctuation characters: The element is a section
        header; again, parsing proceeds as in step 2\&.B, and `Body` is still
        used\&.

      - Anything else: The element is a paragraph, which is examined for
        inline markup and appended to the parent element\&.  Processing
        continues with step 1\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "docutils\&.parsers\&.rst\&.states\&._loweralpha_to_int ( s,  _zero = \fC(ord('a')\-1)\fP)\fC [protected]\fP"

.SS "docutils\&.parsers\&.rst\&.states\&._lowerroman_to_int ( s)\fC [protected]\fP"

.SS "docutils\&.parsers\&.rst\&.states\&._upperalpha_to_int ( s,  _zero = \fC(ord('A')\-1)\fP)\fC [protected]\fP"

.SS "docutils\&.parsers\&.rst\&.states\&.build_regexp ( definition,  compile = \fCTrue\fP)"

.PP
.nf
Build, compile and return a regular expression based on `definition`\&.

:Parameter: `definition`: a 4-tuple (group name, prefix, suffix, parts),
    where 'parts' is a list of regular expressions and/or regular
    expression definitions to be joined into an or-group\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "tuple docutils\&.parsers\&.rst\&.states\&.state_classes"
\fBInitial value:\fP.PP
.nf
1 =  (Body, BulletList, DefinitionList, EnumeratedList, FieldList,
2                  OptionList, LineBlock, ExtensionOptions, Explicit, Text,
3                  Definition, Line, SubstitutionDef, RFC2822Body, RFC2822List)
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
