.TH "docutils.utils.math.tex2unichar" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docutils.utils.math.tex2unichar
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBmathaccent\fP"
.br
.ti -1c
.RI "dict \fBmathalpha\fP"
.br
.ti -1c
.RI "dict \fBmathbin\fP"
.br
.ti -1c
.RI "dict \fBmathclose\fP"
.br
.ti -1c
.RI "dict \fBmathfence\fP"
.br
.ti -1c
.RI "dict \fBmathop\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "dict docutils\&.utils\&.math\&.tex2unichar\&.mathaccent"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'acute': '\\u0301',  #  ́ COMBINING ACUTE ACCENT
3     'bar': '\\u0304',  #  ̄ COMBINING MACRON
4     'breve': '\\u0306',  #  ̆ COMBINING BREVE
5     'check': '\\u030c',  #  ̌ COMBINING CARON
6     'ddddot': '\\u20dc',  #  ⃜ COMBINING FOUR DOTS ABOVE
7     'dddot': '\\u20db',  #  ⃛ COMBINING THREE DOTS ABOVE
8     'ddot': '\\u0308',  #  ̈ COMBINING DIAERESIS
9     'dot': '\\u0307',  #  ̇ COMBINING DOT ABOVE
10     'grave': '\\u0300',  #  ̀ COMBINING GRAVE ACCENT
11     'hat': '\\u0302',  #  ̂ COMBINING CIRCUMFLEX ACCENT
12     'mathring': '\\u030a',  #  ̊ COMBINING RING ABOVE
13     'not': '\\u0338',  #  ̸ COMBINING LONG SOLIDUS OVERLAY
14     'overleftrightarrow': '\\u20e1',  #  ⃡ COMBINING LEFT RIGHT ARROW ABOVE
15     'overline': '\\u0305',  #  ̅ COMBINING OVERLINE
16     'tilde': '\\u0303',  #  ̃ COMBINING TILDE
17     'underbar': '\\u0331',  #  ̱ COMBINING MACRON BELOW
18     'underleftarrow': '\\u20ee',  #  ⃮ COMBINING LEFT ARROW BELOW
19     'underline': '\\u0332',  #  ̲ COMBINING LOW LINE
20     'underrightarrow': '\\u20ef',  #  ⃯ COMBINING RIGHT ARROW BELOW
21     'vec': '\\u20d7',  #  ⃗ COMBINING RIGHT ARROW ABOVE
22     }
.fi

.SS "dict docutils\&.utils\&.math\&.tex2unichar\&.mathalpha"

.SS "dict docutils\&.utils\&.math\&.tex2unichar\&.mathbin"

.SS "dict docutils\&.utils\&.math\&.tex2unichar\&.mathclose"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'Rbag': '\\u27c6',  # ⟆ RIGHT S\-SHAPED BAG DELIMITER
3     'lrcorner': '\\u231f',  # ⌟ BOTTOM RIGHT CORNER
4     'rangle': '\\u27e9',  # ⟩ MATHEMATICAL RIGHT ANGLE BRACKET
5     'rbag': '\\u27c6',  # ⟆ RIGHT S\-SHAPED BAG DELIMITER
6     'rbrace': '}',  # } RIGHT CURLY BRACKET
.fi

.SS "dict docutils\&.utils\&.math\&.tex2unichar\&.mathfence"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'Vert': '\\u2016',  # ‖ DOUBLE VERTICAL LINE
3     'vert': '|',  # | VERTICAL LINE
4     '|': '\\u2016',  # ‖ DOUBLE VERTICAL LINE
5     }
.fi

.SS "dict docutils\&.utils\&.math\&.tex2unichar\&.mathop"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
