.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/network/download.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/network/download.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._internal\&.network\&.download\&.Downloader\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.network\&.download\&.BatchDownloader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.network\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.network\&.download\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Optional[int] \fBpip\&._internal\&.network\&.download\&._get_http_response_size\fP (\fBResponse\fP resp)"
.br
.ti -1c
.RI "Iterable[bytes] \fBpip\&._internal\&.network\&.download\&._prepare_download\fP (\fBResponse\fP resp, \fBLink\fP link, str progress_bar)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.network\&.download\&.sanitize_content_filename\fP (str filename)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.network\&.download\&.parse_content_disposition\fP (str content_disposition, str default_filename)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.network\&.download\&._get_http_response_filename\fP (\fBResponse\fP resp, \fBLink\fP link)"
.br
.ti -1c
.RI "\fBResponse\fP \fBpip\&._internal\&.network\&.download\&._http_get_download\fP (PipSession session, \fBLink\fP link)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._internal\&.network\&.download\&.logger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
