.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/bs4/element.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/bs4/element.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbs4\&.element\&.NamespacedAttribute\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.AttributeValueWithCharsetSubstitution\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.CharsetMetaAttributeValue\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.AttributeValueList\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.AttributeDict\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.XMLAttributeDict\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.HTMLAttributeDict\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.ContentMetaAttributeValue\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.PageElement\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.NavigableString\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.PreformattedString\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.CData\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.ProcessingInstruction\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.XMLProcessingInstruction\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.Comment\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.Declaration\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.Doctype\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.Stylesheet\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.Script\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.TemplateString\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.RubyTextString\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.RubyParenthesisString\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.Tag\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.Tag\&._TreeTraversalEvent\fP"
.br
.ti -1c
.RI "class \fBbs4\&.element\&.ResultSet\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbs4\fP"
.br
.ti -1c
.RI "namespace \fBbs4\&.element\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Any \fBbs4\&.element\&.__getattr__\fP (str name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "TypeAlias \fBbs4\&.element\&._OneOrMoreStringTypes\fP"
.br
.ti -1c
.RI "TypeAlias \fBbs4\&.element\&._FindMethodName\fP = Optional[Union['_StrainableElement', 'ElementFilter']]"
.br
.ti -1c
.RI "\fBbs4\&.element\&._deprecated_names\fP"
.br
.ti -1c
.RI "Pattern \fBbs4\&.element\&._deprecated_whitespace_re\fP = re\&.compile(r'\\s+')"
.br
.ti -1c
.RI "str \fBbs4\&.element\&.DEFAULT_OUTPUT_ENCODING\fP = 'utf\-8'"
.br
.ti -1c
.RI "Pattern \fBbs4\&.element\&.nonwhitespace_re\fP = re\&.compile(r'\\S+')"
.br
.ti -1c
.RI "Set \fBbs4\&.element\&.PYTHON_SPECIFIC_ENCODINGS\fP"
.br
.ti -1c
.RI "\fBbs4\&.element\&._PageElementT\fP = TypeVar('_PageElementT', bound=\fBPageElement\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
