.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/jinja2/environment.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/jinja2/environment.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjinja2\&.environment\&.Environment\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.environment\&.Template\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.environment\&.TemplateModule\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.environment\&.TemplateExpression\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.environment\&.TemplateStream\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBjinja2\fP"
.br
.ti -1c
.RI "namespace \fBjinja2\&.environment\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_env_bound\fP \fBjinja2\&.environment\&.get_spontaneous_environment\fP (t\&.Type[\fB_env_bound\fP] cls, *t\&.Any args)"
.br
.ti -1c
.RI "t\&.Optional[t\&.MutableMapping[t\&.Tuple['weakref\&.ref[t\&.Any]', str], 'Template']] \fBjinja2\&.environment\&.create_cache\fP (int size)"
.br
.ti -1c
.RI "t\&.Optional[t\&.MutableMapping[t\&.Tuple['weakref\&.ref[t\&.Any]', str], 'Template']] \fBjinja2\&.environment\&.copy_cache\fP (t\&.Optional[t\&.MutableMapping[t\&.Any, t\&.Any]] cache)"
.br
.ti -1c
.RI "t\&.Dict[str, 'Extension'] \fBjinja2\&.environment\&.load_extensions\fP ('Environment' environment, t\&.Sequence[t\&.Union[str, t\&.Type['Extension']]] extensions)"
.br
.ti -1c
.RI "\fB_env_bound\fP \fBjinja2\&.environment\&._environment_config_check\fP (\fB_env_bound\fP environment)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBjinja2\&.environment\&._env_bound\fP = t\&.TypeVar('_env_bound', bound='Environment')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
