.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/lexers/esoteric.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/lexers/esoteric.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpygments\&.lexers\&.esoteric\&.BrainfuckLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.esoteric\&.BefungeLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.esoteric\&.CAmkESLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.esoteric\&.CapDLLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.esoteric\&.RedcodeLexer\fP"
.br
.ti -1c
.RI "class \fBpygments\&.lexers\&.esoteric\&.AheuiLexer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpygments\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.lexers\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.lexers\&.esoteric\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
