.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/docutils/examples.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/docutils/examples.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdocutils\fP"
.br
.ti -1c
.RI "namespace \fBdocutils\&.examples\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdocutils\&.examples\&.html_parts\fP (input_string, source_path=None, destination_path=None, input_encoding='unicode', doctitle=True, initial_header_level=1)"
.br
.ti -1c
.RI "\fBdocutils\&.examples\&.html_body\fP (input_string, source_path=None, destination_path=None, input_encoding='unicode', output_encoding='unicode', doctitle=True, initial_header_level=1)"
.br
.ti -1c
.RI "\fBdocutils\&.examples\&.internals\fP (input_string, source_path=None, destination_path=None, input_encoding='unicode', settings_overrides=None)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
