.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/messages/extract.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/messages/extract.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbabel\&.messages\&.extract\&._PyOptions\fP"
.br
.ti -1c
.RI "class \fBbabel\&.messages\&.extract\&._JSOptions\fP"
.br
.ti -1c
.RI "class \fBbabel\&.messages\&.extract\&._FileObj\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbabel\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.messages\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.messages\&.extract\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbabel\&.messages\&.extract\&._strip_comment_tags\fP (MutableSequence[str] comments, Iterable[str] tags)"
.br
.ti -1c
.RI "bool \fBbabel\&.messages\&.extract\&.default_directory_filter\fP (str|os\&.PathLike[str] dirpath)"
.br
.ti -1c
.RI "Generator[\fB_FileExtractionResult\fP, None, None] \fBbabel\&.messages\&.extract\&.extract_from_dir\fP (str|os\&.PathLike[str]|None dirname=None, Iterable[tuple[str, str]] method_map=\fBDEFAULT_MAPPING\fP, SupportsItems[str, dict[str, Any]]|None options_map=None, Mapping[str, \fB_Keyword\fP] keywords=\fBDEFAULT_KEYWORDS\fP, Collection[str] comment_tags=(), Callable[[str, str, dict[str, Any]], object]|None callback=None, bool strip_comment_tags=False, Callable[[str], bool]|None directory_filter=None)"
.br
.ti -1c
.RI "Generator[\fB_FileExtractionResult\fP, None, None] \fBbabel\&.messages\&.extract\&.check_and_call_extract_file\fP (str|os\&.PathLike[str] filepath, Iterable[tuple[str, str]] method_map, SupportsItems[str, dict[str, Any]] options_map, Callable[[str, str, dict[str, Any]], object]|None callback, Mapping[str, \fB_Keyword\fP] keywords, Collection[str] comment_tags, bool strip_comment_tags, str|os\&.PathLike[str]|None dirpath=None)"
.br
.ti -1c
.RI "list[\fB_ExtractionResult\fP] \fBbabel\&.messages\&.extract\&.extract_from_file\fP (\fB_ExtractionMethod\fP method, str|os\&.PathLike[str] filename, Mapping[str, \fB_Keyword\fP] keywords=\fBDEFAULT_KEYWORDS\fP, Collection[str] comment_tags=(), Mapping[str, Any]|None options=None, bool strip_comment_tags=False)"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.extract\&._match_messages_against_spec\fP (int lineno, list[str|None] messages, list[str] comments, \fB_FileObj\fP fileobj, tuple[int|tuple[int, str],\&.\&.\&.] spec)"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.extract\&._find_extractor\fP (str name)"
.br
.ti -1c
.RI "Generator[\fB_ExtractionResult\fP, None, None] \fBbabel\&.messages\&.extract\&.extract\fP (\fB_ExtractionMethod\fP method, \fB_FileObj\fP fileobj, Mapping[str, \fB_Keyword\fP] keywords=\fBDEFAULT_KEYWORDS\fP, Collection[str] comment_tags=(), Mapping[str, Any]|None options=None, bool strip_comment_tags=False)"
.br
.ti -1c
.RI "list[\fB_ExtractionResult\fP] \fBbabel\&.messages\&.extract\&.extract_nothing\fP (\fB_FileObj\fP fileobj, Mapping[str, \fB_Keyword\fP] keywords, Collection[str] comment_tags, Mapping[str, Any] options)"
.br
.ti -1c
.RI "Generator[\fB_ExtractionResult\fP, None, None] \fBbabel\&.messages\&.extract\&.extract_python\fP (IO[bytes] fileobj, Mapping[str, \fB_Keyword\fP] keywords, Collection[str] comment_tags, \fB_PyOptions\fP options)"
.br
.ti -1c
.RI "str|None \fBbabel\&.messages\&.extract\&._parse_python_string\fP (str value, str encoding, int future_flags)"
.br
.ti -1c
.RI "Generator[\fB_ExtractionResult\fP, None, None] \fBbabel\&.messages\&.extract\&.extract_javascript\fP (\fB_FileObj\fP fileobj, Mapping[str, \fB_Keyword\fP] keywords, Collection[str] comment_tags, \fB_JSOptions\fP options, int lineno=1)"
.br
.ti -1c
.RI "Generator[\fB_ExtractionResult\fP, None, None] \fBbabel\&.messages\&.extract\&.parse_template_string\fP (str template_string, Mapping[str, \fB_Keyword\fP] keywords, Collection[str] comment_tags, \fB_JSOptions\fP options, int lineno=1)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbabel\&.messages\&.extract\&.TypeAlias\fP"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.messages\&.extract\&._Keyword\fP = dict[int | None, _SimpleKeyword] | _SimpleKeyword"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.messages\&.extract\&._FileExtractionResult\fP = tuple[str, int, str | tuple[str, \&.\&.\&.], list[str], str | None]"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.messages\&.extract\&._ExtractionResult\fP = tuple[int, str | tuple[str, \&.\&.\&.], list[str], str | None]"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.messages\&.extract\&._CallableExtractionMethod\fP"
.br
.ti -1c
.RI "TypeAlias \fBbabel\&.messages\&.extract\&._ExtractionMethod\fP = \fB_CallableExtractionMethod\fP | str"
.br
.ti -1c
.RI "Final \fBbabel\&.messages\&.extract\&.GROUP_NAME\fP = 'babel\&.extractors'"
.br
.ti -1c
.RI "dict \fBbabel\&.messages\&.extract\&.DEFAULT_KEYWORDS\fP"
.br
.ti -1c
.RI "list \fBbabel\&.messages\&.extract\&.DEFAULT_MAPPING\fP = [('**\&.py', 'python')]"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.extract\&.FSTRING_START\fP = getattr(tokenize, 'FSTRING_START', None)"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.extract\&.FSTRING_MIDDLE\fP = getattr(tokenize, 'FSTRING_MIDDLE', None)"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.extract\&.FSTRING_END\fP = getattr(tokenize, 'FSTRING_END', None)"
.br
.ti -1c
.RI "dict \fBbabel\&.messages\&.extract\&._BUILTIN_EXTRACTORS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
