.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/urllib3/fields.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/urllib3/fields.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBurllib3\&.fields\&.RequestField\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBurllib3\fP"
.br
.ti -1c
.RI "namespace \fBurllib3\&.fields\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBurllib3\&.fields\&.guess_content_type\fP (str|None filename, str default='application/octet\-stream')"
.br
.ti -1c
.RI "str \fBurllib3\&.fields\&.format_header_param_rfc2231\fP (str name, \fB_TYPE_FIELD_VALUE\fP value)"
.br
.ti -1c
.RI "str \fBurllib3\&.fields\&.format_multipart_header_param\fP (str name, \fB_TYPE_FIELD_VALUE\fP value)"
.br
.ti -1c
.RI "str \fBurllib3\&.fields\&.format_header_param_html5\fP (str name, \fB_TYPE_FIELD_VALUE\fP value)"
.br
.ti -1c
.RI "str \fBurllib3\&.fields\&.format_header_param\fP (str name, \fB_TYPE_FIELD_VALUE\fP value)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBurllib3\&.fields\&._TYPE_FIELD_VALUE\fP = typing\&.Union[str, bytes]"
.br
.ti -1c
.RI "\fBurllib3\&.fields\&._TYPE_FIELD_VALUE_TUPLE\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
