.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/urllib3/filepost.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/urllib3/filepost.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBurllib3\fP"
.br
.ti -1c
.RI "namespace \fBurllib3\&.filepost\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBurllib3\&.filepost\&.choose_boundary\fP ()"
.br
.ti -1c
.RI "typing\&.Iterable[\fBRequestField\fP] \fBurllib3\&.filepost\&.iter_field_objects\fP (\fB_TYPE_FIELDS\fP fields)"
.br
.ti -1c
.RI "tuple[bytes, str] \fBurllib3\&.filepost\&.encode_multipart_formdata\fP (\fB_TYPE_FIELDS\fP fields, str|None boundary=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBurllib3\&.filepost\&.writer\fP = codecs\&.lookup('utf\-8')[3]"
.br
.ti -1c
.RI "\fBurllib3\&.filepost\&._TYPE_FIELDS_SEQUENCE\fP"
.br
.ti -1c
.RI "\fBurllib3\&.filepost\&._TYPE_FIELDS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
