.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/testing/fixtures.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/testing/fixtures.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.testing\&.fixtures\&.SharedResult\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.testing\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.testing\&.fixtures\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBsphinx\&.testing\&.fixtures\&.pytest_configure\fP (pytest\&.Config config)"
.br
.ti -1c
.RI "Path|None \fBsphinx\&.testing\&.fixtures\&.rootdir\fP ()"
.br
.ti -1c
.RI "\fB_app_params\fP \fBsphinx\&.testing\&.fixtures\&.app_params\fP (Any request, dict[str, Any] \fBtest_params\fP, \fBSharedResult\fP \fBshared_result\fP, Path \fBsphinx_test_tempdir\fP, Path|None \fBrootdir\fP)"
.br
.ti -1c
.RI "dict[str, Any] \fBsphinx\&.testing\&.fixtures\&.test_params\fP (Any request)"
.br
.ti -1c
.RI "Iterator[\fBSphinxTestApp\fP] \fBsphinx\&.testing\&.fixtures\&.app\fP (dict[str, Any] \fBtest_params\fP, \fB_app_params\fP \fBapp_params\fP, Callable[[], \fBSphinxTestApp\fP] \fBmake_app\fP, \fBSharedResult\fP \fBshared_result\fP)"
.br
.ti -1c
.RI "StringIO \fBsphinx\&.testing\&.fixtures\&.status\fP (\fBSphinxTestApp\fP \fBapp\fP)"
.br
.ti -1c
.RI "StringIO \fBsphinx\&.testing\&.fixtures\&.warning\fP (\fBSphinxTestApp\fP \fBapp\fP)"
.br
.ti -1c
.RI "Iterator[Callable[[], \fBSphinxTestApp\fP]] \fBsphinx\&.testing\&.fixtures\&.make_app\fP (dict[str, Any] \fBtest_params\fP)"
.br
.ti -1c
.RI "\fBSharedResult\fP \fBsphinx\&.testing\&.fixtures\&.shared_result\fP ()"
.br
.ti -1c
.RI "None \fBsphinx\&.testing\&.fixtures\&._shared_result_cache\fP ()"
.br
.ti -1c
.RI "None \fBsphinx\&.testing\&.fixtures\&.if_graphviz_found\fP (\fBSphinxTestApp\fP \fBapp\fP)"
.br
.ti -1c
.RI "Path \fBsphinx\&.testing\&.fixtures\&.sphinx_test_tempdir\fP (pytest\&.TempPathFactory tmp_path_factory)"
.br
.ti -1c
.RI "Iterator[None] \fBsphinx\&.testing\&.fixtures\&.rollback_sysmodules\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBsphinx\&.testing\&.fixtures\&.DEFAULT_ENABLED_MARKERS\fP"
.br
.ti -1c
.RI "\fBsphinx\&.testing\&.fixtures\&._app_params\fP = namedtuple('_app_params', 'args,kwargs')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
