.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/webob/headers.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/webob/headers.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwebob\&.headers\&.ResponseHeaders\fP"
.br
.ti -1c
.RI "class \fBwebob\&.headers\&.EnvironHeaders\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwebob\fP"
.br
.ti -1c
.RI "namespace \fBwebob\&.headers\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwebob\&.headers\&._trans_key\fP (key)"
.br
.ti -1c
.RI "\fBwebob\&.headers\&._trans_name\fP (name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBwebob\&.headers\&.key2header\fP"
.br
.ti -1c
.RI "\fBwebob\&.headers\&.header2key\fP = dict([(v\&.upper(),k) for (k,v) in key2header\&.items()])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
