.TH "idna.core.IDNAError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
idna.core.IDNAError
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnicodeError\&.
.PP
Inherited by \fBidna\&.core\&.IDNABidiError\fP, \fBidna\&.core\&.InvalidCodepoint\fP, and \fBidna\&.core\&.InvalidCodepointContext\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Base exception for all IDNA-encoding related problems
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
