.TH "idna.codec.StreamReader" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
idna.codec.StreamReader
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBidna\&.codec\&.Codec\fP, and codecs\&.StreamReader\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBidna\&.codec\&.Codec\fP
.in +1c
.ti -1c
.RI "Tuple[bytes, int] \fBencode\fP (self, str data, str errors='strict')"
.br
.ti -1c
.RI "Tuple[str, int] \fBdecode\fP (self, bytes data, str errors='strict')"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
