.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/ext/inheritance_diagram.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/ext/inheritance_diagram.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.ext\&.inheritance_diagram\&.InheritanceException\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.ext\&.inheritance_diagram\&.InheritanceGraph\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.ext\&.inheritance_diagram\&.inheritance_diagram\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.ext\&.inheritance_diagram\&.InheritanceDiagram\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.ext\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.ext\&.inheritance_diagram\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Any \fBsphinx\&.ext\&.inheritance_diagram\&.try_import\fP (str objname)"
.br
.ti -1c
.RI "list[type[Any]] \fBsphinx\&.ext\&.inheritance_diagram\&.import_classes\fP (str name, str currmodule)"
.br
.ti -1c
.RI "Iterator[type[Any]] \fBsphinx\&.ext\&.inheritance_diagram\&._subclasses\fP (type[Any] cls)"
.br
.ti -1c
.RI "str \fBsphinx\&.ext\&.inheritance_diagram\&.get_graph_hash\fP (\fBinheritance_diagram\fP node)"
.br
.ti -1c
.RI "None \fBsphinx\&.ext\&.inheritance_diagram\&.html_visit_inheritance_diagram\fP (\fBHTML5Translator\fP self, \fBinheritance_diagram\fP node)"
.br
.ti -1c
.RI "None \fBsphinx\&.ext\&.inheritance_diagram\&.latex_visit_inheritance_diagram\fP (\fBLaTeXTranslator\fP self, \fBinheritance_diagram\fP node)"
.br
.ti -1c
.RI "None \fBsphinx\&.ext\&.inheritance_diagram\&.texinfo_visit_inheritance_diagram\fP (\fBTexinfoTranslator\fP self, \fBinheritance_diagram\fP node)"
.br
.ti -1c
.RI "None \fBsphinx\&.ext\&.inheritance_diagram\&.skip\fP (nodes\&.NodeVisitor self, \fBinheritance_diagram\fP node)"
.br
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsphinx\&.ext\&.inheritance_diagram\&.setup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsphinx\&.ext\&.inheritance_diagram\&.module_sig_re\fP"
.br
.ti -1c
.RI "Final \fBsphinx\&.ext\&.inheritance_diagram\&.PY_BUILTINS\fP = frozenset(filter(inspect\&.isclass, vars(builtins)\&.values()))"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
