.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/search/ja.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/search/ja.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.search\&.ja\&.BaseSplitter\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.search\&.ja\&.MecabSplitter\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.search\&.ja\&.JanomeSplitter\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.search\&.ja\&.DefaultSplitter\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.search\&.ja\&.SearchJapanese\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.search\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.search\&.ja\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBsphinx\&.search\&.ja\&.native_module\fP = True"
.br
.ti -1c
.RI "bool \fBsphinx\&.search\&.ja\&.janome_module\fP = True"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
