.TH "jinja2.lexer.OptionalLStrip" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.lexer.OptionalLStrip
.SH SYNOPSIS
.br
.PP
.PP
Inherits tuple\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__new__\fP (cls, *members, **kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A special tuple for marking a point in the state that can have
lstrip applied\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "jinja2\&.lexer\&.OptionalLStrip\&.__new__ ( cls, * members, ** kwargs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
