.TH "jinja2.sandbox.SandboxedFormatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.sandbox.SandboxedFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits Formatter\&.
.PP
Inherited by \fBjinja2\&.sandbox\&.SandboxedEscapeFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBEnvironment\fP env, **t\&.Any kwargs)"
.br
.ti -1c
.RI "t\&.Tuple[t\&.Any, str] \fBget_field\fP (self, str field_name, t\&.Sequence[t\&.Any] args, t\&.Mapping[str, t\&.Any] kwargs)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_env\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None jinja2\&.sandbox\&.SandboxedFormatter\&.__init__ ( self, \fBEnvironment\fP env, **t\&.Any kwargs)"

.SH "Member Function Documentation"
.PP 
.SS " t\&.Tuple[t\&.Any, str] jinja2\&.sandbox\&.SandboxedFormatter\&.get_field ( self, str field_name, t\&.Sequence[t\&.Any] args, t\&.Mapping[str, t\&.Any]
     kwargs)"

.SH "Member Data Documentation"
.PP 
.SS "jinja2\&.sandbox\&.SandboxedFormatter\&._env\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
