.TH "jinja2.compiler.Frame" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.compiler.Frame
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBEvalContext\fP \fBeval_ctx\fP, t\&.Optional['Frame'] \fBparent\fP=None, t\&.Optional[int] level=None)"
.br
.ti -1c
.RI "'te\&.Self' \fBcopy\fP (self)"
.br
.ti -1c
.RI "'Frame' \fBinner\fP (self, bool isolated=False)"
.br
.ti -1c
.RI "'te\&.Self' \fBsoft\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBeval_ctx\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.ti -1c
.RI "\fBsymbols\fP"
.br
.ti -1c
.RI "\fBrequire_output_check\fP"
.br
.ti -1c
.RI "\fBbuffer\fP"
.br
.ti -1c
.RI "\fBblock\fP"
.br
.ti -1c
.RI "\fBtoplevel\fP"
.br
.ti -1c
.RI "\fBrootlevel\fP"
.br
.ti -1c
.RI "\fBloop_frame\fP"
.br
.ti -1c
.RI "\fBblock_frame\fP"
.br
.ti -1c
.RI "\fBsoft_frame\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Holds compile time information for us\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None jinja2\&.compiler\&.Frame\&.__init__ ( self, \fBEvalContext\fP eval_ctx, t\&.Optional['Frame']  parent = \fCNone\fP, t\&.Optional[int]  level = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS " 'te\&.Self' jinja2\&.compiler\&.Frame\&.copy ( self)"

.PP
.nf
Create a copy of the current one\&.
.fi
.PP
 
.SS " 'Frame' jinja2\&.compiler\&.Frame\&.inner ( self, bool  isolated = \fCFalse\fP)"

.PP
.nf
Return an inner frame\&.
.fi
.PP
 
.SS " 'te\&.Self' jinja2\&.compiler\&.Frame\&.soft ( self)"

.PP
.nf
Return a soft frame\&.  A soft frame may not be modified as
standalone thing as it shares the resources with the frame it
was created of, but it's not a rootlevel frame any longer\&.

This is only used to implement if-statements and conditional
expressions\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "jinja2\&.compiler\&.Frame\&.block"

.SS "jinja2\&.compiler\&.Frame\&.block_frame"

.SS "jinja2\&.compiler\&.Frame\&.buffer"

.SS "jinja2\&.compiler\&.Frame\&.eval_ctx"

.SS "jinja2\&.compiler\&.Frame\&.loop_frame"

.SS "jinja2\&.compiler\&.Frame\&.parent"

.SS "jinja2\&.compiler\&.Frame\&.require_output_check"

.SS "jinja2\&.compiler\&.Frame\&.rootlevel"

.SS "jinja2\&.compiler\&.Frame\&.soft_frame"

.SS "jinja2\&.compiler\&.Frame\&.symbols"

.SS "jinja2\&.compiler\&.Frame\&.toplevel"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
