.TH "jinja2.bccache.Bucket" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.bccache.Bucket
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, 'Environment' \fBenvironment\fP, str \fBkey\fP, str \fBchecksum\fP)"
.br
.ti -1c
.RI "None \fBreset\fP (self)"
.br
.ti -1c
.RI "None \fBload_bytecode\fP (self, t\&.BinaryIO f)"
.br
.ti -1c
.RI "None \fBwrite_bytecode\fP (self, t\&.IO[bytes] f)"
.br
.ti -1c
.RI "None \fBbytecode_from_string\fP (self, bytes string)"
.br
.ti -1c
.RI "bytes \fBbytecode_to_string\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBenvironment\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBchecksum\fP"
.br
.ti -1c
.RI "\fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Buckets are used to store the bytecode for one template\&.  It's created
and initialized by the bytecode cache and passed to the loading functions\&.

The buckets get an internal checksum from the cache assigned and use this
to automatically reject outdated cache material\&.  Individual bytecode
cache subclasses don't have to care about cache invalidation\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None jinja2\&.bccache\&.Bucket\&.__init__ ( self, 'Environment' environment, str key, str checksum)"

.SH "Member Function Documentation"
.PP 
.SS " None jinja2\&.bccache\&.Bucket\&.bytecode_from_string ( self, bytes string)"

.PP
.nf
Load bytecode from bytes\&.
.fi
.PP
 
.SS " bytes jinja2\&.bccache\&.Bucket\&.bytecode_to_string ( self)"

.PP
.nf
Return the bytecode as bytes\&.
.fi
.PP
 
.SS " None jinja2\&.bccache\&.Bucket\&.load_bytecode ( self, t\&.BinaryIO f)"

.PP
.nf
Loads bytecode from a file or file like object\&.
.fi
.PP
 
.SS " None jinja2\&.bccache\&.Bucket\&.reset ( self)"

.PP
.nf
Resets the bucket (unloads the bytecode)\&.
.fi
.PP
 
.SS " None jinja2\&.bccache\&.Bucket\&.write_bytecode ( self, t\&.IO[bytes] f)"

.PP
.nf
Dump the bytecode into the file or file like object passed\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "jinja2\&.bccache\&.Bucket\&.checksum"

.SS "jinja2\&.bccache\&.Bucket\&.code"

.SS "jinja2\&.bccache\&.Bucket\&.environment"

.SS "jinja2\&.bccache\&.Bucket\&.key"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
