.TH "jinja2._identifier" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2._identifier
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpattern\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "jinja2\&._identifier\&.pattern"
\fBInitial value:\fP.PP
.nf
1 =  re\&.compile(
2     r"[\\w·̀\-ͯ·҃\-֑҇\-ׇֽֿׁׂׅׄؐ\-ًؚ\-ٰٟۖ\-ۜ۟\-۪ۤۧۨ\-ܑۭܰ\-݊ަ\-ް߫\-߽߳ࠖ\-࠙ࠛ\-ࠣࠥ\-ࠧࠩ\-࡙࠭\-࡛࣓\-ࣣ࣡\-ःऺ\-़ा\-ॏ॑\-ॗॢॣঁ\-ঃ়া\-ৄেৈো\-্ৗৢৣ৾ਁ\-ਃ਼ਾ\-ੂੇੈੋ\-੍ੑੰੱੵઁ\-ઃ઼ા\-ૅે\-ૉો\-્ૢૣૺ\-૿ଁ\-ଃ଼ା\-ୄେୈୋ\-୍ୖୗୢୣஂா\-ூெ\-ைொ\-்ௗఀ\-ఄా\-ౄె\-ైొ\-్ౕౖౢౣಁ\-ಃ಼ಾ\-ೄೆ\-ೈೊ\-್ೕೖೢೣഀ\-ഃ഻഼ാ\-ൄെ\-ൈൊ\-്ൗൢൣංඃ්ා\-ුූෘ\-ෟෲෳัิ\-ฺ็\-๎ັິ\-ູົຼ່\-ໍ༹༘༙༵༷༾༿ཱ\-྄྆྇ྍ\-ྗྙ\-ྼ࿆ါ\-ှၖ\-ၙၞ\-ၠၢ\-ၤၧ\-ၭၱ\-ၴႂ\-ႍႏႚ\-ႝ፝\-፟ᜒ\-᜔ᜲ\-᜴ᝒᝓᝲᝳ឴\-៓៝᠋\-᠍ᢅᢆᢩᤠ\-ᤫᤰ\-᤻ᨗ\-ᨛᩕ\-ᩞ᩠\-᩿᩼᪰\-᪽ᬀ\-ᬄ᬴\-᭄᭫\-᭳ᮀ\-ᮂᮡ\-ᮭ᯦\-᯳ᰤ\-᰷᳐\-᳔᳒\-᳨᳭ᳲ\-᳴᳷\-᳹᷀\-᷹᷻\-᷿‿⁀⁔⃐\-⃥⃜⃡\-⃰℘℮⳯\-⵿⳱ⷠ\-〪ⷿ\-゙゚〯꙯ꙴ\-꙽ꚞꚟ꛰꛱ꠂ꠆ꠋꠣ\-ꠧꢀꢁꢴ\-ꣅ꣠\-꣱ꣿꤦ\-꤭ꥇ\-꥓ꦀ\-ꦃ꦳\-꧀ꧥꨩ\-ꨶꩃꩌꩍꩻ\-ꩽꪰꪲ\-ꪴꪷꪸꪾ꪿꫁ꫫ\-ꫯꫵ꫶ꯣ\-ꯪ꯬꯭ﬞ︀\-️︠\-︯︳︴﹍\-﹏＿𐇽𐋠𐍶\-𐍺𐨁\-𐨃𐨅𐨆𐨌\-𐨏𐨸\-𐨿𐨺𐫦𐫥𐴤\-𐽆𐴧\-𐽐𑀀\-𑀂𑀸\-𑁆𑁿\-𑂂𑂰\-𑂺𑄀\-𑄂𑄧\-𑄴𑅅𑅆𑅳𑆀\-𑆂𑆳\-𑇀𑇉\-𑇌𑈬\-𑈷𑈾𑋟\-𑋪𑌀\-𑌃𑌻𑌼𑌾\-𑍄𑍇𑍈𑍋\-𑍍𑍗𑍢𑍣𑍦\-𑍬𑍰\-𑍴𑐵\-𑑆𑑞𑒰\-𑓃𑖯\-𑖵𑖸\-𑗀𑗜𑗝𑘰\-𑙀𑚫\-𑚷𑜝\-𑜫𑠬\-𑠺𑨁\-𑨊𑨳\-𑨹𑨻\-𑨾𑩇𑩑\-𑩛𑪊\-𑪙𑰯\-𑰶𑰸\-𑰿𑲒\-𑲧𑲩\-𑲶𑴱\-𑴶𑴺𑴼𑴽𑴿\-𑵅𑵇𑶊\-𑶎𑶐𑶑𑶓\-𑶗𑻳\-𑻶𖫰\-𖫴𖬰\-𖬶𖽑\-𖽾𖾏\-𖾒𛲝𛲞𝅥\-𝅩𝅭\-𝅲𝅻\-𝆂𝆅\-𝆋𝆪\-𝆭𝉂\-𝉄𝨀\-𝨶𝨻\-𝩬𝩵𝪄𝪛\-𝪟𝪡\-𝪯𞀀\-𞀆𞀈\-𞀘𞀛\-𞀡𞀣𞀤𞀦\-𞣐𞀪\-𞣖𞥄\-𞥊󠄀\-󠇯]+"  # noqa: B950
3 )
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
