.TH "jinja2.nodes" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.nodes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_FilterTestCommon\fP"
.br
.ti -1c
.RI "class \fBAdd\fP"
.br
.ti -1c
.RI "class \fBAnd\fP"
.br
.ti -1c
.RI "class \fBAssign\fP"
.br
.ti -1c
.RI "class \fBAssignBlock\fP"
.br
.ti -1c
.RI "class \fBBinExpr\fP"
.br
.ti -1c
.RI "class \fBBlock\fP"
.br
.ti -1c
.RI "class \fBBreak\fP"
.br
.ti -1c
.RI "class \fBCall\fP"
.br
.ti -1c
.RI "class \fBCallBlock\fP"
.br
.ti -1c
.RI "class \fBCompare\fP"
.br
.ti -1c
.RI "class \fBConcat\fP"
.br
.ti -1c
.RI "class \fBCondExpr\fP"
.br
.ti -1c
.RI "class \fBConst\fP"
.br
.ti -1c
.RI "class \fBContextReference\fP"
.br
.ti -1c
.RI "class \fBContinue\fP"
.br
.ti -1c
.RI "class \fBDerivedContextReference\fP"
.br
.ti -1c
.RI "class \fBDict\fP"
.br
.ti -1c
.RI "class \fBDiv\fP"
.br
.ti -1c
.RI "class \fBEnvironmentAttribute\fP"
.br
.ti -1c
.RI "class \fBEvalContext\fP"
.br
.ti -1c
.RI "class \fBEvalContextModifier\fP"
.br
.ti -1c
.RI "class \fBExpr\fP"
.br
.ti -1c
.RI "class \fBExprStmt\fP"
.br
.ti -1c
.RI "class \fBExtends\fP"
.br
.ti -1c
.RI "class \fBExtensionAttribute\fP"
.br
.ti -1c
.RI "class \fBFilter\fP"
.br
.ti -1c
.RI "class \fBFilterBlock\fP"
.br
.ti -1c
.RI "class \fBFloorDiv\fP"
.br
.ti -1c
.RI "class \fBFor\fP"
.br
.ti -1c
.RI "class \fBFromImport\fP"
.br
.ti -1c
.RI "class \fBGetattr\fP"
.br
.ti -1c
.RI "class \fBGetitem\fP"
.br
.ti -1c
.RI "class \fBHelper\fP"
.br
.ti -1c
.RI "class \fBIf\fP"
.br
.ti -1c
.RI "class \fBImport\fP"
.br
.ti -1c
.RI "class \fBImportedName\fP"
.br
.ti -1c
.RI "class \fBImpossible\fP"
.br
.ti -1c
.RI "class \fBInclude\fP"
.br
.ti -1c
.RI "class \fBInternalName\fP"
.br
.ti -1c
.RI "class \fBKeyword\fP"
.br
.ti -1c
.RI "class \fBList\fP"
.br
.ti -1c
.RI "class \fBLiteral\fP"
.br
.ti -1c
.RI "class \fBMacro\fP"
.br
.ti -1c
.RI "class \fBMarkSafe\fP"
.br
.ti -1c
.RI "class \fBMarkSafeIfAutoescape\fP"
.br
.ti -1c
.RI "class \fBMod\fP"
.br
.ti -1c
.RI "class \fBMul\fP"
.br
.ti -1c
.RI "class \fBName\fP"
.br
.ti -1c
.RI "class \fBNeg\fP"
.br
.ti -1c
.RI "class \fBNode\fP"
.br
.ti -1c
.RI "class \fBNodeType\fP"
.br
.ti -1c
.RI "class \fBNot\fP"
.br
.ti -1c
.RI "class \fBNSRef\fP"
.br
.ti -1c
.RI "class \fBOperand\fP"
.br
.ti -1c
.RI "class \fBOr\fP"
.br
.ti -1c
.RI "class \fBOutput\fP"
.br
.ti -1c
.RI "class \fBOverlayScope\fP"
.br
.ti -1c
.RI "class \fBPair\fP"
.br
.ti -1c
.RI "class \fBPos\fP"
.br
.ti -1c
.RI "class \fBPow\fP"
.br
.ti -1c
.RI "class \fBScope\fP"
.br
.ti -1c
.RI "class \fBScopedEvalContextModifier\fP"
.br
.ti -1c
.RI "class \fBSlice\fP"
.br
.ti -1c
.RI "class \fBStmt\fP"
.br
.ti -1c
.RI "class \fBSub\fP"
.br
.ti -1c
.RI "class \fBTemplate\fP"
.br
.ti -1c
.RI "class \fBTemplateData\fP"
.br
.ti -1c
.RI "class \fBTest\fP"
.br
.ti -1c
.RI "class \fBTuple\fP"
.br
.ti -1c
.RI "class \fBUnaryExpr\fP"
.br
.ti -1c
.RI "class \fBWith\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEvalContext\fP \fBget_eval_context\fP ('Node' node, t\&.Optional[\fBEvalContext\fP] ctx)"
.br
.ti -1c
.RI "t\&.Tuple[t\&.List[t\&.Any], t\&.Dict[t\&.Any, t\&.Any]] \fBargs_as_const\fP (t\&.Union['_FilterTestCommon', 'Call'] node, t\&.Optional[\fBEvalContext\fP] eval_ctx)"
.br
.ti -1c
.RI "'te\&.NoReturn' \fB_failing_new\fP (*t\&.Any args, **t\&.Any kwargs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_NodeBound\fP = t\&.TypeVar('_NodeBound', bound='Node')"
.br
.ti -1c
.RI "dict \fB_binop_to_func\fP"
.br
.ti -1c
.RI "dict \fB_uaop_to_func\fP"
.br
.ti -1c
.RI "dict \fB_cmpop_to_func\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
AST nodes generated by the parser for the compiler\&. Also provides
some node tree helper functions used by the parser and compiler in order
to normalize nodes\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " 'te\&.NoReturn' jinja2\&.nodes\&._failing_new (*t\&.Any args, **t\&.Any kwargs)\fC [protected]\fP"

.SS " t\&.Tuple[t\&.List[t\&.Any], t\&.Dict[t\&.Any, t\&.Any]] jinja2\&.nodes\&.args_as_const (t\&.Union['_FilterTestCommon', 'Call'] node, t\&.Optional[\fBEvalContext\fP]
 eval_ctx)"

.SS " \fBEvalContext\fP jinja2\&.nodes\&.get_eval_context ('Node' node, t\&.Optional[\fBEvalContext\fP] ctx)"

.SH "Variable Documentation"
.PP 
.SS "dict jinja2\&.nodes\&._binop_to_func\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  {
2     "*": operator\&.mul,
3     "/": operator\&.truediv,
4     "//": operator\&.floordiv,
5     "**": operator\&.pow,
6     "%": operator\&.mod,
7     "+": operator\&.add,
8     "\-": operator\&.sub,
9 }
.fi

.SS "dict jinja2\&.nodes\&._cmpop_to_func\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  {
2     "eq": operator\&.eq,
3     "ne": operator\&.ne,
4     "gt": operator\&.gt,
5     "gteq": operator\&.ge,
6     "lt": operator\&.lt,
7     "lteq": operator\&.le,
8     "in": lambda a, b: a in b,
9     "notin": lambda a, b: a not in b,
10 }
.fi

.SS "jinja2\&.nodes\&._NodeBound = t\&.TypeVar('_NodeBound', bound='Node')\fC [protected]\fP"

.SS "dict jinja2\&.nodes\&._uaop_to_func\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  {
2     "not": operator\&.not_,
3     "+": operator\&.pos,
4     "\-": operator\&.neg,
5 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
