.TH "jinja2.idtracking.RootVisitor" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.idtracking.RootVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBjinja2\&.visitor\&.NodeVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, 'Symbols' symbols)"
.br
.ti -1c
.RI "None \fBvisit_AssignBlock\fP (self, \fBnodes\&.AssignBlock\fP node, **t\&.Any kwargs)"
.br
.ti -1c
.RI "None \fBvisit_CallBlock\fP (self, \fBnodes\&.CallBlock\fP node, **t\&.Any kwargs)"
.br
.ti -1c
.RI "None \fBvisit_OverlayScope\fP (self, \fBnodes\&.OverlayScope\fP node, **t\&.Any kwargs)"
.br
.ti -1c
.RI "None \fBvisit_For\fP (self, \fBnodes\&.For\fP node, str for_branch='body', **t\&.Any kwargs)"
.br
.ti -1c
.RI "None \fBvisit_With\fP (self, \fBnodes\&.With\fP node, **t\&.Any kwargs)"
.br
.ti -1c
.RI "None \fBgeneric_visit\fP (self, \fBnodes\&.Node\fP node, *t\&.Any args, **t\&.Any kwargs)"
.br
.in -1c

Public Member Functions inherited from \fBjinja2\&.visitor\&.NodeVisitor\fP
.in +1c
.ti -1c
.RI "'t\&.Optional[\fBVisitCallable\fP]' \fBget_visitor\fP (self, \fBNode\fP node)"
.br
.ti -1c
.RI "t\&.Any \fBvisit\fP (self, \fBNode\fP node, *t\&.Any args, **t\&.Any kwargs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsym_visitor\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "None \fBvisit_Template\fP = \fB_simple_visit\fP"
.br
.ti -1c
.RI "None \fBvisit_Block\fP = \fB_simple_visit\fP"
.br
.ti -1c
.RI "None \fBvisit_Macro\fP = \fB_simple_visit\fP"
.br
.ti -1c
.RI "None \fBvisit_FilterBlock\fP = \fB_simple_visit\fP"
.br
.ti -1c
.RI "None \fBvisit_Scope\fP = \fB_simple_visit\fP"
.br
.ti -1c
.RI "None \fBvisit_If\fP = \fB_simple_visit\fP"
.br
.ti -1c
.RI "None \fBvisit_ScopedEvalContextModifier\fP = \fB_simple_visit\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "None \fB_simple_visit\fP (self, \fBnodes\&.Node\fP node, **t\&.Any kwargs)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None jinja2\&.idtracking\&.RootVisitor\&.__init__ ( self, 'Symbols' symbols)"

.SH "Member Function Documentation"
.PP 
.SS " None jinja2\&.idtracking\&.RootVisitor\&._simple_visit ( self, \fBnodes\&.Node\fP node, **t\&.Any kwargs)\fC [protected]\fP"

.SS " None jinja2\&.idtracking\&.RootVisitor\&.generic_visit ( self, \fBnodes\&.Node\fP node, *t\&.Any args, **t\&.Any kwargs)"

.PP
.nf
Called if no explicit visitor function exists for a node\&.
.fi
.PP
 
.PP
Reimplemented from \fBjinja2\&.visitor\&.NodeVisitor\fP\&.
.SS " None jinja2\&.idtracking\&.RootVisitor\&.visit_AssignBlock ( self, \fBnodes\&.AssignBlock\fP node, **t\&.Any kwargs)"

.SS " None jinja2\&.idtracking\&.RootVisitor\&.visit_CallBlock ( self, \fBnodes\&.CallBlock\fP node, **t\&.Any kwargs)"

.SS " None jinja2\&.idtracking\&.RootVisitor\&.visit_For ( self, \fBnodes\&.For\fP node, str  for_branch = \fC'body'\fP, **t\&.Any
     kwargs)"

.SS " None jinja2\&.idtracking\&.RootVisitor\&.visit_OverlayScope ( self, \fBnodes\&.OverlayScope\fP node, **t\&.Any kwargs)"

.SS " None jinja2\&.idtracking\&.RootVisitor\&.visit_With ( self, \fBnodes\&.With\fP node, **t\&.Any kwargs)"

.SH "Member Data Documentation"
.PP 
.SS "jinja2\&.idtracking\&.RootVisitor\&.sym_visitor"

.SS "None jinja2\&.idtracking\&.RootVisitor\&.visit_Block = \fB_simple_visit\fP\fC [static]\fP"

.SS "None jinja2\&.idtracking\&.RootVisitor\&.visit_FilterBlock = \fB_simple_visit\fP\fC [static]\fP"

.SS "None jinja2\&.idtracking\&.RootVisitor\&.visit_If = \fB_simple_visit\fP\fC [static]\fP"

.SS "None jinja2\&.idtracking\&.RootVisitor\&.visit_Macro = \fB_simple_visit\fP\fC [static]\fP"

.SS "None jinja2\&.idtracking\&.RootVisitor\&.visit_Scope = \fB_simple_visit\fP\fC [static]\fP"

.SS "None jinja2\&.idtracking\&.RootVisitor\&.visit_ScopedEvalContextModifier = \fB_simple_visit\fP\fC [static]\fP"

.SS "None jinja2\&.idtracking\&.RootVisitor\&.visit_Template = \fB_simple_visit\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
