.TH "jinja2.tests" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.tests
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtest_odd\fP (int value)"
.br
.ti -1c
.RI "bool \fBtest_even\fP (int value)"
.br
.ti -1c
.RI "bool \fBtest_divisibleby\fP (int value, int num)"
.br
.ti -1c
.RI "bool \fBtest_defined\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_undefined\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_filter\fP ('Environment' env, str value)"
.br
.ti -1c
.RI "bool \fBtest_test\fP ('Environment' env, str value)"
.br
.ti -1c
.RI "bool \fBtest_none\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_boolean\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_false\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_true\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_integer\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_float\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_lower\fP (str value)"
.br
.ti -1c
.RI "bool \fBtest_upper\fP (str value)"
.br
.ti -1c
.RI "bool \fBtest_string\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_mapping\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_number\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_sequence\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_sameas\fP (t\&.Any value, t\&.Any other)"
.br
.ti -1c
.RI "bool \fBtest_iterable\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_escaped\fP (t\&.Any value)"
.br
.ti -1c
.RI "bool \fBtest_in\fP (t\&.Any value, t\&.Container[t\&.Any] seq)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBTESTS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Built-in template tests used with the ``is`` operator\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " bool jinja2\&.tests\&.test_boolean (t\&.Any value)"

.PP
.nf
Return true if the object is a boolean value\&.

\&.\&. versionadded:: 2\&.11

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_defined (t\&.Any value)"

.PP
.nf
Return true if the variable is defined:

\&.\&. sourcecode:: jinja

    {% if variable is defined %}
        value of variable: {{ variable }}
    {% else %}
        variable is not defined
    {% endif %}

See the :func:`default` filter for a simple way to set undefined
variables\&.

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_divisibleby (int value, int num)"

.PP
.nf
Check if a variable is divisible by a number\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_escaped (t\&.Any value)"

.PP
.nf
Check if the value is escaped\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_even (int value)"

.PP
.nf
Return true if the variable is even\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_false (t\&.Any value)"

.PP
.nf
Return true if the object is False\&.

\&.\&. versionadded:: 2\&.11

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_filter ('Environment' env, str value)"

.PP
.nf
Check if a filter exists by name\&. Useful if a filter may be
optionally available\&.

\&.\&. code-block:: jinja

    {% if 'markdown' is filter %}
        {{ value | markdown }}
    {% else %}
        {{ value }}
    {% endif %}

\&.\&. versionadded:: 3\&.0

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_float (t\&.Any value)"

.PP
.nf
Return true if the object is a float\&.

\&.\&. versionadded:: 2\&.11

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_in (t\&.Any value, t\&.Container[t\&.Any] seq)"

.PP
.nf
Check if value is in seq\&.

\&.\&. versionadded:: 2\&.10

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_integer (t\&.Any value)"

.PP
.nf
Return true if the object is an integer\&.

\&.\&. versionadded:: 2\&.11

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_iterable (t\&.Any value)"

.PP
.nf
Check if it's possible to iterate over an object\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_lower (str value)"

.PP
.nf
Return true if the variable is lowercased\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_mapping (t\&.Any value)"

.PP
.nf
Return true if the object is a mapping (dict etc\&.)\&.

\&.\&. versionadded:: 2\&.6

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_none (t\&.Any value)"

.PP
.nf
Return true if the variable is none\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_number (t\&.Any value)"

.PP
.nf
Return true if the variable is a number\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_odd (int value)"

.PP
.nf
Return true if the variable is odd\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_sameas (t\&.Any value, t\&.Any other)"

.PP
.nf
Check if an object points to the same memory address than another
object:

\&.\&. sourcecode:: jinja

    {% if foo\&.attribute is sameas false %}
        the foo attribute really is the `False` singleton
    {% endif %}

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_sequence (t\&.Any value)"

.PP
.nf
Return true if the variable is a sequence\&. Sequences are variables
that are iterable\&.

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_string (t\&.Any value)"

.PP
.nf
Return true if the object is a string\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_test ('Environment' env, str value)"

.PP
.nf
Check if a test exists by name\&. Useful if a test may be
optionally available\&.

\&.\&. code-block:: jinja

    {% if 'loud' is test %}
        {% if value is loud %}
            {{ value|upper }}
        {% else %}
            {{ value|lower }}
        {% endif %}
    {% else %}
        {{ value }}
    {% endif %}

\&.\&. versionadded:: 3\&.0

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_true (t\&.Any value)"

.PP
.nf
Return true if the object is True\&.

\&.\&. versionadded:: 2\&.11

.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_undefined (t\&.Any value)"

.PP
.nf
Like :func:`defined` but the other way round\&.
.fi
.PP
 
.SS " bool jinja2\&.tests\&.test_upper (str value)"

.PP
.nf
Return true if the variable is uppercased\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict jinja2\&.tests\&.TESTS"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
