.TH "jinja2.runtime.Macro" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.runtime.Macro
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, 'Environment' environment, t\&.Callable[\&.\&.\&., str] func, str \fBname\fP, t\&.List[str] \fBarguments\fP, bool \fBcatch_kwargs\fP, bool \fBcatch_varargs\fP, bool \fBcaller\fP, t\&.Optional[bool] default_autoescape=None)"
.br
.ti -1c
.RI "str \fB__call__\fP (self, *t\&.Any args, **t\&.Any kwargs)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBarguments\fP"
.br
.ti -1c
.RI "\fBcatch_kwargs\fP"
.br
.ti -1c
.RI "\fBcatch_varargs\fP"
.br
.ti -1c
.RI "\fBcaller\fP"
.br
.ti -1c
.RI "\fBexplicit_caller\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_async_invoke\fP (self, t\&.List[t\&.Any] \fBarguments\fP, bool autoescape)"
.br
.ti -1c
.RI "str \fB_invoke\fP (self, t\&.List[t\&.Any] \fBarguments\fP, bool autoescape)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_environment\fP"
.br
.ti -1c
.RI "\fB_func\fP"
.br
.ti -1c
.RI "\fB_argument_count\fP"
.br
.ti -1c
.RI "\fB_default_autoescape\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Wraps a macro function\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jinja2\&.runtime\&.Macro\&.__init__ ( self, 'Environment' environment, t\&.Callable[\&.\&.\&., str] func, str name, t\&.List[str] arguments, bool catch_kwargs, bool catch_varargs, bool caller, t\&.Optional[bool]  default_autoescape = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS " str jinja2\&.runtime\&.Macro\&.__call__ ( self, *t\&.Any args, **t\&.Any kwargs)"

.SS " str jinja2\&.runtime\&.Macro\&.__repr__ ( self)"

.SS " str jinja2\&.runtime\&.Macro\&._async_invoke ( self, t\&.List[t\&.Any] arguments, bool autoescape)\fC [protected]\fP"

.SS " str jinja2\&.runtime\&.Macro\&._invoke ( self, t\&.List[t\&.Any] arguments, bool autoescape)\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "jinja2\&.runtime\&.Macro\&._argument_count\fC [protected]\fP"

.SS "jinja2\&.runtime\&.Macro\&._default_autoescape\fC [protected]\fP"

.SS "jinja2\&.runtime\&.Macro\&._environment\fC [protected]\fP"

.SS "jinja2\&.runtime\&.Macro\&._func\fC [protected]\fP"

.SS "jinja2\&.runtime\&.Macro\&.arguments"

.SS "jinja2\&.runtime\&.Macro\&.caller"

.SS "jinja2\&.runtime\&.Macro\&.catch_kwargs"

.SS "jinja2\&.runtime\&.Macro\&.catch_varargs"

.SS "jinja2\&.runtime\&.Macro\&.explicit_caller"

.SS "jinja2\&.runtime\&.Macro\&.name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
