.TH "jinja2.async_utils" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.async_utils
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_IteratorToAsyncIterator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBasync_variant\fP (normal_func)"
.br
.ti -1c
.RI "'V' \fBauto_await\fP (t\&.Union[t\&.Awaitable['V'], 'V'] value)"
.br
.ti -1c
.RI "'t\&.AsyncIterator[\fBV\fP]' \fBauto_aiter\fP ('t\&.Union[t\&.AsyncIterable[\fBV\fP], t\&.Iterable[\fBV\fP]]' iterable)"
.br
.ti -1c
.RI "t\&.List['V'] \fBauto_to_list\fP ('t\&.Union[t\&.AsyncIterable[\fBV\fP], t\&.Iterable[\fBV\fP]]' value)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBV\fP = t\&.TypeVar('V')"
.br
.ti -1c
.RI "dict \fB_common_primitives\fP = {int, float, bool, str, list, dict, tuple, type(None)}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "jinja2\&.async_utils\&.async_variant ( normal_func)"

.SS " 't\&.AsyncIterator[\fBV\fP]' jinja2\&.async_utils\&.auto_aiter ('t\&.Union[t\&.AsyncIterable[\fBV\fP], t\&.Iterable[\fBV\fP]]' iterable)"

.SS " 'V' jinja2\&.async_utils\&.auto_await (t\&.Union[t\&.Awaitable['V'], 'V'] value)"

.SS " t\&.List['V'] jinja2\&.async_utils\&.auto_to_list ('t\&.Union[t\&.AsyncIterable[\fBV\fP], t\&.Iterable[\fBV\fP]]' value)"

.SH "Variable Documentation"
.PP 
.SS "dict jinja2\&.async_utils\&._common_primitives = {int, float, bool, str, list, dict, tuple, type(None)}\fC [protected]\fP"

.SS "jinja2\&.async_utils\&.V = t\&.TypeVar('V')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
