.TH "jinja2.runtime.BlockReference" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.runtime.BlockReference
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBname\fP, 'Context' context, t\&.List[t\&.Callable[['Context'], t\&.Iterator[str]]] stack, int depth)"
.br
.ti -1c
.RI "t\&.Union['BlockReference', 'Undefined'] \fBsuper\fP (self)"
.br
.ti -1c
.RI "str \fB__call__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_async_call\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_context\fP"
.br
.ti -1c
.RI "\fB_stack\fP"
.br
.ti -1c
.RI "\fB_depth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
One block on a template reference\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None jinja2\&.runtime\&.BlockReference\&.__init__ ( self, str name, 'Context' context, t\&.List[t\&.Callable[['Context'], t\&.Iterator[str]]] stack, int depth)"

.SH "Member Function Documentation"
.PP 
.SS " str jinja2\&.runtime\&.BlockReference\&.__call__ ( self)"

.SS " str jinja2\&.runtime\&.BlockReference\&._async_call ( self)\fC [protected]\fP"

.SS " t\&.Union['BlockReference', 'Undefined'] jinja2\&.runtime\&.BlockReference\&.super ( self)"

.PP
.nf
Super the block\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "jinja2\&.runtime\&.BlockReference\&._context\fC [protected]\fP"

.SS "jinja2\&.runtime\&.BlockReference\&._depth\fC [protected]\fP"

.SS "jinja2\&.runtime\&.BlockReference\&._stack\fC [protected]\fP"

.SS "jinja2\&.runtime\&.BlockReference\&.name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
