.TH "jinja2.loaders" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.loaders
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_TemplateModule\fP"
.br
.ti -1c
.RI "class \fBBaseLoader\fP"
.br
.ti -1c
.RI "class \fBChoiceLoader\fP"
.br
.ti -1c
.RI "class \fBDictLoader\fP"
.br
.ti -1c
.RI "class \fBFileSystemLoader\fP"
.br
.ti -1c
.RI "class \fBFunctionLoader\fP"
.br
.ti -1c
.RI "class \fBModuleLoader\fP"
.br
.ti -1c
.RI "class \fBPackageLoader\fP"
.br
.ti -1c
.RI "class \fBPrefixLoader\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "t\&.List[str] \fBsplit_template_path\fP (str template)"
.br
.ti -1c
.RI "t\&.Dict[str, object] \fB_get_zipimporter_files\fP (t\&.Any z)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
API and implementations for loading templates from different data
sources\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " t\&.Dict[str, object] jinja2\&.loaders\&._get_zipimporter_files (t\&.Any z)\fC [protected]\fP"

.SS " t\&.List[str] jinja2\&.loaders\&.split_template_path (str template)"

.PP
.nf
Split a path into segments and perform a sanity check\&.  If it detects
'\&.\&.' in the path it will raise a `TemplateNotFound` error\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
