.TH "jinja2.lexer.TokenStream" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.lexer.TokenStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, t\&.Iterable[\fBToken\fP] generator, t\&.Optional[str] \fBname\fP, t\&.Optional[str] \fBfilename\fP)"
.br
.ti -1c
.RI "\fBTokenStreamIterator\fP \fB__iter__\fP (self)"
.br
.ti -1c
.RI "bool \fB__bool__\fP (self)"
.br
.ti -1c
.RI "bool \fBeos\fP (self)"
.br
.ti -1c
.RI "None \fBpush\fP (self, \fBToken\fP token)"
.br
.ti -1c
.RI "\fBToken\fP \fBlook\fP (self)"
.br
.ti -1c
.RI "None \fBskip\fP (self, int n=1)"
.br
.ti -1c
.RI "t\&.Optional[\fBToken\fP] \fBnext_if\fP (self, str expr)"
.br
.ti -1c
.RI "bool \fBskip_if\fP (self, str expr)"
.br
.ti -1c
.RI "\fBToken\fP \fB__next__\fP (self)"
.br
.ti -1c
.RI "None \fBclose\fP (self)"
.br
.ti -1c
.RI "\fBToken\fP \fBexpect\fP (self, str expr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBclosed\fP"
.br
.ti -1c
.RI "\fBcurrent\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_iter\fP"
.br
.ti -1c
.RI "\fB_pushed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A token stream is an iterable that yields :class:`Token`\\\\s\&.  The
parser however does not iterate over it but calls :meth:`next` to go
one token ahead\&.  The current active token is stored as :attr:`current`\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jinja2\&.lexer\&.TokenStream\&.__init__ ( self, t\&.Iterable[\fBToken\fP] generator, t\&.Optional[str] name, t\&.Optional[str] filename)"

.SH "Member Function Documentation"
.PP 
.SS " bool jinja2\&.lexer\&.TokenStream\&.__bool__ ( self)"

.SS " \fBTokenStreamIterator\fP jinja2\&.lexer\&.TokenStream\&.__iter__ ( self)"

.SS " \fBToken\fP jinja2\&.lexer\&.TokenStream\&.__next__ ( self)"

.PP
.nf
Go one token ahead and return the old one\&.

Use the built-in :func:`next` instead of calling this directly\&.

.fi
.PP
 
.SS " None jinja2\&.lexer\&.TokenStream\&.close ( self)"

.PP
.nf
Close the stream\&.
.fi
.PP
 
.SS " bool jinja2\&.lexer\&.TokenStream\&.eos ( self)"

.PP
.nf
Are we at the end of the stream?
.fi
.PP
 
.SS " \fBToken\fP jinja2\&.lexer\&.TokenStream\&.expect ( self, str expr)"

.PP
.nf
Expect a given token type and return it\&.  This accepts the same
argument as :meth:`jinja2\&.lexer\&.Token\&.test`\&.

.fi
.PP
 
.SS " \fBToken\fP jinja2\&.lexer\&.TokenStream\&.look ( self)"

.PP
.nf
Look at the next token\&.
.fi
.PP
 
.SS " t\&.Optional[\fBToken\fP] jinja2\&.lexer\&.TokenStream\&.next_if ( self, str expr)"

.PP
.nf
Perform the token test and return the token if it matched\&.
Otherwise the return value is `None`\&.

.fi
.PP
 
.SS " None jinja2\&.lexer\&.TokenStream\&.push ( self, \fBToken\fP token)"

.PP
.nf
Push a token back to the stream\&.
.fi
.PP
 
.SS " None jinja2\&.lexer\&.TokenStream\&.skip ( self, int  n = \fC1\fP)"

.PP
.nf
Got n tokens ahead\&.
.fi
.PP
 
.SS " bool jinja2\&.lexer\&.TokenStream\&.skip_if ( self, str expr)"

.PP
.nf
Like :meth:`next_if` but only returns `True` or `False`\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "jinja2\&.lexer\&.TokenStream\&._iter\fC [protected]\fP"

.SS "jinja2\&.lexer\&.TokenStream\&._pushed\fC [protected]\fP"

.SS "jinja2\&.lexer\&.TokenStream\&.closed"

.SS "jinja2\&.lexer\&.TokenStream\&.current"

.SS "jinja2\&.lexer\&.TokenStream\&.filename"

.SS "jinja2\&.lexer\&.TokenStream\&.name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
