.TH "jinja2.runtime.Context" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.runtime.Context
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, 'Environment' \fBenvironment\fP, t\&.Dict[str, t\&.Any] \fBparent\fP, t\&.Optional[str] \fBname\fP, t\&.Dict[str, t\&.Callable[['Context'], t\&.Iterator[str]]] \fBblocks\fP, t\&.Optional[t\&.MutableMapping[str, t\&.Any]] globals=None)"
.br
.ti -1c
.RI "t\&.Union['BlockReference', 'Undefined'] \fBsuper\fP (self, str \fBname\fP, t\&.Callable[['Context'], t\&.Iterator[str]] current)"
.br
.ti -1c
.RI "t\&.Any \fBget\fP (self, str key, t\&.Any default=None)"
.br
.ti -1c
.RI "t\&.Union[t\&.Any, 'Undefined'] \fBresolve\fP (self, str key)"
.br
.ti -1c
.RI "t\&.Any \fBresolve_or_missing\fP (self, str key)"
.br
.ti -1c
.RI "t\&.Dict[str, t\&.Any] \fBget_exported\fP (self)"
.br
.ti -1c
.RI "t\&.Dict[str, t\&.Any] \fBget_all\fP (self)"
.br
.ti -1c
.RI "t\&.Union[t\&.Any, 'Undefined'] \fBcall\fP (__self, t\&.Callable[\&.\&.\&., t\&.Any] __obj, *t\&.Any args, **t\&.Any kwargs)"
.br
.ti -1c
.RI "'Context' \fBderived\fP (self, t\&.Optional[t\&.Dict[str, t\&.Any]] locals=None)"
.br
.ti -1c
.RI "bool \fB__contains__\fP (self, str \fBname\fP)"
.br
.ti -1c
.RI "t\&.Any \fB__getitem__\fP (self, str key)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparent\fP"
.br
.ti -1c
.RI "\fBeval_ctx\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBglobals_keys\fP"
.br
.ti -1c
.RI "\fBblocks\fP"
.br
.ti -1c
.RI "\fBvars\fP"
.br
.ti -1c
.RI "\fBenvironment\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBkeys\fP = \fB_dict_method_all\fP(dict\&.keys)"
.br
.ti -1c
.RI "\fBvalues\fP = \fB_dict_method_all\fP(dict\&.values)"
.br
.ti -1c
.RI "\fBitems\fP = \fB_dict_method_all\fP(dict\&.items)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The template context holds the variables of a template\&.  It stores the
values passed to the template and also the names the template exports\&.
Creating instances is neither supported nor useful as it's created
automatically at various stages of the template evaluation and should not
be created by hand\&.

The context is immutable\&.  Modifications on :attr:`parent` **must not**
happen and modifications on :attr:`vars` are allowed from generated
template code only\&.  Template filters and global functions marked as
:func:`pass_context` get the active context passed as first argument
and are allowed to access the context read-only\&.

The template context supports read only dict operations (`get`,
`keys`, `values`, `items`, `iterkeys`, `itervalues`, `iteritems`,
`__getitem__`, `__contains__`)\&.  Additionally there is a :meth:`resolve`
method that doesn't fail with a `KeyError` but returns an
:class:`Undefined` object for missing variables\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jinja2\&.runtime\&.Context\&.__init__ ( self, 'Environment' environment, t\&.Dict[str, t\&.Any] parent, t\&.Optional[str] name, t\&.Dict[str, t\&.Callable[['Context'], t\&.Iterator[str]]] blocks, t\&.Optional[t\&.MutableMapping[str, t\&.Any]]  globals = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS " bool jinja2\&.runtime\&.Context\&.__contains__ ( self, str name)"

.SS " t\&.Any jinja2\&.runtime\&.Context\&.__getitem__ ( self, str key)"

.PP
.nf
Look up a variable by name with ``[]`` syntax, or raise a
``KeyError`` if the key is not found\&.

.fi
.PP
 
.SS " str jinja2\&.runtime\&.Context\&.__repr__ ( self)"

.SS " t\&.Union[t\&.Any, 'Undefined'] jinja2\&.runtime\&.Context\&.call ( __self, t\&.Callable[\&.\&.\&., t\&.Any] __obj, *t\&.Any args, **t\&.Any kwargs)"

.PP
.nf
Call the callable with the arguments and keyword arguments
provided but inject the active context or environment as first
argument if the callable has :func:`pass_context` or
:func:`pass_environment`\&.

.fi
.PP
 
.SS " 'Context' jinja2\&.runtime\&.Context\&.derived ( self, t\&.Optional[t\&.Dict[str, t\&.Any]]  locals = \fCNone\fP)"

.PP
.nf
Internal helper function to create a derived context\&.  This is
used in situations where the system needs a new context in the same
template that is independent\&.

.fi
.PP
 
.SS " t\&.Any jinja2\&.runtime\&.Context\&.get ( self, str key, t\&.Any  default = \fCNone\fP)"

.PP
.nf
Look up a variable by name, or return a default if the key is
not found\&.

:param key: The variable name to look up\&.
:param default: The value to return if the key is not found\&.

.fi
.PP
 
.SS " t\&.Dict[str, t\&.Any] jinja2\&.runtime\&.Context\&.get_all ( self)"

.PP
.nf
Return the complete context as dict including the exported
variables\&.  For optimizations reasons this might not return an
actual copy so be careful with using it\&.

.fi
.PP
 
.SS " t\&.Dict[str, t\&.Any] jinja2\&.runtime\&.Context\&.get_exported ( self)"

.PP
.nf
Get a new dict with the exported variables\&.
.fi
.PP
 
.SS " t\&.Union[t\&.Any, 'Undefined'] jinja2\&.runtime\&.Context\&.resolve ( self, str key)"

.PP
.nf
Look up a variable by name, or return an :class:`Undefined`
object if the key is not found\&.

If you need to add custom behavior, override
:meth:`resolve_or_missing`, not this method\&. The various lookup
functions use that method, not this one\&.

:param key: The variable name to look up\&.

.fi
.PP
 
.SS " t\&.Any jinja2\&.runtime\&.Context\&.resolve_or_missing ( self, str key)"

.PP
.nf
Look up a variable by name, or return a ``missing`` sentinel
if the key is not found\&.

Override this method to add custom lookup behavior\&.
:meth:`resolve`, :meth:`get`, and :meth:`__getitem__` use this
method\&. Don't call this method directly\&.

:param key: The variable name to look up\&.

.fi
.PP
 
.SS " t\&.Union['BlockReference', 'Undefined'] jinja2\&.runtime\&.Context\&.super ( self, str name, t\&.Callable[['Context'], t\&.Iterator[str]]
     current)"

.PP
.nf
Render a parent block\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "jinja2\&.runtime\&.Context\&.blocks"

.SS "jinja2\&.runtime\&.Context\&.environment"

.SS "jinja2\&.runtime\&.Context\&.eval_ctx"

.SS "jinja2\&.runtime\&.Context\&.globals_keys"

.SS "jinja2\&.runtime\&.Context\&.items = \fB_dict_method_all\fP(dict\&.items)\fC [static]\fP"

.SS "jinja2\&.runtime\&.Context\&.keys = \fB_dict_method_all\fP(dict\&.keys)\fC [static]\fP"

.SS "jinja2\&.runtime\&.Context\&.name"

.SS "jinja2\&.runtime\&.Context\&.parent"

.SS "jinja2\&.runtime\&.Context\&.values = \fB_dict_method_all\fP(dict\&.values)\fC [static]\fP"

.SS "jinja2\&.runtime\&.Context\&.vars"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
