.TH "jinja2.ext._TranslationsContext" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.ext._TranslationsContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBjinja2\&.ext\&._TranslationsBasic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "str \fBpgettext\fP (self, str context, str message)"
.br
.ti -1c
.RI "str \fBnpgettext\fP (self, str context, str singular, str plural, int n)"
.br
.in -1c

Public Member Functions inherited from \fBjinja2\&.ext\&._TranslationsBasic\fP
.in +1c
.ti -1c
.RI "str \fBgettext\fP (self, str message)"
.br
.ti -1c
.RI "str \fBngettext\fP (self, str singular, str plural, int n)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " str jinja2\&.ext\&._TranslationsContext\&.npgettext ( self, str context, str singular, str plural, int
         n)"

.SS " str jinja2\&.ext\&._TranslationsContext\&.pgettext ( self, str context, str message)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
