.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/jinja2glue.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/jinja2glue.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.jinja2glue\&.idgen\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.jinja2glue\&.SphinxFileSystemLoader\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.jinja2glue\&.BuiltinTemplateLoader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.jinja2glue\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsphinx\&.jinja2glue\&._tobool\fP (str val)"
.br
.ti -1c
.RI "int \fBsphinx\&.jinja2glue\&._toint\fP (str val)"
.br
.ti -1c
.RI "str \fBsphinx\&.jinja2glue\&._todim\fP (int|str val)"
.br
.ti -1c
.RI "Iterator[list[_RealIndexEntry]] \fBsphinx\&.jinja2glue\&._slice_index\fP (_RealIndexEntries values, int slices)"
.br
.ti -1c
.RI "str \fBsphinx\&.jinja2glue\&.accesskey\fP (Any context, str key)"
.br
.ti -1c
.RI "str \fBsphinx\&.jinja2glue\&.warning\fP (dict[str, Any] context, str message, *Any args, **Any kwargs)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
