.TH "jinja2.loaders.BaseLoader" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jinja2.loaders.BaseLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBjinja2\&.loaders\&.ChoiceLoader\fP, \fBjinja2\&.loaders\&.DictLoader\fP, \fBjinja2\&.loaders\&.FileSystemLoader\fP, \fBjinja2\&.loaders\&.FunctionLoader\fP, \fBjinja2\&.loaders\&.ModuleLoader\fP, \fBjinja2\&.loaders\&.PackageLoader\fP, \fBjinja2\&.loaders\&.PrefixLoader\fP, \fBsphinx\&.jinja2glue\&.BuiltinTemplateLoader\fP, and \fBsphinx\&.util\&.template\&.SphinxTemplateLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "t\&.Tuple[str, t\&.Optional[str], t\&.Optional[t\&.Callable[[], bool]]] \fBget_source\fP (self, 'Environment' environment, str template)"
.br
.ti -1c
.RI "t\&.List[str] \fBlist_templates\fP (self)"
.br
.ti -1c
.RI "'Template' \fBload\fP (self, 'Environment' environment, str name, t\&.Optional[t\&.MutableMapping[str, t\&.Any]] globals=None)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhas_source_access\fP = True"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Baseclass for all loaders\&.  Subclass this and override `get_source` to
implement a custom loading mechanism\&.  The environment provides a
`get_template` method that calls the loader's `load` method to get the
:class:`Template` object\&.

A very basic example for a loader that looks up templates on the file
system could look like this::

    from jinja2 import BaseLoader, TemplateNotFound
    from os\&.path import join, exists, getmtime

    class MyLoader(BaseLoader):

        def __init__(self, path):
            self\&.path = path

        def get_source(self, environment, template):
            path = join(self\&.path, template)
            if not exists(path):
                raise TemplateNotFound(template)
            mtime = getmtime(path)
            with open(path) as f:
                source = f\&.read()
            return source, path, lambda: mtime == getmtime(path)

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " t\&.Tuple[str, t\&.Optional[str], t\&.Optional[t\&.Callable[[], bool]]] jinja2\&.loaders\&.BaseLoader\&.get_source ( self, 'Environment' environment, str
     template)"

.PP
.nf
Get the template source, filename and reload helper for a template\&.
It's passed the environment and template name and has to return a
tuple in the form ``(source, filename, uptodate)`` or raise a
`TemplateNotFound` error if it can't locate the template\&.

The source part of the returned tuple must be the source of the
template as a string\&. The filename should be the name of the
file on the filesystem if it was loaded from there, otherwise
``None``\&. The filename is used by Python for the tracebacks
if no loader extension is used\&.

The last item in the tuple is the `uptodate` function\&.  If auto
reloading is enabled it's always called to check if the template
changed\&.  No arguments are passed so the function must store the
old state somewhere (for example in a closure)\&.  If it returns `False`
the template will be reloaded\&.

.fi
.PP
 
.PP
Reimplemented in \fBjinja2\&.loaders\&.FileSystemLoader\fP, \fBjinja2\&.loaders\&.PackageLoader\fP, \fBjinja2\&.loaders\&.DictLoader\fP, \fBjinja2\&.loaders\&.FunctionLoader\fP, \fBjinja2\&.loaders\&.PrefixLoader\fP, \fBjinja2\&.loaders\&.ChoiceLoader\fP, \fBsphinx\&.jinja2glue\&.SphinxFileSystemLoader\fP, \fBsphinx\&.jinja2glue\&.BuiltinTemplateLoader\fP, and \fBsphinx\&.util\&.template\&.SphinxTemplateLoader\fP\&.
.SS " t\&.List[str] jinja2\&.loaders\&.BaseLoader\&.list_templates ( self)"

.PP
.nf
Iterates over all templates\&.  If the loader does not support that
it should raise a :exc:`TypeError` which is the default behavior\&.

.fi
.PP
 
.PP
Reimplemented in \fBjinja2\&.loaders\&.FileSystemLoader\fP, \fBjinja2\&.loaders\&.PackageLoader\fP, \fBjinja2\&.loaders\&.DictLoader\fP, \fBjinja2\&.loaders\&.PrefixLoader\fP, and \fBjinja2\&.loaders\&.ChoiceLoader\fP\&.
.SS " 'Template' jinja2\&.loaders\&.BaseLoader\&.load ( self, 'Environment' environment, str name, t\&.Optional[t\&.MutableMapping[str, t\&.Any]]  globals = \fCNone\fP)"

.PP
.nf
Loads a template\&.  This method looks up the template in the cache
or loads one by calling :meth:`get_source`\&.  Subclasses should not
override this method as loaders working on collections of other
loaders (such as :class:`PrefixLoader` or :class:`ChoiceLoader`)
will not call this method but `get_source` directly\&.

.fi
.PP
 
.PP
Reimplemented in \fBjinja2\&.loaders\&.PrefixLoader\fP, \fBjinja2\&.loaders\&.ChoiceLoader\fP, and \fBjinja2\&.loaders\&.ModuleLoader\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool jinja2\&.loaders\&.BaseLoader\&.has_source_access = True\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
