.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/messages/jslexer.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/babel/messages/jslexer.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbabel\&.messages\&.jslexer\&.Token\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbabel\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.messages\fP"
.br
.ti -1c
.RI "namespace \fBbabel\&.messages\&.jslexer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "list[tuple[str|None, re\&.Pattern[str]]] \fBbabel\&.messages\&.jslexer\&.get_rules\fP (bool jsx, bool dotted, bool template_string)"
.br
.ti -1c
.RI "bool \fBbabel\&.messages\&.jslexer\&.indicates_division\fP (\fBToken\fP token)"
.br
.ti -1c
.RI "str \fBbabel\&.messages\&.jslexer\&.unquote_string\fP (str string)"
.br
.ti -1c
.RI "Generator[\fBToken\fP, None, None] \fBbabel\&.messages\&.jslexer\&.tokenize\fP (str source, bool jsx=True, bool dotted=True, bool template_string=True, int lineno=1)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBbabel\&.messages\&.jslexer\&.operators\fP"
.br
.ti -1c
.RI "dict \fBbabel\&.messages\&.jslexer\&.escapes\fP = {'b': '\\b', 'f': '\\f', 'n': '\\n', 'r': '\\r', 't': '\\t'}"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.jslexer\&.name_re\fP = re\&.compile(r'[\\w$_][\\w\\d$_]*', re\&.UNICODE)"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.jslexer\&.dotted_name_re\fP = re\&.compile(r'[\\w$_][\\w\\d$_\&.]*[\\w\\d$_\&.]', re\&.UNICODE)"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.jslexer\&.division_re\fP = re\&.compile(r'/=?')"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.jslexer\&.regex_re\fP = re\&.compile(r'/(?:[^/\\\\]*(?:\\\\\&.[^/\\\\]*)*)/[a\-zA\-Z]*', re\&.DOTALL)"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.jslexer\&.line_re\fP = re\&.compile(r'(\\r\\n|\\n|\\r)')"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.jslexer\&.line_join_re\fP = re\&.compile(r'\\\\' + line_re\&.pattern)"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.jslexer\&.uni_escape_re\fP = re\&.compile(r'[a\-fA\-F0\-9]{1,4}')"
.br
.ti -1c
.RI "\fBbabel\&.messages\&.jslexer\&.hex_escape_re\fP = re\&.compile(r'[a\-fA\-F0\-9]{1,2}')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
