.TH "jsmath.version" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsmath.version
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
.nf
    sphinxcontrib\&.jsmath\&.version
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    :copyright: Copyright 2007-2019 by the Sphinx team, see README\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
