.TH "jsmath" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsmath
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBversion\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBhtml_visit_math\fP (HTMLTranslator self, nodes\&.math node)"
.br
.ti -1c
.RI "None \fBhtml_visit_displaymath\fP (HTMLTranslator self, nodes\&.math_block node)"
.br
.ti -1c
.RI "None \fBinstall_jsmath\fP (\fBSphinx\fP app, \fBBuildEnvironment\fP env)"
.br
.ti -1c
.RI "Dict[str, Any] \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpackage_dir\fP = path\&.abspath(path\&.dirname(__file__))"
.br
.ti -1c
.RI "\fB_\fP = get_translation(__name__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    sphinxcontrib\&.jsmath
    ~~~~~~~~~~~~~~~~~~~~

    Set up everything for use of JSMath to display math in HTML
    via JavaScript\&.

    :copyright: Copyright 2007-2019 by the Sphinx team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " None jsmath\&.html_visit_displaymath (HTMLTranslator self, nodes\&.math_block node)"

.SS " None jsmath\&.html_visit_math (HTMLTranslator self, nodes\&.math node)"

.SS " None jsmath\&.install_jsmath (\fBSphinx\fP app, \fBBuildEnvironment\fP env)"

.SS " Dict[str, Any] jsmath\&.setup (\fBSphinx\fP app)"

.SH "Variable Documentation"
.PP 
.SS "jsmath\&._ = get_translation(__name__)\fC [protected]\fP"

.SS "jsmath\&.package_dir = path\&.abspath(path\&.dirname(__file__))"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
