.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/rich/jupyter.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/rich/jupyter.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterRenderable\fP"
.br
.ti -1c
.RI "class \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.rich\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.rich\&.jupyter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBpip\&._vendor\&.rich\&.jupyter\&._render_segments\fP (Iterable[\fBSegment\fP] segments)"
.br
.ti -1c
.RI "None \fBpip\&._vendor\&.rich\&.jupyter\&.display\fP (Iterable[\fBSegment\fP] segments, str text)"
.br
.ti -1c
.RI "None \fBpip\&._vendor\&.rich\&.jupyter\&.print\fP (*Any args, **Any kwargs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBpip\&._vendor\&.rich\&.jupyter\&.JUPYTER_HTML_FORMAT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
