.TH "/home/umar/Desktop/WorkShop/GLL/Poke/main.c" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Poke/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'poke\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__NOBUFFERING\fP   setvbuf(stdout  , (char *)0 , _IONBF, 0)"
.br
.ti -1c
.RI "#define \fBperr\fP(__fcall)   perror(#__fcall)"
.br
.ti -1c
.RI "#define \fBpokerr\fP(__fcall, \&.\&.\&.)     do{\fBperr\fP(__fcall) ; fprintf(stderr,__VA_ARGS__);}while(0)"
.br
.ti -1c
.RI "#define \fB__gnu_vargs__\fP   \&.\&.\&."
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpoke_sighdl\fP (int incomming_signal) \fB__attribute__\fP((noreturn))"
.br
.ti -1c
.RI "void \fBpoke_handle_registered_signal\fP (int __nsig, struct sigaction *__restrict__ __sact, \fB__gnu_vargs__\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int ac, char **av, char **ev)"
.br
.ti -1c
.RI "void \fBpoke_handle_registered_signal\fP (int nsig, struct sigaction *restrict sact, \fB__gnu_vargs__\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBh_errno\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __gnu_vargs__   \&.\&.\&."

.SS "#define __NOBUFFERING   setvbuf(stdout  , (char *)0 , _IONBF, 0)"

.SS "#define perr(__fcall)   perror(#__fcall)"

.SS "#define pokerr(__fcall,  \&.\&.\&.)     do{\fBperr\fP(__fcall) ; fprintf(stderr,__VA_ARGS__);}while(0)"

.SH "Function Documentation"
.PP 
.SS "int main (int ac, char ** av, char ** ev)"
NOTE : handle multiple signat at once
.PP
NOTE : For testing purpose check if the program receive ICMP_ECHO request form foreign host
.SS "void poke_handle_registered_signal (int __nsig, struct sigaction *__restrict__ __sact, \fB__gnu_vargs__\fP)"

.SS "void poke_handle_registered_signal (int nsig, struct sigaction *restrict sact, \fB__gnu_vargs__\fP)"

.SS "void poke_sighdl (int incomming_signal)"

.SH "Variable Documentation"
.PP 
.SS "int h_errno\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
