.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/util/matching.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/util/matching.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.util\&.matching\&.Matcher\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.util\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.util\&.matching\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBsphinx\&.util\&.matching\&._translate_pattern\fP (str pat)"
.br
.ti -1c
.RI "list[Callable[[str], re\&.Match[str]|None]] \fBsphinx\&.util\&.matching\&.compile_matchers\fP (Iterable[str] patterns)"
.br
.ti -1c
.RI "re\&.Match[str]|None \fBsphinx\&.util\&.matching\&.patmatch\fP (str name, str pat)"
.br
.ti -1c
.RI "list[str] \fBsphinx\&.util\&.matching\&.patfilter\fP (Iterable[str] names, str pat)"
.br
.ti -1c
.RI "Iterator[str] \fBsphinx\&.util\&.matching\&.get_matching_files\fP (str|os\&.PathLike[str] dirname, Iterable[str] include_patterns=(' **',), Iterable[str] exclude_patterns=())"
.br
.ti -1c
.RI "str \fBsphinx\&.util\&.matching\&._unicode_nfc\fP (str s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsphinx\&.util\&.matching\&.DOTFILES\fP = \fBMatcher\fP(['**/\&.*'])"
.br
.ti -1c
.RI "dict \fBsphinx\&.util\&.matching\&._pat_cache\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
