.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/charset_normalizer/md.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/charset_normalizer/md.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.MessDetectorPlugin\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.TooManySymbolOrPunctuationPlugin\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.TooManyAccentuatedPlugin\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.UnprintablePlugin\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.SuspiciousDuplicateAccentPlugin\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.SuspiciousRange\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.SuperWeirdWordPlugin\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.CjkUncommonPlugin\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.ArchaicUpperLowerPlugin\fP"
.br
.ti -1c
.RI "class \fBcharset_normalizer\&.md\&.ArabicIsolatedFormPlugin\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcharset_normalizer\fP"
.br
.ti -1c
.RI "namespace \fBcharset_normalizer\&.md\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcharset_normalizer\&.md\&.is_suspiciously_successive_range\fP (str|None unicode_range_a, str|None unicode_range_b)"
.br
.ti -1c
.RI "float \fBcharset_normalizer\&.md\&.mess_ratio\fP (str decoded_sequence, float maximum_threshold=0\&.2, bool debug=False)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
