.TH "md__2home_2umar_2Desktop_2WorkShop_2GLL_2Greetings_2README" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__2home_2umar_2Desktop_2WorkShop_2GLL_2Greetings_2README \- README 
.PP
  
.SS "GLL Greetings "
.PP
    
.PP
 \fC\fP
.PP
.SH "Greetings"
.PP
.PP
A simple 'Hello World' like program but says “Greetings” at the assembly level\&. It uses the Netwide Assembly language, known as NASM\&. You can install it from the web or from your package manager Check \fCnasm-installation\fP
.PP
So we have two programs that say “Greetings”\&.
.IP "\(bu" 2
form \fCMS-DOS\fP
.IP "\(bu" 2
form the \fCMBR-Bootloader\fP
.PP
.PP
.SS "MS-DOS"
.PP
The file \fCgreeting_from_dos\&.asm\fP : is a simple program that says “Greetings\&.\&.\&.” from an MS-DOS application using the MS-DOS interrupt function call to print it from standard output\&. to print from standard output\&. This program requires to have \fCdosbox-emulator\fP application already install\&. See your package manager if the \fCdosbox-emulator\fP is available first :)
.PP
.SS "MBR-Bootloader"
.PP
MBR stand for Master Boot Record more info see \fCMBR\fP For more info about \fCQemu\fP
.PP
The \fCgreeting_from_bootloader\&.asm\fP file is identical to that in MS-DOS is identical to that of MS-DOS, but uses the BIOS interception call\&. It is a simple boot file used by many operating systems, but contains only a welcome message and the boot signature at the end\&.
.PP
This program requires \fCQemu\fP to be available on your machine\&. Or check your package manager\&.
.PP
.SS "Build Stage"
 You have at your disposal a makefilefile, which you can use to compile\&. Please feel free to consult the file
.PP
here are some instructions, depending on the target you wish to use generate
.PP
.SS "For MS-DOS"
.PP
.PP
.PP
.nf
$ >  make  ms\-dos   # to generate the executable for bosbox 
$ >  make  launch\-dosbox  # to launch dosbox application 
.fi
.PP
.PP
.SS "For Qemu/MBR"
.PP
.PP
.PP
.nf
$ >  make boot\-mbr   # to Generate the MBR  file 
$ >  make run\-qemu   # launch qemu emulation and execute the MBR file 
.fi
.PP
.PP
.IP "\(bu" 2
To clean or delete the generated file, type \fCmake clean\fP\&.
.IP "\(bu" 2
To generate all files, simply type \fCmake\fP\&.
.PP
.PP
 
.SS "ScreenShots"
.PP
 
.SS "DOSBOX"
 
.PP
.SS "Qemu"
.PP
.PP
Feel free to contribute\&.
.PP
We ❤️ Computers at all Levels\&.
.PP
From Senegal\&. 🇸🇳 
