.TH "md__2home_2umar_2Desktop_2WorkShop_2GLL_2README" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__2home_2umar_2Desktop_2WorkShop_2GLL_2README \- CENTRY 
.PP
 
.SS "What is Centry"
Centry is a simple, lightweight program that lets you access the inside of a running Docker container just like in interactive tty mode\&. The only prerequisite is to have Docker already available on your system\&.
.SS "Quick demo"
.PP
.nf
#  center  <short\-id\-container{2\-3}> 
.fi
.PP
 Exemple : 
.PP
.nf
$> docker ps 
CONTAINER ID   IMAGE                     COMMAND           CREATED        STATUS        PORTS     NAMES
c3784c6459b9   <image>                   "sleep 9999999"   24 hours ago   Up 24 hours            festive_ramanujan
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

#> center c37   

.fi
.PP
 For more option use the -h or --help command
.SS "COMPILE"
Quick and easy to compile 
.PP
.nf
$> gcc  centry\&.c  \-o <your_final_exec> 

.fi
.PP
.SS "OPTION"
If you have meson
.PP
.PP
.nf
$>  meson setup build 
$>  meson compile \-C build 
$>  meson install \-C build  #To install localy 
.fi
.PP
.PP
To uninstall 
.PP
.nf
#> ninja uninstall \-C build 

.fi
.PP
 
