.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/utils/misc.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/utils/misc.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._internal\&.utils\&.misc\&.StreamWrapper\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.utils\&.misc\&.HiddenText\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.utils\&.misc\&.ConfiguredBuildBackendHookCaller\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.utils\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.utils\&.misc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.get_pip_version\fP ()"
.br
.ti -1c
.RI "Tuple[int, int, int] \fBpip\&._internal\&.utils\&.misc\&.normalize_version_info\fP (Tuple[int,\&.\&.\&.] py_version_info)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&.ensure_dir\fP (str path)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.get_prog\fP ()"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&.rmtree\fP (str dir, bool ignore_errors=False, Optional[\fBOnExc\fP] onexc=None)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&._onerror_ignore\fP (*Any _args)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&._onerror_reraise\fP (*Any _args)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&.rmtree_errorhandler\fP (FunctionType func, Path path, Union[\fBExcInfo\fP, BaseException] exc_info, *\fBOnExc\fP onexc=\fB_onerror_reraise\fP)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.display_path\fP (str path)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.backup_dir\fP (str dir, str ext='\&.bak')"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.ask_path_exists\fP (str message, Iterable[str] options)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&._check_no_input\fP (str message)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.ask\fP (str message, Iterable[str] options)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.ask_input\fP (str message)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.ask_password\fP (str message)"
.br
.ti -1c
.RI "int \fBpip\&._internal\&.utils\&.misc\&.strtobool\fP (str val)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.format_size\fP (float bytes)"
.br
.ti -1c
.RI "Tuple[List[str], List[int]] \fBpip\&._internal\&.utils\&.misc\&.tabulate\fP (Iterable[Iterable[Any]] rows)"
.br
.ti -1c
.RI "bool \fBpip\&._internal\&.utils\&.misc\&.is_installable_dir\fP (str path)"
.br
.ti -1c
.RI "Generator[bytes, None, None] \fBpip\&._internal\&.utils\&.misc\&.read_chunks\fP (BinaryIO file, int size=\fBFILE_CHUNK_SIZE\fP)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.normalize_path\fP (str path, bool resolve_symlinks=True)"
.br
.ti -1c
.RI "Tuple[str, str] \fBpip\&._internal\&.utils\&.misc\&.splitext\fP (str path)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&.renames\fP (str old, str new)"
.br
.ti -1c
.RI "bool \fBpip\&._internal\&.utils\&.misc\&.is_local\fP (str path)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&.write_output\fP (Any msg, *Any args)"
.br
.ti -1c
.RI "Type[Any] \fBpip\&._internal\&.utils\&.misc\&.enum\fP (*Any sequential, **Any named)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.build_netloc\fP (str host, Optional[int] port)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.build_url_from_netloc\fP (str netloc, str scheme='https')"
.br
.ti -1c
.RI "Tuple[Optional[str], Optional[int]] \fBpip\&._internal\&.utils\&.misc\&.parse_netloc\fP (str netloc)"
.br
.ti -1c
.RI "\fBNetlocTuple\fP \fBpip\&._internal\&.utils\&.misc\&.split_auth_from_netloc\fP (str netloc)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.redact_netloc\fP (str netloc)"
.br
.ti -1c
.RI "Tuple[str, \fBNetlocTuple\fP] \fBpip\&._internal\&.utils\&.misc\&._transform_url\fP (str url, Callable[[str], Tuple[Any,\&.\&.\&.]] transform_netloc)"
.br
.ti -1c
.RI "\fBNetlocTuple\fP \fBpip\&._internal\&.utils\&.misc\&._get_netloc\fP (str netloc)"
.br
.ti -1c
.RI "Tuple[str] \fBpip\&._internal\&.utils\&.misc\&._redact_netloc\fP (str netloc)"
.br
.ti -1c
.RI "Tuple[str, str, Tuple[Optional[str], Optional[str]]] \fBpip\&._internal\&.utils\&.misc\&.split_auth_netloc_from_url\fP (str url)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.remove_auth_from_url\fP (str url)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.redact_auth_from_url\fP (str url)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.utils\&.misc\&.redact_auth_from_requirement\fP (\fBRequirement\fP req)"
.br
.ti -1c
.RI "\fBHiddenText\fP \fBpip\&._internal\&.utils\&.misc\&.hide_value\fP (str value)"
.br
.ti -1c
.RI "\fBHiddenText\fP \fBpip\&._internal\&.utils\&.misc\&.hide_url\fP (str url)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&.protect_pip_from_modification_on_windows\fP (bool modifying_pip)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&.check_externally_managed\fP ()"
.br
.ti -1c
.RI "bool \fBpip\&._internal\&.utils\&.misc\&.is_console_interactive\fP ()"
.br
.ti -1c
.RI "Tuple[Any, int] \fBpip\&._internal\&.utils\&.misc\&.hash_file\fP (str path, int blocksize=1<< 20)"
.br
.ti -1c
.RI "Iterator[Tuple[Any, Any]] \fBpip\&._internal\&.utils\&.misc\&.pairwise\fP (Iterable[Any] iterable)"
.br
.ti -1c
.RI "Tuple[Iterable[\fBT\fP], Iterable[\fBT\fP]] \fBpip\&._internal\&.utils\&.misc\&.partition\fP (Callable[[\fBT\fP], bool] pred, Iterable[\fBT\fP] iterable)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.utils\&.misc\&.warn_if_run_as_root\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.misc\&.logger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.misc\&.T\fP = TypeVar('T')"
.br
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.misc\&.ExcInfo\fP = Tuple[Type[BaseException], BaseException, TracebackType]"
.br
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.misc\&.VersionInfo\fP = Tuple[int, int, int]"
.br
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.misc\&.NetlocTuple\fP = Tuple[str, Tuple[Optional[str], Optional[str]]]"
.br
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.misc\&.OnExc\fP = Callable[[FunctionType, Path, BaseException], Any]"
.br
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.misc\&.OnErr\fP = Callable[[FunctionType, Path, \fBExcInfo\fP], Any]"
.br
.ti -1c
.RI "int \fBpip\&._internal\&.utils\&.misc\&.FILE_CHUNK_SIZE\fP = 1024 * 1024"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
