.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/jinja2/nativetypes.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/jinja2/nativetypes.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjinja2\&.nativetypes\&.NativeCodeGenerator\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.nativetypes\&.NativeEnvironment\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.nativetypes\&.NativeTemplate\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBjinja2\fP"
.br
.ti -1c
.RI "namespace \fBjinja2\&.nativetypes\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "t\&.Optional[t\&.Any] \fBjinja2\&.nativetypes\&.native_concat\fP (t\&.Iterable[t\&.Any] values)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
