.TH "optionx" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
optionx \- arguments counter 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'arghlp\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct option \fBoptlong\fP"
.br
.ti -1c
.RI "char \fBoptdesc\fP [\fBMAX_BUFF\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
arguments counter 
.br
 
.SH "Member Data Documentation"
.PP 
.SS "char optionx::optdesc"

.SS "struct option optionx::optlong"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
