.TH "packaging.markers.UndefinedComparison" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packaging.markers.UndefinedComparison
.SH SYNOPSIS
.br
.PP
.PP
Inherits ValueError\&.
.SH "Detailed Description"
.PP 

.PP
.nf
An invalid operation was attempted on a value that doesn't support it\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
