.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/utils/packaging.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/utils/packaging.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.utils\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.utils\&.packaging\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBpip\&._internal\&.utils\&.packaging\&.check_requires_python\fP (Optional[str] requires_python, Tuple[int,\&.\&.\&.] version_info)"
.br
.ti -1c
.RI "\fBRequirement\fP \fBpip\&._internal\&.utils\&.packaging\&.get_requirement\fP (str req_string)"
.br
.ti -1c
.RI "\fBNormalizedExtra\fP \fBpip\&._internal\&.utils\&.packaging\&.safe_extra\fP (str extra)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.packaging\&.NormalizedExtra\fP = NewType('NormalizedExtra', str)"
.br
.ti -1c
.RI "\fBpip\&._internal\&.utils\&.packaging\&.logger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
