.TH "packaging.markers.UndefinedEnvironmentName" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packaging.markers.UndefinedEnvironmentName
.SH SYNOPSIS
.br
.PP
.PP
Inherits ValueError\&.
.SH "Detailed Description"
.PP 

.PP
.nf
A name was attempted to be used that does not exist inside of the
environment\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
