.TH "packaging._elffile.EIClass" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packaging._elffile.EIClass
.SH SYNOPSIS
.br
.PP
.PP
Inherits enum\&.IntEnum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBC32\fP = 1"
.br
.ti -1c
.RI "int \fBC64\fP = 2"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int packaging\&._elffile\&.EIClass\&.C32 = 1\fC [static]\fP"

.SS "int packaging\&._elffile\&.EIClass\&.C64 = 2\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
