.TH "packaging" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packaging
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_elffile\fP"
.br
.ti -1c
.RI "namespace \fB_manylinux\fP"
.br
.ti -1c
.RI "namespace \fB_musllinux\fP"
.br
.ti -1c
.RI "namespace \fB_parser\fP"
.br
.ti -1c
.RI "namespace \fB_structures\fP"
.br
.ti -1c
.RI "namespace \fB_tokenizer\fP"
.br
.ti -1c
.RI "namespace \fBlicenses\fP"
.br
.ti -1c
.RI "namespace \fBmarkers\fP"
.br
.ti -1c
.RI "namespace \fBmetadata\fP"
.br
.ti -1c
.RI "namespace \fBrequirements\fP"
.br
.ti -1c
.RI "namespace \fBspecifiers\fP"
.br
.ti -1c
.RI "namespace \fBtags\fP"
.br
.ti -1c
.RI "namespace \fButils\fP"
.br
.ti -1c
.RI "namespace \fBversion\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
