.TH "packaging.markers.Environment" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packaging.markers.Environment
.SH SYNOPSIS
.br
.PP
.PP
Inherits TypedDict\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBimplementation_name\fP"
.br
.ti -1c
.RI "str \fBimplementation_version\fP"
.br
.ti -1c
.RI "str \fBos_name\fP"
.br
.ti -1c
.RI "str \fBplatform_machine\fP"
.br
.ti -1c
.RI "str \fBplatform_release\fP"
.br
.ti -1c
.RI "str \fBplatform_system\fP"
.br
.ti -1c
.RI "str \fBplatform_version\fP"
.br
.ti -1c
.RI "str \fBpython_full_version\fP"
.br
.ti -1c
.RI "str \fBplatform_python_implementation\fP"
.br
.ti -1c
.RI "str \fBpython_version\fP"
.br
.ti -1c
.RI "str \fBsys_platform\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "str packaging\&.markers\&.Environment\&.implementation_name\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.implementation_version\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.os_name\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.platform_machine\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.platform_python_implementation\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.platform_release\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.platform_system\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.platform_version\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.python_full_version\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.python_version\fC [static]\fP"

.SS "str packaging\&.markers\&.Environment\&.sys_platform\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
