.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/styles/paraiso_light.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pygments/styles/paraiso_light.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpygments\&.styles\&.paraiso_light\&.ParaisoLightStyle\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpygments\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.styles\fP"
.br
.ti -1c
.RI "namespace \fBpygments\&.styles\&.paraiso_light\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.BACKGROUND\fP = '#e7e9db'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.CURRENT_LINE\fP = '#b9b6b0'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.SELECTION\fP = '#a39e9b'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.FOREGROUND\fP = '#2f1e2e'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.COMMENT\fP = '#8d8687'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.RED\fP = '#ef6155'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.ORANGE\fP = '#f99b15'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.YELLOW\fP = '#fec418'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.GREEN\fP = '#48b685'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.AQUA\fP = '#5bc4bf'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.BLUE\fP = '#06b6ef'"
.br
.ti -1c
.RI "str \fBpygments\&.styles\&.paraiso_light\&.PURPLE\fP = '#815ba4'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
