.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/waitress/parser.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/waitress/parser.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwaitress\&.parser\&.ParsingError\fP"
.br
.ti -1c
.RI "class \fBwaitress\&.parser\&.TransferEncodingNotImplemented\fP"
.br
.ti -1c
.RI "class \fBwaitress\&.parser\&.HTTPRequestParser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwaitress\fP"
.br
.ti -1c
.RI "namespace \fBwaitress\&.parser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwaitress\&.parser\&.unquote_bytes_to_wsgi\fP (bytestring)"
.br
.ti -1c
.RI "\fBwaitress\&.parser\&.split_uri\fP (uri)"
.br
.ti -1c
.RI "\fBwaitress\&.parser\&.get_header_lines\fP (header)"
.br
.ti -1c
.RI "\fBwaitress\&.parser\&.crack_first_line\fP (line)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBwaitress\&.parser\&.first_line_re\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
