.TH "pip._vendor.rich.text.Text" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.text.Text
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBtext\fP='', Union[str, \fBStyle\fP] \fBstyle\fP='', *Optional['JustifyMethod'] \fBjustify\fP=None, Optional['OverflowMethod'] overflow=None, Optional[bool] \fBno_wrap\fP=None, str \fBend\fP='\\n', Optional[int] \fBtab_size\fP=None, Optional[List[\fBSpan\fP]] \fBspans\fP=None)"
.br
.ti -1c
.RI "int \fB__len__\fP (self)"
.br
.ti -1c
.RI "bool \fB__bool__\fP (self)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "'Text' \fB__add__\fP (self, Any other)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, object other)"
.br
.ti -1c
.RI "bool \fB__contains__\fP (self, object other)"
.br
.ti -1c
.RI "'Text' \fB__getitem__\fP (self, Union[int, slice] slice)"
.br
.ti -1c
.RI "int \fBcell_len\fP (self)"
.br
.ti -1c
.RI "str \fBmarkup\fP (self)"
.br
.ti -1c
.RI "'Text' \fBfrom_markup\fP (cls, str \fBtext\fP, *Union[str, \fBStyle\fP] \fBstyle\fP='', bool emoji=True, Optional[EmojiVariant] emoji_variant=None, Optional['JustifyMethod'] \fBjustify\fP=None, Optional['OverflowMethod'] overflow=None, str \fBend\fP='\\n')"
.br
.ti -1c
.RI "'Text' \fBfrom_ansi\fP (cls, str \fBtext\fP, *Union[str, \fBStyle\fP] \fBstyle\fP='', Optional['JustifyMethod'] \fBjustify\fP=None, Optional['OverflowMethod'] overflow=None, Optional[bool] \fBno_wrap\fP=None, str \fBend\fP='\\n', Optional[int] \fBtab_size\fP=8)"
.br
.ti -1c
.RI "'Text' \fBstyled\fP (cls, str \fBtext\fP, StyleType \fBstyle\fP='', *Optional['JustifyMethod'] \fBjustify\fP=None, Optional['OverflowMethod'] overflow=None)"
.br
.ti -1c
.RI "'Text' \fBassemble\fP (cls, *Union[str, 'Text', Tuple[str, StyleType]] parts, Union[str, \fBStyle\fP] \fBstyle\fP='', Optional['JustifyMethod'] \fBjustify\fP=None, Optional['OverflowMethod'] overflow=None, Optional[bool] \fBno_wrap\fP=None, str \fBend\fP='\\n', int \fBtab_size\fP=8, Optional[Dict[str, Any]] meta=None)"
.br
.ti -1c
.RI "str \fBplain\fP (self)"
.br
.ti -1c
.RI "None \fBplain\fP (self, str new_text)"
.br
.ti -1c
.RI "List[\fBSpan\fP] \fBspans\fP (self)"
.br
.ti -1c
.RI "None \fBspans\fP (self, List[\fBSpan\fP] spans)"
.br
.ti -1c
.RI "'Text' \fBblank_copy\fP (self, str \fBplain\fP='')"
.br
.ti -1c
.RI "'Text' \fBcopy\fP (self)"
.br
.ti -1c
.RI "None \fBstylize\fP (self, Union[str, \fBStyle\fP] \fBstyle\fP, int start=0, Optional[int] \fBend\fP=None)"
.br
.ti -1c
.RI "None \fBstylize_before\fP (self, Union[str, \fBStyle\fP] \fBstyle\fP, int start=0, Optional[int] \fBend\fP=None)"
.br
.ti -1c
.RI "None \fBapply_meta\fP (self, Dict[str, Any] meta, int start=0, Optional[int] \fBend\fP=None)"
.br
.ti -1c
.RI "'Text' \fBon\fP (self, Optional[Dict[str, Any]] meta=None, **Any handlers)"
.br
.ti -1c
.RI "None \fBremove_suffix\fP (self, str suffix)"
.br
.ti -1c
.RI "\fBStyle\fP \fBget_style_at_offset\fP (self, 'Console' \fBconsole\fP, int offset)"
.br
.ti -1c
.RI "None \fBextend_style\fP (self, int spaces)"
.br
.ti -1c
.RI "int \fBhighlight_regex\fP (self, str re_highlight, Optional[Union[\fBGetStyleCallable\fP, StyleType]] \fBstyle\fP=None, *str style_prefix='')"
.br
.ti -1c
.RI "int \fBhighlight_words\fP (self, Iterable[str] words, Union[str, \fBStyle\fP] \fBstyle\fP, *bool case_sensitive=True)"
.br
.ti -1c
.RI "None \fBrstrip\fP (self)"
.br
.ti -1c
.RI "None \fBrstrip_end\fP (self, int size)"
.br
.ti -1c
.RI "None \fBset_length\fP (self, int new_length)"
.br
.ti -1c
.RI "Iterable[\fBSegment\fP] \fB__rich_console__\fP (self, 'Console' \fBconsole\fP, 'ConsoleOptions' options)"
.br
.ti -1c
.RI "\fBMeasurement\fP \fB__rich_measure__\fP (self, 'Console' \fBconsole\fP, 'ConsoleOptions' options)"
.br
.ti -1c
.RI "Iterable['Segment'] \fBrender\fP (self, 'Console' \fBconsole\fP, str \fBend\fP='')"
.br
.ti -1c
.RI "'Text' \fBjoin\fP (self, Iterable['Text'] lines)"
.br
.ti -1c
.RI "None \fBexpand_tabs\fP (self, Optional[int] \fBtab_size\fP=None)"
.br
.ti -1c
.RI "None \fBtruncate\fP (self, int max_width, *Optional['OverflowMethod'] overflow=None, bool \fBpad\fP=False)"
.br
.ti -1c
.RI "None \fBpad\fP (self, int count, str character=' ')"
.br
.ti -1c
.RI "None \fBpad_left\fP (self, int count, str character=' ')"
.br
.ti -1c
.RI "None \fBpad_right\fP (self, int count, str character=' ')"
.br
.ti -1c
.RI "None \fBalign\fP (self, AlignMethod align, int width, str character=' ')"
.br
.ti -1c
.RI "'Text' \fBappend\fP (self, Union['Text', str] \fBtext\fP, Optional[Union[str, 'Style']] \fBstyle\fP=None)"
.br
.ti -1c
.RI "'Text' \fBappend_text\fP (self, 'Text' \fBtext\fP)"
.br
.ti -1c
.RI "'Text' \fBappend_tokens\fP (self, Iterable[Tuple[str, Optional[StyleType]]] tokens)"
.br
.ti -1c
.RI "None \fBcopy_styles\fP (self, 'Text' \fBtext\fP)"
.br
.ti -1c
.RI "\fBLines\fP \fBsplit\fP (self, str separator='\\n', *bool include_separator=False, bool allow_blank=False)"
.br
.ti -1c
.RI "\fBLines\fP \fBdivide\fP (self, Iterable[int] offsets)"
.br
.ti -1c
.RI "None \fBright_crop\fP (self, int amount=1)"
.br
.ti -1c
.RI "\fBLines\fP \fBwrap\fP (self, 'Console' \fBconsole\fP, int width, *Optional['JustifyMethod'] \fBjustify\fP=None, Optional['OverflowMethod'] overflow=None, int \fBtab_size\fP=8, Optional[bool] \fBno_wrap\fP=None)"
.br
.ti -1c
.RI "\fBLines\fP \fBfit\fP (self, int width)"
.br
.ti -1c
.RI "int \fBdetect_indentation\fP (self)"
.br
.ti -1c
.RI "'Text' \fBwith_indent_guides\fP (self, Optional[int] indent_size=None, *str character='│', StyleType \fBstyle\fP='dim green')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBno_wrap\fP"
.br
.ti -1c
.RI "\fBend\fP"
.br
.ti -1c
.RI "\fBtab_size\fP"
.br
.ti -1c
.RI "\fBplain\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "None \fB_trim_spans\fP (self)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP
.in +1c
.ti -1c
.RI "Dict[str, str] \fB_repr_mimebundle_\fP ('ConsoleRenderable' self, Sequence[str] include, Sequence[str] exclude, **Any kwargs)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_text\fP"
.br
.ti -1c
.RI "\fB_length\fP"
.br
.ti -1c
.RI "\fB_spans\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Text with color / style\&.

Args:
    text (str, optional): Default unstyled text\&. Defaults to ''\&.
    style (Union[str, Style], optional): Base style for text\&. Defaults to ''\&.
    justify (str, optional): Justify method: 'left', 'center', 'full', 'right'\&. Defaults to None\&.
    overflow (str, optional): Overflow method: 'crop', 'fold', 'ellipsis'\&. Defaults to None\&.
    no_wrap (bool, optional): Disable text wrapping, or None for default\&. Defaults to None\&.
    end (str, optional): Character to end text with\&. Defaults to '\\\\\\\\n'\&.
    tab_size (int): Number of spaces per tab, or ``None`` to use ``console\&.tab_size``\&. Defaults to None\&.
    spans (List[Span], optional)\&. A list of predefined style spans\&. Defaults to None\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.__init__ ( self, str  text = \fC''\fP, Union[str, \fBStyle\fP]  style = \fC''\fP, *Optional['JustifyMethod']  justify = \fCNone\fP, Optional['OverflowMethod']  overflow = \fCNone\fP, Optional[bool]  no_wrap = \fCNone\fP, str  end = \fC'\\n'\fP, Optional[int]  tab_size = \fCNone\fP, Optional[List[\fBSpan\fP]]  spans = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.__add__ ( self, Any other)"

.SS " bool pip\&._vendor\&.rich\&.text\&.Text\&.__bool__ ( self)"

.SS " bool pip\&._vendor\&.rich\&.text\&.Text\&.__contains__ ( self, object other)"

.SS " bool pip\&._vendor\&.rich\&.text\&.Text\&.__eq__ ( self, object other)"

.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.__getitem__ ( self, Union[int, slice] slice)"

.SS " int pip\&._vendor\&.rich\&.text\&.Text\&.__len__ ( self)"

.SS " str pip\&._vendor\&.rich\&.text\&.Text\&.__repr__ ( self)"

.SS " Iterable[\fBSegment\fP] pip\&._vendor\&.rich\&.text\&.Text\&.__rich_console__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.SS " \fBMeasurement\fP pip\&._vendor\&.rich\&.text\&.Text\&.__rich_measure__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.SS " str pip\&._vendor\&.rich\&.text\&.Text\&.__str__ ( self)"

.SS " None pip\&._vendor\&.rich\&.text\&.Text\&._trim_spans ( self)\fC [protected]\fP"

.PP
.nf
Remove or modify any spans that are over the end of the text\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.align ( self, AlignMethod align, int width, str  character = \fC' '\fP)"

.PP
.nf
Align text to a given width\&.

Args:
    align (AlignMethod): One of 'left', 'center', or 'right'\&.
    width (int): Desired width\&.
    character (str, optional): Character to pad with\&. Defaults to ' '\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.append ( self, Union['Text', str] text, Optional[Union[str, 'Style']]  style = \fCNone\fP)"

.PP
.nf
Add text with an optional style\&.

Args:
    text (Union[Text, str]): A str or Text to append\&.
    style (str, optional): A style name\&. Defaults to None\&.

Returns:
    Text: Returns self for chaining\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.append_text ( self, 'Text' text)"

.PP
.nf
Append another Text instance\&. This method is more performant that Text\&.append, but
only works for Text\&.

Args:
    text (Text): The Text instance to append to this instance\&.

Returns:
    Text: Returns self for chaining\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.append_tokens ( self, Iterable[Tuple[str, Optional[StyleType]]]
     tokens)"

.PP
.nf
Append iterable of str and style\&. Style may be a Style instance or a str style definition\&.

Args:
    tokens (Iterable[Tuple[str, Optional[StyleType]]]): An iterable of tuples containing str content and style\&.

Returns:
    Text: Returns self for chaining\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.apply_meta ( self, Dict[str, Any] meta, int  start = \fC0\fP, Optional[int]  end = \fCNone\fP)"

.PP
.nf
Apply metadata to the text, or a portion of the text\&.

Args:
    meta (Dict[str, Any]): A dict of meta information\&.
    start (int): Start offset (negative indexing is supported)\&. Defaults to 0\&.
    end (Optional[int], optional): End offset (negative indexing is supported), or None for end of text\&. Defaults to None\&.
.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.assemble ( cls, *Union[str, 'Text', Tuple[str, StyleType]] parts, Union[str, \fBStyle\fP]  style = \fC''\fP, Optional['JustifyMethod']  justify = \fCNone\fP, Optional['OverflowMethod']  overflow = \fCNone\fP, Optional[bool]  no_wrap = \fCNone\fP, str  end = \fC'\\n'\fP, int  tab_size = \fC8\fP, Optional[Dict[str, Any]]  meta = \fCNone\fP)"

.PP
.nf
Construct a text instance by combining a sequence of strings with optional styles\&.
The positional arguments should be either strings, or a tuple of string + style\&.

Args:
    style (Union[str, Style], optional): Base style for text\&. Defaults to ''\&.
    justify (str, optional): Justify method: 'left', 'center', 'full', 'right'\&. Defaults to None\&.
    overflow (str, optional): Overflow method: 'crop', 'fold', 'ellipsis'\&. Defaults to None\&.
    no_wrap (bool, optional): Disable text wrapping, or None for default\&. Defaults to None\&.
    end (str, optional): Character to end text with\&. Defaults to '\\\\\\\\n'\&.
    tab_size (int): Number of spaces per tab, or ``None`` to use ``console\&.tab_size``\&. Defaults to None\&.
    meta (Dict[str, Any], optional)\&. Meta data to apply to text, or None for no meta data\&. Default to None

Returns:
    Text: A new text instance\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.blank_copy ( self, str  plain = \fC''\fP)"

.PP
.nf
Return a new Text instance with copied metadata (but not the string or spans)\&.
.fi
.PP
 
.SS " int pip\&._vendor\&.rich\&.text\&.Text\&.cell_len ( self)"

.PP
.nf
Get the number of cells required to render this text\&.
.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.copy ( self)"

.PP
.nf
Return a copy of this instance\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.copy_styles ( self, 'Text' text)"

.PP
.nf
Copy styles from another Text instance\&.

Args:
    text (Text): A Text instance to copy styles from, must be the same length\&.

.fi
.PP
 
.SS " int pip\&._vendor\&.rich\&.text\&.Text\&.detect_indentation ( self)"

.PP
.nf
Auto-detect indentation of code\&.

Returns:
    int: Number of spaces used to indent code\&.

.fi
.PP
 
.SS " \fBLines\fP pip\&._vendor\&.rich\&.text\&.Text\&.divide ( self, Iterable[int] offsets)"

.PP
.nf
Divide text in to a number of lines at given offsets\&.

Args:
    offsets (Iterable[int]): Offsets used to divide text\&.

Returns:
    Lines: New RichText instances between offsets\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.expand_tabs ( self, Optional[int]  tab_size = \fCNone\fP)"

.PP
.nf
Converts tabs to spaces\&.

Args:
    tab_size (int, optional): Size of tabs\&. Defaults to 8\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.extend_style ( self, int spaces)"

.PP
.nf
Extend the Text given number of spaces where the spaces have the same style as the last character\&.

Args:
    spaces (int): Number of spaces to add to the Text\&.

.fi
.PP
 
.SS " \fBLines\fP pip\&._vendor\&.rich\&.text\&.Text\&.fit ( self, int width)"

.PP
.nf
Fit the text in to given width by chopping in to lines\&.

Args:
    width (int): Maximum characters in a line\&.

Returns:
    Lines: Lines container\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.from_ansi ( cls, str text, *Union[str, \fBStyle\fP]  style = \fC''\fP, Optional['JustifyMethod']  justify = \fCNone\fP, Optional['OverflowMethod']  overflow = \fCNone\fP, Optional[bool]  no_wrap = \fCNone\fP, str  end = \fC'\\n'\fP, Optional[int]  tab_size = \fC8\fP)"

.PP
.nf
Create a Text object from a string containing ANSI escape codes\&.

Args:
    text (str): A string containing escape codes\&.
    style (Union[str, Style], optional): Base style for text\&. Defaults to ''\&.
    justify (str, optional): Justify method: 'left', 'center', 'full', 'right'\&. Defaults to None\&.
    overflow (str, optional): Overflow method: 'crop', 'fold', 'ellipsis'\&. Defaults to None\&.
    no_wrap (bool, optional): Disable text wrapping, or None for default\&. Defaults to None\&.
    end (str, optional): Character to end text with\&. Defaults to '\\\\\\\\n'\&.
    tab_size (int): Number of spaces per tab, or ``None`` to use ``console\&.tab_size``\&. Defaults to None\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.from_markup ( cls, str text, *Union[str, \fBStyle\fP]  style = \fC''\fP, bool  emoji = \fCTrue\fP, Optional[EmojiVariant]  emoji_variant = \fCNone\fP, Optional['JustifyMethod']  justify = \fCNone\fP, Optional['OverflowMethod']  overflow = \fCNone\fP, str  end = \fC'\\n'\fP)"

.PP
.nf
Create Text instance from markup\&.

Args:
    text (str): A string containing console markup\&.
    style (Union[str, Style], optional): Base style for text\&. Defaults to ''\&.
    emoji (bool, optional): Also render emoji code\&. Defaults to True\&.
    emoji_variant (str, optional): Optional emoji variant, either 'text' or 'emoji'\&. Defaults to None\&.
    justify (str, optional): Justify method: 'left', 'center', 'full', 'right'\&. Defaults to None\&.
    overflow (str, optional): Overflow method: 'crop', 'fold', 'ellipsis'\&. Defaults to None\&.
    end (str, optional): Character to end text with\&. Defaults to '\\\\\\\\n'\&.

Returns:
    Text: A Text instance with markup rendered\&.

.fi
.PP
 
.SS " \fBStyle\fP pip\&._vendor\&.rich\&.text\&.Text\&.get_style_at_offset ( self, 'Console' console, int offset)"

.PP
.nf
Get the style of a character at give offset\&.

Args:
    console (~Console): Console where text will be rendered\&.
    offset (int): Offset in to text (negative indexing supported)

Returns:
    Style: A Style instance\&.

.fi
.PP
 
.SS " int pip\&._vendor\&.rich\&.text\&.Text\&.highlight_regex ( self, str re_highlight, Optional[Union[\fBGetStyleCallable\fP, StyleType]]  style = \fCNone\fP, *str  style_prefix = \fC''\fP)"

.PP
.nf
Highlight text with a regular expression, where group names are
translated to styles\&.

Args:
    re_highlight (str): A regular expression\&.
    style (Union[GetStyleCallable, StyleType]): Optional style to apply to whole match, or a callable
        which accepts the matched text and returns a style\&. Defaults to None\&.
    style_prefix (str, optional): Optional prefix to add to style group names\&.

Returns:
    int: Number of regex matches

.fi
.PP
 
.SS " int pip\&._vendor\&.rich\&.text\&.Text\&.highlight_words ( self, Iterable[str] words, Union[str, \fBStyle\fP] style, *bool  case_sensitive = \fCTrue\fP)"

.PP
.nf
Highlight words with a style\&.

Args:
    words (Iterable[str]): Words to highlight\&.
    style (Union[str, Style]): Style to apply\&.
    case_sensitive (bool, optional): Enable case sensitive matching\&. Defaults to True\&.

Returns:
    int: Number of words highlighted\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.join ( self, Iterable['Text'] lines)"

.PP
.nf
Join text together with this instance as the separator\&.

Args:
    lines (Iterable[Text]): An iterable of Text instances to join\&.

Returns:
    Text: A new text instance containing join text\&.

.fi
.PP
 
.SS " str pip\&._vendor\&.rich\&.text\&.Text\&.markup ( self)"

.PP
.nf
Get console markup to render this Text\&.

Returns:
    str: A string potentially creating markup tags\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.on ( self, Optional[Dict[str, Any]]  meta = \fCNone\fP, **Any handlers)"

.PP
.nf
Apply event handlers (used by Textual project)\&.

Example:
    >>> from rich\&.text import Text
    >>> text = Text('hello world')
    >>> text\&.on(click='view\&.toggle('world')')

Args:
    meta (Dict[str, Any]): Mapping of meta information\&.
    **handlers: Keyword args are prefixed with '@' to defined handlers\&.

Returns:
    Text: Self is returned to method may be chained\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.pad ( self, int count, str  character = \fC' '\fP)"

.PP
.nf
Pad left and right with a given number of characters\&.

Args:
    count (int): Width of padding\&.
    character (str): The character to pad with\&. Must be a string of length 1\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.pad_left ( self, int count, str  character = \fC' '\fP)"

.PP
.nf
Pad the left with a given character\&.

Args:
    count (int): Number of characters to pad\&.
    character (str, optional): Character to pad with\&. Defaults to ' '\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.pad_right ( self, int count, str  character = \fC' '\fP)"

.PP
.nf
Pad the right with a given character\&.

Args:
    count (int): Number of characters to pad\&.
    character (str, optional): Character to pad with\&. Defaults to ' '\&.

.fi
.PP
 
.SS " str pip\&._vendor\&.rich\&.text\&.Text\&.plain ( self)"

.PP
.nf
Get the text as a single string\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.plain ( self, str new_text)"

.PP
.nf
Set the text to a new value\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.remove_suffix ( self, str suffix)"

.PP
.nf
Remove a suffix if it exists\&.

Args:
    suffix (str): Suffix to remove\&.

.fi
.PP
 
.SS " Iterable['Segment'] pip\&._vendor\&.rich\&.text\&.Text\&.render ( self, 'Console' console, str  end = \fC''\fP)"

.PP
.nf
Render the text as Segments\&.

Args:
    console (Console): Console instance\&.
    end (Optional[str], optional): Optional end character\&.

Returns:
    Iterable[Segment]: Result of render that may be written to the console\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.right_crop ( self, int  amount = \fC1\fP)"

.PP
.nf
Remove a number of characters from the end of the text\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.rstrip ( self)"

.PP
.nf
Strip whitespace from end of text\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.rstrip_end ( self, int size)"

.PP
.nf
Remove whitespace beyond a certain width at the end of the text\&.

Args:
    size (int): The desired size of the text\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.set_length ( self, int new_length)"

.PP
.nf
Set new length of the text, clipping or padding is required\&.
.fi
.PP
 
.SS " List[\fBSpan\fP] pip\&._vendor\&.rich\&.text\&.Text\&.spans ( self)"

.PP
.nf
Get a reference to the internal list of spans\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.spans ( self, List[\fBSpan\fP] spans)"

.PP
.nf
Set spans\&.
.fi
.PP
 
.SS " \fBLines\fP pip\&._vendor\&.rich\&.text\&.Text\&.split ( self, str  separator = \fC'\\n'\fP, *bool  include_separator = \fCFalse\fP, bool  allow_blank = \fCFalse\fP)"

.PP
.nf
Split rich text in to lines, preserving styles\&.

Args:
    separator (str, optional): String to split on\&. Defaults to '\\\\\\\\n'\&.
    include_separator (bool, optional): Include the separator in the lines\&. Defaults to False\&.
    allow_blank (bool, optional): Return a blank line if the text ends with a separator\&. Defaults to False\&.

Returns:
    List[RichText]: A list of rich text, one per line of the original\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.styled ( cls, str text, StyleType  style = \fC''\fP, *Optional['JustifyMethod']  justify = \fCNone\fP, Optional['OverflowMethod']  overflow = \fCNone\fP)"

.PP
.nf
Construct a Text instance with a pre-applied styled\&. A style applied in this way won't be used
to pad the text when it is justified\&.

Args:
    text (str): A string containing console markup\&.
    style (Union[str, Style]): Style to apply to the text\&. Defaults to ''\&.
    justify (str, optional): Justify method: 'left', 'center', 'full', 'right'\&. Defaults to None\&.
    overflow (str, optional): Overflow method: 'crop', 'fold', 'ellipsis'\&. Defaults to None\&.

Returns:
    Text: A text instance with a style applied to the entire string\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.stylize ( self, Union[str, \fBStyle\fP] style, int  start = \fC0\fP, Optional[int]  end = \fCNone\fP)"

.PP
.nf
Apply a style to the text, or a portion of the text\&.

Args:
    style (Union[str, Style]): Style instance or style definition to apply\&.
    start (int): Start offset (negative indexing is supported)\&. Defaults to 0\&.
    end (Optional[int], optional): End offset (negative indexing is supported), or None for end of text\&. Defaults to None\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.stylize_before ( self, Union[str, \fBStyle\fP] style, int  start = \fC0\fP, Optional[int]  end = \fCNone\fP)"

.PP
.nf
Apply a style to the text, or a portion of the text\&. Styles will be applied before other styles already present\&.

Args:
    style (Union[str, Style]): Style instance or style definition to apply\&.
    start (int): Start offset (negative indexing is supported)\&. Defaults to 0\&.
    end (Optional[int], optional): End offset (negative indexing is supported), or None for end of text\&. Defaults to None\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.text\&.Text\&.truncate ( self, int max_width, *Optional['OverflowMethod']  overflow = \fCNone\fP, bool  pad = \fCFalse\fP)"

.PP
.nf
Truncate text if it is longer that a given width\&.

Args:
    max_width (int): Maximum number of characters in text\&.
    overflow (str, optional): Overflow method: 'crop', 'fold', or 'ellipsis'\&. Defaults to None, to use self\&.overflow\&.
    pad (bool, optional): Pad with spaces if the length is less than max_width\&. Defaults to False\&.

.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.text\&.Text\&.with_indent_guides ( self, Optional[int]  indent_size = \fCNone\fP, *str  character = \fC'│'\fP, StyleType  style = \fC'dim green'\fP)"

.PP
.nf
Adds indent guide lines to text\&.

Args:
    indent_size (Optional[int]): Size of indentation, or None to auto detect\&. Defaults to None\&.
    character (str, optional): Character to use for indentation\&. Defaults to '│'\&.
    style (Union[Style, str], optional): Style of indent guides\&.

Returns:
    Text: New text with indentation guides\&.

.fi
.PP
 
.SS " \fBLines\fP pip\&._vendor\&.rich\&.text\&.Text\&.wrap ( self, 'Console' console, int width, *Optional['JustifyMethod']  justify = \fCNone\fP, Optional['OverflowMethod']  overflow = \fCNone\fP, int  tab_size = \fC8\fP, Optional[bool]  no_wrap = \fCNone\fP)"

.PP
.nf
Word wrap the text\&.

Args:
    console (Console): Console instance\&.
    width (int): Number of cells available per line\&.
    justify (str, optional): Justify method: 'default', 'left', 'center', 'full', 'right'\&. Defaults to 'default'\&.
    overflow (str, optional): Overflow method: 'crop', 'fold', or 'ellipsis'\&. Defaults to None\&.
    tab_size (int, optional): Default tab size\&. Defaults to 8\&.
    no_wrap (bool, optional): Disable wrapping, Defaults to False\&.

Returns:
    Lines: Number of lines\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.text\&.Text\&._length\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.text\&.Text\&._spans\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.text\&.Text\&._text\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.text\&.Text\&.end"

.SS "pip\&._vendor\&.rich\&.text\&.Text\&.no_wrap"

.SS "pip\&._vendor\&.rich\&.text\&.Text\&.plain"

.SS "pip\&._vendor\&.rich\&.text\&.Text\&.style"

.SS "pip\&._vendor\&.rich\&.text\&.Text\&.tab_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
