.TH "pip._vendor.urllib3.contrib._securetransport.bindings.SecurityConst" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.contrib._securetransport.bindings.SecurityConst
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBkSSLSessionOptionBreakOnServerAuth\fP = 0"
.br
.ti -1c
.RI "int \fBkSSLProtocol2\fP = 1"
.br
.ti -1c
.RI "int \fBkSSLProtocol3\fP = 2"
.br
.ti -1c
.RI "int \fBkTLSProtocol1\fP = 4"
.br
.ti -1c
.RI "int \fBkTLSProtocol11\fP = 7"
.br
.ti -1c
.RI "int \fBkTLSProtocol12\fP = 8"
.br
.ti -1c
.RI "int \fBkTLSProtocol13\fP = 10"
.br
.ti -1c
.RI "int \fBkTLSProtocolMaxSupported\fP = 999"
.br
.ti -1c
.RI "int \fBkSSLClientSide\fP = 1"
.br
.ti -1c
.RI "int \fBkSSLStreamType\fP = 0"
.br
.ti -1c
.RI "int \fBkSecFormatPEMSequence\fP = 10"
.br
.ti -1c
.RI "int \fBkSecTrustResultInvalid\fP = 0"
.br
.ti -1c
.RI "int \fBkSecTrustResultProceed\fP = 1"
.br
.ti -1c
.RI "int \fBkSecTrustResultDeny\fP = 3"
.br
.ti -1c
.RI "int \fBkSecTrustResultUnspecified\fP = 4"
.br
.ti -1c
.RI "int \fBkSecTrustResultRecoverableTrustFailure\fP = 5"
.br
.ti -1c
.RI "int \fBkSecTrustResultFatalTrustFailure\fP = 6"
.br
.ti -1c
.RI "int \fBkSecTrustResultOtherError\fP = 7"
.br
.ti -1c
.RI "int \fBerrSSLProtocol\fP = \-9800"
.br
.ti -1c
.RI "int \fBerrSSLWouldBlock\fP = \-9803"
.br
.ti -1c
.RI "int \fBerrSSLClosedGraceful\fP = \-9805"
.br
.ti -1c
.RI "int \fBerrSSLClosedNoNotify\fP = \-9816"
.br
.ti -1c
.RI "int \fBerrSSLClosedAbort\fP = \-9806"
.br
.ti -1c
.RI "int \fBerrSSLXCertChainInvalid\fP = \-9807"
.br
.ti -1c
.RI "int \fBerrSSLCrypto\fP = \-9809"
.br
.ti -1c
.RI "int \fBerrSSLInternal\fP = \-9810"
.br
.ti -1c
.RI "int \fBerrSSLCertExpired\fP = \-9814"
.br
.ti -1c
.RI "int \fBerrSSLCertNotYetValid\fP = \-9815"
.br
.ti -1c
.RI "int \fBerrSSLUnknownRootCert\fP = \-9812"
.br
.ti -1c
.RI "int \fBerrSSLNoRootCert\fP = \-9813"
.br
.ti -1c
.RI "int \fBerrSSLHostNameMismatch\fP = \-9843"
.br
.ti -1c
.RI "int \fBerrSSLPeerHandshakeFail\fP = \-9824"
.br
.ti -1c
.RI "int \fBerrSSLPeerUserCancelled\fP = \-9839"
.br
.ti -1c
.RI "int \fBerrSSLWeakPeerEphemeralDHKey\fP = \-9850"
.br
.ti -1c
.RI "int \fBerrSSLServerAuthCompleted\fP = \-9841"
.br
.ti -1c
.RI "int \fBerrSSLRecordOverflow\fP = \-9847"
.br
.ti -1c
.RI "int \fBerrSecVerifyFailed\fP = \-67808"
.br
.ti -1c
.RI "int \fBerrSecNoTrustSettings\fP = \-25263"
.br
.ti -1c
.RI "int \fBerrSecItemNotFound\fP = \-25300"
.br
.ti -1c
.RI "int \fBerrSecInvalidTrustSettings\fP = \-25262"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384\fP = 0xC02C"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\fP = 0xC030"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256\fP = 0xC02B"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\fP = 0xC02F"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256\fP = 0xCCA9"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256\fP = 0xCCA8"
.br
.ti -1c
.RI "int \fBTLS_DHE_RSA_WITH_AES_256_GCM_SHA384\fP = 0x009F"
.br
.ti -1c
.RI "int \fBTLS_DHE_RSA_WITH_AES_128_GCM_SHA256\fP = 0x009E"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384\fP = 0xC024"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384\fP = 0xC028"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA\fP = 0xC00A"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_RSA_WITH_AES_256_CBC_SHA\fP = 0xC014"
.br
.ti -1c
.RI "int \fBTLS_DHE_RSA_WITH_AES_256_CBC_SHA256\fP = 0x006B"
.br
.ti -1c
.RI "int \fBTLS_DHE_RSA_WITH_AES_256_CBC_SHA\fP = 0x0039"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256\fP = 0xC023"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256\fP = 0xC027"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA\fP = 0xC009"
.br
.ti -1c
.RI "int \fBTLS_ECDHE_RSA_WITH_AES_128_CBC_SHA\fP = 0xC013"
.br
.ti -1c
.RI "int \fBTLS_DHE_RSA_WITH_AES_128_CBC_SHA256\fP = 0x0067"
.br
.ti -1c
.RI "int \fBTLS_DHE_RSA_WITH_AES_128_CBC_SHA\fP = 0x0033"
.br
.ti -1c
.RI "int \fBTLS_RSA_WITH_AES_256_GCM_SHA384\fP = 0x009D"
.br
.ti -1c
.RI "int \fBTLS_RSA_WITH_AES_128_GCM_SHA256\fP = 0x009C"
.br
.ti -1c
.RI "int \fBTLS_RSA_WITH_AES_256_CBC_SHA256\fP = 0x003D"
.br
.ti -1c
.RI "int \fBTLS_RSA_WITH_AES_128_CBC_SHA256\fP = 0x003C"
.br
.ti -1c
.RI "int \fBTLS_RSA_WITH_AES_256_CBC_SHA\fP = 0x0035"
.br
.ti -1c
.RI "int \fBTLS_RSA_WITH_AES_128_CBC_SHA\fP = 0x002F"
.br
.ti -1c
.RI "int \fBTLS_AES_128_GCM_SHA256\fP = 0x1301"
.br
.ti -1c
.RI "int \fBTLS_AES_256_GCM_SHA384\fP = 0x1302"
.br
.ti -1c
.RI "int \fBTLS_AES_128_CCM_8_SHA256\fP = 0x1305"
.br
.ti -1c
.RI "int \fBTLS_AES_128_CCM_SHA256\fP = 0x1304"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A class object that acts as essentially a namespace for Security constants\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSecInvalidTrustSettings = \-25262\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSecItemNotFound = \-25300\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSecNoTrustSettings = \-25263\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSecVerifyFailed = \-67808\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLCertExpired = \-9814\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLCertNotYetValid = \-9815\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLClosedAbort = \-9806\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLClosedGraceful = \-9805\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLClosedNoNotify = \-9816\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLCrypto = \-9809\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLHostNameMismatch = \-9843\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLInternal = \-9810\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLNoRootCert = \-9813\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLPeerHandshakeFail = \-9824\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLPeerUserCancelled = \-9839\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLProtocol = \-9800\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLRecordOverflow = \-9847\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLServerAuthCompleted = \-9841\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLUnknownRootCert = \-9812\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLWeakPeerEphemeralDHKey = \-9850\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLWouldBlock = \-9803\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.errSSLXCertChainInvalid = \-9807\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSecFormatPEMSequence = 10\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSecTrustResultDeny = 3\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSecTrustResultFatalTrustFailure = 6\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSecTrustResultInvalid = 0\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSecTrustResultOtherError = 7\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSecTrustResultProceed = 1\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSecTrustResultRecoverableTrustFailure = 5\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSecTrustResultUnspecified = 4\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSSLClientSide = 1\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSSLProtocol2 = 1\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSSLProtocol3 = 2\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSSLSessionOptionBreakOnServerAuth = 0\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kSSLStreamType = 0\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kTLSProtocol1 = 4\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kTLSProtocol11 = 7\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kTLSProtocol12 = 8\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kTLSProtocol13 = 10\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.kTLSProtocolMaxSupported = 999\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_AES_128_CCM_8_SHA256 = 0x1305\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_AES_128_CCM_SHA256 = 0x1304\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_AES_128_GCM_SHA256 = 0x1301\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_AES_256_GCM_SHA384 = 0x1302\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 0x0033\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 0x0067\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = 0x009E\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 0x0039\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 0x006B\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 0x009F\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 0xC009\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = 0xC023\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 0xC02B\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 0xC00A\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = 0xC024\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 0xC02C\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = 0xCCA9\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 0xC013\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = 0xC027\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 0xC02F\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 0xC014\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = 0xC028\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 0xC030\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 0xCCA8\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_RSA_WITH_AES_128_CBC_SHA = 0x002F\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_RSA_WITH_AES_128_CBC_SHA256 = 0x003C\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_RSA_WITH_AES_128_GCM_SHA256 = 0x009C\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_RSA_WITH_AES_256_CBC_SHA = 0x0035\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_RSA_WITH_AES_256_CBC_SHA256 = 0x003D\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&._securetransport\&.bindings\&.SecurityConst\&.TLS_RSA_WITH_AES_256_GCM_SHA384 = 0x009D\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
