.TH "pip._vendor.urllib3.connection.DummyConnection" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.connection.DummyConnection
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Used to detect a failed ConnectionCls import\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
