.TH "pip._vendor.distlib.manifest" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.manifest
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBManifest\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fB_COLLAPSE_PATTERN\fP = re\&.compile('\\\\\\\\w*\\n', re\&.M)"
.br
.ti -1c
.RI "\fB_COMMENTED_LINE\fP = re\&.compile('#\&.*?(?=\\n)|\\n(?=$)', re\&.M | re\&.S)"
.br
.ti -1c
.RI "\fB_PYTHON_VERSION\fP = sys\&.version_info[:2]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class representing the list of files in a distribution\&.

Equivalent to distutils\&.filelist, but fixes some problems\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.manifest\&._COLLAPSE_PATTERN = re\&.compile('\\\\\\\\w*\\n', re\&.M)\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.manifest\&._COMMENTED_LINE = re\&.compile('#\&.*?(?=\\n)|\\n(?=$)', re\&.M | re\&.S)\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.manifest\&._PYTHON_VERSION = sys\&.version_info[:2]\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.manifest\&.logger = logging\&.getLogger(__name__)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
