.TH "pip._vendor.platformdirs.macos" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.platformdirs.macos
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMacOS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
macOS\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
