.TH "pip._vendor.urllib3.response.GzipDecoderState" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.response.GzipDecoderState
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBFIRST_MEMBER\fP = 0"
.br
.ti -1c
.RI "int \fBOTHER_MEMBERS\fP = 1"
.br
.ti -1c
.RI "int \fBSWALLOW_DATA\fP = 2"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int pip\&._vendor\&.urllib3\&.response\&.GzipDecoderState\&.FIRST_MEMBER = 0\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.response\&.GzipDecoderState\&.OTHER_MEMBERS = 1\fC [static]\fP"

.SS "int pip\&._vendor\&.urllib3\&.response\&.GzipDecoderState\&.SWALLOW_DATA = 2\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
