.TH "pip._vendor.urllib3.contrib._appengine_environ" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.contrib._appengine_environ
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBis_appengine\fP ()"
.br
.ti -1c
.RI "\fBis_appengine_sandbox\fP ()"
.br
.ti -1c
.RI "\fBis_local_appengine\fP ()"
.br
.ti -1c
.RI "\fBis_prod_appengine\fP ()"
.br
.ti -1c
.RI "\fBis_prod_appengine_mvms\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This module provides means to detect the App Engine environment\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.contrib\&._appengine_environ\&.is_appengine ()"

.SS "pip\&._vendor\&.urllib3\&.contrib\&._appengine_environ\&.is_appengine_sandbox ()"

.PP
.nf
Reports if the app is running in the first generation sandbox\&.

The second generation runtimes are technically still in a sandbox, but it
is much less restrictive, so generally you shouldn't need to check for it\&.
see https://cloud\&.google\&.com/appengine/docs/standard/runtimes

.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.contrib\&._appengine_environ\&.is_local_appengine ()"

.SS "pip\&._vendor\&.urllib3\&.contrib\&._appengine_environ\&.is_prod_appengine ()"

.SS "pip\&._vendor\&.urllib3\&.contrib\&._appengine_environ\&.is_prod_appengine_mvms ()"

.PP
.nf
Deprecated\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
