.TH "pip._vendor.rich.styled" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.styled
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStyled\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpanel\fP = \fBStyled\fP(\fBPanel\fP('hello'), 'on blue')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.styled\&.panel = \fBStyled\fP(\fBPanel\fP('hello'), 'on blue')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
