.TH "pip._vendor.rich.live" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.live
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_RefreshThread\fP"
.br
.ti -1c
.RI "class \fBLive\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconsole\fP = \fBConsole\fP()"
.br
.ti -1c
.RI "\fBsyntax\fP"
.br
.ti -1c
.RI "\fBtable\fP = \fBTable\fP('foo', 'bar', 'baz')"
.br
.ti -1c
.RI "list \fBprogress_renderables\fP"
.br
.ti -1c
.RI "\fBexamples\fP = cycle(\fBprogress_renderables\fP)"
.br
.ti -1c
.RI "list \fBexchanges\fP"
.br
.ti -1c
.RI "dict \fBexchange_rate_dict\fP = {}"
.br
.ti -1c
.RI "list \fBselect_exchange\fP = \fBexchanges\fP[index % len(\fBexchanges\fP)]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.live\&.console = \fBConsole\fP()"

.SS "pip\&._vendor\&.rich\&.live\&.examples = cycle(\fBprogress_renderables\fP)"

.SS "dict pip\&._vendor\&.rich\&.live\&.exchange_rate_dict = {}"

.SS "list pip\&._vendor\&.rich\&.live\&.exchanges"
\fBInitial value:\fP.PP
.nf
1 =  [
2         "SGD",
3         "MYR",
4         "EUR",
5         "USD",
6         "AUD",
7         "JPY",
8         "CNH",
9         "HKD",
10         "CAD",
11         "INR",
12         "DKK",
13         "GBP",
14         "RUB",
15         "NZD",
16         "MXN",
17         "IDR",
18         "TWD",
19         "THB",
20         "VND",
21     ]
.fi

.SS "list pip\&._vendor\&.rich\&.live\&.progress_renderables"
\fBInitial value:\fP.PP
.nf
1 =  [
2         "You can make the terminal shorter and taller to see the live table hide"
3         "Text may be printed while the progress bars are rendering\&.",
4         Panel("In fact, [i]any[/i] renderable will work"),
5         "Such as [magenta]tables[/]\&.\&.\&.",
6         table,
7         "Pretty printed structures\&.\&.\&.",
8         {"type": "example", "text": "Pretty printed"},
9         "Syntax\&.\&.\&.",
10         syntax,
11         Rule("Give it a try!"),
12     ]
.fi

.SS "list pip\&._vendor\&.rich\&.live\&.select_exchange = \fBexchanges\fP[index % len(\fBexchanges\fP)]"

.SS "pip\&._vendor\&.rich\&.live\&.syntax"
\fBInitial value:\fP.PP
.nf
1 =  Syntax(
2         ,
3         "python",
4         line_numbers=True,
5     )
.fi

.SS "pip\&._vendor\&.rich\&.live\&.table = \fBTable\fP('foo', 'bar', 'baz')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
