.TH "pip._vendor.packaging._parser.ParsedRequirement" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging._parser.ParsedRequirement
.SH SYNOPSIS
.br
.PP
.PP
Inherits NamedTuple\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP"
.br
.ti -1c
.RI "str \fBurl\fP"
.br
.ti -1c
.RI "list \fBextras\fP [str]"
.br
.ti -1c
.RI "str \fBspecifier\fP"
.br
.ti -1c
.RI "\fBMarkerList\fP \fBmarker\fP | None"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "list pip\&._vendor\&.packaging\&._parser\&.ParsedRequirement\&.extras [str]\fC [static]\fP"

.SS "\fBMarkerList\fP pip\&._vendor\&.packaging\&._parser\&.ParsedRequirement\&.marker | None\fC [static]\fP"

.SS "str pip\&._vendor\&.packaging\&._parser\&.ParsedRequirement\&.name\fC [static]\fP"

.SS "str pip\&._vendor\&.packaging\&._parser\&.ParsedRequirement\&.specifier\fC [static]\fP"

.SS "str pip\&._vendor\&.packaging\&._parser\&.ParsedRequirement\&.url\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
