.TH "pip._internal.network.cache.SafeFileCache" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.network.cache.SafeFileCache
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.cachecontrol\&.cache\&.SeparateBodyBaseCache\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBdirectory\fP)"
.br
.ti -1c
.RI "Optional[bytes] \fBget\fP (self, str key)"
.br
.ti -1c
.RI "None \fBset\fP (self, str key, bytes value, Union[int, datetime, None] expires=None)"
.br
.ti -1c
.RI "None \fBdelete\fP (self, str key)"
.br
.ti -1c
.RI "Optional[BinaryIO] \fBget_body\fP (self, str key)"
.br
.ti -1c
.RI "None \fBset_body\fP (self, str key, bytes body)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.cachecontrol\&.cache\&.BaseCache\fP
.in +1c
.ti -1c
.RI "None \fBclose\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdirectory\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_get_cache_path\fP (self, str name)"
.br
.ti -1c
.RI "None \fB_write\fP (self, str path, bytes data)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A file based cache which is safe to use even when the target directory may
not be accessible or writable\&.

There is a race condition when two processes try to write and/or read the
same entry at the same time, since each entry consists of two separate
files (https://github\&.com/psf/cachecontrol/issues/324)\&.  We therefore have
additional logic that makes sure that both files to be present before
returning an entry; this fixes the read side of the race condition\&.

For the write side, we assume that the server will only ever return the
same data for the same URL, which ought to be the case for files pip is
downloading\&.  PyPI does not have a mechanism to swap out a wheel for
another wheel, for example\&.  If this assumption is not true, the
CacheControl issue will need to be fixed\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.network\&.cache\&.SafeFileCache\&.__init__ ( self, str directory)"

.SH "Member Function Documentation"
.PP 
.SS " str pip\&._internal\&.network\&.cache\&.SafeFileCache\&._get_cache_path ( self, str name)\fC [protected]\fP"

.SS " None pip\&._internal\&.network\&.cache\&.SafeFileCache\&._write ( self, str path, bytes data)\fC [protected]\fP"

.SS " None pip\&._internal\&.network\&.cache\&.SafeFileCache\&.delete ( self, str key)"

.PP
Reimplemented from \fBpip\&._vendor\&.cachecontrol\&.cache\&.BaseCache\fP\&.
.SS " Optional[bytes] pip\&._internal\&.network\&.cache\&.SafeFileCache\&.get ( self, str key)"

.PP
Reimplemented from \fBpip\&._vendor\&.cachecontrol\&.cache\&.BaseCache\fP\&.
.SS " Optional[BinaryIO] pip\&._internal\&.network\&.cache\&.SafeFileCache\&.get_body ( self, str key)"

.PP
.nf
Return the body as file-like object\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.cachecontrol\&.cache\&.SeparateBodyBaseCache\fP\&.
.SS " None pip\&._internal\&.network\&.cache\&.SafeFileCache\&.set ( self, str key, bytes value, Union[int, datetime, None]  expires = \fCNone\fP)"

.PP
Reimplemented from \fBpip\&._vendor\&.cachecontrol\&.cache\&.BaseCache\fP\&.
.SS " None pip\&._internal\&.network\&.cache\&.SafeFileCache\&.set_body ( self, str key, bytes body)"

.PP
Reimplemented from \fBpip\&._vendor\&.cachecontrol\&.cache\&.SeparateBodyBaseCache\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.network\&.cache\&.SafeFileCache\&.directory"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
