.TH "pip._vendor.requests.packages" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.requests.packages
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBvendored_package\fP = 'pip\&._vendor\&.' + package"
.br
.ti -1c
.RI "\fBunprefixed_mod\fP = \fBmod\fP[len('pip\&._vendor\&.'):]"
.br
.ti -1c
.RI "\fBtarget\fP = chardet\&.__name__"
.br
.ti -1c
.RI "\fBimported_mod\fP = sys\&.modules[\fBmod\fP]"
.br
.ti -1c
.RI "\fBmod\fP = mod\&.replace(\fBtarget\fP, 'chardet')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.requests\&.packages\&.imported_mod = sys\&.modules[\fBmod\fP]"

.SS "pip\&._vendor\&.requests\&.packages\&.mod = mod\&.replace(\fBtarget\fP, 'chardet')"

.SS "pip\&._vendor\&.requests\&.packages\&.target = chardet\&.__name__"

.SS "pip\&._vendor\&.requests\&.packages\&.unprefixed_mod = \fBmod\fP[len('pip\&._vendor\&.'):]"

.SS "str pip\&._vendor\&.requests\&.packages\&.vendored_package = 'pip\&._vendor\&.' + package"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
