.TH "pip._vendor.rich._log_render.LogRender" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._log_render.LogRender
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, bool \fBshow_time\fP=True, bool \fBshow_level\fP=False, bool \fBshow_path\fP=True, Union[str, \fBFormatTimeCallable\fP] \fBtime_format\fP='[%x %X]', bool \fBomit_repeated_times\fP=True, Optional[int] \fBlevel_width\fP=8)"
.br
.ti -1c
.RI "'Table' \fB__call__\fP (self, 'Console' console, Iterable['ConsoleRenderable'] renderables, Optional[datetime] log_time=None, Optional[Union[str, \fBFormatTimeCallable\fP]] \fBtime_format\fP=None, TextType level='', Optional[str] path=None, Optional[int] line_no=None, Optional[str] link_path=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBshow_time\fP"
.br
.ti -1c
.RI "\fBshow_level\fP"
.br
.ti -1c
.RI "\fBshow_path\fP"
.br
.ti -1c
.RI "\fBtime_format\fP"
.br
.ti -1c
.RI "\fBomit_repeated_times\fP"
.br
.ti -1c
.RI "\fBlevel_width\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_last_time\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&._log_render\&.LogRender\&.__init__ ( self, bool  show_time = \fCTrue\fP, bool  show_level = \fCFalse\fP, bool  show_path = \fCTrue\fP, Union[str, \fBFormatTimeCallable\fP]  time_format = \fC'[%x %X]'\fP, bool  omit_repeated_times = \fCTrue\fP, Optional[int]  level_width = \fC8\fP)"

.SH "Member Function Documentation"
.PP 
.SS " 'Table' pip\&._vendor\&.rich\&._log_render\&.LogRender\&.__call__ ( self, 'Console' console, Iterable['ConsoleRenderable'] renderables, Optional[datetime]  log_time = \fCNone\fP, Optional[Union[str, \fBFormatTimeCallable\fP]]  time_format = \fCNone\fP, TextType  level = \fC''\fP, Optional[str]  path = \fCNone\fP, Optional[int]  line_no = \fCNone\fP, Optional[str]  link_path = \fCNone\fP)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&._log_render\&.LogRender\&._last_time\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&._log_render\&.LogRender\&.level_width"

.SS "pip\&._vendor\&.rich\&._log_render\&.LogRender\&.omit_repeated_times"

.SS "pip\&._vendor\&.rich\&._log_render\&.LogRender\&.show_level"

.SS "pip\&._vendor\&.rich\&._log_render\&.LogRender\&.show_path"

.SS "pip\&._vendor\&.rich\&._log_render\&.LogRender\&.show_time"

.SS "pip\&._vendor\&.rich\&._log_render\&.LogRender\&.time_format"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
