.TH "pip._vendor.urllib3.packages.backports.weakref_finalize.weakref_finalize" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.packages.backports.weakref_finalize.weakref_finalize
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Info\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, obj, func, *args, **kwargs)"
.br
.ti -1c
.RI "\fB__call__\fP (self, _=None)"
.br
.ti -1c
.RI "\fBdetach\fP (self)"
.br
.ti -1c
.RI "\fBpeek\fP (self)"
.br
.ti -1c
.RI "\fBalive\fP (self)"
.br
.ti -1c
.RI "\fBatexit\fP (self)"
.br
.ti -1c
.RI "\fBatexit\fP (self, value)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_select_for_exit\fP (cls)"
.br
.ti -1c
.RI "\fB_exitfunc\fP (cls)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_exitfunc\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "dict \fB_registry\fP = {}"
.br
.ti -1c
.RI "bool \fB_shutdown\fP = False"
.br
.ti -1c
.RI "\fB_index_iter\fP = itertools\&.count()"
.br
.ti -1c
.RI "bool \fB_dirty\fP = False"
.br
.ti -1c
.RI "bool \fB_registered_with_atexit\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for finalization of weakrefable objects
finalize(obj, func, *args, **kwargs) returns a callable finalizer
object which will be called when obj is garbage collected\&. The
first time the finalizer is called it evaluates func(*arg, **kwargs)
and returns the result\&. After this the finalizer is dead, and
calling it just returns None\&.
When the program exits any remaining finalizers for which the
atexit attribute is true will be run in reverse order of creation\&.
By default atexit is true\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&.__init__ ( self,  obj,  func, * args, ** kwargs)"

.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&.__call__ ( self,  _ = \fCNone\fP)"

.PP
.nf
If alive then mark as dead and return func(*args, **kwargs);
otherwise return None
.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&.__repr__ ( self)"

.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&._exitfunc ( cls)\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&._select_for_exit ( cls)\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&.alive ( self)"

.PP
.nf
Whether finalizer is alive
.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&.atexit ( self)"

.PP
.nf
Whether finalizer should be called at exit
.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&.atexit ( self,  value)"

.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&.detach ( self)"

.PP
.nf
If alive then mark as dead and return (obj, func, args, kwargs);
otherwise return None
.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&.peek ( self)"

.PP
.nf
If alive then return (obj, func, args, kwargs);
otherwise return None
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "bool pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&._dirty = False\fC [static]\fP, \fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&._exitfunc\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&._index_iter = itertools\&.count()\fC [static]\fP, \fC [protected]\fP"

.SS "bool pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&._registered_with_atexit = False\fC [static]\fP, \fC [protected]\fP"

.SS "dict pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&._registry = {}\fC [static]\fP, \fC [protected]\fP"

.SS "bool pip\&._vendor\&.urllib3\&.packages\&.backports\&.weakref_finalize\&.weakref_finalize\&._shutdown = False\fC [static]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
