.TH "pip._vendor.urllib3.util.url.Url" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.util.url.Url
.SH SYNOPSIS
.br
.PP
.PP
Inherits namedtuple, and url_attrs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__new__\fP (cls, scheme=None, auth=None, \fBhost\fP=None, \fBport\fP=None, path=None, query=None, fragment=None)"
.br
.ti -1c
.RI "\fBhostname\fP (self)"
.br
.ti -1c
.RI "\fBrequest_uri\fP (self)"
.br
.ti -1c
.RI "\fBnetloc\fP (self)"
.br
.ti -1c
.RI "\fBurl\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Data structure for representing an HTTP URL\&. Used as a return value for
:func:`parse_url`\&. Both the scheme and host are normalized as they are
both case-insensitive according to RFC 3986\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.util\&.url\&.Url\&.__new__ ( cls,  scheme = \fCNone\fP,  auth = \fCNone\fP,  host = \fCNone\fP,  port = \fCNone\fP,  path = \fCNone\fP,  query = \fCNone\fP,  fragment = \fCNone\fP)"

.SS "pip\&._vendor\&.urllib3\&.util\&.url\&.Url\&.__str__ ( self)"

.SS "pip\&._vendor\&.urllib3\&.util\&.url\&.Url\&.hostname ( self)"

.PP
.nf
For backwards-compatibility with urlparse\&. We're nice like that\&.
.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.util\&.url\&.Url\&.netloc ( self)"

.PP
.nf
Network location including host and port
.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.util\&.url\&.Url\&.request_uri ( self)"

.PP
.nf
Absolute path including the query string\&.
.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.util\&.url\&.Url\&.url ( self)"

.PP
.nf
Convert self into a url

This function should more or less round-trip with :func:`\&.parse_url`\&. The
returned url may not be exactly the same as the url inputted to
:func:`\&.parse_url`, but it should be equivalent by the RFC (e\&.g\&., urls
with a blank port will have : removed)\&.

Example: ::

    >>> U = parse_url('http://google\&.com/mail/')
    >>> U\&.url
    'http://google\&.com/mail/'
    >>> Url('http', 'username:password', 'host\&.com', 80,
    \&.\&.\&. '/path', 'query', 'fragment')\&.url
    'http://username:password@host\&.com:80/path?query#fragment'

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.util\&.url\&.Url\&.host"

.SS "pip\&._vendor\&.urllib3\&.util\&.url\&.Url\&.port"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
