.TH "pip._internal.network.lazy_wheel" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.network.lazy_wheel
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHTTPRangeRequestUnsupported\fP"
.br
.ti -1c
.RI "class \fBLazyZipOverHTTP\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBaseDistribution\fP \fBdist_from_wheel_url\fP (str name, str url, PipSession session)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Lazy ZIP over HTTP
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fBBaseDistribution\fP pip\&._internal\&.network\&.lazy_wheel\&.dist_from_wheel_url (str name, str url, PipSession session)"

.PP
.nf
Return a distribution object from the given wheel URL\&.

This uses HTTP range requests to only fetch the portion of the wheel
containing metadata, just enough for the object to be constructed\&.
If such requests are not supported, HTTPRangeRequestUnsupported
is raised\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
