.TH "pip._internal.locations._distutils" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.locations._distutils
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "Dict[str, str] \fBdistutils_scheme\fP (str dist_name, bool user=False, Optional[str] home=None, Optional[str] root=None, bool isolated=False, Optional[str] prefix=None, *bool ignore_config_files=False)"
.br
.ti -1c
.RI "\fBScheme\fP \fBget_scheme\fP (str dist_name, bool user=False, Optional[str] home=None, Optional[str] root=None, bool isolated=False, Optional[str] prefix=None)"
.br
.ti -1c
.RI "str \fBget_bin_prefix\fP ()"
.br
.ti -1c
.RI "str \fBget_purelib\fP ()"
.br
.ti -1c
.RI "str \fBget_platlib\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Locations where we look for configs, install stuff, etc
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " Dict[str, str] pip\&._internal\&.locations\&._distutils\&.distutils_scheme (str dist_name, bool  user = \fCFalse\fP, Optional[str]  home = \fCNone\fP, Optional[str]  root = \fCNone\fP, bool  isolated = \fCFalse\fP, Optional[str]  prefix = \fCNone\fP, *bool  ignore_config_files = \fCFalse\fP)"

.PP
.nf
Return a distutils install scheme

.fi
.PP
 
.SS " str pip\&._internal\&.locations\&._distutils\&.get_bin_prefix ()"

.SS " str pip\&._internal\&.locations\&._distutils\&.get_platlib ()"

.SS " str pip\&._internal\&.locations\&._distutils\&.get_purelib ()"

.SS " \fBScheme\fP pip\&._internal\&.locations\&._distutils\&.get_scheme (str dist_name, bool  user = \fCFalse\fP, Optional[str]  home = \fCNone\fP, Optional[str]  root = \fCNone\fP, bool  isolated = \fCFalse\fP, Optional[str]  prefix = \fCNone\fP)"

.PP
.nf
Get the 'scheme' corresponding to the input parameters\&. The distutils
documentation provides the context for the available schemes:
https://docs\&.python\&.org/3/install/index\&.html#alternate-installation

:param dist_name: the name of the package to retrieve the scheme for, used
    in the headers scheme path
:param user: indicates to use the 'user' scheme
:param home: indicates to use the 'home' scheme and provides the base
    directory for the same
:param root: root under which other directories are re-based
:param isolated: equivalent to --no-user-cfg, i\&.e\&. do not consider
    ~/\&.pydistutils\&.cfg (posix) or ~/pydistutils\&.cfg (non-posix) for
    scheme paths
:param prefix: indicates to use the 'prefix' scheme and provides the
    base directory for the same

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._internal\&.locations\&._distutils\&.logger = logging\&.getLogger(__name__)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
