.TH "pip._vendor.urllib3.util.wait" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.util.wait
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNoWayToWaitForSocketError\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_retry_on_intr\fP (fn, timeout)"
.br
.ti -1c
.RI "\fBselect_wait_for_socket\fP (sock, read=False, write=False, timeout=None)"
.br
.ti -1c
.RI "\fBpoll_wait_for_socket\fP (sock, read=False, write=False, timeout=None)"
.br
.ti -1c
.RI "\fBnull_wait_for_socket\fP (*args, **kwargs)"
.br
.ti -1c
.RI "\fB_have_working_poll\fP ()"
.br
.ti -1c
.RI "\fBwait_for_socket\fP (*args, **kwargs)"
.br
.ti -1c
.RI "\fBwait_for_read\fP (sock, timeout=None)"
.br
.ti -1c
.RI "\fBwait_for_write\fP (sock, timeout=None)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.util\&.wait\&._have_working_poll ()\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.util\&.wait\&._retry_on_intr ( fn,  timeout)\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.util\&.wait\&.null_wait_for_socket (* args, ** kwargs)"

.SS "pip\&._vendor\&.urllib3\&.util\&.wait\&.poll_wait_for_socket ( sock,  read = \fCFalse\fP,  write = \fCFalse\fP,  timeout = \fCNone\fP)"

.SS "pip\&._vendor\&.urllib3\&.util\&.wait\&.select_wait_for_socket ( sock,  read = \fCFalse\fP,  write = \fCFalse\fP,  timeout = \fCNone\fP)"

.SS "pip\&._vendor\&.urllib3\&.util\&.wait\&.wait_for_read ( sock,  timeout = \fCNone\fP)"

.PP
.nf
Waits for reading to be available on a given socket\&.
Returns True if the socket is readable, or False if the timeout expired\&.

.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.util\&.wait\&.wait_for_socket (* args, ** kwargs)"

.SS "pip\&._vendor\&.urllib3\&.util\&.wait\&.wait_for_write ( sock,  timeout = \fCNone\fP)"

.PP
.nf
Waits for writing to be available on a given socket\&.
Returns True if the socket is readable, or False if the timeout expired\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
