.TH "pip._vendor.tomli._parser.NestedDict" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.tomli._parser.NestedDict
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self)"
.br
.ti -1c
.RI "dict \fBget_or_create_nest\fP (self, Key key, *bool access_lists=True)"
.br
.ti -1c
.RI "None \fBappend_nest_to_list\fP (self, Key key)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.tomli\&._parser\&.NestedDict\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS " None pip\&._vendor\&.tomli\&._parser\&.NestedDict\&.append_nest_to_list ( self, Key key)"

.SS " dict pip\&._vendor\&.tomli\&._parser\&.NestedDict\&.get_or_create_nest ( self, Key key, *bool  access_lists = \fCTrue\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
