.TH "pip._vendor.pkg_resources.MemoizedZipManifests" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pkg_resources.MemoizedZipManifests
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.pkg_resources\&.ZipManifests\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmanifest_mod\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "dict[str, zipfile\&.ZipInfo] \fBload\fP (self, str path)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.pkg_resources\&.ZipManifests\fP
.in +1c
.ti -1c
.RI "\fBbuild\fP (cls, str path)"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBpip\&._vendor\&.pkg_resources\&.ZipManifests\fP
.SH "Detailed Description"
.PP 

.PP
.nf
Memoized zipfile manifests\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " dict[str, zipfile\&.ZipInfo] pip\&._vendor\&.pkg_resources\&.MemoizedZipManifests\&.load ( self, str path)"

.PP
.nf
Load a manifest at path or return a suitable manifest already loaded\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.pkg_resources\&.ZipManifests\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
