.TH "pip._vendor.rich.scope" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.scope
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "'ConsoleRenderable' \fBrender_scope\fP ('Mapping[str, Any]' scope, *Optional[TextType] title=None, bool sort_keys=True, bool indent_guides=False, Optional[int] max_length=None, Optional[int] max_string=None)"
.br
.ti -1c
.RI "None \fBtest\fP (float foo, float bar)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " 'ConsoleRenderable' pip\&._vendor\&.rich\&.scope\&.render_scope ('Mapping[str, Any]' scope, *Optional[TextType]  title = \fCNone\fP, bool  sort_keys = \fCTrue\fP, bool  indent_guides = \fCFalse\fP, Optional[int]  max_length = \fCNone\fP, Optional[int]  max_string = \fCNone\fP)"

.PP
.nf
Render python variables in a given scope\&.

Args:
    scope (Mapping): A mapping containing variable names and values\&.
    title (str, optional): Optional title\&. Defaults to None\&.
    sort_keys (bool, optional): Enable sorting of items\&. Defaults to True\&.
    indent_guides (bool, optional): Enable indentation guides\&. Defaults to False\&.
    max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation\&.
        Defaults to None\&.
    max_string (int, optional): Maximum length of string before truncating, or None to disable\&. Defaults to None\&.

Returns:
    ConsoleRenderable: A renderable object\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.scope\&.test (float foo, float bar)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
