.TH "pip._vendor.distlib.util.ExportEntry" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.util.ExportEntry
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBname\fP, \fBprefix\fP, \fBsuffix\fP, \fBflags\fP)"
.br
.ti -1c
.RI "\fBvalue\fP (self)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__eq__\fP (self, other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBsuffix\fP"
.br
.ti -1c
.RI "\fBflags\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.util\&.ExportEntry\&.__init__ ( self,  name,  prefix,  suffix,  flags)"

.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.util\&.ExportEntry\&.__eq__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.util\&.ExportEntry\&.__repr__ ( self)"

.SS "pip\&._vendor\&.distlib\&.util\&.ExportEntry\&.value ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.util\&.ExportEntry\&.flags"

.SS "pip\&._vendor\&.distlib\&.util\&.ExportEntry\&.name"

.SS "pip\&._vendor\&.distlib\&.util\&.ExportEntry\&.prefix"

.SS "pip\&._vendor\&.distlib\&.util\&.ExportEntry\&.suffix"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
