.TH "pip._vendor.requests.compat" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.requests.compat
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_resolve_char_detection\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBchardet\fP = \fB_resolve_char_detection\fP()"
.br
.ti -1c
.RI "\fB_ver\fP = sys\&.version_info"
.br
.ti -1c
.RI "int \fBis_py2\fP = 2"
.br
.ti -1c
.RI "int \fBis_py3\fP = 3"
.br
.ti -1c
.RI "\fBbuiltin_str\fP = \fBstr\fP"
.br
.ti -1c
.RI "\fBstr\fP = str"
.br
.ti -1c
.RI "\fBbytes\fP = bytes"
.br
.ti -1c
.RI "tuple \fBbasestring\fP = (\fBstr\fP, \fBbytes\fP)"
.br
.ti -1c
.RI "tuple \fBnumeric_types\fP = (int, float)"
.br
.ti -1c
.RI "tuple \fBinteger_types\fP = (int,)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
requests\&.compat
~~~~~~~~~~~~~~~

This module previously handled import compatibility issues
between Python 2 and Python 3\&. It remains for backwards
compatibility until the next major version\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.requests\&.compat\&._resolve_char_detection ()\fC [protected]\fP"

.PP
.nf
Find supported character detection libraries\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.requests\&.compat\&._ver = sys\&.version_info\fC [protected]\fP"

.SS "tuple pip\&._vendor\&.requests\&.compat\&.basestring = (\fBstr\fP, \fBbytes\fP)"

.SS "pip\&._vendor\&.requests\&.compat\&.builtin_str = \fBstr\fP"

.SS "pip\&._vendor\&.requests\&.compat\&.bytes = bytes"

.SS "pip\&._vendor\&.requests\&.compat\&.chardet = \fB_resolve_char_detection\fP()"

.SS "tuple pip\&._vendor\&.requests\&.compat\&.integer_types = (int,)"

.SS "int pip\&._vendor\&.requests\&.compat\&.is_py2 = 2"

.SS "int pip\&._vendor\&.requests\&.compat\&.is_py3 = 3"

.SS "tuple pip\&._vendor\&.requests\&.compat\&.numeric_types = (int, float)"

.SS "pip\&._vendor\&.requests\&.compat\&.str = str"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
