.TH "pip._vendor.idna.codec" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.idna.codec
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCodec\fP"
.br
.ti -1c
.RI "class \fBIncrementalDecoder\fP"
.br
.ti -1c
.RI "class \fBIncrementalEncoder\fP"
.br
.ti -1c
.RI "class \fBStreamReader\fP"
.br
.ti -1c
.RI "class \fBStreamWriter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Optional[codecs\&.CodecInfo] \fBsearch_function\fP (str name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_unicode_dots_re\fP = re\&.compile('[\\u002e\\u3002\\uff0e\\uff61]')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " Optional[codecs\&.CodecInfo] pip\&._vendor\&.idna\&.codec\&.search_function (str name)"

.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.idna\&.codec\&._unicode_dots_re = re\&.compile('[\\u002e\\u3002\\uff0e\\uff61]')\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
