.TH "pip._vendor.rich._null_file.NullFile" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._null_file.NullFile
.SH SYNOPSIS
.br
.PP
.PP
Inherits IO, and str\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fBclose\fP (self)"
.br
.ti -1c
.RI "bool \fBisatty\fP (self)"
.br
.ti -1c
.RI "str \fBread\fP (self, int __n=1)"
.br
.ti -1c
.RI "bool \fBreadable\fP (self)"
.br
.ti -1c
.RI "str \fBreadline\fP (self, int __limit=1)"
.br
.ti -1c
.RI "List[str] \fBreadlines\fP (self, int __hint=1)"
.br
.ti -1c
.RI "int \fBseek\fP (self, int __offset, int __whence=1)"
.br
.ti -1c
.RI "bool \fBseekable\fP (self)"
.br
.ti -1c
.RI "int \fBtell\fP (self)"
.br
.ti -1c
.RI "int \fBtruncate\fP (self, Optional[int] __size=1)"
.br
.ti -1c
.RI "bool \fBwritable\fP (self)"
.br
.ti -1c
.RI "None \fBwritelines\fP (self, Iterable[str] __lines)"
.br
.ti -1c
.RI "str \fB__next__\fP (self)"
.br
.ti -1c
.RI "Iterator[str] \fB__iter__\fP (self)"
.br
.ti -1c
.RI "IO[str] \fB__enter__\fP (self)"
.br
.ti -1c
.RI "None \fB__exit__\fP (self, Optional[Type[BaseException]] __t, Optional[BaseException] __value, Optional[TracebackType] __traceback)"
.br
.ti -1c
.RI "int \fBwrite\fP (self, str text)"
.br
.ti -1c
.RI "None \fBflush\fP (self)"
.br
.ti -1c
.RI "int \fBfileno\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " IO[str] pip\&._vendor\&.rich\&._null_file\&.NullFile\&.__enter__ ( self)"

.SS " None pip\&._vendor\&.rich\&._null_file\&.NullFile\&.__exit__ ( self, Optional[Type[BaseException]] __t, Optional[BaseException] __value, Optional[TracebackType] __traceback)"

.SS " Iterator[str] pip\&._vendor\&.rich\&._null_file\&.NullFile\&.__iter__ ( self)"

.SS " str pip\&._vendor\&.rich\&._null_file\&.NullFile\&.__next__ ( self)"

.SS " None pip\&._vendor\&.rich\&._null_file\&.NullFile\&.close ( self)"

.SS " int pip\&._vendor\&.rich\&._null_file\&.NullFile\&.fileno ( self)"

.SS " None pip\&._vendor\&.rich\&._null_file\&.NullFile\&.flush ( self)"

.SS " bool pip\&._vendor\&.rich\&._null_file\&.NullFile\&.isatty ( self)"

.SS " str pip\&._vendor\&.rich\&._null_file\&.NullFile\&.read ( self, int  __n = \fC1\fP)"

.SS " bool pip\&._vendor\&.rich\&._null_file\&.NullFile\&.readable ( self)"

.SS " str pip\&._vendor\&.rich\&._null_file\&.NullFile\&.readline ( self, int  __limit = \fC1\fP)"

.SS " List[str] pip\&._vendor\&.rich\&._null_file\&.NullFile\&.readlines ( self, int  __hint = \fC1\fP)"

.SS " int pip\&._vendor\&.rich\&._null_file\&.NullFile\&.seek ( self, int __offset, int  __whence = \fC1\fP)"

.SS " bool pip\&._vendor\&.rich\&._null_file\&.NullFile\&.seekable ( self)"

.SS " int pip\&._vendor\&.rich\&._null_file\&.NullFile\&.tell ( self)"

.SS " int pip\&._vendor\&.rich\&._null_file\&.NullFile\&.truncate ( self, Optional[int]  __size = \fC1\fP)"

.SS " bool pip\&._vendor\&.rich\&._null_file\&.NullFile\&.writable ( self)"

.SS " int pip\&._vendor\&.rich\&._null_file\&.NullFile\&.write ( self, str text)"

.SS " None pip\&._vendor\&.rich\&._null_file\&.NullFile\&.writelines ( self, Iterable[str] __lines)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
