.TH "pip._vendor.rich._loop" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._loop
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "Iterable[Tuple[bool, \fBT\fP]] \fBloop_first\fP (Iterable[\fBT\fP] values)"
.br
.ti -1c
.RI "Iterable[Tuple[bool, \fBT\fP]] \fBloop_last\fP (Iterable[\fBT\fP] values)"
.br
.ti -1c
.RI "Iterable[Tuple[bool, bool, \fBT\fP]] \fBloop_first_last\fP (Iterable[\fBT\fP] values)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBT\fP = TypeVar('T')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " Iterable[Tuple[bool, \fBT\fP]] pip\&._vendor\&.rich\&._loop\&.loop_first (Iterable[\fBT\fP] values)"

.PP
.nf
Iterate and generate a tuple with a flag for first value\&.
.fi
.PP
 
.SS " Iterable[Tuple[bool, bool, \fBT\fP]] pip\&._vendor\&.rich\&._loop\&.loop_first_last (Iterable[\fBT\fP] values)"

.PP
.nf
Iterate and generate a tuple with a flag for first and last value\&.
.fi
.PP
 
.SS " Iterable[Tuple[bool, \fBT\fP]] pip\&._vendor\&.rich\&._loop\&.loop_last (Iterable[\fBT\fP] values)"

.PP
.nf
Iterate and generate a tuple with a flag for last value\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&._loop\&.T = TypeVar('T')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
