.TH "pip._vendor.pygments.formatters.other.TestcaseFormatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pygments.formatters.other.TestcaseFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.pygments\&.formatter\&.Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fBformat\fP (self, tokensource, outfile)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.pygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBget_style_defs\fP (self, arg='')"
.br
.ti -1c
.RI "\fB__class_getitem__\fP (cls, \fBname\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'Testcase'"
.br
.ti -1c
.RI "list \fBaliases\fP = ['testcase']"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._vendor\&.pygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBname\fP = None"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "list \fBfilenames\fP = []"
.br
.ti -1c
.RI "bool \fBunicodeoutput\fP = True"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBpip\&._vendor\&.pygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBfull\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Format tokens as appropriate for a new testcase\&.

\&.\&. versionadded:: 2\&.0

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.pygments\&.formatters\&.other\&.TestcaseFormatter\&.__init__ ( self, ** options)"

.PP
.nf
As with lexers, this constructor takes arbitrary optional arguments,
and if you override it, you should first process your own options, then
call the base class implementation\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.pygments\&.formatter\&.Formatter\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.pygments\&.formatters\&.other\&.TestcaseFormatter\&.format ( self,  tokensource,  outfile)"

.PP
.nf
This method must format the tokens from the `tokensource` iterable and
write the formatted version to the file object `outfile`\&.

Formatter options can control how exactly the tokens are converted\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.pygments\&.formatter\&.Formatter\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "list pip\&._vendor\&.pygments\&.formatters\&.other\&.TestcaseFormatter\&.aliases = ['testcase']\fC [static]\fP"

.SS "str pip\&._vendor\&.pygments\&.formatters\&.other\&.TestcaseFormatter\&.name = 'Testcase'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
