.TH "pip._vendor.cachecontrol.caches.file_cache" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.cachecontrol.caches.file_cache
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_FileCacheMixin\fP"
.br
.ti -1c
.RI "class \fBFileCache\fP"
.br
.ti -1c
.RI "class \fBSeparateBodyFileCache\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "IO[bytes] \fB_secure_open_write\fP (str filename, int fmode)"
.br
.ti -1c
.RI "str \fBurl_to_file_path\fP (str url, \fBFileCache\fP filecache)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " IO[bytes] pip\&._vendor\&.cachecontrol\&.caches\&.file_cache\&._secure_open_write (str filename, int fmode)\fC [protected]\fP"

.SS " str pip\&._vendor\&.cachecontrol\&.caches\&.file_cache\&.url_to_file_path (str url, \fBFileCache\fP filecache)"

.PP
.nf
Return the file cache path based on the URL\&.

This does not ensure the file exists!

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
