.TH "pip._vendor.rich.progress.BarColumn" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.progress.BarColumn
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.rich\&.progress\&.ProgressColumn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, Optional[int] \fBbar_width\fP=40, StyleType \fBstyle\fP='bar\&.back', StyleType \fBcomplete_style\fP='bar\&.complete', StyleType \fBfinished_style\fP='bar\&.finished', StyleType \fBpulse_style\fP='bar\&.pulse', Optional[\fBColumn\fP] table_column=None)"
.br
.ti -1c
.RI "\fBProgressBar\fP \fBrender\fP (self, 'Task' task)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.rich\&.progress\&.ProgressColumn\fP
.in +1c
.ti -1c
.RI "\fBColumn\fP \fBget_table_column\fP (self)"
.br
.ti -1c
.RI "RenderableType \fB__call__\fP (self, 'Task' task)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbar_width\fP"
.br
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBcomplete_style\fP"
.br
.ti -1c
.RI "\fBfinished_style\fP"
.br
.ti -1c
.RI "\fBpulse_style\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBpip\&._vendor\&.rich\&.progress\&.ProgressColumn\fP
.in +1c
.ti -1c
.RI "Optional \fBmax_refresh\fP = None"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._vendor\&.rich\&.progress\&.ProgressColumn\fP
.in +1c
.ti -1c
.RI "\fB_table_column\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Renders a visual progress bar\&.

Args:
    bar_width (Optional[int], optional): Width of bar or None for full width\&. Defaults to 40\&.
    style (StyleType, optional): Style for the bar background\&. Defaults to 'bar\&.back'\&.
    complete_style (StyleType, optional): Style for the completed bar\&. Defaults to 'bar\&.complete'\&.
    finished_style (StyleType, optional): Style for a finished bar\&. Defaults to 'bar\&.finished'\&.
    pulse_style (StyleType, optional): Style for pulsing bars\&. Defaults to 'bar\&.pulse'\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.progress\&.BarColumn\&.__init__ ( self, Optional[int]  bar_width = \fC40\fP, StyleType  style = \fC'bar\&.back'\fP, StyleType  complete_style = \fC'bar\&.complete'\fP, StyleType  finished_style = \fC'bar\&.finished'\fP, StyleType  pulse_style = \fC'bar\&.pulse'\fP, Optional[\fBColumn\fP]  table_column = \fCNone\fP)"

.PP
Reimplemented from \fBpip\&._vendor\&.rich\&.progress\&.ProgressColumn\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " \fBProgressBar\fP pip\&._vendor\&.rich\&.progress\&.BarColumn\&.render ( self, 'Task' task)"

.PP
.nf
Gets a progress bar widget for a task\&.
.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.rich\&.progress\&.ProgressColumn\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.progress\&.BarColumn\&.bar_width"

.SS "pip\&._vendor\&.rich\&.progress\&.BarColumn\&.complete_style"

.SS "pip\&._vendor\&.rich\&.progress\&.BarColumn\&.finished_style"

.SS "pip\&._vendor\&.rich\&.progress\&.BarColumn\&.pulse_style"

.SS "pip\&._vendor\&.rich\&.progress\&.BarColumn\&.style"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
