.TH "pip._internal.cli.parser.UpdatingDefaultsHelpFormatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.cli.parser.UpdatingDefaultsHelpFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._internal\&.cli\&.parser\&.PrettyHelpFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "str \fBexpand_default\fP (self, optparse\&.Option option)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._internal\&.cli\&.parser\&.PrettyHelpFormatter\fP
.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, *Any args, **Any kwargs)"
.br
.ti -1c
.RI "str \fBformat_option_strings\fP (self, optparse\&.Option option)"
.br
.ti -1c
.RI "str \fBformat_heading\fP (self, str heading)"
.br
.ti -1c
.RI "str \fBformat_usage\fP (self, str usage)"
.br
.ti -1c
.RI "str \fBformat_description\fP (self, Optional[str] description)"
.br
.ti -1c
.RI "str \fBformat_epilog\fP (self, Optional[str] epilog)"
.br
.ti -1c
.RI "str \fBindent_lines\fP (self, str text, str indent)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparser\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._internal\&.cli\&.parser\&.PrettyHelpFormatter\fP
.in +1c
.ti -1c
.RI "\fBparser\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpip\&._internal\&.cli\&.parser\&.PrettyHelpFormatter\fP
.in +1c
.ti -1c
.RI "str \fB_format_option_strings\fP (self, optparse\&.Option option, str mvarfmt=' <{}>', str optsep=', ')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Custom help formatter for use in ConfigOptionParser\&.

This is updates the defaults before expanding them, allowing
them to show up correctly in the help listing\&.

Also redact auth from url type options

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str pip\&._internal\&.cli\&.parser\&.UpdatingDefaultsHelpFormatter\&.expand_default ( self, optparse\&.Option option)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.cli\&.parser\&.UpdatingDefaultsHelpFormatter\&.parser"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
