.TH "pip._vendor.distlib.scripts" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.scripts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScriptMaker\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBenquote_executable\fP (executable)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "str \fB_DEFAULT_MANIFEST\fP"
.br
.ti -1c
.RI "\fBFIRST_LINE_RE\fP = re\&.compile(b'^#!\&.*pythonw?[0\-9\&.]*([ \\t]\&.*)?$')"
.br
.ti -1c
.RI "str \fBSCRIPT_TEMPLATE\fP"
.br
.ti -1c
.RI "\fBDISTLIB_PACKAGE\fP = __name__\&.rsplit('\&.', 1)[0]"
.br
.ti -1c
.RI "dict \fBWRAPPERS\fP"
.br
.ti -1c
.RI "\fB_enquote_executable\fP = \fBenquote_executable\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.scripts\&.enquote_executable ( executable)"

.SH "Variable Documentation"
.PP 
.SS "str pip\&._vendor\&.distlib\&.scripts\&._DEFAULT_MANIFEST\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  '''
2 <?xml version="1\&.0" encoding="UTF\-8" standalone="yes"?>
3 <assembly xmlns="urn:schemas\-microsoft\-com:asm\&.v1" manifestVersion="1\&.0">
4  <assemblyIdentity version="1\&.0\&.0\&.0"
5  processorArchitecture="X86"
6  name="%s"
7  type="win32"/>
8 
9  <!\-\- Identify the application security requirements\&. \-\->
10  <trustInfo xmlns="urn:schemas\-microsoft\-com:asm\&.v3">
11  <security>
12  <requestedPrivileges>
13  <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
14  </requestedPrivileges>
15  </security>
16  </trustInfo>
17 </assembly>'''\&.strip()
.fi

.SS "pip\&._vendor\&.distlib\&.scripts\&._enquote_executable = \fBenquote_executable\fP\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.scripts\&.DISTLIB_PACKAGE = __name__\&.rsplit('\&.', 1)[0]"

.SS "pip\&._vendor\&.distlib\&.scripts\&.FIRST_LINE_RE = re\&.compile(b'^#!\&.*pythonw?[0\-9\&.]*([ \\t]\&.*)?$')"

.SS "pip\&._vendor\&.distlib\&.scripts\&.logger = logging\&.getLogger(__name__)"

.SS "str pip\&._vendor\&.distlib\&.scripts\&.SCRIPT_TEMPLATE"
\fBInitial value:\fP.PP
.nf
1 =  r'''# \-*\- coding: utf\-8 \-*\-
2 import re
3 import sys
4 from %(module)s import %(import_name)s
5 if __name__ == '__main__':
6     sys\&.argv[0] = re\&.sub(r'(\-script\\\&.pyw|\\\&.exe)?$', '', sys\&.argv[0])
7     sys\&.exit(%(func)s())
8 '''
.fi

.SS "dict pip\&._vendor\&.distlib\&.scripts\&.WRAPPERS"
\fBInitial value:\fP.PP
.nf
1 =  {
2         r\&.name: r\&.bytes
3         for r in finder(DISTLIB_PACKAGE)\&.iterator("")
4         if r\&.name\&.endswith("\&.exe")
5     }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
