.TH "pip._vendor.rich.pretty.BrokenRepr" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.pretty.BrokenRepr
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " str pip\&._vendor\&.rich\&.pretty\&.BrokenRepr\&.__repr__ ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
