.TH "pip._internal.operations.install.wheel.ZipBackedFile" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.operations.install.wheel.ZipBackedFile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBRecordPath\fP \fBsrc_record_path\fP, str \fBdest_path\fP, ZipFile zip_file)"
.br
.ti -1c
.RI "None \fBsave\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsrc_record_path\fP"
.br
.ti -1c
.RI "\fBdest_path\fP"
.br
.ti -1c
.RI "\fBchanged\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "ZipInfo \fB_getinfo\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_zip_file\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.operations\&.install\&.wheel\&.ZipBackedFile\&.__init__ ( self, \fBRecordPath\fP src_record_path, str dest_path, ZipFile
     zip_file)"

.SH "Member Function Documentation"
.PP 
.SS " ZipInfo pip\&._internal\&.operations\&.install\&.wheel\&.ZipBackedFile\&._getinfo ( self)\fC [protected]\fP"

.SS " None pip\&._internal\&.operations\&.install\&.wheel\&.ZipBackedFile\&.save ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.operations\&.install\&.wheel\&.ZipBackedFile\&._zip_file\fC [protected]\fP"

.SS "pip\&._internal\&.operations\&.install\&.wheel\&.ZipBackedFile\&.changed"

.SS "pip\&._internal\&.operations\&.install\&.wheel\&.ZipBackedFile\&.dest_path"

.SS "pip\&._internal\&.operations\&.install\&.wheel\&.ZipBackedFile\&.src_record_path"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
