.TH "pip._vendor.platformdirs.android" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.platformdirs.android
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAndroid\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str|None \fB_android_folder\fP ()"
.br
.ti -1c
.RI "str \fB_android_documents_folder\fP ()"
.br
.ti -1c
.RI "str \fB_android_downloads_folder\fP ()"
.br
.ti -1c
.RI "str \fB_android_pictures_folder\fP ()"
.br
.ti -1c
.RI "str \fB_android_videos_folder\fP ()"
.br
.ti -1c
.RI "str \fB_android_music_folder\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Android\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str pip\&._vendor\&.platformdirs\&.android\&._android_documents_folder ()\fC [protected]\fP"

.PP
.nf
:return: documents folder for the Android OS
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.android\&._android_downloads_folder ()\fC [protected]\fP"

.PP
.nf
:return: downloads folder for the Android OS
.fi
.PP
 
.SS " str | None pip\&._vendor\&.platformdirs\&.android\&._android_folder ()\fC [protected]\fP"

.PP
.nf
:return: base folder for the Android OS or None if it cannot be found
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.android\&._android_music_folder ()\fC [protected]\fP"

.PP
.nf
:return: music folder for the Android OS
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.android\&._android_pictures_folder ()\fC [protected]\fP"

.PP
.nf
:return: pictures folder for the Android OS
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.android\&._android_videos_folder ()\fC [protected]\fP"

.PP
.nf
:return: videos folder for the Android OS
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
