.TH "pip._vendor.packaging._parser.Node" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging._parser.Node
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpip\&._vendor\&.packaging\&._parser\&.Op\fP, \fBpip\&._vendor\&.packaging\&._parser\&.Value\fP, and \fBpip\&._vendor\&.packaging\&._parser\&.Variable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBvalue\fP)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "str \fBserialize\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalue\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.packaging\&._parser\&.Node\&.__init__ ( self, str value)"

.SH "Member Function Documentation"
.PP 
.SS " str pip\&._vendor\&.packaging\&._parser\&.Node\&.__repr__ ( self)"

.SS " str pip\&._vendor\&.packaging\&._parser\&.Node\&.__str__ ( self)"

.SS " str pip\&._vendor\&.packaging\&._parser\&.Node\&.serialize ( self)"

.PP
Reimplemented in \fBpip\&._vendor\&.packaging\&._parser\&.Variable\fP, \fBpip\&._vendor\&.packaging\&._parser\&.Value\fP, and \fBpip\&._vendor\&.packaging\&._parser\&.Op\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.packaging\&._parser\&.Node\&.value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
