.TH "pip._vendor.packaging.tags.Tag" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging.tags.Tag
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBinterpreter\fP, str \fBabi\fP, str \fBplatform\fP)"
.br
.ti -1c
.RI "str \fBinterpreter\fP (self)"
.br
.ti -1c
.RI "str \fBabi\fP (self)"
.br
.ti -1c
.RI "str \fBplatform\fP (self)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, object other)"
.br
.ti -1c
.RI "int \fB__hash__\fP (self)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_interpreter\fP"
.br
.ti -1c
.RI "\fB_abi\fP"
.br
.ti -1c
.RI "\fB_platform\fP"
.br
.ti -1c
.RI "\fB_hash\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A representation of the tag triple for a wheel\&.

Instances are considered immutable and thus are hashable\&. Equality checking
is also supported\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.packaging\&.tags\&.Tag\&.__init__ ( self, str interpreter, str abi, str platform)"

.SH "Member Function Documentation"
.PP 
.SS " bool pip\&._vendor\&.packaging\&.tags\&.Tag\&.__eq__ ( self, object other)"

.SS " int pip\&._vendor\&.packaging\&.tags\&.Tag\&.__hash__ ( self)"

.SS " str pip\&._vendor\&.packaging\&.tags\&.Tag\&.__repr__ ( self)"

.SS " str pip\&._vendor\&.packaging\&.tags\&.Tag\&.__str__ ( self)"

.SS " str pip\&._vendor\&.packaging\&.tags\&.Tag\&.abi ( self)"

.SS " str pip\&._vendor\&.packaging\&.tags\&.Tag\&.interpreter ( self)"

.SS " str pip\&._vendor\&.packaging\&.tags\&.Tag\&.platform ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.packaging\&.tags\&.Tag\&._abi\fC [protected]\fP"

.SS "pip\&._vendor\&.packaging\&.tags\&.Tag\&._hash\fC [protected]\fP"

.SS "pip\&._vendor\&.packaging\&.tags\&.Tag\&._interpreter\fC [protected]\fP"

.SS "pip\&._vendor\&.packaging\&.tags\&.Tag\&._platform\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
