.TH "pip._internal.req.constructors.RequirementParts" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.req.constructors.RequirementParts
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "Optional \fBrequirement\fP [\fBRequirement\fP]"
.br
.ti -1c
.RI "Optional \fBlink\fP [\fBLink\fP]"
.br
.ti -1c
.RI "Optional \fBmarkers\fP [\fBMarker\fP]"
.br
.ti -1c
.RI "Set \fBextras\fP [str]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Set pip\&._internal\&.req\&.constructors\&.RequirementParts\&.extras [str]\fC [static]\fP"

.SS "Optional pip\&._internal\&.req\&.constructors\&.RequirementParts\&.link [\fBLink\fP]\fC [static]\fP"

.SS "Optional pip\&._internal\&.req\&.constructors\&.RequirementParts\&.markers [\fBMarker\fP]\fC [static]\fP"

.SS "Optional pip\&._internal\&.req\&.constructors\&.RequirementParts\&.requirement [\fBRequirement\fP]\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
