.TH "pip._internal.distributions" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.distributions
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbase\fP"
.br
.ti -1c
.RI "namespace \fBinstalled\fP"
.br
.ti -1c
.RI "namespace \fBsdist\fP"
.br
.ti -1c
.RI "namespace \fBwheel\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAbstractDistribution\fP \fBmake_distribution_for_install_requirement\fP (\fBInstallRequirement\fP install_req)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " \fBAbstractDistribution\fP pip\&._internal\&.distributions\&.make_distribution_for_install_requirement (\fBInstallRequirement\fP install_req)"

.PP
.nf
Returns a Distribution for the given InstallRequirement
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
