.TH "pip._vendor.pyproject_hooks._in_process._in_process.BackendUnavailable" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pyproject_hooks._in_process._in_process.BackendUnavailable
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBtraceback\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtraceback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raised if we cannot import the backend
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.BackendUnavailable\&.__init__ ( self,  traceback)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.BackendUnavailable\&.traceback"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
