.TH "pip._internal.commands.show" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.commands.show
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_PackageInfo\fP"
.br
.ti -1c
.RI "class \fBShowCommand\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Generator[\fB_PackageInfo\fP, None, None] \fBsearch_packages_info\fP (List[str] query)"
.br
.ti -1c
.RI "bool \fBprint_results\fP (Iterable[\fB_PackageInfo\fP] distributions, bool list_files, bool verbose)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " bool pip\&._internal\&.commands\&.show\&.print_results (Iterable[\fB_PackageInfo\fP] distributions, bool list_files, bool verbose)"

.PP
.nf
Print the information from installed distributions found\&.

.fi
.PP
 
.SS " Generator[\fB_PackageInfo\fP, None, None] pip\&._internal\&.commands\&.show\&.search_packages_info (List[str] query)"

.PP
.nf
Gather details from installed distributions\&. Print distribution name,
version, location, and installed files\&. Installed files requires a
pip generated 'installed-files\&.txt' in the distributions '\&.egg-info'
directory\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._internal\&.commands\&.show\&.logger = logging\&.getLogger(__name__)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
