.TH "pip._internal.operations.build.metadata_editable" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.operations.build.metadata_editable
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBgenerate_editable_metadata\fP (\fBBuildEnvironment\fP build_env, \fBBuildBackendHookCaller\fP backend, str details)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Metadata generation logic for source distributions\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str pip\&._internal\&.operations\&.build\&.metadata_editable\&.generate_editable_metadata (\fBBuildEnvironment\fP build_env, \fBBuildBackendHookCaller\fP backend, str
 details)"

.PP
.nf
Generate metadata using mechanisms described in PEP 660\&.

Returns the generated metadata directory\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
