.TH "pip._vendor.pkg_resources.ZipManifests" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pkg_resources.ZipManifests
.SH SYNOPSIS
.br
.PP
.PP
Inherits Dict, and str\&.
.PP
Inherited by \fBpip\&._vendor\&.pkg_resources\&.MemoizedZipManifests\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbuild\fP (cls, str path)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBload\fP = \fBbuild\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
zip manifest builder

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.pkg_resources\&.ZipManifests\&.build ( cls, str path)"

.PP
.nf
Build a dictionary similar to the zipimport directory
caches, except instead of tuples, store ZipInfo objects\&.

Use a platform-specific path separator (os\&.sep) for the path keys
for compatibility with pypy on Windows\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.pkg_resources\&.ZipManifests\&.load = \fBbuild\fP\fC [static]\fP"

.PP
Reimplemented in \fBpip\&._vendor\&.pkg_resources\&.MemoizedZipManifests\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
