.TH "pip._vendor.idna.core.InvalidCodepoint" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.idna.core.InvalidCodepoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.idna\&.core\&.IDNAError\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
 Exception when a disallowed or unallocated codepoint is used 
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
