.TH "pip._vendor.rich.style.StyleStack" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.style.StyleStack
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, 'Style' default_style)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBStyle\fP \fBcurrent\fP (self)"
.br
.ti -1c
.RI "None \fBpush\fP (self, \fBStyle\fP style)"
.br
.ti -1c
.RI "\fBStyle\fP \fBpop\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A stack of styles\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.style\&.StyleStack\&.__init__ ( self, 'Style' default_style)"

.SH "Member Function Documentation"
.PP 
.SS " str pip\&._vendor\&.rich\&.style\&.StyleStack\&.__repr__ ( self)"

.SS " \fBStyle\fP pip\&._vendor\&.rich\&.style\&.StyleStack\&.current ( self)"

.PP
.nf
Get the Style at the top of the stack\&.
.fi
.PP
 
.SS " \fBStyle\fP pip\&._vendor\&.rich\&.style\&.StyleStack\&.pop ( self)"

.PP
.nf
Pop last style and discard\&.

Returns:
    Style: New current style (also available as stack\&.current)

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.style\&.StyleStack\&.push ( self, \fBStyle\fP style)"

.PP
.nf
Push a new style on to the stack\&.

Args:
    style (Style): New style to combine with current style\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
