.TH "pip._vendor.distlib.locators.RedirectHandler" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.locators.RedirectHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseRedirectHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhttp_error_302\fP (self, req, fp, code, msg, headers)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBhttp_error_301\fP = \fBhttp_error_302\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A class to work around a bug in some Python 3\&.2\&.x releases\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.locators\&.RedirectHandler\&.http_error_302 ( self,  req,  fp,  code,  msg,  headers)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.locators\&.RedirectHandler\&.http_error_301 = \fBhttp_error_302\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
