.TH "pip._vendor.pygments.lexer.ProfilingRegexLexerMeta" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pygments.lexer.ProfilingRegexLexerMeta
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.pygments\&.lexer\&.RegexLexerMeta\fP\&.
.PP
Inherited by \fBpip\&._vendor\&.pygments\&.lexer\&.ProfilingRegexLexer\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_process_regex\fP (cls, regex, rflags, state)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.pygments\&.lexer\&.RegexLexerMeta\fP
.in +1c
.ti -1c
.RI "\fB_process_token\fP (cls, token)"
.br
.ti -1c
.RI "\fB_process_new_state\fP (cls, new_state, unprocessed, processed)"
.br
.ti -1c
.RI "\fB_process_state\fP (cls, unprocessed, processed, state)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBpip\&._vendor\&.pygments\&.lexer\&.RegexLexerMeta\fP
.in +1c
.ti -1c
.RI "\fBprocess_tokendef\fP (cls, name, tokendefs=None)"
.br
.ti -1c
.RI "\fBget_tokendefs\fP (cls)"
.br
.ti -1c
.RI "\fB__call__\fP (cls, *args, **kwds)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.pygments\&.lexer\&.LexerMeta\fP
.in +1c
.ti -1c
.RI "\fB__new__\fP (mcs, name, bases, d)"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._vendor\&.pygments\&.lexer\&.RegexLexerMeta\fP
.in +1c
.ti -1c
.RI "\fB_all_tokens\fP"
.br
.ti -1c
.RI "\fB_tmpname\fP"
.br
.ti -1c
.RI "\fB_tokens\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Metaclass for ProfilingRegexLexer, collects regex timing info\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.pygments\&.lexer\&.ProfilingRegexLexerMeta\&._process_regex ( cls,  regex,  rflags,  state)\fC [protected]\fP"

.PP
.nf
Preprocess the regular expression component of a token definition\&.
.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.pygments\&.lexer\&.RegexLexerMeta\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
