.TH "pip._vendor.distlib.version.Version" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.version.Version
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpip\&._vendor\&.distlib\&.version\&.LegacyVersion\fP, \fBpip\&._vendor\&.distlib\&.version\&.NormalizedVersion\fP, and \fBpip\&._vendor\&.distlib\&.version\&.SemanticVersion\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, s)"
.br
.ti -1c
.RI "\fBparse\fP (self, s)"
.br
.ti -1c
.RI "\fB__eq__\fP (self, other)"
.br
.ti -1c
.RI "\fB__ne__\fP (self, other)"
.br
.ti -1c
.RI "\fB__lt__\fP (self, other)"
.br
.ti -1c
.RI "\fB__gt__\fP (self, other)"
.br
.ti -1c
.RI "\fB__le__\fP (self, other)"
.br
.ti -1c
.RI "\fB__ge__\fP (self, other)"
.br
.ti -1c
.RI "\fB__hash__\fP (self)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.ti -1c
.RI "\fBis_prerelease\fP (self)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_check_compatible\fP (self, other)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_string\fP"
.br
.ti -1c
.RI "\fB_parts\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__init__ ( self,  s)"

.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__eq__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__ge__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__gt__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__hash__ ( self)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__le__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__lt__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__ne__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__repr__ ( self)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.__str__ ( self)"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&._check_compatible ( self,  other)\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.is_prerelease ( self)"

.PP
Reimplemented in \fBpip\&._vendor\&.distlib\&.version\&.NormalizedVersion\fP, \fBpip\&._vendor\&.distlib\&.version\&.LegacyVersion\fP, and \fBpip\&._vendor\&.distlib\&.version\&.SemanticVersion\fP\&.
.SS "pip\&._vendor\&.distlib\&.version\&.Version\&.parse ( self,  s)"

.PP
Reimplemented in \fBpip\&._vendor\&.distlib\&.version\&.NormalizedVersion\fP, \fBpip\&._vendor\&.distlib\&.version\&.LegacyVersion\fP, and \fBpip\&._vendor\&.distlib\&.version\&.SemanticVersion\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.version\&.Version\&._parts\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.version\&.Version\&._string\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
