.TH "pip._internal.models.direct_url.DirectUrlValidationError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.models.direct_url.DirectUrlValidationError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
