.TH "pip._vendor.rich.control.Control" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.control.Control
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, *Union[\fBControlType\fP, ControlCode] codes)"
.br
.ti -1c
.RI "'Control' \fBbell\fP (cls)"
.br
.ti -1c
.RI "'Control' \fBhome\fP (cls)"
.br
.ti -1c
.RI "'Control' \fBmove\fP (cls, int x=0, int y=0)"
.br
.ti -1c
.RI "'Control' \fBmove_to_column\fP (cls, int x, int y=0)"
.br
.ti -1c
.RI "'Control' \fBmove_to\fP (cls, int x, int y)"
.br
.ti -1c
.RI "'Control' \fBclear\fP (cls)"
.br
.ti -1c
.RI "'Control' \fBshow_cursor\fP (cls, bool show)"
.br
.ti -1c
.RI "'Control' \fBalt_screen\fP (cls, bool enable)"
.br
.ti -1c
.RI "'Control' \fBtitle\fP (cls, str title)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "'RenderResult' \fB__rich_console__\fP (self, 'Console' \fBconsole\fP, 'ConsoleOptions' options)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsegment\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A renderable that inserts a control code (non printable but may move cursor)\&.

Args:
    *codes (str): Positional arguments are either a :class:`~rich\&.segment\&.ControlType` enum or a
        tuple of ControlType and an integer parameter

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.control\&.Control\&.__init__ ( self, *Union[\fBControlType\fP, ControlCode] codes)"

.SH "Member Function Documentation"
.PP 
.SS " 'RenderResult' pip\&._vendor\&.rich\&.control\&.Control\&.__rich_console__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.SS " str pip\&._vendor\&.rich\&.control\&.Control\&.__str__ ( self)"

.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.alt_screen ( cls, bool enable)"

.PP
.nf
Enable or disable alt screen\&.
.fi
.PP
 
.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.bell ( cls)"

.PP
.nf
Ring the 'bell'\&.
.fi
.PP
 
.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.clear ( cls)"

.PP
.nf
Clear the screen\&.
.fi
.PP
 
.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.home ( cls)"

.PP
.nf
Move cursor to 'home' position\&.
.fi
.PP
 
.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.move ( cls, int  x = \fC0\fP, int  y = \fC0\fP)"

.PP
.nf
Move cursor relative to current position\&.

Args:
    x (int): X offset\&.
    y (int): Y offset\&.

Returns:
    ~Control: Control object\&.
.fi
.PP
 
.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.move_to ( cls, int x, int y)"

.PP
.nf
Move cursor to absolute position\&.

Args:
    x (int): x offset (column)
    y (int): y offset (row)

Returns:
    ~Control: Control object\&.

.fi
.PP
 
.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.move_to_column ( cls, int x, int  y = \fC0\fP)"

.PP
.nf
Move to the given column, optionally add offset to row\&.

Returns:
    x (int): absolute x (column)
    y (int): optional y offset (row)

Returns:
    ~Control: Control object\&.

.fi
.PP
 
.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.show_cursor ( cls, bool show)"

.PP
.nf
Show or hide the cursor\&.
.fi
.PP
 
.SS " 'Control' pip\&._vendor\&.rich\&.control\&.Control\&.title ( cls, str title)"

.PP
.nf
Set the terminal window title

Args:
    title (str): The new terminal window title

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.control\&.Control\&.segment"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
