.TH "pip._vendor.distlib.compat.ChainMap" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.compat.ChainMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits MutableMapping\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, *\fBmaps\fP)"
.br
.ti -1c
.RI "\fB__missing__\fP (self, key)"
.br
.ti -1c
.RI "\fB__getitem__\fP (self, key)"
.br
.ti -1c
.RI "\fBget\fP (self, key, default=None)"
.br
.ti -1c
.RI "\fB__len__\fP (self)"
.br
.ti -1c
.RI "\fB__iter__\fP (self)"
.br
.ti -1c
.RI "\fB__contains__\fP (self, key)"
.br
.ti -1c
.RI "\fB__bool__\fP (self)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBfromkeys\fP (cls, iterable, *args)"
.br
.ti -1c
.RI "\fBcopy\fP (self)"
.br
.ti -1c
.RI "\fBnew_child\fP (self)"
.br
.ti -1c
.RI "\fBparents\fP (self)"
.br
.ti -1c
.RI "\fB__setitem__\fP (self, key, value)"
.br
.ti -1c
.RI "\fB__delitem__\fP (self, key)"
.br
.ti -1c
.RI "\fBpopitem\fP (self)"
.br
.ti -1c
.RI "\fBpop\fP (self, key, *args)"
.br
.ti -1c
.RI "\fBclear\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmaps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A ChainMap groups multiple dicts (or other mappings) together
to create a single, updateable view\&.

The underlying mappings are stored in a list\&.  That list is public and can
accessed or updated using the *maps* attribute\&.  There is no other state\&.

Lookups search the underlying mappings successively until a key is found\&.
In contrast, writes, updates, and deletions only operate on the first
mapping\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__init__ ( self, * maps)"

.PP
.nf
Initialize a ChainMap by setting *maps* to the given mappings\&.
If no mappings are provided, a single empty dictionary is used\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__bool__ ( self)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__contains__ ( self,  key)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__delitem__ ( self,  key)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__getitem__ ( self,  key)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__iter__ ( self)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__len__ ( self)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__missing__ ( self,  key)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__repr__ ( self)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.__setitem__ ( self,  key,  value)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.clear ( self)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.copy ( self)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.fromkeys ( cls,  iterable, * args)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.get ( self,  key,  default = \fCNone\fP)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.new_child ( self)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.parents ( self)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.pop ( self,  key, * args)"

.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.popitem ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.compat\&.ChainMap\&.maps"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
