.TH "pip._vendor.packaging.requirements" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging.requirements
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInvalidRequirement\fP"
.br
.ti -1c
.RI "class \fBRequirement\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
