.TH "pip._internal.resolution.base.BaseResolver" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.resolution.base.BaseResolver
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpip\&._internal\&.resolution\&.legacy\&.resolver\&.Resolver\fP, and \fBpip\&._internal\&.resolution\&.resolvelib\&.resolver\&.Resolver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequirementSet\fP \fBresolve\fP (self, List[\fBInstallRequirement\fP] root_reqs, bool check_supported_wheels)"
.br
.ti -1c
.RI "List[\fBInstallRequirement\fP] \fBget_installation_order\fP (self, \fBRequirementSet\fP req_set)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " List[\fBInstallRequirement\fP] pip\&._internal\&.resolution\&.base\&.BaseResolver\&.get_installation_order ( self, \fBRequirementSet\fP
     req_set)"

.PP
Reimplemented in \fBpip\&._internal\&.resolution\&.legacy\&.resolver\&.Resolver\fP, and \fBpip\&._internal\&.resolution\&.resolvelib\&.resolver\&.Resolver\fP\&.
.SS " \fBRequirementSet\fP pip\&._internal\&.resolution\&.base\&.BaseResolver\&.resolve ( self, List[\fBInstallRequirement\fP] root_reqs, bool
     check_supported_wheels)"

.PP
Reimplemented in \fBpip\&._internal\&.resolution\&.legacy\&.resolver\&.Resolver\fP, and \fBpip\&._internal\&.resolution\&.resolvelib\&.resolver\&.Resolver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
