.TH "pip._vendor.rich.align.Align" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.align.Align
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, 'RenderableType' \fBrenderable\fP, \fBAlignMethod\fP \fBalign\fP='left', Optional[StyleType] \fBstyle\fP=None, *Optional[\fBVerticalAlignMethod\fP] \fBvertical\fP=None, bool \fBpad\fP=True, Optional[int] \fBwidth\fP=None, Optional[int] \fBheight\fP=None)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "'Align' \fBleft\fP (cls, 'RenderableType' \fBrenderable\fP, Optional[StyleType] \fBstyle\fP=None, *Optional[\fBVerticalAlignMethod\fP] \fBvertical\fP=None, bool \fBpad\fP=True, Optional[int] \fBwidth\fP=None, Optional[int] \fBheight\fP=None)"
.br
.ti -1c
.RI "'Align' \fBcenter\fP (cls, 'RenderableType' \fBrenderable\fP, Optional[StyleType] \fBstyle\fP=None, *Optional[\fBVerticalAlignMethod\fP] \fBvertical\fP=None, bool \fBpad\fP=True, Optional[int] \fBwidth\fP=None, Optional[int] \fBheight\fP=None)"
.br
.ti -1c
.RI "'Align' \fBright\fP (cls, 'RenderableType' \fBrenderable\fP, Optional[StyleType] \fBstyle\fP=None, *Optional[\fBVerticalAlignMethod\fP] \fBvertical\fP=None, bool \fBpad\fP=True, Optional[int] \fBwidth\fP=None, Optional[int] \fBheight\fP=None)"
.br
.ti -1c
.RI "'RenderResult' \fB__rich_console__\fP (self, 'Console' \fBconsole\fP, 'ConsoleOptions' options)"
.br
.ti -1c
.RI "\fBMeasurement\fP \fB__rich_measure__\fP (self, 'Console' \fBconsole\fP, 'ConsoleOptions' options)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrenderable\fP"
.br
.ti -1c
.RI "\fBalign\fP"
.br
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBvertical\fP"
.br
.ti -1c
.RI "\fBpad\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.ti -1c
.RI "\fBheight\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP
.in +1c
.ti -1c
.RI "Dict[str, str] \fB_repr_mimebundle_\fP ('ConsoleRenderable' self, Sequence[str] include, Sequence[str] exclude, **Any kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Align a renderable by adding spaces if necessary\&.

Args:
    renderable (RenderableType): A console renderable\&.
    align (AlignMethod): One of 'left', 'center', or 'right''
    style (StyleType, optional): An optional style to apply to the background\&.
    vertical (Optional[VerticalAlignMethod], optional): Optional vertical align, one of 'top', 'middle', or 'bottom'\&. Defaults to None\&.
    pad (bool, optional): Pad the right with spaces\&. Defaults to True\&.
    width (int, optional): Restrict contents to given width, or None to use default width\&. Defaults to None\&.
    height (int, optional): Set height of align renderable, or None to fit to contents\&. Defaults to None\&.

Raises:
    ValueError: if ``align`` is not one of the expected values\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.align\&.Align\&.__init__ ( self, 'RenderableType' renderable, \fBAlignMethod\fP  align = \fC'left'\fP, Optional[StyleType]  style = \fCNone\fP, *Optional[\fBVerticalAlignMethod\fP]  vertical = \fCNone\fP, bool  pad = \fCTrue\fP, Optional[int]  width = \fCNone\fP, Optional[int]  height = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS " str pip\&._vendor\&.rich\&.align\&.Align\&.__repr__ ( self)"

.SS " 'RenderResult' pip\&._vendor\&.rich\&.align\&.Align\&.__rich_console__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.SS " \fBMeasurement\fP pip\&._vendor\&.rich\&.align\&.Align\&.__rich_measure__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.SS " 'Align' pip\&._vendor\&.rich\&.align\&.Align\&.center ( cls, 'RenderableType' renderable, Optional[StyleType]  style = \fCNone\fP, *Optional[\fBVerticalAlignMethod\fP]  vertical = \fCNone\fP, bool  pad = \fCTrue\fP, Optional[int]  width = \fCNone\fP, Optional[int]  height = \fCNone\fP)"

.PP
.nf
Align a renderable to the center\&.
.fi
.PP
 
.SS " 'Align' pip\&._vendor\&.rich\&.align\&.Align\&.left ( cls, 'RenderableType' renderable, Optional[StyleType]  style = \fCNone\fP, *Optional[\fBVerticalAlignMethod\fP]  vertical = \fCNone\fP, bool  pad = \fCTrue\fP, Optional[int]  width = \fCNone\fP, Optional[int]  height = \fCNone\fP)"

.PP
.nf
Align a renderable to the left\&.
.fi
.PP
 
.SS " 'Align' pip\&._vendor\&.rich\&.align\&.Align\&.right ( cls, 'RenderableType' renderable, Optional[StyleType]  style = \fCNone\fP, *Optional[\fBVerticalAlignMethod\fP]  vertical = \fCNone\fP, bool  pad = \fCTrue\fP, Optional[int]  width = \fCNone\fP, Optional[int]  height = \fCNone\fP)"

.PP
.nf
Align a renderable to the right\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.align\&.Align\&.align"

.SS "pip\&._vendor\&.rich\&.align\&.Align\&.height"

.SS "pip\&._vendor\&.rich\&.align\&.Align\&.pad"

.SS "pip\&._vendor\&.rich\&.align\&.Align\&.renderable"

.SS "pip\&._vendor\&.rich\&.align\&.Align\&.style"

.SS "pip\&._vendor\&.rich\&.align\&.Align\&.vertical"

.SS "pip\&._vendor\&.rich\&.align\&.Align\&.width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
