.TH "pip._vendor.urllib3.contrib.securetransport" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.contrib.securetransport
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSecureTransportContext\fP"
.br
.ti -1c
.RI "class \fBWrappedSocket\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinject_into_urllib3\fP ()"
.br
.ti -1c
.RI "\fBextract_from_urllib3\fP ()"
.br
.ti -1c
.RI "\fB_read_callback\fP (connection_id, data_buffer, data_length_pointer)"
.br
.ti -1c
.RI "\fB_write_callback\fP (connection_id, data_buffer, data_length_pointer)"
.br
.ti -1c
.RI "\fBmakefile\fP (self, mode, bufsize=\-1)"
.br
.ti -1c
.RI "\fBmakefile\fP (self, mode='r', buffering=None, *args, **kwargs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_fileobject\fP = None"
.br
.ti -1c
.RI "bool \fBHAS_SNI\fP = True"
.br
.ti -1c
.RI "bool \fBorig_util_HAS_SNI\fP = util\&.HAS_SNI"
.br
.ti -1c
.RI "\fBorig_util_SSLContext\fP = \fButil\&.ssl_\&.SSLContext\fP"
.br
.ti -1c
.RI "\fB_connection_refs\fP = weakref\&.WeakValueDictionary()"
.br
.ti -1c
.RI "\fB_connection_ref_lock\fP = threading\&.Lock()"
.br
.ti -1c
.RI "int \fBSSL_WRITE_BLOCKSIZE\fP = 16384"
.br
.ti -1c
.RI "list \fBCIPHER_SUITES\fP"
.br
.ti -1c
.RI "dict \fB_protocol_to_min_max\fP"
.br
.ti -1c
.RI "\fB_read_callback_pointer\fP = Security\&.SSLReadFunc(\fB_read_callback\fP)"
.br
.ti -1c
.RI "\fB_write_callback_pointer\fP = Security\&.SSLWriteFunc(\fB_write_callback\fP)"
.br
.ti -1c
.RI "\fBmakefile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
SecureTranport support for urllib3 via ctypes\&.

This makes platform-native TLS available to urllib3 users on macOS without the
use of a compiler\&. This is an important feature because the Python Package
Index is moving to become a TLSv1\&.2-or-higher server, and the default OpenSSL
that ships with macOS is not capable of doing TLSv1\&.2\&. The only way to resolve
this is to give macOS users an alternative solution to the problem, and that
solution is to use SecureTransport\&.

We use ctypes here because this solution must not require a compiler\&. That's
because pip is not allowed to require a compiler either\&.

This is not intended to be a seriously long-term solution to this problem\&.
The hope is that PEP 543 will eventually solve this issue for us, at which
point we can retire this contrib module\&. But in the short term, we need to
solve the impending tire fire that is Python on Mac without this kind of
contrib module\&. So\&.\&.\&.here we are\&.

To use this module, simply import and inject it::

    import pip\&._vendor\&.urllib3\&.contrib\&.securetransport as securetransport
    securetransport\&.inject_into_urllib3()

Happy TLSing!

This code is a bastardised version of the code found in Will Bond's oscrypto
library\&. An enormous debt is owed to him for blazing this trail for us\&. For
that reason, this code should be considered to be covered both by urllib3's
license and by oscrypto's:

\&.\&. code-block::

    Copyright (c) 2015-2016 Will Bond <will@wbond\&.net>

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the 'Software'),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software\&.

    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&._read_callback ( connection_id,  data_buffer,  data_length_pointer)\fC [protected]\fP"

.PP
.nf
SecureTransport read callback\&. This is called by ST to request that data
be returned from the socket\&.

.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&._write_callback ( connection_id,  data_buffer,  data_length_pointer)\fC [protected]\fP"

.PP
.nf
SecureTransport write callback\&. This is called by ST to request that data
actually be sent on the network\&.

.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.extract_from_urllib3 ()"

.PP
.nf
Undo monkey-patching by :func:`inject_into_urllib3`\&.

.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.inject_into_urllib3 ()"

.PP
.nf
Monkey-patch urllib3 with SecureTransport-backed SSL-support\&.

.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.makefile ( self,  mode,  bufsize = \fC\-1\fP)"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.makefile ( self,  mode = \fC'r'\fP,  buffering = \fCNone\fP, * args, ** kwargs)"

.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&._connection_ref_lock = threading\&.Lock()\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&._connection_refs = weakref\&.WeakValueDictionary()\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&._fileobject = None\fC [protected]\fP"

.SS "dict pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&._protocol_to_min_max\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  {
2     util\&.PROTOCOL_TLS: (SecurityConst\&.kTLSProtocol1, SecurityConst\&.kTLSProtocol12),
3     PROTOCOL_TLS_CLIENT: (SecurityConst\&.kTLSProtocol1, SecurityConst\&.kTLSProtocol12),
4 }
.fi

.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&._read_callback_pointer = Security\&.SSLReadFunc(\fB_read_callback\fP)\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&._write_callback_pointer = Security\&.SSLWriteFunc(\fB_write_callback\fP)\fC [protected]\fP"

.SS "list pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.CIPHER_SUITES"

.SS "bool pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.HAS_SNI = True"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.makefile"

.SS "bool pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.orig_util_HAS_SNI = util\&.HAS_SNI"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.orig_util_SSLContext = \fButil\&.ssl_\&.SSLContext\fP"

.SS "int pip\&._vendor\&.urllib3\&.contrib\&.securetransport\&.SSL_WRITE_BLOCKSIZE = 16384"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
