.TH "pip._vendor.rich.color.Color" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.color.Color
.SH SYNOPSIS
.br
.PP
.PP
Inherits NamedTuple\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "'Text' \fB__rich__\fP (self)"
.br
.ti -1c
.RI "Result \fB__rich_repr__\fP (self)"
.br
.ti -1c
.RI "\fBColorSystem\fP \fBsystem\fP (self)"
.br
.ti -1c
.RI "bool \fBis_system_defined\fP (self)"
.br
.ti -1c
.RI "bool \fBis_default\fP (self)"
.br
.ti -1c
.RI "\fBColorTriplet\fP \fBget_truecolor\fP (self, Optional['TerminalTheme'] theme=None, bool foreground=True)"
.br
.ti -1c
.RI "'Color' \fBfrom_ansi\fP (cls, int \fBnumber\fP)"
.br
.ti -1c
.RI "'Color' \fBfrom_triplet\fP (cls, 'ColorTriplet' \fBtriplet\fP)"
.br
.ti -1c
.RI "'Color' \fBfrom_rgb\fP (cls, float red, float green, float blue)"
.br
.ti -1c
.RI "'Color' \fBdefault\fP (cls)"
.br
.ti -1c
.RI "'Color' \fBparse\fP (cls, str \fBcolor\fP)"
.br
.ti -1c
.RI "Tuple[str,\&.\&.\&.] \fBget_ansi_codes\fP (self, bool foreground=True)"
.br
.ti -1c
.RI "'Color' \fBdowngrade\fP (self, \fBColorSystem\fP \fBsystem\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnumber\fP"
.br
.ti -1c
.RI "\fBtriplet\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBsystem\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP"
.br
.ti -1c
.RI "\fBColorType\fP \fBtype\fP"
.br
.ti -1c
.RI "Optional \fBnumber\fP = None"
.br
.ti -1c
.RI "Optional \fBtriplet\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Terminal color definition\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " 'Text' pip\&._vendor\&.rich\&.color\&.Color\&.__rich__ ( self)"

.PP
.nf
Displays the actual color if Rich printed\&.
.fi
.PP
 
.SS " Result pip\&._vendor\&.rich\&.color\&.Color\&.__rich_repr__ ( self)"

.SS " 'Color' pip\&._vendor\&.rich\&.color\&.Color\&.default ( cls)"

.PP
.nf
Get a Color instance representing the default color\&.

Returns:
    Color: Default color\&.

.fi
.PP
 
.SS " 'Color' pip\&._vendor\&.rich\&.color\&.Color\&.downgrade ( self, \fBColorSystem\fP system)"

.PP
.nf
Downgrade a color system to a system with fewer colors\&.
.fi
.PP
 
.SS " 'Color' pip\&._vendor\&.rich\&.color\&.Color\&.from_ansi ( cls, int number)"

.PP
.nf
Create a Color number from it's 8-bit ansi number\&.

Args:
    number (int): A number between 0-255 inclusive\&.

Returns:
    Color: A new Color instance\&.

.fi
.PP
 
.SS " 'Color' pip\&._vendor\&.rich\&.color\&.Color\&.from_rgb ( cls, float red, float green, float blue)"

.PP
.nf
Create a truecolor from three color components in the range(0->255)\&.

Args:
    red (float): Red component in range 0-255\&.
    green (float): Green component in range 0-255\&.
    blue (float): Blue component in range 0-255\&.

Returns:
    Color: A new color object\&.

.fi
.PP
 
.SS " 'Color' pip\&._vendor\&.rich\&.color\&.Color\&.from_triplet ( cls, 'ColorTriplet' triplet)"

.PP
.nf
Create a truecolor RGB color from a triplet of values\&.

Args:
    triplet (ColorTriplet): A color triplet containing red, green and blue components\&.

Returns:
    Color: A new color object\&.

.fi
.PP
 
.SS " Tuple[str, \&.\&.\&.] pip\&._vendor\&.rich\&.color\&.Color\&.get_ansi_codes ( self, bool  foreground = \fCTrue\fP)"

.PP
.nf
Get the ANSI escape codes for this color\&.
.fi
.PP
 
.SS " \fBColorTriplet\fP pip\&._vendor\&.rich\&.color\&.Color\&.get_truecolor ( self, Optional['TerminalTheme']  theme = \fCNone\fP, bool  foreground = \fCTrue\fP)"

.PP
.nf
Get an equivalent color triplet for this color\&.

Args:
    theme (TerminalTheme, optional): Optional terminal theme, or None to use default\&. Defaults to None\&.
    foreground (bool, optional): True for a foreground color, or False for background\&. Defaults to True\&.

Returns:
    ColorTriplet: A color triplet containing RGB components\&.

.fi
.PP
 
.SS " bool pip\&._vendor\&.rich\&.color\&.Color\&.is_default ( self)"

.PP
.nf
Check if the color is a default color\&.
.fi
.PP
 
.SS " bool pip\&._vendor\&.rich\&.color\&.Color\&.is_system_defined ( self)"

.PP
.nf
Check if the color is ultimately defined by the system\&.
.fi
.PP
 
.SS " 'Color' pip\&._vendor\&.rich\&.color\&.Color\&.parse ( cls, str color)"

.PP
.nf
Parse a color definition\&.
.fi
.PP
 
.SS " \fBColorSystem\fP pip\&._vendor\&.rich\&.color\&.Color\&.system ( self)"

.PP
.nf
Get the native color system for this color\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "str pip\&._vendor\&.rich\&.color\&.Color\&.name\fC [static]\fP"

.SS "pip\&._vendor\&.rich\&.color\&.Color\&.name"

.SS "Optional pip\&._vendor\&.rich\&.color\&.Color\&.number = None\fC [static]\fP"

.SS "pip\&._vendor\&.rich\&.color\&.Color\&.number"

.SS "pip\&._vendor\&.rich\&.color\&.Color\&.system"

.SS "Optional pip\&._vendor\&.rich\&.color\&.Color\&.triplet = None\fC [static]\fP"

.SS "pip\&._vendor\&.rich\&.color\&.Color\&.triplet"

.SS "\fBColorType\fP pip\&._vendor\&.rich\&.color\&.Color\&.type\fC [static]\fP"

.SS "pip\&._vendor\&.rich\&.color\&.Color\&.type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
