.TH "pip._vendor.rich._windows_renderer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._windows_renderer
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBlegacy_windows_render\fP (Iterable[\fBSegment\fP] buffer, \fBLegacyWindowsTerm\fP term)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&._windows_renderer\&.legacy_windows_render (Iterable[\fBSegment\fP] buffer, \fBLegacyWindowsTerm\fP term)"

.PP
.nf
Makes appropriate Windows Console API calls based on the segments in the buffer\&.

Args:
    buffer (Iterable[Segment]): Iterable of Segments to convert to Win32 API calls\&.
    term (LegacyWindowsTerm): Used to call the Windows Console API\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
