.TH "pip._vendor.idna.codec.StreamWriter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.idna.codec.StreamWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.idna\&.codec\&.Codec\fP, and codecs\&.StreamWriter\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBpip\&._vendor\&.idna\&.codec\&.Codec\fP
.in +1c
.ti -1c
.RI "Tuple[bytes, int] \fBencode\fP (self, str data, str errors='strict')"
.br
.ti -1c
.RI "Tuple[str, int] \fBdecode\fP (self, bytes data, str errors='strict')"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
