.TH "pip._vendor.rich._inspect" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._inspect
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInspect\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fB_first_paragraph\fP (str doc)"
.br
.ti -1c
.RI "Tuple[type,\&.\&.\&.] \fBget_object_types_mro\fP (Union[object, Type[Any]] obj)"
.br
.ti -1c
.RI "Collection[str] \fBget_object_types_mro_as_strings\fP (object obj)"
.br
.ti -1c
.RI "bool \fBis_object_one_of_types\fP (object obj, Collection[str] fully_qualified_types_names)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " str pip\&._vendor\&.rich\&._inspect\&._first_paragraph (str doc)\fC [protected]\fP"

.PP
.nf
Get the first paragraph from a docstring\&.
.fi
.PP
 
.SS " Tuple[type, \&.\&.\&.] pip\&._vendor\&.rich\&._inspect\&.get_object_types_mro (Union[object, Type[Any]] obj)"

.PP
.nf
Returns the MRO of an object's class, or of the object itself if it's a class\&.
.fi
.PP
 
.SS " Collection[str] pip\&._vendor\&.rich\&._inspect\&.get_object_types_mro_as_strings (object obj)"

.PP
.nf
Returns the MRO of an object's class as full qualified names, or of the object itself if it's a class\&.

Examples:
    `object_types_mro_as_strings(JSONDecoder)` will return `['json\&.decoder\&.JSONDecoder', 'builtins\&.object']`

.fi
.PP
 
.SS " bool pip\&._vendor\&.rich\&._inspect\&.is_object_one_of_types (object obj, Collection[str]
 fully_qualified_types_names)"

.PP
.nf
Returns `True` if the given object's class (or the object itself, if it's a class) has one of the
fully qualified names in its MRO\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
