.TH "pip._vendor.rich.console.ScreenUpdate" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.console.ScreenUpdate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, List[List[\fBSegment\fP]] lines, int \fBx\fP, int \fBy\fP)"
.br
.ti -1c
.RI "\fBRenderResult\fP \fB__rich_console__\fP (self, 'Console' \fBconsole\fP, \fBConsoleOptions\fP options)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_lines\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Render a list of lines at a given offset\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.console\&.ScreenUpdate\&.__init__ ( self, List[List[\fBSegment\fP]] lines, int x, int y)"

.SH "Member Function Documentation"
.PP 
.SS " \fBRenderResult\fP pip\&._vendor\&.rich\&.console\&.ScreenUpdate\&.__rich_console__ ( self, 'Console' console, \fBConsoleOptions\fP
     options)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.console\&.ScreenUpdate\&._lines\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.console\&.ScreenUpdate\&.x"

.SS "pip\&._vendor\&.rich\&.console\&.ScreenUpdate\&.y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
