.TH "pip._vendor.rich._stack.Stack" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._stack.Stack
.SH SYNOPSIS
.br
.PP
.PP
Inherits List, and T\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBT\fP \fBtop\fP (self)"
.br
.ti -1c
.RI "None \fBpush\fP (self, \fBT\fP item)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A small shim over builtin list\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&._stack\&.Stack\&.push ( self, \fBT\fP item)"

.PP
.nf
Push an item on to the stack (append in stack nomenclature)\&.
.fi
.PP
 
.SS " \fBT\fP pip\&._vendor\&.rich\&._stack\&.Stack\&.top ( self)"

.PP
.nf
Get top of stack\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
