.TH "pip._internal.cli.parser.ConfigOptionParser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.cli.parser.ConfigOptionParser
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._internal\&.cli\&.parser\&.CustomOptionParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, *Any args, str \fBname\fP, bool isolated=False, **Any kwargs)"
.br
.ti -1c
.RI "Any \fBcheck_default\fP (self, optparse\&.Option option, str key, Any val)"
.br
.ti -1c
.RI "optparse\&.Values \fBget_default_values\fP (self)"
.br
.ti -1c
.RI "NoReturn \fBerror\fP (self, str msg)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._internal\&.cli\&.parser\&.CustomOptionParser\fP
.in +1c
.ti -1c
.RI "optparse\&.OptionGroup \fBinsert_option_group\fP (self, int idx, *Any args, **Any kwargs)"
.br
.ti -1c
.RI "List[optparse\&.Option] \fBoption_list_all\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBvalues\fP"
.br
.ti -1c
.RI "\fBdefaults\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Generator[Tuple[str, Any], None, None] \fB_get_ordered_configuration_items\fP (self)"
.br
.ti -1c
.RI "Dict[str, Any] \fB_update_defaults\fP (self, Dict[str, Any] \fBdefaults\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Custom option parser which updates its defaults by checking the
configuration files and environmental variables
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&.__init__ ( self, *Any args, str name, bool  isolated = \fCFalse\fP, **Any kwargs)"

.SH "Member Function Documentation"
.PP 
.SS " Generator[Tuple[str, Any], None, None] pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&._get_ordered_configuration_items ( self)\fC [protected]\fP"

.SS " Dict[str, Any] pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&._update_defaults ( self, Dict[str, Any] defaults)\fC [protected]\fP"

.PP
.nf
Updates the given defaults with values from the config files and
the environ\&. Does a little special handling for certain types of
options (lists)\&.
.fi
.PP
 
.SS " Any pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&.check_default ( self, optparse\&.Option option, str key, Any val)"

.SS " NoReturn pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&.error ( self, str msg)"

.SS " optparse\&.Values pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&.get_default_values ( self)"

.PP
.nf
Overriding to make updating the defaults after instantiation of
the option parser possible, _update_defaults() does the dirty work\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&.config"

.SS "pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&.defaults"

.SS "pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&.name"

.SS "pip\&._internal\&.cli\&.parser\&.ConfigOptionParser\&.values"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
