.TH "pip._vendor.rich.containers.Lines" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.containers.Lines
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, Iterable['Text'] lines=())"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "Iterator['Text'] \fB__iter__\fP (self)"
.br
.ti -1c
.RI "'Text' \fB__getitem__\fP (self, int index)"
.br
.ti -1c
.RI "List['Text'] \fB__getitem__\fP (self, slice index)"
.br
.ti -1c
.RI "Union['Text', List['Text']] \fB__getitem__\fP (self, Union[slice, int] index)"
.br
.ti -1c
.RI "'Lines' \fB__setitem__\fP (self, int index, 'Text' value)"
.br
.ti -1c
.RI "int \fB__len__\fP (self)"
.br
.ti -1c
.RI "'RenderResult' \fB__rich_console__\fP (self, 'Console' console, 'ConsoleOptions' options)"
.br
.ti -1c
.RI "None \fBappend\fP (self, 'Text' line)"
.br
.ti -1c
.RI "None \fBextend\fP (self, Iterable['Text'] lines)"
.br
.ti -1c
.RI "'Text' \fBpop\fP (self, int index=\-1)"
.br
.ti -1c
.RI "None \fBjustify\fP (self, 'Console' console, int width, 'JustifyMethod' justify='left', 'OverflowMethod' overflow='fold')"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_lines\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A list subclass which can render to the console\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.containers\&.Lines\&.__init__ ( self, Iterable['Text']  lines = \fC()\fP)"

.SH "Member Function Documentation"
.PP 
.SS " 'Text' pip\&._vendor\&.rich\&.containers\&.Lines\&.__getitem__ ( self, int index)"

.SS " List['Text'] pip\&._vendor\&.rich\&.containers\&.Lines\&.__getitem__ ( self, slice index)"

.SS " Union['Text', List['Text']] pip\&._vendor\&.rich\&.containers\&.Lines\&.__getitem__ ( self, Union[slice, int] index)"

.SS " Iterator['Text'] pip\&._vendor\&.rich\&.containers\&.Lines\&.__iter__ ( self)"

.SS " int pip\&._vendor\&.rich\&.containers\&.Lines\&.__len__ ( self)"

.SS " str pip\&._vendor\&.rich\&.containers\&.Lines\&.__repr__ ( self)"

.SS " 'RenderResult' pip\&._vendor\&.rich\&.containers\&.Lines\&.__rich_console__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.PP
.nf
Console render method to insert line-breaks\&.
.fi
.PP
 
.SS " 'Lines' pip\&._vendor\&.rich\&.containers\&.Lines\&.__setitem__ ( self, int index, 'Text' value)"

.SS " None pip\&._vendor\&.rich\&.containers\&.Lines\&.append ( self, 'Text' line)"

.SS " None pip\&._vendor\&.rich\&.containers\&.Lines\&.extend ( self, Iterable['Text'] lines)"

.SS " None pip\&._vendor\&.rich\&.containers\&.Lines\&.justify ( self, 'Console' console, int width, 'JustifyMethod'  justify = \fC'left'\fP, 'OverflowMethod'  overflow = \fC'fold'\fP)"

.PP
.nf
Justify and overflow text to a given width\&.

Args:
    console (Console): Console instance\&.
    width (int): Number of cells available per line\&.
    justify (str, optional): Default justify method for text: 'left', 'center', 'full' or 'right'\&. Defaults to 'left'\&.
    overflow (str, optional): Default overflow for text: 'crop', 'fold', or 'ellipsis'\&. Defaults to 'fold'\&.
.fi
.PP
 
.SS " 'Text' pip\&._vendor\&.rich\&.containers\&.Lines\&.pop ( self, int  index = \fC\-1\fP)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.containers\&.Lines\&._lines\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
