.TH "pip._internal.exceptions.MetadataGenerationFailed" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.exceptions.MetadataGenerationFailed
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._internal\&.exceptions\&.InstallationSubprocessError\fP, and \fBpip\&._internal\&.exceptions\&.InstallationError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, *str package_details)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._internal\&.exceptions\&.DiagnosticPipError\fP
.in +1c
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "RenderResult \fB__rich_console__\fP (self, \fBConsole\fP console, \fBConsoleOptions\fP options)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBreference\fP = 'metadata\-generation\-failed'"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._internal\&.exceptions\&.InstallationSubprocessError\fP
.in +1c
.ti -1c
.RI "str \fBreference\fP = 'subprocess\-exited\-with\-error'"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._internal\&.exceptions\&.DiagnosticPipError\fP
.in +1c
.ti -1c
.RI "str \fBreference\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBpip\&._internal\&.exceptions\&.InstallationSubprocessError\fP
.in +1c
.ti -1c
.RI "\fBcommand_description\fP"
.br
.ti -1c
.RI "\fBexit_code\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._internal\&.exceptions\&.DiagnosticPipError\fP
.in +1c
.ti -1c
.RI "\fBkind\fP"
.br
.ti -1c
.RI "\fBreference\fP"
.br
.ti -1c
.RI "\fBmessage\fP"
.br
.ti -1c
.RI "\fBcontext\fP"
.br
.ti -1c
.RI "\fBnote_stmt\fP"
.br
.ti -1c
.RI "\fBhint_stmt\fP"
.br
.ti -1c
.RI "\fBlink\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.exceptions\&.MetadataGenerationFailed\&.__init__ ( self, *str package_details)"

.PP
Reimplemented from \fBpip\&._internal\&.exceptions\&.InstallationSubprocessError\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " str pip\&._internal\&.exceptions\&.MetadataGenerationFailed\&.__str__ ( self)"

.PP
Reimplemented from \fBpip\&._internal\&.exceptions\&.InstallationSubprocessError\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str pip\&._internal\&.exceptions\&.MetadataGenerationFailed\&.reference = 'metadata\-generation\-failed'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
