.TH "pip._vendor.rich.emoji.Emoji" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.emoji.Emoji
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBname\fP, Union[str, \fBStyle\fP] \fBstyle\fP='none', Optional[\fBEmojiVariant\fP] \fBvariant\fP=None)"
.br
.ti -1c
.RI "str \fBreplace\fP (cls, str text)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "'RenderResult' \fB__rich_console__\fP (self, 'Console' \fBconsole\fP, 'ConsoleOptions' options)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBvariant\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dict \fBVARIANTS\fP = {'text': '\\uFE0E', 'emoji': '\\uFE0F'}"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_char\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP
.in +1c
.ti -1c
.RI "Dict[str, str] \fB_repr_mimebundle_\fP ('ConsoleRenderable' self, Sequence[str] include, Sequence[str] exclude, **Any kwargs)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.emoji\&.Emoji\&.__init__ ( self, str name, Union[str, \fBStyle\fP]  style = \fC'none'\fP, Optional[\fBEmojiVariant\fP]  variant = \fCNone\fP)"

.PP
.nf
A single emoji character\&.

Args:
    name (str): Name of emoji\&.
    style (Union[str, Style], optional): Optional style\&. Defaults to None\&.

Raises:
    NoEmoji: If the emoji doesn't exist\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str pip\&._vendor\&.rich\&.emoji\&.Emoji\&.__repr__ ( self)"

.SS " 'RenderResult' pip\&._vendor\&.rich\&.emoji\&.Emoji\&.__rich_console__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.SS " str pip\&._vendor\&.rich\&.emoji\&.Emoji\&.__str__ ( self)"

.SS " str pip\&._vendor\&.rich\&.emoji\&.Emoji\&.replace ( cls, str text)"

.PP
.nf
Replace emoji markup with corresponding unicode characters\&.

Args:
    text (str): A string with emojis codes, e\&.g\&. 'Hello :smiley:!'

Returns:
    str: A string with emoji codes replaces with actual emoji\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.emoji\&.Emoji\&._char\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.emoji\&.Emoji\&.name"

.SS "pip\&._vendor\&.rich\&.emoji\&.Emoji\&.style"

.SS "pip\&._vendor\&.rich\&.emoji\&.Emoji\&.variant"

.SS "dict pip\&._vendor\&.rich\&.emoji\&.Emoji\&.VARIANTS = {'text': '\\uFE0E', 'emoji': '\\uFE0F'}\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
