.TH "pip._vendor.rich._timer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._timer
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "Generator[None, None, None] \fBtimer\fP (str subject='time')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Timer context manager, only used in debug\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " Generator[None, None, None] pip\&._vendor\&.rich\&._timer\&.timer (str  subject = \fC'time'\fP)"

.PP
.nf
print the elapsed time\&. (only used in debugging)
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
