.TH "pip._vendor.packaging.specifiers" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging.specifiers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseSpecifier\fP"
.br
.ti -1c
.RI "class \fBInvalidSpecifier\fP"
.br
.ti -1c
.RI "class \fBSpecifier\fP"
.br
.ti -1c
.RI "class \fBSpecifierSet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBVersion\fP \fB_coerce_version\fP (\fBUnparsedVersion\fP version)"
.br
.ti -1c
.RI "list[str] \fB_version_split\fP (str version)"
.br
.ti -1c
.RI "str \fB_version_join\fP (list[str] components)"
.br
.ti -1c
.RI "bool \fB_is_not_suffix\fP (str segment)"
.br
.ti -1c
.RI "tuple[list[str], list[str]] \fB_pad_version\fP (list[str] left, list[str] right)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUnparsedVersion\fP = Union[\fBVersion\fP, str]"
.br
.ti -1c
.RI "\fBUnparsedVersionVar\fP = TypeVar('UnparsedVersionVar', bound=\fBUnparsedVersion\fP)"
.br
.ti -1c
.RI "\fBCallableOperator\fP = Callable[[\fBVersion\fP, str], bool]"
.br
.ti -1c
.RI "\fB_prefix_regex\fP = re\&.compile(r'^([0\-9]+)((?:a|b|c|rc)[0\-9]+)$')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
\&.\&. testsetup::

    from pip\&._vendor\&.packaging\&.specifiers import Specifier, SpecifierSet, InvalidSpecifier
    from pip\&._vendor\&.packaging\&.version import Version

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fBVersion\fP pip\&._vendor\&.packaging\&.specifiers\&._coerce_version (\fBUnparsedVersion\fP version)\fC [protected]\fP"

.SS " bool pip\&._vendor\&.packaging\&.specifiers\&._is_not_suffix (str segment)\fC [protected]\fP"

.SS " tuple[list[str], list[str]] pip\&._vendor\&.packaging\&.specifiers\&._pad_version (list[str] left, list[str] right)\fC [protected]\fP"

.SS " str pip\&._vendor\&.packaging\&.specifiers\&._version_join (list[str] components)\fC [protected]\fP"

.PP
.nf
Join split version components into a version string\&.

This function assumes the input came from :func:`_version_split`, where the
first component must be the epoch (either empty or numeric), and all other
components numeric\&.

.fi
.PP
 
.SS " list[str] pip\&._vendor\&.packaging\&.specifiers\&._version_split (str version)\fC [protected]\fP"

.PP
.nf
Split version into components\&.

The split components are intended for version comparison\&. The logic does
not attempt to retain the original version string, so joining the
components back with :func:`_version_join` may not produce the original
version string\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.packaging\&.specifiers\&._prefix_regex = re\&.compile(r'^([0\-9]+)((?:a|b|c|rc)[0\-9]+)$')\fC [protected]\fP"

.SS "pip\&._vendor\&.packaging\&.specifiers\&.CallableOperator = Callable[[\fBVersion\fP, str], bool]"

.SS "pip\&._vendor\&.packaging\&.specifiers\&.UnparsedVersion = Union[\fBVersion\fP, str]"

.SS "pip\&._vendor\&.packaging\&.specifiers\&.UnparsedVersionVar = TypeVar('UnparsedVersionVar', bound=\fBUnparsedVersion\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
