.TH "pip._vendor.cachecontrol.cache.BaseCache" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.cachecontrol.cache.BaseCache
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpip\&._vendor\&.cachecontrol\&.cache\&.DictCache\fP, \fBpip\&._vendor\&.cachecontrol\&.cache\&.SeparateBodyBaseCache\fP, \fBpip\&._vendor\&.cachecontrol\&.caches\&.file_cache\&.FileCache\fP, and \fBpip\&._vendor\&.cachecontrol\&.caches\&.redis_cache\&.RedisCache\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bytes|None \fBget\fP (self, str key)"
.br
.ti -1c
.RI "None \fBset\fP (self, str key, bytes value, int|datetime|None expires=None)"
.br
.ti -1c
.RI "None \fBdelete\fP (self, str key)"
.br
.ti -1c
.RI "None \fBclose\fP (self)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " None pip\&._vendor\&.cachecontrol\&.cache\&.BaseCache\&.close ( self)"

.PP
Reimplemented in \fBpip\&._vendor\&.cachecontrol\&.caches\&.redis_cache\&.RedisCache\fP\&.
.SS " None pip\&._vendor\&.cachecontrol\&.cache\&.BaseCache\&.delete ( self, str key)"

.PP
Reimplemented in \fBpip\&._internal\&.network\&.cache\&.SafeFileCache\fP, \fBpip\&._vendor\&.cachecontrol\&.cache\&.DictCache\fP, \fBpip\&._vendor\&.cachecontrol\&.caches\&.file_cache\&.FileCache\fP, \fBpip\&._vendor\&.cachecontrol\&.caches\&.file_cache\&.SeparateBodyFileCache\fP, and \fBpip\&._vendor\&.cachecontrol\&.caches\&.redis_cache\&.RedisCache\fP\&.
.SS " bytes | None pip\&._vendor\&.cachecontrol\&.cache\&.BaseCache\&.get ( self, str key)"

.PP
Reimplemented in \fBpip\&._internal\&.network\&.cache\&.SafeFileCache\fP, \fBpip\&._vendor\&.cachecontrol\&.cache\&.DictCache\fP, and \fBpip\&._vendor\&.cachecontrol\&.caches\&.redis_cache\&.RedisCache\fP\&.
.SS " None pip\&._vendor\&.cachecontrol\&.cache\&.BaseCache\&.set ( self, str key, bytes value, int | datetime | None  expires = \fCNone\fP)"

.PP
Reimplemented in \fBpip\&._vendor\&.cachecontrol\&.cache\&.DictCache\fP, \fBpip\&._vendor\&.cachecontrol\&.caches\&.redis_cache\&.RedisCache\fP, and \fBpip\&._internal\&.network\&.cache\&.SafeFileCache\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
