.TH "pip._internal.network.xmlrpc.PipXmlrpcTransport" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.network.xmlrpc.PipXmlrpcTransport
.SH SYNOPSIS
.br
.PP
.PP
Inherits xmlrpc\&.client\&.Transport\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str index_url, PipSession session, bool use_datetime=False)"
.br
.ti -1c
.RI "Tuple['_Marshallable',\&.\&.\&.] \fBrequest\fP (self, '_HostType' host, str handler, 'SizedBuffer' request_body, bool \fBverbose\fP=False)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBverbose\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_scheme\fP"
.br
.ti -1c
.RI "\fB_session\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Provide a `xmlrpclib\&.Transport` implementation via a `PipSession`
object\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.network\&.xmlrpc\&.PipXmlrpcTransport\&.__init__ ( self, str index_url, PipSession session, bool  use_datetime = \fCFalse\fP)"

.SH "Member Function Documentation"
.PP 
.SS " Tuple['_Marshallable', \&.\&.\&.] pip\&._internal\&.network\&.xmlrpc\&.PipXmlrpcTransport\&.request ( self, '_HostType' host, str handler, 'SizedBuffer' request_body, bool  verbose = \fCFalse\fP)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.network\&.xmlrpc\&.PipXmlrpcTransport\&._scheme\fC [protected]\fP"

.SS "pip\&._internal\&.network\&.xmlrpc\&.PipXmlrpcTransport\&._session\fC [protected]\fP"

.SS "pip\&._internal\&.network\&.xmlrpc\&.PipXmlrpcTransport\&.verbose"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
