.TH "pip._vendor.pygments.formatters.img" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pygments.formatters.img
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBmpImageFormatter\fP"
.br
.ti -1c
.RI "class \fBFontManager\fP"
.br
.ti -1c
.RI "class \fBFontNotFound\fP"
.br
.ti -1c
.RI "class \fBGifImageFormatter\fP"
.br
.ti -1c
.RI "class \fBImageFormatter\fP"
.br
.ti -1c
.RI "class \fBJpgImageFormatter\fP"
.br
.ti -1c
.RI "class \fBPilNotAvailable\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBpil_available\fP = True"
.br
.ti -1c
.RI "\fB_winreg\fP = None"
.br
.ti -1c
.RI "dict \fBSTYLES\fP"
.br
.ti -1c
.RI "str \fBDEFAULT_FONT_NAME_NIX\fP = 'DejaVu Sans Mono'"
.br
.ti -1c
.RI "str \fBDEFAULT_FONT_NAME_WIN\fP = 'Courier New'"
.br
.ti -1c
.RI "str \fBDEFAULT_FONT_NAME_MAC\fP = 'Menlo'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.formatters\&.img
    ~~~~~~~~~~~~~~~~~~~~~~~

    Formatter for Pixmap output\&.

    :copyright: Copyright 2006-2024 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.pygments\&.formatters\&.img\&._winreg = None\fC [protected]\fP"

.SS "str pip\&._vendor\&.pygments\&.formatters\&.img\&.DEFAULT_FONT_NAME_MAC = 'Menlo'"

.SS "str pip\&._vendor\&.pygments\&.formatters\&.img\&.DEFAULT_FONT_NAME_NIX = 'DejaVu Sans Mono'"

.SS "str pip\&._vendor\&.pygments\&.formatters\&.img\&.DEFAULT_FONT_NAME_WIN = 'Courier New'"

.SS "bool pip\&._vendor\&.pygments\&.formatters\&.img\&.pil_available = True"

.SS "dict pip\&._vendor\&.pygments\&.formatters\&.img\&.STYLES"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'NORMAL':     ['', 'Roman', 'Book', 'Normal', 'Regular', 'Medium'],
3     'ITALIC':     ['Oblique', 'Italic'],
4     'BOLD':       ['Bold'],
5     'BOLDITALIC': ['Bold Oblique', 'Bold Italic'],
6 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
