.TH "pip._vendor.pygments.formatters.latex" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pygments.formatters.latex
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLatexEmbeddedLexer\fP"
.br
.ti -1c
.RI "class \fBLatexFormatter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBescape_tex\fP (text, commandprefix)"
.br
.ti -1c
.RI "\fB_get_ttype_name\fP (ttype)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBDOC_TEMPLATE\fP"
.br
.ti -1c
.RI "str \fBSTYLE_TEMPLATE\fP"
.br
.RI "Small explanation of the mess below :) "
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.formatters\&.latex
    ~~~~~~~~~~~~~~~~~~~~~~~~~

    Formatter for LaTeX fancyvrb output\&.

    :copyright: Copyright 2006-2024 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.pygments\&.formatters\&.latex\&._get_ttype_name ( ttype)\fC [protected]\fP"

.SS "pip\&._vendor\&.pygments\&.formatters\&.latex\&.escape_tex ( text,  commandprefix)"

.SH "Variable Documentation"
.PP 
.SS "str pip\&._vendor\&.pygments\&.formatters\&.latex\&.DOC_TEMPLATE"
\fBInitial value:\fP.PP
.nf
1 =  r'''
2 \\documentclass{%(docclass)s}
3 \\usepackage{fancyvrb}
4 \\usepackage{color}
5 \\usepackage[%(encoding)s]{inputenc}
6 %(preamble)s
7 
8 %(styledefs)s
9 
10 \\begin{document}
11 
12 \\section*{%(title)s}
13 
14 %(code)s
15 \\end{document}
16 '''
.fi

.SS "str pip\&._vendor\&.pygments\&.formatters\&.latex\&.STYLE_TEMPLATE"

.PP
Small explanation of the mess below :) The previous version of the LaTeX formatter just assigned a command to each token type defined in the current style\&. That obviously is problematic if the highlighted code is produced for a different style than the style commands themselves\&.
.PP
This version works much like the HTML formatter which assigns multiple CSS classes to each  tag, from the most specific to the least specific token type, thus falling back to the parent token type if one is not defined\&. Here, the classes are there too and use the same short forms given in token\&.STANDARD_TYPES\&.
.PP
 Highlighted code now only uses one custom command, which by default is \\PY and selectable by the commandprefix option (and in addition the escapes \\PYZat, \\PYZlb and \\PYZrb which haven't been renamed for backwards compatibility purposes)\&.
.PP
 \\PY has two arguments: the classes, separated by +, and the text to render in that style\&. The classes are resolved into the respective style commands by magic, which serves to ignore unknown classes\&.
.PP
 The magic macros are:
.IP "\(bu" 2
\\PY@it, \\PY@bf, etc\&. are unconditionally wrapped around the text to render in \\PY@do\&. Their definition determines the style\&.
.IP "\(bu" 2
\\PY@reset resets \\PY@it etc\&. to do nothing\&.
.IP "\(bu" 2
\\PY@toks parses the list of classes, using magic inspired by the keyval package (but modified to use plusses instead of commas because fancyvrb redefines commas inside its environments)\&.
.IP "\(bu" 2
\\PY@tok processes one class, calling the \\PY@tok@classname command if it exists\&.
.IP "\(bu" 2
\\PY@tok@classname sets the \\PY@it etc\&. to reflect the chosen style for its class\&.
.IP "\(bu" 2
\\PY resets the style, parses the classnames and then calls \\PY@do\&.
.PP
.PP
 Tip: to read this code, print it out in substituted form using e\&.g\&. 
.PP
.RS 4

.PP
.RS 4

.PP
.RS 4
print STYLE_TEMPLATE % {'cp': 'PY'} 
.RE
.PP
.RE
.PP
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
