.TH "pip._vendor.rich.progress._ReadContext" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.progress._ReadContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits ContextManager, _I, Generic, and _I\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, 'Progress' \fBprogress\fP, \fB_I\fP reader)"
.br
.ti -1c
.RI "\fB_I\fP \fB__enter__\fP (self)"
.br
.ti -1c
.RI "None \fB__exit__\fP (self, Optional[Type[BaseException]] exc_type, Optional[BaseException] exc_val, Optional[TracebackType] exc_tb)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprogress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A utility class to handle a context for both a reader and a progress\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.progress\&._ReadContext\&.__init__ ( self, 'Progress' progress, \fB_I\fP reader)"

.SH "Member Function Documentation"
.PP 
.SS " \fB_I\fP pip\&._vendor\&.rich\&.progress\&._ReadContext\&.__enter__ ( self)"

.SS " None pip\&._vendor\&.rich\&.progress\&._ReadContext\&.__exit__ ( self, Optional[Type[BaseException]] exc_type, Optional[BaseException] exc_val, Optional[TracebackType] exc_tb)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.progress\&._ReadContext\&.progress"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
