.TH "pip._vendor.packaging._tokenizer.Token" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging._tokenizer.Token
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP"
.br
.ti -1c
.RI "str \fBtext\fP"
.br
.ti -1c
.RI "int \fBposition\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "str pip\&._vendor\&.packaging\&._tokenizer\&.Token\&.name\fC [static]\fP"

.SS "int pip\&._vendor\&.packaging\&._tokenizer\&.Token\&.position\fC [static]\fP"

.SS "str pip\&._vendor\&.packaging\&._tokenizer\&.Token\&.text\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
