.TH "pip._internal.network.cache" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.network.cache
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSafeFileCache\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBis_from_cache\fP (\fBResponse\fP response)"
.br
.ti -1c
.RI "Generator[None, None, None] \fBsuppressed_cache_errors\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
HTTP cache implementation\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " bool pip\&._internal\&.network\&.cache\&.is_from_cache (\fBResponse\fP response)"

.SS " Generator[None, None, None] pip\&._internal\&.network\&.cache\&.suppressed_cache_errors ()"

.PP
.nf
If we can't access the cache then we can just skip caching and process
requests as if caching wasn't enabled\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
