.TH "pip._vendor.pkg_resources._ReqExtras" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pkg_resources._ReqExtras
.SH SYNOPSIS
.br
.PP
.PP
Inherits Dict, Tuple, and str\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmarkers_pass\fP (self, \fBRequirement\fP req, tuple[str,\&.\&.\&.]|None extras=None)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Map each requirement to the extras that demanded it\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.pkg_resources\&._ReqExtras\&.markers_pass ( self, \fBRequirement\fP req, tuple[str, \&.\&.\&.] | None  extras = \fCNone\fP)"

.PP
.nf
Evaluate markers for req against each extra that
demanded it\&.

Return False if the req has a marker and fails
evaluation\&. Otherwise, return True\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
