.TH "pip._vendor.distlib.util.HTTPSConnection" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.util.HTTPSConnection
.SH SYNOPSIS
.br
.PP
.PP
Inherits httplib\&.HTTPSConnection\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnect\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsock\fP"
.br
.ti -1c
.RI "\fBcert_file\fP"
.br
.ti -1c
.RI "\fBkey_file\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBca_certs\fP = None"
.br
.ti -1c
.RI "bool \fBcheck_domain\fP = True"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.util\&.HTTPSConnection\&.connect ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.util\&.HTTPSConnection\&.ca_certs = None\fC [static]\fP"

.SS "pip\&._vendor\&.distlib\&.util\&.HTTPSConnection\&.cert_file"

.SS "bool pip\&._vendor\&.distlib\&.util\&.HTTPSConnection\&.check_domain = True\fC [static]\fP"

.SS "pip\&._vendor\&.distlib\&.util\&.HTTPSConnection\&.host"

.SS "pip\&._vendor\&.distlib\&.util\&.HTTPSConnection\&.key_file"

.SS "pip\&._vendor\&.distlib\&.util\&.HTTPSConnection\&.sock"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
