.TH "pip._vendor.typing_extensions._SpecialGenericAlias" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.typing_extensions._SpecialGenericAlias
.SH SYNOPSIS
.br
.PP
.PP
Inherits _special_generic_alias_base, _root, and True\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, origin, nparams, *inst=True, name=None, defaults=())"
.br
.ti -1c
.RI "\fB__setattr__\fP (self, attr, val)"
.br
.ti -1c
.RI "\fB__getitem__\fP (self, params)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_nparams\fP"
.br
.ti -1c
.RI "\fB_defaults\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.typing_extensions\&._SpecialGenericAlias\&.__init__ ( self,  origin,  nparams, * inst = \fCTrue\fP,  name = \fCNone\fP,  defaults = \fC()\fP)"

.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.typing_extensions\&._SpecialGenericAlias\&.__getitem__ ( self,  params)"

.SS "pip\&._vendor\&.typing_extensions\&._SpecialGenericAlias\&.__setattr__ ( self,  attr,  val)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.typing_extensions\&._SpecialGenericAlias\&._defaults\fC [protected]\fP"

.SS "pip\&._vendor\&.typing_extensions\&._SpecialGenericAlias\&._nparams\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
