.TH "pip._vendor.pyproject_hooks._in_process" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pyproject_hooks._in_process
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_in_process\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_in_proc_script_path\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This is a subpackage because the directory is on sys\&.path for _in_process\&.py

The subpackage should stay as empty as possible to avoid shadowing modules that
the backend might import\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_proc_script_path ()\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
