.TH "pip._vendor.pygments.plugin" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pygments.plugin
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBiter_entry_points\fP (group_name)"
.br
.ti -1c
.RI "\fBfind_plugin_lexers\fP ()"
.br
.ti -1c
.RI "\fBfind_plugin_formatters\fP ()"
.br
.ti -1c
.RI "\fBfind_plugin_styles\fP ()"
.br
.ti -1c
.RI "\fBfind_plugin_filters\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBLEXER_ENTRY_POINT\fP = 'pygments\&.lexers'"
.br
.ti -1c
.RI "str \fBFORMATTER_ENTRY_POINT\fP = 'pygments\&.formatters'"
.br
.ti -1c
.RI "str \fBSTYLE_ENTRY_POINT\fP = 'pygments\&.styles'"
.br
.ti -1c
.RI "str \fBFILTER_ENTRY_POINT\fP = 'pygments\&.filters'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.plugin
    ~~~~~~~~~~~~~~~

    Pygments plugin interface\&.

    lexer plugins::

        [pygments\&.lexers]
        yourlexer = yourmodule:YourLexer

    formatter plugins::

        [pygments\&.formatters]
        yourformatter = yourformatter:YourFormatter
        /\&.ext = yourformatter:YourFormatter

    As you can see, you can define extensions for the formatter
    with a leading slash\&.

    syntax plugins::

        [pygments\&.styles]
        yourstyle = yourstyle:YourStyle

    filter plugin::

        [pygments\&.filter]
        yourfilter = yourfilter:YourFilter


    :copyright: Copyright 2006-2024 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.pygments\&.plugin\&.find_plugin_filters ()"

.SS "pip\&._vendor\&.pygments\&.plugin\&.find_plugin_formatters ()"

.SS "pip\&._vendor\&.pygments\&.plugin\&.find_plugin_lexers ()"

.SS "pip\&._vendor\&.pygments\&.plugin\&.find_plugin_styles ()"

.SS "pip\&._vendor\&.pygments\&.plugin\&.iter_entry_points ( group_name)"

.SH "Variable Documentation"
.PP 
.SS "str pip\&._vendor\&.pygments\&.plugin\&.FILTER_ENTRY_POINT = 'pygments\&.filters'"

.SS "str pip\&._vendor\&.pygments\&.plugin\&.FORMATTER_ENTRY_POINT = 'pygments\&.formatters'"

.SS "str pip\&._vendor\&.pygments\&.plugin\&.LEXER_ENTRY_POINT = 'pygments\&.lexers'"

.SS "str pip\&._vendor\&.pygments\&.plugin\&.STYLE_ENTRY_POINT = 'pygments\&.styles'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
