.TH "pip._vendor.rich._ratio" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._ratio
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBE\fP"
.br
.ti -1c
.RI "class \fBEdge\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "List[int] \fBratio_resolve\fP (int total, Sequence[\fBEdge\fP] edges)"
.br
.ti -1c
.RI "List[int] \fBratio_reduce\fP (int total, List[int] ratios, List[int] maximums, List[int] values)"
.br
.ti -1c
.RI "List[int] \fBratio_distribute\fP (int total, List[int] ratios, Optional[List[int]] minimums=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBresolved\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " List[int] pip\&._vendor\&.rich\&._ratio\&.ratio_distribute (int total, List[int] ratios, Optional[List[int]]  minimums = \fCNone\fP)"

.PP
.nf
Distribute an integer total in to parts based on ratios\&.

Args:
    total (int): The total to divide\&.
    ratios (List[int]): A list of integer ratios\&.
    minimums (List[int]): List of minimum values for each slot\&.

Returns:
    List[int]: A list of integers guaranteed to sum to total\&.

.fi
.PP
 
.SS " List[int] pip\&._vendor\&.rich\&._ratio\&.ratio_reduce (int total, List[int] ratios, List[int] maximums, List[int]
 values)"

.PP
.nf
Divide an integer total in to parts based on ratios\&.

Args:
    total (int): The total to divide\&.
    ratios (List[int]): A list of integer ratios\&.
    maximums (List[int]): List of maximums values for each slot\&.
    values (List[int]): List of values

Returns:
    List[int]: A list of integers guaranteed to sum to total\&.

.fi
.PP
 
.SS " List[int] pip\&._vendor\&.rich\&._ratio\&.ratio_resolve (int total, Sequence[\fBEdge\fP] edges)"

.PP
.nf
Divide total space to satisfy size, ratio, and minimum_size, constraints\&.

The returned list of integers should add up to total in most cases, unless it is
impossible to satisfy all the constraints\&. For instance, if there are two edges
with a minimum size of 20 each and `total` is 30 then the returned list will be
greater than total\&. In practice, this would mean that a Layout object would
clip the rows that would overflow the screen height\&.

Args:
    total (int): Total number of characters\&.
    edges (List[Edge]): Edges within total space\&.

Returns:
    List[int]: Number of characters for each edge\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&._ratio\&.resolved"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
