.TH "pip._vendor.distlib.version.NormalizedVersion" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.version.NormalizedVersion
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.distlib\&.version\&.Version\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparse\fP (self, s)"
.br
.ti -1c
.RI "\fBis_prerelease\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.distlib\&.version\&.Version\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, s)"
.br
.ti -1c
.RI "\fB__eq__\fP (self, other)"
.br
.ti -1c
.RI "\fB__ne__\fP (self, other)"
.br
.ti -1c
.RI "\fB__lt__\fP (self, other)"
.br
.ti -1c
.RI "\fB__gt__\fP (self, other)"
.br
.ti -1c
.RI "\fB__le__\fP (self, other)"
.br
.ti -1c
.RI "\fB__ge__\fP (self, other)"
.br
.ti -1c
.RI "\fB__hash__\fP (self)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBPREREL_TAGS\fP = set(['a', 'b', 'c', 'rc', 'dev'])"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_release_clause\fP"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._vendor\&.distlib\&.version\&.Version\fP
.in +1c
.ti -1c
.RI "\fB_string\fP"
.br
.ti -1c
.RI "\fB_parts\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpip\&._vendor\&.distlib\&.version\&.Version\fP
.in +1c
.ti -1c
.RI "\fB_check_compatible\fP (self, other)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A rational version\&.

Good:
    1\&.2         # equivalent to '1\&.2\&.0'
    1\&.2\&.0
    1\&.2a1
    1\&.2\&.3a2
    1\&.2\&.3b1
    1\&.2\&.3c1
    1\&.2\&.3\&.4
    TODO: fill this out

Bad:
    1           # minimum two numbers
    1\&.2a        # release level must have a release serial
    1\&.2\&.3b

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.version\&.NormalizedVersion\&.is_prerelease ( self)"

.PP
Reimplemented from \fBpip\&._vendor\&.distlib\&.version\&.Version\fP\&.
.SS "pip\&._vendor\&.distlib\&.version\&.NormalizedVersion\&.parse ( self,  s)"

.PP
Reimplemented from \fBpip\&._vendor\&.distlib\&.version\&.Version\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.version\&.NormalizedVersion\&._release_clause\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.version\&.NormalizedVersion\&.PREREL_TAGS = set(['a', 'b', 'c', 'rc', 'dev'])\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
