.TH "pip._vendor.distlib.util.Progress" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.util.Progress
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, minval=0, maxval=100)"
.br
.ti -1c
.RI "\fBupdate\fP (self, curval)"
.br
.ti -1c
.RI "\fBincrement\fP (self, incr)"
.br
.ti -1c
.RI "\fBstart\fP (self)"
.br
.ti -1c
.RI "\fBstop\fP (self)"
.br
.ti -1c
.RI "\fBmaximum\fP (self)"
.br
.ti -1c
.RI "\fBpercentage\fP (self)"
.br
.ti -1c
.RI "\fBformat_duration\fP (self, duration)"
.br
.ti -1c
.RI "\fBETA\fP (self)"
.br
.ti -1c
.RI "\fBspeed\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmin\fP"
.br
.ti -1c
.RI "\fBmax\fP"
.br
.ti -1c
.RI "\fBstarted\fP"
.br
.ti -1c
.RI "\fBelapsed\fP"
.br
.ti -1c
.RI "\fBdone\fP"
.br
.ti -1c
.RI "\fBcur\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBunknown\fP = 'UNKNOWN'"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.__init__ ( self,  minval = \fC0\fP,  maxval = \fC100\fP)"

.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.ETA ( self)"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.format_duration ( self,  duration)"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.increment ( self,  incr)"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.maximum ( self)"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.percentage ( self)"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.speed ( self)"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.start ( self)"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.stop ( self)"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.update ( self,  curval)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.cur"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.done"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.elapsed"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.max"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.min"

.SS "pip\&._vendor\&.distlib\&.util\&.Progress\&.started"

.SS "str pip\&._vendor\&.distlib\&.util\&.Progress\&.unknown = 'UNKNOWN'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
