.TH "pip._vendor.rich.progress_bar.ProgressBar" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.progress_bar.ProgressBar
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, Optional[float] \fBtotal\fP=100\&.0, float \fBcompleted\fP=0, Optional[int] \fBwidth\fP=None, bool \fBpulse\fP=False, StyleType \fBstyle\fP='bar\&.back', StyleType \fBcomplete_style\fP='bar\&.complete', StyleType \fBfinished_style\fP='bar\&.finished', StyleType \fBpulse_style\fP='bar\&.pulse', Optional[float] \fBanimation_time\fP=None)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "Optional[float] \fBpercentage_completed\fP (self)"
.br
.ti -1c
.RI "None \fBupdate\fP (self, float \fBcompleted\fP, Optional[float] \fBtotal\fP=None)"
.br
.ti -1c
.RI "RenderResult \fB__rich_console__\fP (self, \fBConsole\fP \fBconsole\fP, \fBConsoleOptions\fP options)"
.br
.ti -1c
.RI "\fBMeasurement\fP \fB__rich_measure__\fP (self, \fBConsole\fP \fBconsole\fP, \fBConsoleOptions\fP options)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtotal\fP"
.br
.ti -1c
.RI "\fBcompleted\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.ti -1c
.RI "\fBpulse\fP"
.br
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBcomplete_style\fP"
.br
.ti -1c
.RI "\fBfinished_style\fP"
.br
.ti -1c
.RI "\fBpulse_style\fP"
.br
.ti -1c
.RI "\fBanimation_time\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "List[\fBSegment\fP] \fB_get_pulse_segments\fP (self, \fBStyle\fP fore_style, \fBStyle\fP back_style, str color_system, bool no_color, bool ascii=False)"
.br
.ti -1c
.RI "Iterable[\fBSegment\fP] \fB_render_pulse\fP (self, \fBConsole\fP \fBconsole\fP, int \fBwidth\fP, bool ascii=False)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP
.in +1c
.ti -1c
.RI "Dict[str, str] \fB_repr_mimebundle_\fP ('ConsoleRenderable' self, Sequence[str] include, Sequence[str] exclude, **Any kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Renders a (progress) bar\&. Used by rich\&.progress\&.

Args:
    total (float, optional): Number of steps in the bar\&. Defaults to 100\&. Set to None to render a pulsing animation\&.
    completed (float, optional): Number of steps completed\&. Defaults to 0\&.
    width (int, optional): Width of the bar, or ``None`` for maximum width\&. Defaults to None\&.
    pulse (bool, optional): Enable pulse effect\&. Defaults to False\&. Will pulse if a None total was passed\&.
    style (StyleType, optional): Style for the bar background\&. Defaults to 'bar\&.back'\&.
    complete_style (StyleType, optional): Style for the completed bar\&. Defaults to 'bar\&.complete'\&.
    finished_style (StyleType, optional): Style for a finished bar\&. Defaults to 'bar\&.finished'\&.
    pulse_style (StyleType, optional): Style for pulsing bars\&. Defaults to 'bar\&.pulse'\&.
    animation_time (Optional[float], optional): Time in seconds to use for animation, or None to use system time\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.__init__ ( self, Optional[float]  total = \fC100\&.0\fP, float  completed = \fC0\fP, Optional[int]  width = \fCNone\fP, bool  pulse = \fCFalse\fP, StyleType  style = \fC'bar\&.back'\fP, StyleType  complete_style = \fC'bar\&.complete'\fP, StyleType  finished_style = \fC'bar\&.finished'\fP, StyleType  pulse_style = \fC'bar\&.pulse'\fP, Optional[float]  animation_time = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS " str pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.__repr__ ( self)"

.SS " RenderResult pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.__rich_console__ ( self, \fBConsole\fP console, \fBConsoleOptions\fP
     options)"

.SS " \fBMeasurement\fP pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.__rich_measure__ ( self, \fBConsole\fP console, \fBConsoleOptions\fP
     options)"

.SS " List[\fBSegment\fP] pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&._get_pulse_segments ( self, \fBStyle\fP fore_style, \fBStyle\fP back_style, str color_system, bool no_color, bool  ascii = \fCFalse\fP)\fC [protected]\fP"

.PP
.nf
Get a list of segments to render a pulse animation\&.

Returns:
    List[Segment]: A list of segments, one segment per character\&.

.fi
.PP
 
.SS " Iterable[\fBSegment\fP] pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&._render_pulse ( self, \fBConsole\fP console, int width, bool  ascii = \fCFalse\fP)\fC [protected]\fP"

.PP
.nf
Renders the pulse animation\&.

Args:
    console (Console): Console instance\&.
    width (int): Width in characters of pulse animation\&.

Returns:
    RenderResult: [description]

Yields:
    Iterator[Segment]: Segments to render pulse

.fi
.PP
 
.SS " Optional[float] pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.percentage_completed ( self)"

.PP
.nf
Calculate percentage complete\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.update ( self, float completed, Optional[float]  total = \fCNone\fP)"

.PP
.nf
Update progress with new values\&.

Args:
    completed (float): Number of steps completed\&.
    total (float, optional): Total number of steps, or ``None`` to not change\&. Defaults to None\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.animation_time"

.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.complete_style"

.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.completed"

.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.finished_style"

.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.pulse"

.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.pulse_style"

.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.style"

.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.total"

.SS "pip\&._vendor\&.rich\&.progress_bar\&.ProgressBar\&.width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
