.TH "pip._vendor.urllib3.exceptions.PoolError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.exceptions.PoolError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.urllib3\&.exceptions\&.HTTPError\fP\&.
.PP
Inherited by \fBpip\&._vendor\&.urllib3\&.exceptions\&.ClosedPoolError\fP, \fBpip\&._vendor\&.urllib3\&.exceptions\&.EmptyPoolError\fP, \fBpip\&._vendor\&.urllib3\&.exceptions\&.NewConnectionError\fP, and \fBpip\&._vendor\&.urllib3\&.exceptions\&.RequestError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBpool\fP, message)"
.br
.ti -1c
.RI "\fB__reduce__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpool\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base exception for errors caused within a pool\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.exceptions\&.PoolError\&.__init__ ( self,  pool,  message)"

.PP
Reimplemented in \fBpip\&._vendor\&.urllib3\&.exceptions\&.RequestError\fP, \fBpip\&._vendor\&.urllib3\&.exceptions\&.MaxRetryError\fP, and \fBpip\&._vendor\&.urllib3\&.exceptions\&.HostChangedError\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.exceptions\&.PoolError\&.__reduce__ ( self)"

.PP
Reimplemented in \fBpip\&._vendor\&.urllib3\&.exceptions\&.RequestError\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.exceptions\&.PoolError\&.pool"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
