.TH "pip._vendor.urllib3.connectionpool.HTTPSConnectionPool" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.connectionpool.HTTPSConnectionPool
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP\&.
.PP
Inherited by \fBpip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSHTTPSConnectionPool\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBhost\fP, \fBport\fP=None, \fBstrict\fP=False, \fBtimeout\fP=\fBTimeout\&.DEFAULT_TIMEOUT\fP, maxsize=1, \fBblock\fP=False, \fBheaders\fP=None, \fBretries\fP=None, _proxy=None, _proxy_headers=None, \fBkey_file\fP=None, \fBcert_file\fP=None, \fBcert_reqs\fP=None, \fBkey_password\fP=None, \fBca_certs\fP=None, \fBssl_version\fP=None, \fBassert_hostname\fP=None, \fBassert_fingerprint\fP=None, \fBca_cert_dir\fP=None, **\fBconn_kw\fP)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP
.in +1c
.ti -1c
.RI "\fBclose\fP (self)"
.br
.ti -1c
.RI "\fBis_same_host\fP (self, url)"
.br
.ti -1c
.RI "\fBurlopen\fP (self, method, url, body=None, \fBheaders\fP=None, \fBretries\fP=None, redirect=True, assert_same_host=True, \fBtimeout\fP=\fB_Default\fP, pool_timeout=None, release_conn=None, chunked=False, body_pos=None, **response_kw)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.ConnectionPool\fP
.in +1c
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.ti -1c
.RI "\fB__enter__\fP (self)"
.br
.ti -1c
.RI "\fB__exit__\fP (self, exc_type, exc_val, exc_tb)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.urllib3\&.request\&.RequestMethods\fP
.in +1c
.ti -1c
.RI "\fBrequest\fP (self, method, url, fields=None, \fBheaders\fP=None, **urlopen_kw)"
.br
.ti -1c
.RI "\fBrequest_encode_url\fP (self, method, url, fields=None, \fBheaders\fP=None, **urlopen_kw)"
.br
.ti -1c
.RI "\fBrequest_encode_body\fP (self, method, url, fields=None, \fBheaders\fP=None, encode_multipart=True, multipart_boundary=None, **urlopen_kw)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBkey_file\fP"
.br
.ti -1c
.RI "\fBcert_file\fP"
.br
.ti -1c
.RI "\fBcert_reqs\fP"
.br
.ti -1c
.RI "\fBkey_password\fP"
.br
.ti -1c
.RI "\fBca_certs\fP"
.br
.ti -1c
.RI "\fBca_cert_dir\fP"
.br
.ti -1c
.RI "\fBssl_version\fP"
.br
.ti -1c
.RI "\fBassert_hostname\fP"
.br
.ti -1c
.RI "\fBassert_fingerprint\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBproxy_headers\fP"
.br
.ti -1c
.RI "\fBnum_connections\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP
.in +1c
.ti -1c
.RI "\fBstrict\fP"
.br
.ti -1c
.RI "\fBtimeout\fP"
.br
.ti -1c
.RI "\fBretries\fP"
.br
.ti -1c
.RI "\fBpool\fP"
.br
.ti -1c
.RI "\fBblock\fP"
.br
.ti -1c
.RI "\fBproxy\fP"
.br
.ti -1c
.RI "\fBproxy_headers\fP"
.br
.ti -1c
.RI "\fBproxy_config\fP"
.br
.ti -1c
.RI "\fBnum_connections\fP"
.br
.ti -1c
.RI "\fBnum_requests\fP"
.br
.ti -1c
.RI "\fBconn_kw\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBscheme\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.ConnectionPool\fP
.in +1c
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.request\&.RequestMethods\fP
.in +1c
.ti -1c
.RI "\fBheaders\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBscheme\fP = 'https'"
.br
.ti -1c
.RI "\fBConnectionCls\fP = \fBHTTPSConnection\fP"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP
.in +1c
.ti -1c
.RI "str \fBscheme\fP = 'http'"
.br
.ti -1c
.RI "\fBConnectionCls\fP = \fBHTTPConnection\fP"
.br
.ti -1c
.RI "\fBResponseCls\fP = \fBHTTPResponse\fP"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.ConnectionPool\fP
.in +1c
.ti -1c
.RI "\fBscheme\fP = None"
.br
.ti -1c
.RI "\fBQueueCls\fP = \fBLifoQueue\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_prepare_conn\fP (self, conn)"
.br
.ti -1c
.RI "\fB_prepare_proxy\fP (self, conn)"
.br
.ti -1c
.RI "\fB_new_conn\fP (self)"
.br
.ti -1c
.RI "\fB_validate_conn\fP (self, conn)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP
.in +1c
.ti -1c
.RI "\fB_get_conn\fP (self, \fBtimeout\fP=None)"
.br
.ti -1c
.RI "\fB_put_conn\fP (self, conn)"
.br
.ti -1c
.RI "\fB_get_timeout\fP (self, \fBtimeout\fP)"
.br
.ti -1c
.RI "\fB_raise_timeout\fP (self, err, url, timeout_value)"
.br
.ti -1c
.RI "\fB_make_request\fP (self, conn, method, url, \fBtimeout\fP=\fB_Default\fP, chunked=False, **httplib_request_kw)"
.br
.ti -1c
.RI "\fB_absolute_url\fP (self, path)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_proxy_host\fP"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.ConnectionPool\fP
.in +1c
.ti -1c
.RI "\fB_proxy_host\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Protected Attributes inherited from \fBpip\&._vendor\&.urllib3\&.request\&.RequestMethods\fP
.in +1c
.ti -1c
.RI "dict \fB_encode_url_methods\fP = {'DELETE', 'GET', 'HEAD', 'OPTIONS'}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Same as :class:`\&.HTTPConnectionPool`, but HTTPS\&.

:class:`\&.HTTPSConnection` uses one of ``assert_fingerprint``,
``assert_hostname`` and ``host`` in this order to verify connections\&.
If ``assert_hostname`` is False, no verification is done\&.

The ``key_file``, ``cert_file``, ``cert_reqs``, ``ca_certs``,
``ca_cert_dir``, ``ssl_version``, ``key_password`` are only used if :mod:`ssl`
is available and are fed into :meth:`urllib3\&.util\&.ssl_wrap_socket` to upgrade
the connection socket into an SSL socket\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.__init__ ( self,  host,  port = \fCNone\fP,  strict = \fCFalse\fP,  timeout = \fC\fBTimeout\&.DEFAULT_TIMEOUT\fP\fP,  maxsize = \fC1\fP,  block = \fCFalse\fP,  headers = \fCNone\fP,  retries = \fCNone\fP,  _proxy = \fCNone\fP,  _proxy_headers = \fCNone\fP,  key_file = \fCNone\fP,  cert_file = \fCNone\fP,  cert_reqs = \fCNone\fP,  key_password = \fCNone\fP,  ca_certs = \fCNone\fP,  ssl_version = \fCNone\fP,  assert_hostname = \fCNone\fP,  assert_fingerprint = \fCNone\fP,  ca_cert_dir = \fCNone\fP, ** conn_kw)"

.PP
Reimplemented from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&._new_conn ( self)\fC [protected]\fP"

.PP
.nf
Return a fresh :class:`http\&.client\&.HTTPSConnection`\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP\&.
.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&._prepare_conn ( self,  conn)\fC [protected]\fP"

.PP
.nf
Prepare the ``connection`` for :meth:`urllib3\&.util\&.ssl_wrap_socket`
and establish the tunnel if proxy is used\&.

.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&._prepare_proxy ( self,  conn)\fC [protected]\fP"

.PP
.nf
Establishes a tunnel connection through HTTP CONNECT\&.

Tunnel connection is established early because otherwise httplib would
improperly set Host: header to proxy's IP:port\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP\&.
.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&._validate_conn ( self,  conn)\fC [protected]\fP"

.PP
.nf
Called right before a request is made, after the socket is created\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.urllib3\&.connectionpool\&.HTTPConnectionPool\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&._proxy_host\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.assert_fingerprint"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.assert_hostname"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.ca_cert_dir"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.ca_certs"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.cert_file"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.cert_reqs"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.ConnectionCls = \fBHTTPSConnection\fP\fC [static]\fP"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.host"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.key_file"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.key_password"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.num_connections"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.port"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.proxy_headers"

.SS "str pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.scheme = 'https'\fC [static]\fP"

.SS "pip\&._vendor\&.urllib3\&.connectionpool\&.HTTPSConnectionPool\&.ssl_version"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
