.TH "pip._internal.resolution.base" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.resolution.base
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseResolver\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBInstallRequirementProvider\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "pip\&._internal\&.resolution\&.base\&.InstallRequirementProvider"
\fBInitial value:\fP.PP
.nf
1 =  Callable[
2     [str, Optional[InstallRequirement]], InstallRequirement
3 ]
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
