.TH "pip._vendor.pygments.token" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pygments.token
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_TokenType\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBis_token_subtype\fP (ttype, other)"
.br
.ti -1c
.RI "\fBstring_to_tokentype\fP (s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBToken\fP = \fB_TokenType\fP()"
.br
.ti -1c
.RI "\fBText\fP = Token\&.Text"
.br
.ti -1c
.RI "\fBWhitespace\fP = Text\&.Whitespace"
.br
.ti -1c
.RI "\fBEscape\fP = Token\&.Escape"
.br
.ti -1c
.RI "\fBError\fP = Token\&.Error"
.br
.ti -1c
.RI "\fBOther\fP = Token\&.Other"
.br
.ti -1c
.RI "\fBKeyword\fP = Token\&.Keyword"
.br
.ti -1c
.RI "\fBName\fP = Token\&.Name"
.br
.ti -1c
.RI "\fBLiteral\fP = Token\&.Literal"
.br
.ti -1c
.RI "\fBString\fP = Literal\&.String"
.br
.ti -1c
.RI "\fBNumber\fP = Literal\&.Number"
.br
.ti -1c
.RI "\fBPunctuation\fP = Token\&.Punctuation"
.br
.ti -1c
.RI "\fBOperator\fP = Token\&.Operator"
.br
.ti -1c
.RI "\fBComment\fP = Token\&.Comment"
.br
.ti -1c
.RI "\fBGeneric\fP = Token\&.Generic"
.br
.ti -1c
.RI "dict \fBSTANDARD_TYPES\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.token
    ~~~~~~~~~~~~~~

    Basic token types and the standard tokens\&.

    :copyright: Copyright 2006-2024 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.pygments\&.token\&.is_token_subtype ( ttype,  other)"

.PP
.nf
Return True if ``ttype`` is a subtype of ``other``\&.

exists for backwards compatibility\&. use ``ttype in other`` now\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pygments\&.token\&.string_to_tokentype ( s)"

.PP
.nf
Convert a string into a token type::

    >>> string_to_token('String\&.Double')
    Token\&.Literal\&.String\&.Double
    >>> string_to_token('Token\&.Literal\&.Number')
    Token\&.Literal\&.Number
    >>> string_to_token('')
    Token

Tokens that are already tokens are returned unchanged:

    >>> string_to_token(String)
    Token\&.Literal\&.String

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.pygments\&.token\&.Comment = Token\&.Comment"

.SS "pip\&._vendor\&.pygments\&.token\&.Error = Token\&.Error"

.SS "pip\&._vendor\&.pygments\&.token\&.Escape = Token\&.Escape"

.SS "pip\&._vendor\&.pygments\&.token\&.Generic = Token\&.Generic"

.SS "pip\&._vendor\&.pygments\&.token\&.Keyword = Token\&.Keyword"

.SS "pip\&._vendor\&.pygments\&.token\&.Literal = Token\&.Literal"

.SS "pip\&._vendor\&.pygments\&.token\&.Name = Token\&.Name"

.SS "pip\&._vendor\&.pygments\&.token\&.Number = Literal\&.Number"

.SS "pip\&._vendor\&.pygments\&.token\&.Operator = Token\&.Operator"

.SS "pip\&._vendor\&.pygments\&.token\&.Other = Token\&.Other"

.SS "pip\&._vendor\&.pygments\&.token\&.Punctuation = Token\&.Punctuation"

.SS "dict pip\&._vendor\&.pygments\&.token\&.STANDARD_TYPES"

.SS "pip\&._vendor\&.pygments\&.token\&.String = Literal\&.String"

.SS "pip\&._vendor\&.pygments\&.token\&.Text = Token\&.Text"

.SS "pip\&._vendor\&.pygments\&.token\&.Token = \fB_TokenType\fP()"

.SS "pip\&._vendor\&.pygments\&.token\&.Whitespace = Text\&.Whitespace"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
