.TH "pip._vendor.urllib3.exceptions.IncompleteRead" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.exceptions.IncompleteRead
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.urllib3\&.exceptions\&.HTTPError\fP, and httplib_IncompleteRead\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBpartial\fP, \fBexpected\fP)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpartial\fP"
.br
.ti -1c
.RI "\fBexpected\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Response length doesn't match expected Content-Length

Subclass of :class:`http\&.client\&.IncompleteRead` to allow int value
for ``partial`` to avoid creating large objects on streamed reads\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.exceptions\&.IncompleteRead\&.__init__ ( self,  partial,  expected)"

.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.exceptions\&.IncompleteRead\&.__repr__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.exceptions\&.IncompleteRead\&.expected"

.SS "pip\&._vendor\&.urllib3\&.exceptions\&.IncompleteRead\&.partial"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
