.TH "pip._vendor.typing_extensions._DefaultMixin" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.typing_extensions._DefaultMixin
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpip\&._vendor\&.typing_extensions\&.ParamSpec\fP, and \fBpip\&._vendor\&.typing_extensions\&.TypeVarTuple\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Mixin for TypeVarLike defaults\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
