.TH "pip._vendor.rich.bar.Bar" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.bar.Bar
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, float \fBsize\fP, float \fBbegin\fP, float \fBend\fP, *Optional[int] \fBwidth\fP=None, Union[\fBColor\fP, str] color='default', Union[\fBColor\fP, str] bgcolor='default')"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "RenderResult \fB__rich_console__\fP (self, \fBConsole\fP console, \fBConsoleOptions\fP options)"
.br
.ti -1c
.RI "\fBMeasurement\fP \fB__rich_measure__\fP (self, \fBConsole\fP console, \fBConsoleOptions\fP options)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsize\fP"
.br
.ti -1c
.RI "\fBbegin\fP"
.br
.ti -1c
.RI "\fBend\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.ti -1c
.RI "\fBstyle\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP
.in +1c
.ti -1c
.RI "Dict[str, str] \fB_repr_mimebundle_\fP ('ConsoleRenderable' self, Sequence[str] include, Sequence[str] exclude, **Any kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Renders a solid block bar\&.

Args:
    size (float): Value for the end of the bar\&.
    begin (float): Begin point (between 0 and size, inclusive)\&.
    end (float): End point (between 0 and size, inclusive)\&.
    width (int, optional): Width of the bar, or ``None`` for maximum width\&. Defaults to None\&.
    color (Union[Color, str], optional): Color of the bar\&. Defaults to 'default'\&.
    bgcolor (Union[Color, str], optional): Color of bar background\&. Defaults to 'default'\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.bar\&.Bar\&.__init__ ( self, float size, float begin, float end, *Optional[int]  width = \fCNone\fP, Union[\fBColor\fP, str]  color = \fC'default'\fP, Union[\fBColor\fP, str]  bgcolor = \fC'default'\fP)"

.SH "Member Function Documentation"
.PP 
.SS " str pip\&._vendor\&.rich\&.bar\&.Bar\&.__repr__ ( self)"

.SS " RenderResult pip\&._vendor\&.rich\&.bar\&.Bar\&.__rich_console__ ( self, \fBConsole\fP console, \fBConsoleOptions\fP
     options)"

.SS " \fBMeasurement\fP pip\&._vendor\&.rich\&.bar\&.Bar\&.__rich_measure__ ( self, \fBConsole\fP console, \fBConsoleOptions\fP
     options)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.bar\&.Bar\&.begin"

.SS "pip\&._vendor\&.rich\&.bar\&.Bar\&.end"

.SS "pip\&._vendor\&.rich\&.bar\&.Bar\&.size"

.SS "pip\&._vendor\&.rich\&.bar\&.Bar\&.style"

.SS "pip\&._vendor\&.rich\&.bar\&.Bar\&.width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
