.TH "pip._vendor.pkg_resources.ExtractionError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pkg_resources.ExtractionError
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeError\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBResourceManager\fP \fBmanager\fP"
.br
.ti -1c
.RI "str \fBcache_path\fP"
.br
.ti -1c
.RI "BaseException \fBoriginal_error\fP | None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An error occurred extracting a resource

The following attributes are available from instances of this exception:

manager
    The resource manager that raised this exception

cache_path
    The base directory for resource extraction

original_error
    The exception instance that caused extraction to fail

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "str pip\&._vendor\&.pkg_resources\&.ExtractionError\&.cache_path\fC [static]\fP"

.SS "\fBResourceManager\fP pip\&._vendor\&.pkg_resources\&.ExtractionError\&.manager\fC [static]\fP"

.SS "BaseException pip\&._vendor\&.pkg_resources\&.ExtractionError\&.original_error | None\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
