.TH "pip._vendor.rich.file_proxy.FileProxy" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.file_proxy.FileProxy
.SH SYNOPSIS
.br
.PP
.PP
Inherits io\&.TextIOBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, 'Console' console, IO[str] file)"
.br
.ti -1c
.RI "IO[str] \fBrich_proxied_file\fP (self)"
.br
.ti -1c
.RI "Any \fB__getattr__\fP (self, str name)"
.br
.ti -1c
.RI "int \fBwrite\fP (self, str text)"
.br
.ti -1c
.RI "None \fBflush\fP (self)"
.br
.ti -1c
.RI "int \fBfileno\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Wraps a file (e\&.g\&. sys\&.stdout) and redirects writes to a console\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.file_proxy\&.FileProxy\&.__init__ ( self, 'Console' console, IO[str] file)"

.SH "Member Function Documentation"
.PP 
.SS " Any pip\&._vendor\&.rich\&.file_proxy\&.FileProxy\&.__getattr__ ( self, str name)"

.SS " int pip\&._vendor\&.rich\&.file_proxy\&.FileProxy\&.fileno ( self)"

.SS " None pip\&._vendor\&.rich\&.file_proxy\&.FileProxy\&.flush ( self)"

.SS " IO[str] pip\&._vendor\&.rich\&.file_proxy\&.FileProxy\&.rich_proxied_file ( self)"

.PP
.nf
Get proxied file\&.
.fi
.PP
 
.SS " int pip\&._vendor\&.rich\&.file_proxy\&.FileProxy\&.write ( self, str text)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
