.TH "pip._vendor.distlib.compat.ConvertingTuple" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.compat.ConvertingTuple
.SH SYNOPSIS
.br
.PP
.PP
Inherits tuple\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__getitem__\fP (self, key)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A converting tuple wrapper\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.compat\&.ConvertingTuple\&.__getitem__ ( self,  key)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
