.TH "pip._internal.network.download.Downloader" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.network.download.Downloader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, PipSession session, str progress_bar)"
.br
.ti -1c
.RI "Tuple[str, str] \fB__call__\fP (self, \fBLink\fP link, str location)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_session\fP"
.br
.ti -1c
.RI "\fB_progress_bar\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.network\&.download\&.Downloader\&.__init__ ( self, PipSession session, str progress_bar)"

.SH "Member Function Documentation"
.PP 
.SS " Tuple[str, str] pip\&._internal\&.network\&.download\&.Downloader\&.__call__ ( self, \fBLink\fP link, str location)"

.PP
.nf
Download the file given by link into location\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.network\&.download\&.Downloader\&._progress_bar\fC [protected]\fP"

.SS "pip\&._internal\&.network\&.download\&.Downloader\&._session\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
