.TH "pip._internal.operations.check.PackageDetails" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.operations.check.PackageDetails
.SH SYNOPSIS
.br
.PP
.PP
Inherits NamedTuple\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBVersion\fP \fBversion\fP"
.br
.ti -1c
.RI "List \fBdependencies\fP [\fBRequirement\fP]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "List pip\&._internal\&.operations\&.check\&.PackageDetails\&.dependencies [\fBRequirement\fP]\fC [static]\fP"

.SS "\fBVersion\fP pip\&._internal\&.operations\&.check\&.PackageDetails\&.version\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
