.TH "pip._vendor.pyproject_hooks._in_process._in_process" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pyproject_hooks._in_process._in_process
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_DummyException\fP"
.br
.ti -1c
.RI "class \fBBackendInvalid\fP"
.br
.ti -1c
.RI "class \fBBackendUnavailable\fP"
.br
.ti -1c
.RI "class \fBGotUnsupportedOperation\fP"
.br
.ti -1c
.RI "class \fBHookMissing\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwrite_json\fP (obj, path, **kwargs)"
.br
.ti -1c
.RI "\fBread_json\fP (path)"
.br
.ti -1c
.RI "\fBcontained_in\fP (filename, directory)"
.br
.ti -1c
.RI "\fB_build_backend\fP ()"
.br
.ti -1c
.RI "\fB_supported_features\fP ()"
.br
.ti -1c
.RI "\fBget_requires_for_build_wheel\fP (config_settings)"
.br
.ti -1c
.RI "\fBget_requires_for_build_editable\fP (config_settings)"
.br
.ti -1c
.RI "\fBprepare_metadata_for_build_wheel\fP (metadata_directory, config_settings, _allow_fallback)"
.br
.ti -1c
.RI "\fBprepare_metadata_for_build_editable\fP (metadata_directory, config_settings, _allow_fallback)"
.br
.ti -1c
.RI "\fB_dist_info_files\fP (whl_zip)"
.br
.ti -1c
.RI "\fB_get_wheel_metadata_from_wheel\fP (whl_basename, metadata_directory, config_settings)"
.br
.ti -1c
.RI "\fB_find_already_built_wheel\fP (metadata_directory)"
.br
.ti -1c
.RI "\fBbuild_wheel\fP (wheel_directory, config_settings, metadata_directory=None)"
.br
.ti -1c
.RI "\fBbuild_editable\fP (wheel_directory, config_settings, metadata_directory=None)"
.br
.ti -1c
.RI "\fBget_requires_for_build_sdist\fP (config_settings)"
.br
.ti -1c
.RI "\fBbuild_sdist\fP (sdist_directory, config_settings)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBWHEEL_BUILT_MARKER\fP = 'PEP517_ALREADY_BUILT_WHEEL'"
.br
.ti -1c
.RI "dict \fBHOOK_NAMES\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This is invoked in a subprocess to call the build backend hooks\&.

It expects:
- Command line args: hook_name, control_dir
- Environment variables:
      PEP517_BUILD_BACKEND=entry\&.point:spec
      PEP517_BACKEND_PATH=paths (separated with os\&.pathsep)
- control_dir/input\&.json:
  - {'kwargs': {\&.\&.\&.}}

Results:
- control_dir/output\&.json
  - {'return_val': \&.\&.\&.}

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&._build_backend ()\fC [protected]\fP"

.PP
.nf
Find and load the build backend
.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&._dist_info_files ( whl_zip)\fC [protected]\fP"

.PP
.nf
Identify the \&.dist-info folder inside a wheel ZipFile\&.
.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&._find_already_built_wheel ( metadata_directory)\fC [protected]\fP"

.PP
.nf
Check for a wheel already built during the get_wheel_metadata hook\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&._get_wheel_metadata_from_wheel ( whl_basename,  metadata_directory,  config_settings)\fC [protected]\fP"

.PP
.nf
Extract the metadata from a wheel\&.

Fallback for when the build backend does not
define the 'get_wheel_metadata' hook\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&._supported_features ()\fC [protected]\fP"

.PP
.nf
Return the list of options features supported by the backend\&.

Returns a list of strings\&.
The only possible value is 'build_editable'\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.build_editable ( wheel_directory,  config_settings,  metadata_directory = \fCNone\fP)"

.PP
.nf
Invoke the optional build_editable hook\&.

If a wheel was already built in the
prepare_metadata_for_build_editable fallback, this
will copy it rather than rebuilding the wheel\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.build_sdist ( sdist_directory,  config_settings)"

.PP
.nf
Invoke the mandatory build_sdist hook\&.
.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.build_wheel ( wheel_directory,  config_settings,  metadata_directory = \fCNone\fP)"

.PP
.nf
Invoke the mandatory build_wheel hook\&.

If a wheel was already built in the
prepare_metadata_for_build_wheel fallback, this
will copy it rather than rebuilding the wheel\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.contained_in ( filename,  directory)"

.PP
.nf
Test if a file is located within the given directory\&.
.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.get_requires_for_build_editable ( config_settings)"

.PP
.nf
Invoke the optional get_requires_for_build_editable hook

Returns [] if the hook is not defined\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.get_requires_for_build_sdist ( config_settings)"

.PP
.nf
Invoke the optional get_requires_for_build_wheel hook

Returns [] if the hook is not defined\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.get_requires_for_build_wheel ( config_settings)"

.PP
.nf
Invoke the optional get_requires_for_build_wheel hook

Returns [] if the hook is not defined\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.main ()"

.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.prepare_metadata_for_build_editable ( metadata_directory,  config_settings,  _allow_fallback)"

.PP
.nf
Invoke optional prepare_metadata_for_build_editable

Implements a fallback by building an editable wheel if the hook isn't
defined, unless _allow_fallback is False in which case HookMissing is
raised\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.prepare_metadata_for_build_wheel ( metadata_directory,  config_settings,  _allow_fallback)"

.PP
.nf
Invoke optional prepare_metadata_for_build_wheel

Implements a fallback by building a wheel if the hook isn't defined,
unless _allow_fallback is False in which case HookMissing is raised\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.read_json ( path)"

.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.write_json ( obj,  path, ** kwargs)"

.SH "Variable Documentation"
.PP 
.SS "dict pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.HOOK_NAMES"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'get_requires_for_build_wheel',
3     'prepare_metadata_for_build_wheel',
4     'build_wheel',
5     'get_requires_for_build_editable',
6     'prepare_metadata_for_build_editable',
7     'build_editable',
8     'get_requires_for_build_sdist',
9     'build_sdist',
10     '_supported_features',
11 }
.fi

.SS "str pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.WHEEL_BUILT_MARKER = 'PEP517_ALREADY_BUILT_WHEEL'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
