.TH "pip._vendor.urllib3.exceptions.ProxySchemeUnsupported" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.exceptions.ProxySchemeUnsupported
.SH SYNOPSIS
.br
.PP
.PP
Inherits ValueError\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Fetching HTTPS resources through HTTPS proxies is unsupported
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
