.TH "pip._internal.build_env.BuildEnvironment" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.build_env.BuildEnvironment
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpip\&._internal\&.build_env\&.NoOpBuildEnvironment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self)"
.br
.ti -1c
.RI "None \fB__enter__\fP (self)"
.br
.ti -1c
.RI "None \fB__exit__\fP (self, Optional[Type[BaseException]] exc_type, Optional[BaseException] exc_val, Optional[TracebackType] exc_tb)"
.br
.ti -1c
.RI "Tuple[Set[Tuple[str, str]], Set[str]] \fBcheck_requirements\fP (self, Iterable[str] reqs)"
.br
.ti -1c
.RI "None \fBinstall_requirements\fP (self, 'PackageFinder' finder, Iterable[str] requirements, str prefix_as_string, *str kind)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "None \fB_install_requirements\fP (str pip_runnable, 'PackageFinder' finder, Iterable[str] requirements, \fB_Prefix\fP prefix, *str kind)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_prefixes\fP"
.br
.ti -1c
.RI "\fB_site_dir\fP"
.br
.ti -1c
.RI "\fB_save_env\fP"
.br
.ti -1c
.RI "\fB_lib_dirs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Creates and manages an isolated environment to install build deps
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.build_env\&.BuildEnvironment\&.__init__ ( self)"

.PP
Reimplemented in \fBpip\&._internal\&.build_env\&.NoOpBuildEnvironment\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " None pip\&._internal\&.build_env\&.BuildEnvironment\&.__enter__ ( self)"

.PP
Reimplemented in \fBpip\&._internal\&.build_env\&.NoOpBuildEnvironment\fP\&.
.SS " None pip\&._internal\&.build_env\&.BuildEnvironment\&.__exit__ ( self, Optional[Type[BaseException]] exc_type, Optional[BaseException] exc_val, Optional[TracebackType] exc_tb)"

.PP
Reimplemented in \fBpip\&._internal\&.build_env\&.NoOpBuildEnvironment\fP\&.
.SS " None pip\&._internal\&.build_env\&.BuildEnvironment\&._install_requirements (str pip_runnable, 'PackageFinder' finder, Iterable[str] requirements, \fB_Prefix\fP prefix, *str kind)\fC [static]\fP, \fC [protected]\fP"

.SS " Tuple[Set[Tuple[str, str]], Set[str]] pip\&._internal\&.build_env\&.BuildEnvironment\&.check_requirements ( self, Iterable[str]
     reqs)"

.PP
.nf
Return 2 sets:
- conflicting requirements: set of (installed, wanted) reqs tuples
- missing requirements: set of reqs

.fi
.PP
 
.SS " None pip\&._internal\&.build_env\&.BuildEnvironment\&.install_requirements ( self, 'PackageFinder' finder, Iterable[str] requirements, str prefix_as_string, *str kind)"

.PP
Reimplemented in \fBpip\&._internal\&.build_env\&.NoOpBuildEnvironment\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.build_env\&.BuildEnvironment\&._lib_dirs\fC [protected]\fP"

.SS "pip\&._internal\&.build_env\&.BuildEnvironment\&._prefixes\fC [protected]\fP"

.SS "pip\&._internal\&.build_env\&.BuildEnvironment\&._save_env\fC [protected]\fP"

.SS "pip\&._internal\&.build_env\&.BuildEnvironment\&._site_dir\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
