.TH "pip._vendor.urllib3.packages.six._LazyDescr" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.packages.six._LazyDescr
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpip\&._vendor\&.urllib3\&.packages\&.six\&.MovedAttribute\fP, and \fBpip\&._vendor\&.urllib3\&.packages\&.six\&.MovedModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBname\fP)"
.br
.ti -1c
.RI "\fB__get__\fP (self, obj, tp)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.packages\&.six\&._LazyDescr\&.__init__ ( self,  name)"

.PP
Reimplemented in \fBpip\&._vendor\&.urllib3\&.packages\&.six\&.MovedModule\fP, and \fBpip\&._vendor\&.urllib3\&.packages\&.six\&.MovedAttribute\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.packages\&.six\&._LazyDescr\&.__get__ ( self,  obj,  tp)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.packages\&.six\&._LazyDescr\&.name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
