.TH "pip._vendor.urllib3.connection.HTTPSConnection" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.connection.HTTPSConnection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP\&.
.PP
Inherited by \fBpip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSHTTPSConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBhost\fP, \fBport\fP=None, \fBkey_file\fP=None, \fBcert_file\fP=None, \fBkey_password\fP=None, strict=None, \fBtimeout\fP=socket\&._GLOBAL_DEFAULT_TIMEOUT, \fBssl_context\fP=None, \fBserver_hostname\fP=None, **kw)"
.br
.ti -1c
.RI "\fBset_cert\fP (self, \fBkey_file\fP=None, \fBcert_file\fP=None, \fBcert_reqs\fP=None, \fBkey_password\fP=None, \fBca_certs\fP=None, \fBassert_hostname\fP=None, \fBassert_fingerprint\fP=None, \fBca_cert_dir\fP=None, \fBca_cert_data\fP=None)"
.br
.ti -1c
.RI "\fBconnect\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fBhost\fP (self)"
.br
.ti -1c
.RI "\fBhost\fP (self, value)"
.br
.ti -1c
.RI "\fBputrequest\fP (self, method, url, *args, **kwargs)"
.br
.ti -1c
.RI "\fBputheader\fP (self, header, *values)"
.br
.ti -1c
.RI "\fBrequest\fP (self, method, url, body=None, headers=None)"
.br
.ti -1c
.RI "\fBrequest_chunked\fP (self, method, url, body=None, headers=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBkey_file\fP"
.br
.ti -1c
.RI "\fBcert_file\fP"
.br
.ti -1c
.RI "\fBkey_password\fP"
.br
.ti -1c
.RI "\fBssl_context\fP"
.br
.ti -1c
.RI "\fBserver_hostname\fP"
.br
.ti -1c
.RI "\fBassert_hostname\fP"
.br
.ti -1c
.RI "\fBsock\fP"
.br
.ti -1c
.RI "\fBauto_open\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBis_verified\fP"
.br
.ti -1c
.RI "\fBproxy_is_verified\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fBsource_address\fP"
.br
.ti -1c
.RI "\fBsocket_options\fP"
.br
.ti -1c
.RI "\fBproxy\fP"
.br
.ti -1c
.RI "\fBproxy_config\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBtimeout\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBsock\fP"
.br
.ti -1c
.RI "\fBauto_open\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBdefault_port\fP = \fBport_by_scheme\fP['https']"
.br
.ti -1c
.RI "\fBcert_reqs\fP = None"
.br
.ti -1c
.RI "\fBca_certs\fP = None"
.br
.ti -1c
.RI "\fBca_cert_dir\fP = None"
.br
.ti -1c
.RI "\fBca_cert_data\fP = None"
.br
.ti -1c
.RI "\fBssl_version\fP = None"
.br
.ti -1c
.RI "\fBassert_fingerprint\fP = None"
.br
.ti -1c
.RI "bool \fBtls_in_tls_required\fP = False"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fBdefault_port\fP = \fBport_by_scheme\fP['http']"
.br
.ti -1c
.RI "list \fBdefault_socket_options\fP = [(socket\&.IPPROTO_TCP, socket\&.TCP_NODELAY, 1)]"
.br
.ti -1c
.RI "bool \fBis_verified\fP = False"
.br
.ti -1c
.RI "\fBproxy_is_verified\fP = None"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_connect_tls_proxy\fP (self, hostname, conn)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fB_new_conn\fP (self)"
.br
.ti -1c
.RI "\fB_is_using_tunnel\fP (self)"
.br
.ti -1c
.RI "\fB_prepare_conn\fP (self, conn)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_protocol\fP"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fB_dns_host\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Many of the parameters to this constructor are passed to the underlying SSL
socket by means of :py:func:`urllib3\&.util\&.ssl_wrap_socket`\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.__init__ ( self,  host,  port = \fCNone\fP,  key_file = \fCNone\fP,  cert_file = \fCNone\fP,  key_password = \fCNone\fP,  strict = \fCNone\fP,  timeout = \fCsocket\&._GLOBAL_DEFAULT_TIMEOUT\fP,  ssl_context = \fCNone\fP,  server_hostname = \fCNone\fP, ** kw)"

.PP
Reimplemented from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&._connect_tls_proxy ( self,  hostname,  conn)\fC [protected]\fP"

.PP
.nf
Establish a TLS connection to the proxy using the provided SSL context\&.

.fi
.PP
 
.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.connect ( self)"

.PP
Reimplemented from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP\&.
.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.set_cert ( self,  key_file = \fCNone\fP,  cert_file = \fCNone\fP,  cert_reqs = \fCNone\fP,  key_password = \fCNone\fP,  ca_certs = \fCNone\fP,  assert_hostname = \fCNone\fP,  assert_fingerprint = \fCNone\fP,  ca_cert_dir = \fCNone\fP,  ca_cert_data = \fCNone\fP)"

.PP
.nf
This method should only be called once, before the connection is used\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&._protocol\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.assert_fingerprint = None\fC [static]\fP"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.assert_hostname"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.auto_open"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.ca_cert_data = None\fC [static]\fP"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.ca_cert_dir = None\fC [static]\fP"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.ca_certs = None\fC [static]\fP"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.cert_file"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.cert_reqs = None\fC [static]\fP"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.default_port = \fBport_by_scheme\fP['https']\fC [static]\fP"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.host"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.is_verified"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.key_file"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.key_password"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.proxy_is_verified"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.server_hostname"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.sock"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.ssl_context"

.SS "pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.ssl_version = None\fC [static]\fP"

.SS "bool pip\&._vendor\&.urllib3\&.connection\&.HTTPSConnection\&.tls_in_tls_required = False\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
