.TH "pip._vendor.urllib3.exceptions.SubjectAltNameWarning" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.exceptions.SubjectAltNameWarning
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.urllib3\&.exceptions\&.SecurityWarning\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Warned when connecting to a host with a certificate missing a SAN\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
