.TH "pip._internal.cli.spinners.RateLimiter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.cli.spinners.RateLimiter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, float min_update_interval_seconds)"
.br
.ti -1c
.RI "bool \fBready\fP (self)"
.br
.ti -1c
.RI "None \fBreset\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_min_update_interval_seconds\fP"
.br
.ti -1c
.RI "\fB_last_update\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.cli\&.spinners\&.RateLimiter\&.__init__ ( self, float min_update_interval_seconds)"

.SH "Member Function Documentation"
.PP 
.SS " bool pip\&._internal\&.cli\&.spinners\&.RateLimiter\&.ready ( self)"

.SS " None pip\&._internal\&.cli\&.spinners\&.RateLimiter\&.reset ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.cli\&.spinners\&.RateLimiter\&._last_update\fC [protected]\fP"

.SS "pip\&._internal\&.cli\&.spinners\&.RateLimiter\&._min_update_interval_seconds\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
