.TH "pip._internal.req.req_file.ParsedLine" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.req.req_file.ParsedLine
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBfilename\fP, int \fBlineno\fP, str args, Values \fBopts\fP, bool \fBconstraint\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBlineno\fP"
.br
.ti -1c
.RI "\fBopts\fP"
.br
.ti -1c
.RI "\fBconstraint\fP"
.br
.ti -1c
.RI "\fBis_requirement\fP"
.br
.ti -1c
.RI "\fBis_editable\fP"
.br
.ti -1c
.RI "\fBrequirement\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.req\&.req_file\&.ParsedLine\&.__init__ ( self, str filename, int lineno, str args, Values opts, bool constraint)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.req\&.req_file\&.ParsedLine\&.constraint"

.SS "pip\&._internal\&.req\&.req_file\&.ParsedLine\&.filename"

.SS "pip\&._internal\&.req\&.req_file\&.ParsedLine\&.is_editable"

.SS "pip\&._internal\&.req\&.req_file\&.ParsedLine\&.is_requirement"

.SS "pip\&._internal\&.req\&.req_file\&.ParsedLine\&.lineno"

.SS "pip\&._internal\&.req\&.req_file\&.ParsedLine\&.opts"

.SS "pip\&._internal\&.req\&.req_file\&.ParsedLine\&.requirement"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
