.TH "pip._vendor.rich.progress" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.progress
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_ReadContext\fP"
.br
.ti -1c
.RI "class \fB_Reader\fP"
.br
.ti -1c
.RI "class \fB_TrackThread\fP"
.br
.ti -1c
.RI "class \fBBarColumn\fP"
.br
.ti -1c
.RI "class \fBDownloadColumn\fP"
.br
.ti -1c
.RI "class \fBFileSizeColumn\fP"
.br
.ti -1c
.RI "class \fBMofNCompleteColumn\fP"
.br
.ti -1c
.RI "class \fBProgress\fP"
.br
.ti -1c
.RI "class \fBProgressColumn\fP"
.br
.ti -1c
.RI "class \fBProgressSample\fP"
.br
.ti -1c
.RI "class \fBRenderableColumn\fP"
.br
.ti -1c
.RI "class \fBSpinnerColumn\fP"
.br
.ti -1c
.RI "class \fBTask\fP"
.br
.ti -1c
.RI "class \fBTaskProgressColumn\fP"
.br
.ti -1c
.RI "class \fBTextColumn\fP"
.br
.ti -1c
.RI "class \fBTimeElapsedColumn\fP"
.br
.ti -1c
.RI "class \fBTimeRemainingColumn\fP"
.br
.ti -1c
.RI "class \fBTotalFileSizeColumn\fP"
.br
.ti -1c
.RI "class \fBTransferSpeedColumn\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Iterable[\fBProgressType\fP] \fBtrack\fP (Union[Sequence[\fBProgressType\fP], Iterable[\fBProgressType\fP]] sequence, str description='Working\&.\&.\&.', Optional[float] total=None, bool auto_refresh=True, Optional[\fBConsole\fP] \fBconsole\fP=None, bool \fBtransient\fP=False, Optional[Callable[[], float]] get_time=None, float refresh_per_second=10, StyleType style='bar\&.back', StyleType complete_style='bar\&.complete', StyleType finished_style='bar\&.finished', StyleType pulse_style='bar\&.pulse', float update_period=0\&.1, bool disable=False, bool show_speed=True)"
.br
.ti -1c
.RI "ContextManager[BinaryIO] \fBwrap_file\fP (BinaryIO file, int total, *str description='Reading\&.\&.\&.', bool auto_refresh=True, Optional[\fBConsole\fP] \fBconsole\fP=None, bool \fBtransient\fP=False, Optional[Callable[[], float]] get_time=None, float refresh_per_second=10, StyleType style='bar\&.back', StyleType complete_style='bar\&.complete', StyleType finished_style='bar\&.finished', StyleType pulse_style='bar\&.pulse', bool disable=False)"
.br
.ti -1c
.RI "ContextManager[TextIO] \fBopen\fP (Union[str, 'PathLike[str]', bytes] file, Union[Literal['rt'], Literal['r']] mode, int buffering=\-1, Optional[str] encoding=None, Optional[str] errors=None, Optional[str] newline=None, *Optional[int] total=None, str description='Reading\&.\&.\&.', bool auto_refresh=True, Optional[\fBConsole\fP] \fBconsole\fP=None, bool \fBtransient\fP=False, Optional[Callable[[], float]] get_time=None, float refresh_per_second=10, StyleType style='bar\&.back', StyleType complete_style='bar\&.complete', StyleType finished_style='bar\&.finished', StyleType pulse_style='bar\&.pulse', bool disable=False)"
.br
.ti -1c
.RI "ContextManager[BinaryIO] \fBopen\fP (Union[str, 'PathLike[str]', bytes] file, Literal['rb'] mode, int buffering=\-1, Optional[str] encoding=None, Optional[str] errors=None, Optional[str] newline=None, *Optional[int] total=None, str description='Reading\&.\&.\&.', bool auto_refresh=True, Optional[\fBConsole\fP] \fBconsole\fP=None, bool \fBtransient\fP=False, Optional[Callable[[], float]] get_time=None, float refresh_per_second=10, StyleType style='bar\&.back', StyleType complete_style='bar\&.complete', StyleType finished_style='bar\&.finished', StyleType pulse_style='bar\&.pulse', bool disable=False)"
.br
.ti -1c
.RI "Union[ContextManager[BinaryIO], ContextManager[TextIO]] \fBopen\fP (Union[str, 'PathLike[str]', bytes] file, Union[Literal['rb'], Literal['rt'], Literal['r']] mode='r', int buffering=\-1, Optional[str] encoding=None, Optional[str] errors=None, Optional[str] newline=None, *Optional[int] total=None, str description='Reading\&.\&.\&.', bool auto_refresh=True, Optional[\fBConsole\fP] \fBconsole\fP=None, bool \fBtransient\fP=False, Optional[Callable[[], float]] get_time=None, float refresh_per_second=10, StyleType style='bar\&.back', StyleType complete_style='bar\&.complete', StyleType finished_style='bar\&.finished', StyleType pulse_style='bar\&.pulse', bool disable=False)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTaskID\fP = NewType('TaskID', int)"
.br
.ti -1c
.RI "\fBProgressType\fP = TypeVar('ProgressType')"
.br
.ti -1c
.RI "\fBGetTimeCallable\fP = Callable[[], float]"
.br
.ti -1c
.RI "\fB_I\fP = typing\&.TypeVar('_I', TextIO, BinaryIO)"
.br
.ti -1c
.RI "\fBsyntax\fP"
.br
.ti -1c
.RI "\fBtable\fP = \fBTable\fP('foo', 'bar', 'baz')"
.br
.ti -1c
.RI "list \fBprogress_renderables\fP"
.br
.ti -1c
.RI "\fBexamples\fP = cycle(\fBprogress_renderables\fP)"
.br
.ti -1c
.RI "\fBconsole\fP = \fBConsole\fP(record=True)"
.br
.ti -1c
.RI "\fBtransient\fP"
.br
.ti -1c
.RI "\fBtask1\fP = progress\&.add_task('[red]Downloading', total=1000)"
.br
.ti -1c
.RI "\fBtask2\fP = progress\&.add_task('[green]Processing', total=1000)"
.br
.ti -1c
.RI "\fBtask3\fP = progress\&.add_task('[yellow]Thinking', total=None)"
.br
.ti -1c
.RI "\fBadvance\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " ContextManager[BinaryIO] pip\&._vendor\&.rich\&.progress\&.open (Union[str, 'PathLike[str]', bytes] file, Literal['rb'] mode, int  buffering = \fC\-1\fP, Optional[str]  encoding = \fCNone\fP, Optional[str]  errors = \fCNone\fP, Optional[str]  newline = \fCNone\fP, *Optional[int]  total = \fCNone\fP, str  description = \fC'Reading\&.\&.\&.'\fP, bool  auto_refresh = \fCTrue\fP, Optional[\fBConsole\fP]  console = \fCNone\fP, bool  transient = \fCFalse\fP, Optional[Callable[[], float]]  get_time = \fCNone\fP, float  refresh_per_second = \fC10\fP, StyleType  style = \fC'bar\&.back'\fP, StyleType  complete_style = \fC'bar\&.complete'\fP, StyleType  finished_style = \fC'bar\&.finished'\fP, StyleType  pulse_style = \fC'bar\&.pulse'\fP, bool  disable = \fCFalse\fP)"

.SS " Union[ContextManager[BinaryIO], ContextManager[TextIO]] pip\&._vendor\&.rich\&.progress\&.open (Union[str, 'PathLike[str]', bytes] file, Union[Literal['rb'], Literal['rt'], Literal['r']]  mode = \fC'r'\fP, int  buffering = \fC\-1\fP, Optional[str]  encoding = \fCNone\fP, Optional[str]  errors = \fCNone\fP, Optional[str]  newline = \fCNone\fP, *Optional[int]  total = \fCNone\fP, str  description = \fC'Reading\&.\&.\&.'\fP, bool  auto_refresh = \fCTrue\fP, Optional[\fBConsole\fP]  console = \fCNone\fP, bool  transient = \fCFalse\fP, Optional[Callable[[], float]]  get_time = \fCNone\fP, float  refresh_per_second = \fC10\fP, StyleType  style = \fC'bar\&.back'\fP, StyleType  complete_style = \fC'bar\&.complete'\fP, StyleType  finished_style = \fC'bar\&.finished'\fP, StyleType  pulse_style = \fC'bar\&.pulse'\fP, bool  disable = \fCFalse\fP)"

.PP
.nf
Read bytes from a file while tracking progress\&.

Args:
    path (Union[str, PathLike[str], BinaryIO]): The path to the file to read, or a file-like object in binary mode\&.
    mode (str): The mode to use to open the file\&. Only supports 'r', 'rb' or 'rt'\&.
    buffering (int): The buffering strategy to use, see :func:`io\&.open`\&.
    encoding (str, optional): The encoding to use when reading in text mode, see :func:`io\&.open`\&.
    errors (str, optional): The error handling strategy for decoding errors, see :func:`io\&.open`\&.
    newline (str, optional): The strategy for handling newlines in text mode, see :func:`io\&.open`
    total: (int, optional): Total number of bytes to read\&. Must be provided if reading from a file handle\&. Default for a path is os\&.stat(file)\&.st_size\&.
    description (str, optional): Description of task show next to progress bar\&. Defaults to 'Reading'\&.
    auto_refresh (bool, optional): Automatic refresh, disable to force a refresh after each iteration\&. Default is True\&.
    transient: (bool, optional): Clear the progress on exit\&. Defaults to False\&.
    console (Console, optional): Console to write to\&. Default creates internal Console instance\&.
    refresh_per_second (float): Number of times per second to refresh the progress information\&. Defaults to 10\&.
    style (StyleType, optional): Style for the bar background\&. Defaults to 'bar\&.back'\&.
    complete_style (StyleType, optional): Style for the completed bar\&. Defaults to 'bar\&.complete'\&.
    finished_style (StyleType, optional): Style for a finished bar\&. Defaults to 'bar\&.finished'\&.
    pulse_style (StyleType, optional): Style for pulsing bars\&. Defaults to 'bar\&.pulse'\&.
    disable (bool, optional): Disable display of progress\&.
    encoding (str, optional): The encoding to use when reading in text mode\&.

Returns:
    ContextManager[BinaryIO]: A context manager yielding a progress reader\&.
.fi
.PP
 
.SS " ContextManager[TextIO] pip\&._vendor\&.rich\&.progress\&.open (Union[str, 'PathLike[str]', bytes] file, Union[Literal['rt'], Literal['r']] mode, int  buffering = \fC\-1\fP, Optional[str]  encoding = \fCNone\fP, Optional[str]  errors = \fCNone\fP, Optional[str]  newline = \fCNone\fP, *Optional[int]  total = \fCNone\fP, str  description = \fC'Reading\&.\&.\&.'\fP, bool  auto_refresh = \fCTrue\fP, Optional[\fBConsole\fP]  console = \fCNone\fP, bool  transient = \fCFalse\fP, Optional[Callable[[], float]]  get_time = \fCNone\fP, float  refresh_per_second = \fC10\fP, StyleType  style = \fC'bar\&.back'\fP, StyleType  complete_style = \fC'bar\&.complete'\fP, StyleType  finished_style = \fC'bar\&.finished'\fP, StyleType  pulse_style = \fC'bar\&.pulse'\fP, bool  disable = \fCFalse\fP)"

.SS " Iterable[\fBProgressType\fP] pip\&._vendor\&.rich\&.progress\&.track (Union[Sequence[\fBProgressType\fP], Iterable[\fBProgressType\fP]] sequence, str  description = \fC'Working\&.\&.\&.'\fP, Optional[float]  total = \fCNone\fP, bool  auto_refresh = \fCTrue\fP, Optional[\fBConsole\fP]  console = \fCNone\fP, bool  transient = \fCFalse\fP, Optional[Callable[[], float]]  get_time = \fCNone\fP, float  refresh_per_second = \fC10\fP, StyleType  style = \fC'bar\&.back'\fP, StyleType  complete_style = \fC'bar\&.complete'\fP, StyleType  finished_style = \fC'bar\&.finished'\fP, StyleType  pulse_style = \fC'bar\&.pulse'\fP, float  update_period = \fC0\&.1\fP, bool  disable = \fCFalse\fP, bool  show_speed = \fCTrue\fP)"

.PP
.nf
Track progress by iterating over a sequence\&.

Args:
    sequence (Iterable[ProgressType]): A sequence (must support 'len') you wish to iterate over\&.
    description (str, optional): Description of task show next to progress bar\&. Defaults to 'Working'\&.
    total: (float, optional): Total number of steps\&. Default is len(sequence)\&.
    auto_refresh (bool, optional): Automatic refresh, disable to force a refresh after each iteration\&. Default is True\&.
    transient: (bool, optional): Clear the progress on exit\&. Defaults to False\&.
    console (Console, optional): Console to write to\&. Default creates internal Console instance\&.
    refresh_per_second (float): Number of times per second to refresh the progress information\&. Defaults to 10\&.
    style (StyleType, optional): Style for the bar background\&. Defaults to 'bar\&.back'\&.
    complete_style (StyleType, optional): Style for the completed bar\&. Defaults to 'bar\&.complete'\&.
    finished_style (StyleType, optional): Style for a finished bar\&. Defaults to 'bar\&.finished'\&.
    pulse_style (StyleType, optional): Style for pulsing bars\&. Defaults to 'bar\&.pulse'\&.
    update_period (float, optional): Minimum time (in seconds) between calls to update()\&. Defaults to 0\&.1\&.
    disable (bool, optional): Disable display of progress\&.
    show_speed (bool, optional): Show speed if total isn't known\&. Defaults to True\&.
Returns:
    Iterable[ProgressType]: An iterable of the values in the sequence\&.
.fi
.PP
 
.SS " ContextManager[BinaryIO] pip\&._vendor\&.rich\&.progress\&.wrap_file (BinaryIO file, int total, *str  description = \fC'Reading\&.\&.\&.'\fP, bool  auto_refresh = \fCTrue\fP, Optional[\fBConsole\fP]  console = \fCNone\fP, bool  transient = \fCFalse\fP, Optional[Callable[[], float]]  get_time = \fCNone\fP, float  refresh_per_second = \fC10\fP, StyleType  style = \fC'bar\&.back'\fP, StyleType  complete_style = \fC'bar\&.complete'\fP, StyleType  finished_style = \fC'bar\&.finished'\fP, StyleType  pulse_style = \fC'bar\&.pulse'\fP, bool  disable = \fCFalse\fP)"

.PP
.nf
Read bytes from a file while tracking progress\&.

Args:
    file (Union[str, PathLike[str], BinaryIO]): The path to the file to read, or a file-like object in binary mode\&.
    total (int): Total number of bytes to read\&.
    description (str, optional): Description of task show next to progress bar\&. Defaults to 'Reading'\&.
    auto_refresh (bool, optional): Automatic refresh, disable to force a refresh after each iteration\&. Default is True\&.
    transient: (bool, optional): Clear the progress on exit\&. Defaults to False\&.
    console (Console, optional): Console to write to\&. Default creates internal Console instance\&.
    refresh_per_second (float): Number of times per second to refresh the progress information\&. Defaults to 10\&.
    style (StyleType, optional): Style for the bar background\&. Defaults to 'bar\&.back'\&.
    complete_style (StyleType, optional): Style for the completed bar\&. Defaults to 'bar\&.complete'\&.
    finished_style (StyleType, optional): Style for a finished bar\&. Defaults to 'bar\&.finished'\&.
    pulse_style (StyleType, optional): Style for pulsing bars\&. Defaults to 'bar\&.pulse'\&.
    disable (bool, optional): Disable display of progress\&.
Returns:
    ContextManager[BinaryIO]: A context manager yielding a progress reader\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.progress\&._I = typing\&.TypeVar('_I', TextIO, BinaryIO)\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.progress\&.advance"

.SS "pip\&._vendor\&.rich\&.progress\&.console = \fBConsole\fP(record=True)"

.SS "pip\&._vendor\&.rich\&.progress\&.examples = cycle(\fBprogress_renderables\fP)"

.SS "pip\&._vendor\&.rich\&.progress\&.GetTimeCallable = Callable[[], float]"

.SS "list pip\&._vendor\&.rich\&.progress\&.progress_renderables"
\fBInitial value:\fP.PP
.nf
1 =  [
2         "Text may be printed while the progress bars are rendering\&.",
3         Panel("In fact, [i]any[/i] renderable will work"),
4         "Such as [magenta]tables[/]\&.\&.\&.",
5         table,
6         "Pretty printed structures\&.\&.\&.",
7         {"type": "example", "text": "Pretty printed"},
8         "Syntax\&.\&.\&.",
9         syntax,
10         Rule("Give it a try!"),
11     ]
.fi

.SS "pip\&._vendor\&.rich\&.progress\&.ProgressType = TypeVar('ProgressType')"

.SS "pip\&._vendor\&.rich\&.progress\&.syntax"
\fBInitial value:\fP.PP
.nf
1 =  Syntax(
2         ,
3         "python",
4         line_numbers=True,
5     )
.fi

.SS "pip\&._vendor\&.rich\&.progress\&.table = \fBTable\fP('foo', 'bar', 'baz')"

.SS "pip\&._vendor\&.rich\&.progress\&.task1 = progress\&.add_task('[red]Downloading', total=1000)"

.SS "pip\&._vendor\&.rich\&.progress\&.task2 = progress\&.add_task('[green]Processing', total=1000)"

.SS "pip\&._vendor\&.rich\&.progress\&.task3 = progress\&.add_task('[yellow]Thinking', total=None)"

.SS "pip\&._vendor\&.rich\&.progress\&.TaskID = NewType('TaskID', int)"

.SS "pip\&._vendor\&.rich\&.progress\&.transient"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
