.TH "pip._vendor.typing_extensions.NoDefaultTypeMeta" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.typing_extensions.NoDefaultTypeMeta
.SH SYNOPSIS
.br
.PP
.PP
Inherits type\&.
.PP
Inherited by \fBpip\&._vendor\&.typing_extensions\&.NoDefaultType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__setattr__\fP (cls, attr, value)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.typing_extensions\&.NoDefaultTypeMeta\&.__setattr__ ( cls,  attr,  value)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
