.TH "pip._vendor.distlib.database.InstalledDistribution" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.database.InstalledDistribution
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.distlib\&.database\&.BaseInstalledDistribution\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBpath\fP, \fBmetadata\fP=None, env=None)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.ti -1c
.RI "\fBexports\fP (self)"
.br
.ti -1c
.RI "\fBread_exports\fP (self)"
.br
.ti -1c
.RI "\fBwrite_exports\fP (self, \fBexports\fP)"
.br
.ti -1c
.RI "\fBget_resource_path\fP (self, relative_path)"
.br
.ti -1c
.RI "\fBlist_installed_files\fP (self)"
.br
.ti -1c
.RI "\fBwrite_installed_files\fP (self, paths, prefix, dry_run=False)"
.br
.ti -1c
.RI "\fBcheck_installed_files\fP (self)"
.br
.ti -1c
.RI "\fBshared_locations\fP (self)"
.br
.ti -1c
.RI "\fBwrite_shared_locations\fP (self, paths, dry_run=False)"
.br
.ti -1c
.RI "\fBget_distinfo_resource\fP (self, \fBpath\fP)"
.br
.ti -1c
.RI "\fBget_distinfo_file\fP (self, \fBpath\fP)"
.br
.ti -1c
.RI "\fBlist_distinfo_files\fP (self)"
.br
.ti -1c
.RI "\fB__eq__\fP (self, other)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.distlib\&.database\&.BaseInstalledDistribution\fP
.in +1c
.ti -1c
.RI "\fBget_hash\fP (self, data, \fBhasher\fP=None)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.distlib\&.database\&.Distribution\fP
.in +1c
.ti -1c
.RI "\fBsource_url\fP (self)"
.br
.ti -1c
.RI "\fBname_and_version\fP (self)"
.br
.ti -1c
.RI "\fBprovides\fP (self)"
.br
.ti -1c
.RI "\fBrun_requires\fP (self)"
.br
.ti -1c
.RI "\fBmeta_requires\fP (self)"
.br
.ti -1c
.RI "\fBbuild_requires\fP (self)"
.br
.ti -1c
.RI "\fBtest_requires\fP (self)"
.br
.ti -1c
.RI "\fBdev_requires\fP (self)"
.br
.ti -1c
.RI "\fBmatches_requirement\fP (self, req)"
.br
.ti -1c
.RI "\fB__hash__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodules\fP"
.br
.ti -1c
.RI "\fBfinder\fP"
.br
.ti -1c
.RI "\fBrequested\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.distlib\&.database\&.BaseInstalledDistribution\fP
.in +1c
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBdist_path\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.distlib\&.database\&.Distribution\fP
.in +1c
.ti -1c
.RI "\fBmetadata\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBlocator\fP"
.br
.ti -1c
.RI "\fBdigest\fP"
.br
.ti -1c
.RI "\fBextras\fP"
.br
.ti -1c
.RI "\fBcontext\fP"
.br
.ti -1c
.RI "\fBdownload_urls\fP"
.br
.ti -1c
.RI "\fBdigests\fP"
.br
.ti -1c
.RI "\fBsource_url\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBhasher\fP = 'sha256'"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._vendor\&.distlib\&.database\&.BaseInstalledDistribution\fP
.in +1c
.ti -1c
.RI "\fBhasher\fP = None"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._vendor\&.distlib\&.database\&.Distribution\fP
.in +1c
.ti -1c
.RI "bool \fBbuild_time_dependency\fP = False"
.br
.ti -1c
.RI "bool \fBrequested\fP = False"
.br
.ti -1c
.RI "\fBdownload_url\fP = \fBsource_url\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_get_records\fP (self)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.distlib\&.database\&.Distribution\fP
.in +1c
.ti -1c
.RI "\fB_get_requirements\fP (self, req_attr)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Created with the *path* of the ``\&.dist-info`` directory provided to the
constructor\&. It reads the metadata contained in ``pydist\&.json`` when it is
instantiated\&., or uses a passed in Metadata instance (useful for when
dry-run mode is being used)\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.__init__ ( self,  metadata,  path = \fCNone\fP,  env = \fCNone\fP)"

.PP
.nf
Initialise an instance\&.
:param metadata: An instance of :class:`Metadata` which describes the
                 distribution\&. This will normally have been initialised
                 from a metadata file in the ``path``\&.
:param path:     The path of the ``\&.dist-info`` or ``\&.egg-info``
                 directory for the distribution\&.
:param env:      This is normally the :class:`DistributionPath`
                 instance where this distribution was found\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.distlib\&.database\&.BaseInstalledDistribution\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.__eq__ ( self,  other)"

.PP
.nf
See if this distribution is the same as another\&.
:param other: The distribution to compare with\&. To be equal to one
              another\&. distributions must have the same type, name,
              version and source_url\&.
:return: True if it is the same, else False\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.distlib\&.database\&.Distribution\fP\&.
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.__repr__ ( self)"

.PP
.nf
Return a textual representation of this instance,

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.distlib\&.database\&.Distribution\fP\&.
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.__str__ ( self)"

.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&._get_records ( self)\fC [protected]\fP"

.PP
.nf
Get the list of installed files for the distribution
:return: A list of tuples of path, hash and size\&. Note that hash and
         size might be ``None`` for some entries\&. The path is exactly
         as stored in the file (which is as in PEP 376)\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.check_installed_files ( self)"

.PP
.nf
Checks that the hashes and sizes of the files in ``RECORD`` are
matched by the files themselves\&. Returns a (possibly empty) list of
mismatches\&. Each entry in the mismatch list will be a tuple consisting
of the path, 'exists', 'size' or 'hash' according to what didn't match
(existence is checked first, then size, then hash), the expected
value and the actual value\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.exports ( self)"

.PP
.nf
Return the information exported by this distribution\&.
:return: A dictionary of exports, mapping an export category to a dict
         of :class:`ExportEntry` instances describing the individual
         export entries, and keyed by name\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.get_distinfo_file ( self,  path)"

.PP
.nf
Returns a path located under the ``\&.dist-info`` directory\&. Returns a
string representing the path\&.

:parameter path: a ``'/'``-separated path relative to the
                 ``\&.dist-info`` directory or an absolute path;
                 If *path* is an absolute path and doesn't start
                 with the ``\&.dist-info`` directory path,
                 a :class:`DistlibException` is raised
:type path: str
:rtype: str

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.get_distinfo_resource ( self,  path)"

.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.get_resource_path ( self,  relative_path)"

.PP
.nf
NOTE: This API may change in the future\&.

Return the absolute path to a resource file with the given relative
path\&.

:param relative_path: The path, relative to \&.dist-info, of the resource
                      of interest\&.
:return: The absolute path where the resource is to be found\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.list_distinfo_files ( self)"

.PP
.nf
Iterates over the ``RECORD`` entries and returns paths for each line if
the path is pointing to a file located in the ``\&.dist-info`` directory
or one of its subdirectories\&.

:returns: iterator of paths

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.list_installed_files ( self)"

.PP
.nf
Iterates over the ``RECORD`` entries and returns a tuple
``(path, hash, size)`` for each line\&.

:returns: iterator of (path, hash, size)

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.read_exports ( self)"

.PP
.nf
Read exports data from a file in \&.ini format\&.

:return: A dictionary of exports, mapping an export category to a list
         of :class:`ExportEntry` instances describing the individual
         export entries\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.shared_locations ( self)"

.PP
.nf
A dictionary of shared locations whose keys are in the set 'prefix',
'purelib', 'platlib', 'scripts', 'headers', 'data' and 'namespace'\&.
The corresponding value is the absolute path of that category for
this distribution, and takes into account any paths selected by the
user at installation time (e\&.g\&. via command-line arguments)\&. In the
case of the 'namespace' key, this would be a list of absolute paths
for the roots of namespace packages in this distribution\&.

The first time this property is accessed, the relevant information is
read from the SHARED file in the \&.dist-info directory\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.write_exports ( self,  exports)"

.PP
.nf
Write a dictionary of exports to a file in \&.ini format\&.
:param exports: A dictionary of exports, mapping an export category to
                a list of :class:`ExportEntry` instances describing the
                individual export entries\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.write_installed_files ( self,  paths,  prefix,  dry_run = \fCFalse\fP)"

.PP
.nf
Writes the ``RECORD`` file, using the ``paths`` iterable passed in\&. Any
existing ``RECORD`` file is silently overwritten\&.

prefix is used to determine when to write absolute paths\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.write_shared_locations ( self,  paths,  dry_run = \fCFalse\fP)"

.PP
.nf
Write shared location information to the SHARED file in \&.dist-info\&.
:param paths: A dictionary as described in the documentation for
:meth:`shared_locations`\&.
:param dry_run: If True, the action is logged but no file is actually
                written\&.
:return: The path of the file written to\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.finder"

.SS "str pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.hasher = 'sha256'\fC [static]\fP"

.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.modules"

.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.name"

.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.path"

.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.requested"

.SS "pip\&._vendor\&.distlib\&.database\&.InstalledDistribution\&.version"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
