.TH "pip._vendor.rich._fileno" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._fileno
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int|None \fBget_fileno\fP (IO[str] file_like)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " int | None pip\&._vendor\&.rich\&._fileno\&.get_fileno (IO[str] file_like)"

.PP
.nf
Get fileno() from a file, accounting for poorly implemented file-like objects\&.

Args:
    file_like (IO): A file-like object\&.

Returns:
    int | None: The result of fileno if available, or None if operation failed\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
