.TH "pip._vendor.rich.traceback.Trace" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.traceback.Trace
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "List \fBstacks\fP [\fBStack\fP]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "List pip\&._vendor\&.rich\&.traceback\&.Trace\&.stacks [\fBStack\fP]\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
