.TH "pip._internal.operations.build.wheel_legacy" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.operations.build.wheel_legacy
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBformat_command_result\fP (List[str] command_args, str command_output)"
.br
.ti -1c
.RI "Optional[str] \fBget_legacy_build_wheel_path\fP (List[str] names, str temp_dir, str name, List[str] command_args, str command_output)"
.br
.ti -1c
.RI "Optional[str] \fBbuild_wheel_legacy\fP (str name, str setup_py_path, str source_dir, List[str] global_options, List[str] build_options, str tempd)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " Optional[str] pip\&._internal\&.operations\&.build\&.wheel_legacy\&.build_wheel_legacy (str name, str setup_py_path, str source_dir, List[str] global_options, List[str] build_options, str tempd)"

.PP
.nf
Build one unpacked package using the 'legacy' build process\&.

Returns path to wheel if successfully built\&. Otherwise, returns None\&.

.fi
.PP
 
.SS " str pip\&._internal\&.operations\&.build\&.wheel_legacy\&.format_command_result (List[str] command_args, str command_output)"

.PP
.nf
Format command information for logging\&.
.fi
.PP
 
.SS " Optional[str] pip\&._internal\&.operations\&.build\&.wheel_legacy\&.get_legacy_build_wheel_path (List[str] names, str temp_dir, str name, List[str] command_args, str command_output)"

.PP
.nf
Return the path to the wheel in the temporary build directory\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._internal\&.operations\&.build\&.wheel_legacy\&.logger = logging\&.getLogger(__name__)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
