.TH "pip._internal.models.link.Link" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.models.link.Link
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBurl\fP, Optional[Union[str, 'IndexContent']] \fBcomes_from\fP=None, Optional[str] \fBrequires_python\fP=None, Optional[str] \fByanked_reason\fP=None, Optional[\fBMetadataFile\fP] \fBmetadata_file_data\fP=None, bool \fBcache_link_parsing\fP=True, Optional[Mapping[str, str]] hashes=None)"
.br
.ti -1c
.RI "Optional['Link'] \fBfrom_json\fP (cls, Dict[str, Any] file_data, str page_url)"
.br
.ti -1c
.RI "Optional['Link'] \fBfrom_element\fP (cls, Dict[str, Optional[str]] anchor_attribs, str page_url, str base_url)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "int \fB__hash__\fP (self)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, Any other)"
.br
.ti -1c
.RI "bool \fB__lt__\fP (self, Any other)"
.br
.ti -1c
.RI "str \fBurl\fP (self)"
.br
.ti -1c
.RI "str \fBfilename\fP (self)"
.br
.ti -1c
.RI "str \fBfile_path\fP (self)"
.br
.ti -1c
.RI "str \fBscheme\fP (self)"
.br
.ti -1c
.RI "str \fBnetloc\fP (self)"
.br
.ti -1c
.RI "str \fBpath\fP (self)"
.br
.ti -1c
.RI "Tuple[str, str] \fBsplitext\fP (self)"
.br
.ti -1c
.RI "str \fBext\fP (self)"
.br
.ti -1c
.RI "str \fBurl_without_fragment\fP (self)"
.br
.ti -1c
.RI "Optional[str] \fBsubdirectory_fragment\fP (self)"
.br
.ti -1c
.RI "Optional['Link'] \fBmetadata_link\fP (self)"
.br
.ti -1c
.RI "\fBHashes\fP \fBas_hashes\fP (self)"
.br
.ti -1c
.RI "Optional[str] \fBhash\fP (self)"
.br
.ti -1c
.RI "Optional[str] \fBhash_name\fP (self)"
.br
.ti -1c
.RI "str \fBshow_url\fP (self)"
.br
.ti -1c
.RI "bool \fBis_file\fP (self)"
.br
.ti -1c
.RI "bool \fBis_existing_dir\fP (self)"
.br
.ti -1c
.RI "bool \fBis_wheel\fP (self)"
.br
.ti -1c
.RI "bool \fBis_vcs\fP (self)"
.br
.ti -1c
.RI "bool \fBis_yanked\fP (self)"
.br
.ti -1c
.RI "bool \fBhas_hash\fP (self)"
.br
.ti -1c
.RI "bool \fBis_hash_allowed\fP (self, Optional[\fBHashes\fP] hashes)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcomes_from\fP"
.br
.ti -1c
.RI "\fBrequires_python\fP"
.br
.ti -1c
.RI "\fByanked_reason\fP"
.br
.ti -1c
.RI "\fBmetadata_file_data\fP"
.br
.ti -1c
.RI "\fBcache_link_parsing\fP"
.br
.ti -1c
.RI "\fBegg_fragment\fP"
.br
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBscheme\fP"
.br
.ti -1c
.RI "\fBfile_path\fP"
.br
.ti -1c
.RI "\fBext\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Optional[str] \fB_egg_fragment\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_parsed_url\fP"
.br
.ti -1c
.RI "\fB_url\fP"
.br
.ti -1c
.RI "\fB_hashes\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_egg_fragment_re\fP = re\&.compile(r'[#&]egg=([^&]*)')"
.br
.ti -1c
.RI "\fB_project_name_re\fP"
.br
.ti -1c
.RI "\fB_subdirectory_fragment_re\fP = re\&.compile(r'[#&]subdirectory=([^&]*)')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a parsed link from a Package Index's simple URL
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.models\&.link\&.Link\&.__init__ ( self, str url, Optional[Union[str, 'IndexContent']]  comes_from = \fCNone\fP, Optional[str]  requires_python = \fCNone\fP, Optional[str]  yanked_reason = \fCNone\fP, Optional[\fBMetadataFile\fP]  metadata_file_data = \fCNone\fP, bool  cache_link_parsing = \fCTrue\fP, Optional[Mapping[str, str]]  hashes = \fCNone\fP)"

.PP
.nf
:param url: url of the resource pointed to (href of the link)
:param comes_from: instance of IndexContent where the link was found,
    or string\&.
:param requires_python: String containing the `Requires-Python`
    metadata field, specified in PEP 345\&. This may be specified by
    a data-requires-python attribute in the HTML link tag, as
    described in PEP 503\&.
:param yanked_reason: the reason the file has been yanked, if the
    file has been yanked, or None if the file hasn't been yanked\&.
    This is the value of the 'data-yanked' attribute, if present, in
    a simple repository HTML link\&. If the file has been yanked but
    no reason was provided, this should be the empty string\&. See
    PEP 592 for more information and the specification\&.
:param metadata_file_data: the metadata attached to the file, or None if
    no such metadata is provided\&. This argument, if not None, indicates
    that a separate metadata file exists, and also optionally supplies
    hashes for that file\&.
:param cache_link_parsing: A flag that is used elsewhere to determine
    whether resources retrieved from this link should be cached\&. PyPI
    URLs should generally have this set to False, for example\&.
:param hashes: A mapping of hash names to digests to allow us to
    determine the validity of a download\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " bool pip\&._internal\&.models\&.link\&.Link\&.__eq__ ( self, Any other)"

.SS " int pip\&._internal\&.models\&.link\&.Link\&.__hash__ ( self)"

.SS " bool pip\&._internal\&.models\&.link\&.Link\&.__lt__ ( self, Any other)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.__repr__ ( self)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.__str__ ( self)"

.SS " Optional[str] pip\&._internal\&.models\&.link\&.Link\&._egg_fragment ( self)\fC [protected]\fP"

.SS " \fBHashes\fP pip\&._internal\&.models\&.link\&.Link\&.as_hashes ( self)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.ext ( self)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.file_path ( self)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.filename ( self)"

.SS " Optional['Link'] pip\&._internal\&.models\&.link\&.Link\&.from_element ( cls, Dict[str, Optional[str]] anchor_attribs, str page_url, str base_url)"

.PP
.nf
Convert an anchor element's attributes in a simple repository page to a Link\&.

.fi
.PP
 
.SS " Optional['Link'] pip\&._internal\&.models\&.link\&.Link\&.from_json ( cls, Dict[str, Any] file_data, str page_url)"

.PP
.nf
Convert an pypi json document from a simple repository page into a Link\&.

.fi
.PP
 
.SS " bool pip\&._internal\&.models\&.link\&.Link\&.has_hash ( self)"

.SS " Optional[str] pip\&._internal\&.models\&.link\&.Link\&.hash ( self)"

.SS " Optional[str] pip\&._internal\&.models\&.link\&.Link\&.hash_name ( self)"

.SS " bool pip\&._internal\&.models\&.link\&.Link\&.is_existing_dir ( self)"

.SS " bool pip\&._internal\&.models\&.link\&.Link\&.is_file ( self)"

.SS " bool pip\&._internal\&.models\&.link\&.Link\&.is_hash_allowed ( self, Optional[\fBHashes\fP] hashes)"

.PP
.nf
Return True if the link has a hash and it is allowed by `hashes`\&.

.fi
.PP
 
.SS " bool pip\&._internal\&.models\&.link\&.Link\&.is_vcs ( self)"

.SS " bool pip\&._internal\&.models\&.link\&.Link\&.is_wheel ( self)"

.SS " bool pip\&._internal\&.models\&.link\&.Link\&.is_yanked ( self)"

.SS " Optional['Link'] pip\&._internal\&.models\&.link\&.Link\&.metadata_link ( self)"

.PP
.nf
Return a link to the associated core metadata file (if any)\&.
.fi
.PP
 
.SS " str pip\&._internal\&.models\&.link\&.Link\&.netloc ( self)"

.PP
.nf
This can contain auth information\&.

.fi
.PP
 
.SS " str pip\&._internal\&.models\&.link\&.Link\&.path ( self)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.scheme ( self)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.show_url ( self)"

.SS " Tuple[str, str] pip\&._internal\&.models\&.link\&.Link\&.splitext ( self)"

.SS " Optional[str] pip\&._internal\&.models\&.link\&.Link\&.subdirectory_fragment ( self)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.url ( self)"

.SS " str pip\&._internal\&.models\&.link\&.Link\&.url_without_fragment ( self)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.models\&.link\&.Link\&._egg_fragment_re = re\&.compile(r'[#&]egg=([^&]*)')\fC [static]\fP, \fC [protected]\fP"

.SS "pip\&._internal\&.models\&.link\&.Link\&._hashes\fC [protected]\fP"

.SS "pip\&._internal\&.models\&.link\&.Link\&._parsed_url\fC [protected]\fP"

.SS "pip\&._internal\&.models\&.link\&.Link\&._project_name_re\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
=  re\&.compile(
        r"^([A\-Z0\-9]|[A\-Z0\-9][A\-Z0\-9\&._\-]*[A\-Z0\-9])$", re\&.IGNORECASE
    )
.fi

.SS "pip\&._internal\&.models\&.link\&.Link\&._subdirectory_fragment_re = re\&.compile(r'[#&]subdirectory=([^&]*)')\fC [static]\fP, \fC [protected]\fP"

.SS "pip\&._internal\&.models\&.link\&.Link\&._url\fC [protected]\fP"

.SS "pip\&._internal\&.models\&.link\&.Link\&.cache_link_parsing"

.SS "pip\&._internal\&.models\&.link\&.Link\&.comes_from"

.SS "pip\&._internal\&.models\&.link\&.Link\&.egg_fragment"

.SS "pip\&._internal\&.models\&.link\&.Link\&.ext"

.SS "pip\&._internal\&.models\&.link\&.Link\&.file_path"

.SS "pip\&._internal\&.models\&.link\&.Link\&.metadata_file_data"

.SS "pip\&._internal\&.models\&.link\&.Link\&.requires_python"

.SS "pip\&._internal\&.models\&.link\&.Link\&.scheme"

.SS "pip\&._internal\&.models\&.link\&.Link\&.url"

.SS "pip\&._internal\&.models\&.link\&.Link\&.yanked_reason"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
