.TH "pip._vendor.rich.syntax.SyntaxTheme" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.syntax.SyntaxTheme
.SH SYNOPSIS
.br
.PP
.PP
Inherits ABC\&.
.PP
Inherited by \fBpip\&._vendor\&.rich\&.syntax\&.ANSISyntaxTheme\fP, and \fBpip\&._vendor\&.rich\&.syntax\&.PygmentsSyntaxTheme\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStyle\fP \fBget_style_for_token\fP (self, \fBTokenType\fP token_type)"
.br
.ti -1c
.RI "\fBStyle\fP \fBget_background_style\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base class for a syntax theme\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " \fBStyle\fP pip\&._vendor\&.rich\&.syntax\&.SyntaxTheme\&.get_background_style ( self)"

.PP
.nf
Get the background color\&.
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.rich\&.syntax\&.PygmentsSyntaxTheme\fP, and \fBpip\&._vendor\&.rich\&.syntax\&.ANSISyntaxTheme\fP\&.
.SS " \fBStyle\fP pip\&._vendor\&.rich\&.syntax\&.SyntaxTheme\&.get_style_for_token ( self, \fBTokenType\fP token_type)"

.PP
.nf
Get a style for a given Pygments token\&.
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.rich\&.syntax\&.PygmentsSyntaxTheme\fP, and \fBpip\&._vendor\&.rich\&.syntax\&.ANSISyntaxTheme\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
