.TH "pip._vendor.pkg_resources.PkgResourcesDeprecationWarning" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pkg_resources.PkgResourcesDeprecationWarning
.SH SYNOPSIS
.br
.PP
.PP
Inherits Warning\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Base class for warning about deprecations in ``pkg_resources``

This class is not derived from ``DeprecationWarning``, and as such is
visible by default\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
