.TH "pip._vendor.requests.structures.LookupDict" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.requests.structures.LookupDict
.SH SYNOPSIS
.br
.PP
.PP
Inherits dict\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBname\fP=None)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__getitem__\fP (self, key)"
.br
.ti -1c
.RI "\fBget\fP (self, key, default=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Dictionary lookup object\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.requests\&.structures\&.LookupDict\&.__init__ ( self,  name = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.requests\&.structures\&.LookupDict\&.__getitem__ ( self,  key)"

.SS "pip\&._vendor\&.requests\&.structures\&.LookupDict\&.__repr__ ( self)"

.SS "pip\&._vendor\&.requests\&.structures\&.LookupDict\&.get ( self,  key,  default = \fCNone\fP)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.requests\&.structures\&.LookupDict\&.name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
