.TH "pip._internal.index.sources._RemoteFileSource" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.index.sources._RemoteFileSource
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._internal\&.index\&.sources\&.LinkSource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBCandidatesFromPage\fP candidates_from_page, \fBPageValidator\fP page_validator, \fBLink\fP \fBlink\fP)"
.br
.ti -1c
.RI "Optional[\fBLink\fP] \fBlink\fP (self)"
.br
.ti -1c
.RI "\fBFoundCandidates\fP \fBpage_candidates\fP (self)"
.br
.ti -1c
.RI "\fBFoundLinks\fP \fBfile_links\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_candidates_from_page\fP"
.br
.ti -1c
.RI "\fB_page_validator\fP"
.br
.ti -1c
.RI "\fB_link\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
``--find-links=<url>`` or ``--[extra-]index-url=<url>``\&.

This returns:

* ``page_candidates``: Links listed on an HTML file\&.
* ``file_candidates``: The non-HTML file\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.index\&.sources\&._RemoteFileSource\&.__init__ ( self, \fBCandidatesFromPage\fP candidates_from_page, \fBPageValidator\fP page_validator, \fBLink\fP link)"

.SH "Member Function Documentation"
.PP 
.SS " \fBFoundLinks\fP pip\&._internal\&.index\&.sources\&._RemoteFileSource\&.file_links ( self)"

.PP
.nf
Links found by specifying archives directly\&.
.fi
.PP
 
.PP
Reimplemented from \fBpip\&._internal\&.index\&.sources\&.LinkSource\fP\&.
.SS " Optional[\fBLink\fP] pip\&._internal\&.index\&.sources\&._RemoteFileSource\&.link ( self)"

.PP
.nf
Returns the underlying link, if there's one\&.
.fi
.PP
 
.PP
Reimplemented from \fBpip\&._internal\&.index\&.sources\&.LinkSource\fP\&.
.SS " \fBFoundCandidates\fP pip\&._internal\&.index\&.sources\&._RemoteFileSource\&.page_candidates ( self)"

.PP
.nf
Candidates found by parsing an archive listing HTML file\&.
.fi
.PP
 
.PP
Reimplemented from \fBpip\&._internal\&.index\&.sources\&.LinkSource\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.index\&.sources\&._RemoteFileSource\&._candidates_from_page\fC [protected]\fP"

.SS "pip\&._internal\&.index\&.sources\&._RemoteFileSource\&._link\fC [protected]\fP"

.SS "pip\&._internal\&.index\&.sources\&._RemoteFileSource\&._page_validator\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
