.TH "pip._vendor.packaging.utils" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging.utils
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInvalidName\fP"
.br
.ti -1c
.RI "class \fBInvalidSdistFilename\fP"
.br
.ti -1c
.RI "class \fBInvalidWheelFilename\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNormalizedName\fP \fBcanonicalize_name\fP (str name, *bool validate=False)"
.br
.ti -1c
.RI "bool \fBis_normalized_name\fP (str name)"
.br
.ti -1c
.RI "str \fBcanonicalize_version\fP (\fBVersion\fP|str version, *bool strip_trailing_zero=True)"
.br
.ti -1c
.RI "tuple[\fBNormalizedName\fP, \fBVersion\fP, \fBBuildTag\fP, frozenset[\fBTag\fP]] \fBparse_wheel_filename\fP (str filename)"
.br
.ti -1c
.RI "tuple[\fBNormalizedName\fP, \fBVersion\fP] \fBparse_sdist_filename\fP (str filename)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBuildTag\fP = Union[Tuple[()], Tuple[int, str]]"
.br
.ti -1c
.RI "\fBNormalizedName\fP = NewType('NormalizedName', str)"
.br
.ti -1c
.RI "\fB_validate_regex\fP"
.br
.ti -1c
.RI "\fB_canonicalize_regex\fP = re\&.compile(r'[\-_\&.]+')"
.br
.ti -1c
.RI "\fB_normalized_regex\fP = re\&.compile(r'^([a\-z0\-9]|[a\-z0\-9]([a\-z0\-9\-](?!\-\-))*[a\-z0\-9])$')"
.br
.ti -1c
.RI "\fB_build_tag_regex\fP = re\&.compile(r'(\\d+)(\&.*)')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " \fBNormalizedName\fP pip\&._vendor\&.packaging\&.utils\&.canonicalize_name (str name, *bool  validate = \fCFalse\fP)"

.SS " str pip\&._vendor\&.packaging\&.utils\&.canonicalize_version (\fBVersion\fP | str version, *bool  strip_trailing_zero = \fCTrue\fP)"

.PP
.nf
This is very similar to Version\&.__str__, but has one subtle difference
with the way it handles the release segment\&.

.fi
.PP
 
.SS " bool pip\&._vendor\&.packaging\&.utils\&.is_normalized_name (str name)"

.SS " tuple[\fBNormalizedName\fP, \fBVersion\fP] pip\&._vendor\&.packaging\&.utils\&.parse_sdist_filename (str filename)"

.SS " tuple[\fBNormalizedName\fP, \fBVersion\fP, \fBBuildTag\fP, frozenset[\fBTag\fP]] pip\&._vendor\&.packaging\&.utils\&.parse_wheel_filename (str filename)"

.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.packaging\&.utils\&._build_tag_regex = re\&.compile(r'(\\d+)(\&.*)')\fC [protected]\fP"

.SS "pip\&._vendor\&.packaging\&.utils\&._canonicalize_regex = re\&.compile(r'[\-_\&.]+')\fC [protected]\fP"

.SS "pip\&._vendor\&.packaging\&.utils\&._normalized_regex = re\&.compile(r'^([a\-z0\-9]|[a\-z0\-9]([a\-z0\-9\-](?!\-\-))*[a\-z0\-9])$')\fC [protected]\fP"

.SS "pip\&._vendor\&.packaging\&.utils\&._validate_regex\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  re\&.compile(
2     r"^([A\-Z0\-9]|[A\-Z0\-9][A\-Z0\-9\&._\-]*[A\-Z0\-9])$", re\&.IGNORECASE
3 )
.fi

.SS "pip\&._vendor\&.packaging\&.utils\&.BuildTag = Union[Tuple[()], Tuple[int, str]]"

.SS "pip\&._vendor\&.packaging\&.utils\&.NormalizedName = NewType('NormalizedName', str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
