.TH "pip._vendor.rich.console.ConsoleOptions" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.console.ConsoleOptions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBascii_only\fP (self)"
.br
.ti -1c
.RI "'ConsoleOptions' \fBcopy\fP (self)"
.br
.ti -1c
.RI "'ConsoleOptions' \fBupdate\fP (self, *Union[int, \fBNoChange\fP] width=\fBNO_CHANGE\fP, Union[int, \fBNoChange\fP] \fBmin_width\fP=\fBNO_CHANGE\fP, Union[int, \fBNoChange\fP] \fBmax_width\fP=\fBNO_CHANGE\fP, Union[Optional[\fBJustifyMethod\fP], \fBNoChange\fP] \fBjustify\fP=\fBNO_CHANGE\fP, Union[Optional[\fBOverflowMethod\fP], \fBNoChange\fP] \fBoverflow\fP=\fBNO_CHANGE\fP, Union[Optional[bool], \fBNoChange\fP] \fBno_wrap\fP=\fBNO_CHANGE\fP, Union[Optional[bool], \fBNoChange\fP] \fBhighlight\fP=\fBNO_CHANGE\fP, Union[Optional[bool], \fBNoChange\fP] \fBmarkup\fP=\fBNO_CHANGE\fP, Union[Optional[int], \fBNoChange\fP] \fBheight\fP=\fBNO_CHANGE\fP)"
.br
.ti -1c
.RI "'ConsoleOptions' \fBupdate_width\fP (self, int width)"
.br
.ti -1c
.RI "'ConsoleOptions' \fBupdate_height\fP (self, int \fBheight\fP)"
.br
.ti -1c
.RI "'ConsoleOptions' \fBreset_height\fP (self)"
.br
.ti -1c
.RI "'ConsoleOptions' \fBupdate_dimensions\fP (self, int width, int \fBheight\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBConsoleDimensions\fP \fBsize\fP"
.br
.ti -1c
.RI "bool \fBlegacy_windows\fP"
.br
.ti -1c
.RI "int \fBmin_width\fP"
.br
.ti -1c
.RI "int \fBmax_width\fP"
.br
.ti -1c
.RI "bool \fBis_terminal\fP"
.br
.ti -1c
.RI "str \fBencoding\fP"
.br
.ti -1c
.RI "int \fBmax_height\fP"
.br
.ti -1c
.RI "Optional \fBjustify\fP = None"
.br
.ti -1c
.RI "Optional \fBoverflow\fP = None"
.br
.ti -1c
.RI "Optional \fBno_wrap\fP = False"
.br
.ti -1c
.RI "Optional \fBhighlight\fP = None"
.br
.ti -1c
.RI "Optional \fBmarkup\fP = None"
.br
.ti -1c
.RI "Optional \fBheight\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Options for __rich_console__ method\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " bool pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.ascii_only ( self)"

.PP
.nf
Check if renderables should use ascii only\&.
.fi
.PP
 
.SS " 'ConsoleOptions' pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.copy ( self)"

.PP
.nf
Return a copy of the options\&.

Returns:
    ConsoleOptions: a copy of self\&.

.fi
.PP
 
.SS " 'ConsoleOptions' pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.reset_height ( self)"

.PP
.nf
Return a copy of the options with height set to ``None``\&.

Returns:
    ~ConsoleOptions: New console options instance\&.

.fi
.PP
 
.SS " 'ConsoleOptions' pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.update ( self, *Union[int, \fBNoChange\fP]  width = \fC\fBNO_CHANGE\fP\fP, Union[int, \fBNoChange\fP]  min_width = \fC\fBNO_CHANGE\fP\fP, Union[int, \fBNoChange\fP]  max_width = \fC\fBNO_CHANGE\fP\fP, Union[Optional[\fBJustifyMethod\fP], \fBNoChange\fP]  justify = \fC\fBNO_CHANGE\fP\fP, Union[Optional[\fBOverflowMethod\fP], \fBNoChange\fP]  overflow = \fC\fBNO_CHANGE\fP\fP, Union[Optional[bool], \fBNoChange\fP]  no_wrap = \fC\fBNO_CHANGE\fP\fP, Union[Optional[bool], \fBNoChange\fP]  highlight = \fC\fBNO_CHANGE\fP\fP, Union[Optional[bool], \fBNoChange\fP]  markup = \fC\fBNO_CHANGE\fP\fP, Union[Optional[int], \fBNoChange\fP]  height = \fC\fBNO_CHANGE\fP\fP)"

.PP
.nf
Update values, return a copy\&.
.fi
.PP
 
.SS " 'ConsoleOptions' pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.update_dimensions ( self, int width, int height)"

.PP
.nf
Update the width and height, and return a copy\&.

Args:
    width (int): New width (sets both min_width and max_width)\&.
    height (int): New height\&.

Returns:
    ~ConsoleOptions: New console options instance\&.

.fi
.PP
 
.SS " 'ConsoleOptions' pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.update_height ( self, int height)"

.PP
.nf
Update the height, and return a copy\&.

Args:
    height (int): New height

Returns:
    ~ConsoleOptions: New Console options instance\&.

.fi
.PP
 
.SS " 'ConsoleOptions' pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.update_width ( self, int width)"

.PP
.nf
Update just the width, return a copy\&.

Args:
    width (int): New width (sets both min_width and max_width)

Returns:
    ~ConsoleOptions: New console options instance\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "str pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.encoding\fC [static]\fP"

.SS "Optional pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.height = None\fC [static]\fP"

.SS "Optional pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.highlight = None\fC [static]\fP"

.SS "bool pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.is_terminal\fC [static]\fP"

.SS "Optional pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.justify = None\fC [static]\fP"

.SS "bool pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.legacy_windows\fC [static]\fP"

.SS "Optional pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.markup = None\fC [static]\fP"

.SS "int pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.max_height\fC [static]\fP"

.SS "int pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.max_width\fC [static]\fP"

.SS "int pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.min_width\fC [static]\fP"

.SS "Optional pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.no_wrap = False\fC [static]\fP"

.SS "Optional pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.overflow = None\fC [static]\fP"

.SS "\fBConsoleDimensions\fP pip\&._vendor\&.rich\&.console\&.ConsoleOptions\&.size\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
