.TH "pip._vendor.packaging.requirements.InvalidRequirement" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging.requirements.InvalidRequirement
.SH SYNOPSIS
.br
.PP
.PP
Inherits ValueError\&.
.SH "Detailed Description"
.PP 

.PP
.nf
An invalid requirement was found, users should refer to PEP 508\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
