.TH "pip._vendor.pygments.formatters.terminal" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pygments.formatters.terminal
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerminalFormatter\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBTERMINAL_COLORS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.formatters\&.terminal
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Formatter for terminal output with ANSI sequences\&.

    :copyright: Copyright 2006-2024 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict pip\&._vendor\&.pygments\&.formatters\&.terminal\&.TERMINAL_COLORS"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
