.TH "pip._internal.cache.CacheEntry" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.cache.CacheEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBLink\fP \fBlink\fP, bool \fBpersistent\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlink\fP"
.br
.ti -1c
.RI "\fBpersistent\fP"
.br
.ti -1c
.RI "\fBorigin\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._internal\&.cache\&.CacheEntry\&.__init__ ( self, \fBLink\fP link, bool persistent)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.cache\&.CacheEntry\&.link"

.SS "pip\&._internal\&.cache\&.CacheEntry\&.origin"

.SS "pip\&._internal\&.cache\&.CacheEntry\&.persistent"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
