.TH "pip._vendor.rich._windows" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich._windows
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindowsConsoleFeatures\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBWindowsConsoleFeatures\fP \fBget_windows_console_features\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBWindowsConsoleFeatures\fP \fBfeatures\fP = \fBget_windows_console_features\fP()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBWindowsConsoleFeatures\fP pip\&._vendor\&.rich\&._windows\&.get_windows_console_features ()"

.PP
.nf
Get windows console features\&.

Returns:
    WindowsConsoleFeatures: An instance of WindowsConsoleFeatures\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "\fBWindowsConsoleFeatures\fP pip\&._vendor\&.rich\&._windows\&.features = \fBget_windows_console_features\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
