.TH "pip._internal.models.target_python.TargetPython" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.models.target_python.TargetPython
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, Optional[List[str]] \fBplatforms\fP=None, Optional[Tuple[int,\&.\&.\&.]] \fBpy_version_info\fP=None, Optional[List[str]] \fBabis\fP=None, Optional[str] \fBimplementation\fP=None)"
.br
.ti -1c
.RI "str \fBformat_given\fP (self)"
.br
.ti -1c
.RI "List[\fBTag\fP] \fBget_sorted_tags\fP (self)"
.br
.ti -1c
.RI "Set[\fBTag\fP] \fBget_unsorted_tags\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBabis\fP"
.br
.ti -1c
.RI "\fBimplementation\fP"
.br
.ti -1c
.RI "\fBplatforms\fP"
.br
.ti -1c
.RI "\fBpy_version\fP"
.br
.ti -1c
.RI "\fBpy_version_info\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_given_py_version_info\fP"
.br
.ti -1c
.RI "\fB_valid_tags\fP"
.br
.ti -1c
.RI "\fB_valid_tags_set\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Encapsulates the properties of a Python interpreter one is targeting
for a package install, download, etc\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.models\&.target_python\&.TargetPython\&.__init__ ( self, Optional[List[str]]  platforms = \fCNone\fP, Optional[Tuple[int, \&.\&.\&.]]  py_version_info = \fCNone\fP, Optional[List[str]]  abis = \fCNone\fP, Optional[str]  implementation = \fCNone\fP)"

.PP
.nf
:param platforms: A list of strings or None\&. If None, searches for
    packages that are supported by the current system\&. Otherwise, will
    find packages that can be built on the platforms passed in\&. These
    packages will only be downloaded for distribution: they will
    not be built locally\&.
:param py_version_info: An optional tuple of ints representing the
    Python version information to use (e\&.g\&. `sys\&.version_info[:3]`)\&.
    This can have length 1, 2, or 3 when provided\&.
:param abis: A list of strings or None\&. This is passed to
    compatibility_tags\&.py's get_supported() function as is\&.
:param implementation: A string or None\&. This is passed to
    compatibility_tags\&.py's get_supported() function as is\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str pip\&._internal\&.models\&.target_python\&.TargetPython\&.format_given ( self)"

.PP
.nf
Format the given, non-None attributes for display\&.

.fi
.PP
 
.SS " List[\fBTag\fP] pip\&._internal\&.models\&.target_python\&.TargetPython\&.get_sorted_tags ( self)"

.PP
.nf
Return the supported PEP 425 tags to check wheel candidates against\&.

The tags are returned in order of preference (most preferred first)\&.

.fi
.PP
 
.SS " Set[\fBTag\fP] pip\&._internal\&.models\&.target_python\&.TargetPython\&.get_unsorted_tags ( self)"

.PP
.nf
Exactly the same as get_sorted_tags, but returns a set\&.

This is important for performance\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.models\&.target_python\&.TargetPython\&._given_py_version_info\fC [protected]\fP"

.SS "pip\&._internal\&.models\&.target_python\&.TargetPython\&._valid_tags\fC [protected]\fP"

.SS "pip\&._internal\&.models\&.target_python\&.TargetPython\&._valid_tags_set\fC [protected]\fP"

.SS "pip\&._internal\&.models\&.target_python\&.TargetPython\&.abis"

.SS "pip\&._internal\&.models\&.target_python\&.TargetPython\&.implementation"

.SS "pip\&._internal\&.models\&.target_python\&.TargetPython\&.platforms"

.SS "pip\&._internal\&.models\&.target_python\&.TargetPython\&.py_version"

.SS "pip\&._internal\&.models\&.target_python\&.TargetPython\&.py_version_info"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
