.TH "pip._vendor.rich.markup" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.markup
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTag\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBescape\fP (str markup, \fB_EscapeSubMethod\fP _escape=re\&.compile(r'(\\\\*)(\\[[a\-z#/@][^[]*?])')\&.sub)"
.br
.ti -1c
.RI "Iterable[Tuple[int, Optional[str], Optional[\fBTag\fP]]] \fB_parse\fP (str markup)"
.br
.ti -1c
.RI "\fBText\fP \fBrender\fP (str markup, Union[str, \fBStyle\fP] style='', bool emoji=True, Optional[EmojiVariant] emoji_variant=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRE_TAGS\fP"
.br
.ti -1c
.RI "\fBRE_HANDLER\fP = re\&.compile(r'^([\\w\&.]*?)(\\(\&.*?\\))?$')"
.br
.ti -1c
.RI "\fB_ReStringMatch\fP = Match[str]"
.br
.ti -1c
.RI "\fB_ReSubCallable\fP = Callable[[\fB_ReStringMatch\fP], str]"
.br
.ti -1c
.RI "\fB_EscapeSubMethod\fP = Callable[[\fB_ReSubCallable\fP, str], str]"
.br
.ti -1c
.RI "list \fBMARKUP\fP"
.br
.ti -1c
.RI "\fBgrid\fP = \fBTable\fP('Markup', 'Result', padding=(0, 1))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " Iterable[Tuple[int, Optional[str], Optional[\fBTag\fP]]] pip\&._vendor\&.rich\&.markup\&._parse (str markup)\fC [protected]\fP"

.PP
.nf
Parse markup in to an iterable of tuples of (position, text, tag)\&.

Args:
    markup (str): A string containing console markup
.fi
.PP
 
.SS " str pip\&._vendor\&.rich\&.markup\&.escape (str markup, \fB_EscapeSubMethod\fP  _escape = \fCre\&.compile(r'(\\\\*)(\\[[a\-z#/@][^[]*?])')\&.sub\fP)"

.PP
.nf
Escapes text so that it won't be interpreted as markup\&.

Args:
    markup (str): Content to be inserted in to markup\&.

Returns:
    str: Markup with square brackets escaped\&.

.fi
.PP
 
.SS " \fBText\fP pip\&._vendor\&.rich\&.markup\&.render (str markup, Union[str, \fBStyle\fP]  style = \fC''\fP, bool  emoji = \fCTrue\fP, Optional[EmojiVariant]  emoji_variant = \fCNone\fP)"

.PP
.nf
Render console markup in to a Text instance\&.

Args:
    markup (str): A string containing console markup\&.
    style: (Union[str, Style]): The style to use\&.
    emoji (bool, optional): Also render emoji code\&. Defaults to True\&.
    emoji_variant (str, optional): Optional emoji variant, either 'text' or 'emoji'\&. Defaults to None\&.


Raises:
    MarkupError: If there is a syntax error in the markup\&.

Returns:
    Text: A test instance\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.markup\&._EscapeSubMethod = Callable[[\fB_ReSubCallable\fP, str], str]\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.markup\&._ReStringMatch = Match[str]\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.markup\&._ReSubCallable = Callable[[\fB_ReStringMatch\fP], str]\fC [protected]\fP"

.SS "pip\&._vendor\&.rich\&.markup\&.grid = \fBTable\fP('Markup', 'Result', padding=(0, 1))"

.SS "list pip\&._vendor\&.rich\&.markup\&.MARKUP"
\fBInitial value:\fP.PP
.nf
1 =  [
2         "[red]Hello World[/red]",
3         "[magenta]Hello [b]World[/b]",
4         "[bold]Bold[italic] bold and italic [/bold]italic[/italic]",
5         "Click [link=https://www\&.willmcgugan\&.com]here[/link] to visit my Blog",
6         ":warning\-emoji: [bold red blink] DANGER![/]",
7     ]
.fi

.SS "pip\&._vendor\&.rich\&.markup\&.RE_HANDLER = re\&.compile(r'^([\\w\&.]*?)(\\(\&.*?\\))?$')"

.SS "pip\&._vendor\&.rich\&.markup\&.RE_TAGS"
\fBInitial value:\fP.PP
.nf
1 =  re\&.compile(
2     ,
3     re\&.VERBOSE,
4 )
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
