.TH "pip._vendor.idna.core.InvalidCodepointContext" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.idna.core.InvalidCodepointContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.idna\&.core\&.IDNAError\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
 Exception when the codepoint is not valid in the context it is used 
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
