.TH "pip._vendor.pkg_resources.DistInfoDistribution" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pkg_resources.DistInfoDistribution
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.pkg_resources\&.Distribution\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBPKG_INFO\fP = 'METADATA'"
.br
.ti -1c
.RI "\fBEQEQ\fP = re\&.compile(r'([\\(,])\\s*(\\d\&.*?)\\s*([,\\)])')"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._vendor\&.pkg_resources\&.Distribution\fP
.in +1c
.ti -1c
.RI "str \fBPKG_INFO\fP = 'PKG\-\fBINFO\fP'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_parsed_pkg_info\fP (self)"
.br
.ti -1c
.RI "\fB_dep_map\fP (self)"
.br
.ti -1c
.RI "dict[str|None, list[\fBRequirement\fP]] \fB_compute_dependencies\fP (self)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.pkg_resources\&.Distribution\fP
.in +1c
.ti -1c
.RI "\fB_reload_version\fP (self)"
.br
.ti -1c
.RI "\fB_forgiving_parsed_version\fP (self)"
.br
.ti -1c
.RI "\fB_build_dep_map\fP (self)"
.br
.ti -1c
.RI "\fB_get_metadata_path_for_display\fP (self, name)"
.br
.ti -1c
.RI "\fB_get_metadata\fP (self, name)"
.br
.ti -1c
.RI "\fB_get_version\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_pkg_info\fP"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._vendor\&.pkg_resources\&.Distribution\fP
.in +1c
.ti -1c
.RI "\fB_version\fP"
.br
.ti -1c
.RI "\fB_provider\fP"
.br
.ti -1c
.RI "\fB_forgiving_parsed_version\fP"
.br
.ti -1c
.RI "\fB_key\fP"
.br
.ti -1c
.RI "\fB_parsed_version\fP"
.br
.ti -1c
.RI "\fB_ep_map\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBpip\&._vendor\&.pkg_resources\&.Distribution\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, str|None \fBlocation\fP=None, \fB_MetadataType\fP metadata=None, str|None \fBproject_name\fP=None, str|None \fBversion\fP=None, str|None \fBpy_version\fP=\fBPY_MAJOR\fP, str|None \fBplatform\fP=None, int \fBprecedence\fP=\fBEGG_DIST\fP)"
.br
.ti -1c
.RI "\fBDistribution\fP \fBfrom_location\fP (cls, str \fBlocation\fP, StrPath basename, \fB_MetadataType\fP metadata=None, **int kw)"
.br
.ti -1c
.RI "\fBhashcmp\fP (self)"
.br
.ti -1c
.RI "\fB__hash__\fP (self)"
.br
.ti -1c
.RI "\fB__lt__\fP (self, \fBDistribution\fP other)"
.br
.ti -1c
.RI "\fB__le__\fP (self, \fBDistribution\fP other)"
.br
.ti -1c
.RI "\fB__gt__\fP (self, \fBDistribution\fP other)"
.br
.ti -1c
.RI "\fB__ge__\fP (self, \fBDistribution\fP other)"
.br
.ti -1c
.RI "\fB__eq__\fP (self, object other)"
.br
.ti -1c
.RI "\fB__ne__\fP (self, object other)"
.br
.ti -1c
.RI "\fBkey\fP (self)"
.br
.ti -1c
.RI "\fBparsed_version\fP (self)"
.br
.ti -1c
.RI "\fBversion\fP (self)"
.br
.ti -1c
.RI "\fBrequires\fP (self, Iterable[str] \fBextras\fP=())"
.br
.ti -1c
.RI "\fBactivate\fP (self, list[str]|None path=None, bool replace=False)"
.br
.ti -1c
.RI "\fBegg_name\fP (self)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.ti -1c
.RI "\fB__getattr__\fP (self, attr)"
.br
.ti -1c
.RI "\fB__dir__\fP (self)"
.br
.ti -1c
.RI "\fBfrom_filename\fP (cls, StrPath filename, \fB_MetadataType\fP metadata=None, **int kw)"
.br
.ti -1c
.RI "\fBas_requirement\fP (self)"
.br
.ti -1c
.RI "\fB_ResolvedEntryPoint\fP \fBload_entry_point\fP (self, str group, str name)"
.br
.ti -1c
.RI "dict[str, dict[str, \fBEntryPoint\fP]] \fBget_entry_map\fP (self, None group=None)"
.br
.ti -1c
.RI "dict[str, \fBEntryPoint\fP] \fBget_entry_map\fP (self, str group)"
.br
.ti -1c
.RI "\fBget_entry_map\fP (self, str|None group=None)"
.br
.ti -1c
.RI "\fBget_entry_info\fP (self, str group, str name)"
.br
.ti -1c
.RI "\fBinsert_on\fP (self, list[str] path, loc=None, bool replace=False)"
.br
.ti -1c
.RI "\fBcheck_version_conflict\fP (self)"
.br
.ti -1c
.RI "\fBhas_version\fP (self)"
.br
.ti -1c
.RI "\fBclone\fP (self, **str|int|\fBIResourceProvider\fP|None kw)"
.br
.ti -1c
.RI "\fBextras\fP (self)"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.pkg_resources\&.Distribution\fP
.in +1c
.ti -1c
.RI "\fBproject_name\fP"
.br
.ti -1c
.RI "\fBpy_version\fP"
.br
.ti -1c
.RI "\fBplatform\fP"
.br
.ti -1c
.RI "\fBlocation\fP"
.br
.ti -1c
.RI "\fBprecedence\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBhashcmp\fP"
.br
.ti -1c
.RI "\fBPKG_INFO\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBparsed_version\fP"
.br
.in -1c

Static Protected Member Functions inherited from \fBpip\&._vendor\&.pkg_resources\&.Distribution\fP
.in +1c
.ti -1c
.RI "\fB_filter_extras\fP (dict[str|None, list[\fBRequirement\fP]] dm)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Wrap an actual or potential sys\&.path entry
w/metadata, \&.dist-info style\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " dict[str | None, list[\fBRequirement\fP]] pip\&._vendor\&.pkg_resources\&.DistInfoDistribution\&._compute_dependencies ( self)\fC [protected]\fP"

.PP
.nf
Recompute this distribution's dependencies\&.
.fi
.PP
 
.SS "pip\&._vendor\&.pkg_resources\&.DistInfoDistribution\&._dep_map ( self)\fC [protected]\fP"

.PP
.nf
A map of extra to its list of (direct) requirements
for this distribution, including the null extra\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.pkg_resources\&.Distribution\fP\&.
.SS "pip\&._vendor\&.pkg_resources\&.DistInfoDistribution\&._parsed_pkg_info ( self)\fC [protected]\fP"

.PP
.nf
Parse and cache metadata
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.pkg_resources\&.DistInfoDistribution\&._pkg_info\fC [protected]\fP"

.SS "pip\&._vendor\&.pkg_resources\&.DistInfoDistribution\&.EQEQ = re\&.compile(r'([\\(,])\\s*(\\d\&.*?)\\s*([,\\)])')\fC [static]\fP"

.SS "str pip\&._vendor\&.pkg_resources\&.DistInfoDistribution\&.PKG_INFO = 'METADATA'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
