.TH "pip._internal.exceptions.ExternallyManagedEnvironment" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.exceptions.ExternallyManagedEnvironment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._internal\&.exceptions\&.DiagnosticPipError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, Optional[str] error)"
.br
.ti -1c
.RI "'ExternallyManagedEnvironment' \fBfrom_config\fP (cls, Union[pathlib\&.Path, str] config)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._internal\&.exceptions\&.DiagnosticPipError\fP
.in +1c
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "RenderResult \fB__rich_console__\fP (self, \fBConsole\fP console, \fBConsoleOptions\fP options)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBreference\fP = 'externally\-managed\-environment'"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._internal\&.exceptions\&.DiagnosticPipError\fP
.in +1c
.ti -1c
.RI "str \fBreference\fP"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "Iterator[str] \fB_iter_externally_managed_error_keys\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBpip\&._internal\&.exceptions\&.DiagnosticPipError\fP
.in +1c
.ti -1c
.RI "\fBkind\fP"
.br
.ti -1c
.RI "\fBreference\fP"
.br
.ti -1c
.RI "\fBmessage\fP"
.br
.ti -1c
.RI "\fBcontext\fP"
.br
.ti -1c
.RI "\fBnote_stmt\fP"
.br
.ti -1c
.RI "\fBhint_stmt\fP"
.br
.ti -1c
.RI "\fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The current environment is externally managed\&.

This is raised when the current environment is externally managed, as
defined by `PEP 668`_\&. The ``EXTERNALLY-MANAGED`` configuration is checked
and displayed when the error is bubbled up to the user\&.

:param error: The error message read from ``EXTERNALLY-MANAGED``\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.exceptions\&.ExternallyManagedEnvironment\&.__init__ ( self, Optional[str] error)"

.PP
Reimplemented from \fBpip\&._internal\&.exceptions\&.DiagnosticPipError\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " Iterator[str] pip\&._internal\&.exceptions\&.ExternallyManagedEnvironment\&._iter_externally_managed_error_keys ()\fC [static]\fP, \fC [protected]\fP"

.SS " 'ExternallyManagedEnvironment' pip\&._internal\&.exceptions\&.ExternallyManagedEnvironment\&.from_config ( cls, Union[pathlib\&.Path, str] config)"

.SH "Member Data Documentation"
.PP 
.SS "str pip\&._internal\&.exceptions\&.ExternallyManagedEnvironment\&.reference = 'externally\-managed\-environment'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
