.TH "pip._internal.commands.show._PackageInfo" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.commands.show._PackageInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits NamedTuple\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP"
.br
.ti -1c
.RI "str \fBversion\fP"
.br
.ti -1c
.RI "str \fBlocation\fP"
.br
.ti -1c
.RI "Optional \fBeditable_project_location\fP [str]"
.br
.ti -1c
.RI "List \fBrequires\fP [str]"
.br
.ti -1c
.RI "List \fBrequired_by\fP [str]"
.br
.ti -1c
.RI "str \fBinstaller\fP"
.br
.ti -1c
.RI "str \fBmetadata_version\fP"
.br
.ti -1c
.RI "List \fBclassifiers\fP [str]"
.br
.ti -1c
.RI "str \fBsummary\fP"
.br
.ti -1c
.RI "str \fBhomepage\fP"
.br
.ti -1c
.RI "List \fBproject_urls\fP [str]"
.br
.ti -1c
.RI "str \fBauthor\fP"
.br
.ti -1c
.RI "str \fBauthor_email\fP"
.br
.ti -1c
.RI "str \fBlicense\fP"
.br
.ti -1c
.RI "List \fBentry_points\fP [str]"
.br
.ti -1c
.RI "Optional \fBfiles\fP [List[str]]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.author\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.author_email\fC [static]\fP"

.SS "List pip\&._internal\&.commands\&.show\&._PackageInfo\&.classifiers [str]\fC [static]\fP"

.SS "Optional pip\&._internal\&.commands\&.show\&._PackageInfo\&.editable_project_location [str]\fC [static]\fP"

.SS "List pip\&._internal\&.commands\&.show\&._PackageInfo\&.entry_points [str]\fC [static]\fP"

.SS "Optional pip\&._internal\&.commands\&.show\&._PackageInfo\&.files [List[str]]\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.homepage\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.installer\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.license\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.location\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.metadata_version\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.name\fC [static]\fP"

.SS "List pip\&._internal\&.commands\&.show\&._PackageInfo\&.project_urls [str]\fC [static]\fP"

.SS "List pip\&._internal\&.commands\&.show\&._PackageInfo\&.required_by [str]\fC [static]\fP"

.SS "List pip\&._internal\&.commands\&.show\&._PackageInfo\&.requires [str]\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.summary\fC [static]\fP"

.SS "str pip\&._internal\&.commands\&.show\&._PackageInfo\&.version\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
