.TH "pip._vendor.pkg_resources.RequirementParseError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pkg_resources.RequirementParseError
.SH SYNOPSIS
.br
.PP
.PP
Inherits _packaging_requirements\&.InvalidRequirement\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
