.TH "pip._vendor.urllib3.contrib.socks.SOCKSConnection" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.urllib3.contrib.socks.SOCKSConnection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP\&.
.PP
Inherited by \fBpip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSHTTPSConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, *args, **kwargs)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fBhost\fP (self)"
.br
.ti -1c
.RI "\fBhost\fP (self, value)"
.br
.ti -1c
.RI "\fBconnect\fP (self)"
.br
.ti -1c
.RI "\fBputrequest\fP (self, method, url, *args, **kwargs)"
.br
.ti -1c
.RI "\fBputheader\fP (self, header, *values)"
.br
.ti -1c
.RI "\fBrequest\fP (self, method, url, body=None, headers=None)"
.br
.ti -1c
.RI "\fBrequest_chunked\fP (self, method, url, body=None, headers=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBtimeout\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fBsource_address\fP"
.br
.ti -1c
.RI "\fBsocket_options\fP"
.br
.ti -1c
.RI "\fBproxy\fP"
.br
.ti -1c
.RI "\fBproxy_config\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBtimeout\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBsock\fP"
.br
.ti -1c
.RI "\fBauto_open\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_new_conn\fP (self)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fB_is_using_tunnel\fP (self)"
.br
.ti -1c
.RI "\fB_prepare_conn\fP (self, conn)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_socks_options\fP"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fB_dns_host\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP
.in +1c
.ti -1c
.RI "\fBdefault_port\fP = \fBport_by_scheme\fP['http']"
.br
.ti -1c
.RI "list \fBdefault_socket_options\fP = [(socket\&.IPPROTO_TCP, socket\&.TCP_NODELAY, 1)]"
.br
.ti -1c
.RI "bool \fBis_verified\fP = False"
.br
.ti -1c
.RI "\fBproxy_is_verified\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A plain-text HTTP connection that connects via a SOCKS proxy\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSConnection\&.__init__ ( self, * args, ** kwargs)"

.PP
Reimplemented from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSConnection\&._new_conn ( self)\fC [protected]\fP"

.PP
.nf
Establish a new connection via the SOCKS proxy\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.urllib3\&.connection\&.HTTPConnection\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSConnection\&._socks_options\fC [protected]\fP"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSConnection\&.host"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSConnection\&.port"

.SS "pip\&._vendor\&.urllib3\&.contrib\&.socks\&.SOCKSConnection\&.timeout"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
