.TH "pip._internal.cli.index_command.SessionCommandMixin" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.cli.index_command.SessionCommandMixin
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._internal\&.cli\&.command_context\&.CommandContextMixIn\fP\&.
.PP
Inherited by \fBpip\&._internal\&.cli\&.index_command\&.IndexGroupCommand\fP, \fBpip\&._internal\&.commands\&.search\&.SearchCommand\fP, and \fBpip\&._internal\&.commands\&.uninstall\&.UninstallCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self)"
.br
.ti -1c
.RI "'PipSession' \fBget_default_session\fP (self, Values options)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._internal\&.cli\&.command_context\&.CommandContextMixIn\fP
.in +1c
.ti -1c
.RI "Generator[None, None, None] \fBmain_context\fP (self)"
.br
.ti -1c
.RI "\fB_T\fP \fBenter_context\fP (self, ContextManager[\fB_T\fP] context_provider)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Optional[List[str]] \fB_get_index_urls\fP (cls, Values options)"
.br
.ti -1c
.RI "'PipSession' \fB_build_session\fP (self, Values options, Optional[int] retries=None, Optional[int] timeout=None)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_session\fP"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._internal\&.cli\&.command_context\&.CommandContextMixIn\fP
.in +1c
.ti -1c
.RI "\fB_in_main_context\fP"
.br
.ti -1c
.RI "\fB_main_context\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A class mixin for command classes needing _build_session()\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.cli\&.index_command\&.SessionCommandMixin\&.__init__ ( self)"

.PP
Reimplemented from \fBpip\&._internal\&.cli\&.command_context\&.CommandContextMixIn\fP\&.
.PP
Reimplemented in \fBpip\&._internal\&.cli\&.req_command\&.RequirementCommand\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " 'PipSession' pip\&._internal\&.cli\&.index_command\&.SessionCommandMixin\&._build_session ( self, Values options, Optional[int]  retries = \fCNone\fP, Optional[int]  timeout = \fCNone\fP)\fC [protected]\fP"

.SS " Optional[List[str]] pip\&._internal\&.cli\&.index_command\&.SessionCommandMixin\&._get_index_urls ( cls, Values options)\fC [protected]\fP"

.PP
.nf
Return a list of index urls from user-provided options\&.
.fi
.PP
 
.SS " 'PipSession' pip\&._internal\&.cli\&.index_command\&.SessionCommandMixin\&.get_default_session ( self, Values options)"

.PP
.nf
Get a default-managed session\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.cli\&.index_command\&.SessionCommandMixin\&._session\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
