.TH "pip._vendor.pkg_resources.Environment" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pkg_resources.Environment
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, Iterable[str]|None search_path=None, str|None \fBplatform\fP=\fBget_supported_platform\fP(), str|None \fBpython\fP=\fBPY_MAJOR\fP)"
.br
.ti -1c
.RI "\fBcan_add\fP (self, \fBDistribution\fP dist)"
.br
.ti -1c
.RI "\fBremove\fP (self, \fBDistribution\fP dist)"
.br
.ti -1c
.RI "\fBscan\fP (self, Iterable[str]|None search_path=None)"
.br
.ti -1c
.RI "list[\fBDistribution\fP] \fB__getitem__\fP (self, str project_name)"
.br
.ti -1c
.RI "\fBadd\fP (self, \fBDistribution\fP dist)"
.br
.ti -1c
.RI "\fB_DistributionT\fP \fBbest_match\fP (self, \fBRequirement\fP req, \fBWorkingSet\fP \fBworking_set\fP, \fB_InstallerTypeT\fP[\fB_DistributionT\fP] installer, bool replace_conflicting=False)"
.br
.ti -1c
.RI "\fBDistribution\fP|None \fBbest_match\fP (self, \fBRequirement\fP req, \fBWorkingSet\fP \fBworking_set\fP, \fB_InstallerType\fP|None installer=None, bool replace_conflicting=False)"
.br
.ti -1c
.RI "\fBDistribution\fP|None \fBbest_match\fP (self, \fBRequirement\fP req, \fBWorkingSet\fP \fBworking_set\fP, \fB_InstallerType\fP|None|\fB_InstallerTypeT\fP[\fB_DistributionT\fP] installer=None, bool replace_conflicting=False)"
.br
.ti -1c
.RI "\fB_DistributionT\fP \fBobtain\fP (self, \fBRequirement\fP requirement, \fB_InstallerTypeT\fP[\fB_DistributionT\fP] installer)"
.br
.ti -1c
.RI "None \fBobtain\fP (self, \fBRequirement\fP requirement, Callable[[\fBRequirement\fP], None]|None installer=None)"
.br
.ti -1c
.RI "\fBDistribution\fP|None \fBobtain\fP (self, \fBRequirement\fP requirement, \fB_InstallerType\fP|None installer=None)"
.br
.ti -1c
.RI "\fBDistribution\fP|None \fBobtain\fP (self, \fBRequirement\fP requirement, Callable[[\fBRequirement\fP], None]|\fB_InstallerType\fP|None|\fB_InstallerTypeT\fP[\fB_DistributionT\fP] installer=None)"
.br
.ti -1c
.RI "Iterator[str] \fB__iter__\fP (self)"
.br
.ti -1c
.RI "\fB__iadd__\fP (self, \fBDistribution\fP|\fBEnvironment\fP other)"
.br
.ti -1c
.RI "\fB__add__\fP (self, \fBDistribution\fP|\fBEnvironment\fP other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBplatform\fP"
.br
.ti -1c
.RI "\fBpython\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_distmap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Searchable snapshot of distributions on a search path
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.__init__ ( self, Iterable[str] | None  search_path = \fCNone\fP, str | None  platform = \fC\fBget_supported_platform\fP()\fP, str | None  python = \fC\fBPY_MAJOR\fP\fP)"

.PP
.nf
Snapshot distributions available on a search path

Any distributions found on `search_path` are added to the environment\&.
`search_path` should be a sequence of ``sys\&.path`` items\&.  If not
supplied, ``sys\&.path`` is used\&.

`platform` is an optional string specifying the name of the platform
that platform-specific distributions must be compatible with\&.  If
unspecified, it defaults to the current platform\&.  `python` is an
optional string naming the desired version of Python (e\&.g\&. ``'3\&.6'``);
it defaults to the current version\&.

You may explicitly set `platform` (and/or `python`) to ``None`` if you
wish to map *all* distributions, not just those compatible with the
running platform or Python version\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.__add__ ( self, \fBDistribution\fP | \fBEnvironment\fP other)"

.PP
.nf
Add an environment or distribution to an environment
.fi
.PP
 
.SS " list[\fBDistribution\fP] pip\&._vendor\&.pkg_resources\&.Environment\&.__getitem__ ( self, str project_name)"

.PP
.nf
Return a newest-to-oldest list of distributions for `project_name`

Uses case-insensitive `project_name` comparison, assuming all the
project's distributions use their project's name converted to all
lowercase as their key\&.
.fi
.PP
 
.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.__iadd__ ( self, \fBDistribution\fP | \fBEnvironment\fP other)"

.PP
.nf
In-place addition of a distribution or environment
.fi
.PP
 
.SS " Iterator[str] pip\&._vendor\&.pkg_resources\&.Environment\&.__iter__ ( self)"

.PP
.nf
Yield the unique project names of the available distributions
.fi
.PP
 
.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.add ( self, \fBDistribution\fP dist)"

.PP
.nf
Add `dist` if we ``can_add()`` it and it has not already been added
.fi
.PP
 
.SS " \fB_DistributionT\fP pip\&._vendor\&.pkg_resources\&.Environment\&.best_match ( self, \fBRequirement\fP req, \fBWorkingSet\fP working_set, \fB_InstallerTypeT\fP[\fB_DistributionT\fP] installer, bool  replace_conflicting = \fCFalse\fP)"

.SS " \fBDistribution\fP | None pip\&._vendor\&.pkg_resources\&.Environment\&.best_match ( self, \fBRequirement\fP req, \fBWorkingSet\fP working_set, \fB_InstallerType\fP | None  installer = \fCNone\fP, bool  replace_conflicting = \fCFalse\fP)"

.SS " \fBDistribution\fP | None pip\&._vendor\&.pkg_resources\&.Environment\&.best_match ( self, \fBRequirement\fP req, \fBWorkingSet\fP working_set, \fB_InstallerType\fP | None | \fB_InstallerTypeT\fP[\fB_DistributionT\fP]  installer = \fCNone\fP, bool  replace_conflicting = \fCFalse\fP)"

.PP
.nf
Find distribution best matching `req` and usable on `working_set`

This calls the ``find(req)`` method of the `working_set` to see if a
suitable distribution is already active\&.  (This may raise
``VersionConflict`` if an unsuitable version of the project is already
active in the specified `working_set`\&.)  If a suitable distribution
isn't active, this method returns the newest distribution in the
environment that meets the ``Requirement`` in `req`\&.  If no suitable
distribution is found, and `installer` is supplied, then the result of
calling the environment's ``obtain(req, installer)`` method will be
returned\&.

.fi
.PP
 
.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.can_add ( self, \fBDistribution\fP dist)"

.PP
.nf
Is distribution `dist` acceptable for this environment?

The distribution must match the platform and python version
requirements specified when this environment was created, or False
is returned\&.

.fi
.PP
 
.SS " \fB_DistributionT\fP pip\&._vendor\&.pkg_resources\&.Environment\&.obtain ( self, \fBRequirement\fP requirement, \fB_InstallerTypeT\fP[\fB_DistributionT\fP] installer)"

.SS " \fBDistribution\fP | None pip\&._vendor\&.pkg_resources\&.Environment\&.obtain ( self, \fBRequirement\fP requirement, \fB_InstallerType\fP | None  installer = \fCNone\fP)"

.SS " \fBDistribution\fP | None pip\&._vendor\&.pkg_resources\&.Environment\&.obtain ( self, \fBRequirement\fP requirement, Callable[[\fBRequirement\fP], None]
        | \fB_InstallerType\fP
        | None
        | \fB_InstallerTypeT\fP[\fB_DistributionT\fP]  installer = \fCNone\fP)"

.PP
.nf
Obtain a distribution matching `requirement` (e\&.g\&. via download)

Obtain a distro that matches requirement (e\&.g\&. via download)\&.  In the
base ``Environment`` class, this routine just returns
``installer(requirement)``, unless `installer` is None, in which case
None is returned instead\&.  This method is a hook that allows subclasses
to attempt other ways of obtaining a distribution before falling back
to the `installer` argument\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.pkg_resources\&.Environment\&.obtain ( self, \fBRequirement\fP requirement, Callable[[\fBRequirement\fP], None] | None  installer = \fCNone\fP)"

.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.remove ( self, \fBDistribution\fP dist)"

.PP
.nf
Remove `dist` from the environment
.fi
.PP
 
.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.scan ( self, Iterable[str] | None  search_path = \fCNone\fP)"

.PP
.nf
Scan `search_path` for distributions usable in this environment

Any distributions found are added to the environment\&.
`search_path` should be a sequence of ``sys\&.path`` items\&.  If not
supplied, ``sys\&.path`` is used\&.  Only distributions conforming to
the platform/python version defined at initialization are added\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.pkg_resources\&.Environment\&._distmap\fC [protected]\fP"

.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.platform"

.SS "pip\&._vendor\&.pkg_resources\&.Environment\&.python"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
