.TH "pip._internal.network.download.BatchDownloader" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.network.download.BatchDownloader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, PipSession session, str progress_bar)"
.br
.ti -1c
.RI "Iterable[Tuple[\fBLink\fP, Tuple[str, str]]] \fB__call__\fP (self, Iterable[\fBLink\fP] links, str location)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_session\fP"
.br
.ti -1c
.RI "\fB_progress_bar\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.network\&.download\&.BatchDownloader\&.__init__ ( self, PipSession session, str progress_bar)"

.SH "Member Function Documentation"
.PP 
.SS " Iterable[Tuple[\fBLink\fP, Tuple[str, str]]] pip\&._internal\&.network\&.download\&.BatchDownloader\&.__call__ ( self, Iterable[\fBLink\fP] links, str
     location)"

.PP
.nf
Download the files given by links into location\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.network\&.download\&.BatchDownloader\&._progress_bar\fC [protected]\fP"

.SS "pip\&._internal\&.network\&.download\&.BatchDownloader\&._session\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
