.TH "pip._vendor.packaging.markers" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.packaging.markers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnvironment\fP"
.br
.ti -1c
.RI "class \fBInvalidMarker\fP"
.br
.ti -1c
.RI "class \fBMarker\fP"
.br
.ti -1c
.RI "class \fBUndefinedComparison\fP"
.br
.ti -1c
.RI "class \fBUndefinedEnvironmentName\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Any \fB_normalize_extra_values\fP (Any results)"
.br
.ti -1c
.RI "str \fB_format_marker\fP (list[str]|MarkerAtom|str marker, bool|None first=True)"
.br
.ti -1c
.RI "bool \fB_eval_op\fP (str lhs, \fBOp\fP op, str rhs)"
.br
.ti -1c
.RI "tuple[str,\&.\&.\&.] \fB_normalize\fP (*str values, str key)"
.br
.ti -1c
.RI "bool \fB_evaluate_markers\fP (MarkerList markers, dict[str, str] environment)"
.br
.ti -1c
.RI "str \fBformat_full_version\fP (sys\&._version_info info)"
.br
.ti -1c
.RI "\fBEnvironment\fP \fBdefault_environment\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBOperator\fP = Callable[[str, str], bool]"
.br
.ti -1c
.RI "dict \fB_operators\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " bool pip\&._vendor\&.packaging\&.markers\&._eval_op (str lhs, \fBOp\fP op, str rhs)\fC [protected]\fP"

.SS " bool pip\&._vendor\&.packaging\&.markers\&._evaluate_markers (MarkerList markers, dict[str, str] environment)\fC [protected]\fP"

.SS " str pip\&._vendor\&.packaging\&.markers\&._format_marker (list[str] | MarkerAtom | str marker, bool | None  first = \fCTrue\fP)\fC [protected]\fP"

.SS " tuple[str, \&.\&.\&.] pip\&._vendor\&.packaging\&.markers\&._normalize (*str values, str key)\fC [protected]\fP"

.SS " Any pip\&._vendor\&.packaging\&.markers\&._normalize_extra_values (Any results)\fC [protected]\fP"

.PP
.nf
Normalize extra values\&.

.fi
.PP
 
.SS " \fBEnvironment\fP pip\&._vendor\&.packaging\&.markers\&.default_environment ()"

.SS " str pip\&._vendor\&.packaging\&.markers\&.format_full_version (sys\&._version_info info)"

.SH "Variable Documentation"
.PP 
.SS "dict pip\&._vendor\&.packaging\&.markers\&._operators\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  {
2     "in": lambda lhs, rhs: lhs in rhs,
3     "not in": lambda lhs, rhs: lhs not in rhs,
4     "<": operator\&.lt,
5     "<=": operator\&.le,
6     "==": operator\&.eq,
7     "!=": operator\&.ne,
8     ">=": operator\&.ge,
9     ">": operator\&.gt,
10 }
.fi

.SS "pip\&._vendor\&.packaging\&.markers\&.Operator = Callable[[str, str], bool]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
