.TH "pip._vendor.distlib.version.Matcher" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.version.Matcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpip\&._vendor\&.distlib\&.version\&.LegacyMatcher\fP, \fBpip\&._vendor\&.distlib\&.version\&.NormalizedMatcher\fP, and \fBpip\&._vendor\&.distlib\&.version\&.SemanticMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparse_requirement\fP (self, s)"
.br
.ti -1c
.RI "\fB__init__\fP (self, s)"
.br
.ti -1c
.RI "\fBmatch\fP (self, version)"
.br
.ti -1c
.RI "\fBexact_version\fP (self)"
.br
.ti -1c
.RI "\fB__eq__\fP (self, other)"
.br
.ti -1c
.RI "\fB__ne__\fP (self, other)"
.br
.ti -1c
.RI "\fB__hash__\fP (self)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBversion_class\fP = None"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_check_compatible\fP (self, other)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_string\fP"
.br
.ti -1c
.RI "\fB_parts\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "dict \fB_operators\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.__init__ ( self,  s)"

.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.__eq__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.__hash__ ( self)"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.__ne__ ( self,  other)"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.__repr__ ( self)"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.__str__ ( self)"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&._check_compatible ( self,  other)\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.exact_version ( self)"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.match ( self,  version)"

.PP
.nf
Check if the provided version matches the constraints\&.

:param version: The version to match against this instance\&.
:type version: String or :class:`Version` instance\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.parse_requirement ( self,  s)"

.SH "Member Data Documentation"
.PP 
.SS "dict pip\&._vendor\&.distlib\&.version\&.Matcher\&._operators\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
=  {
        '<': lambda v, c, p: v < c,
        '>': lambda v, c, p: v > c,
        '<=': lambda v, c, p: v == c or v < c,
        '>=': lambda v, c, p: v == c or v > c,
        '==': lambda v, c, p: v == c,
        '===': lambda v, c, p: v == c,
        # by default, compatible => >=\&.
        '~=': lambda v, c, p: v == c or v > c,
        '!=': lambda v, c, p: v != c,
    }
.fi

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&._parts\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&._string\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.key"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.name"

.SS "pip\&._vendor\&.distlib\&.version\&.Matcher\&.version_class = None\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
