.TH "pip._vendor.rich" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__main__\fP"
.br
.ti -1c
.RI "namespace \fB_cell_widths\fP"
.br
.ti -1c
.RI "namespace \fB_emoji_codes\fP"
.br
.ti -1c
.RI "namespace \fB_emoji_replace\fP"
.br
.ti -1c
.RI "namespace \fB_export_format\fP"
.br
.ti -1c
.RI "namespace \fB_extension\fP"
.br
.ti -1c
.RI "namespace \fB_fileno\fP"
.br
.ti -1c
.RI "namespace \fB_inspect\fP"
.br
.ti -1c
.RI "namespace \fB_log_render\fP"
.br
.ti -1c
.RI "namespace \fB_loop\fP"
.br
.ti -1c
.RI "namespace \fB_null_file\fP"
.br
.ti -1c
.RI "namespace \fB_palettes\fP"
.br
.ti -1c
.RI "namespace \fB_pick\fP"
.br
.ti -1c
.RI "namespace \fB_ratio\fP"
.br
.ti -1c
.RI "namespace \fB_spinners\fP"
.br
.ti -1c
.RI "namespace \fB_stack\fP"
.br
.ti -1c
.RI "namespace \fB_timer\fP"
.br
.ti -1c
.RI "namespace \fB_win32_console\fP"
.br
.ti -1c
.RI "namespace \fB_windows\fP"
.br
.ti -1c
.RI "namespace \fB_windows_renderer\fP"
.br
.ti -1c
.RI "namespace \fB_wrap\fP"
.br
.ti -1c
.RI "namespace \fBabc\fP"
.br
.ti -1c
.RI "namespace \fBalign\fP"
.br
.ti -1c
.RI "namespace \fBansi\fP"
.br
.ti -1c
.RI "namespace \fBbar\fP"
.br
.ti -1c
.RI "namespace \fBbox\fP"
.br
.ti -1c
.RI "namespace \fBcells\fP"
.br
.ti -1c
.RI "namespace \fBcolor\fP"
.br
.ti -1c
.RI "namespace \fBcolor_triplet\fP"
.br
.ti -1c
.RI "namespace \fBcolumns\fP"
.br
.ti -1c
.RI "namespace \fBconsole\fP"
.br
.ti -1c
.RI "namespace \fBconstrain\fP"
.br
.ti -1c
.RI "namespace \fBcontainers\fP"
.br
.ti -1c
.RI "namespace \fBcontrol\fP"
.br
.ti -1c
.RI "namespace \fBdefault_styles\fP"
.br
.ti -1c
.RI "namespace \fBdiagnose\fP"
.br
.ti -1c
.RI "namespace \fBemoji\fP"
.br
.ti -1c
.RI "namespace \fBerrors\fP"
.br
.ti -1c
.RI "namespace \fBfile_proxy\fP"
.br
.ti -1c
.RI "namespace \fBfilesize\fP"
.br
.ti -1c
.RI "namespace \fBhighlighter\fP"
.br
.ti -1c
.RI "namespace \fBjson\fP"
.br
.ti -1c
.RI "namespace \fBjupyter\fP"
.br
.ti -1c
.RI "namespace \fBlayout\fP"
.br
.ti -1c
.RI "namespace \fBlive\fP"
.br
.ti -1c
.RI "namespace \fBlive_render\fP"
.br
.ti -1c
.RI "namespace \fBlogging\fP"
.br
.ti -1c
.RI "namespace \fBmarkup\fP"
.br
.ti -1c
.RI "namespace \fBmeasure\fP"
.br
.ti -1c
.RI "namespace \fBpadding\fP"
.br
.ti -1c
.RI "namespace \fBpager\fP"
.br
.ti -1c
.RI "namespace \fBpalette\fP"
.br
.ti -1c
.RI "namespace \fBpanel\fP"
.br
.ti -1c
.RI "namespace \fBpretty\fP"
.br
.ti -1c
.RI "namespace \fBprogress\fP"
.br
.ti -1c
.RI "namespace \fBprogress_bar\fP"
.br
.ti -1c
.RI "namespace \fBprompt\fP"
.br
.ti -1c
.RI "namespace \fBprotocol\fP"
.br
.ti -1c
.RI "namespace \fBregion\fP"
.br
.ti -1c
.RI "namespace \fBrepr\fP"
.br
.ti -1c
.RI "namespace \fBrule\fP"
.br
.ti -1c
.RI "namespace \fBscope\fP"
.br
.ti -1c
.RI "namespace \fBscreen\fP"
.br
.ti -1c
.RI "namespace \fBsegment\fP"
.br
.ti -1c
.RI "namespace \fBspinner\fP"
.br
.ti -1c
.RI "namespace \fBstatus\fP"
.br
.ti -1c
.RI "namespace \fBstyle\fP"
.br
.ti -1c
.RI "namespace \fBstyled\fP"
.br
.ti -1c
.RI "namespace \fBsyntax\fP"
.br
.ti -1c
.RI "namespace \fBtable\fP"
.br
.ti -1c
.RI "namespace \fBterminal_theme\fP"
.br
.ti -1c
.RI "namespace \fBtext\fP"
.br
.ti -1c
.RI "namespace \fBtheme\fP"
.br
.ti -1c
.RI "namespace \fBthemes\fP"
.br
.ti -1c
.RI "namespace \fBtraceback\fP"
.br
.ti -1c
.RI "namespace \fBtree\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "'Console' \fBget_console\fP ()"
.br
.ti -1c
.RI "None \fBreconfigure\fP (*Any args, **Any kwargs)"
.br
.ti -1c
.RI "None \fBprint\fP (*Any objects, str sep=' ', str end='\\n', Optional[IO[str]] file=None, bool flush=False)"
.br
.ti -1c
.RI "None \fBprint_json\fP (Optional[str] json=None, *Any data=None, Union[None, int, str] indent=2, bool highlight=True, bool skip_keys=False, bool ensure_ascii=False, bool check_circular=True, bool allow_nan=True, Optional[Callable[[Any], Any]] default=None, bool sort_keys=False)"
.br
.ti -1c
.RI "None \fBinspect\fP (Any obj, *Optional['Console'] console=None, Optional[str] title=None, bool help=False, bool methods=False, bool docs=True, bool private=False, bool dunder=False, bool sort=True, bool all=False, bool value=True)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Optional \fB_console\fP = None"
.br
.ti -1c
.RI "\fB_IMPORT_CWD\fP = os\&.path\&.abspath(os\&.getcwd())"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Rich text and beautiful formatting in the terminal\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " 'Console' pip\&._vendor\&.rich\&.get_console ()"

.PP
.nf
Get a global :class:`~rich\&.console\&.Console` instance\&. This function is used when Rich requires a Console,
and hasn't been explicitly given one\&.

Returns:
    Console: A console instance\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.inspect (Any obj, *Optional['Console']  console = \fCNone\fP, Optional[str]  title = \fCNone\fP, bool  help = \fCFalse\fP, bool  methods = \fCFalse\fP, bool  docs = \fCTrue\fP, bool  private = \fCFalse\fP, bool  dunder = \fCFalse\fP, bool  sort = \fCTrue\fP, bool  all = \fCFalse\fP, bool  value = \fCTrue\fP)"

.PP
.nf
Inspect any Python object\&.

* inspect(<OBJECT>) to see summarized info\&.
* inspect(<OBJECT>, methods=True) to see methods\&.
* inspect(<OBJECT>, help=True) to see full (non-abbreviated) help\&.
* inspect(<OBJECT>, private=True) to see private attributes (single underscore)\&.
* inspect(<OBJECT>, dunder=True) to see attributes beginning with double underscore\&.
* inspect(<OBJECT>, all=True) to see all attributes\&.

Args:
    obj (Any): An object to inspect\&.
    title (str, optional): Title to display over inspect result, or None use type\&. Defaults to None\&.
    help (bool, optional): Show full help text rather than just first paragraph\&. Defaults to False\&.
    methods (bool, optional): Enable inspection of callables\&. Defaults to False\&.
    docs (bool, optional): Also render doc strings\&. Defaults to True\&.
    private (bool, optional): Show private attributes (beginning with underscore)\&. Defaults to False\&.
    dunder (bool, optional): Show attributes starting with double underscore\&. Defaults to False\&.
    sort (bool, optional): Sort attributes alphabetically\&. Defaults to True\&.
    all (bool, optional): Show all attributes\&. Defaults to False\&.
    value (bool, optional): Pretty print value\&. Defaults to True\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.print (*Any objects, str  sep = \fC' '\fP, str  end = \fC'\\n'\fP, Optional[IO[str]]  file = \fCNone\fP, bool  flush = \fCFalse\fP)"

.PP
.nf
Print object(s) supplied via positional arguments\&.
This function has an identical signature to the built-in print\&.
For more advanced features, see the :class:`~rich\&.console\&.Console` class\&.

Args:
    sep (str, optional): Separator between printed objects\&. Defaults to ' '\&.
    end (str, optional): Character to write at end of output\&. Defaults to '\\\\n'\&.
    file (IO[str], optional): File to write to, or None for stdout\&. Defaults to None\&.
    flush (bool, optional): Has no effect as Rich always flushes output\&. Defaults to False\&.
.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.print_json (Optional[str]  json = \fCNone\fP, *Any  data = \fCNone\fP, Union[None, int, str]  indent = \fC2\fP, bool  highlight = \fCTrue\fP, bool  skip_keys = \fCFalse\fP, bool  ensure_ascii = \fCFalse\fP, bool  check_circular = \fCTrue\fP, bool  allow_nan = \fCTrue\fP, Optional[Callable[[Any], Any]]  default = \fCNone\fP, bool  sort_keys = \fCFalse\fP)"

.PP
.nf
Pretty prints JSON\&. Output will be valid JSON\&.

Args:
    json (str): A string containing JSON\&.
    data (Any): If json is not supplied, then encode this data\&.
    indent (int, optional): Number of spaces to indent\&. Defaults to 2\&.
    highlight (bool, optional): Enable highlighting of output: Defaults to True\&.
    skip_keys (bool, optional): Skip keys not of a basic type\&. Defaults to False\&.
    ensure_ascii (bool, optional): Escape all non-ascii characters\&. Defaults to False\&.
    check_circular (bool, optional): Check for circular references\&. Defaults to True\&.
    allow_nan (bool, optional): Allow NaN and Infinity values\&. Defaults to True\&.
    default (Callable, optional): A callable that converts values that can not be encoded
        in to something that can be JSON encoded\&. Defaults to None\&.
    sort_keys (bool, optional): Sort dictionary keys\&. Defaults to False\&.

.fi
.PP
 
.SS " None pip\&._vendor\&.rich\&.reconfigure (*Any args, **Any kwargs)"

.PP
.nf
Reconfigures the global console by replacing it with another\&.

Args:
    *args (Any): Positional arguments for the replacement :class:`~rich\&.console\&.Console`\&.
    **kwargs (Any): Keyword arguments for the replacement :class:`~rich\&.console\&.Console`\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "Optional pip\&._vendor\&.rich\&._console = None\fC [protected]\fP"

.SS "str pip\&._vendor\&.rich\&._IMPORT_CWD = os\&.path\&.abspath(os\&.getcwd())\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
