.TH "pip._vendor.pygments.formatters.img.PilNotAvailable" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pygments.formatters.img.PilNotAvailable
.SH SYNOPSIS
.br
.PP
.PP
Inherits ImportError\&.
.SH "Detailed Description"
.PP 

.PP
.nf
When Python imaging library is not available
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
