.TH "pip._vendor.distlib.locators.SimpleScrapingLocator" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.locators.SimpleScrapingLocator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, url, \fBtimeout\fP=None, \fBnum_workers\fP=10, **kwargs)"
.br
.ti -1c
.RI "\fBget_page\fP (self, url)"
.br
.ti -1c
.RI "\fBget_distribution_names\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP
.in +1c
.ti -1c
.RI "\fBget_errors\fP (self)"
.br
.ti -1c
.RI "\fBclear_errors\fP (self)"
.br
.ti -1c
.RI "\fBclear_cache\fP (self)"
.br
.ti -1c
.RI "\fBget_project\fP (self, name)"
.br
.ti -1c
.RI "\fBscore_url\fP (self, url)"
.br
.ti -1c
.RI "\fBprefer_url\fP (self, url1, url2)"
.br
.ti -1c
.RI "\fBsplit_filename\fP (self, filename, project_name)"
.br
.ti -1c
.RI "\fBconvert_url_to_download_info\fP (self, url, project_name)"
.br
.ti -1c
.RI "\fBlocate\fP (self, requirement, prereleases=False)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbase_url\fP"
.br
.ti -1c
.RI "\fBtimeout\fP"
.br
.ti -1c
.RI "\fBskip_externals\fP"
.br
.ti -1c
.RI "\fBnum_workers\fP"
.br
.ti -1c
.RI "\fBplatform_check\fP"
.br
.ti -1c
.RI "\fBresult\fP"
.br
.ti -1c
.RI "\fBproject_name\fP"
.br
.ti -1c
.RI "\fBexcluded_extensions\fP"
.br
.in -1c

Public Attributes inherited from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP
.in +1c
.ti -1c
.RI "\fBopener\fP"
.br
.ti -1c
.RI "\fBmatcher\fP"
.br
.ti -1c
.RI "\fBerrors\fP"
.br
.ti -1c
.RI "\fBdownloadable_extensions\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dict \fBdecoders\fP"
.br
.ti -1c
.RI "\fBplatform_dependent\fP"
.br
.in -1c

Static Public Attributes inherited from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP
.in +1c
.ti -1c
.RI "tuple \fBsource_extensions\fP = ('\&.tar\&.gz', '\&.tar\&.bz2', '\&.tar', '\&.zip', '\&.tgz', '\&.tbz')"
.br
.ti -1c
.RI "tuple \fBbinary_extensions\fP = ('\&.egg', '\&.exe', '\&.whl')"
.br
.ti -1c
.RI "tuple \fBexcluded_extensions\fP = ('\&.pdf', )"
.br
.ti -1c
.RI "\fBwheel_tags\fP = None"
.br
.ti -1c
.RI "tuple \fBdownloadable_extensions\fP = \fBsource_extensions\fP + ('\&.whl', )"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_prepare_threads\fP (self)"
.br
.ti -1c
.RI "\fB_wait_threads\fP (self)"
.br
.ti -1c
.RI "\fB_get_project\fP (self, name)"
.br
.ti -1c
.RI "\fB_is_platform_dependent\fP (self, url)"
.br
.ti -1c
.RI "\fB_process_download\fP (self, url)"
.br
.ti -1c
.RI "\fB_should_queue\fP (self, link, referrer, rel)"
.br
.ti -1c
.RI "\fB_fetch\fP (self)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP
.in +1c
.ti -1c
.RI "\fB_get_scheme\fP (self)"
.br
.ti -1c
.RI "\fB_set_scheme\fP (self, value)"
.br
.ti -1c
.RI "\fB_get_digest\fP (self, info)"
.br
.ti -1c
.RI "\fB_update_version_data\fP (self, result, info)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_page_cache\fP"
.br
.ti -1c
.RI "\fB_seen\fP"
.br
.ti -1c
.RI "\fB_to_fetch\fP"
.br
.ti -1c
.RI "\fB_bad_hosts\fP"
.br
.ti -1c
.RI "\fB_lock\fP"
.br
.ti -1c
.RI "\fB_gplock\fP"
.br
.ti -1c
.RI "\fB_threads\fP"
.br
.in -1c

Protected Attributes inherited from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP
.in +1c
.ti -1c
.RI "\fB_cache\fP"
.br
.ti -1c
.RI "\fB_scheme\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_distname_re\fP = re\&.compile('<a href=[^>]*>([^<]+)<')"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP
.in +1c
.ti -1c
.RI "\fBscheme\fP = property(\fB_get_scheme\fP, \fB_set_scheme\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A locator which scrapes HTML pages to locate downloads for a distribution\&.
This runs multiple threads to do the I/O; performance is at least as good
as pip's PackageFinder, which works in an analogous fashion\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.__init__ ( self,  url,  timeout = \fCNone\fP,  num_workers = \fC10\fP, ** kwargs)"

.PP
.nf
Initialise an instance\&.
:param url: The root URL to use for scraping\&.
:param timeout: The timeout, in seconds, to be applied to requests\&.
                This defaults to ``None`` (no timeout specified)\&.
:param num_workers: The number of worker threads you want to do I/O,
                    This defaults to 10\&.
:param kwargs: Passed to the superclass\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._fetch ( self)\fC [protected]\fP"

.PP
.nf
Get a URL to fetch from the work queue, get the HTML page, examine its
links for download candidates and candidates for further scraping\&.

This is a handy method to run in a thread\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._get_project ( self,  name)\fC [protected]\fP"

.PP
.nf
For a given project, get a dictionary mapping available versions to Distribution
instances\&.

This should be implemented in subclasses\&.

If called from a locate() request, self\&.matcher will be set to a
matcher for the requirement to satisfy, otherwise it will be None\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP\&.
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._is_platform_dependent ( self,  url)\fC [protected]\fP"

.PP
.nf
Does an URL refer to a platform-specific download?

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._prepare_threads ( self)\fC [protected]\fP"

.PP
.nf
Threads are created only when get_project is called, and terminate
before it returns\&. They are there primarily to parallelise I/O (i\&.e\&.
fetching web pages)\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._process_download ( self,  url)\fC [protected]\fP"

.PP
.nf
See if an URL is a suitable download for a project\&.

If it is, register information in the result dictionary (for
_get_project) about the specific version it's for\&.

Note that the return value isn't actually used other than as a boolean
value\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._should_queue ( self,  link,  referrer,  rel)\fC [protected]\fP"

.PP
.nf
Determine whether a link URL from a referring page and with a
particular 'rel' attribute should be queued for scraping\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._wait_threads ( self)\fC [protected]\fP"

.PP
.nf
Tell all the threads to terminate (by sending a sentinel value) and
wait for them to do so\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.get_distribution_names ( self)"

.PP
.nf
Return all the distribution names known to this locator\&.

.fi
.PP
 
.PP
Reimplemented from \fBpip\&._vendor\&.distlib\&.locators\&.Locator\fP\&.
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.get_page ( self,  url)"

.PP
.nf
Get the HTML for an URL, possibly from an in-memory cache\&.

XXX TODO Note: this cache is never actually cleared\&. It's assumed that
the data won't get stale over the lifetime of a locator instance (not
necessarily true for the default_locator)\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._bad_hosts\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._distname_re = re\&.compile('<a href=[^>]*>([^<]+)<')\fC [static]\fP, \fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._gplock\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._lock\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._page_cache\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._seen\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._threads\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&._to_fetch\fC [protected]\fP"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.base_url"

.SS "dict pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.decoders\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  {
        'deflate': zlib\&.decompress,
        'gzip': lambda b: gzip\&.GzipFile(fileobj=BytesIO(b))\&.read(),
        'none': lambda b: b,
    }
.fi

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.excluded_extensions"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.num_workers"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.platform_check"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.platform_dependent\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  re\&.compile(r'\\b(linux_(i\\d86|x86_64|arm\\w+)|'
                                    r'win(32|_amd64)|macosx_?\\d+)\\b', re\&.I)
.fi

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.project_name"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.result"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.skip_externals"

.SS "pip\&._vendor\&.distlib\&.locators\&.SimpleScrapingLocator\&.timeout"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
