.TH "pip._vendor.rich.__main__" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.__main__
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColorBox\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTable\fP \fBmake_test_card\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconsole\fP"
.br
.ti -1c
.RI "\fBTable\fP \fBtest_card\fP = \fBmake_test_card\fP()"
.br
.ti -1c
.RI "\fBstart\fP = process_time()"
.br
.ti -1c
.RI "\fBpre_cache_taken\fP = round((process_time() \- \fBstart\fP) * 1000\&.0, 1)"
.br
.ti -1c
.RI "\fBfile\fP"
.br
.ti -1c
.RI "\fBtaken\fP = round((process_time() \- \fBstart\fP) * 1000\&.0, 1)"
.br
.ti -1c
.RI "\fBc\fP = \fBConsole\fP(record=True)"
.br
.ti -1c
.RI "\fBsponsor_message\fP = \fBTable\&.grid\fP(padding=1)"
.br
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBjustify\fP"
.br
.ti -1c
.RI "\fBno_wrap\fP"
.br
.ti -1c
.RI "\fBintro_message\fP"
.br
.ti -1c
.RI "\fBmessage\fP = \fBTable\&.grid\fP(padding=2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " \fBTable\fP pip\&._vendor\&.rich\&.__main__\&.make_test_card ()"

.PP
.nf
Get a renderable that demonstrates a number of features\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.__main__\&.c = \fBConsole\fP(record=True)"

.SS "pip\&._vendor\&.rich\&.__main__\&.console"
\fBInitial value:\fP.PP
.nf
1 =  Console(
2         file=io\&.StringIO(),
3         force_terminal=True,
4     )
.fi

.SS "pip\&._vendor\&.rich\&.__main__\&.file"

.SS "pip\&._vendor\&.rich\&.__main__\&.intro_message"
\fBInitial value:\fP.PP
.nf
1 =  Text\&.from_markup(
2         
3     )
.fi

.SS "pip\&._vendor\&.rich\&.__main__\&.justify"

.SS "pip\&._vendor\&.rich\&.__main__\&.message = \fBTable\&.grid\fP(padding=2)"

.SS "pip\&._vendor\&.rich\&.__main__\&.no_wrap"

.SS "pip\&._vendor\&.rich\&.__main__\&.pre_cache_taken = round((process_time() \- \fBstart\fP) * 1000\&.0, 1)"

.SS "pip\&._vendor\&.rich\&.__main__\&.sponsor_message = \fBTable\&.grid\fP(padding=1)"

.SS "pip\&._vendor\&.rich\&.__main__\&.start = process_time()"

.SS "pip\&._vendor\&.rich\&.__main__\&.style"

.SS "pip\&._vendor\&.rich\&.__main__\&.taken = round((process_time() \- \fBstart\fP) * 1000\&.0, 1)"

.SS "\fBTable\fP pip\&._vendor\&.rich\&.__main__\&.test_card = \fBmake_test_card\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
