.TH "pip._internal.req.req_file.RequirementsFileParser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.req.req_file.RequirementsFileParser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, 'PipSession' session, \fBLineParser\fP line_parser)"
.br
.ti -1c
.RI "Generator[\fBParsedLine\fP, None, None] \fBparse\fP (self, str filename, bool constraint)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Generator[\fBParsedLine\fP, None, None] \fB_parse_and_recurse\fP (self, str filename, bool constraint, List[Dict[str, Optional[str]]] parsed_files_stack)"
.br
.ti -1c
.RI "Generator[\fBParsedLine\fP, None, None] \fB_parse_file\fP (self, str filename, bool constraint)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_session\fP"
.br
.ti -1c
.RI "\fB_line_parser\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._internal\&.req\&.req_file\&.RequirementsFileParser\&.__init__ ( self, 'PipSession' session, \fBLineParser\fP line_parser)"

.SH "Member Function Documentation"
.PP 
.SS " Generator[\fBParsedLine\fP, None, None] pip\&._internal\&.req\&.req_file\&.RequirementsFileParser\&._parse_and_recurse ( self, str filename, bool constraint, List[Dict[str, Optional[str]]] parsed_files_stack)\fC [protected]\fP"

.SS " Generator[\fBParsedLine\fP, None, None] pip\&._internal\&.req\&.req_file\&.RequirementsFileParser\&._parse_file ( self, str filename, bool
     constraint)\fC [protected]\fP"

.SS " Generator[\fBParsedLine\fP, None, None] pip\&._internal\&.req\&.req_file\&.RequirementsFileParser\&.parse ( self, str filename, bool
     constraint)"

.PP
.nf
Parse a given file, yielding parsed lines\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.req\&.req_file\&.RequirementsFileParser\&._line_parser\fC [protected]\fP"

.SS "pip\&._internal\&.req\&.req_file\&.RequirementsFileParser\&._session\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
