.TH "pip._vendor.platformdirs.api.PlatformDirsABC" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.platformdirs.api.PlatformDirsABC
.SH SYNOPSIS
.br
.PP
.PP
Inherits ABC\&.
.PP
Inherited by \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str|None \fBappname\fP=None, str|None|Literal[False] \fBappauthor\fP=None, str|None \fBversion\fP=None, bool \fBroaming\fP=False, bool \fBmultipath\fP=False, bool \fBopinion\fP=True, bool \fBensure_exists\fP=False)"
.br
.ti -1c
.RI "str \fBuser_data_dir\fP (self)"
.br
.ti -1c
.RI "str \fBsite_data_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_config_dir\fP (self)"
.br
.ti -1c
.RI "str \fBsite_config_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_cache_dir\fP (self)"
.br
.ti -1c
.RI "str \fBsite_cache_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_state_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_log_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_documents_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_downloads_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_pictures_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_videos_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_music_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_desktop_dir\fP (self)"
.br
.ti -1c
.RI "str \fBuser_runtime_dir\fP (self)"
.br
.ti -1c
.RI "str \fBsite_runtime_dir\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_data_path\fP (self)"
.br
.ti -1c
.RI "Path \fBsite_data_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_config_path\fP (self)"
.br
.ti -1c
.RI "Path \fBsite_config_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_cache_path\fP (self)"
.br
.ti -1c
.RI "Path \fBsite_cache_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_state_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_log_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_documents_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_downloads_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_pictures_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_videos_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_music_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_desktop_path\fP (self)"
.br
.ti -1c
.RI "Path \fBuser_runtime_path\fP (self)"
.br
.ti -1c
.RI "Path \fBsite_runtime_path\fP (self)"
.br
.ti -1c
.RI "Iterator[str] \fBiter_config_dirs\fP (self)"
.br
.ti -1c
.RI "Iterator[str] \fBiter_data_dirs\fP (self)"
.br
.ti -1c
.RI "Iterator[str] \fBiter_cache_dirs\fP (self)"
.br
.ti -1c
.RI "Iterator[str] \fBiter_runtime_dirs\fP (self)"
.br
.ti -1c
.RI "Iterator[Path] \fBiter_config_paths\fP (self)"
.br
.ti -1c
.RI "Iterator[Path] \fBiter_data_paths\fP (self)"
.br
.ti -1c
.RI "Iterator[Path] \fBiter_cache_paths\fP (self)"
.br
.ti -1c
.RI "Iterator[Path] \fBiter_runtime_paths\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBappname\fP"
.br
.ti -1c
.RI "\fBappauthor\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBroaming\fP"
.br
.ti -1c
.RI "\fBmultipath\fP"
.br
.ti -1c
.RI "\fBopinion\fP"
.br
.ti -1c
.RI "\fBensure_exists\fP"
.br
.ti -1c
.RI "\fBuser_data_dir\fP"
.br
.ti -1c
.RI "\fBsite_data_dir\fP"
.br
.ti -1c
.RI "\fBuser_config_dir\fP"
.br
.ti -1c
.RI "\fBsite_config_dir\fP"
.br
.ti -1c
.RI "\fBuser_cache_dir\fP"
.br
.ti -1c
.RI "\fBsite_cache_dir\fP"
.br
.ti -1c
.RI "\fBuser_state_dir\fP"
.br
.ti -1c
.RI "\fBuser_log_dir\fP"
.br
.ti -1c
.RI "\fBuser_documents_dir\fP"
.br
.ti -1c
.RI "\fBuser_downloads_dir\fP"
.br
.ti -1c
.RI "\fBuser_pictures_dir\fP"
.br
.ti -1c
.RI "\fBuser_videos_dir\fP"
.br
.ti -1c
.RI "\fBuser_music_dir\fP"
.br
.ti -1c
.RI "\fBuser_desktop_dir\fP"
.br
.ti -1c
.RI "\fBuser_runtime_dir\fP"
.br
.ti -1c
.RI "\fBsite_runtime_dir\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_append_app_name_and_version\fP (self, *str base)"
.br
.ti -1c
.RI "None \fB_optionally_create_directory\fP (self, str path)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Abstract base class for platform directories\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.__init__ ( self, str | None  appname = \fCNone\fP, str | None | Literal[False]  appauthor = \fCNone\fP, str | None  version = \fCNone\fP, bool  roaming = \fCFalse\fP, bool  multipath = \fCFalse\fP, bool  opinion = \fCTrue\fP, bool  ensure_exists = \fCFalse\fP)"

.PP
.nf
Create a new platform directory\&.

:param appname: See `appname`\&.
:param appauthor: See `appauthor`\&.
:param version: See `version`\&.
:param roaming: See `roaming`\&.
:param multipath: See `multipath`\&.
:param opinion: See `opinion`\&.
:param ensure_exists: See `ensure_exists`\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&._append_app_name_and_version ( self, *str base)\fC [protected]\fP"

.SS " None pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&._optionally_create_directory ( self, str path)\fC [protected]\fP"

.SS " Iterator[str] pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.iter_cache_dirs ( self)"

.PP
.nf
:yield: all user and site cache directories\&.
.fi
.PP
 
.SS " Iterator[Path] pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.iter_cache_paths ( self)"

.PP
.nf
:yield: all user and site cache paths\&.
.fi
.PP
 
.SS " Iterator[str] pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.iter_config_dirs ( self)"

.PP
.nf
:yield: all user and site configuration directories\&.
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP\&.
.SS " Iterator[Path] pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.iter_config_paths ( self)"

.PP
.nf
:yield: all user and site configuration paths\&.
.fi
.PP
 
.SS " Iterator[str] pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.iter_data_dirs ( self)"

.PP
.nf
:yield: all user and site data directories\&.
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP\&.
.SS " Iterator[Path] pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.iter_data_paths ( self)"

.PP
.nf
:yield: all user and site data paths\&.
.fi
.PP
 
.SS " Iterator[str] pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.iter_runtime_dirs ( self)"

.PP
.nf
:yield: all user and site runtime directories\&.
.fi
.PP
 
.SS " Iterator[Path] pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.iter_runtime_paths ( self)"

.PP
.nf
:yield: all user and site runtime paths\&.
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_cache_dir ( self)"

.PP
.nf
:return: cache directory shared by users
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_cache_path ( self)"

.PP
.nf
:return: cache path shared by users
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP\&.
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_config_dir ( self)"

.PP
.nf
:return: config directory shared by the users
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_config_path ( self)"

.PP
.nf
:return: config path shared by the users
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP\&.
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_data_dir ( self)"

.PP
.nf
:return: data directory shared by users
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_data_path ( self)"

.PP
.nf
:return: data path shared by users
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP\&.
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_runtime_dir ( self)"

.PP
.nf
:return: runtime directory shared by users
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_runtime_path ( self)"

.PP
.nf
:return: runtime path shared by users
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_cache_dir ( self)"

.PP
.nf
:return: cache directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_cache_path ( self)"

.PP
.nf
:return: cache path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_config_dir ( self)"

.PP
.nf
:return: config directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_config_path ( self)"

.PP
.nf
:return: config path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_data_dir ( self)"

.PP
.nf
:return: data directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_data_path ( self)"

.PP
.nf
:return: data path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_desktop_dir ( self)"

.PP
.nf
:return: desktop directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_desktop_path ( self)"

.PP
.nf
:return: desktop path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_documents_dir ( self)"

.PP
.nf
:return: documents directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_documents_path ( self)"

.PP
.nf
:return: documents a path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_downloads_dir ( self)"

.PP
.nf
:return: downloads directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_downloads_path ( self)"

.PP
.nf
:return: downloads path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_log_dir ( self)"

.PP
.nf
:return: log directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_log_path ( self)"

.PP
.nf
:return: log path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_music_dir ( self)"

.PP
.nf
:return: music directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_music_path ( self)"

.PP
.nf
:return: music path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_pictures_dir ( self)"

.PP
.nf
:return: pictures directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_pictures_path ( self)"

.PP
.nf
:return: pictures path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_runtime_dir ( self)"

.PP
.nf
:return: runtime directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_runtime_path ( self)"

.PP
.nf
:return: runtime path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_state_dir ( self)"

.PP
.nf
:return: state directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_state_path ( self)"

.PP
.nf
:return: state path tied to the user
.fi
.PP
 
.SS " str pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_videos_dir ( self)"

.PP
.nf
:return: videos directory tied to the user
.fi
.PP
 
.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS " Path pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_videos_path ( self)"

.PP
.nf
:return: videos path tied to the user
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.appauthor"

.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.appname"

.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.ensure_exists"

.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.multipath"

.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.opinion"

.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.roaming"

.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_cache_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_config_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_data_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.site_runtime_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_cache_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_config_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_data_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_desktop_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_documents_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_downloads_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_log_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_music_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_pictures_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_runtime_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_state_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.user_videos_dir"

.PP
Reimplemented in \fBpip\&._vendor\&.platformdirs\&.android\&.Android\fP, \fBpip\&._vendor\&.platformdirs\&.macos\&.MacOS\fP, \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP, and \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP\&.
.SS "pip\&._vendor\&.platformdirs\&.api\&.PlatformDirsABC\&.version"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
