.TH "pip._vendor.distlib.index.PackageIndex" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.distlib.index.PackageIndex
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBurl\fP=None)"
.br
.ti -1c
.RI "\fBread_configuration\fP (self)"
.br
.ti -1c
.RI "\fBsave_configuration\fP (self)"
.br
.ti -1c
.RI "\fBcheck_credentials\fP (self)"
.br
.ti -1c
.RI "\fBregister\fP (self, metadata)"
.br
.ti -1c
.RI "\fBget_sign_command\fP (self, filename, signer, sign_password, keystore=None)"
.br
.ti -1c
.RI "\fBrun_command\fP (self, cmd, input_data=None)"
.br
.ti -1c
.RI "\fBsign_file\fP (self, filename, signer, sign_password, keystore=None)"
.br
.ti -1c
.RI "\fBupload_file\fP (self, metadata, filename, signer=None, sign_password=None, filetype='sdist', pyversion='source', keystore=None)"
.br
.ti -1c
.RI "\fBupload_documentation\fP (self, metadata, doc_dir)"
.br
.ti -1c
.RI "\fBget_verify_command\fP (self, signature_filename, data_filename, keystore=None)"
.br
.ti -1c
.RI "\fBverify_signature\fP (self, signature_filename, data_filename, keystore=None)"
.br
.ti -1c
.RI "\fBdownload_file\fP (self, \fBurl\fP, destfile, digest=None, reporthook=None)"
.br
.ti -1c
.RI "\fBsend_request\fP (self, req)"
.br
.ti -1c
.RI "\fBencode_request\fP (self, fields, files)"
.br
.ti -1c
.RI "\fBsearch\fP (self, terms, operator=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBpassword_handler\fP"
.br
.ti -1c
.RI "\fBssl_verifier\fP"
.br
.ti -1c
.RI "\fBgpg\fP"
.br
.ti -1c
.RI "\fBgpg_home\fP"
.br
.ti -1c
.RI "\fBusername\fP"
.br
.ti -1c
.RI "\fBpassword\fP"
.br
.ti -1c
.RI "\fBrealm\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBboundary\fP = b'\-\-\-\-\-\-\-\-\-\-ThIs_Is_tHe_distlib_index_bouNdaRY_$'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_get_pypirc_command\fP (self)"
.br
.ti -1c
.RI "\fB_reader\fP (self, name, stream, outbuf)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class represents a package index compatible with PyPI, the Python
Package Index\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.__init__ ( self,  url = \fCNone\fP)"

.PP
.nf
Initialise an instance\&.

:param url: The URL of the index\&. If not specified, the URL for PyPI is
            used\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&._get_pypirc_command ( self)\fC [protected]\fP"

.PP
.nf
Get the distutils command for interacting with PyPI configurations\&.
:return: the command\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&._reader ( self,  name,  stream,  outbuf)\fC [protected]\fP"

.PP
.nf
Thread runner for reading lines of from a subprocess into a buffer\&.

:param name: The logical name of the stream (used for logging only)\&.
:param stream: The stream to read from\&. This will typically a pipe
               connected to the output stream of a subprocess\&.
:param outbuf: The list to append the read lines to\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.check_credentials ( self)"

.PP
.nf
Check that ``username`` and ``password`` have been set, and raise an
exception if not\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.download_file ( self,  url,  destfile,  digest = \fCNone\fP,  reporthook = \fCNone\fP)"

.PP
.nf
This is a convenience method for downloading a file from an URL\&.
Normally, this will be a file from the index, though currently
no check is made for this (i\&.e\&. a file can be downloaded from
anywhere)\&.

The method is just like the :func:`urlretrieve` function in the
standard library, except that it allows digest computation to be
done during download and checking that the downloaded data
matched any expected value\&.

:param url: The URL of the file to be downloaded (assumed to be
            available via an HTTP GET request)\&.
:param destfile: The pathname where the downloaded file is to be
                 saved\&.
:param digest: If specified, this must be a (hasher, value)
               tuple, where hasher is the algorithm used (e\&.g\&.
               ``'md5'``) and ``value`` is the expected value\&.
:param reporthook: The same as for :func:`urlretrieve` in the
                   standard library\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.encode_request ( self,  fields,  files)"

.PP
.nf
Encode fields and files for posting to an HTTP server\&.

:param fields: The fields to send as a list of (fieldname, value)
               tuples\&.
:param files: The files to send as a list of (fieldname, filename,
              file_bytes) tuple\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.get_sign_command ( self,  filename,  signer,  sign_password,  keystore = \fCNone\fP)"

.PP
.nf
Return a suitable command for signing a file\&.

:param filename: The pathname to the file to be signed\&.
:param signer: The identifier of the signer of the file\&.
:param sign_password: The passphrase for the signer's
                      private key used for signing\&.
:param keystore: The path to a directory which contains the keys
                 used in verification\&. If not specified, the
                 instance's ``gpg_home`` attribute is used instead\&.
:return: The signing command as a list suitable to be
         passed to :class:`subprocess\&.Popen`\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.get_verify_command ( self,  signature_filename,  data_filename,  keystore = \fCNone\fP)"

.PP
.nf
Return a suitable command for verifying a file\&.

:param signature_filename: The pathname to the file containing the
                           signature\&.
:param data_filename: The pathname to the file containing the
                      signed data\&.
:param keystore: The path to a directory which contains the keys
                 used in verification\&. If not specified, the
                 instance's ``gpg_home`` attribute is used instead\&.
:return: The verifying command as a list suitable to be
         passed to :class:`subprocess\&.Popen`\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.read_configuration ( self)"

.PP
.nf
Read the PyPI access configuration as supported by distutils\&. This populates
``username``, ``password``, ``realm`` and ``url`` attributes from the
configuration\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.register ( self,  metadata)"

.PP
.nf
Register a distribution on PyPI, using the provided metadata\&.

:param metadata: A :class:`Metadata` instance defining at least a name
                 and version number for the distribution to be
                 registered\&.
:return: The HTTP response received from PyPI upon submission of the
        request\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.run_command ( self,  cmd,  input_data = \fCNone\fP)"

.PP
.nf
Run a command in a child process , passing it any input data specified\&.

:param cmd: The command to run\&.
:param input_data: If specified, this must be a byte string containing
                   data to be sent to the child process\&.
:return: A tuple consisting of the subprocess' exit code, a list of
         lines read from the subprocess' ``stdout``, and a list of
         lines read from the subprocess' ``stderr``\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.save_configuration ( self)"

.PP
.nf
Save the PyPI access configuration\&. You must have set ``username`` and
``password`` attributes before calling this method\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.search ( self,  terms,  operator = \fCNone\fP)"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.send_request ( self,  req)"

.PP
.nf
Send a standard library :class:`Request` to PyPI and return its
response\&.

:param req: The request to send\&.
:return: The HTTP response from PyPI (a standard library HTTPResponse)\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.sign_file ( self,  filename,  signer,  sign_password,  keystore = \fCNone\fP)"

.PP
.nf
Sign a file\&.

:param filename: The pathname to the file to be signed\&.
:param signer: The identifier of the signer of the file\&.
:param sign_password: The passphrase for the signer's
                      private key used for signing\&.
:param keystore: The path to a directory which contains the keys
                 used in signing\&. If not specified, the instance's
                 ``gpg_home`` attribute is used instead\&.
:return: The absolute pathname of the file where the signature is
         stored\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.upload_documentation ( self,  metadata,  doc_dir)"

.PP
.nf
Upload documentation to the index\&.

:param metadata: A :class:`Metadata` instance defining at least a name
                 and version number for the documentation to be
                 uploaded\&.
:param doc_dir: The pathname of the directory which contains the
                documentation\&. This should be the directory that
                contains the ``index\&.html`` for the documentation\&.
:return: The HTTP response received from PyPI upon submission of the
        request\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.upload_file ( self,  metadata,  filename,  signer = \fCNone\fP,  sign_password = \fCNone\fP,  filetype = \fC'sdist'\fP,  pyversion = \fC'source'\fP,  keystore = \fCNone\fP)"

.PP
.nf
Upload a release file to the index\&.

:param metadata: A :class:`Metadata` instance defining at least a name
                 and version number for the file to be uploaded\&.
:param filename: The pathname of the file to be uploaded\&.
:param signer: The identifier of the signer of the file\&.
:param sign_password: The passphrase for the signer's
                      private key used for signing\&.
:param filetype: The type of the file being uploaded\&. This is the
                distutils command which produced that file, e\&.g\&.
                ``sdist`` or ``bdist_wheel``\&.
:param pyversion: The version of Python which the release relates
                  to\&. For code compatible with any Python, this would
                  be ``source``, otherwise it would be e\&.g\&. ``3\&.2``\&.
:param keystore: The path to a directory which contains the keys
                 used in signing\&. If not specified, the instance's
                 ``gpg_home`` attribute is used instead\&.
:return: The HTTP response received from PyPI upon submission of the
        request\&.

.fi
.PP
 
.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.verify_signature ( self,  signature_filename,  data_filename,  keystore = \fCNone\fP)"

.PP
.nf
Verify a signature for a file\&.

:param signature_filename: The pathname to the file containing the
                           signature\&.
:param data_filename: The pathname to the file containing the
                      signed data\&.
:param keystore: The path to a directory which contains the keys
                 used in verification\&. If not specified, the
                 instance's ``gpg_home`` attribute is used instead\&.
:return: True if the signature was verified, else False\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "str pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.boundary = b'\-\-\-\-\-\-\-\-\-\-ThIs_Is_tHe_distlib_index_bouNdaRY_$'\fC [static]\fP"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.gpg"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.gpg_home"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.password"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.password_handler"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.realm"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.ssl_verifier"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.url"

.SS "pip\&._vendor\&.distlib\&.index\&.PackageIndex\&.username"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
