.TH "pip._vendor.pyproject_hooks._in_process._in_process.HookMissing" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.pyproject_hooks._in_process._in_process.HookMissing
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBhook_name\fP=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhook_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raised if a hook is missing and we are not executing the fallback
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.HookMissing\&.__init__ ( self,  hook_name = \fCNone\fP)"

.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.pyproject_hooks\&._in_process\&._in_process\&.HookMissing\&.hook_name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
