.TH "pip._vendor.rich.panel.Panel" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.panel.Panel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, 'RenderableType' \fBrenderable\fP, \fBBox\fP \fBbox\fP=ROUNDED, *Optional[TextType] \fBtitle\fP=None, AlignMethod \fBtitle_align\fP='center', Optional[TextType] \fBsubtitle\fP=None, AlignMethod \fBsubtitle_align\fP='center', Optional[bool] \fBsafe_box\fP=None, bool \fBexpand\fP=True, StyleType \fBstyle\fP='none', StyleType \fBborder_style\fP='none', Optional[int] \fBwidth\fP=None, Optional[int] \fBheight\fP=None, PaddingDimensions \fBpadding\fP=(0, 1), bool \fBhighlight\fP=False)"
.br
.ti -1c
.RI "'Panel' \fBfit\fP (cls, 'RenderableType' \fBrenderable\fP, \fBBox\fP \fBbox\fP=ROUNDED, *Optional[TextType] \fBtitle\fP=None, AlignMethod \fBtitle_align\fP='center', Optional[TextType] \fBsubtitle\fP=None, AlignMethod \fBsubtitle_align\fP='center', Optional[bool] \fBsafe_box\fP=None, StyleType \fBstyle\fP='none', StyleType \fBborder_style\fP='none', Optional[int] \fBwidth\fP=None, Optional[int] \fBheight\fP=None, PaddingDimensions \fBpadding\fP=(0, 1), bool \fBhighlight\fP=False)"
.br
.ti -1c
.RI "'RenderResult' \fB__rich_console__\fP (self, 'Console' console, 'ConsoleOptions' options)"
.br
.ti -1c
.RI "'Measurement' \fB__rich_measure__\fP (self, 'Console' console, 'ConsoleOptions' options)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrenderable\fP"
.br
.ti -1c
.RI "\fBbox\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBsubtitle\fP"
.br
.ti -1c
.RI "\fBsubtitle_align\fP"
.br
.ti -1c
.RI "\fBsafe_box\fP"
.br
.ti -1c
.RI "\fBexpand\fP"
.br
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBborder_style\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.ti -1c
.RI "\fBheight\fP"
.br
.ti -1c
.RI "\fBpadding\fP"
.br
.ti -1c
.RI "\fBhighlight\fP"
.br
.ti -1c
.RI "\fBtitle_align\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Optional[\fBText\fP] \fB_title\fP (self)"
.br
.ti -1c
.RI "Optional[\fBText\fP] \fB_subtitle\fP (self)"
.br
.in -1c

Protected Member Functions inherited from \fBpip\&._vendor\&.rich\&.jupyter\&.JupyterMixin\fP
.in +1c
.ti -1c
.RI "Dict[str, str] \fB_repr_mimebundle_\fP ('ConsoleRenderable' self, Sequence[str] include, Sequence[str] exclude, **Any kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A console renderable that draws a border around its contents\&.

Example:
    >>> console\&.print(Panel('Hello, World!'))

Args:
    renderable (RenderableType): A console renderable object\&.
    box (Box, optional): A Box instance that defines the look of the border (see :ref:`appendix_box`\&.
        Defaults to box\&.ROUNDED\&.
    safe_box (bool, optional): Disable box characters that don't display on windows legacy terminal with *raster* fonts\&. Defaults to True\&.
    expand (bool, optional): If True the panel will stretch to fill the console
        width, otherwise it will be sized to fit the contents\&. Defaults to True\&.
    style (str, optional): The style of the panel (border and contents)\&. Defaults to 'none'\&.
    border_style (str, optional): The style of the border\&. Defaults to 'none'\&.
    width (Optional[int], optional): Optional width of panel\&. Defaults to None to auto-detect\&.
    height (Optional[int], optional): Optional height of panel\&. Defaults to None to auto-detect\&.
    padding (Optional[PaddingDimensions]): Optional padding around renderable\&. Defaults to 0\&.
    highlight (bool, optional): Enable automatic highlighting of panel title (if str)\&. Defaults to False\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.panel\&.Panel\&.__init__ ( self, 'RenderableType' renderable, \fBBox\fP  box = \fCROUNDED\fP, *Optional[TextType]  title = \fCNone\fP, AlignMethod  title_align = \fC'center'\fP, Optional[TextType]  subtitle = \fCNone\fP, AlignMethod  subtitle_align = \fC'center'\fP, Optional[bool]  safe_box = \fCNone\fP, bool  expand = \fCTrue\fP, StyleType  style = \fC'none'\fP, StyleType  border_style = \fC'none'\fP, Optional[int]  width = \fCNone\fP, Optional[int]  height = \fCNone\fP, PaddingDimensions  padding = \fC(0, 1)\fP, bool  highlight = \fCFalse\fP)"

.SH "Member Function Documentation"
.PP 
.SS " 'RenderResult' pip\&._vendor\&.rich\&.panel\&.Panel\&.__rich_console__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.SS " 'Measurement' pip\&._vendor\&.rich\&.panel\&.Panel\&.__rich_measure__ ( self, 'Console' console, 'ConsoleOptions'
     options)"

.SS " Optional[\fBText\fP] pip\&._vendor\&.rich\&.panel\&.Panel\&._subtitle ( self)\fC [protected]\fP"

.SS " Optional[\fBText\fP] pip\&._vendor\&.rich\&.panel\&.Panel\&._title ( self)\fC [protected]\fP"

.SS " 'Panel' pip\&._vendor\&.rich\&.panel\&.Panel\&.fit ( cls, 'RenderableType' renderable, \fBBox\fP  box = \fCROUNDED\fP, *Optional[TextType]  title = \fCNone\fP, AlignMethod  title_align = \fC'center'\fP, Optional[TextType]  subtitle = \fCNone\fP, AlignMethod  subtitle_align = \fC'center'\fP, Optional[bool]  safe_box = \fCNone\fP, StyleType  style = \fC'none'\fP, StyleType  border_style = \fC'none'\fP, Optional[int]  width = \fCNone\fP, Optional[int]  height = \fCNone\fP, PaddingDimensions  padding = \fC(0, 1)\fP, bool  highlight = \fCFalse\fP)"

.PP
.nf
An alternative constructor that sets expand=False\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.border_style"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.box"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.expand"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.height"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.highlight"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.padding"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.renderable"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.safe_box"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.style"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.subtitle"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.subtitle_align"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.title"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.title_align"

.SS "pip\&._vendor\&.rich\&.panel\&.Panel\&.width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
