.TH "pip._vendor.typing_extensions.SupportsAbs" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.typing_extensions.SupportsAbs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpip\&._vendor\&.typing_extensions\&.Protocol\fP, and T_co\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBT_co\fP \fB__abs__\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.typing_extensions\&.Protocol\fP
.in +1c
.ti -1c
.RI "\fB__init_subclass__\fP (cls, *args, **kwargs)"
.br
.in -1c

Public Member Functions inherited from \fBpip\&._vendor\&.typing_extensions\&._ProtocolMeta\fP
.in +1c
.ti -1c
.RI "\fB__new__\fP (mcls, name, bases, namespace, **kwargs)"
.br
.ti -1c
.RI "\fB__init__\fP (cls, *args, **kwargs)"
.br
.ti -1c
.RI "\fB__subclasscheck__\fP (cls, other)"
.br
.ti -1c
.RI "\fB__instancecheck__\fP (cls, instance)"
.br
.ti -1c
.RI "\fB__eq__\fP (cls, other)"
.br
.ti -1c
.RI "int \fB__hash__\fP (cls)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBpip\&._vendor\&.typing_extensions\&.Protocol\fP
.in +1c
.ti -1c
.RI "\fB_is_protocol\fP"
.br
.in -1c

Static Protected Attributes inherited from \fBpip\&._vendor\&.typing_extensions\&.Protocol\fP
.in +1c
.ti -1c
.RI "bool \fB_is_protocol\fP = True"
.br
.ti -1c
.RI "bool \fB_is_runtime_protocol\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An ABC with one abstract method __abs__ that is covariant in its return type\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " \fBT_co\fP pip\&._vendor\&.typing_extensions\&.SupportsAbs\&.__abs__ ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
