.TH "pip._vendor.rich.table" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._vendor.rich.table
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Cell\fP"
.br
.ti -1c
.RI "class \fBColumn\fP"
.br
.ti -1c
.RI "class \fBRow\fP"
.br
.ti -1c
.RI "class \fBTable\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBheader\fP (str text)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtable\fP"
.br
.ti -1c
.RI "\fBheader_style\fP"
.br
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBno_wrap\fP"
.br
.ti -1c
.RI "\fBjustify\fP"
.br
.ti -1c
.RI "\fBend_section\fP"
.br
.ti -1c
.RI "\fBconsole\fP = \fBConsole\fP()"
.br
.ti -1c
.RI "\fBhighlight\fP = \fBReprHighlighter\fP()"
.br
.ti -1c
.RI "\fBexpand\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.ti -1c
.RI "\fBrow_styles\fP"
.br
.ti -1c
.RI "\fBleading\fP"
.br
.ti -1c
.RI "\fBshow_lines\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " None pip\&._vendor\&.rich\&.table\&.header (str text)"

.SH "Variable Documentation"
.PP 
.SS "pip\&._vendor\&.rich\&.table\&.console = \fBConsole\fP()"

.SS "pip\&._vendor\&.rich\&.table\&.end_section"

.SS "pip\&._vendor\&.rich\&.table\&.expand"

.SS "pip\&._vendor\&.rich\&.table\&.header_style"

.SS "pip\&._vendor\&.rich\&.table\&.highlight = \fBReprHighlighter\fP()"

.SS "pip\&._vendor\&.rich\&.table\&.justify"

.SS "pip\&._vendor\&.rich\&.table\&.leading"

.SS "pip\&._vendor\&.rich\&.table\&.no_wrap"

.SS "pip\&._vendor\&.rich\&.table\&.row_styles"

.SS "pip\&._vendor\&.rich\&.table\&.show_lines"

.SS "pip\&._vendor\&.rich\&.table\&.style"

.SS "pip\&._vendor\&.rich\&.table\&.table"
\fBInitial value:\fP.PP
.nf
1 =  Table(
2             title="Star Wars Movies",
3             caption="Rich example table",
4             caption_justify="right",
5         )
.fi

.SS "pip\&._vendor\&.rich\&.table\&.width"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
