.TH "pip._internal.models.link.LinkHash" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip._internal.models.link.LinkHash
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__post_init__\fP (self)"
.br
.ti -1c
.RI "Optional['LinkHash'] \fBfind_hash_url_fragment\fP (cls, str url)"
.br
.ti -1c
.RI "Dict[str, str] \fBas_dict\fP (self)"
.br
.ti -1c
.RI "\fBHashes\fP \fBas_hashes\fP (self)"
.br
.ti -1c
.RI "bool \fBis_hash_allowed\fP (self, Optional[\fBHashes\fP] hashes)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP"
.br
.ti -1c
.RI "str \fBvalue\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_hash_url_fragment_re\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Links to content may have embedded hash values\&. This class parses those\&.

`name` must be any member of `_SUPPORTED_HASHES`\&.

This class can be converted to and from `ArchiveInfo`\&. While ArchiveInfo intends to
be JSON-serializable to conform to PEP 610, this class contains the logic for
parsing a hash name and value for correctness, and then checking whether that hash
conforms to a schema with `\&.is_hash_allowed()`\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " None pip\&._internal\&.models\&.link\&.LinkHash\&.__post_init__ ( self)"

.SS " Dict[str, str] pip\&._internal\&.models\&.link\&.LinkHash\&.as_dict ( self)"

.SS " \fBHashes\fP pip\&._internal\&.models\&.link\&.LinkHash\&.as_hashes ( self)"

.PP
.nf
Return a Hashes instance which checks only for the current hash\&.
.fi
.PP
 
.SS " Optional['LinkHash'] pip\&._internal\&.models\&.link\&.LinkHash\&.find_hash_url_fragment ( cls, str url)"

.PP
.nf
Search a string for a checksum algorithm name and encoded output value\&.
.fi
.PP
 
.SS " bool pip\&._internal\&.models\&.link\&.LinkHash\&.is_hash_allowed ( self, Optional[\fBHashes\fP] hashes)"

.PP
.nf
Return True if the current hash is allowed by `hashes`\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pip\&._internal\&.models\&.link\&.LinkHash\&._hash_url_fragment_re\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
=  re\&.compile(
        # NB: we do not validate that the second group (\&.*) is a valid hex
        # digest\&. Instead, we simply keep that string in this class, and then check it
        # against Hashes when hash\-checking is needed\&. This is easier to debug than
        # proactively discarding an invalid hex digest, as we handle incorrect hashes
        # and malformed hashes in the same place\&.
        r"[#&]({choices})=([^&]*)"\&.format(
            choices="|"\&.join(re\&.escape(hash_name) for hash_name in _SUPPORTED_HASHES)
        ),
    )
.fi

.SS "str pip\&._internal\&.models\&.link\&.LinkHash\&.name\fC [static]\fP"

.SS "pip\&._internal\&.models\&.link\&.LinkHash\&.name"

.SS "str pip\&._internal\&.models\&.link\&.LinkHash\&.value\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
