.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/waitress/proxy_headers.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/waitress/proxy_headers.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwaitress\&.proxy_headers\&.MalformedProxyHeader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwaitress\fP"
.br
.ti -1c
.RI "namespace \fBwaitress\&.proxy_headers\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwaitress\&.proxy_headers\&.proxy_headers_middleware\fP (app, trusted_proxy=None, trusted_proxy_count=1, trusted_proxy_headers=None, clear_untrusted=True, log_untrusted=False, logger=logger)"
.br
.ti -1c
.RI "\fBwaitress\&.proxy_headers\&.parse_proxy_headers\fP (environ, trusted_proxy_count, trusted_proxy_headers, logger=logger)"
.br
.ti -1c
.RI "\fBwaitress\&.proxy_headers\&.strip_brackets\fP (addr)"
.br
.ti -1c
.RI "\fBwaitress\&.proxy_headers\&.clear_untrusted_headers\fP (environ, untrusted_headers, log_warning=False, logger=logger)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBwaitress\&.proxy_headers\&.PROXY_HEADERS\fP"
.br
.ti -1c
.RI "\fBwaitress\&.proxy_headers\&.Forwarded\fP = namedtuple('Forwarded', ['by', 'for_', 'host', 'proto'])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
