.TH "pygments.lexers._luau_builtins" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers._luau_builtins
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBLUAU_BUILTINS\fP"
.br
.ti -1c
.RI "dict \fBROBLOX_BUILTINS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&._luau_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Includes the builtins for Luau and Roblox\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict pygments\&.lexers\&._luau_builtins\&.LUAU_BUILTINS"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'bit32',
3     'buffer',
4     'coroutine',
5     'debug',
6     'math',
7     'os',
8     'string',
9     'table',
10     'utf8',
11 }
.fi

.SS "dict pygments\&.lexers\&._luau_builtins\&.ROBLOX_BUILTINS"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
