.TH "pygments.lexers.robotframework.VariableTokenizer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.robotframework.VariableTokenizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtokenize\fP (self, string, token)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_tokenize\fP (self, var, string, orig_token)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.lexers\&.robotframework\&.VariableTokenizer\&._tokenize ( self,  var,  string,  orig_token)\fC [protected]\fP"

.SS "pygments\&.lexers\&.robotframework\&.VariableTokenizer\&.tokenize ( self,  string,  token)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
