.TH "pygments.lexers.objective" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.objective
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogosLexer\fP"
.br
.ti -1c
.RI "class \fBObjectiveCLexer\fP"
.br
.ti -1c
.RI "class \fBObjectiveCppLexer\fP"
.br
.ti -1c
.RI "class \fBSwiftLexer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBobjective\fP (baselexer)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.objective
    ~~~~~~~~~~~~~~~~~~~~~~~~~

    Lexers for Objective-C family languages\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pygments\&.lexers\&.objective\&.objective ( baselexer)"

.PP
.nf
Generate a subclass of baselexer that accepts the Objective-C syntax
extensions\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
