.TH "pygments.formatters._automodule" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.formatters._automodule
.SH SYNOPSIS
.br
.PP
.PP
Inherits types\&.ModuleType\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__getattr__\fP (self, name)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Automatically import formatters\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.formatters\&._automodule\&.__getattr__ ( self,  name)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
