.TH "pygments.styles.paraiso_dark" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.styles.paraiso_dark
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParaisoDarkStyle\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBBACKGROUND\fP = '#2f1e2e'"
.br
.ti -1c
.RI "str \fBCURRENT_LINE\fP = '#41323f'"
.br
.ti -1c
.RI "str \fBSELECTION\fP = '#4f424c'"
.br
.ti -1c
.RI "str \fBFOREGROUND\fP = '#e7e9db'"
.br
.ti -1c
.RI "str \fBCOMMENT\fP = '#776e71'"
.br
.ti -1c
.RI "str \fBRED\fP = '#ef6155'"
.br
.ti -1c
.RI "str \fBORANGE\fP = '#f99b15'"
.br
.ti -1c
.RI "str \fBYELLOW\fP = '#fec418'"
.br
.ti -1c
.RI "str \fBGREEN\fP = '#48b685'"
.br
.ti -1c
.RI "str \fBAQUA\fP = '#5bc4bf'"
.br
.ti -1c
.RI "str \fBBLUE\fP = '#06b6ef'"
.br
.ti -1c
.RI "str \fBPURPLE\fP = '#815ba4'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.styles\&.paraiso_dark
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Paraíso (Dark) by Jan T\&. Sott

    Pygments template by Jan T\&. Sott (https://github\&.com/idleberg)
    Created with Base16 Builder by Chris Kempson
    (https://github\&.com/chriskempson/base16-builder)\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "str pygments\&.styles\&.paraiso_dark\&.AQUA = '#5bc4bf'"

.SS "str pygments\&.styles\&.paraiso_dark\&.BACKGROUND = '#2f1e2e'"

.SS "str pygments\&.styles\&.paraiso_dark\&.BLUE = '#06b6ef'"

.SS "str pygments\&.styles\&.paraiso_dark\&.COMMENT = '#776e71'"

.SS "str pygments\&.styles\&.paraiso_dark\&.CURRENT_LINE = '#41323f'"

.SS "str pygments\&.styles\&.paraiso_dark\&.FOREGROUND = '#e7e9db'"

.SS "str pygments\&.styles\&.paraiso_dark\&.GREEN = '#48b685'"

.SS "str pygments\&.styles\&.paraiso_dark\&.ORANGE = '#f99b15'"

.SS "str pygments\&.styles\&.paraiso_dark\&.PURPLE = '#815ba4'"

.SS "str pygments\&.styles\&.paraiso_dark\&.RED = '#ef6155'"

.SS "str pygments\&.styles\&.paraiso_dark\&.SELECTION = '#4f424c'"

.SS "str pygments\&.styles\&.paraiso_dark\&.YELLOW = '#fec418'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
