.TH "pygments.formatters.svg.SvgFormatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.formatters.svg.SvgFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.formatter\&.Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fBformat_unencoded\fP (self, tokensource, outfile)"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBget_style_defs\fP (self, arg='')"
.br
.ti -1c
.RI "\fBformat\fP (self, tokensource, outfile)"
.br
.ti -1c
.RI "\fB__class_getitem__\fP (cls, \fBname\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnowrap\fP"
.br
.ti -1c
.RI "\fBfontfamily\fP"
.br
.ti -1c
.RI "\fBfontsize\fP"
.br
.ti -1c
.RI "\fBxoffset\fP"
.br
.ti -1c
.RI "\fByoffset\fP"
.br
.ti -1c
.RI "\fBystep\fP"
.br
.ti -1c
.RI "\fBspacehack\fP"
.br
.ti -1c
.RI "\fBlinenos\fP"
.br
.ti -1c
.RI "\fBlinenostart\fP"
.br
.ti -1c
.RI "\fBlinenostep\fP"
.br
.ti -1c
.RI "\fBlinenowidth\fP"
.br
.in -1c

Public Attributes inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBfull\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'SVG'"
.br
.ti -1c
.RI "list \fBaliases\fP = ['svg']"
.br
.ti -1c
.RI "list \fBfilenames\fP = ['*\&.svg']"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBname\fP = None"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "list \fBfilenames\fP = []"
.br
.ti -1c
.RI "bool \fBunicodeoutput\fP = True"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_get_style\fP (self, tokentype)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_stylecache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Format tokens as an SVG graphics file\&.  This formatter is still experimental\&.
Each line of code is a ``<text>`` element with explicit ``x`` and ``y``
coordinates containing ``<tspan>`` elements with the individual token styles\&.

By default, this formatter outputs a full SVG document including doctype
declaration and the ``<svg>`` root element\&.

\&.\&. versionadded:: 0\&.9

Additional options accepted:

`nowrap`
    Don't wrap the SVG ``<text>`` elements in ``<svg><g>`` elements and
    don't add a XML declaration and a doctype\&.  If true, the `fontfamily`
    and `fontsize` options are ignored\&.  Defaults to ``False``\&.

`fontfamily`
    The value to give the wrapping ``<g>`` element's ``font-family``
    attribute, defaults to ``'monospace'``\&.

`fontsize`
    The value to give the wrapping ``<g>`` element's ``font-size``
    attribute, defaults to ``'14px'``\&.

`linenos`
    If ``True``, add line numbers (default: ``False``)\&.

`linenostart`
    The line number for the first line (default: ``1``)\&.

`linenostep`
    If set to a number n > 1, only every nth line number is printed\&.

`linenowidth`
    Maximum width devoted to line numbers (default: ``3*ystep``, sufficient
    for up to 4-digit line numbers\&. Increase width for longer code blocks)\&.

`xoffset`
    Starting offset in X direction, defaults to ``0``\&.

`yoffset`
    Starting offset in Y direction, defaults to the font size if it is given
    in pixels, or ``20`` else\&.  (This is necessary since text coordinates
    refer to the text baseline, not the top edge\&.)

`ystep`
    Offset to add to the Y coordinate for each subsequent line\&.  This should
    roughly be the text size plus 5\&.  It defaults to that value if the text
    size is given in pixels, or ``25`` else\&.

`spacehack`
    Convert spaces in the source to ``&#160;``, which are non-breaking
    spaces\&.  SVG provides the ``xml:space`` attribute to control how
    whitespace inside tags is handled, in theory, the ``preserve`` value
    could be used to keep all whitespace as-is\&.  However, many current SVG
    viewers don't obey that rule, so this option is provided as a workaround
    and defaults to ``True``\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.__init__ ( self, ** options)"

.PP
.nf
As with lexers, this constructor takes arbitrary optional arguments,
and if you override it, you should first process your own options, then
call the base class implementation\&.

.fi
.PP
 
.PP
Reimplemented from \fBpygments\&.formatter\&.Formatter\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&._get_style ( self,  tokentype)\fC [protected]\fP"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.format_unencoded ( self,  tokensource,  outfile)"

.PP
.nf
Format ``tokensource``, an iterable of ``(tokentype, tokenstring)``
tuples and write it into ``outfile``\&.

For our implementation we put all lines in their own 'line group'\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&._stylecache\fC [protected]\fP"

.SS "list pygments\&.formatters\&.svg\&.SvgFormatter\&.aliases = ['svg']\fC [static]\fP"

.SS "list pygments\&.formatters\&.svg\&.SvgFormatter\&.filenames = ['*\&.svg']\fC [static]\fP"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.fontfamily"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.fontsize"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.linenos"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.linenostart"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.linenostep"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.linenowidth"

.SS "str pygments\&.formatters\&.svg\&.SvgFormatter\&.name = 'SVG'\fC [static]\fP"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.nowrap"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.spacehack"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.xoffset"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.yoffset"

.SS "pygments\&.formatters\&.svg\&.SvgFormatter\&.ystep"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
