.TH "pygments.lexers._ada_builtins" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers._ada_builtins
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBKEYWORD_LIST\fP"
.br
.ti -1c
.RI "tuple \fBBUILTIN_LIST\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&._ada_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Ada builtins\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "tuple pygments\&.lexers\&._ada_builtins\&.BUILTIN_LIST"
\fBInitial value:\fP.PP
.nf
1 =  (
2     'Address',
3     'Byte',
4     'Boolean',
5     'Character',
6     'Controlled',
7     'Count',
8     'Cursor',
9     'Duration',
10     'File_Mode',
11     'File_Type',
12     'Float',
13     'Generator',
14     'Integer',
15     'Long_Float',
16     'Long_Integer',
17     'Long_Long_Float',
18     'Long_Long_Integer',
19     'Natural',
20     'Positive',
21     'Reference_Type',
22     'Short_Float',
23     'Short_Integer',
24     'Short_Short_Float',
25     'Short_Short_Integer',
26     'String',
27     'Wide_Character',
28     'Wide_String'
29 )
.fi

.SS "tuple pygments\&.lexers\&._ada_builtins\&.KEYWORD_LIST"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
