.TH "pygments.lexers._vbscript_builtins" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers._vbscript_builtins
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBKEYWORDS\fP"
.br
.ti -1c
.RI "list \fBBUILTIN_FUNCTIONS\fP"
.br
.ti -1c
.RI "list \fBBUILTIN_VARIABLES\fP"
.br
.ti -1c
.RI "list \fBOPERATORS\fP"
.br
.ti -1c
.RI "list \fBOPERATOR_WORDS\fP"
.br
.ti -1c
.RI "list \fBBUILTIN_CONSTANTS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&._vbscript_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    These are manually translated lists from
    http://www\&.indusoft\&.com/pdf/VBScript%20Reference\&.pdf\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list pygments\&.lexers\&._vbscript_builtins\&.BUILTIN_CONSTANTS"

.SS "list pygments\&.lexers\&._vbscript_builtins\&.BUILTIN_FUNCTIONS"

.SS "list pygments\&.lexers\&._vbscript_builtins\&.BUILTIN_VARIABLES"
\fBInitial value:\fP.PP
.nf
1 =  [
2     'Debug',
3     'Dictionary',
4     'Drive',
5     'Drives',
6     'Err',
7     'File',
8     'Files',
9     'FileSystemObject',
10     'Folder',
11     'Folders',
12     'Match',
13     'Matches',
14     'RegExp',
15     'Submatches',
16     'TextStream',
17 ]
.fi

.SS "list pygments\&.lexers\&._vbscript_builtins\&.KEYWORDS"

.SS "list pygments\&.lexers\&._vbscript_builtins\&.OPERATOR_WORDS"
\fBInitial value:\fP.PP
.nf
1 =  [
2     'mod',
3     'and',
4     'or',
5     'xor',
6     'eqv',
7     'imp',
8     'is',
9     'not',
10 ]
.fi

.SS "list pygments\&.lexers\&._vbscript_builtins\&.OPERATORS"
\fBInitial value:\fP.PP
.nf
1 =  [
2     '+',
3     '\-',
4     '*',
5     '/',
6     '\\\\',
7     '^',
8     '|',
9     '<',
10     '<=',
11     '>',
12     '>=',
13     '=',
14     '<>',
15     '&',
16     '$',
17 ]
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
