.TH "pygments.lexers.arrow" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.arrow
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArrowLexer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBTYPES\fP = r'\\b(int|bool|char)((?:\\[\\])*)(?=\\s+)'"
.br
.ti -1c
.RI "str \fBIDENT\fP = r'([a\-zA\-Z_][a\-zA\-Z0\-9_]*)'"
.br
.ti -1c
.RI "str \fBDECL\fP = \fBTYPES\fP + r'(\\s+)' + \fBIDENT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.arrow
    ~~~~~~~~~~~~~~~~~~~~~

    Lexer for Arrow\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "str pygments\&.lexers\&.arrow\&.DECL = \fBTYPES\fP + r'(\\s+)' + \fBIDENT\fP"

.SS "str pygments\&.lexers\&.arrow\&.IDENT = r'([a\-zA\-Z_][a\-zA\-Z0\-9_]*)'"

.SS "str pygments\&.lexers\&.arrow\&.TYPES = r'\\b(int|bool|char)((?:\\[\\])*)(?=\\s+)'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
