.TH "pygments.styles.borland.BorlandStyle" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.styles.borland.BorlandStyle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.style\&.Style\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'borland'"
.br
.ti -1c
.RI "dict \fBstyles\fP"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.style\&.Style\fP
.in +1c
.ti -1c
.RI "str \fBbackground_color\fP = '#ffffff'"
.br
.ti -1c
.RI "str \fBhighlight_color\fP = '#ffffcc'"
.br
.ti -1c
.RI "str \fBline_number_color\fP = 'inherit'"
.br
.ti -1c
.RI "str \fBline_number_background_color\fP = 'transparent'"
.br
.ti -1c
.RI "str \fBline_number_special_color\fP = '#000000'"
.br
.ti -1c
.RI "str \fBline_number_special_background_color\fP = '#ffffc0'"
.br
.ti -1c
.RI "dict \fBstyles\fP = {}"
.br
.ti -1c
.RI "str \fBname\fP = 'unnamed'"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "bool \fBweb_style_gallery_exclude\fP = False"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBpygments\&.style\&.StyleMeta\fP
.in +1c
.ti -1c
.RI "\fB__new__\fP (mcs, name, bases, dct)"
.br
.ti -1c
.RI "\fBstyle_for_token\fP (cls, token)"
.br
.ti -1c
.RI "\fBlist_styles\fP (cls)"
.br
.ti -1c
.RI "\fBstyles_token\fP (cls, ttype)"
.br
.ti -1c
.RI "\fB__iter__\fP (cls)"
.br
.ti -1c
.RI "\fB__len__\fP (cls)"
.br
.in -1c

Protected Attributes inherited from \fBpygments\&.style\&.StyleMeta\fP
.in +1c
.ti -1c
.RI "\fB_styles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Style similar to the style used in the borland IDEs\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "str pygments\&.styles\&.borland\&.BorlandStyle\&.name = 'borland'\fC [static]\fP"

.SS "dict pygments\&.styles\&.borland\&.BorlandStyle\&.styles\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  {
        Whitespace:             '#bbbbbb',

        Comment:                'italic #008800',
        Comment\&.Preproc:        'noitalic #008080',
        Comment\&.Special:        'noitalic bold',

        String:                 '#0000FF',
        String\&.Char:            '#800080',
        Number:                 '#0000FF',
        Keyword:                'bold #000080',
        Operator\&.Word:          'bold',
        Name\&.Tag:               'bold #000080',
        Name\&.Attribute:         '#FF0000',

        Generic\&.Heading:        '#999999',
        Generic\&.Subheading:     '#aaaaaa',
        Generic\&.Deleted:        'bg:#ffdddd #000000',
        Generic\&.Inserted:       'bg:#ddffdd #000000',
        Generic\&.Error:          '#aa0000',
        Generic\&.Emph:           'italic',
        Generic\&.Strong:         'bold',
        Generic\&.EmphStrong:     'bold italic',
        Generic\&.Prompt:         '#555555',
        Generic\&.Output:         '#888888',
        Generic\&.Traceback:      '#aa0000',

        Error:                  'bg:#e3d2d2 #a61717'
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
