.TH "pygments.formatters.other.NullFormatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.formatters.other.NullFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.formatter\&.Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat\fP (self, tokensource, outfile)"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fBget_style_defs\fP (self, arg='')"
.br
.ti -1c
.RI "\fB__class_getitem__\fP (cls, \fBname\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'Text only'"
.br
.ti -1c
.RI "list \fBaliases\fP = ['text', 'null']"
.br
.ti -1c
.RI "list \fBfilenames\fP = ['*\&.txt']"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBname\fP = None"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "list \fBfilenames\fP = []"
.br
.ti -1c
.RI "bool \fBunicodeoutput\fP = True"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBfull\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Output the text unchanged without any formatting\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.formatters\&.other\&.NullFormatter\&.format ( self,  tokensource,  outfile)"

.PP
.nf
This method must format the tokens from the `tokensource` iterable and
write the formatted version to the file object `outfile`\&.

Formatter options can control how exactly the tokens are converted\&.

.fi
.PP
 
.PP
Reimplemented from \fBpygments\&.formatter\&.Formatter\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "list pygments\&.formatters\&.other\&.NullFormatter\&.aliases = ['text', 'null']\fC [static]\fP"

.SS "list pygments\&.formatters\&.other\&.NullFormatter\&.filenames = ['*\&.txt']\fC [static]\fP"

.SS "str pygments\&.formatters\&.other\&.NullFormatter\&.name = 'Text only'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
