.TH "pygments.styles.gh_dark" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.styles.gh_dark
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGhDarkStyle\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBRED_2\fP = '#ffa198'"
.br
.ti -1c
.RI "str \fBRED_3\fP = '#ff7b72'"
.br
.ti -1c
.RI "str \fBRED_9\fP = '#490202'"
.br
.ti -1c
.RI "str \fBORANGE_2\fP = '#ffa657'"
.br
.ti -1c
.RI "str \fBORANGE_3\fP = '#f0883e'"
.br
.ti -1c
.RI "str \fBGREEN_1\fP = '#7ee787'"
.br
.ti -1c
.RI "str \fBGREEN_2\fP = '#56d364'"
.br
.ti -1c
.RI "str \fBGREEN_7\fP = '#0f5323'"
.br
.ti -1c
.RI "str \fBBLUE_1\fP = '#a5d6ff'"
.br
.ti -1c
.RI "str \fBBLUE_2\fP = '#79c0ff'"
.br
.ti -1c
.RI "str \fBPURPLE_2\fP = '#d2a8ff'"
.br
.ti -1c
.RI "str \fBGRAY_3\fP = '#8b949e'"
.br
.ti -1c
.RI "str \fBGRAY_4\fP = '#6e7681'"
.br
.ti -1c
.RI "str \fBFG_SUBTLE\fP = '#6e7681'"
.br
.ti -1c
.RI "str \fBFG_DEFAULT\fP = '#e6edf3'"
.br
.ti -1c
.RI "str \fBBG_DEFAULT\fP = '#0d1117'"
.br
.ti -1c
.RI "str \fBDANGER_FG\fP = '#f85149'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.styles\&.gh_dark
    ~~~~~~~~~~~~~~~~~~~~~~~

    Github's Dark-Colorscheme based theme for Pygments
    Colors extracted from https://github\&.com/primer/primitives

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "str pygments\&.styles\&.gh_dark\&.BG_DEFAULT = '#0d1117'"

.SS "str pygments\&.styles\&.gh_dark\&.BLUE_1 = '#a5d6ff'"

.SS "str pygments\&.styles\&.gh_dark\&.BLUE_2 = '#79c0ff'"

.SS "str pygments\&.styles\&.gh_dark\&.DANGER_FG = '#f85149'"

.SS "str pygments\&.styles\&.gh_dark\&.FG_DEFAULT = '#e6edf3'"

.SS "str pygments\&.styles\&.gh_dark\&.FG_SUBTLE = '#6e7681'"

.SS "str pygments\&.styles\&.gh_dark\&.GRAY_3 = '#8b949e'"

.SS "str pygments\&.styles\&.gh_dark\&.GRAY_4 = '#6e7681'"

.SS "str pygments\&.styles\&.gh_dark\&.GREEN_1 = '#7ee787'"

.SS "str pygments\&.styles\&.gh_dark\&.GREEN_2 = '#56d364'"

.SS "str pygments\&.styles\&.gh_dark\&.GREEN_7 = '#0f5323'"

.SS "str pygments\&.styles\&.gh_dark\&.ORANGE_2 = '#ffa657'"

.SS "str pygments\&.styles\&.gh_dark\&.ORANGE_3 = '#f0883e'"

.SS "str pygments\&.styles\&.gh_dark\&.PURPLE_2 = '#d2a8ff'"

.SS "str pygments\&.styles\&.gh_dark\&.RED_2 = '#ffa198'"

.SS "str pygments\&.styles\&.gh_dark\&.RED_3 = '#ff7b72'"

.SS "str pygments\&.styles\&.gh_dark\&.RED_9 = '#490202'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
