.TH "pygments.lexers.webidl" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.webidl
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWebIDLLexer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fB_builtin_types\fP"
.br
.ti -1c
.RI "str \fB_identifier\fP = r'_?[A\-Za\-z][a\-zA\-Z0\-9_\-]*'"
.br
.ti -1c
.RI "str \fB_keyword_suffix\fP = r'(?![\\w\-])'"
.br
.ti -1c
.RI "str \fB_string\fP = r''[^']*''"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.webidl
    ~~~~~~~~~~~~~~~~~~~~~~

    Lexers for Web IDL, including some extensions\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "tuple pygments\&.lexers\&.webidl\&._builtin_types\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  (
2     # primitive types
3     'byte', 'octet', 'boolean',
4     r'(?:unsigned\\s+)?(?:short|long(?:\\s+long)?)',
5     r'(?:unrestricted\\s+)?(?:float|double)',
6     # string types
7     'DOMString', 'ByteString', 'USVString',
8     # exception types
9     'Error', 'DOMException',
10     # typed array types
11     'Uint8Array', 'Uint16Array', 'Uint32Array', 'Uint8ClampedArray',
12     'Float32Array', 'Float64Array',
13     # buffer source types
14     'ArrayBuffer', 'DataView', 'Int8Array', 'Int16Array', 'Int32Array',
15     # other
16     'any', 'void', 'object', 'RegExp',
17 )
.fi

.SS "str pygments\&.lexers\&.webidl\&._identifier = r'_?[A\-Za\-z][a\-zA\-Z0\-9_\-]*'\fC [protected]\fP"

.SS "str pygments\&.lexers\&.webidl\&._keyword_suffix = r'(?![\\w\-])'\fC [protected]\fP"

.SS "str pygments\&.lexers\&.webidl\&._string = r''[^']*''\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
