.TH "pygments.lexers.scripting" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.scripting
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppleScriptLexer\fP"
.br
.ti -1c
.RI "class \fBChaiscriptLexer\fP"
.br
.ti -1c
.RI "class \fBEasytrieveLexer\fP"
.br
.ti -1c
.RI "class \fBHybrisLexer\fP"
.br
.ti -1c
.RI "class \fBJclLexer\fP"
.br
.ti -1c
.RI "class \fBLSLLexer\fP"
.br
.ti -1c
.RI "class \fBLuaLexer\fP"
.br
.ti -1c
.RI "class \fBLuauLexer\fP"
.br
.ti -1c
.RI "class \fBMiniScriptLexer\fP"
.br
.ti -1c
.RI "class \fBMOOCodeLexer\fP"
.br
.ti -1c
.RI "class \fBMoonScriptLexer\fP"
.br
.ti -1c
.RI "class \fBRexxLexer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBall_lua_builtins\fP ()"
.br
.ti -1c
.RI "\fB_luau_make_expression\fP (should_pop, _s)"
.br
.ti -1c
.RI "\fB_luau_make_expression_special\fP (should_pop)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.scripting
    ~~~~~~~~~~~~~~~~~~~~~~~~~

    Lexer for scripting and embedded languages\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pygments\&.lexers\&.scripting\&._luau_make_expression ( should_pop,  _s)\fC [protected]\fP"

.SS "pygments\&.lexers\&.scripting\&._luau_make_expression_special ( should_pop)\fC [protected]\fP"

.SS "pygments\&.lexers\&.scripting\&.all_lua_builtins ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
