.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/docutils/writers/odf_odt/pygmentsformatter.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/docutils/writers/odf_odt/pygmentsformatter.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdocutils\&.writers\&.odf_odt\&.pygmentsformatter\&.OdtPygmentsFormatter\fP"
.br
.ti -1c
.RI "class \fBdocutils\&.writers\&.odf_odt\&.pygmentsformatter\&.OdtPygmentsProgFormatter\fP"
.br
.ti -1c
.RI "class \fBdocutils\&.writers\&.odf_odt\&.pygmentsformatter\&.OdtPygmentsLaTeXFormatter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdocutils\fP"
.br
.ti -1c
.RI "namespace \fBdocutils\&.writers\fP"
.br
.ti -1c
.RI "namespace \fBdocutils\&.writers\&.odf_odt\fP"
.br
.ti -1c
.RI "namespace \fBdocutils\&.writers\&.odf_odt\&.pygmentsformatter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
