.TH "pygments.lexers.graphql" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.graphql
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphQLLexer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBOPERATION_TYPES\fP = ('query', 'mutation', 'subscription')"
.br
.ti -1c
.RI "tuple \fBBUILTIN_TYPES\fP = ('Int', 'Float', 'String', 'Boolean', 'ID')"
.br
.ti -1c
.RI "tuple \fBBOOLEAN_VALUES\fP = ('true', 'false', 'null')"
.br
.ti -1c
.RI "tuple \fBKEYWORDS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.graphql
    ~~~~~~~~~~~~~~~~~~~~~~~

    Lexer for GraphQL, an open-source data query and manipulation
    language for APIs\&.

    More information:
    https://graphql\&.org/

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "tuple pygments\&.lexers\&.graphql\&.BOOLEAN_VALUES = ('true', 'false', 'null')"

.SS "tuple pygments\&.lexers\&.graphql\&.BUILTIN_TYPES = ('Int', 'Float', 'String', 'Boolean', 'ID')"

.SS "tuple pygments\&.lexers\&.graphql\&.KEYWORDS"
\fBInitial value:\fP.PP
.nf
1 =  (
2     "type",
3     "schema",
4     "extend",
5     "enum",
6     "scalar",
7     "implements",
8     "interface",
9     "union",
10     "input",
11     "directive",
12     "QUERY",
13     "MUTATION",
14     "SUBSCRIPTION",
15     "FIELD",
16     "FRAGMENT_DEFINITION",
17     "FRAGMENT_SPREAD",
18     "INLINE_FRAGMENT",
19     "SCHEMA",
20     "SCALAR",
21     "OBJECT",
22     "FIELD_DEFINITION",
23     "ARGUMENT_DEFINITION",
24     "INTERFACE",
25     "UNION",
26     "ENUM",
27     "ENUM_VALUE",
28     "INPUT_OBJECT",
29     "INPUT_FIELD_DEFINITION",
30 )
.fi

.SS "tuple pygments\&.lexers\&.graphql\&.OPERATION_TYPES = ('query', 'mutation', 'subscription')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
