.TH "pygments.formatters.img.FontNotFound" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.formatters.img.FontNotFound
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 

.PP
.nf
When there are no usable fonts specified
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
