.TH "pygments.formatters.other.RawTokenFormatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.formatters.other.RawTokenFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.formatter\&.Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fBformat\fP (self, tokensource, outfile)"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBget_style_defs\fP (self, arg='')"
.br
.ti -1c
.RI "\fB__class_getitem__\fP (cls, \fBname\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBcompress\fP"
.br
.ti -1c
.RI "\fBerror_color\fP"
.br
.in -1c

Public Attributes inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBfull\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'Raw tokens'"
.br
.ti -1c
.RI "list \fBaliases\fP = ['raw', 'tokens']"
.br
.ti -1c
.RI "list \fBfilenames\fP = ['*\&.raw']"
.br
.ti -1c
.RI "bool \fBunicodeoutput\fP = False"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBname\fP = None"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "list \fBfilenames\fP = []"
.br
.ti -1c
.RI "bool \fBunicodeoutput\fP = True"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Format tokens as a raw representation for storing token streams\&.

The format is ``tokentype<TAB>repr(tokenstring)\\n``\&. The output can later
be converted to a token stream with the `RawTokenLexer`, described in the
:doc:`lexer list <lexers>`\&.

Only two options are accepted:

`compress`
    If set to ``'gz'`` or ``'bz2'``, compress the output with the given
    compression algorithm after encoding (default: ``''``)\&.
`error_color`
    If set to a color name, highlight error tokens using that color\&.  If
    set but with no value, defaults to ``'red'``\&.

    \&.\&. versionadded:: 0\&.11
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pygments\&.formatters\&.other\&.RawTokenFormatter\&.__init__ ( self, ** options)"

.PP
.nf
As with lexers, this constructor takes arbitrary optional arguments,
and if you override it, you should first process your own options, then
call the base class implementation\&.

.fi
.PP
 
.PP
Reimplemented from \fBpygments\&.formatter\&.Formatter\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.formatters\&.other\&.RawTokenFormatter\&.format ( self,  tokensource,  outfile)"

.PP
.nf
This method must format the tokens from the `tokensource` iterable and
write the formatted version to the file object `outfile`\&.

Formatter options can control how exactly the tokens are converted\&.

.fi
.PP
 
.PP
Reimplemented from \fBpygments\&.formatter\&.Formatter\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "list pygments\&.formatters\&.other\&.RawTokenFormatter\&.aliases = ['raw', 'tokens']\fC [static]\fP"

.SS "pygments\&.formatters\&.other\&.RawTokenFormatter\&.compress"

.SS "pygments\&.formatters\&.other\&.RawTokenFormatter\&.encoding"

.SS "pygments\&.formatters\&.other\&.RawTokenFormatter\&.error_color"

.SS "list pygments\&.formatters\&.other\&.RawTokenFormatter\&.filenames = ['*\&.raw']\fC [static]\fP"

.SS "str pygments\&.formatters\&.other\&.RawTokenFormatter\&.name = 'Raw tokens'\fC [static]\fP"

.SS "bool pygments\&.formatters\&.other\&.RawTokenFormatter\&.unicodeoutput = False\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
