.TH "pygments.styles.paraiso_light" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.styles.paraiso_light
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParaisoLightStyle\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBBACKGROUND\fP = '#e7e9db'"
.br
.ti -1c
.RI "str \fBCURRENT_LINE\fP = '#b9b6b0'"
.br
.ti -1c
.RI "str \fBSELECTION\fP = '#a39e9b'"
.br
.ti -1c
.RI "str \fBFOREGROUND\fP = '#2f1e2e'"
.br
.ti -1c
.RI "str \fBCOMMENT\fP = '#8d8687'"
.br
.ti -1c
.RI "str \fBRED\fP = '#ef6155'"
.br
.ti -1c
.RI "str \fBORANGE\fP = '#f99b15'"
.br
.ti -1c
.RI "str \fBYELLOW\fP = '#fec418'"
.br
.ti -1c
.RI "str \fBGREEN\fP = '#48b685'"
.br
.ti -1c
.RI "str \fBAQUA\fP = '#5bc4bf'"
.br
.ti -1c
.RI "str \fBBLUE\fP = '#06b6ef'"
.br
.ti -1c
.RI "str \fBPURPLE\fP = '#815ba4'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.styles\&.paraiso_light
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Paraíso (Light) by Jan T\&. Sott

    Pygments template by Jan T\&. Sott (https://github\&.com/idleberg)
    Created with Base16 Builder by Chris Kempson
    (https://github\&.com/chriskempson/base16-builder)\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "str pygments\&.styles\&.paraiso_light\&.AQUA = '#5bc4bf'"

.SS "str pygments\&.styles\&.paraiso_light\&.BACKGROUND = '#e7e9db'"

.SS "str pygments\&.styles\&.paraiso_light\&.BLUE = '#06b6ef'"

.SS "str pygments\&.styles\&.paraiso_light\&.COMMENT = '#8d8687'"

.SS "str pygments\&.styles\&.paraiso_light\&.CURRENT_LINE = '#b9b6b0'"

.SS "str pygments\&.styles\&.paraiso_light\&.FOREGROUND = '#2f1e2e'"

.SS "str pygments\&.styles\&.paraiso_light\&.GREEN = '#48b685'"

.SS "str pygments\&.styles\&.paraiso_light\&.ORANGE = '#f99b15'"

.SS "str pygments\&.styles\&.paraiso_light\&.PURPLE = '#815ba4'"

.SS "str pygments\&.styles\&.paraiso_light\&.RED = '#ef6155'"

.SS "str pygments\&.styles\&.paraiso_light\&.SELECTION = '#a39e9b'"

.SS "str pygments\&.styles\&.paraiso_light\&.YELLOW = '#fec418'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
