.TH "pygments.lexer._This" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexer._This
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
.nf
Special singleton used for indicating the caller class\&.
Used by ``using``\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
