.TH "pygments.lexers.tnt.TNTLexer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.tnt.TNTLexer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.lexer\&.Lexer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, *args, **kwargs)"
.br
.ti -1c
.RI "\fBwhitespace\fP (self, start, text, required=False)"
.br
.ti -1c
.RI "\fBvariable\fP (self, start, text)"
.br
.ti -1c
.RI "\fBterm\fP (self, start, text)"
.br
.ti -1c
.RI "\fBformula\fP (self, start, text)"
.br
.ti -1c
.RI "\fBrule\fP (self, start, text)"
.br
.ti -1c
.RI "\fBlineno\fP (self, start, text)"
.br
.ti -1c
.RI "\fBerror_till_line_end\fP (self, start, text)"
.br
.ti -1c
.RI "\fBget_tokens_unprocessed\fP (self, text)"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBadd_filter\fP (self, filter_, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fBanalyse_text\fP (text)"
.br
.ti -1c
.RI "\fBget_tokens\fP (self, text, unfiltered=False)"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.lexer\&.LexerMeta\fP
.in +1c
.ti -1c
.RI "\fB__new__\fP (mcs, name, bases, d)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcur\fP"
.br
.in -1c

Public Attributes inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBstripnl\fP"
.br
.ti -1c
.RI "\fBstripall\fP"
.br
.ti -1c
.RI "\fBensurenl\fP"
.br
.ti -1c
.RI "\fBtabsize\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBfilters\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'Typographic Number Theory'"
.br
.ti -1c
.RI "str \fBurl\fP = 'https://github\&.com/Kenny2github/language\-tnt'"
.br
.ti -1c
.RI "list \fBaliases\fP = ['tnt']"
.br
.ti -1c
.RI "list \fBfilenames\fP = ['*\&.tnt']"
.br
.ti -1c
.RI "str \fBversion_added\fP = '2\&.7'"
.br
.ti -1c
.RI "list \fBcur\fP = []"
.br
.ti -1c
.RI "\fBLOGIC\fP = set('⊃→]&∧^|∨Vv')"
.br
.ti -1c
.RI "\fBOPERATORS\fP = set('+\&.⋅*')"
.br
.ti -1c
.RI "\fBVARIABLES\fP = set('abcde')"
.br
.ti -1c
.RI "\fBPRIMES\fP = set(''′')"
.br
.ti -1c
.RI "\fBNEGATORS\fP = set('~!')"
.br
.ti -1c
.RI "\fBQUANTIFIERS\fP = set('AE∀∃')"
.br
.ti -1c
.RI "\fBNUMBERS\fP = set('0123456789')"
.br
.ti -1c
.RI "\fBWHITESPACE\fP = set('\\t \\v\\n')"
.br
.ti -1c
.RI "\fBRULES\fP = re\&.compile()"
.br
.ti -1c
.RI "\fBLINENOS\fP = re\&.compile(r'(?:[0\-9]+)(?:(?:, ?|,? and )(?:[0\-9]+))*')"
.br
.ti -1c
.RI "\fBCOMMENT\fP = re\&.compile(r'\\[[^\\n\\]]+\\]')"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fBname\fP = None"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "list \fBfilenames\fP = []"
.br
.ti -1c
.RI "list \fBalias_filenames\fP = []"
.br
.ti -1c
.RI "list \fBmimetypes\fP = []"
.br
.ti -1c
.RI "int \fBpriority\fP = 0"
.br
.ti -1c
.RI "\fBurl\fP = None"
.br
.ti -1c
.RI "\fBversion_added\fP = None"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fB_preprocess_lexer_input\fP (self, text)"
.br
.in -1c

Static Protected Attributes inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fB_example\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Lexer for Typographic Number Theory, as described in the book
Gödel, Escher, Bach, by Douglas R\&. Hofstadter

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.__init__ ( self, * options, ** kwargs)"

.PP
.nf
This constructor takes arbitrary options as keyword arguments\&.
Every subclass must first process its own options and then call
the `Lexer` constructor, since it processes the basic
options like `stripnl`\&.

An example looks like this:

\&.\&. sourcecode:: python

   def __init__(self, **options):
       self\&.compress = options\&.get('compress', '')
       Lexer\&.__init__(self, **options)

As these options must all be specifiable as strings (due to the
command line usage), there are various utility functions
available to help with that, see `Utilities`_\&.

.fi
.PP
 
.PP
Reimplemented from \fBpygments\&.lexer\&.Lexer\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.error_till_line_end ( self,  start,  text)"

.PP
.nf
Mark everything from ``start`` to the end of the line as Error\&.
.fi
.PP
 
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.formula ( self,  start,  text)"

.PP
.nf
Tokenize a formula\&.
.fi
.PP
 
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.get_tokens_unprocessed ( self,  text)"

.PP
.nf
Returns a list of TNT tokens\&.
.fi
.PP
 
.PP
Reimplemented from \fBpygments\&.lexer\&.Lexer\fP\&.
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.lineno ( self,  start,  text)"

.PP
.nf
Tokenize a line referral\&.
.fi
.PP
 
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.rule ( self,  start,  text)"

.PP
.nf
Tokenize a rule\&.
.fi
.PP
 
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.term ( self,  start,  text)"

.PP
.nf
Tokenize a term\&.
.fi
.PP
 
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.variable ( self,  start,  text)"

.PP
.nf
Tokenize a variable\&.
.fi
.PP
 
.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.whitespace ( self,  start,  text,  required = \fCFalse\fP)"

.PP
.nf
Tokenize whitespace\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "list pygments\&.lexers\&.tnt\&.TNTLexer\&.aliases = ['tnt']\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.COMMENT = re\&.compile(r'\\[[^\\n\\]]+\\]')\fC [static]\fP"

.SS "list pygments\&.lexers\&.tnt\&.TNTLexer\&.cur = []\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.cur"

.SS "list pygments\&.lexers\&.tnt\&.TNTLexer\&.filenames = ['*\&.tnt']\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.LINENOS = re\&.compile(r'(?:[0\-9]+)(?:(?:, ?|,? and )(?:[0\-9]+))*')\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.LOGIC = set('⊃→]&∧^|∨Vv')\fC [static]\fP"

.SS "str pygments\&.lexers\&.tnt\&.TNTLexer\&.name = 'Typographic Number Theory'\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.NEGATORS = set('~!')\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.NUMBERS = set('0123456789')\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.OPERATORS = set('+\&.⋅*')\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.PRIMES = set(''′')\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.QUANTIFIERS = set('AE∀∃')\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.RULES = re\&.compile()\fC [static]\fP"

.SS "str pygments\&.lexers\&.tnt\&.TNTLexer\&.url = 'https://github\&.com/Kenny2github/language\-tnt'\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.VARIABLES = set('abcde')\fC [static]\fP"

.SS "str pygments\&.lexers\&.tnt\&.TNTLexer\&.version_added = '2\&.7'\fC [static]\fP"

.SS "pygments\&.lexers\&.tnt\&.TNTLexer\&.WHITESPACE = set('\\t \\v\\n')\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
