.TH "pygments.lexers.markup" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.markup
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBBCodeLexer\fP"
.br
.ti -1c
.RI "class \fBGroffLexer\fP"
.br
.ti -1c
.RI "class \fBMarkdownLexer\fP"
.br
.ti -1c
.RI "class \fBMoinWikiLexer\fP"
.br
.ti -1c
.RI "class \fBMozPreprocCssLexer\fP"
.br
.ti -1c
.RI "class \fBMozPreprocHashLexer\fP"
.br
.ti -1c
.RI "class \fBMozPreprocJavascriptLexer\fP"
.br
.ti -1c
.RI "class \fBMozPreprocPercentLexer\fP"
.br
.ti -1c
.RI "class \fBMozPreprocXulLexer\fP"
.br
.ti -1c
.RI "class \fBOrgLexer\fP"
.br
.ti -1c
.RI "class \fBRstLexer\fP"
.br
.ti -1c
.RI "class \fBTexLexer\fP"
.br
.ti -1c
.RI "class \fBTiddlyWiki5Lexer\fP"
.br
.ti -1c
.RI "class \fBWikitextLexer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.markup
    ~~~~~~~~~~~~~~~~~~~~~~

    Lexers for non-HTML markup languages\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
