.TH "pygments.styles.solarized" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.styles.solarized
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSolarizedDarkStyle\fP"
.br
.ti -1c
.RI "class \fBSolarizedLightStyle\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmake_style\fP (colors)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBDARK_COLORS\fP"
.br
.ti -1c
.RI "dict \fBLIGHT_COLORS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.styles\&.solarized
    ~~~~~~~~~~~~~~~~~~~~~~~~~

    Solarized by Camil Staps

    A Pygments style for the Solarized themes (licensed under MIT)\&.
    See: https://github\&.com/altercation/solarized

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pygments\&.styles\&.solarized\&.make_style ( colors)"

.SH "Variable Documentation"
.PP 
.SS "dict pygments\&.styles\&.solarized\&.DARK_COLORS"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'base03':  '#002b36',
3     'base02':  '#073642',
4     'base01':  '#586e75',
5     'base00':  '#657b83',
6     'base0':   '#839496',
7     'base1':   '#93a1a1',
8     'base2':   '#eee8d5',
9     'base3':   '#fdf6e3',
10     'yellow':  '#b58900',
11     'orange':  '#cb4b16',
12     'red':     '#dc322f',
13     'magenta': '#d33682',
14     'violet':  '#6c71c4',
15     'blue':    '#268bd2',
16     'cyan':    '#2aa198',
17     'green':   '#859900',
18 }
.fi

.SS "dict pygments\&.styles\&.solarized\&.LIGHT_COLORS"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'base3':   '#002b36',
3     'base2':   '#073642',
4     'base1':   '#586e75',
5     'base0':   '#657b83',
6     'base00':  '#839496',
7     'base01':  '#93a1a1',
8     'base02':  '#eee8d5',
9     'base03':  '#fdf6e3',
10     'yellow':  '#b58900',
11     'orange':  '#cb4b16',
12     'red':     '#dc322f',
13     'magenta': '#d33682',
14     'violet':  '#6c71c4',
15     'blue':    '#268bd2',
16     'cyan':    '#2aa198',
17     'green':   '#859900',
18 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
