.TH "pygments.filter.FunctionFilter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.filter.FunctionFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.filter\&.Filter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fBfilter\fP (self, lexer, stream)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoptions\fP"
.br
.in -1c

Public Attributes inherited from \fBpygments\&.filter\&.Filter\fP
.in +1c
.ti -1c
.RI "\fBoptions\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBfunction\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Abstract class used by `simplefilter` to create simple
function filters on the fly\&. The `simplefilter` decorator
automatically creates subclasses of this class for
functions passed to it\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pygments\&.filter\&.FunctionFilter\&.__init__ ( self, ** options)"

.PP
Reimplemented from \fBpygments\&.filter\&.Filter\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.filter\&.FunctionFilter\&.filter ( self,  lexer,  stream)"

.PP
Reimplemented from \fBpygments\&.filter\&.Filter\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "pygments\&.filter\&.FunctionFilter\&.function = None\fC [static]\fP"

.SS "pygments\&.filter\&.FunctionFilter\&.options"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
