.TH "pygments.lexers._mysql_builtins" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers._mysql_builtins
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBupdate_myself\fP ()"
.br
.ti -1c
.RI "\fBparse_lex_keywords\fP (f)"
.br
.ti -1c
.RI "\fBparse_lex_optimizer_hints\fP (f)"
.br
.ti -1c
.RI "\fBparse_lex_functions\fP (f)"
.br
.ti -1c
.RI "\fBparse_item_create_functions\fP (f)"
.br
.ti -1c
.RI "\fBupdate_content\fP (field_name, content)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBMYSQL_CONSTANTS\fP"
.br
.ti -1c
.RI "tuple \fBMYSQL_DATATYPES\fP"
.br
.ti -1c
.RI "tuple \fBMYSQL_FUNCTIONS\fP"
.br
.ti -1c
.RI "tuple \fBMYSQL_OPTIMIZER_HINTS\fP"
.br
.ti -1c
.RI "tuple \fBMYSQL_KEYWORDS\fP"
.br
.ti -1c
.RI "str \fBSOURCE_URL\fP = 'https://github\&.com/mysql/mysql\-server/raw/8\&.0'"
.br
.ti -1c
.RI "str \fBLEX_URL\fP = \fBSOURCE_URL\fP + '/sql/lex\&.h'"
.br
.ti -1c
.RI "str \fBITEM_CREATE_URL\fP = \fBSOURCE_URL\fP + '/sql/item_create\&.cc'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&._mysql_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Self-updating data files for the MySQL lexer\&.

    Run with `python -I` to update\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pygments\&.lexers\&._mysql_builtins\&.parse_item_create_functions ( f)"

.PP
.nf
Parse MySQL function names from item_create\&.cc\&.
.fi
.PP
 
.SS "pygments\&.lexers\&._mysql_builtins\&.parse_lex_functions ( f)"

.PP
.nf
Parse MySQL function names from lex\&.h\&.
.fi
.PP
 
.SS "pygments\&.lexers\&._mysql_builtins\&.parse_lex_keywords ( f)"

.PP
.nf
Parse keywords in lex\&.h\&.
.fi
.PP
 
.SS "pygments\&.lexers\&._mysql_builtins\&.parse_lex_optimizer_hints ( f)"

.PP
.nf
Parse optimizer hints in lex\&.h\&.
.fi
.PP
 
.SS "pygments\&.lexers\&._mysql_builtins\&.update_content ( field_name,  content)"

.PP
.nf
Overwrite this file with content parsed from MySQL's source code\&.
.fi
.PP
 
.SS "pygments\&.lexers\&._mysql_builtins\&.update_myself ()"

.SH "Variable Documentation"
.PP 
.SS "str pygments\&.lexers\&._mysql_builtins\&.ITEM_CREATE_URL = \fBSOURCE_URL\fP + '/sql/item_create\&.cc'"

.SS "str pygments\&.lexers\&._mysql_builtins\&.LEX_URL = \fBSOURCE_URL\fP + '/sql/lex\&.h'"

.SS "tuple pygments\&.lexers\&._mysql_builtins\&.MYSQL_CONSTANTS"
\fBInitial value:\fP.PP
.nf
1 =  (
2     'false',
3     'null',
4     'true',
5     'unknown',
6 )
.fi

.SS "tuple pygments\&.lexers\&._mysql_builtins\&.MYSQL_DATATYPES"

.SS "tuple pygments\&.lexers\&._mysql_builtins\&.MYSQL_FUNCTIONS"

.SS "tuple pygments\&.lexers\&._mysql_builtins\&.MYSQL_KEYWORDS"

.SS "tuple pygments\&.lexers\&._mysql_builtins\&.MYSQL_OPTIMIZER_HINTS"

.SS "str pygments\&.lexers\&._mysql_builtins\&.SOURCE_URL = 'https://github\&.com/mysql/mysql\-server/raw/8\&.0'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
