.TH "pygments.styles.gh_dark.GhDarkStyle" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.styles.gh_dark.GhDarkStyle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.style\&.Style\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'github\-dark'"
.br
.ti -1c
.RI "\fBbackground_color\fP = \fBBG_DEFAULT\fP"
.br
.ti -1c
.RI "\fBhighlight_color\fP = \fBGRAY_4\fP"
.br
.ti -1c
.RI "\fBline_number_special_color\fP = \fBFG_DEFAULT\fP"
.br
.ti -1c
.RI "\fBline_number_special_background_color\fP = \fBFG_SUBTLE\fP"
.br
.ti -1c
.RI "\fBline_number_color\fP = \fBGRAY_4\fP"
.br
.ti -1c
.RI "\fBline_number_background_color\fP = \fBBG_DEFAULT\fP"
.br
.ti -1c
.RI "dict \fBstyles\fP"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.style\&.Style\fP
.in +1c
.ti -1c
.RI "str \fBbackground_color\fP = '#ffffff'"
.br
.ti -1c
.RI "str \fBhighlight_color\fP = '#ffffcc'"
.br
.ti -1c
.RI "str \fBline_number_color\fP = 'inherit'"
.br
.ti -1c
.RI "str \fBline_number_background_color\fP = 'transparent'"
.br
.ti -1c
.RI "str \fBline_number_special_color\fP = '#000000'"
.br
.ti -1c
.RI "str \fBline_number_special_background_color\fP = '#ffffc0'"
.br
.ti -1c
.RI "dict \fBstyles\fP = {}"
.br
.ti -1c
.RI "str \fBname\fP = 'unnamed'"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "bool \fBweb_style_gallery_exclude\fP = False"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBpygments\&.style\&.StyleMeta\fP
.in +1c
.ti -1c
.RI "\fB__new__\fP (mcs, name, bases, dct)"
.br
.ti -1c
.RI "\fBstyle_for_token\fP (cls, token)"
.br
.ti -1c
.RI "\fBlist_styles\fP (cls)"
.br
.ti -1c
.RI "\fBstyles_token\fP (cls, ttype)"
.br
.ti -1c
.RI "\fB__iter__\fP (cls)"
.br
.ti -1c
.RI "\fB__len__\fP (cls)"
.br
.in -1c

Protected Attributes inherited from \fBpygments\&.style\&.StyleMeta\fP
.in +1c
.ti -1c
.RI "\fB_styles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Github's Dark-Colorscheme based theme for Pygments

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "pygments\&.styles\&.gh_dark\&.GhDarkStyle\&.background_color = \fBBG_DEFAULT\fP\fC [static]\fP"

.SS "pygments\&.styles\&.gh_dark\&.GhDarkStyle\&.highlight_color = \fBGRAY_4\fP\fC [static]\fP"

.SS "pygments\&.styles\&.gh_dark\&.GhDarkStyle\&.line_number_background_color = \fBBG_DEFAULT\fP\fC [static]\fP"

.SS "pygments\&.styles\&.gh_dark\&.GhDarkStyle\&.line_number_color = \fBGRAY_4\fP\fC [static]\fP"

.SS "pygments\&.styles\&.gh_dark\&.GhDarkStyle\&.line_number_special_background_color = \fBFG_SUBTLE\fP\fC [static]\fP"

.SS "pygments\&.styles\&.gh_dark\&.GhDarkStyle\&.line_number_special_color = \fBFG_DEFAULT\fP\fC [static]\fP"

.SS "str pygments\&.styles\&.gh_dark\&.GhDarkStyle\&.name = 'github\-dark'\fC [static]\fP"

.SS "dict pygments\&.styles\&.gh_dark\&.GhDarkStyle\&.styles\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
