.TH "pygments.lexers._scheme_builtins" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers._scheme_builtins
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBscheme_keywords\fP"
.br
.ti -1c
.RI "dict \fBscheme_builtins\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&._scheme_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Scheme builtins\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict pygments\&.lexers\&._scheme_builtins\&.scheme_builtins"

.SS "dict pygments\&.lexers\&._scheme_builtins\&.scheme_keywords"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
