.TH "pygments.formatters.irc.IRCFormatter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.formatters.irc.IRCFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.formatter\&.Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fBformat_unencoded\fP (self, tokensource, outfile)"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBget_style_defs\fP (self, arg='')"
.br
.ti -1c
.RI "\fBformat\fP (self, tokensource, outfile)"
.br
.ti -1c
.RI "\fB__class_getitem__\fP (cls, \fBname\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdarkbg\fP"
.br
.ti -1c
.RI "\fBcolorscheme\fP"
.br
.ti -1c
.RI "\fBlinenos\fP"
.br
.in -1c

Public Attributes inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBstyle\fP"
.br
.ti -1c
.RI "\fBfull\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'IRC'"
.br
.ti -1c
.RI "list \fBaliases\fP = ['irc', 'IRC']"
.br
.ti -1c
.RI "list \fBfilenames\fP = []"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.formatter\&.Formatter\fP
.in +1c
.ti -1c
.RI "\fBname\fP = None"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "list \fBfilenames\fP = []"
.br
.ti -1c
.RI "bool \fBunicodeoutput\fP = True"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_write_lineno\fP (self, outfile)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_lineno\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Format tokens with IRC color sequences

The `get_style_defs()` method doesn't do anything special since there is
no support for common styles\&.

Options accepted:

`bg`
    Set to ``'light'`` or ``'dark'`` depending on the terminal's background
    (default: ``'light'``)\&.

`colorscheme`
    A dictionary mapping token types to (lightbg, darkbg) color names or
    ``None`` (default: ``None`` = use builtin colorscheme)\&.

`linenos`
    Set to ``True`` to have line numbers in the output as well
    (default: ``False`` = no line numbers)\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pygments\&.formatters\&.irc\&.IRCFormatter\&.__init__ ( self, ** options)"

.PP
.nf
As with lexers, this constructor takes arbitrary optional arguments,
and if you override it, you should first process your own options, then
call the base class implementation\&.

.fi
.PP
 
.PP
Reimplemented from \fBpygments\&.formatter\&.Formatter\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.formatters\&.irc\&.IRCFormatter\&._write_lineno ( self,  outfile)\fC [protected]\fP"

.SS "pygments\&.formatters\&.irc\&.IRCFormatter\&.format_unencoded ( self,  tokensource,  outfile)"

.SH "Member Data Documentation"
.PP 
.SS "pygments\&.formatters\&.irc\&.IRCFormatter\&._lineno\fC [protected]\fP"

.SS "list pygments\&.formatters\&.irc\&.IRCFormatter\&.aliases = ['irc', 'IRC']\fC [static]\fP"

.SS "pygments\&.formatters\&.irc\&.IRCFormatter\&.colorscheme"

.SS "pygments\&.formatters\&.irc\&.IRCFormatter\&.darkbg"

.SS "list pygments\&.formatters\&.irc\&.IRCFormatter\&.filenames = []\fC [static]\fP"

.SS "pygments\&.formatters\&.irc\&.IRCFormatter\&.linenos"

.SS "str pygments\&.formatters\&.irc\&.IRCFormatter\&.name = 'IRC'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
