.TH "pygments.lexers._csound_builtins" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers._csound_builtins
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBREMOVED_OPCODES\fP = set(\&.split())"
.br
.ti -1c
.RI "\fBOPCODES\fP = set(\&.split())"
.br
.ti -1c
.RI "\fBDEPRECATED_OPCODES\fP = set(\&.split())"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&._csound_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "pygments\&.lexers\&._csound_builtins\&.DEPRECATED_OPCODES = set(\&.split())"

.SS "pygments\&.lexers\&._csound_builtins\&.OPCODES = set(\&.split())"

.SS "pygments\&.lexers\&._csound_builtins\&.REMOVED_OPCODES = set(\&.split())"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
