.TH "pygments.lexers.javascript" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.javascript
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoffeeScriptLexer\fP"
.br
.ti -1c
.RI "class \fBDartLexer\fP"
.br
.ti -1c
.RI "class \fBEarlGreyLexer\fP"
.br
.ti -1c
.RI "class \fBJavascriptLexer\fP"
.br
.ti -1c
.RI "class \fBJuttleLexer\fP"
.br
.ti -1c
.RI "class \fBKalLexer\fP"
.br
.ti -1c
.RI "class \fBLassoLexer\fP"
.br
.ti -1c
.RI "class \fBLiveScriptLexer\fP"
.br
.ti -1c
.RI "class \fBMaskLexer\fP"
.br
.ti -1c
.RI "class \fBNodeConsoleLexer\fP"
.br
.ti -1c
.RI "class \fBObjectiveJLexer\fP"
.br
.ti -1c
.RI "class \fBTypeScriptLexer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBJS_IDENT_START\fP"
.br
.ti -1c
.RI "tuple \fBJS_IDENT_PART\fP"
.br
.ti -1c
.RI "tuple \fBJS_IDENT\fP = \fBJS_IDENT_START\fP + '(?:' + \fBJS_IDENT_PART\fP + ')*'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.javascript
    ~~~~~~~~~~~~~~~~~~~~~~~~~~

    Lexers for JavaScript and related languages\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "tuple pygments\&.lexers\&.javascript\&.JS_IDENT = \fBJS_IDENT_START\fP + '(?:' + \fBJS_IDENT_PART\fP + ')*'"

.SS "tuple pygments\&.lexers\&.javascript\&.JS_IDENT_PART"
\fBInitial value:\fP.PP
.nf
1 =  ('(?:[$' + uni\&.combine('Lu', 'Ll', 'Lt', 'Lm', 'Lo', 'Nl',
2                                        'Mn', 'Mc', 'Nd', 'Pc') +
3                  '\\u200c\\u200d]|\\\\\\\\u[a\-fA\-F0\-9]{4})')
.fi

.SS "tuple pygments\&.lexers\&.javascript\&.JS_IDENT_START"
\fBInitial value:\fP.PP
.nf
1 =  ('(?:[$_' + uni\&.combine('Lu', 'Ll', 'Lt', 'Lm', 'Lo', 'Nl') +
2                   ']|\\\\\\\\u[a\-fA\-F0\-9]{4})')
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
