.TH "pygments.lexers.json5" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.json5
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJson5Lexer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstring_rules\fP (quote_mark)"
.br
.ti -1c
.RI "\fBquoted_field_name\fP (quote_mark)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.json5
    ~~~~~~~~~~~~~~~~~~~~~

    Lexer for Json5 file format\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pygments\&.lexers\&.json5\&.quoted_field_name ( quote_mark)"

.SS "pygments\&.lexers\&.json5\&.string_rules ( quote_mark)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
