.TH "pygments.lexers._lasso_builtins" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers._lasso_builtins
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBBUILTINS\fP"
.br
.ti -1c
.RI "dict \fBMEMBERS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&._lasso_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Built-in Lasso types, traits, methods, and members\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dict pygments\&.lexers\&._lasso_builtins\&.BUILTINS"

.SS "dict pygments\&.lexers\&._lasso_builtins\&.MEMBERS"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
