.TH "pygments.scanner" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.scanner
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEndOfText\fP"
.br
.ti -1c
.RI "class \fBScanner\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.scanner
    ~~~~~~~~~~~~~~~~

    This library implements a regex based scanner\&. Some languages
    like Pascal are easy to parse but have some keywords that
    depend on the context\&. Because of this it's impossible to lex
    that just by using a regular expression lexer like the
    `RegexLexer`\&.

    Have a look at the `DelphiLexer` to get an idea of how to use
    this scanner\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
