.TH "pygments.lexer.LexerMeta" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexer.LexerMeta
.SH SYNOPSIS
.br
.PP
.PP
Inherits type\&.
.PP
Inherited by \fBpygments\&.lexer\&.Lexer\fP, and \fBpygments\&.lexer\&.RegexLexerMeta\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__new__\fP (mcs, name, bases, d)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This metaclass automagically converts ``analyse_text`` methods into
static methods which always return float values\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.lexer\&.LexerMeta\&.__new__ ( mcs,  name,  bases,  d)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
