.TH "pygments.lexer.default" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexer.default
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBstate\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Indicates a state or state action (e\&.g\&. #pop) to apply\&.
For example default('#pop') is equivalent to ('', Token, '#pop')
Note that state tuples may be used as well\&.

\&.\&. versionadded:: 2\&.0

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pygments\&.lexer\&.default\&.__init__ ( self,  state)"

.SH "Member Data Documentation"
.PP 
.SS "pygments\&.lexer\&.default\&.state"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
