.TH "pygments.lexers.robotframework._Table" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.robotframework._Table
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpygments\&.lexers\&.robotframework\&.SettingTable\fP, \fBpygments\&.lexers\&.robotframework\&.TestCaseTable\fP, \fBpygments\&.lexers\&.robotframework\&.UnknownTable\fP, and \fBpygments\&.lexers\&.robotframework\&.VariableTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, prev_tokenizer=None)"
.br
.ti -1c
.RI "\fBtokenize\fP (self, value, index)"
.br
.ti -1c
.RI "\fBend_row\fP (self)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_continues\fP (self, value, index)"
.br
.ti -1c
.RI "\fB_is_empty\fP (self, value)"
.br
.ti -1c
.RI "\fB_tokenize\fP (self, value, index)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_tokenizer\fP"
.br
.ti -1c
.RI "\fB_prev_tokenizer\fP"
.br
.ti -1c
.RI "\fB_prev_values_on_row\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_tokenizer_class\fP = None"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pygments\&.lexers\&.robotframework\&._Table\&.__init__ ( self,  prev_tokenizer = \fCNone\fP)"

.PP
Reimplemented in \fBpygments\&.lexers\&.robotframework\&.SettingTable\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pygments\&.lexers\&.robotframework\&._Table\&._continues ( self,  value,  index)\fC [protected]\fP"

.PP
Reimplemented in \fBpygments\&.lexers\&.robotframework\&.UnknownTable\fP, and \fBpygments\&.lexers\&.robotframework\&.TestCaseTable\fP\&.
.SS "pygments\&.lexers\&.robotframework\&._Table\&._is_empty ( self,  value)\fC [protected]\fP"

.SS "pygments\&.lexers\&.robotframework\&._Table\&._tokenize ( self,  value,  index)\fC [protected]\fP"

.PP
Reimplemented in \fBpygments\&.lexers\&.robotframework\&.SettingTable\fP, and \fBpygments\&.lexers\&.robotframework\&.TestCaseTable\fP\&.
.SS "pygments\&.lexers\&.robotframework\&._Table\&.end_row ( self)"

.PP
Reimplemented in \fBpygments\&.lexers\&.robotframework\&.SettingTable\fP\&.
.SS "pygments\&.lexers\&.robotframework\&._Table\&.tokenize ( self,  value,  index)"

.SH "Member Data Documentation"
.PP 
.SS "pygments\&.lexers\&.robotframework\&._Table\&._prev_tokenizer\fC [protected]\fP"

.SS "pygments\&.lexers\&.robotframework\&._Table\&._prev_values_on_row\fC [protected]\fP"

.SS "pygments\&.lexers\&.robotframework\&._Table\&._tokenizer\fC [protected]\fP"

.SS "pygments\&.lexers\&.robotframework\&._Table\&._tokenizer_class = None\fC [static]\fP, \fC [protected]\fP"

.PP
Reimplemented in \fBpygments\&.lexers\&.robotframework\&.TestCaseTable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
