.TH "pygments.lexers.theorem.IsabelleLexer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.theorem.IsabelleLexer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpygments\&.lexer\&.RegexLexer\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBname\fP = 'Isabelle'"
.br
.ti -1c
.RI "str \fBurl\fP = 'https://isabelle\&.in\&.tum\&.de/'"
.br
.ti -1c
.RI "list \fBaliases\fP = ['isabelle']"
.br
.ti -1c
.RI "list \fBfilenames\fP = ['*\&.thy']"
.br
.ti -1c
.RI "list \fBmimetypes\fP = ['text/x\-isabelle']"
.br
.ti -1c
.RI "str \fBversion_added\fP = '2\&.0'"
.br
.ti -1c
.RI "tuple \fBkeyword_minor\fP"
.br
.ti -1c
.RI "tuple \fBkeyword_diag\fP"
.br
.ti -1c
.RI "tuple \fBkeyword_thy\fP = ('theory', 'begin', 'end')"
.br
.ti -1c
.RI "tuple \fBkeyword_section\fP = ('header', 'chapter')"
.br
.ti -1c
.RI "tuple \fBkeyword_subsection\fP"
.br
.ti -1c
.RI "tuple \fBkeyword_theory_decl\fP"
.br
.ti -1c
.RI "tuple \fBkeyword_theory_script\fP = ('inductive_cases', 'inductive_simps')"
.br
.ti -1c
.RI "tuple \fBkeyword_theory_goal\fP"
.br
.ti -1c
.RI "tuple \fBkeyword_qed\fP = ('by', 'done', 'qed')"
.br
.ti -1c
.RI "tuple \fBkeyword_abandon_proof\fP = ('sorry', 'oops')"
.br
.ti -1c
.RI "tuple \fBkeyword_proof_goal\fP = ('have', 'hence', 'interpret')"
.br
.ti -1c
.RI "tuple \fBkeyword_proof_block\fP = ('next', 'proof')"
.br
.ti -1c
.RI "tuple \fBkeyword_proof_chain\fP"
.br
.ti -1c
.RI "tuple \fBkeyword_proof_decl\fP"
.br
.ti -1c
.RI "tuple \fBkeyword_proof_asm\fP = ('assume', 'case', '\fBdef\fP', 'fix', 'presume')"
.br
.ti -1c
.RI "tuple \fBkeyword_proof_asm_goal\fP = ('guess', 'obtain', 'show', 'thus')"
.br
.ti -1c
.RI "tuple \fBkeyword_proof_script\fP"
.br
.ti -1c
.RI "tuple \fBoperators\fP"
.br
.ti -1c
.RI "tuple \fBproof_operators\fP = ('{', '}', '\&.', '\&.\&.')"
.br
.ti -1c
.RI "dict \fBtokens\fP"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.lexer\&.RegexLexer\fP
.in +1c
.ti -1c
.RI "\fBflags\fP = re\&.MULTILINE"
.br
.ti -1c
.RI "dict \fBtokens\fP = {}"
.br
.in -1c

Static Public Attributes inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fBname\fP = None"
.br
.ti -1c
.RI "list \fBaliases\fP = []"
.br
.ti -1c
.RI "list \fBfilenames\fP = []"
.br
.ti -1c
.RI "list \fBalias_filenames\fP = []"
.br
.ti -1c
.RI "list \fBmimetypes\fP = []"
.br
.ti -1c
.RI "int \fBpriority\fP = 0"
.br
.ti -1c
.RI "\fBurl\fP = None"
.br
.ti -1c
.RI "\fBversion_added\fP = None"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBpygments\&.lexer\&.RegexLexer\fP
.in +1c
.ti -1c
.RI "\fBget_tokens_unprocessed\fP (self, text, stack=('root',))"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBadd_filter\fP (self, filter_, **\fBoptions\fP)"
.br
.ti -1c
.RI "\fBanalyse_text\fP (text)"
.br
.ti -1c
.RI "\fBget_tokens\fP (self, text, unfiltered=False)"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.lexer\&.LexerMeta\fP
.in +1c
.ti -1c
.RI "\fB__new__\fP (mcs, name, bases, d)"
.br
.in -1c

Public Member Functions inherited from \fBpygments\&.lexer\&.RegexLexerMeta\fP
.in +1c
.ti -1c
.RI "\fBprocess_tokendef\fP (cls, name, tokendefs=None)"
.br
.ti -1c
.RI "\fBget_tokendefs\fP (cls)"
.br
.ti -1c
.RI "\fB__call__\fP (cls, *args, **kwds)"
.br
.in -1c

Public Attributes inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBstripnl\fP"
.br
.ti -1c
.RI "\fBstripall\fP"
.br
.ti -1c
.RI "\fBensurenl\fP"
.br
.ti -1c
.RI "\fBtabsize\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBfilters\fP"
.br
.in -1c

Protected Member Functions inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fB_preprocess_lexer_input\fP (self, text)"
.br
.in -1c

Protected Member Functions inherited from \fBpygments\&.lexer\&.RegexLexerMeta\fP
.in +1c
.ti -1c
.RI "\fB_process_regex\fP (cls, regex, rflags, state)"
.br
.ti -1c
.RI "\fB_process_token\fP (cls, token)"
.br
.ti -1c
.RI "\fB_process_new_state\fP (cls, new_state, unprocessed, processed)"
.br
.ti -1c
.RI "\fB_process_state\fP (cls, unprocessed, processed, state)"
.br
.in -1c

Protected Attributes inherited from \fBpygments\&.lexer\&.RegexLexerMeta\fP
.in +1c
.ti -1c
.RI "\fB_all_tokens\fP"
.br
.ti -1c
.RI "\fB_tmpname\fP"
.br
.ti -1c
.RI "\fB_tokens\fP"
.br
.in -1c

Static Protected Attributes inherited from \fBpygments\&.lexer\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fB_example\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
For the Isabelle proof assistant\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "list pygments\&.lexers\&.theorem\&.IsabelleLexer\&.aliases = ['isabelle']\fC [static]\fP"

.SS "list pygments\&.lexers\&.theorem\&.IsabelleLexer\&.filenames = ['*\&.thy']\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_abandon_proof = ('sorry', 'oops')\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_diag\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        'ML_command', 'ML_val', 'class_deps', 'code_deps', 'code_thms',
        'display_drafts', 'find_consts', 'find_theorems', 'find_unused_assms',
        'full_prf', 'help', 'locale_deps', 'nitpick', 'pr', 'prf',
        'print_abbrevs', 'print_antiquotations', 'print_attributes',
        'print_binds', 'print_bnfs', 'print_bundles',
        'print_case_translations', 'print_cases', 'print_claset',
        'print_classes', 'print_codeproc', 'print_codesetup',
        'print_coercions', 'print_commands', 'print_context',
        'print_defn_rules', 'print_dependencies', 'print_facts',
        'print_induct_rules', 'print_inductives', 'print_interps',
        'print_locale', 'print_locales', 'print_methods', 'print_options',
        'print_orders', 'print_quot_maps', 'print_quotconsts',
        'print_quotients', 'print_quotientsQ3', 'print_quotmapsQ3',
        'print_rules', 'print_simpset', 'print_state', 'print_statement',
        'print_syntax', 'print_theorems', 'print_theory', 'print_trans_rules',
        'prop', 'pwd', 'quickcheck', 'refute', 'sledgehammer', 'smt_status',
        'solve_direct', 'spark_status', 'term', 'thm', 'thm_deps', 'thy_deps',
        'try', 'try0', 'typ', 'unused_thms', 'value', 'values', 'welcome',
        'print_ML_antiquotations', 'print_term_bindings', 'values_prolog',
    )
.fi

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_minor\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        'and', 'assumes', 'attach', 'avoids', 'binder', 'checking',
        'class_instance', 'class_relation', 'code_module', 'congs',
        'constant', 'constrains', 'datatypes', 'defines', 'file', 'fixes',
        'for', 'functions', 'hints', 'identifier', 'if', 'imports', 'in',
        'includes', 'infix', 'infixl', 'infixr', 'is', 'keywords', 'lazy',
        'module_name', 'monos', 'morphisms', 'no_discs_sels', 'notes',
        'obtains', 'open', 'output', 'overloaded', 'parametric', 'permissive',
        'pervasive', 'rep_compat', 'shows', 'structure', 'type_class',
        'type_constructor', 'unchecked', 'unsafe', 'where',
    )
.fi

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_proof_asm = ('assume', 'case', '\fBdef\fP', 'fix', 'presume')\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_proof_asm_goal = ('guess', 'obtain', 'show', 'thus')\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_proof_block = ('next', 'proof')\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_proof_chain\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        'finally', 'from', 'then', 'ultimately', 'with',
    )
.fi

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_proof_decl\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        'ML_prf', 'also', 'include', 'including', 'let', 'moreover', 'note',
        'txt', 'txt_raw', 'unfolding', 'using', 'write',
    )
.fi

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_proof_goal = ('have', 'hence', 'interpret')\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_proof_script\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        'apply', 'apply_end', 'apply_trace', 'back', 'defer', 'prefer',
    )
.fi

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_qed = ('by', 'done', 'qed')\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_section = ('header', 'chapter')\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_subsection\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        'section', 'subsection', 'subsubsection', 'sect', 'subsect',
        'subsubsect',
    )
.fi

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_theory_decl\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_theory_goal\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        'ax_specification', 'bnf', 'code_pred', 'corollary', 'cpodef',
        'crunch', 'crunch_ignore',
        'enriched_type', 'function', 'instance', 'interpretation', 'lemma',
        'lift_definition', 'nominal_inductive', 'nominal_inductive2',
        'nominal_primrec', 'pcpodef', 'primcorecursive',
        'quotient_definition', 'quotient_type', 'recdef_tc', 'rep_datatype',
        'schematic_corollary', 'schematic_lemma', 'schematic_theorem',
        'spark_vc', 'specification', 'subclass', 'sublocale', 'termination',
        'theorem', 'typedef', 'wrap_free_constructors',
    )
.fi

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_theory_script = ('inductive_cases', 'inductive_simps')\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.keyword_thy = ('theory', 'begin', 'end')\fC [static]\fP"

.SS "list pygments\&.lexers\&.theorem\&.IsabelleLexer\&.mimetypes = ['text/x\-isabelle']\fC [static]\fP"

.SS "str pygments\&.lexers\&.theorem\&.IsabelleLexer\&.name = 'Isabelle'\fC [static]\fP"

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.operators\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        '::', ':', '(', ')', '[', ']', '_', '=', ',', '|',
        '+', '\-', '!', '?',
    )
.fi

.SS "tuple pygments\&.lexers\&.theorem\&.IsabelleLexer\&.proof_operators = ('{', '}', '\&.', '\&.\&.')\fC [static]\fP"

.SS "dict pygments\&.lexers\&.theorem\&.IsabelleLexer\&.tokens\fC [static]\fP"

.SS "str pygments\&.lexers\&.theorem\&.IsabelleLexer\&.url = 'https://isabelle\&.in\&.tum\&.de/'\fC [static]\fP"

.SS "str pygments\&.lexers\&.theorem\&.IsabelleLexer\&.version_added = '2\&.0'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
