.TH "pygments.lexers.jsonnet" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.jsonnet
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJsonnetLexer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstring_rules\fP (quote_mark)"
.br
.ti -1c
.RI "\fBquoted_field_name\fP (quote_mark)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBjsonnet_token\fP = r'[^\\W\\d]\\w*'"
.br
.ti -1c
.RI "str \fBjsonnet_function_token\fP = \fBjsonnet_token\fP + r'(?=\\()'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.jsonnet
    ~~~~~~~~~~~~~~~~~~~~~~~

    Lexer for Jsonnet data templating language\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pygments\&.lexers\&.jsonnet\&.quoted_field_name ( quote_mark)"

.SS "pygments\&.lexers\&.jsonnet\&.string_rules ( quote_mark)"

.SH "Variable Documentation"
.PP 
.SS "str pygments\&.lexers\&.jsonnet\&.jsonnet_function_token = \fBjsonnet_token\fP + r'(?=\\()'"

.SS "str pygments\&.lexers\&.jsonnet\&.jsonnet_token = r'[^\\W\\d]\\w*'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
