.TH "pygments.styles.sas" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.styles.sas
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSasStyle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.styles\&.sas
    ~~~~~~~~~~~~~~~~~~~

    Style inspired by SAS' enhanced program editor\&. Note This is not
    meant to be a complete style\&. It's merely meant to mimic SAS'
    program editor syntax highlighting\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
