.TH "pygments.lexers._php_builtins" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers._php_builtins
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_php_functions\fP ()"
.br
.ti -1c
.RI "\fBget_php_references\fP ()"
.br
.ti -1c
.RI "\fBregenerate\fP (filename, modules)"
.br
.ti -1c
.RI "\fBrun\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBMODULES\fP"
.br
.ti -1c
.RI "str \fBPHP_MANUAL_URL\fP = 'http://us3\&.php\&.net/distributions/manual/php_manual_en\&.tar\&.gz'"
.br
.ti -1c
.RI "str \fBPHP_MANUAL_DIR\fP = '\&./php\-chunked\-xhtml/'"
.br
.ti -1c
.RI "str \fBPHP_REFERENCE_GLOB\fP = 'ref\&.*'"
.br
.ti -1c
.RI "str \fBPHP_FUNCTION_RE\fP = r'<a href='function\\\&.\&.*?\\\&.html'>(\&.*?)</a>'"
.br
.ti -1c
.RI "str \fBPHP_MODULE_RE\fP = '<title>(\&.*?) Functions</title>'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&._php_builtins
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    This file loads the function names and their modules from the
    php webpage and generates itself\&.

    Run with `python -I` to regenerate\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pygments\&.lexers\&._php_builtins\&.get_php_functions ()"

.SS "pygments\&.lexers\&._php_builtins\&.get_php_references ()"

.SS "pygments\&.lexers\&._php_builtins\&.regenerate ( filename,  modules)"

.SS "pygments\&.lexers\&._php_builtins\&.run ()"

.SH "Variable Documentation"
.PP 
.SS "dict pygments\&.lexers\&._php_builtins\&.MODULES"

.SS "str pygments\&.lexers\&._php_builtins\&.PHP_FUNCTION_RE = r'<a href='function\\\&.\&.*?\\\&.html'>(\&.*?)</a>'"

.SS "str pygments\&.lexers\&._php_builtins\&.PHP_MANUAL_DIR = '\&./php\-chunked\-xhtml/'"

.SS "str pygments\&.lexers\&._php_builtins\&.PHP_MANUAL_URL = 'http://us3\&.php\&.net/distributions/manual/php_manual_en\&.tar\&.gz'"

.SS "str pygments\&.lexers\&._php_builtins\&.PHP_MODULE_RE = '<title>(\&.*?) Functions</title>'"

.SS "str pygments\&.lexers\&._php_builtins\&.PHP_REFERENCE_GLOB = 'ref\&.*'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
