.TH "pygments.lexers.shell" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pygments.lexers.shell
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBashLexer\fP"
.br
.ti -1c
.RI "class \fBBashSessionLexer\fP"
.br
.ti -1c
.RI "class \fBBatchLexer\fP"
.br
.ti -1c
.RI "class \fBExeclineLexer\fP"
.br
.ti -1c
.RI "class \fBFishShellLexer\fP"
.br
.ti -1c
.RI "class \fBMSDOSSessionLexer\fP"
.br
.ti -1c
.RI "class \fBPowerShellLexer\fP"
.br
.ti -1c
.RI "class \fBPowerShellSessionLexer\fP"
.br
.ti -1c
.RI "class \fBShellSessionBaseLexer\fP"
.br
.ti -1c
.RI "class \fBSlurmBashLexer\fP"
.br
.ti -1c
.RI "class \fBTcshLexer\fP"
.br
.ti -1c
.RI "class \fBTcshSessionLexer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    pygments\&.lexers\&.shell
    ~~~~~~~~~~~~~~~~~~~~~

    Lexers for various shells\&.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS\&.
    :license: BSD, see LICENSE for details\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
