.TH "requests.exceptions.RequestException" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
requests.exceptions.RequestException
.SH SYNOPSIS
.br
.PP
.PP
Inherits IOError\&.
.PP
Inherited by \fBrequests\&.exceptions\&.ChunkedEncodingError\fP, \fBrequests\&.exceptions\&.ConnectionError\fP, \fBrequests\&.exceptions\&.ContentDecodingError\fP, \fBrequests\&.exceptions\&.HTTPError\fP, \fBrequests\&.exceptions\&.InvalidHeader\fP, \fBrequests\&.exceptions\&.InvalidJSONError\fP, \fBrequests\&.exceptions\&.InvalidSchema\fP, \fBrequests\&.exceptions\&.InvalidURL\fP, \fBrequests\&.exceptions\&.MissingSchema\fP, \fBrequests\&.exceptions\&.RetryError\fP, \fBrequests\&.exceptions\&.StreamConsumedError\fP, \fBrequests\&.exceptions\&.Timeout\fP, \fBrequests\&.exceptions\&.TooManyRedirects\fP, \fBrequests\&.exceptions\&.URLRequired\fP, and \fBrequests\&.exceptions\&.UnrewindableBodyError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, *args, **kwargs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBresponse\fP"
.br
.ti -1c
.RI "\fBrequest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
There was an ambiguous exception that occurred while handling your
request\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "requests\&.exceptions\&.RequestException\&.__init__ ( self, * args, ** kwargs)"

.PP
.nf
Initialize RequestException with `request` and `response` objects\&.
.fi
.PP
 
.PP
Reimplemented in \fBrequests\&.exceptions\&.JSONDecodeError\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "requests\&.exceptions\&.RequestException\&.request"

.SS "requests\&.exceptions\&.RequestException\&.response"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
