.TH "requests.packages" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
requests.packages
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtarget\fP = chardet\&.__name__"
.br
.ti -1c
.RI "\fBimported_mod\fP = sys\&.modules[\fBmod\fP]"
.br
.ti -1c
.RI "\fBmod\fP = mod\&.replace(\fBtarget\fP, 'chardet')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "requests\&.packages\&.imported_mod = sys\&.modules[\fBmod\fP]"

.SS "requests\&.packages\&.mod = mod\&.replace(\fBtarget\fP, 'chardet')"

.SS "requests\&.packages\&.target = chardet\&.__name__"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
