.TH "requests.cookies.CookieConflictError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
requests.cookies.CookieConflictError
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeError\&.
.SH "Detailed Description"
.PP 

.PP
.nf
There are two cookies that meet the criteria specified in the cookie jar\&.
Use \&.get and \&.set and include domain and path args in order to be more specific\&.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
