.TH "requests.certs" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
requests.certs
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
.nf
requests\&.certs
~~~~~~~~~~~~~~

This module returns the preferred default CA certificate bundle\&. There is
only one — the one from the certifi package\&.

If you are packaging Requests, e\&.g\&., for a Linux distribution or a managed
environment, you can change the definition of where() to return a separately
packaged CA bundle\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
