.TH "requests.models.Response" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
requests.models.Response
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fB__enter__\fP (self)"
.br
.ti -1c
.RI "\fB__exit__\fP (self, *args)"
.br
.ti -1c
.RI "\fB__getstate__\fP (self)"
.br
.ti -1c
.RI "\fB__setstate__\fP (self, state)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__bool__\fP (self)"
.br
.ti -1c
.RI "\fB__nonzero__\fP (self)"
.br
.ti -1c
.RI "\fB__iter__\fP (self)"
.br
.ti -1c
.RI "\fBok\fP (self)"
.br
.ti -1c
.RI "\fBis_redirect\fP (self)"
.br
.ti -1c
.RI "\fBis_permanent_redirect\fP (self)"
.br
.ti -1c
.RI "\fBnext\fP (self)"
.br
.ti -1c
.RI "\fBapparent_encoding\fP (self)"
.br
.ti -1c
.RI "\fBiter_content\fP (self, chunk_size=1, decode_unicode=False)"
.br
.ti -1c
.RI "\fBiter_lines\fP (self, chunk_size=\fBITER_CHUNK_SIZE\fP, decode_unicode=False, delimiter=None)"
.br
.ti -1c
.RI "\fBcontent\fP (self)"
.br
.ti -1c
.RI "\fBtext\fP (self)"
.br
.ti -1c
.RI "\fBjson\fP (self, **kwargs)"
.br
.ti -1c
.RI "\fBlinks\fP (self)"
.br
.ti -1c
.RI "\fBraise_for_status\fP (self)"
.br
.ti -1c
.RI "\fBclose\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatus_code\fP"
.br
.ti -1c
.RI "\fBheaders\fP"
.br
.ti -1c
.RI "\fBraw\fP"
.br
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBhistory\fP"
.br
.ti -1c
.RI "\fBreason\fP"
.br
.ti -1c
.RI "\fBcookies\fP"
.br
.ti -1c
.RI "\fBelapsed\fP"
.br
.ti -1c
.RI "\fBrequest\fP"
.br
.ti -1c
.RI "\fBcontent\fP"
.br
.ti -1c
.RI "\fBtext\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_content\fP"
.br
.ti -1c
.RI "\fB_content_consumed\fP"
.br
.ti -1c
.RI "\fB_next\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The :class:`Response <Response>` object, which contains a
server's response to an HTTP request\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "requests\&.models\&.Response\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "requests\&.models\&.Response\&.__bool__ ( self)"

.PP
.nf
Returns True if :attr:`status_code` is less than 400\&.

This attribute checks if the status code of the response is between
400 and 600 to see if there was a client error or a server error\&. If
the status code, is between 200 and 400, this will return True\&. This
is **not** a check to see if the response code is ``200 OK``\&.

.fi
.PP
 
.SS "requests\&.models\&.Response\&.__enter__ ( self)"

.SS "requests\&.models\&.Response\&.__exit__ ( self, * args)"

.SS "requests\&.models\&.Response\&.__getstate__ ( self)"

.SS "requests\&.models\&.Response\&.__iter__ ( self)"

.PP
.nf
Allows you to use a response as an iterator\&.
.fi
.PP
 
.SS "requests\&.models\&.Response\&.__nonzero__ ( self)"

.PP
.nf
Returns True if :attr:`status_code` is less than 400\&.

This attribute checks if the status code of the response is between
400 and 600 to see if there was a client error or a server error\&. If
the status code, is between 200 and 400, this will return True\&. This
is **not** a check to see if the response code is ``200 OK``\&.

.fi
.PP
 
.SS "requests\&.models\&.Response\&.__repr__ ( self)"

.SS "requests\&.models\&.Response\&.__setstate__ ( self,  state)"

.SS "requests\&.models\&.Response\&.apparent_encoding ( self)"

.PP
.nf
The apparent encoding, provided by the charset_normalizer or chardet libraries\&.
.fi
.PP
 
.SS "requests\&.models\&.Response\&.close ( self)"

.PP
.nf
Releases the connection back to the pool\&. Once this method has been
called the underlying ``raw`` object must not be accessed again\&.

*Note: Should not normally need to be called explicitly\&.*

.fi
.PP
 
.SS "requests\&.models\&.Response\&.content ( self)"

.PP
.nf
Content of the response, in bytes\&.
.fi
.PP
 
.SS "requests\&.models\&.Response\&.is_permanent_redirect ( self)"

.PP
.nf
True if this Response one of the permanent versions of redirect\&.
.fi
.PP
 
.SS "requests\&.models\&.Response\&.is_redirect ( self)"

.PP
.nf
True if this Response is a well-formed HTTP redirect that could have
been processed automatically (by :meth:`Session\&.resolve_redirects`)\&.

.fi
.PP
 
.SS "requests\&.models\&.Response\&.iter_content ( self,  chunk_size = \fC1\fP,  decode_unicode = \fCFalse\fP)"

.PP
.nf
Iterates over the response data\&.  When stream=True is set on the
request, this avoids reading the content at once into memory for
large responses\&.  The chunk size is the number of bytes it should
read into memory\&.  This is not necessarily the length of each item
returned as decoding can take place\&.

chunk_size must be of type int or None\&. A value of None will
function differently depending on the value of `stream`\&.
stream=True will read data as it arrives in whatever size the
chunks are received\&. If stream=False, data is returned as
a single chunk\&.

If decode_unicode is True, content will be decoded using the best
available encoding based on the response\&.

.fi
.PP
 
.SS "requests\&.models\&.Response\&.iter_lines ( self,  chunk_size = \fC\fBITER_CHUNK_SIZE\fP\fP,  decode_unicode = \fCFalse\fP,  delimiter = \fCNone\fP)"

.PP
.nf
Iterates over the response data, one line at a time\&.  When
stream=True is set on the request, this avoids reading the
content at once into memory for large responses\&.

\&.\&. note:: This method is not reentrant safe\&.

.fi
.PP
 
.SS "requests\&.models\&.Response\&.json ( self, ** kwargs)"

.PP
.nf
Decodes the JSON response body (if any) as a Python object\&.

This may return a dictionary, list, etc\&. depending on what is in the response\&.

:param \\*\\*kwargs: Optional arguments that ``json\&.loads`` takes\&.
:raises requests\&.exceptions\&.JSONDecodeError: If the response body does not
contain valid json\&.

.fi
.PP
 
.SS "requests\&.models\&.Response\&.links ( self)"

.PP
.nf
Returns the parsed header links of the response, if any\&.
.fi
.PP
 
.SS "requests\&.models\&.Response\&.next ( self)"

.PP
.nf
Returns a PreparedRequest for the next request in a redirect chain, if there is one\&.
.fi
.PP
 
.SS "requests\&.models\&.Response\&.ok ( self)"

.PP
.nf
Returns True if :attr:`status_code` is less than 400, False if not\&.

This attribute checks if the status code of the response is between
400 and 600 to see if there was a client error or a server error\&. If
the status code is between 200 and 400, this will return True\&. This
is **not** a check to see if the response code is ``200 OK``\&.

.fi
.PP
 
.SS "requests\&.models\&.Response\&.raise_for_status ( self)"

.PP
.nf
Raises :class:`HTTPError`, if one occurred\&.
.fi
.PP
 
.SS "requests\&.models\&.Response\&.text ( self)"

.PP
.nf
Content of the response, in unicode\&.

If Response\&.encoding is None, encoding will be guessed using
``charset_normalizer`` or ``chardet``\&.

The encoding of the response content is determined based solely on HTTP
headers, following RFC 2616 to the letter\&. If you can take advantage of
non-HTTP knowledge to make a better guess at the encoding, you should
set ``r\&.encoding`` appropriately before accessing this property\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "requests\&.models\&.Response\&._content\fC [protected]\fP"

.SS "requests\&.models\&.Response\&._content_consumed\fC [protected]\fP"

.SS "requests\&.models\&.Response\&._next\fC [protected]\fP"

.SS "requests\&.models\&.Response\&.content"

.SS "requests\&.models\&.Response\&.cookies"

.SS "requests\&.models\&.Response\&.elapsed"

.SS "requests\&.models\&.Response\&.encoding"

.SS "requests\&.models\&.Response\&.headers"

.SS "requests\&.models\&.Response\&.history"

.SS "requests\&.models\&.Response\&.raw"

.SS "requests\&.models\&.Response\&.reason"

.SS "requests\&.models\&.Response\&.request"

.SS "requests\&.models\&.Response\&.status_code"

.SS "requests\&.models\&.Response\&.text"

.SS "requests\&.models\&.Response\&.url"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
