.TH "requests.auth.AuthBase" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
requests.auth.AuthBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBrequests\&.auth\&.HTTPBasicAuth\fP, and \fBrequests\&.auth\&.HTTPDigestAuth\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__call__\fP (self, r)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base class that all auth implementations derive from
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "requests\&.auth\&.AuthBase\&.__call__ ( self,  r)"

.PP
Reimplemented in \fBrequests\&.auth\&.HTTPBasicAuth\fP, \fBrequests\&.auth\&.HTTPProxyAuth\fP, and \fBrequests\&.auth\&.HTTPDigestAuth\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
