.TH "requests.exceptions.RequestsDependencyWarning" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
requests.exceptions.RequestsDependencyWarning
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrequests\&.exceptions\&.RequestsWarning\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
An imported dependency doesn't match the expected version range\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
