.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/waitress/runner.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/waitress/runner.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwaitress\fP"
.br
.ti -1c
.RI "namespace \fBwaitress\&.runner\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwaitress\&.runner\&.show_help\fP (stream, name, error=None)"
.br
.ti -1c
.RI "\fBwaitress\&.runner\&.show_exception\fP (stream)"
.br
.ti -1c
.RI "\fBwaitress\&.runner\&.run\fP (argv=sys\&.argv, _serve=serve)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBwaitress\&.runner\&.HELP\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
