.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/jinja2/runtime.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/jinja2/runtime.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjinja2\&.runtime\&.LoopRenderFunc\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.TemplateReference\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.Context\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.BlockReference\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.LoopContext\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.AsyncLoopContext\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.Macro\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.Undefined\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.ChainableUndefined\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.DebugUndefined\fP"
.br
.ti -1c
.RI "class \fBjinja2\&.runtime\&.StrictUndefined\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBjinja2\fP"
.br
.ti -1c
.RI "namespace \fBjinja2\&.runtime\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBV\fP \fBjinja2\&.runtime\&.identity\fP (\fBV\fP x)"
.br
.ti -1c
.RI "str \fBjinja2\&.runtime\&.markup_join\fP (t\&.Iterable[t\&.Any] seq)"
.br
.ti -1c
.RI "str \fBjinja2\&.runtime\&.str_join\fP (t\&.Iterable[t\&.Any] seq)"
.br
.ti -1c
.RI "'Context' \fBjinja2\&.runtime\&.new_context\fP ('Environment' environment, t\&.Optional[str] template_name, t\&.Dict[str, t\&.Callable[['Context'], t\&.Iterator[str]]] blocks, t\&.Optional[t\&.Dict[str, t\&.Any]] vars=None, bool shared=False, t\&.Optional[t\&.MutableMapping[str, t\&.Any]] globals=None, t\&.Optional[t\&.Mapping[str, t\&.Any]] locals=None)"
.br
.ti -1c
.RI "\fBF\fP \fBjinja2\&.runtime\&._dict_method_all\fP (\fBF\fP dict_method)"
.br
.ti -1c
.RI "t\&.Type[\fBUndefined\fP] \fBjinja2\&.runtime\&.make_logging_undefined\fP (t\&.Optional['logging\&.Logger'] logger=None, t\&.Type[\fBUndefined\fP] base=\fBUndefined\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBjinja2\&.runtime\&.V\fP = t\&.TypeVar('V')"
.br
.ti -1c
.RI "\fBjinja2\&.runtime\&.F\fP = t\&.TypeVar('F', bound=t\&.Callable[\&.\&.\&., t\&.Any])"
.br
.ti -1c
.RI "list \fBjinja2\&.runtime\&.exported\fP"
.br
.ti -1c
.RI "list \fBjinja2\&.runtime\&.async_exported\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
