.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/distlib/scripts.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/distlib/scripts.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._vendor\&.distlib\&.scripts\&.ScriptMaker\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.distlib\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.distlib\&.scripts\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.scripts\&.enquote_executable\fP (executable)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.scripts\&.logger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.distlib\&.scripts\&._DEFAULT_MANIFEST\fP"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.scripts\&.FIRST_LINE_RE\fP = re\&.compile(b'^#!\&.*pythonw?[0\-9\&.]*([ \\t]\&.*)?$')"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.distlib\&.scripts\&.SCRIPT_TEMPLATE\fP"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.scripts\&.DISTLIB_PACKAGE\fP = __name__\&.rsplit('\&.', 1)[0]"
.br
.ti -1c
.RI "dict \fBpip\&._vendor\&.distlib\&.scripts\&.WRAPPERS\fP"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.scripts\&._enquote_executable\fP = \fBenquote_executable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
