.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/commands/search.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/commands/search.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._internal\&.commands\&.search\&.TransformedHit\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.commands\&.search\&.SearchCommand\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.commands\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.commands\&.search\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "List['TransformedHit'] \fBpip\&._internal\&.commands\&.search\&.transform_hits\fP (List[Dict[str, str]] hits)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.commands\&.search\&.print_dist_installation_info\fP (str name, str latest)"
.br
.ti -1c
.RI "None \fBpip\&._internal\&.commands\&.search\&.print_results\fP (List['TransformedHit'] hits, Optional[int] name_column_width=None, Optional[int] terminal_width=None)"
.br
.ti -1c
.RI "str \fBpip\&._internal\&.commands\&.search\&.highest_version\fP (List[str] versions)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._internal\&.commands\&.search\&.logger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
