.TH "serializinghtml.jsonimpl" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serializinghtml.jsonimpl
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSphinxJSONEncoder\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBdump\fP (Any obj, IO[str]|IO[bytes] file, *Any args, **Any kwds)"
.br
.ti -1c
.RI "str \fBdumps\fP (Any obj, *Any args, **Any kwds)"
.br
.ti -1c
.RI "Any \fBload\fP (*Any args, **Any kwds)"
.br
.ti -1c
.RI "Any \fBloads\fP (*Any args, **Any kwds)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
JSON serializer implementation wrapper\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " None serializinghtml\&.jsonimpl\&.dump (Any obj, IO[str] | IO[bytes] file, *Any args, **Any kwds)"

.SS " str serializinghtml\&.jsonimpl\&.dumps (Any obj, *Any args, **Any kwds)"

.SS " Any serializinghtml\&.jsonimpl\&.load (*Any args, **Any kwds)"

.SS " Any serializinghtml\&.jsonimpl\&.loads (*Any args, **Any kwds)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
