.TH "serializinghtml.SerialisingImplementation" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serializinghtml.SerialisingImplementation
.SH SYNOPSIS
.br
.PP
.PP
Inherits Protocol\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fBdump\fP (self, Any obj, Any file, *Any args, **Any kwargs)"
.br
.ti -1c
.RI "str|bytes \fBdumps\fP (self, Any obj, *Any args, **Any kwargs)"
.br
.ti -1c
.RI "Any \fBload\fP (self, Any file, *Any args, **Any kwargs)"
.br
.ti -1c
.RI "Any \fBloads\fP (self, Any data, *Any args, **Any kwargs)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " None serializinghtml\&.SerialisingImplementation\&.dump ( self, Any obj, Any file, *Any args, **Any kwargs)"

.SS " str | bytes serializinghtml\&.SerialisingImplementation\&.dumps ( self, Any obj, *Any args, **Any kwargs)"

.SS " Any serializinghtml\&.SerialisingImplementation\&.load ( self, Any file, *Any args, **Any kwargs)"

.SS " Any serializinghtml\&.SerialisingImplementation\&.loads ( self, Any data, *Any args, **Any kwargs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
