.TH "/home/umar/Desktop/WorkShop/GLL/mksck/shim.c" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/mksck/shim.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmksck\fP (const char *restrict file, const char *mode, int re_use)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int mksck (const char *restrict file, const char * mode, int re_use)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
