.TH "snowballstemmer.greek_stemmer.GreekStemmer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snowballstemmer.greek_stemmer.GreekStemmer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcurrent\fP"
.br
.ti -1c
.RI "\fBket\fP"
.br
.ti -1c
.RI "\fBbra\fP"
.br
.ti -1c
.RI "\fBcursor\fP"
.br
.ti -1c
.RI "\fBB_test1\fP"
.br
.ti -1c
.RI "\fBlimit_backward\fP"
.br
.in -1c

Public Attributes inherited from \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP
.in +1c
.ti -1c
.RI "\fBcurrent\fP"
.br
.ti -1c
.RI "\fBcursor\fP"
.br
.ti -1c
.RI "\fBlimit\fP"
.br
.ti -1c
.RI "\fBlimit_backward\fP"
.br
.ti -1c
.RI "\fBbra\fP"
.br
.ti -1c
.RI "\fBket\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dict \fBg_v\fP = {u'α', u'ε', u'η', u'ι', u'ο', u'υ', u'ω'}"
.br
.ti -1c
.RI "dict \fBg_v2\fP = {u'α', u'ε', u'η', u'ι', u'ο', u'ω'}"
.br
.ti -1c
.RI "bool \fBB_test1\fP = False"
.br
.ti -1c
.RI "list \fBa_0\fP"
.br
.ti -1c
.RI "list \fBa_1\fP"
.br
.ti -1c
.RI "list \fBa_2\fP"
.br
.ti -1c
.RI "list \fBa_3\fP"
.br
.ti -1c
.RI "list \fBa_4\fP"
.br
.ti -1c
.RI "list \fBa_5\fP"
.br
.ti -1c
.RI "list \fBa_6\fP"
.br
.ti -1c
.RI "list \fBa_7\fP"
.br
.ti -1c
.RI "list \fBa_8\fP"
.br
.ti -1c
.RI "list \fBa_9\fP"
.br
.ti -1c
.RI "list \fBa_10\fP"
.br
.ti -1c
.RI "list \fBa_11\fP"
.br
.ti -1c
.RI "list \fBa_12\fP"
.br
.ti -1c
.RI "list \fBa_13\fP"
.br
.ti -1c
.RI "list \fBa_14\fP"
.br
.ti -1c
.RI "list \fBa_15\fP"
.br
.ti -1c
.RI "list \fBa_16\fP"
.br
.ti -1c
.RI "list \fBa_17\fP"
.br
.ti -1c
.RI "list \fBa_18\fP"
.br
.ti -1c
.RI "list \fBa_19\fP"
.br
.ti -1c
.RI "list \fBa_20\fP"
.br
.ti -1c
.RI "list \fBa_21\fP"
.br
.ti -1c
.RI "list \fBa_22\fP"
.br
.ti -1c
.RI "list \fBa_23\fP"
.br
.ti -1c
.RI "list \fBa_24\fP"
.br
.ti -1c
.RI "list \fBa_25\fP"
.br
.ti -1c
.RI "list \fBa_26\fP"
.br
.ti -1c
.RI "list \fBa_27\fP"
.br
.ti -1c
.RI "list \fBa_28\fP"
.br
.ti -1c
.RI "list \fBa_29\fP"
.br
.ti -1c
.RI "list \fBa_30\fP"
.br
.ti -1c
.RI "list \fBa_31\fP"
.br
.ti -1c
.RI "list \fBa_32\fP"
.br
.ti -1c
.RI "list \fBa_33\fP"
.br
.ti -1c
.RI "list \fBa_34\fP"
.br
.ti -1c
.RI "list \fBa_35\fP"
.br
.ti -1c
.RI "list \fBa_36\fP"
.br
.ti -1c
.RI "list \fBa_37\fP"
.br
.ti -1c
.RI "list \fBa_38\fP"
.br
.ti -1c
.RI "list \fBa_39\fP"
.br
.ti -1c
.RI "list \fBa_40\fP"
.br
.ti -1c
.RI "list \fBa_41\fP"
.br
.ti -1c
.RI "list \fBa_42\fP"
.br
.ti -1c
.RI "list \fBa_43\fP"
.br
.ti -1c
.RI "list \fBa_44\fP"
.br
.ti -1c
.RI "list \fBa_45\fP"
.br
.ti -1c
.RI "list \fBa_46\fP"
.br
.ti -1c
.RI "list \fBa_47\fP"
.br
.ti -1c
.RI "list \fBa_48\fP"
.br
.ti -1c
.RI "list \fBa_49\fP"
.br
.ti -1c
.RI "list \fBa_50\fP"
.br
.ti -1c
.RI "list \fBa_51\fP"
.br
.ti -1c
.RI "list \fBa_52\fP"
.br
.ti -1c
.RI "list \fBa_53\fP"
.br
.ti -1c
.RI "list \fBa_54\fP"
.br
.ti -1c
.RI "list \fBa_55\fP"
.br
.ti -1c
.RI "list \fBa_56\fP"
.br
.ti -1c
.RI "list \fBa_57\fP"
.br
.ti -1c
.RI "list \fBa_58\fP"
.br
.ti -1c
.RI "list \fBa_59\fP"
.br
.ti -1c
.RI "list \fBa_60\fP"
.br
.ti -1c
.RI "list \fBa_61\fP"
.br
.ti -1c
.RI "list \fBa_62\fP"
.br
.ti -1c
.RI "list \fBa_63\fP"
.br
.ti -1c
.RI "list \fBa_64\fP"
.br
.ti -1c
.RI "list \fBa_65\fP"
.br
.ti -1c
.RI "list \fBa_66\fP"
.br
.ti -1c
.RI "list \fBa_67\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_stem\fP (self)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBset_current\fP (self, value)"
.br
.ti -1c
.RI "\fBget_current\fP (self)"
.br
.ti -1c
.RI "\fBcopy_from\fP (self, other)"
.br
.ti -1c
.RI "\fBin_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_in_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBin_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_in_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBout_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_out_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBout_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_out_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBeq_s\fP (self, s)"
.br
.ti -1c
.RI "\fBeq_s_b\fP (self, s)"
.br
.ti -1c
.RI "\fBfind_among\fP (self, v)"
.br
.ti -1c
.RI "\fBfind_among_b\fP (self, v)"
.br
.ti -1c
.RI "\fBreplace_s\fP (self, c_bra, c_ket, s)"
.br
.ti -1c
.RI "\fBslice_check\fP (self)"
.br
.ti -1c
.RI "\fBslice_from\fP (self, s)"
.br
.ti -1c
.RI "\fBslice_del\fP (self)"
.br
.ti -1c
.RI "\fBinsert\fP (self, c_bra, c_ket, s)"
.br
.ti -1c
.RI "\fBslice_to\fP (self)"
.br
.ti -1c
.RI "\fBassign_to\fP (self)"
.br
.ti -1c
.RI "\fBstemWord\fP (self, word)"
.br
.ti -1c
.RI "\fBstemWords\fP (self, words)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class implements the stemming algorithm defined by a snowball script\&.
Generated from greek\&.sbl by Snowball 3\&.0\&.1 - https://snowballstem\&.org/

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "snowballstemmer\&.greek_stemmer\&.GreekStemmer\&._stem ( self)\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_0\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_1\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_10\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_11\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ιστα", \-1, 1),
        Among(u"ιστε", \-1, 1),
        Among(u"ιστη", \-1, 1),
        Among(u"ιστοι", \-1, 1),
        Among(u"ιστων", \-1, 1),
        Among(u"ιστο", \-1, 1),
        Among(u"ιστεσ", \-1, 1),
        Among(u"ιστησ", \-1, 1),
        Among(u"ιστοσ", \-1, 1),
        Among(u"ιστουσ", \-1, 1),
        Among(u"ιστου", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_12\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"εγκλε", \-1, 1),
        Among(u"αποκλε", \-1, 1),
        Among(u"δανε", \-1, 2),
        Among(u"αντιδανε", 2, 2),
        Among(u"σε", \-1, 1),
        Among(u"μετασε", 4, 1),
        Among(u"μικροσε", 4, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_13\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ατομικ", \-1, 2),
        Among(u"εθνικ", \-1, 4),
        Among(u"τοπικ", \-1, 7),
        Among(u"εκλεκτικ", \-1, 5),
        Among(u"σκεπτικ", \-1, 6),
        Among(u"γνωστικ", \-1, 3),
        Among(u"αγνωστικ", 5, 1),
        Among(u"αλεξανδριν", \-1, 8),
        Among(u"θεατριν", \-1, 10),
        Among(u"βυζαντιν", \-1, 9)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_14\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ισμοι", \-1, 1),
        Among(u"ισμων", \-1, 1),
        Among(u"ισμο", \-1, 1),
        Among(u"ισμοσ", \-1, 1),
        Among(u"ισμουσ", \-1, 1),
        Among(u"ισμου", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_15\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"σ", \-1, 1),
        Among(u"χ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_16\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ουδακια", \-1, 1),
        Among(u"αρακια", \-1, 1),
        Among(u"ουδακι", \-1, 1),
        Among(u"αρακι", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_17\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_18\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ακια", \-1, 1),
        Among(u"αρακια", 0, 1),
        Among(u"ιτσα", \-1, 1),
        Among(u"ακι", \-1, 1),
        Among(u"αρακι", 3, 1),
        Among(u"ιτσων", \-1, 1),
        Among(u"ιτσασ", \-1, 1),
        Among(u"ιτσεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_19\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ψαλ", \-1, 1),
        Among(u"αιφν", \-1, 1),
        Among(u"ολο", \-1, 1),
        Among(u"ιρ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_2\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_20\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ε", \-1, 1),
        Among(u"παιχν", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_21\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ιδια", \-1, 1),
        Among(u"ιδιων", \-1, 1),
        Among(u"ιδιο", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_22\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ιβ", \-1, 1),
        Among(u"δ", \-1, 1),
        Among(u"φραγκ", \-1, 1),
        Among(u"λυκ", \-1, 1),
        Among(u"οβελ", \-1, 1),
        Among(u"μην", \-1, 1),
        Among(u"ρ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_23\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ισκε", \-1, 1),
        Among(u"ισκο", \-1, 1),
        Among(u"ισκοσ", \-1, 1),
        Among(u"ισκου", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_24\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"αδων", \-1, 1),
        Among(u"αδεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_25\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"γιαγι", \-1, \-1),
        Among(u"θει", \-1, \-1),
        Among(u"οκ", \-1, \-1),
        Among(u"μαμ", \-1, \-1),
        Among(u"μαν", \-1, \-1),
        Among(u"μπαμπ", \-1, \-1),
        Among(u"πεθερ", \-1, \-1),
        Among(u"πατερ", \-1, \-1),
        Among(u"κυρ", \-1, \-1),
        Among(u"νταντ", \-1, \-1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_26\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"εδων", \-1, 1),
        Among(u"εδεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_27\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"μιλ", \-1, 1),
        Among(u"δαπ", \-1, 1),
        Among(u"γηπ", \-1, 1),
        Among(u"ιπ", \-1, 1),
        Among(u"εμπ", \-1, 1),
        Among(u"οπ", \-1, 1),
        Among(u"κρασπ", \-1, 1),
        Among(u"υπ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_28\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ουδων", \-1, 1),
        Among(u"ουδεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_29\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"τραγ", \-1, 1),
        Among(u"φε", \-1, 1),
        Among(u"καλιακ", \-1, 1),
        Among(u"αρκ", \-1, 1),
        Among(u"σκ", \-1, 1),
        Among(u"πεταλ", \-1, 1),
        Among(u"βελ", \-1, 1),
        Among(u"λουλ", \-1, 1),
        Among(u"φλ", \-1, 1),
        Among(u"χν", \-1, 1),
        Among(u"πλεξ", \-1, 1),
        Among(u"σπ", \-1, 1),
        Among(u"φρ", \-1, 1),
        Among(u"σ", \-1, 1),
        Among(u"λιχ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_3\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ιζα", \-1, 1),
        Among(u"ιζε", \-1, 1),
        Among(u"ιζαμε", \-1, 1),
        Among(u"ιζουμε", \-1, 1),
        Among(u"ιζανε", \-1, 1),
        Among(u"ιζουνε", \-1, 1),
        Among(u"ιζατε", \-1, 1),
        Among(u"ιζετε", \-1, 1),
        Among(u"ιζει", \-1, 1),
        Among(u"ιζαν", \-1, 1),
        Among(u"ιζουν", \-1, 1),
        Among(u"ιζεσ", \-1, 1),
        Among(u"ιζεισ", \-1, 1),
        Among(u"ιζω", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_30\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"εων", \-1, 1),
        Among(u"εωσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_31\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"δ", \-1, 1),
        Among(u"ιδ", 0, 1),
        Among(u"θ", \-1, 1),
        Among(u"γαλ", \-1, 1),
        Among(u"ελ", \-1, 1),
        Among(u"ν", \-1, 1),
        Among(u"π", \-1, 1),
        Among(u"παρ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_32\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ια", \-1, 1),
        Among(u"ιων", \-1, 1),
        Among(u"ιου", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_33\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ικα", \-1, 1),
        Among(u"ικων", \-1, 1),
        Among(u"ικο", \-1, 1),
        Among(u"ικου", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_34\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_35\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"αγαμε", \-1, 1),
        Among(u"ηκαμε", \-1, 1),
        Among(u"ηθηκαμε", 1, 1),
        Among(u"ησαμε", \-1, 1),
        Among(u"ουσαμε", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_36\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"βουβ", \-1, 1),
        Among(u"ξεθ", \-1, 1),
        Among(u"πεθ", \-1, 1),
        Among(u"αποθ", \-1, 1),
        Among(u"αποκ", \-1, 1),
        Among(u"ουλ", \-1, 1),
        Among(u"αναπ", \-1, 1),
        Among(u"πικρ", \-1, 1),
        Among(u"ποτ", \-1, 1),
        Among(u"αποστ", \-1, 1),
        Among(u"χ", \-1, 1),
        Among(u"σιχ", 10, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_37\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"τρ", \-1, 1),
        Among(u"τσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_38\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"αγανε", \-1, 1),
        Among(u"ηκανε", \-1, 1),
        Among(u"ηθηκανε", 1, 1),
        Among(u"ησανε", \-1, 1),
        Among(u"ουσανε", \-1, 1),
        Among(u"οντανε", \-1, 1),
        Among(u"ιοντανε", 5, 1),
        Among(u"ουντανε", \-1, 1),
        Among(u"ιουντανε", 7, 1),
        Among(u"οτανε", \-1, 1),
        Among(u"ιοτανε", 9, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_39\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_4\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"βι", \-1, 1),
        Among(u"λι", \-1, 1),
        Among(u"αλ", \-1, 1),
        Among(u"εν", \-1, 1),
        Among(u"σ", \-1, 1),
        Among(u"χ", \-1, 1),
        Among(u"υψ", \-1, 1),
        Among(u"ζω", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_40\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ησετε", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_41\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_42\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"παγ", \-1, 1),
        Among(u"δ", \-1, 1),
        Among(u"αδ", 1, 1),
        Among(u"θ", \-1, 1),
        Among(u"αθ", 3, 1),
        Among(u"τοκ", \-1, 1),
        Among(u"σκ", \-1, 1),
        Among(u"παρακαλ", \-1, 1),
        Among(u"σκελ", \-1, 1),
        Among(u"απλ", \-1, 1),
        Among(u"εμ", \-1, 1),
        Among(u"αν", \-1, 1),
        Among(u"βεν", \-1, 1),
        Among(u"βαρον", \-1, 1),
        Among(u"κοπ", \-1, 1),
        Among(u"σερπ", \-1, 1),
        Among(u"αβαρ", \-1, 1),
        Among(u"εναρ", \-1, 1),
        Among(u"αβρ", \-1, 1),
        Among(u"μπορ", \-1, 1),
        Among(u"θαρρ", \-1, 1),
        Among(u"ντρ", \-1, 1),
        Among(u"υ", \-1, 1),
        Among(u"νιφ", \-1, 1),
        Among(u"συρφ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_43\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"οντασ", \-1, 1),
        Among(u"ωντασ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_44\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ομαστε", \-1, 1),
        Among(u"ιομαστε", 0, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_45\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"π", \-1, 1),
        Among(u"απ", 0, 1),
        Among(u"ακαταπ", 1, 1),
        Among(u"συμπ", 0, 1),
        Among(u"ασυμπ", 3, 1),
        Among(u"αμεταμφ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_46\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ζ", \-1, 1),
        Among(u"αλ", \-1, 1),
        Among(u"παρακαλ", 1, 1),
        Among(u"εκτελ", \-1, 1),
        Among(u"μ", \-1, 1),
        Among(u"ξ", \-1, 1),
        Among(u"προ", \-1, 1),
        Among(u"αρ", \-1, 1),
        Among(u"νισ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_47\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ηθηκα", \-1, 1),
        Among(u"ηθηκε", \-1, 1),
        Among(u"ηθηκεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_48\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"πιθ", \-1, 1),
        Among(u"οθ", \-1, 1),
        Among(u"ναρθ", \-1, 1),
        Among(u"σκουλ", \-1, 1),
        Among(u"σκωλ", \-1, 1),
        Among(u"σφ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_49\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"θ", \-1, 1),
        Among(u"διαθ", 0, 1),
        Among(u"παρακαταθ", 0, 1),
        Among(u"συνθ", 0, 1),
        Among(u"προσθ", 0, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_5\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ωθηκα", \-1, 1),
        Among(u"ωθηκε", \-1, 1),
        Among(u"ωθηκαμε", \-1, 1),
        Among(u"ωθηκανε", \-1, 1),
        Among(u"ωθηκατε", \-1, 1),
        Among(u"ωθηκαν", \-1, 1),
        Among(u"ωθηκεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_50\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ηκα", \-1, 1),
        Among(u"ηκε", \-1, 1),
        Among(u"ηκεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_51\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"φαγ", \-1, 1),
        Among(u"ληγ", \-1, 1),
        Among(u"φρυδ", \-1, 1),
        Among(u"μαντιλ", \-1, 1),
        Among(u"μαλλ", \-1, 1),
        Among(u"ομ", \-1, 1),
        Among(u"βλεπ", \-1, 1),
        Among(u"ποδαρ", \-1, 1),
        Among(u"κυματ", \-1, 1),
        Among(u"πρωτ", \-1, 1),
        Among(u"λαχ", \-1, 1),
        Among(u"πανταχ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_52\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"τσα", \-1, 1),
        Among(u"χαδ", \-1, 1),
        Among(u"μεδ", \-1, 1),
        Among(u"λαμπιδ", \-1, 1),
        Among(u"δε", \-1, 1),
        Among(u"πλε", \-1, 1),
        Among(u"μεσαζ", \-1, 1),
        Among(u"δεσποζ", \-1, 1),
        Among(u"αιθ", \-1, 1),
        Among(u"φαρμακ", \-1, 1),
        Among(u"αγκ", \-1, 1),
        Among(u"ανηκ", \-1, 1),
        Among(u"λ", \-1, 1),
        Among(u"μ", \-1, 1),
        Among(u"αμ", 13, 1),
        Among(u"βρομ", 13, 1),
        Among(u"υποτειν", \-1, 1),
        Among(u"εκλιπ", \-1, 1),
        Among(u"ρ", \-1, 1),
        Among(u"ενδιαφερ", 18, 1),
        Among(u"αναρρ", 18, 1),
        Among(u"πατ", \-1, 1),
        Among(u"καθαρευ", \-1, 1),
        Among(u"δευτερευ", \-1, 1),
        Among(u"λεχ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_53\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ουσα", \-1, 1),
        Among(u"ουσε", \-1, 1),
        Among(u"ουσεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_54\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"πελ", \-1, 1),
        Among(u"λλ", \-1, 1),
        Among(u"σμην", \-1, 1),
        Among(u"ρπ", \-1, 1),
        Among(u"πρ", \-1, 1),
        Among(u"φρ", \-1, 1),
        Among(u"χορτ", \-1, 1),
        Among(u"οφ", \-1, 1),
        Among(u"ψοφ", 7, \-1),
        Among(u"σφ", \-1, 1),
        Among(u"λοχ", \-1, 1),
        Among(u"ναυλοχ", 10, \-1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_55\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_56\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"αγα", \-1, 1),
        Among(u"αγε", \-1, 1),
        Among(u"αγεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_57\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ησα", \-1, 1),
        Among(u"ησε", \-1, 1),
        Among(u"ησου", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_58\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ν", \-1, 1),
        Among(u"δωδεκαν", 0, 1),
        Among(u"επταν", 0, 1),
        Among(u"μεγαλον", 0, 1),
        Among(u"ερημον", 0, 1),
        Among(u"χερσον", 0, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_59\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ηστε", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_6\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_60\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"σβ", \-1, 1),
        Among(u"ασβ", 0, 1),
        Among(u"απλ", \-1, 1),
        Among(u"αειμν", \-1, 1),
        Among(u"χρ", \-1, 1),
        Among(u"αχρ", 4, 1),
        Among(u"κοινοχρ", 4, 1),
        Among(u"δυσχρ", 4, 1),
        Among(u"ευχρ", 4, 1),
        Among(u"παλιμψ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_61\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ουνε", \-1, 1),
        Among(u"ηθουνε", 0, 1),
        Among(u"ησουνε", 0, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_62\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"σπι", \-1, 1),
        Among(u"ν", \-1, 1),
        Among(u"εξων", 1, 1),
        Among(u"ρ", \-1, 1),
        Among(u"στραβομουτσ", \-1, 1),
        Among(u"κακομουτσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_63\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ουμε", \-1, 1),
        Among(u"ηθουμε", 0, 1),
        Among(u"ησουμε", 0, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_64\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"αζ", \-1, 1),
        Among(u"ωριοπλ", \-1, 1),
        Among(u"ασουσ", \-1, 1),
        Among(u"παρασουσ", 2, 1),
        Among(u"αλλοσουσ", \-1, 1),
        Among(u"φ", \-1, 1),
        Among(u"χ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_65\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ματα", \-1, 1),
        Among(u"ματων", \-1, 1),
        Among(u"ματοσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_66\fC [static]\fP"

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_67\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"οτερ", \-1, 1),
        Among(u"εστερ", \-1, 1),
        Among(u"υτερ", \-1, 1),
        Among(u"ωτερ", \-1, 1),
        Among(u"οτατ", \-1, 1),
        Among(u"εστατ", \-1, 1),
        Among(u"υτατ", \-1, 1),
        Among(u"ωτατ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_7\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ισα", \-1, 1),
        Among(u"ισαμε", \-1, 1),
        Among(u"ισανε", \-1, 1),
        Among(u"ισε", \-1, 1),
        Among(u"ισατε", \-1, 1),
        Among(u"ισαν", \-1, 1),
        Among(u"ισεσ", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_8\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ξαναπα", \-1, 1),
        Among(u"επα", \-1, 1),
        Among(u"περιπα", \-1, 1),
        Among(u"αναμπα", \-1, 1),
        Among(u"εμπα", \-1, 1),
        Among(u"χαρτοπα", \-1, 1),
        Among(u"εξαρχα", \-1, 1),
        Among(u"κλε", \-1, 1),
        Among(u"εκλε", 7, 1),
        Among(u"απεκλε", 8, 1),
        Among(u"αποκλε", 7, 1),
        Among(u"εσωκλε", 7, 1),
        Among(u"δανε", \-1, 1),
        Among(u"πε", \-1, 1),
        Among(u"επε", 13, 1),
        Among(u"μετεπε", 14, 1),
        Among(u"εσε", \-1, 1),
        Among(u"αθρο", \-1, 1),
        Among(u"συναθρο", 17, 1)
    ]
.fi

.SS "list snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.a_9\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"ισουμε", \-1, 1),
        Among(u"ισουνε", \-1, 1),
        Among(u"ισετε", \-1, 1),
        Among(u"ισει", \-1, 1),
        Among(u"ισουν", \-1, 1),
        Among(u"ισεισ", \-1, 1),
        Among(u"ισω", \-1, 1)
    ]
.fi

.SS "bool snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.B_test1 = False\fC [static]\fP"

.SS "snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.B_test1"

.SS "snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.bra"

.SS "snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.current"

.SS "snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.cursor"

.SS "dict snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.g_v = {u'α', u'ε', u'η', u'ι', u'ο', u'υ', u'ω'}\fC [static]\fP"

.SS "dict snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.g_v2 = {u'α', u'ε', u'η', u'ι', u'ο', u'ω'}\fC [static]\fP"

.SS "snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.ket"

.SS "snowballstemmer\&.greek_stemmer\&.GreekStemmer\&.limit_backward"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
