.TH "snowballstemmer.irish_stemmer.IrishStemmer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snowballstemmer.irish_stemmer.IrishStemmer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBI_pV\fP"
.br
.ti -1c
.RI "\fBI_p1\fP"
.br
.ti -1c
.RI "\fBI_p2\fP"
.br
.ti -1c
.RI "\fBcursor\fP"
.br
.ti -1c
.RI "\fBbra\fP"
.br
.ti -1c
.RI "\fBket\fP"
.br
.ti -1c
.RI "\fBlimit_backward\fP"
.br
.in -1c

Public Attributes inherited from \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP
.in +1c
.ti -1c
.RI "\fBcurrent\fP"
.br
.ti -1c
.RI "\fBcursor\fP"
.br
.ti -1c
.RI "\fBlimit\fP"
.br
.ti -1c
.RI "\fBlimit_backward\fP"
.br
.ti -1c
.RI "\fBbra\fP"
.br
.ti -1c
.RI "\fBket\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dict \fBg_v\fP = {u'a', u'e', u'i', u'o', u'u', u'á', u'é', u'í', u'ó', u'ú'}"
.br
.ti -1c
.RI "int \fBI_p2\fP = 0"
.br
.ti -1c
.RI "int \fBI_p1\fP = 0"
.br
.ti -1c
.RI "int \fBI_pV\fP = 0"
.br
.ti -1c
.RI "list \fBa_0\fP"
.br
.ti -1c
.RI "list \fBa_1\fP"
.br
.ti -1c
.RI "list \fBa_2\fP"
.br
.ti -1c
.RI "list \fBa_3\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_stem\fP (self)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBset_current\fP (self, value)"
.br
.ti -1c
.RI "\fBget_current\fP (self)"
.br
.ti -1c
.RI "\fBcopy_from\fP (self, other)"
.br
.ti -1c
.RI "\fBin_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_in_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBin_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_in_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBout_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_out_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBout_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_out_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBeq_s\fP (self, s)"
.br
.ti -1c
.RI "\fBeq_s_b\fP (self, s)"
.br
.ti -1c
.RI "\fBfind_among\fP (self, v)"
.br
.ti -1c
.RI "\fBfind_among_b\fP (self, v)"
.br
.ti -1c
.RI "\fBreplace_s\fP (self, c_bra, c_ket, s)"
.br
.ti -1c
.RI "\fBslice_check\fP (self)"
.br
.ti -1c
.RI "\fBslice_from\fP (self, s)"
.br
.ti -1c
.RI "\fBslice_del\fP (self)"
.br
.ti -1c
.RI "\fBinsert\fP (self, c_bra, c_ket, s)"
.br
.ti -1c
.RI "\fBslice_to\fP (self)"
.br
.ti -1c
.RI "\fBassign_to\fP (self)"
.br
.ti -1c
.RI "\fBstemWord\fP (self, word)"
.br
.ti -1c
.RI "\fBstemWords\fP (self, words)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class implements the stemming algorithm defined by a snowball script\&.
Generated from irish\&.sbl by Snowball 3\&.0\&.1 - https://snowballstem\&.org/

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "snowballstemmer\&.irish_stemmer\&.IrishStemmer\&._stem ( self)\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "list snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.a_0\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"b'", \-1, 1),
        Among(u"bh", \-1, 4),
        Among(u"bhf", 1, 2),
        Among(u"bp", \-1, 8),
        Among(u"ch", \-1, 5),
        Among(u"d'", \-1, 1),
        Among(u"d'fh", 5, 2),
        Among(u"dh", \-1, 6),
        Among(u"dt", \-1, 9),
        Among(u"fh", \-1, 2),
        Among(u"gc", \-1, 5),
        Among(u"gh", \-1, 7),
        Among(u"h\-", \-1, 1),
        Among(u"m'", \-1, 1),
        Among(u"mb", \-1, 4),
        Among(u"mh", \-1, 10),
        Among(u"n\-", \-1, 1),
        Among(u"nd", \-1, 6),
        Among(u"ng", \-1, 7),
        Among(u"ph", \-1, 8),
        Among(u"sh", \-1, 3),
        Among(u"t\-", \-1, 1),
        Among(u"th", \-1, 9),
        Among(u"ts", \-1, 3)
    ]
.fi

.SS "list snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.a_1\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"íochta", \-1, 1),
        Among(u"aíochta", 0, 1),
        Among(u"ire", \-1, 2),
        Among(u"aire", 2, 2),
        Among(u"abh", \-1, 1),
        Among(u"eabh", 4, 1),
        Among(u"ibh", \-1, 1),
        Among(u"aibh", 6, 1),
        Among(u"amh", \-1, 1),
        Among(u"eamh", 8, 1),
        Among(u"imh", \-1, 1),
        Among(u"aimh", 10, 1),
        Among(u"íocht", \-1, 1),
        Among(u"aíocht", 12, 1),
        Among(u"irí", \-1, 2),
        Among(u"airí", 14, 2)
    ]
.fi

.SS "list snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.a_2\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"óideacha", \-1, 6),
        Among(u"patacha", \-1, 5),
        Among(u"achta", \-1, 1),
        Among(u"arcachta", 2, 2),
        Among(u"eachta", 2, 1),
        Among(u"grafaíochta", \-1, 4),
        Among(u"paite", \-1, 5),
        Among(u"ach", \-1, 1),
        Among(u"each", 7, 1),
        Among(u"óideach", 8, 6),
        Among(u"gineach", 8, 3),
        Among(u"patach", 7, 5),
        Among(u"grafaíoch", \-1, 4),
        Among(u"pataigh", \-1, 5),
        Among(u"óidigh", \-1, 6),
        Among(u"achtúil", \-1, 1),
        Among(u"eachtúil", 15, 1),
        Among(u"gineas", \-1, 3),
        Among(u"ginis", \-1, 3),
        Among(u"acht", \-1, 1),
        Among(u"arcacht", 19, 2),
        Among(u"eacht", 19, 1),
        Among(u"grafaíocht", \-1, 4),
        Among(u"arcachtaí", \-1, 2),
        Among(u"grafaíochtaí", \-1, 4)
    ]
.fi

.SS "list snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.a_3\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"imid", \-1, 1),
        Among(u"aimid", 0, 1),
        Among(u"ímid", \-1, 1),
        Among(u"aímid", 2, 1),
        Among(u"adh", \-1, 2),
        Among(u"eadh", 4, 2),
        Among(u"faidh", \-1, 1),
        Among(u"fidh", \-1, 1),
        Among(u"áil", \-1, 2),
        Among(u"ain", \-1, 2),
        Among(u"tear", \-1, 2),
        Among(u"tar", \-1, 2)
    ]
.fi

.SS "snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.bra"

.SS "snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.cursor"

.SS "dict snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.g_v = {u'a', u'e', u'i', u'o', u'u', u'á', u'é', u'í', u'ó', u'ú'}\fC [static]\fP"

.SS "int snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.I_p1 = 0\fC [static]\fP"

.SS "snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.I_p1"

.SS "int snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.I_p2 = 0\fC [static]\fP"

.SS "snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.I_p2"

.SS "int snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.I_pV = 0\fC [static]\fP"

.SS "snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.I_pV"

.SS "snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.ket"

.SS "snowballstemmer\&.irish_stemmer\&.IrishStemmer\&.limit_backward"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
