.TH "snowballstemmer.indonesian_stemmer.IndonesianStemmer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snowballstemmer.indonesian_stemmer.IndonesianStemmer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBket\fP"
.br
.ti -1c
.RI "\fBbra\fP"
.br
.ti -1c
.RI "\fBI_prefix\fP"
.br
.ti -1c
.RI "\fBcursor\fP"
.br
.ti -1c
.RI "\fBI_measure\fP"
.br
.ti -1c
.RI "\fBlimit_backward\fP"
.br
.in -1c

Public Attributes inherited from \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP
.in +1c
.ti -1c
.RI "\fBcurrent\fP"
.br
.ti -1c
.RI "\fBcursor\fP"
.br
.ti -1c
.RI "\fBlimit\fP"
.br
.ti -1c
.RI "\fBlimit_backward\fP"
.br
.ti -1c
.RI "\fBbra\fP"
.br
.ti -1c
.RI "\fBket\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dict \fBg_vowel\fP = {u'a', u'e', u'i', u'o', u'u'}"
.br
.ti -1c
.RI "int \fBI_prefix\fP = 0"
.br
.ti -1c
.RI "int \fBI_measure\fP = 0"
.br
.ti -1c
.RI "list \fBa_0\fP"
.br
.ti -1c
.RI "list \fBa_1\fP"
.br
.ti -1c
.RI "list \fBa_2\fP"
.br
.ti -1c
.RI "list \fBa_3\fP"
.br
.ti -1c
.RI "list \fBa_4\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_stem\fP (self)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBsnowballstemmer\&.basestemmer\&.BaseStemmer\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBset_current\fP (self, value)"
.br
.ti -1c
.RI "\fBget_current\fP (self)"
.br
.ti -1c
.RI "\fBcopy_from\fP (self, other)"
.br
.ti -1c
.RI "\fBin_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_in_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBin_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_in_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBout_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_out_grouping\fP (self, s)"
.br
.ti -1c
.RI "\fBout_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBgo_out_grouping_b\fP (self, s)"
.br
.ti -1c
.RI "\fBeq_s\fP (self, s)"
.br
.ti -1c
.RI "\fBeq_s_b\fP (self, s)"
.br
.ti -1c
.RI "\fBfind_among\fP (self, v)"
.br
.ti -1c
.RI "\fBfind_among_b\fP (self, v)"
.br
.ti -1c
.RI "\fBreplace_s\fP (self, c_bra, c_ket, s)"
.br
.ti -1c
.RI "\fBslice_check\fP (self)"
.br
.ti -1c
.RI "\fBslice_from\fP (self, s)"
.br
.ti -1c
.RI "\fBslice_del\fP (self)"
.br
.ti -1c
.RI "\fBinsert\fP (self, c_bra, c_ket, s)"
.br
.ti -1c
.RI "\fBslice_to\fP (self)"
.br
.ti -1c
.RI "\fBassign_to\fP (self)"
.br
.ti -1c
.RI "\fBstemWord\fP (self, word)"
.br
.ti -1c
.RI "\fBstemWords\fP (self, words)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class implements the stemming algorithm defined by a snowball script\&.
Generated from indonesian\&.sbl by Snowball 3\&.0\&.1 - https://snowballstem\&.org/

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&._stem ( self)\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "list snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.a_0\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"kah", \-1, 1),
        Among(u"lah", \-1, 1),
        Among(u"pun", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.a_1\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"nya", \-1, 1),
        Among(u"ku", \-1, 1),
        Among(u"mu", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.a_2\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"i", \-1, 1, __r_SUFFIX_I_OK),
        Among(u"an", \-1, 1, __r_SUFFIX_AN_OK),
        Among(u"kan", 1, 1, __r_SUFFIX_KAN_OK)
    ]
.fi

.SS "list snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.a_3\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"di", \-1, 1),
        Among(u"ke", \-1, 2),
        Among(u"me", \-1, 1),
        Among(u"mem", 2, 5),
        Among(u"men", 2, 1),
        Among(u"meng", 4, 1),
        Among(u"meny", 4, 3, __r_VOWEL),
        Among(u"pem", \-1, 6),
        Among(u"pen", \-1, 2),
        Among(u"peng", 8, 2),
        Among(u"peny", 8, 4, __r_VOWEL),
        Among(u"ter", \-1, 1)
    ]
.fi

.SS "list snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.a_4\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        Among(u"be", \-1, 3, __r_KER),
        Among(u"belajar", 0, 4),
        Among(u"ber", 0, 3),
        Among(u"pe", \-1, 1),
        Among(u"pelajar", 3, 2),
        Among(u"per", 3, 1)
    ]
.fi

.SS "snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.bra"

.SS "snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.cursor"

.SS "dict snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.g_vowel = {u'a', u'e', u'i', u'o', u'u'}\fC [static]\fP"

.SS "int snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.I_measure = 0\fC [static]\fP"

.SS "snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.I_measure"

.SS "int snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.I_prefix = 0\fC [static]\fP"

.SS "snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.I_prefix"

.SS "snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.ket"

.SS "snowballstemmer\&.indonesian_stemmer\&.IndonesianStemmer\&.limit_backward"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
