.TH "soupsieve.css_match.SoupSieve" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soupsieve.css_match.SoupSieve
.SH SYNOPSIS
.br
.PP
.PP
Inherits ct\&.Immutable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, str \fBpattern\fP, ct\&.SelectorList \fBselectors\fP, ct\&.Namespaces|None \fBnamespaces\fP, ct\&.CustomSelectors|None \fBcustom\fP, int \fBflags\fP)"
.br
.ti -1c
.RI "bool \fBmatch\fP (self, \fBbs4\&.Tag\fP tag)"
.br
.ti -1c
.RI "\fBbs4\&.Tag\fP|None \fBclosest\fP (self, \fBbs4\&.Tag\fP tag)"
.br
.ti -1c
.RI "list[\fBbs4\&.Tag\fP] \fBfilter\fP (self, Iterable[\fBbs4\&.Tag\fP] iterable)"
.br
.ti -1c
.RI "\fBbs4\&.Tag\fP|None \fBselect_one\fP (self, \fBbs4\&.Tag\fP tag)"
.br
.ti -1c
.RI "list[\fBbs4\&.Tag\fP] \fBselect\fP (self, \fBbs4\&.Tag\fP tag, int limit=0)"
.br
.ti -1c
.RI "Iterator[\fBbs4\&.Tag\fP] \fBiselect\fP (self, \fBbs4\&.Tag\fP tag, int limit=0)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBselectors\fP"
.br
.ti -1c
.RI "\fBnamespaces\fP"
.br
.ti -1c
.RI "\fBflags\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBpattern\fP"
.br
.ti -1c
.RI "ct \fBselectors\fP \&.SelectorList"
.br
.ti -1c
.RI "ct \fBnamespaces\fP \&.Namespaces | None"
.br
.ti -1c
.RI "dict \fBcustom\fP [str, str]"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Compiled Soup Sieve selector matching object\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "soupsieve\&.css_match\&.SoupSieve\&.__init__ ( self, str pattern, ct\&.SelectorList selectors, ct\&.Namespaces | None namespaces, ct\&.CustomSelectors | None custom, int
     flags)"

.PP
.nf
Initialize\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str soupsieve\&.css_match\&.SoupSieve\&.__repr__ ( self)"

.PP
.nf
Representation\&.
.fi
.PP
 
.SS " \fBbs4\&.Tag\fP | None soupsieve\&.css_match\&.SoupSieve\&.closest ( self, \fBbs4\&.Tag\fP tag)"

.PP
.nf
Match closest ancestor\&.
.fi
.PP
 
.SS " list[\fBbs4\&.Tag\fP] soupsieve\&.css_match\&.SoupSieve\&.filter ( self, Iterable[\fBbs4\&.Tag\fP] iterable)"

.PP
.nf
Filter\&.

`CSSMatch` can cache certain searches for tags of the same document,
so if we are given a tag, all tags are from the same document,
and we can take advantage of the optimization\&.

Any other kind of iterable could have tags from different documents or detached tags,
so for those, we use a new `CSSMatch` for each item in the iterable\&.

.fi
.PP
 
.SS " Iterator[\fBbs4\&.Tag\fP] soupsieve\&.css_match\&.SoupSieve\&.iselect ( self, \fBbs4\&.Tag\fP tag, int  limit = \fC0\fP)"

.PP
.nf
Iterate the specified tags\&.
.fi
.PP
 
.SS " bool soupsieve\&.css_match\&.SoupSieve\&.match ( self, \fBbs4\&.Tag\fP tag)"

.PP
.nf
Match\&.
.fi
.PP
 
.SS " list[\fBbs4\&.Tag\fP] soupsieve\&.css_match\&.SoupSieve\&.select ( self, \fBbs4\&.Tag\fP tag, int  limit = \fC0\fP)"

.PP
.nf
Select the specified tags\&.
.fi
.PP
 
.SS " \fBbs4\&.Tag\fP | None soupsieve\&.css_match\&.SoupSieve\&.select_one ( self, \fBbs4\&.Tag\fP tag)"

.PP
.nf
Select a single tag\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "dict soupsieve\&.css_match\&.SoupSieve\&.custom [str, str]\fC [static]\fP"

.SS "int soupsieve\&.css_match\&.SoupSieve\&.flags\fC [static]\fP"

.SS "soupsieve\&.css_match\&.SoupSieve\&.flags"

.SS "ct soupsieve\&.css_match\&.SoupSieve\&.namespaces \&.Namespaces | None\fC [static]\fP"

.SS "soupsieve\&.css_match\&.SoupSieve\&.namespaces"

.SS "str soupsieve\&.css_match\&.SoupSieve\&.pattern\fC [static]\fP"

.SS "ct soupsieve\&.css_match\&.SoupSieve\&.selectors \&.SelectorList\fC [static]\fP"

.SS "soupsieve\&.css_match\&.SoupSieve\&.selectors"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
