.TH "soupsieve.css_types" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soupsieve.css_types
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomSelectors\fP"
.br
.ti -1c
.RI "class \fBImmutable\fP"
.br
.ti -1c
.RI "class \fBImmutableDict\fP"
.br
.ti -1c
.RI "class \fBNamespaces\fP"
.br
.ti -1c
.RI "class \fBSelector\fP"
.br
.ti -1c
.RI "class \fBSelectorAttribute\fP"
.br
.ti -1c
.RI "class \fBSelectorContains\fP"
.br
.ti -1c
.RI "class \fBSelectorLang\fP"
.br
.ti -1c
.RI "class \fBSelectorList\fP"
.br
.ti -1c
.RI "class \fBSelectorNth\fP"
.br
.ti -1c
.RI "class \fBSelectorNull\fP"
.br
.ti -1c
.RI "class \fBSelectorTag\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Any \fB_pickle\fP (Any p)"
.br
.ti -1c
.RI "None \fBpickle_register\fP (Any obj)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBSEL_EMPTY\fP = 0x1"
.br
.ti -1c
.RI "int \fBSEL_ROOT\fP = 0x2"
.br
.ti -1c
.RI "int \fBSEL_DEFAULT\fP = 0x4"
.br
.ti -1c
.RI "int \fBSEL_INDETERMINATE\fP = 0x8"
.br
.ti -1c
.RI "int \fBSEL_SCOPE\fP = 0x10"
.br
.ti -1c
.RI "int \fBSEL_DIR_LTR\fP = 0x20"
.br
.ti -1c
.RI "int \fBSEL_DIR_RTL\fP = 0x40"
.br
.ti -1c
.RI "int \fBSEL_IN_RANGE\fP = 0x80"
.br
.ti -1c
.RI "int \fBSEL_OUT_OF_RANGE\fP = 0x100"
.br
.ti -1c
.RI "int \fBSEL_DEFINED\fP = 0x200"
.br
.ti -1c
.RI "int \fBSEL_PLACEHOLDER_SHOWN\fP = 0x400"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
CSS selector structure items\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " Any soupsieve\&.css_types\&._pickle (Any p)\fC [protected]\fP"

.SS " None soupsieve\&.css_types\&.pickle_register (Any obj)"

.PP
.nf
Allow object to be pickled\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "int soupsieve\&.css_types\&.SEL_DEFAULT = 0x4"

.SS "int soupsieve\&.css_types\&.SEL_DEFINED = 0x200"

.SS "int soupsieve\&.css_types\&.SEL_DIR_LTR = 0x20"

.SS "int soupsieve\&.css_types\&.SEL_DIR_RTL = 0x40"

.SS "int soupsieve\&.css_types\&.SEL_EMPTY = 0x1"

.SS "int soupsieve\&.css_types\&.SEL_IN_RANGE = 0x80"

.SS "int soupsieve\&.css_types\&.SEL_INDETERMINATE = 0x8"

.SS "int soupsieve\&.css_types\&.SEL_OUT_OF_RANGE = 0x100"

.SS "int soupsieve\&.css_types\&.SEL_PLACEHOLDER_SHOWN = 0x400"

.SS "int soupsieve\&.css_types\&.SEL_ROOT = 0x2"

.SS "int soupsieve\&.css_types\&.SEL_SCOPE = 0x10"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
