.TH "soupsieve.pretty" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soupsieve.pretty
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBpretty\fP (Any obj)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRE_CLASS\fP = re\&.compile(r'(?i)[a\-z_][_a\-z\\d\\\&.]+\\(')"
.br
.ti -1c
.RI "\fBRE_PARAM\fP = re\&.compile(r'(?i)[_a\-z][_a\-z\\d]+=')"
.br
.ti -1c
.RI "\fBRE_EMPTY\fP = re\&.compile(r'\\(\\)|\\[\\]|\\{\\}')"
.br
.ti -1c
.RI "\fBRE_LSTRT\fP = re\&.compile(r'\\[')"
.br
.ti -1c
.RI "\fBRE_DSTRT\fP = re\&.compile(r'\\{')"
.br
.ti -1c
.RI "\fBRE_TSTRT\fP = re\&.compile(r'\\(')"
.br
.ti -1c
.RI "\fBRE_LEND\fP = re\&.compile(r'\\]')"
.br
.ti -1c
.RI "\fBRE_DEND\fP = re\&.compile(r'\\}')"
.br
.ti -1c
.RI "\fBRE_TEND\fP = re\&.compile(r'\\)')"
.br
.ti -1c
.RI "\fBRE_INT\fP = re\&.compile(r'\\d+')"
.br
.ti -1c
.RI "\fBRE_KWORD\fP = re\&.compile(r'(?i)[_a\-z][_a\-z\\d]+')"
.br
.ti -1c
.RI "\fBRE_DQSTR\fP = re\&.compile(r''(?:\\\\\&.|[^'\\\\])*'')"
.br
.ti -1c
.RI "\fBRE_SQSTR\fP = re\&.compile(r''(?:\\\\\&.|[^'\\\\])*'')"
.br
.ti -1c
.RI "\fBRE_SEP\fP = re\&.compile(r'\\s*(,)\\s*')"
.br
.ti -1c
.RI "\fBRE_DSEP\fP = re\&.compile(r'\\s*(:)\\s*')"
.br
.ti -1c
.RI "dict \fBTOKENS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Format a pretty string of a `SoupSieve` object for easy debugging\&.

This won't necessarily support all types and such, and definitely
not support custom outputs\&.

It is mainly geared towards our types as the `SelectorList`
object is a beast to look at without some indentation and newlines\&.
The format and various output types is fairly known (though it
hasn't been tested extensively to make sure we aren't missing corners)\&.

Example:
-------
```
>>> import soupsieve as sv
>>> sv\&.compile('this > that\&.class[name=value]')\&.selectors\&.pretty()
SelectorList(
    selectors=(
        Selector(
            tag=SelectorTag(
                name='that',
                prefix=None),
            ids=(),
            classes=(
                'class',
                ),
            attributes=(
                SelectorAttribute(
                    attribute='name',
                    prefix='',
                    pattern=re\&.compile(
                        '^value$'),
                    xml_type_pattern=None),
                ),
            nth=(),
            selectors=(),
            relation=SelectorList(
                selectors=(
                    Selector(
                        tag=SelectorTag(
                            name='this',
                            prefix=None),
                        ids=(),
                        classes=(),
                        attributes=(),
                        nth=(),
                        selectors=(),
                        relation=SelectorList(
                            selectors=(),
                            is_not=False,
                            is_html=False),
                        rel_type='>',
                        contains=(),
                        lang=(),
                        flags=0),
                    ),
                is_not=False,
                is_html=False),
            rel_type=None,
            contains=(),
            lang=(),
            flags=0),
        ),
    is_not=False,
    is_html=False)
```
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str soupsieve\&.pretty\&.pretty (Any obj)"

.PP
.nf
Make the object output string pretty\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "soupsieve\&.pretty\&.RE_CLASS = re\&.compile(r'(?i)[a\-z_][_a\-z\\d\\\&.]+\\(')"

.SS "soupsieve\&.pretty\&.RE_DEND = re\&.compile(r'\\}')"

.SS "soupsieve\&.pretty\&.RE_DQSTR = re\&.compile(r''(?:\\\\\&.|[^'\\\\])*'')"

.SS "soupsieve\&.pretty\&.RE_DSEP = re\&.compile(r'\\s*(:)\\s*')"

.SS "soupsieve\&.pretty\&.RE_DSTRT = re\&.compile(r'\\{')"

.SS "soupsieve\&.pretty\&.RE_EMPTY = re\&.compile(r'\\(\\)|\\[\\]|\\{\\}')"

.SS "soupsieve\&.pretty\&.RE_INT = re\&.compile(r'\\d+')"

.SS "soupsieve\&.pretty\&.RE_KWORD = re\&.compile(r'(?i)[_a\-z][_a\-z\\d]+')"

.SS "soupsieve\&.pretty\&.RE_LEND = re\&.compile(r'\\]')"

.SS "soupsieve\&.pretty\&.RE_LSTRT = re\&.compile(r'\\[')"

.SS "soupsieve\&.pretty\&.RE_PARAM = re\&.compile(r'(?i)[_a\-z][_a\-z\\d]+=')"

.SS "soupsieve\&.pretty\&.RE_SEP = re\&.compile(r'\\s*(,)\\s*')"

.SS "soupsieve\&.pretty\&.RE_SQSTR = re\&.compile(r''(?:\\\\\&.|[^'\\\\])*'')"

.SS "soupsieve\&.pretty\&.RE_TEND = re\&.compile(r'\\)')"

.SS "soupsieve\&.pretty\&.RE_TSTRT = re\&.compile(r'\\(')"

.SS "dict soupsieve\&.pretty\&.TOKENS"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'class': RE_CLASS,
3     'param': RE_PARAM,
4     'empty': RE_EMPTY,
5     'lstrt': RE_LSTRT,
6     'dstrt': RE_DSTRT,
7     'tstrt': RE_TSTRT,
8     'lend': RE_LEND,
9     'dend': RE_DEND,
10     'tend': RE_TEND,
11     'sqstr': RE_SQSTR,
12     'sep': RE_SEP,
13     'dsep': RE_DSEP,
14     'int': RE_INT,
15     'kword': RE_KWORD,
16     'dqstr': RE_DQSTR
17 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
