.TH "soupsieve.css_parser.SelectorPattern" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soupsieve.css_parser.SelectorPattern
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsoupsieve\&.css_parser\&.SpecialPseudoPattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBname\fP, str pattern)"
.br
.ti -1c
.RI "str \fBget_name\fP (self)"
.br
.ti -1c
.RI "Match[str]|None \fBmatch\fP (self, str selector, int index, int flags)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBre_pattern\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Selector pattern\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None soupsieve\&.css_parser\&.SelectorPattern\&.__init__ ( self, str name, str pattern)"

.PP
.nf
Initialize\&.
.fi
.PP
 
.PP
Reimplemented in \fBsoupsieve\&.css_parser\&.SpecialPseudoPattern\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " str soupsieve\&.css_parser\&.SelectorPattern\&.get_name ( self)"

.PP
.nf
Get name\&.
.fi
.PP
 
.PP
Reimplemented in \fBsoupsieve\&.css_parser\&.SpecialPseudoPattern\fP\&.
.SS " Match[str] | None soupsieve\&.css_parser\&.SelectorPattern\&.match ( self, str selector, int index, int flags)"

.PP
.nf
Match the selector\&.
.fi
.PP
 
.PP
Reimplemented in \fBsoupsieve\&.css_parser\&.SpecialPseudoPattern\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "soupsieve\&.css_parser\&.SelectorPattern\&.name"

.SS "soupsieve\&.css_parser\&.SelectorPattern\&.re_pattern"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
