.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/index/sources.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_internal/index/sources.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._internal\&.index\&.sources\&.LinkSource\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.index\&.sources\&._FlatDirectoryToUrls\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.index\&.sources\&._FlatDirectorySource\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.index\&.sources\&._LocalFileSource\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.index\&.sources\&._RemoteFileSource\fP"
.br
.ti -1c
.RI "class \fBpip\&._internal\&.index\&.sources\&._IndexDirectorySource\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.index\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._internal\&.index\&.sources\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBpip\&._internal\&.index\&.sources\&._is_html_file\fP (str file_url)"
.br
.ti -1c
.RI "Tuple[Optional[str], Optional[\fBLinkSource\fP]] \fBpip\&._internal\&.index\&.sources\&.build_source\fP (str location, *\fBCandidatesFromPage\fP candidates_from_page, \fBPageValidator\fP page_validator, bool expand_dir, bool cache_link_parsing, str project_name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._internal\&.index\&.sources\&.logger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fBpip\&._internal\&.index\&.sources\&.FoundCandidates\fP = Iterable[\fBInstallationCandidate\fP]"
.br
.ti -1c
.RI "\fBpip\&._internal\&.index\&.sources\&.FoundLinks\fP = Iterable[\fBLink\fP]"
.br
.ti -1c
.RI "\fBpip\&._internal\&.index\&.sources\&.CandidatesFromPage\fP = Callable[[\fBLink\fP], Iterable[\fBInstallationCandidate\fP]]"
.br
.ti -1c
.RI "\fBpip\&._internal\&.index\&.sources\&.PageValidator\fP = Callable[[\fBLink\fP], bool]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
