.TH "sphinx.pycode.parser.Token" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.pycode.parser.Token
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, int \fBkind\fP, Any \fBvalue\fP, tuple[int, int] \fBstart\fP, tuple[int, int] \fBend\fP, str \fBsource\fP)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, object other)"
.br
.ti -1c
.RI "int \fB__hash__\fP (self)"
.br
.ti -1c
.RI "bool \fBmatch\fP (self, *Any conditions)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBkind\fP"
.br
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBstart\fP"
.br
.ti -1c
.RI "\fBend\fP"
.br
.ti -1c
.RI "\fBsource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Better token wrapper for tokenize module\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.pycode\&.parser\&.Token\&.__init__ ( self, int kind, Any value, tuple[int, int] start, tuple[int, int] end, str source)"

.SH "Member Function Documentation"
.PP 
.SS " bool sphinx\&.pycode\&.parser\&.Token\&.__eq__ ( self, object other)"

.SS " int sphinx\&.pycode\&.parser\&.Token\&.__hash__ ( self)"

.SS " str sphinx\&.pycode\&.parser\&.Token\&.__repr__ ( self)"

.SS " bool sphinx\&.pycode\&.parser\&.Token\&.match ( self, *Any conditions)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.pycode\&.parser\&.Token\&.end"

.SS "sphinx\&.pycode\&.parser\&.Token\&.kind"

.SS "sphinx\&.pycode\&.parser\&.Token\&.source"

.SS "sphinx\&.pycode\&.parser\&.Token\&.start"

.SS "sphinx\&.pycode\&.parser\&.Token\&.value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
