.TH "sphinx.builders.linkcheck.HyperlinkAvailabilityChecker" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders.linkcheck.HyperlinkAvailabilityChecker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBConfig\fP \fBconfig\fP)"
.br
.ti -1c
.RI "Iterator[\fBCheckResult\fP] \fBcheck\fP (self, dict[str, \fBHyperlink\fP] hyperlinks)"
.br
.ti -1c
.RI "None \fBinvoke_threads\fP (self)"
.br
.ti -1c
.RI "None \fBshutdown_threads\fP (self)"
.br
.ti -1c
.RI "bool \fBis_ignored_uri\fP (self, str uri)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBnum_workers\fP"
.br
.ti -1c
.RI "\fBrqueue\fP"
.br
.ti -1c
.RI "\fBwqueue\fP"
.br
.ti -1c
.RI "\fBto_ignore\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.__init__ ( self, \fBConfig\fP config)"

.SH "Member Function Documentation"
.PP 
.SS " Iterator[\fBCheckResult\fP] sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.check ( self, dict[str, \fBHyperlink\fP] hyperlinks)"

.SS " None sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.invoke_threads ( self)"

.SS " bool sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.is_ignored_uri ( self, str uri)"

.SS " None sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.shutdown_threads ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.config"

.SS "sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.num_workers"

.SS "sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.rqueue"

.SS "sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.to_ignore"

.SS "sphinx\&.builders\&.linkcheck\&.HyperlinkAvailabilityChecker\&.wqueue"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
