.TH "sphinx.util.logging.OnceFilter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.logging.OnceFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits logging\&.Filter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str name='')"
.br
.ti -1c
.RI "bool \fBfilter\fP (self, logging\&.LogRecord record)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Show the message only once\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.util\&.logging\&.OnceFilter\&.__init__ ( self, str  name = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS " bool sphinx\&.util\&.logging\&.OnceFilter\&.filter ( self, logging\&.LogRecord record)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
