.TH "sphinx.config._Opt" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.config._Opt
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, Any \fBdefault\fP, \fB_ConfigRebuild\fP \fBrebuild\fP, _OptValidTypes \fBvalid_types\fP, str \fBdescription\fP='')"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, object other)"
.br
.ti -1c
.RI "bool \fB__lt__\fP (self, \fB_Opt\fP other)"
.br
.ti -1c
.RI "int \fB__hash__\fP (self)"
.br
.ti -1c
.RI "None \fB__setattr__\fP (self, str key, Any value)"
.br
.ti -1c
.RI "None \fB__delattr__\fP (self, str key)"
.br
.ti -1c
.RI "tuple[Any, \fB_ConfigRebuild\fP, _OptValidTypes, str] \fB__getstate__\fP (self)"
.br
.ti -1c
.RI "None \fB__setstate__\fP (self, tuple[Any, \fB_ConfigRebuild\fP, _OptValidTypes, str] state)"
.br
.ti -1c
.RI "Any \fB__getitem__\fP (self, int|slice item)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdefault\fP"
.br
.ti -1c
.RI "\fBrebuild\fP"
.br
.ti -1c
.RI "\fBvalid_types\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "Any \fBdefault\fP"
.br
.ti -1c
.RI "\fB_ConfigRebuild\fP \fBrebuild\fP"
.br
.ti -1c
.RI "_OptValidTypes \fBvalid_types\fP"
.br
.ti -1c
.RI "str \fBdescription\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.config\&._Opt\&.__init__ ( self, Any default, \fB_ConfigRebuild\fP rebuild, _OptValidTypes valid_types, str  description = \fC''\fP)"

.PP
.nf
Configuration option type for Sphinx\&.

The type is intended to be immutable; changing the field values
is an unsupported action\&.
No validation is performed on the values, though consumers will
likely expect them to be of the types advertised\&.
The old tuple-based interface will be removed in Sphinx 9\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.config\&._Opt\&.__delattr__ ( self, str key)"

.SS " bool sphinx\&.config\&._Opt\&.__eq__ ( self, object other)"

.SS " Any sphinx\&.config\&._Opt\&.__getitem__ ( self, int | slice item)"

.SS " tuple[Any, \fB_ConfigRebuild\fP, _OptValidTypes, str] sphinx\&.config\&._Opt\&.__getstate__ ( self)"

.SS " int sphinx\&.config\&._Opt\&.__hash__ ( self)"

.SS " bool sphinx\&.config\&._Opt\&.__lt__ ( self, \fB_Opt\fP other)"

.SS " str sphinx\&.config\&._Opt\&.__repr__ ( self)"

.SS " None sphinx\&.config\&._Opt\&.__setattr__ ( self, str key, Any value)"

.SS " None sphinx\&.config\&._Opt\&.__setstate__ ( self, tuple[Any, \fB_ConfigRebuild\fP, _OptValidTypes, str]
     state)"

.SH "Member Data Documentation"
.PP 
.SS "Any sphinx\&.config\&._Opt\&.default\fC [static]\fP"

.SS "sphinx\&.config\&._Opt\&.default"

.SS "str sphinx\&.config\&._Opt\&.description\fC [static]\fP"

.SS "sphinx\&.config\&._Opt\&.description"

.SS "\fB_ConfigRebuild\fP sphinx\&.config\&._Opt\&.rebuild\fC [static]\fP"

.SS "sphinx\&.config\&._Opt\&.rebuild"

.SS "_OptValidTypes sphinx\&.config\&._Opt\&.valid_types\fC [static]\fP"

.SS "sphinx\&.config\&._Opt\&.valid_types"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
