.TH "sphinx.domains.c._ast.ASTTrailingTypeSpecName" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.domains.c._ast.ASTTrailingTypeSpecName
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpec\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBprefix\fP, \fBASTNestedName\fP \fBnestedName\fP)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, object other)"
.br
.ti -1c
.RI "int \fB__hash__\fP (self)"
.br
.ti -1c
.RI "\fBASTNestedName\fP \fBname\fP (self)"
.br
.ti -1c
.RI "None \fBdescribe_signature\fP (self, \fBTextElement\fP signode, str mode, \fBBuildEnvironment\fP env, \fBSymbol\fP symbol)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP
.in +1c
.ti -1c
.RI "Any \fBclone\fP (self)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "str \fBget_display_string\fP (self)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBnestedName\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_stringify\fP (self, StringifyTransform transform)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpecName\&.__init__ ( self, str prefix, \fBASTNestedName\fP nestedName)"

.SH "Member Function Documentation"
.PP 
.SS " bool sphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpecName\&.__eq__ ( self, object other)"

.PP
Reimplemented from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS " int sphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpecName\&.__hash__ ( self)"

.PP
Reimplemented from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS " str sphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpecName\&._stringify ( self, StringifyTransform transform)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS " None sphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpecName\&.describe_signature ( self, \fBTextElement\fP signode, str mode, \fBBuildEnvironment\fP env, \fBSymbol\fP
     symbol)"

.PP
Reimplemented from \fBsphinx\&.domains\&.c\&._ast\&.ASTBase\fP\&.
.SS " \fBASTNestedName\fP sphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpecName\&.name ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpecName\&.nestedName"

.SS "sphinx\&.domains\&.c\&._ast\&.ASTTrailingTypeSpecName\&.prefix"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
