.TH "sphinx.util.template" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.template
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseRenderer\fP"
.br
.ti -1c
.RI "class \fBFileRenderer\fP"
.br
.ti -1c
.RI "class \fBLaTeXRenderer\fP"
.br
.ti -1c
.RI "class \fBReSTRenderer\fP"
.br
.ti -1c
.RI "class \fBSphinxRenderer\fP"
.br
.ti -1c
.RI "class \fBSphinxTemplateLoader\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fB_TEMPLATES_PATH\fP = package_dir / 'templates'"
.br
.ti -1c
.RI "str \fB_LATEX_TEMPLATES_PATH\fP = \fB_TEMPLATES_PATH\fP / 'latex'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Templates utility functions for Sphinx\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "str sphinx\&.util\&.template\&._LATEX_TEMPLATES_PATH = \fB_TEMPLATES_PATH\fP / 'latex'\fC [protected]\fP"

.SS "str sphinx\&.util\&.template\&._TEMPLATES_PATH = package_dir / 'templates'\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
