.TH "sphinx.writers" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBhtml\fP"
.br
.ti -1c
.RI "namespace \fBhtml5\fP"
.br
.ti -1c
.RI "namespace \fBlatex\fP"
.br
.ti -1c
.RI "namespace \fBmanpage\fP"
.br
.ti -1c
.RI "namespace \fBtexinfo\fP"
.br
.ti -1c
.RI "namespace \fBtext\fP"
.br
.ti -1c
.RI "namespace \fBxml\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Custom docutils writers\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
