.TH "sphinx.ext.githubpages" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.githubpages
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fB_get_domain_from_url\fP (str url)"
.br
.ti -1c
.RI "None \fBcreate_nojekyll_and_cname\fP (\fBSphinx\fP app, \fBBuildEnvironment\fP env)"
.br
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
To publish HTML docs at GitHub Pages, create \&.nojekyll file\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str sphinx\&.ext\&.githubpages\&._get_domain_from_url (str url)\fC [protected]\fP"

.PP
.nf
Get the domain from a URL\&.
.fi
.PP
 
.SS " None sphinx\&.ext\&.githubpages\&.create_nojekyll_and_cname (\fBSphinx\fP app, \fBBuildEnvironment\fP env)"

.PP
.nf
Manage the ``\&.nojekyll`` and ``CNAME`` files for GitHub Pages\&.

For HTML-format builders (e\&.g\&. 'html', 'dirhtml') we unconditionally create
the ``\&.nojekyll`` file to signal that GitHub Pages should not run Jekyll
processing\&.

If the :confval:`html_baseurl` option is set, we also create a CNAME file
with the domain from ``html_baseurl``, so long as it is not a ``github\&.io``
domain\&.

If this extension is loaded and the domain in ``html_baseurl`` no longer
requires a CNAME file, we remove any existing ``CNAME`` files from the
output directory\&.

.fi
.PP
 
.SS " \fBExtensionMetadata\fP sphinx\&.ext\&.githubpages\&.setup (\fBSphinx\fP app)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
