.TH "sphinx.util._lines" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util._lines
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "list[int] \fBparse_line_num_spec\fP (str spec, int total)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " list[int] sphinx\&.util\&._lines\&.parse_line_num_spec (str spec, int total)"

.PP
.nf
Parse a line number spec (such as '1,2,4-6') and return a list of
wanted line numbers\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
