.TH "sphinx.util.inspect._SupportsSet" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.inspect._SupportsSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits Protocol\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__set__\fP (self, Any instance, Any value)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.util\&.inspect\&._SupportsSet\&.__set__ ( self, Any instance, Any value)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
