.TH "sphinx.writers.text" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers.text
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCell\fP"
.br
.ti -1c
.RI "class \fBTable\fP"
.br
.ti -1c
.RI "class \fBTextTranslator\fP"
.br
.ti -1c
.RI "class \fBTextWrapper\fP"
.br
.ti -1c
.RI "class \fBTextWriter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "list[str] \fBmy_wrap\fP (str text, int width=\fBMAXWIDTH\fP, **Any kwargs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBMAXWIDTH\fP = 70"
.br
.ti -1c
.RI "int \fBSTDINDENT\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Custom docutils writer for plain text\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " list[str] sphinx\&.writers\&.text\&.my_wrap (str text, int  width = \fC\fBMAXWIDTH\fP\fP, **Any kwargs)"

.SH "Variable Documentation"
.PP 
.SS "int sphinx\&.writers\&.text\&.MAXWIDTH = 70"

.SS "int sphinx\&.writers\&.text\&.STDINDENT = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
