.TH "sphinx.util.typing.ExtensionMetadata" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.typing.ExtensionMetadata
.SH SYNOPSIS
.br
.PP
.PP
Inherits typing\&.TypedDict, total, and False\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBversion\fP"
.br
.ti -1c
.RI "int \fBenv_version\fP"
.br
.ti -1c
.RI "bool \fBparallel_read_safe\fP"
.br
.ti -1c
.RI "bool \fBparallel_write_safe\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The metadata returned by an extension's ``setup()`` function\&.

See :ref:`ext-metadata`\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int sphinx\&.util\&.typing\&.ExtensionMetadata\&.env_version\fC [static]\fP"

.SS "bool sphinx\&.util\&.typing\&.ExtensionMetadata\&.parallel_read_safe\fC [static]\fP"

.SS "bool sphinx\&.util\&.typing\&.ExtensionMetadata\&.parallel_write_safe\fC [static]\fP"

.SS "str sphinx\&.util\&.typing\&.ExtensionMetadata\&.version\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
