.TH "sphinx.util._pathlib._StrPathProperty" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util._pathlib._StrPathProperty
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self)"
.br
.ti -1c
.RI "None \fB__set_name__\fP (self, object owner, str name)"
.br
.ti -1c
.RI "\fB_StrPathProperty\fP \fB__get__\fP (self, None obj, None objtype)"
.br
.ti -1c
.RI "\fB_StrPath\fP \fB__get__\fP (self, object obj, type[object] objtype)"
.br
.ti -1c
.RI "\fB_StrPathProperty\fP|\fB_StrPath\fP \fB__get__\fP (self, object|None obj, type[object]|None objtype=None)"
.br
.ti -1c
.RI "None \fB__set__\fP (self, Any obj, \fB_StrPath\fP|Path value)"
.br
.ti -1c
.RI "None \fB__delete__\fP (self, Any obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBinstance_attr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.util\&._pathlib\&._StrPathProperty\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.util\&._pathlib\&._StrPathProperty\&.__delete__ ( self, Any obj)"

.SS " \fB_StrPathProperty\fP sphinx\&.util\&._pathlib\&._StrPathProperty\&.__get__ ( self, None obj, None objtype)"

.SS " \fB_StrPath\fP sphinx\&.util\&._pathlib\&._StrPathProperty\&.__get__ ( self, object obj, type[object] objtype)"

.SS " \fB_StrPathProperty\fP | \fB_StrPath\fP sphinx\&.util\&._pathlib\&._StrPathProperty\&.__get__ ( self, object | None obj, type[object] | None  objtype = \fCNone\fP)"

.SS " None sphinx\&.util\&._pathlib\&._StrPathProperty\&.__set__ ( self, Any obj, \fB_StrPath\fP | Path value)"

.SS " None sphinx\&.util\&._pathlib\&._StrPathProperty\&.__set_name__ ( self, object owner, str name)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.util\&._pathlib\&._StrPathProperty\&.instance_attr"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
