.TH "sphinx.util._uri" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util._uri
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBencode_uri\fP (str uri)"
.br
.ti -1c
.RI "bool \fBis_url\fP (str url)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " str sphinx\&.util\&._uri\&.encode_uri (str uri)"

.SS " bool sphinx\&.util\&._uri\&.is_url (str url)"

.PP
.nf
Check *url* is URL or not\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
