.TH "sphinx.builders._epub_base.Spine" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders._epub_base.Spine
.SH SYNOPSIS
.br
.PP
.PP
Inherits NamedTuple\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBidref\fP"
.br
.ti -1c
.RI "bool \fBlinear\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "str sphinx\&.builders\&._epub_base\&.Spine\&.idref\fC [static]\fP"

.SS "bool sphinx\&.builders\&._epub_base\&.Spine\&.linear\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
