.TH "sphinx.domains.changeset" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.domains.changeset
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChangeSet\fP"
.br
.ti -1c
.RI "class \fBChangeSetDomain\fP"
.br
.ti -1c
.RI "class \fBVersionChange\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBversionlabels\fP"
.br
.ti -1c
.RI "dict \fBversionlabel_classes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The changeset domain\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fBExtensionMetadata\fP sphinx\&.domains\&.changeset\&.setup (\fBSphinx\fP app)"

.SH "Variable Documentation"
.PP 
.SS "dict sphinx\&.domains\&.changeset\&.versionlabel_classes"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'versionadded': 'added',
3     'versionchanged': 'changed',
4     'deprecated': 'deprecated',
5     'versionremoved': 'removed',
6 }
.fi

.SS "dict sphinx\&.domains\&.changeset\&.versionlabels"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'versionadded': _('Added in version %s'),
3     'versionchanged': _('Changed in version %s'),
4     'deprecated': _('Deprecated since version %s'),
5     'versionremoved': _('Removed in version %s'),
6 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
