.TH "sphinx.builders.dirhtml" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders.dirhtml
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectoryHTMLBuilder\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Directory HTML builders\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fBExtensionMetadata\fP sphinx\&.builders\&.dirhtml\&.setup (\fBSphinx\fP app)"

.SH "Variable Documentation"
.PP 
.SS "sphinx\&.builders\&.dirhtml\&.logger = logging\&.getLogger(__name__)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
