.TH "sphinx.addnodes.only" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.addnodes.only
.SH SYNOPSIS
.br
.PP
.PP
Inherits nodes\&.Element\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Node for 'only' directives (conditional inclusion based on tags)\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
