.TH "sphinx.ext.inheritance_diagram.InheritanceException" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.inheritance_diagram.InheritanceException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
