.TH "sphinx.ext.apidoc._cli" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.apidoc._cli
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "argparse\&.ArgumentParser \fBget_parser\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (Sequence[str] argv=())"
.br
.ti -1c
.RI "\fBApidocOptions\fP \fB_parse_args\fP (Sequence[str] argv)"
.br
.ti -1c
.RI "None \fB_full_quickstart\fP (\fBApidocOptions\fP opts, *list[str] modules)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " None sphinx\&.ext\&.apidoc\&._cli\&._full_quickstart (\fBApidocOptions\fP opts, *list[str] modules)\fC [protected]\fP"

.SS " \fBApidocOptions\fP sphinx\&.ext\&.apidoc\&._cli\&._parse_args (Sequence[str] argv)\fC [protected]\fP"

.SS " argparse\&.ArgumentParser sphinx\&.ext\&.apidoc\&._cli\&.get_parser ()"

.SS " int sphinx\&.ext\&.apidoc\&._cli\&.main (Sequence[str]  argv = \fC()\fP)"

.PP
.nf
Run the apidoc CLI\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
