.TH "sphinx.writers.manpage.ManualPageTranslator" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers.manpage.ManualPageTranslator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP, and BaseTranslator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, nodes\&.document document, \fBBuilder\fP \fBbuilder\fP)"
.br
.ti -1c
.RI "str \fBheader\fP (self)"
.br
.ti -1c
.RI "None \fBvisit_start_of_file\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_start_of_file\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc\fP (self, \fBElement\fP node)"
.br
.RI "Domain-specific object descriptions\&. "
.ti -1c
.RI "None \fBdepart_desc\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_signature\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_signature\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_signature_line\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_signature_line\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_content\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_content\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_name\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_name\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_addname\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_addname\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_type\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_type\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_returns\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_returns\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_parameterlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_parameterlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_type_parameter_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_type_parameter_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_type_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_type_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_optional\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_optional\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_annotation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_annotation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_versionmodified\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_versionmodified\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_term\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_comment\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_footnote\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_rubric\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_rubric\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_seealso\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_seealso\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_productionlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_productionlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_production\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_production\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_image\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_number_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_centered\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_centered\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_compact_paragraph\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_compact_paragraph\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_download_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_download_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_toctree\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_index\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_tabular_col_spec\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_glossary\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_glossary\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_acks\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_hlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_hlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_hlistcol\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_hlistcol\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_literal_emphasis\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_literal_emphasis\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_literal_strong\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_literal_strong\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_abbreviation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_abbreviation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_manpage\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_manpage\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_caption\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_caption\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_title\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_title\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_raw\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_meta\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_math\fP (self, nodes\&.math node)"
.br
.ti -1c
.RI "None \fBdepart_math\fP (self, nodes\&.math node)"
.br
.ti -1c
.RI "None \fBvisit_math_block\fP (self, nodes\&.math_block node)"
.br
.ti -1c
.RI "None \fBdepart_math_block\fP (self, nodes\&.math_block node)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP
.in +1c
.ti -1c
.RI "None \fBdispatch_visit\fP (self, \fBNode\fP node)"
.br
.ti -1c
.RI "None \fBdispatch_departure\fP (self, \fBNode\fP node)"
.br
.ti -1c
.RI "None \fBunknown_visit\fP (self, \fBNode\fP node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsection_level\fP"
.br
.ti -1c
.RI "\fBfirst_param\fP"
.br
.in -1c

Public Attributes inherited from \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP
.in +1c
.ti -1c
.RI "\fBbuilder\fP"
.br
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBsettings\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "dict \fB_docinfo\fP = {}"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP
.in +1c
.ti -1c
.RI "\fB_domains\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Custom man page translator\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.__init__ ( self, nodes\&.document document, \fBBuilder\fP builder)"

.PP
Reimplemented from \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_abbreviation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_caption ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_centered ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_compact_paragraph ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_addname ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_annotation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_content ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_inline ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_name ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_optional ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_parameter ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_parameterlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_returns ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_signature ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_signature_line ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_type ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_type_parameter ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_desc_type_parameter_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_download_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_glossary ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_hlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_hlistcol ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_inline ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_literal_emphasis ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_literal_strong ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_manpage ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_math ( self, nodes\&.math node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_math_block ( self, nodes\&.math_block node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_production ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_productionlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_rubric ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_seealso ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_start_of_file ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_title ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.depart_versionmodified ( self, \fBElement\fP node)"

.SS " str sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.header ( self)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_abbreviation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_acks ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_caption ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_centered ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_comment ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_compact_paragraph ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc ( self, \fBElement\fP node)"

.PP
Domain-specific object descriptions\&. 
.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_addname ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_annotation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_content ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_inline ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_name ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_optional ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_parameter ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_parameterlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_returns ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_signature ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_signature_line ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_type ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_type_parameter ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_desc_type_parameter_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_download_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_footnote ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_glossary ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_hlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_hlistcol ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_image ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_index ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_inline ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_literal_emphasis ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_literal_strong ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_manpage ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_math ( self, nodes\&.math node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_math_block ( self, nodes\&.math_block node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_meta ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_number_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_production ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_productionlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_raw ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_rubric ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_seealso ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_start_of_file ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_tabular_col_spec ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_term ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_title ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_toctree ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.visit_versionmodified ( self, \fBElement\fP node)"

.SH "Member Data Documentation"
.PP 
.SS "dict sphinx\&.writers\&.manpage\&.ManualPageTranslator\&._docinfo = {}\fC [static]\fP, \fC [protected]\fP"

.SS "sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.first_param"

.SS "sphinx\&.writers\&.manpage\&.ManualPageTranslator\&.section_level"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
