.TH "sphinx.ext.napoleon.docstring.Deque" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.napoleon.docstring.Deque
.SH SYNOPSIS
.br
.PP
.PP
Inherits collections\&.deque, and Any\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Any \fBget\fP (self, int n)"
.br
.ti -1c
.RI "Any \fBnext\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsentinel\fP = object()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A subclass of deque that mimics ``pockets\&.iterators\&.modify_iter``\&.

The `\&.Deque\&.get` and `\&.Deque\&.next` methods are added\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " Any sphinx\&.ext\&.napoleon\&.docstring\&.Deque\&.get ( self, int n)"

.PP
.nf
Return the nth element of the stack, or ``self\&.sentinel`` if n is
greater than the stack size\&.

.fi
.PP
 
.SS " Any sphinx\&.ext\&.napoleon\&.docstring\&.Deque\&.next ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.ext\&.napoleon\&.docstring\&.Deque\&.sentinel = object()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
