.TH "sphinx.ext.duration._DurationDomainData" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.duration._DurationDomainData
.SH SYNOPSIS
.br
.PP
.PP
Inherits TypedDict\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dict \fBreading_durations\fP [str, float]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "dict sphinx\&.ext\&.duration\&._DurationDomainData\&.reading_durations [str, float]\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
