.TH "sphinx.ext.viewcode" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.viewcode
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBviewcode_anchor\fP"
.br
.ti -1c
.RI "class \fBViewcodeAnchorTransform\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str|None \fB_get_full_modname\fP (str modname, str attribute)"
.br
.ti -1c
.RI "bool \fBis_supported_builder\fP (\fBBuilder\fP builder)"
.br
.ti -1c
.RI "None \fBdoctree_read\fP (\fBSphinx\fP app, \fBNode\fP doctree)"
.br
.ti -1c
.RI "None \fBenv_merge_info\fP (\fBSphinx\fP app, \fBBuildEnvironment\fP env, Set[str] docnames, \fBBuildEnvironment\fP other)"
.br
.ti -1c
.RI "None \fBenv_purge_doc\fP (\fBSphinx\fP app, \fBBuildEnvironment\fP env, str docname)"
.br
.ti -1c
.RI "\fB_StrPath\fP|None \fBget_module_filename\fP (\fBSphinx\fP app, str modname)"
.br
.ti -1c
.RI "bool \fBshould_generate_module_page\fP (\fBSphinx\fP app, str modname)"
.br
.ti -1c
.RI "Iterator[tuple[str, dict[str, Any], str]] \fBcollect_pages\fP (\fBSphinx\fP app)"
.br
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "str \fBOUTPUT_DIRNAME\fP = '_modules'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Add links to module code in Python object descriptions\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str | None sphinx\&.ext\&.viewcode\&._get_full_modname (str modname, str attribute)\fC [protected]\fP"

.SS " Iterator[tuple[str, dict[str, Any], str]] sphinx\&.ext\&.viewcode\&.collect_pages (\fBSphinx\fP app)"

.SS " None sphinx\&.ext\&.viewcode\&.doctree_read (\fBSphinx\fP app, \fBNode\fP doctree)"

.SS " None sphinx\&.ext\&.viewcode\&.env_merge_info (\fBSphinx\fP app, \fBBuildEnvironment\fP env, Set[str] docnames, \fBBuildEnvironment\fP
 other)"

.SS " None sphinx\&.ext\&.viewcode\&.env_purge_doc (\fBSphinx\fP app, \fBBuildEnvironment\fP env, str docname)"

.SS " \fB_StrPath\fP | None sphinx\&.ext\&.viewcode\&.get_module_filename (\fBSphinx\fP app, str modname)"

.PP
.nf
Get module filename for *modname*\&.
.fi
.PP
 
.SS " bool sphinx\&.ext\&.viewcode\&.is_supported_builder (\fBBuilder\fP builder)"

.SS " \fBExtensionMetadata\fP sphinx\&.ext\&.viewcode\&.setup (\fBSphinx\fP app)"

.SS " bool sphinx\&.ext\&.viewcode\&.should_generate_module_page (\fBSphinx\fP app, str modname)"

.PP
.nf
Check generation of module page is needed\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "sphinx\&.ext\&.viewcode\&.logger = logging\&.getLogger(__name__)"

.SS "str sphinx\&.ext\&.viewcode\&.OUTPUT_DIRNAME = '_modules'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
