.TH "sphinx.util.inspect._SupportsGet" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.inspect._SupportsGet
.SH SYNOPSIS
.br
.PP
.PP
Inherits Protocol\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Any \fB__get__\fP (self, Any instance, type|None owner=\&.\&.\&.)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " Any sphinx\&.util\&.inspect\&._SupportsGet\&.__get__ ( self, Any instance, type | None  owner = \fC\&.\&.\&.\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
