.TH "sphinx.ext.autosummary.ImportExceptionGroup" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.autosummary.ImportExceptionGroup
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str|None message, Sequence[BaseException] \fBexceptions\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBexceptions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Exceptions raised during importing the target objects\&.

It contains an error messages and a list of exceptions as its arguments\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.ext\&.autosummary\&.ImportExceptionGroup\&.__init__ ( self, str | None message, Sequence[BaseException]
     exceptions)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.ext\&.autosummary\&.ImportExceptionGroup\&.exceptions"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
