.TH "sphinx.ext.intersphinx._load._InvConfig" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.intersphinx._load._InvConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_InvConfig\fP \fBfrom_config\fP (cls, \fBConfig\fP config)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBintersphinx_cache_limit\fP"
.br
.ti -1c
.RI "int \fBintersphinx_timeout\fP | float | None"
.br
.ti -1c
.RI "bool \fBtls_verify\fP"
.br
.ti -1c
.RI "str \fBtls_cacerts\fP | dict[str, str] | None"
.br
.ti -1c
.RI "str \fBuser_agent\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " \fB_InvConfig\fP sphinx\&.ext\&.intersphinx\&._load\&._InvConfig\&.from_config ( cls, \fBConfig\fP config)"

.SH "Member Data Documentation"
.PP 
.SS "int sphinx\&.ext\&.intersphinx\&._load\&._InvConfig\&.intersphinx_cache_limit\fC [static]\fP"

.SS "int sphinx\&.ext\&.intersphinx\&._load\&._InvConfig\&.intersphinx_timeout | float | None\fC [static]\fP"

.SS "str sphinx\&.ext\&.intersphinx\&._load\&._InvConfig\&.tls_cacerts | dict[str, str] | None\fC [static]\fP"

.SS "bool sphinx\&.ext\&.intersphinx\&._load\&._InvConfig\&.tls_verify\fC [static]\fP"

.SS "str sphinx\&.ext\&.intersphinx\&._load\&._InvConfig\&.user_agent\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
