.TH "sphinx.search.fr" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.search.fr
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSearchFrench\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfrench_stopwords\fP = parse_stop_word()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
French search language: includes the JS French stemmer\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "sphinx\&.search\&.fr\&.french_stopwords = parse_stop_word()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
