.TH "sphinx.util.logging._RaiseOnWarningFilter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.logging._RaiseOnWarningFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits logging\&.Filter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "NoReturn \fBfilter\fP (self, logging\&.LogRecord record)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raise exception if a warning is emitted\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " NoReturn sphinx\&.util\&.logging\&._RaiseOnWarningFilter\&.filter ( self, logging\&.LogRecord record)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
