.TH "sphinx.util.parallel.SerialTasks" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.parallel.SerialTasks
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, int nproc=1)"
.br
.ti -1c
.RI "None \fBadd_task\fP (self, Callable[[Any], Any]|Callable[[], Any] task_func, Any arg=None, Callable[[Any], Any]|None result_func=None)"
.br
.ti -1c
.RI "None \fBjoin\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Has the same interface as ParallelTasks, but executes tasks directly\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.util\&.parallel\&.SerialTasks\&.__init__ ( self, int  nproc = \fC1\fP)"

.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.util\&.parallel\&.SerialTasks\&.add_task ( self, Callable[[Any], Any] | Callable[[], Any] task_func, Any  arg = \fCNone\fP, Callable[[Any], Any] | None  result_func = \fCNone\fP)"

.SS " None sphinx\&.util\&.parallel\&.SerialTasks\&.join ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
