.TH "sphinx.environment.collectors.asset.DownloadFileCollector" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.environment.collectors.asset.DownloadFileCollector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.environment\&.collectors\&.EnvironmentCollector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fBclear_doc\fP (self, \fBSphinx\fP app, \fBBuildEnvironment\fP env, str docname)"
.br
.ti -1c
.RI "None \fBmerge_other\fP (self, \fBSphinx\fP app, \fBBuildEnvironment\fP env, Set[str] docnames, \fBBuildEnvironment\fP other)"
.br
.ti -1c
.RI "None \fBprocess_doc\fP (self, \fBSphinx\fP app, nodes\&.document doctree)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.environment\&.collectors\&.EnvironmentCollector\fP
.in +1c
.ti -1c
.RI "None \fBenable\fP (self, \fBSphinx\fP app)"
.br
.ti -1c
.RI "None \fBdisable\fP (self, \fBSphinx\fP app)"
.br
.ti -1c
.RI "list[str] \fBget_updated_docs\fP (self, \fBSphinx\fP app, \fBBuildEnvironment\fP env)"
.br
.ti -1c
.RI "list[str] \fBget_outdated_docs\fP (self, \fBSphinx\fP app, \fBBuildEnvironment\fP env, set[str] added, set[str] changed, set[str] removed)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBsphinx\&.environment\&.collectors\&.EnvironmentCollector\fP
.in +1c
.ti -1c
.RI "\fBlistener_ids\fP"
.br
.ti -1c
.RI "\fBget_updated_docs\fP"
.br
.ti -1c
.RI "\fBget_outdated_docs\fP"
.br
.in -1c

Static Public Attributes inherited from \fBsphinx\&.environment\&.collectors\&.EnvironmentCollector\fP
.in +1c
.ti -1c
.RI "dict \fBlistener_ids\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Download files collector for sphinx\&.environment\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.environment\&.collectors\&.asset\&.DownloadFileCollector\&.clear_doc ( self, \fBSphinx\fP app, \fBBuildEnvironment\fP env, str docname)"

.PP
Reimplemented from \fBsphinx\&.environment\&.collectors\&.EnvironmentCollector\fP\&.
.SS " None sphinx\&.environment\&.collectors\&.asset\&.DownloadFileCollector\&.merge_other ( self, \fBSphinx\fP app, \fBBuildEnvironment\fP env, Set[str] docnames, \fBBuildEnvironment\fP other)"

.PP
Reimplemented from \fBsphinx\&.environment\&.collectors\&.EnvironmentCollector\fP\&.
.SS " None sphinx\&.environment\&.collectors\&.asset\&.DownloadFileCollector\&.process_doc ( self, \fBSphinx\fP app, nodes\&.document doctree)"

.PP
.nf
Process downloadable file paths\&.
.fi
.PP
 
.PP
Reimplemented from \fBsphinx\&.environment\&.collectors\&.EnvironmentCollector\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
