.TH "sphinx.transforms.post_transforms.images" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.transforms.post_transforms.images
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseImageConverter\fP"
.br
.ti -1c
.RI "class \fBDataURIExtractor\fP"
.br
.ti -1c
.RI "class \fBImageConverter\fP"
.br
.ti -1c
.RI "class \fBImageDownloader\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBget_filename_for\fP (str filename, str mimetype)"
.br
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "int \fBMAX_FILENAME_LEN\fP = 32"
.br
.ti -1c
.RI "\fBCRITICAL_PATH_CHAR_RE\fP = re\&.compile('[:;<>|*' ]')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Docutils transforms used by Sphinx\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str sphinx\&.transforms\&.post_transforms\&.images\&.get_filename_for (str filename, str mimetype)"

.SS " \fBExtensionMetadata\fP sphinx\&.transforms\&.post_transforms\&.images\&.setup (\fBSphinx\fP app)"

.SH "Variable Documentation"
.PP 
.SS "sphinx\&.transforms\&.post_transforms\&.images\&.CRITICAL_PATH_CHAR_RE = re\&.compile('[:;<>|*' ]')"

.SS "sphinx\&.transforms\&.post_transforms\&.images\&.logger = logging\&.getLogger(__name__)"

.SS "int sphinx\&.transforms\&.post_transforms\&.images\&.MAX_FILENAME_LEN = 32"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
