.TH "sphinx.writers.html5" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers.html5
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHTML5Translator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBmultiply_length\fP (str length, int scale)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Experimental docutils writers for HTML5 handling Sphinx's custom nodes\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str sphinx\&.writers\&.html5\&.multiply_length (str length, int scale)"

.PP
.nf
Multiply *length* (width or height) by *scale*\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "sphinx\&.writers\&.html5\&.logger = logging\&.getLogger(__name__)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
