.TH "sphinx._cli" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx._cli
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_RootArgumentParser\fP"
.br
.ti -1c
.RI "class \fB_SubcommandModule\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Iterator[tuple[str, str]] \fB_load_subcommand_descriptions\fP ()"
.br
.ti -1c
.RI "\fB_RootArgumentParser\fP \fB_create_parser\fP ()"
.br
.ti -1c
.RI "tuple[str, Sequence[str]] \fB_parse_command\fP (Sequence[str] argv=())"
.br
.ti -1c
.RI "tuple[str, \fB_PARSER_SETUP\fP, \fB_RUNNER\fP] \fB_load_subcommand\fP (str command_name)"
.br
.ti -1c
.RI "argparse\&.ArgumentParser \fB_create_sub_parser\fP (str command_name, str description, \fB_PARSER_SETUP\fP parser_setup)"
.br
.ti -1c
.RI "int \fBrun\fP (Sequence[str] argv=())"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "TypeAlias \fB_PARSER_SETUP\fP"
.br
.ti -1c
.RI "TypeAlias \fB_RUNNER\fP = Callable[[argparse\&.Namespace], int]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base 'sphinx' command\&.

Subcommands are loaded lazily from the ``_COMMANDS`` table for performance\&.

All subcommand modules must define three attributes:

- ``parser_description``, a description of the subcommand\&. The first paragraph
  is taken as the short description for the command\&.
- ``set_up_parser``, a callable taking and returning an ``ArgumentParser``\&. This
  function is responsible for adding options and arguments to the subcommand's
  parser\&.
- ``run``, a callable taking parsed arguments and returning an exit code\&. This
  function is responsible for running the main body of the subcommand and
  returning the exit status\&.

The entire ``sphinx\&._cli`` namespace is private, only the command line interface
has backwards-compatibility guarantees\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fB_RootArgumentParser\fP sphinx\&._cli\&._create_parser ()\fC [protected]\fP"

.SS " argparse\&.ArgumentParser sphinx\&._cli\&._create_sub_parser (str command_name, str description, \fB_PARSER_SETUP\fP parser_setup)\fC [protected]\fP"

.SS " tuple[str, \fB_PARSER_SETUP\fP, \fB_RUNNER\fP] sphinx\&._cli\&._load_subcommand (str command_name)\fC [protected]\fP"

.SS " Iterator[tuple[str, str]] sphinx\&._cli\&._load_subcommand_descriptions ()\fC [protected]\fP"

.SS " tuple[str, Sequence[str]] sphinx\&._cli\&._parse_command (Sequence[str]  argv = \fC()\fP)\fC [protected]\fP"

.SS " int sphinx\&._cli\&.run (Sequence[str]  argv = \fC()\fP)"

.SH "Variable Documentation"
.PP 
.SS "TypeAlias sphinx\&._cli\&._PARSER_SETUP\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  Callable[
2         [argparse\&.ArgumentParser], argparse\&.ArgumentParser
3     ]
.fi

.SS "TypeAlias sphinx\&._cli\&._RUNNER = Callable[[argparse\&.Namespace], int]\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
