.TH "sphinx.domains.c._symbol.LookupKey" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.domains.c._symbol.LookupKey
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, Sequence[tuple[\fBASTIdentifier\fP, str]] \fBdata\fP)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdata\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "Sequence \fBdata\fP [tuple[\fBASTIdentifier\fP, str]]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.domains\&.c\&._symbol\&.LookupKey\&.__init__ ( self, Sequence[tuple[\fBASTIdentifier\fP, str]] data)"

.SH "Member Function Documentation"
.PP 
.SS " str sphinx\&.domains\&.c\&._symbol\&.LookupKey\&.__repr__ ( self)"

.SS " str sphinx\&.domains\&.c\&._symbol\&.LookupKey\&.__str__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "Sequence sphinx\&.domains\&.c\&._symbol\&.LookupKey\&.data [tuple[\fBASTIdentifier\fP, str]]\fC [static]\fP"

.SS "sphinx\&.domains\&.c\&._symbol\&.LookupKey\&.data"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
