.TH "sphinx.builders.gettext.Message" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders.gettext.Message
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBtext\fP, list[tuple[str, int]] \fBlocations\fP, list[str] \fBuuids\fP)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtext\fP"
.br
.ti -1c
.RI "\fBlocations\fP"
.br
.ti -1c
.RI "\fBuuids\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBtext\fP"
.br
.ti -1c
.RI "list \fBlocations\fP [tuple[str, int]]"
.br
.ti -1c
.RI "list \fBuuids\fP [str]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An entry of translatable message\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.builders\&.gettext\&.Message\&.__init__ ( self, str text, list[tuple[str, int]] locations, list[str]
     uuids)"

.SH "Member Function Documentation"
.PP 
.SS " str sphinx\&.builders\&.gettext\&.Message\&.__repr__ ( self)"

.SH "Member Data Documentation"
.PP 
.SS "list sphinx\&.builders\&.gettext\&.Message\&.locations [tuple[str, int]]\fC [static]\fP"

.SS "sphinx\&.builders\&.gettext\&.Message\&.locations"

.SS "str sphinx\&.builders\&.gettext\&.Message\&.text\fC [static]\fP"

.SS "sphinx\&.builders\&.gettext\&.Message\&.text"

.SS "list sphinx\&.builders\&.gettext\&.Message\&.uuids [str]\fC [static]\fP"

.SS "sphinx\&.builders\&.gettext\&.Message\&.uuids"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
