.TH "sphinx.ext.autodoc.directive.DocumenterBridge" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.autodoc.directive.DocumenterBridge
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsphinx\&.ext\&.autosummary\&.FakeDirective\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBBuildEnvironment\fP \fBenv\fP, \fBReporter\fP|None reporter, \fBOptions\fP options, int \fBlineno\fP, Any \fBstate\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBenv\fP"
.br
.ti -1c
.RI "\fBgenopt\fP"
.br
.ti -1c
.RI "\fBlineno\fP"
.br
.ti -1c
.RI "\fBresult\fP"
.br
.ti -1c
.RI "\fBstate\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_reporter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A parameters container for Documenters\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.ext\&.autodoc\&.directive\&.DocumenterBridge\&.__init__ ( self, \fBBuildEnvironment\fP env, \fBReporter\fP | None reporter, \fBOptions\fP options, int lineno, Any state)"

.PP
Reimplemented in \fBsphinx\&.ext\&.autosummary\&.FakeDirective\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.ext\&.autodoc\&.directive\&.DocumenterBridge\&._reporter\fC [protected]\fP"

.SS "sphinx\&.ext\&.autodoc\&.directive\&.DocumenterBridge\&.env"

.SS "sphinx\&.ext\&.autodoc\&.directive\&.DocumenterBridge\&.genopt"

.SS "sphinx\&.ext\&.autodoc\&.directive\&.DocumenterBridge\&.lineno"

.SS "sphinx\&.ext\&.autodoc\&.directive\&.DocumenterBridge\&.result"

.SS "sphinx\&.ext\&.autodoc\&.directive\&.DocumenterBridge\&.state"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
