.TH "sphinx.util.template.LaTeXRenderer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.template.LaTeXRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.util\&.template\&.SphinxRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, Sequence[str|os\&.PathLike[str]]|None template_path=None, str|None latex_engine=None)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.util\&.template\&.SphinxRenderer\fP
.in +1c
.ti -1c
.RI "str \fBrender_from_file\fP (type[\fBFileRenderer\fP] cls, str|os\&.PathLike[str] filename, dict[str, Any] context)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.util\&.template\&.BaseRenderer\fP
.in +1c
.ti -1c
.RI "str \fBrender\fP (self, str template_name, dict[str, Any] context)"
.br
.ti -1c
.RI "str \fBrender_string\fP (self, str source, dict[str, Any] context)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBsphinx\&.util\&.template\&.BaseRenderer\fP
.in +1c
.ti -1c
.RI "\fBenv\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.util\&.template\&.LaTeXRenderer\&.__init__ ( self, Sequence[str | os\&.PathLike[str]] | None  template_path = \fCNone\fP, str | None  latex_engine = \fCNone\fP)"

.PP
Reimplemented from \fBsphinx\&.util\&.template\&.SphinxRenderer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
