.TH "sphinx.util.typing.RoleFunction" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.typing.RoleFunction
.SH SYNOPSIS
.br
.PP
.PP
Inherits Protocol\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "tuple[list[\fBnodes\&.Node\fP], list[nodes\&.system_message]] \fB__call__\fP (self, str name, str rawtext, str text, int lineno, \fBInliner\fP inliner, dict[str, Any]|None options=None, Sequence[str] content=())"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " tuple[list[\fBnodes\&.Node\fP], list[nodes\&.system_message]] sphinx\&.util\&.typing\&.RoleFunction\&.__call__ ( self, str name, str rawtext, str text, int lineno, \fBInliner\fP inliner, dict[str, Any] | None  options = \fCNone\fP, Sequence[str]  content = \fC()\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
