.TH "sphinx.cmd.quickstart.QuickstartRenderer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.cmd.quickstart.QuickstartRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.util\&.template\&.SphinxRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBtemplatedir\fP='')"
.br
.ti -1c
.RI "str \fBrender\fP (self, str template_name, dict[str, Any] context)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.util\&.template\&.SphinxRenderer\fP
.in +1c
.ti -1c
.RI "str \fBrender_from_file\fP (type[\fBFileRenderer\fP] cls, str|os\&.PathLike[str] filename, dict[str, Any] context)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.util\&.template\&.BaseRenderer\fP
.in +1c
.ti -1c
.RI "str \fBrender_string\fP (self, str source, dict[str, Any] context)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtemplatedir\fP"
.br
.in -1c

Public Attributes inherited from \fBsphinx\&.util\&.template\&.BaseRenderer\fP
.in +1c
.ti -1c
.RI "\fBenv\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fB_has_custom_template\fP (self, str template_name)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.cmd\&.quickstart\&.QuickstartRenderer\&.__init__ ( self, str  templatedir = \fC''\fP)"

.PP
Reimplemented from \fBsphinx\&.util\&.template\&.SphinxRenderer\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " bool sphinx\&.cmd\&.quickstart\&.QuickstartRenderer\&._has_custom_template ( self, str template_name)\fC [protected]\fP"

.PP
.nf
Check if custom template file exists\&.

Note: Please don't use this function from extensions\&.
      It will be removed in the future without deprecation period\&.

.fi
.PP
 
.SS " str sphinx\&.cmd\&.quickstart\&.QuickstartRenderer\&.render ( self, str template_name, dict[str, Any] context)"

.PP
Reimplemented from \fBsphinx\&.util\&.template\&.BaseRenderer\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.cmd\&.quickstart\&.QuickstartRenderer\&.templatedir"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
