.TH "sphinx.builders._epub_base" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders._epub_base
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEpubBuilder\fP"
.br
.ti -1c
.RI "class \fBGuide\fP"
.br
.ti -1c
.RI "class \fBManifestItem\fP"
.br
.ti -1c
.RI "class \fBNavPoint\fP"
.br
.ti -1c
.RI "class \fBSpine\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBsphinx_smarty_pants\fP (str t, str language='en')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBPILLOW_AVAILABLE\fP = True"
.br
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "str \fBCOVERPAGE_NAME\fP = 'epub\-cover\&.xhtml'"
.br
.ti -1c
.RI "str \fBTOCTREE_TEMPLATE\fP = 'toctree\-l%d'"
.br
.ti -1c
.RI "str \fBLINK_TARGET_TEMPLATE\fP = ' [%(uri)s]'"
.br
.ti -1c
.RI "str \fBFOOTNOTE_LABEL_TEMPLATE\fP = '#%d'"
.br
.ti -1c
.RI "str \fBFOOTNOTES_RUBRIC_NAME\fP = 'Footnotes'"
.br
.ti -1c
.RI "str \fBCSS_LINK_TARGET_CLASS\fP = 'link\-target'"
.br
.ti -1c
.RI "dict \fBGUIDE_TITLES\fP"
.br
.ti -1c
.RI "dict \fBMEDIA_TYPES\fP"
.br
.ti -1c
.RI "tuple \fBVECTOR_GRAPHICS_EXTENSIONS\fP = ('\&.svg',)"
.br
.ti -1c
.RI "\fBREFURI_RE\fP = re\&.compile('([^#:]*#)(\&.*)')"
.br
.ti -1c
.RI "str \fBssp\fP = \fBsphinx_smarty_pants\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base class of epub2/epub3 builders\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str sphinx\&.builders\&._epub_base\&.sphinx_smarty_pants (str t, str  language = \fC'en'\fP)"

.SH "Variable Documentation"
.PP 
.SS "str sphinx\&.builders\&._epub_base\&.COVERPAGE_NAME = 'epub\-cover\&.xhtml'"

.SS "str sphinx\&.builders\&._epub_base\&.CSS_LINK_TARGET_CLASS = 'link\-target'"

.SS "str sphinx\&.builders\&._epub_base\&.FOOTNOTE_LABEL_TEMPLATE = '#%d'"

.SS "str sphinx\&.builders\&._epub_base\&.FOOTNOTES_RUBRIC_NAME = 'Footnotes'"

.SS "dict sphinx\&.builders\&._epub_base\&.GUIDE_TITLES"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'toc': 'Table of Contents',
3     'cover': 'Cover',
4 }
.fi

.SS "str sphinx\&.builders\&._epub_base\&.LINK_TARGET_TEMPLATE = ' [%(uri)s]'"

.SS "sphinx\&.builders\&._epub_base\&.logger = logging\&.getLogger(__name__)"

.SS "dict sphinx\&.builders\&._epub_base\&.MEDIA_TYPES"
\fBInitial value:\fP.PP
.nf
1 =  {
2     '\&.xhtml': 'application/xhtml+xml',
3     '\&.css': 'text/css',
4     '\&.png': 'image/png',
5     '\&.webp': 'image/webp',
6     '\&.gif': 'image/gif',
7     '\&.svg': 'image/svg+xml',
8     '\&.jpg': 'image/jpeg',
9     '\&.jpeg': 'image/jpeg',
10     '\&.otf': 'font/otf',
11     '\&.ttf': 'font/ttf',
12     '\&.woff': 'font/woff',
13 }
.fi

.SS "bool sphinx\&.builders\&._epub_base\&.PILLOW_AVAILABLE = True"

.SS "sphinx\&.builders\&._epub_base\&.REFURI_RE = re\&.compile('([^#:]*#)(\&.*)')"

.SS "str sphinx\&.builders\&._epub_base\&.ssp = \fBsphinx_smarty_pants\fP"

.SS "str sphinx\&.builders\&._epub_base\&.TOCTREE_TEMPLATE = 'toctree\-l%d'"

.SS "tuple sphinx\&.builders\&._epub_base\&.VECTOR_GRAPHICS_EXTENSIONS = ('\&.svg',)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
