.TH "sphinx.environment.adapters.indexentries.IndexEntries" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.environment.adapters.indexentries.IndexEntries
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBBuildEnvironment\fP \fBenv\fP)"
.br
.ti -1c
.RI "\fB_Index\fP \fBcreate_index\fP (self, \fBBuilder\fP builder, bool group_entries=True, re\&.Pattern[str] _fixre=re\&.compile(r'(\&.*)([(][^()] *[)])'))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBenv\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.environment\&.adapters\&.indexentries\&.IndexEntries\&.__init__ ( self, \fBBuildEnvironment\fP env)"

.SH "Member Function Documentation"
.PP 
.SS " \fB_Index\fP sphinx\&.environment\&.adapters\&.indexentries\&.IndexEntries\&.create_index ( self, \fBBuilder\fP builder, bool  group_entries = \fCTrue\fP, re\&.Pattern[str]  _fixre = \fCre\&.compile(r'(\&.*) ([(][^()]*[)])')\fP)"

.PP
.nf
Create the real index from the collected index entries\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.environment\&.adapters\&.indexentries\&.IndexEntries\&.env"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
