.TH "sphinx.util.docutils._DirectivesDispatcher" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.docutils._DirectivesDispatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits Protocol\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "tuple[type[\fBDirective\fP]|None, list[\fBsystem_message\fP]] \fB__call__\fP (self, str directive_name, \fB_LanguageModule\fP language_module, nodes\&.document document)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " tuple[type[\fBDirective\fP] | None, list[\fBsystem_message\fP]] sphinx\&.util\&.docutils\&._DirectivesDispatcher\&.__call__ ( self, str directive_name, \fB_LanguageModule\fP language_module, nodes\&.document document)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
