.TH "sphinx.domains.cpp.AliasNode" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.domains.cpp.AliasNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits nodes\&.Element\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBsig\fP, dict[str, bool] \fBaliasOptions\fP, \fBBuildEnvironment\fP|None env=None, \fBLookupKey\fP|None \fBparentKey\fP=None)"
.br
.ti -1c
.RI "\fBAliasNode\fP \fBcopy\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsig\fP"
.br
.ti -1c
.RI "\fBaliasOptions\fP"
.br
.ti -1c
.RI "\fBparentKey\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.domains\&.cpp\&.AliasNode\&.__init__ ( self, str sig, dict[str, bool] aliasOptions, \fBBuildEnvironment\fP | None  env = \fCNone\fP, \fBLookupKey\fP | None  parentKey = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS " \fBAliasNode\fP sphinx\&.domains\&.cpp\&.AliasNode\&.copy ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.domains\&.cpp\&.AliasNode\&.aliasOptions"

.SS "sphinx\&.domains\&.cpp\&.AliasNode\&.parentKey"

.SS "sphinx\&.domains\&.cpp\&.AliasNode\&.sig"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
