.TH "sphinx.ext.napoleon.docstring.NumpyDocstring" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.napoleon.docstring.NumpyDocstring
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str|list[str] docstring, SphinxConfig|None config=None, \fBSphinx\fP|None app=None, str what='', str name='', Any obj=None, Any options=None)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP
.in +1c
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "list[str] \fBlines\fP (self)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_escape_args_and_kwargs\fP (self, str name)"
.br
.ti -1c
.RI "tuple[str, str, list[str]] \fB_consume_field\fP (self, bool parse_type=True, bool prefer_type=False)"
.br
.ti -1c
.RI "list[tuple[str, str, list[str]]] \fB_consume_returns_section\fP (self, bool preprocess_types=False)"
.br
.ti -1c
.RI "str \fB_consume_section_header\fP (self)"
.br
.ti -1c
.RI "bool \fB_is_section_break\fP (self)"
.br
.ti -1c
.RI "bool \fB_is_section_header\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_parse_see_also_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_numpydoc_see_also_section\fP (self, list[str] content)"
.br
.in -1c

Protected Member Functions inherited from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP
.in +1c
.ti -1c
.RI "str|None \fB_get_location\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_consume_indented_block\fP (self, int indent=1)"
.br
.ti -1c
.RI "list[str] \fB_consume_contiguous\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_consume_empty\fP (self)"
.br
.ti -1c
.RI "list[tuple[str, str, list[str]]] \fB_consume_fields\fP (self, bool parse_type=True, bool prefer_type=False, bool multiple=False)"
.br
.ti -1c
.RI "tuple[str, list[str]] \fB_consume_inline_attribute\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_consume_usage_section\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_consume_to_end\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_consume_to_next_section\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_dedent\fP (self, list[str] \fBlines\fP, bool full=False)"
.br
.ti -1c
.RI "list[str] \fB_fix_field_desc\fP (self, list[str] desc)"
.br
.ti -1c
.RI "list[str] \fB_format_admonition\fP (self, str admonition, list[str] \fBlines\fP)"
.br
.ti -1c
.RI "list[str] \fB_format_block\fP (self, str prefix, list[str] \fBlines\fP, str|None padding=None)"
.br
.ti -1c
.RI "list[str] \fB_format_docutils_params\fP (self, list[tuple[str, str, list[str]]] fields, str field_role='param', str type_role='type')"
.br
.ti -1c
.RI "list[str] \fB_format_field\fP (self, str \fB_name\fP, str _type, list[str] _desc)"
.br
.ti -1c
.RI "list[str] \fB_format_fields\fP (self, str field_type, list[tuple[str, str, list[str]]] fields)"
.br
.ti -1c
.RI "int \fB_get_current_indent\fP (self, int peek_ahead=0)"
.br
.ti -1c
.RI "int \fB_get_indent\fP (self, str line)"
.br
.ti -1c
.RI "int \fB_get_initial_indent\fP (self, list[str] \fBlines\fP)"
.br
.ti -1c
.RI "int \fB_get_min_indent\fP (self, list[str] \fBlines\fP)"
.br
.ti -1c
.RI "list[str] \fB_indent\fP (self, list[str] \fBlines\fP, int n=4)"
.br
.ti -1c
.RI "bool \fB_is_indented\fP (self, str line, int indent=1)"
.br
.ti -1c
.RI "bool \fB_is_list\fP (self, list[str] \fBlines\fP)"
.br
.ti -1c
.RI "None \fB_load_custom_sections\fP (self)"
.br
.ti -1c
.RI "None \fB_parse\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_parse_admonition\fP (self, str admonition, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_attribute_docstring\fP (self)"
.br
.ti -1c
.RI "list[str] \fB_parse_attributes_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_examples_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_custom_generic_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_custom_params_style_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_custom_returns_style_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_usage_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_generic_section\fP (self, str section, bool use_admonition)"
.br
.ti -1c
.RI "list[str] \fB_parse_keyword_arguments_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_methods_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_notes_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_other_parameters_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_parameters_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_raises_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_receives_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_references_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_returns_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_warns_section\fP (self, str section)"
.br
.ti -1c
.RI "list[str] \fB_parse_yields_section\fP (self, str section)"
.br
.ti -1c
.RI "tuple[str, str, str] \fB_partition_field_on_colon\fP (self, str line)"
.br
.ti -1c
.RI "list[str] \fB_strip_empty\fP (self, list[str] \fBlines\fP)"
.br
.ti -1c
.RI "str \fB_lookup_annotation\fP (self, str \fB_name\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_directive_sections\fP"
.br
.ti -1c
.RI "\fB_section_indent\fP"
.br
.in -1c

Protected Attributes inherited from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP
.in +1c
.ti -1c
.RI "\fB_app\fP"
.br
.ti -1c
.RI "\fB_config\fP"
.br
.ti -1c
.RI "\fB_what\fP"
.br
.ti -1c
.RI "\fB_name\fP"
.br
.ti -1c
.RI "\fB_obj\fP"
.br
.ti -1c
.RI "\fB_opt\fP"
.br
.ti -1c
.RI "\fB_lines\fP"
.br
.ti -1c
.RI "\fB_is_in_section\fP"
.br
.ti -1c
.RI "\fB_section_indent\fP"
.br
.ti -1c
.RI "\fB_parse_parameters_section\fP"
.br
.ti -1c
.RI "\fB_parse_admonition\fP"
.br
.ti -1c
.RI "\fB_parse_attributes_section\fP"
.br
.ti -1c
.RI "\fB_parse_examples_section\fP"
.br
.ti -1c
.RI "\fB_parse_keyword_arguments_section\fP"
.br
.ti -1c
.RI "\fB_parse_methods_section\fP"
.br
.ti -1c
.RI "\fB_parse_notes_section\fP"
.br
.ti -1c
.RI "\fB_parse_other_parameters_section\fP"
.br
.ti -1c
.RI "\fB_parse_receives_section\fP"
.br
.ti -1c
.RI "\fB_parse_returns_section\fP"
.br
.ti -1c
.RI "\fB_parse_raises_section\fP"
.br
.ti -1c
.RI "\fB_parse_references_section\fP"
.br
.ti -1c
.RI "\fB_parse_warns_section\fP"
.br
.ti -1c
.RI "\fB_parse_yields_section\fP"
.br
.ti -1c
.RI "\fB_parsed_lines\fP"
.br
.ti -1c
.RI "\fB_annotations\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Protected Attributes inherited from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP
.in +1c
.ti -1c
.RI "\fB_name_rgx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Convert NumPy style docstrings to reStructuredText\&.

Parameters
----------
docstring : :obj:`str` or :obj:`list` of :obj:`str`
    The docstring to parse, given either as a string or split into
    individual lines\&.
config: :obj:`sphinx\&.ext\&.napoleon\&.Config` or :obj:`sphinx\&.config\&.Config`
    The configuration settings to use\&. If not given, defaults to the
    config object on `app`; or if `app` is not given defaults to the
    a new :class:`sphinx\&.ext\&.napoleon\&.Config` object\&.


Other Parameters
----------------
app : :class:`sphinx\&.application\&.Sphinx`, optional
    Application object representing the Sphinx process\&.
what : :obj:`str`, optional
    A string specifying the type of the object to which the docstring
    belongs\&. Valid values: 'module', 'class', 'exception', 'function',
    'method', 'attribute'\&.
name : :obj:`str`, optional
    The fully qualified name of the object\&.
obj : module, class, exception, function, method, or attribute
    The object to which the docstring belongs\&.
options : :class:`sphinx\&.ext\&.autodoc\&.Options`, optional
    The options given to the directive: an object with attributes
    inherited_members, undoc_members, show_inheritance and no_index that
    are True if the flag option of same name was given to the auto
    directive\&.


Example
-------
>>> from sphinx\&.ext\&.napoleon import Config
>>> config = Config(napoleon_use_param=True, napoleon_use_rtype=True)
>>> docstring = '''One line summary\&.
\&.\&.\&.
\&.\&.\&. Extended description\&.
\&.\&.\&.
\&.\&.\&. Parameters
\&.\&.\&. ----------
\&.\&.\&. arg1 : int
\&.\&.\&.     Description of `arg1`
\&.\&.\&. arg2 : str
\&.\&.\&.     Description of `arg2`
\&.\&.\&. Returns
\&.\&.\&. -------
\&.\&.\&. str
\&.\&.\&.     Description of return value\&.
\&.\&.\&. '''
>>> print(NumpyDocstring(docstring, config))
One line summary\&.
<BLANKLINE>
Extended description\&.
<BLANKLINE>
:param arg1: Description of `arg1`
:type arg1: int
:param arg2: Description of `arg2`
:type arg2: str
<BLANKLINE>
:returns: Description of return value\&.
:rtype: str
<BLANKLINE>

Methods
-------
__str__()
    Return the parsed docstring in reStructuredText format\&.

    Returns
    -------
    str
        UTF-8 encoded version of the docstring\&.

__unicode__()
    Return the parsed docstring in reStructuredText format\&.

    Returns
    -------
    unicode
        Unicode version of the docstring\&.

lines()
    Return the parsed lines of the docstring in reStructuredText format\&.

    Returns
    -------
    list(str)
        The lines of the docstring in a list\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&.__init__ ( self, str | list[str] docstring, SphinxConfig | None  config = \fCNone\fP, \fBSphinx\fP | None  app = \fCNone\fP, str  what = \fC''\fP, str  name = \fC''\fP, Any  obj = \fCNone\fP, Any  options = \fCNone\fP)"

.PP
Reimplemented from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " tuple[str, str, list[str]] sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._consume_field ( self, bool  parse_type = \fCTrue\fP, bool  prefer_type = \fCFalse\fP)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SS " list[tuple[str, str, list[str]]] sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._consume_returns_section ( self, bool  preprocess_types = \fCFalse\fP)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SS " str sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._consume_section_header ( self)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SS " str sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._escape_args_and_kwargs ( self, str name)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SS " bool sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._is_section_break ( self)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SS " bool sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._is_section_header ( self)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SS " list[str] sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._parse_numpydoc_see_also_section ( self, list[str] content)\fC [protected]\fP"

.PP
.nf
See Also
--------
func_name : Descriptive text
    continued text
another_func_name : Descriptive text
func_name1, func_name2, :meth:`func_name`, func_name3

Licence
-------

Derived from the NumpyDoc implementation of ``_parse_see_also``,
which was under the following licence:

    Copyright (C) 2008 Stefan van der Walt <stefan@mentat\&.za\&.net>,
                       Pauli Virtanen <pav@iki\&.fi>

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are
    met:

     1\&. Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer\&.
     2\&. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in
        the documentation and/or other materials provided with the
        distribution\&.

    THIS SOFTWARE IS PROVIDED BY THE AUTHOR 'AS IS' AND ANY EXPRESS OR
    IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED\&. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
    INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
    HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
    IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE\&.

.fi
.PP
 
.SS " list[str] sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._parse_see_also_section ( self, str section)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.ext\&.napoleon\&.docstring\&.GoogleDocstring\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._directive_sections\fC [protected]\fP"

.SS "sphinx\&.ext\&.napoleon\&.docstring\&.NumpyDocstring\&._section_indent\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
