.TH "sphinx.writers.latex.TableCell" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers.latex.TableCell
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBTable\fP \fBtable\fP, int \fBrow\fP, int \fBcol\fP)"
.br
.ti -1c
.RI "int \fBwidth\fP (self)"
.br
.ti -1c
.RI "int \fBheight\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtable\fP"
.br
.ti -1c
.RI "\fBcell_id\fP"
.br
.ti -1c
.RI "\fBrow\fP"
.br
.ti -1c
.RI "\fBcol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Data of a cell in a table\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.writers\&.latex\&.TableCell\&.__init__ ( self, \fBTable\fP table, int row, int col)"

.SH "Member Function Documentation"
.PP 
.SS " int sphinx\&.writers\&.latex\&.TableCell\&.height ( self)"

.PP
.nf
Returns the cell height\&.
.fi
.PP
 
.SS " int sphinx\&.writers\&.latex\&.TableCell\&.width ( self)"

.PP
.nf
Returns the cell width\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.writers\&.latex\&.TableCell\&.cell_id"

.SS "sphinx\&.writers\&.latex\&.TableCell\&.col"

.SS "sphinx\&.writers\&.latex\&.TableCell\&.row"

.SS "sphinx\&.writers\&.latex\&.TableCell\&.table"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
