.TH "sphinx.ext.autosummary.generate._DummyEvents" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.autosummary.generate._DummyEvents
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fBemit_firstresult\fP (self, *Any args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.ext\&.autosummary\&.generate\&._DummyEvents\&.emit_firstresult ( self, *Any args)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
