.TH "sphinx.util._inventory_file_reader._SupportsRead" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util._inventory_file_reader._SupportsRead
.SH SYNOPSIS
.br
.PP
.PP
Inherits Protocol\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bytes \fBread\fP (self, int size=\&.\&.\&.)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " bytes sphinx\&.util\&._inventory_file_reader\&._SupportsRead\&.read ( self, int  size = \fC\&.\&.\&.\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
