.TH "sphinx.writers.texinfo.TexinfoWriter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers.texinfo.TexinfoWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits writers\&.Writer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBTexinfoBuilder\fP \fBbuilder\fP)"
.br
.ti -1c
.RI "None \fBtranslate\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbuilder\fP"
.br
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBvisitor\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBsupported\fP = ('texinfo', 'texi')"
.br
.ti -1c
.RI "tuple \fBsettings_spec\fP"
.br
.ti -1c
.RI "dict \fBsettings_defaults\fP = {}"
.br
.ti -1c
.RI "str \fBoutput\fP"
.br
.ti -1c
.RI "tuple \fBvisitor_attributes\fP = ('\fBoutput\fP', 'fragment')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Texinfo writer for generating Texinfo documents\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.__init__ ( self, \fBTexinfoBuilder\fP builder)"

.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.translate ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.builder"

.SS "sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.document"

.SS "str sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.output\fC [static]\fP"

.SS "dict sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.settings_defaults = {}\fC [static]\fP"

.SS "tuple sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.settings_spec\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  (
        'Texinfo Specific Options',
        None,
        (
            ('Name of the Info file', ['\-\-texinfo\-filename'], {'default': ''}),
            ('Dir entry', ['\-\-texinfo\-dir\-entry'], {'default': ''}),
            ('Description', ['\-\-texinfo\-dir\-description'], {'default': ''}),
            ('Category', ['\-\-texinfo\-dir\-category'], {'default': 'Miscellaneous'}),
        ),
    )
.fi

.SS "tuple sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.supported = ('texinfo', 'texi')\fC [static]\fP"

.SS "sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.visitor"

.SS "tuple sphinx\&.writers\&.texinfo\&.TexinfoWriter\&.visitor_attributes = ('\fBoutput\fP', 'fragment')\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
