.TH "sphinx.io" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.io
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSphinxBaseReader\fP"
.br
.ti -1c
.RI "class \fBSphinxDummyWriter\fP"
.br
.ti -1c
.RI "class \fBSphinxFileInput\fP"
.br
.ti -1c
.RI "class \fBSphinxI18nReader\fP"
.br
.ti -1c
.RI "class \fBSphinxStandaloneReader\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Any \fBSphinxDummySourceClass\fP (Any source, *Any args, **Any kwargs)"
.br
.ti -1c
.RI "\fBPublisher\fP \fBcreate_publisher\fP (\fBSphinx\fP app, str filetype)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Input/Output files
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fBPublisher\fP sphinx\&.io\&.create_publisher (\fBSphinx\fP app, str filetype)"

.SS " Any sphinx\&.io\&.SphinxDummySourceClass (Any source, *Any args, **Any kwargs)"

.PP
.nf
Bypass source object as is to cheat Publisher\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "sphinx\&.io\&.logger = logging\&.getLogger(__name__)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
