.TH "sphinx.search._ReadableStream" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.search._ReadableStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits Protocol, and _T_co\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_T_co\fP \fBread\fP (self, int n=\&.\&.\&.)"
.br
.ti -1c
.RI "\fB_T_co\fP \fBreadline\fP (self, int n=\&.\&.\&.)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " \fB_T_co\fP sphinx\&.search\&._ReadableStream\&.read ( self, int  n = \fC\&.\&.\&.\fP)"

.SS " \fB_T_co\fP sphinx\&.search\&._ReadableStream\&.readline ( self, int  n = \fC\&.\&.\&.\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
