.TH "sphinx.transforms.post_transforms.SigElementFallbackTransform" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.transforms.post_transforms.SigElementFallbackTransform
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.transforms\&.post_transforms\&.SphinxPostTransform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fBrun\fP (self, **Any kwargs)"
.br
.ti -1c
.RI "None \fBfallback\fP (self, Any node_type)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.transforms\&.post_transforms\&.SphinxPostTransform\fP
.in +1c
.ti -1c
.RI "None \fBapply\fP (self, **Any kwargs)"
.br
.ti -1c
.RI "bool \fBis_supported\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.transforms\&.SphinxTransform\fP
.in +1c
.ti -1c
.RI "\fBSphinx\fP \fBapp\fP (self)"
.br
.ti -1c
.RI "\fBBuildEnvironment\fP \fBenv\fP (self)"
.br
.ti -1c
.RI "\fBConfig\fP \fBconfig\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBdocument\fP, \fBstartnode\fP=None)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdefault_priority\fP = 200"
.br
.in -1c

Static Public Attributes inherited from \fBsphinx\&.transforms\&.post_transforms\&.SphinxPostTransform\fP
.in +1c
.ti -1c
.RI "tuple \fBbuilders\fP = ()"
.br
.ti -1c
.RI "tuple \fBformats\fP = ()"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdefault_priority\fP = None"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBstartnode\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Fallback various desc_* nodes to inline if translator does not support them\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.transforms\&.post_transforms\&.SigElementFallbackTransform\&.fallback ( self, Any node_type)"

.PP
.nf
Translate nodes of type *node_type* to docutils inline nodes\&.

The original node type name is stored as a string in a private
``_sig_node_type`` attribute if the latter did not exist\&.

.fi
.PP
 
.SS " None sphinx\&.transforms\&.post_transforms\&.SigElementFallbackTransform\&.run ( self, **Any kwargs)"

.PP
.nf
Main method of post transforms\&.

Subclasses should override this method instead of ``apply()``\&.

.fi
.PP
 
.PP
Reimplemented from \fBsphinx\&.transforms\&.post_transforms\&.SphinxPostTransform\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int sphinx\&.transforms\&.post_transforms\&.SigElementFallbackTransform\&.default_priority = 200\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
