.TH "sphinx.builders.gettext.Catalog" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders.gettext.Catalog
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self)"
.br
.ti -1c
.RI "None \fBadd\fP (self, str msg, \fBElement\fP|\fBMsgOrigin\fP origin)"
.br
.ti -1c
.RI "Iterator[\fBMessage\fP] \fB__iter__\fP (self)"
.br
.ti -1c
.RI "list[str] \fBmessages\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmetadata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Catalog of translatable messages\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.builders\&.gettext\&.Catalog\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS " Iterator[\fBMessage\fP] sphinx\&.builders\&.gettext\&.Catalog\&.__iter__ ( self)"

.SS " None sphinx\&.builders\&.gettext\&.Catalog\&.add ( self, str msg, \fBElement\fP | \fBMsgOrigin\fP origin)"

.SS " list[str] sphinx\&.builders\&.gettext\&.Catalog\&.messages ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.builders\&.gettext\&.Catalog\&.metadata"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
