.TH "sphinx.directives.admonitions" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.directives.admonitions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdmonition\fP"
.br
.ti -1c
.RI "class \fBAttention\fP"
.br
.ti -1c
.RI "class \fBCaution\fP"
.br
.ti -1c
.RI "class \fBDanger\fP"
.br
.ti -1c
.RI "class \fBError\fP"
.br
.ti -1c
.RI "class \fBHint\fP"
.br
.ti -1c
.RI "class \fBImportant\fP"
.br
.ti -1c
.RI "class \fBNote\fP"
.br
.ti -1c
.RI "class \fBSeeAlso\fP"
.br
.ti -1c
.RI "class \fBSphinxAdmonition\fP"
.br
.ti -1c
.RI "class \fBTip\fP"
.br
.ti -1c
.RI "class \fBWarning\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fB_collapsible_arg\fP (str|None argument)"
.br
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " str sphinx\&.directives\&.admonitions\&._collapsible_arg (str | None argument)\fC [protected]\fP"

.SS " \fBExtensionMetadata\fP sphinx\&.directives\&.admonitions\&.setup (\fBSphinx\fP app)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
