.TH "sphinx.builders.latex.nodes" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders.latex.nodes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcaptioned_literal_block\fP"
.br
.ti -1c
.RI "class \fBfootnotemark\fP"
.br
.ti -1c
.RI "class \fBfootnotetext\fP"
.br
.ti -1c
.RI "class \fBmath_reference\fP"
.br
.ti -1c
.RI "class \fBthebibliography\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBHYPERLINK_SUPPORT_NODES\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Additional nodes for LaTeX writer\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "tuple sphinx\&.builders\&.latex\&.nodes\&.HYPERLINK_SUPPORT_NODES"
\fBInitial value:\fP.PP
.nf
1 =  (
2     nodes\&.figure,
3     nodes\&.literal_block,
4     nodes\&.table,
5     nodes\&.section,
6     captioned_literal_block,
7 )
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
