.TH "sphinx.writers.latex.UnsupportedError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers.latex.UnsupportedError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.errors\&.SphinxError\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBcategory\fP = 'Markup is unsupported in LaTeX'"
.br
.in -1c

Static Public Attributes inherited from \fBsphinx\&.errors\&.SphinxError\fP
.in +1c
.ti -1c
.RI "str \fBcategory\fP = 'Sphinx error'"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "str sphinx\&.writers\&.latex\&.UnsupportedError\&.category = 'Markup is unsupported in LaTeX'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
