.TH "sphinx.transforms" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.transforms
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcompact_bullet_list\fP"
.br
.ti -1c
.RI "namespace \fBi18n\fP"
.br
.ti -1c
.RI "namespace \fBpost_transforms\fP"
.br
.ti -1c
.RI "namespace \fBreferences\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplySourceWorkaround\fP"
.br
.ti -1c
.RI "class \fBAutoIndexUpgrader\fP"
.br
.ti -1c
.RI "class \fBAutoNumbering\fP"
.br
.ti -1c
.RI "class \fBDefaultSubstitutions\fP"
.br
.ti -1c
.RI "class \fBDoctestTransform\fP"
.br
.ti -1c
.RI "class \fBDoctreeReadEvent\fP"
.br
.ti -1c
.RI "class \fBExtraTranslatableNodes\fP"
.br
.ti -1c
.RI "class \fBFilterSystemMessages\fP"
.br
.ti -1c
.RI "class \fBGlossarySorter\fP"
.br
.ti -1c
.RI "class \fBHandleCodeBlocks\fP"
.br
.ti -1c
.RI "class \fBMoveModuleTargets\fP"
.br
.ti -1c
.RI "class \fBReorderConsecutiveTargetAndIndexNodes\fP"
.br
.ti -1c
.RI "class \fBSortIds\fP"
.br
.ti -1c
.RI "class \fBSphinxContentsFilter\fP"
.br
.ti -1c
.RI "class \fBSphinxSmartQuotes\fP"
.br
.ti -1c
.RI "class \fBSphinxTransform\fP"
.br
.ti -1c
.RI "class \fBSphinxTransformer\fP"
.br
.ti -1c
.RI "class \fBUnreferencedFootnotesDetector\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fB_calculate_translation_progress\fP (nodes\&.document document)"
.br
.ti -1c
.RI "None \fB_reorder_index_target_nodes\fP (nodes\&.target start_node)"
.br
.ti -1c
.RI "int \fB_sort_key\fP (nodes\&.Node node)"
.br
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "TypeAlias \fB_DEFAULT_SUBSTITUTION_NAMES\fP"
.br
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fB_DEFAULT_SUBSTITUTIONS\fP"
.br
.ti -1c
.RI "dict \fBTRANSLATABLE_NODES\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Docutils transforms used by Sphinx when reading documents\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " str sphinx\&.transforms\&._calculate_translation_progress (nodes\&.document document)\fC [protected]\fP"

.SS " None sphinx\&.transforms\&._reorder_index_target_nodes (nodes\&.target start_node)\fC [protected]\fP"

.PP
.nf
Sort target and index nodes\&.

Find all consecutive target and index nodes starting from ``start_node``,
and move all index nodes to before the first target node\&.

.fi
.PP
 
.SS " int sphinx\&.transforms\&._sort_key (nodes\&.Node node)\fC [protected]\fP"

.SS " \fBExtensionMetadata\fP sphinx\&.transforms\&.setup (\fBSphinx\fP app)"

.SH "Variable Documentation"
.PP 
.SS "TypeAlias sphinx\&.transforms\&._DEFAULT_SUBSTITUTION_NAMES\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  Literal[
2         'version',
3         'release',
4         'today',
5         'translation progress',
6     ]
.fi

.SS "sphinx\&.transforms\&._DEFAULT_SUBSTITUTIONS\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  frozenset({
2     'version',
3     'release',
4     'today',
5     'translation progress',
6 })
.fi

.SS "sphinx\&.transforms\&.logger = logging\&.getLogger(__name__)"

.SS "dict sphinx\&.transforms\&.TRANSLATABLE_NODES"
\fBInitial value:\fP.PP
.nf
1 =  {
2     'literal\-block': nodes\&.literal_block,
3     'doctest\-block': nodes\&.doctest_block,
4     'raw': nodes\&.raw,
5     'index': addnodes\&.index,
6     'image': nodes\&.image,
7 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
