.TH "sphinx.domains.c._ast.ASTIdentifier" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.domains.c._ast.ASTIdentifier
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBname\fP)"
.br
.ti -1c
.RI "bool \fB__eq__\fP (self, object other)"
.br
.ti -1c
.RI "int \fB__hash__\fP (self)"
.br
.ti -1c
.RI "bool \fBis_anon\fP (self)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "str \fBget_display_string\fP (self)"
.br
.ti -1c
.RI "None \fBdescribe_signature\fP (self, \fBTextElement\fP signode, str mode, \fBBuildEnvironment\fP env, str prefix, \fBSymbol\fP symbol)"
.br
.ti -1c
.RI "str \fBidentifier\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP
.in +1c
.ti -1c
.RI "Any \fBclone\fP (self)"
.br
.ti -1c
.RI "str \fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBis_anonymous\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_stringify\fP (self, StringifyTransform transform)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.__init__ ( self, str name)"

.SH "Member Function Documentation"
.PP 
.SS " bool sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.__eq__ ( self, object other)"

.PP
Reimplemented from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS " int sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.__hash__ ( self)"

.PP
Reimplemented from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS " str sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.__str__ ( self)"

.PP
Reimplemented from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS " str sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&._stringify ( self, StringifyTransform transform)\fC [protected]\fP"

.PP
Reimplemented from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS " None sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.describe_signature ( self, \fBTextElement\fP signode, str mode, \fBBuildEnvironment\fP env, str prefix, \fBSymbol\fP symbol)"

.SS " str sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.get_display_string ( self)"

.PP
Reimplemented from \fBsphinx\&.util\&.cfamily\&.ASTBaseBase\fP\&.
.SS " str sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.identifier ( self)"

.SS " bool sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.is_anon ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.is_anonymous"

.SS "sphinx\&.domains\&.c\&._ast\&.ASTIdentifier\&.name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
