.TH "sphinx.builders._UnicodeDecodeErrorHandler" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders._UnicodeDecodeErrorHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBdocname\fP)"
.br
.ti -1c
.RI "tuple[str, int] \fB__call__\fP (self, UnicodeDecodeError error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdocname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Custom error handler for open() that warns and replaces\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.builders\&._UnicodeDecodeErrorHandler\&.__init__ ( self, str docname)"

.SH "Member Function Documentation"
.PP 
.SS " tuple[str, int] sphinx\&.builders\&._UnicodeDecodeErrorHandler\&.__call__ ( self, UnicodeDecodeError error)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.builders\&._UnicodeDecodeErrorHandler\&.docname"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
