.TH "sphinx.ext.apidoc" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.apidoc
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__main__\fP"
.br
.ti -1c
.RI "namespace \fB_cli\fP"
.br
.ti -1c
.RI "namespace \fB_extension\fP"
.br
.ti -1c
.RI "namespace \fB_generate\fP"
.br
.ti -1c
.RI "namespace \fB_shared\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Creates reST files corresponding to Python modules for code documentation\&.

Parses a directory tree looking for Python modules and packages and creates
ReST files appropriately to create code documentation with Sphinx\&.  It also
creates a modules index (named modules\&.<suffix>)\&.

This is derived from the 'sphinx-autopackage' script, which is:
Copyright 2008 Société des arts technologiques (SAT),
https://sat\&.qc\&.ca/

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fBExtensionMetadata\fP sphinx\&.ext\&.apidoc\&.setup (\fBSphinx\fP app)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
