.TH "sphinx.transforms.post_transforms.images.ImageConverter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.transforms.post_transforms.images.ImageConverter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.transforms\&.post_transforms\&.images\&.BaseImageConverter\fP\&.
.PP
Inherited by \fBsphinx\&.ext\&.imgconverter\&.ImagemagickConverter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBmatch\fP (self, nodes\&.image node)"
.br
.ti -1c
.RI "tuple[str, str] \fBget_conversion_rule\fP (self, nodes\&.image node)"
.br
.ti -1c
.RI "bool \fBis_available\fP (self)"
.br
.ti -1c
.RI "list[str] \fBguess_mimetypes\fP (self, nodes\&.image node)"
.br
.ti -1c
.RI "None \fBhandle\fP (self, nodes\&.image node)"
.br
.ti -1c
.RI "bool \fBconvert\fP (self, str|os\&.PathLike[str] _from, str|os\&.PathLike[str] _to)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.transforms\&.post_transforms\&.images\&.BaseImageConverter\fP
.in +1c
.ti -1c
.RI "None \fBapply\fP (self, **Any kwargs)"
.br
.ti -1c
.RI "\fB_StrPath\fP \fBimagedir\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.transforms\&.SphinxTransform\fP
.in +1c
.ti -1c
.RI "\fBSphinx\fP \fBapp\fP (self)"
.br
.ti -1c
.RI "\fBBuildEnvironment\fP \fBenv\fP (self)"
.br
.ti -1c
.RI "\fBConfig\fP \fBconfig\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBdocument\fP, \fBstartnode\fP=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBimagedir\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdocument\fP"
.br
.ti -1c
.RI "\fBstartnode\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdefault_priority\fP = 200"
.br
.ti -1c
.RI "bool \fBavailable\fP = None"
.br
.ti -1c
.RI "list \fBconversion_rules\fP = []"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.transforms\&.Transform\fP
.in +1c
.ti -1c
.RI "\fBdefault_priority\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A base class for image converters\&.

An image converter is kind of Docutils transform module\&.  It is used to
convert image files which are not supported by a builder to the
appropriate format for that builder\&.

For example, :py:class:`LaTeX builder <\&.LaTeXBuilder>` supports PDF,
PNG and JPEG as image formats\&.  However it does not support SVG images\&.
For such case, using image converters allows to embed these
unsupported images into the document\&.  One of the image converters;
:ref:`sphinx\&.ext\&.imgconverter <sphinx\&.ext\&.imgconverter>` can convert
a SVG image to PNG format using Imagemagick internally\&.

There are three steps to make your custom image converter:

1\&. Make a subclass of ``ImageConverter`` class
2\&. Override ``conversion_rules``, ``is_available()`` and ``convert()``
3\&. Register your image converter to Sphinx using
   :py:meth:`\&.Sphinx\&.add_post_transform`

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " bool sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.convert ( self, str | os\&.PathLike[str] _from, str | os\&.PathLike[str]
     _to)"

.PP
.nf
Convert an image file to the expected format\&.

*_from* is a path of the source image file, and *_to* is a path
of the destination file\&.

.fi
.PP
 
.PP
Reimplemented in \fBsphinx\&.ext\&.imgconverter\&.ImagemagickConverter\fP\&.
.SS " tuple[str, str] sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.get_conversion_rule ( self, nodes\&.image node)"

.SS " list[str] sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.guess_mimetypes ( self, nodes\&.image node)"

.SS " None sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.handle ( self, nodes\&.image node)"

.PP
Reimplemented from \fBsphinx\&.transforms\&.post_transforms\&.images\&.BaseImageConverter\fP\&.
.SS " bool sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.is_available ( self)"

.PP
.nf
Return the image converter is available or not\&.
.fi
.PP
 
.PP
Reimplemented in \fBsphinx\&.ext\&.imgconverter\&.ImagemagickConverter\fP\&.
.SS " bool sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.match ( self, nodes\&.image node)"

.PP
Reimplemented from \fBsphinx\&.transforms\&.post_transforms\&.images\&.BaseImageConverter\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.available = None\fC [static]\fP"

.SS "list sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.conversion_rules = []\fC [static]\fP"

.SS "int sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.default_priority = 200\fC [static]\fP"

.SS "sphinx\&.transforms\&.post_transforms\&.images\&.ImageConverter\&.imagedir"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
