.TH "sphinx.util.index_entries" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.index_entries
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "list[str] \fBsplit_index_msg\fP (str entry_type, str value)"
.br
.ti -1c
.RI "list[str] \fB_split_into\fP (int n, str type, str value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " list[str] sphinx\&.util\&.index_entries\&._split_into (int n, str type, str value)\fC [protected]\fP"

.PP
.nf
Split an index entry into a given number of parts at semicolons\&.
.fi
.PP
 
.SS " list[str] sphinx\&.util\&.index_entries\&.split_index_msg (str entry_type, str value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
