.TH "sphinx.writers.latex.LaTeXTranslator" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers.latex.LaTeXTranslator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, nodes\&.document document, \fBLaTeXBuilder\fP \fBbuilder\fP, \fBTheme\fP \fBtheme\fP)"
.br
.ti -1c
.RI "None \fBpushbody\fP (self, list[str] newbody)"
.br
.ti -1c
.RI "list[str] \fBpopbody\fP (self)"
.br
.ti -1c
.RI "str \fBastext\fP (self)"
.br
.ti -1c
.RI "str \fBhypertarget\fP (self, str id, bool withdoc=True, bool anchor=True)"
.br
.ti -1c
.RI "str \fBhypertarget_to\fP (self, \fBElement\fP node, bool anchor=False)"
.br
.ti -1c
.RI "str \fBhyperlink\fP (self, str id)"
.br
.ti -1c
.RI "str \fBhyperpageref\fP (self, str id)"
.br
.ti -1c
.RI "str \fBescape\fP (self, str s)"
.br
.ti -1c
.RI "str \fBidescape\fP (self, str id)"
.br
.ti -1c
.RI "str \fBbabel_renewcommand\fP (self, str command, str definition)"
.br
.ti -1c
.RI "str \fBgenerate_indices\fP (self)"
.br
.ti -1c
.RI "str \fBrender\fP (self, str template_name, dict[str, Any] variables)"
.br
.ti -1c
.RI "\fBTable\fP|None \fBtable\fP (self)"
.br
.ti -1c
.RI "None \fBvisit_document\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_document\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_start_of_file\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_start_of_file\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_section\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_section\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_problematic\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_problematic\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_topic\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_topic\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_sidebar\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_glossary\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_glossary\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_productionlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_productionlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_production\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_production\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_transition\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_transition\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_title\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_title\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_subtitle\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_subtitle\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc\fP (self, \fBElement\fP node)"
.br
.RI "Domain-specific object descriptions\&. "
.ti -1c
.RI "None \fBdepart_desc\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_signature\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_signature\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_signature_line\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_signature_line\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_content\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_content\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_name\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_name\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_addname\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_addname\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_type\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_type\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_returns\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_returns\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_parameterlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_parameterlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_type_parameter_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_type_parameter_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_type_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_type_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_optional\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_optional\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_desc_annotation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_desc_annotation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_seealso\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_seealso\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_rubric\fP (self, nodes\&.rubric node)"
.br
.ti -1c
.RI "None \fBdepart_rubric\fP (self, nodes\&.rubric node)"
.br
.ti -1c
.RI "None \fBvisit_footnote\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_footnote\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_label\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_tabular_col_spec\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_table\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_table\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_colspec\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_colspec\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_tgroup\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_tgroup\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_thead\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_thead\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_tbody\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_tbody\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_row\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_row\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_entry\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_entry\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_acks\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_bullet_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_bullet_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_enumerated_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_enumerated_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_list_item\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_list_item\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_definition_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_definition_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_definition_list_item\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_definition_list_item\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_term\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_term\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_classifier\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_classifier\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_definition\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_definition\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_field_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_field_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_field\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_field\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_paragraph\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_paragraph\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_centered\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_centered\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_hlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_hlist\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_hlistcol\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_hlistcol\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "str|None \fBlatex_image_length\fP (self, str width_str, int scale=100)"
.br
.ti -1c
.RI "bool \fBis_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_image\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_image\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_figure\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_figure\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_caption\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_caption\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_legend\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_legend\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_admonition\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_admonition\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_versionmodified\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_versionmodified\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_target\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_target\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_attribution\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_attribution\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_index\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_raw\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_number_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_download_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_download_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_pending_xref\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_pending_xref\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_emphasis\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_emphasis\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_literal_emphasis\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_literal_emphasis\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_strong\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_strong\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_literal_strong\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_literal_strong\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_abbreviation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_abbreviation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_manpage\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_manpage\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_title_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_title_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_thebibliography\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_thebibliography\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_citation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_citation\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_citation_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_citation_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_literal\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_literal\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_footnote_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_footnotemark\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_footnotemark\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_footnotetext\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_footnotetext\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_captioned_literal_block\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_captioned_literal_block\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_literal_block\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_literal_block\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_line\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_line\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_line_block\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_line_block\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_block_quote\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_block_quote\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_option\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_option\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_option_argument\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_option_argument\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_option_group\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_option_group\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_option_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_option_list\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_option_list_item\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_option_list_item\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_option_string\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_description\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_description\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_superscript\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_superscript\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_subscript\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_subscript\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_inline\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_generated\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_generated\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_compound\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_compound\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_container\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_container\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_decoration\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_decoration\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_header\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_footer\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_docinfo\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "str \fBencode\fP (self, str text)"
.br
.ti -1c
.RI "str \fBencode_uri\fP (self, str text)"
.br
.ti -1c
.RI "None \fBvisit_Text\fP (self, \fBText\fP node)"
.br
.ti -1c
.RI "None \fBdepart_Text\fP (self, \fBText\fP node)"
.br
.ti -1c
.RI "None \fBvisit_comment\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_meta\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_system_message\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_system_message\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBvisit_math\fP (self, nodes\&.math node)"
.br
.ti -1c
.RI "None \fBvisit_math_block\fP (self, nodes\&.math_block node)"
.br
.ti -1c
.RI "None \fBvisit_math_reference\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fBdepart_math_reference\fP (self, \fBElement\fP node)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP
.in +1c
.ti -1c
.RI "None \fBdispatch_visit\fP (self, \fBNode\fP node)"
.br
.ti -1c
.RI "None \fBdispatch_departure\fP (self, \fBNode\fP node)"
.br
.ti -1c
.RI "None \fBunknown_visit\fP (self, \fBNode\fP node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtheme\fP"
.br
.ti -1c
.RI "\fBin_title\fP"
.br
.ti -1c
.RI "\fBin_production_list\fP"
.br
.ti -1c
.RI "\fBin_footnote\fP"
.br
.ti -1c
.RI "\fBin_caption\fP"
.br
.ti -1c
.RI "\fBin_term\fP"
.br
.ti -1c
.RI "\fBneeds_linetrimming\fP"
.br
.ti -1c
.RI "\fBin_minipage\fP"
.br
.ti -1c
.RI "\fBno_latex_floats\fP"
.br
.ti -1c
.RI "\fBfirst_document\fP"
.br
.ti -1c
.RI "\fBthis_is_the_title\fP"
.br
.ti -1c
.RI "\fBliteral_whitespace\fP"
.br
.ti -1c
.RI "\fBin_parsed_literal\fP"
.br
.ti -1c
.RI "\fBcompact_list\fP"
.br
.ti -1c
.RI "\fBfirst_param\fP"
.br
.ti -1c
.RI "\fBin_desc_signature\fP"
.br
.ti -1c
.RI "\fBelements\fP"
.br
.ti -1c
.RI "\fBsectionnames\fP"
.br
.ti -1c
.RI "\fBtop_sectionlevel\fP"
.br
.ti -1c
.RI "\fBnumfig_secnum_depth\fP"
.br
.ti -1c
.RI "\fBbabel\fP"
.br
.ti -1c
.RI "\fBhighlighter\fP"
.br
.ti -1c
.RI "\fBbody\fP"
.br
.ti -1c
.RI "\fBsectionlevel\fP"
.br
.ti -1c
.RI "\fBhas_tp_list\fP"
.br
.ti -1c
.RI "\fBorphan_tp_list\fP"
.br
.ti -1c
.RI "\fBis_first_param\fP"
.br
.ti -1c
.RI "\fBoptional_param_level\fP"
.br
.ti -1c
.RI "\fBparams_left_at_level\fP"
.br
.ti -1c
.RI "\fBparam_group_index\fP"
.br
.ti -1c
.RI "\fBlist_is_required_param\fP"
.br
.ti -1c
.RI "\fBrequired_params_left\fP"
.br
.ti -1c
.RI "\fBparam_separator\fP"
.br
.ti -1c
.RI "\fBmulti_line_parameter_list\fP"
.br
.ti -1c
.RI "\fBtrailing_comma\fP"
.br
.ti -1c
.RI "\fBmax_optional_param_level\fP"
.br
.ti -1c
.RI "\fBnext_table_colspec\fP"
.br
.ti -1c
.RI "\fBtables\fP"
.br
.ti -1c
.RI "\fBtable\fP"
.br
.in -1c

Public Attributes inherited from \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP
.in +1c
.ti -1c
.RI "\fBbuilder\fP"
.br
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBsettings\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBLaTeXBuilder\fP \fBbuilder\fP"
.br
.ti -1c
.RI "int \fBsecnumdepth\fP = 2"
.br
.ti -1c
.RI "bool \fBignore_missing_images\fP = False"
.br
.ti -1c
.RI "None \fBdepart_sidebar\fP = \fBdepart_topic\fP"
.br
.ti -1c
.RI "None \fBvisit_field_name\fP = \fBvisit_term\fP"
.br
.ti -1c
.RI "None \fBdepart_field_name\fP = \fBdepart_term\fP"
.br
.ti -1c
.RI "None \fBvisit_field_body\fP = \fBvisit_definition\fP"
.br
.ti -1c
.RI "None \fBdepart_field_body\fP = \fBdepart_definition\fP"
.br
.ti -1c
.RI "None \fBvisit_attention\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_attention\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_caution\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_caution\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_danger\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_danger\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_error\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_error\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_hint\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_hint\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_important\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_important\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_note\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_note\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_tip\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_tip\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_warning\fP = \fB_visit_named_admonition\fP"
.br
.ti -1c
.RI "None \fBdepart_warning\fP = \fB_depart_named_admonition\fP"
.br
.ti -1c
.RI "None \fBvisit_doctest_block\fP = \fBvisit_literal_block\fP"
.br
.ti -1c
.RI "None \fBdepart_doctest_block\fP = \fBdepart_literal_block\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "None \fB_visit_signature_line\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fB_depart_signature_line\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fB_visit_sig_parameter_list\fP (self, \fBElement\fP node, type[\fBElement\fP] parameter_group)"
.br
.ti -1c
.RI "None \fB_visit_sig_parameter\fP (self, \fBElement\fP node, str parameter_macro)"
.br
.ti -1c
.RI "None \fB_depart_sig_parameter\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fB_visit_named_admonition\fP (self, \fBElement\fP node)"
.br
.ti -1c
.RI "None \fB_depart_named_admonition\fP (self, \fBElement\fP node)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP
.in +1c
.ti -1c
.RI "\fB_domains\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.__init__ ( self, nodes\&.document document, \fBLaTeXBuilder\fP builder, \fBTheme\fP
     theme)"

.PP
Reimplemented from \fBsphinx\&.util\&.docutils\&.SphinxTranslator\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&._depart_named_admonition ( self, \fBElement\fP node)\fC [protected]\fP"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&._depart_sig_parameter ( self, \fBElement\fP node)\fC [protected]\fP"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&._depart_signature_line ( self, \fBElement\fP node)\fC [protected]\fP"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&._visit_named_admonition ( self, \fBElement\fP node)\fC [protected]\fP"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&._visit_sig_parameter ( self, \fBElement\fP node, str parameter_macro)\fC [protected]\fP"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&._visit_sig_parameter_list ( self, \fBElement\fP node, type[\fBElement\fP]
     parameter_group)\fC [protected]\fP"

.PP
.nf
Visit a signature parameters or type parameters list\&.

The *parameter_group* value is the type of a child node acting as a required parameter
or as a set of contiguous optional parameters\&.

The caller is responsible for closing adding surrounding LaTeX macro argument start
and stop tokens\&.

.fi
.PP
 
.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&._visit_signature_line ( self, \fBElement\fP node)\fC [protected]\fP"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.astext ( self)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.babel_renewcommand ( self, str command, str definition)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_abbreviation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_admonition ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_attribution ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_block_quote ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_bullet_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_caption ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_captioned_literal_block ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_centered ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_citation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_citation_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_classifier ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_colspec ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_compound ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_container ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_decoration ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_definition ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_definition_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_definition_list_item ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_addname ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_annotation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_content ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_inline ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_name ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_optional ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_parameter ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_parameterlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_returns ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_signature ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_signature_line ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_type ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_type_parameter ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_desc_type_parameter_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_description ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_document ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_download_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_emphasis ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_entry ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_enumerated_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_field ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_field_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_figure ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_footnote ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_footnotemark ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_footnotetext ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_generated ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_glossary ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_hlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_hlistcol ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_image ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_inline ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_legend ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_line ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_line_block ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_list_item ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_literal ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_literal_block ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_literal_emphasis ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_literal_strong ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_manpage ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_math_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_option ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_option_argument ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_option_group ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_option_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_option_list_item ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_paragraph ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_pending_xref ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_problematic ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_production ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_productionlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_row ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_rubric ( self, nodes\&.rubric node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_section ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_seealso ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_start_of_file ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_strong ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_subscript ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_subtitle ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_superscript ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_system_message ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_table ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_target ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_tbody ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_term ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_Text ( self, \fBText\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_tgroup ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_thead ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_thebibliography ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_title ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_title_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_topic ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_transition ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_versionmodified ( self, \fBElement\fP node)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.encode ( self, str text)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.encode_uri ( self, str text)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.escape ( self, str s)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.generate_indices ( self)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.hyperlink ( self, str id)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.hyperpageref ( self, str id)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.hypertarget ( self, str id, bool  withdoc = \fCTrue\fP, bool  anchor = \fCTrue\fP)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.hypertarget_to ( self, \fBElement\fP node, bool  anchor = \fCFalse\fP)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.idescape ( self, str id)"

.SS " bool sphinx\&.writers\&.latex\&.LaTeXTranslator\&.is_inline ( self, \fBElement\fP node)"

.PP
.nf
Check whether a node represents an inline element\&.
.fi
.PP
 
.SS " str | None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.latex_image_length ( self, str width_str, int  scale = \fC100\fP)"

.SS " list[str] sphinx\&.writers\&.latex\&.LaTeXTranslator\&.popbody ( self)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.pushbody ( self, list[str] newbody)"

.SS " str sphinx\&.writers\&.latex\&.LaTeXTranslator\&.render ( self, str template_name, dict[str, Any] variables)"

.SS " \fBTable\fP | None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.table ( self)"

.PP
.nf
Get current table\&.
.fi
.PP
 
.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_abbreviation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_acks ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_admonition ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_attribution ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_block_quote ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_bullet_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_caption ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_captioned_literal_block ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_centered ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_citation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_citation_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_classifier ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_colspec ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_comment ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_compound ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_container ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_decoration ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_definition ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_definition_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_definition_list_item ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc ( self, \fBElement\fP node)"

.PP
Domain-specific object descriptions\&. 
.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_addname ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_annotation ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_content ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_inline ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_name ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_optional ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_parameter ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_parameterlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_returns ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_signature ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_signature_line ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_type ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_type_parameter ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_desc_type_parameter_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_description ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_docinfo ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_document ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_download_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_emphasis ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_entry ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_enumerated_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_field ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_field_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_figure ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_footer ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_footnote ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_footnote_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_footnotemark ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_footnotetext ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_generated ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_glossary ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_header ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_hlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_hlistcol ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_image ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_index ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_inline ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_label ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_legend ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_line ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_line_block ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_list_item ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_literal ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_literal_block ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_literal_emphasis ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_literal_strong ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_manpage ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_math ( self, nodes\&.math node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_math_block ( self, nodes\&.math_block node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_math_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_meta ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_number_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_option ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_option_argument ( self, \fBElement\fP node)"

.PP
.nf
The delimiter between an option and its argument\&.
.fi
.PP
 
.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_option_group ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_option_list ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_option_list_item ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_option_string ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_paragraph ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_pending_xref ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_problematic ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_production ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_productionlist ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_raw ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_row ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_rubric ( self, nodes\&.rubric node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_section ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_seealso ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_sidebar ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_start_of_file ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_strong ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_subscript ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_subtitle ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_superscript ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_system_message ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_table ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_tabular_col_spec ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_target ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_tbody ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_term ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_Text ( self, \fBText\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_tgroup ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_thead ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_thebibliography ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_title ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_title_reference ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_topic ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_transition ( self, \fBElement\fP node)"

.SS " None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_versionmodified ( self, \fBElement\fP node)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.babel"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.body"

.SS "\fBLaTeXBuilder\fP sphinx\&.writers\&.latex\&.LaTeXTranslator\&.builder\fC [static]\fP"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.compact_list"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_attention = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_caution = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_danger = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_doctest_block = \fBdepart_literal_block\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_error = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_field_body = \fBdepart_definition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_field_name = \fBdepart_term\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_hint = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_important = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_note = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_sidebar = \fBdepart_topic\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_tip = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.depart_warning = \fB_depart_named_admonition\fP\fC [static]\fP"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.elements"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.first_document"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.first_param"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.has_tp_list"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.highlighter"

.SS "bool sphinx\&.writers\&.latex\&.LaTeXTranslator\&.ignore_missing_images = False\fC [static]\fP"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.in_caption"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.in_desc_signature"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.in_footnote"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.in_minipage"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.in_parsed_literal"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.in_production_list"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.in_term"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.in_title"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.is_first_param"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.list_is_required_param"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.literal_whitespace"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.max_optional_param_level"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.multi_line_parameter_list"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.needs_linetrimming"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.next_table_colspec"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.no_latex_floats"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.numfig_secnum_depth"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.optional_param_level"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.orphan_tp_list"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.param_group_index"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.param_separator"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.params_left_at_level"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.required_params_left"

.SS "int sphinx\&.writers\&.latex\&.LaTeXTranslator\&.secnumdepth = 2\fC [static]\fP"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.sectionlevel"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.sectionnames"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.table"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.tables"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.theme"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.this_is_the_title"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.top_sectionlevel"

.SS "sphinx\&.writers\&.latex\&.LaTeXTranslator\&.trailing_comma"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_attention = \fB_visit_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_caution = \fB_visit_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_danger = \fB_visit_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_doctest_block = \fBvisit_literal_block\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_error = \fB_visit_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_field_body = \fBvisit_definition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_field_name = \fBvisit_term\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_hint = \fB_visit_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_important = \fB_visit_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_note = \fB_visit_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_tip = \fB_visit_named_admonition\fP\fC [static]\fP"

.SS "None sphinx\&.writers\&.latex\&.LaTeXTranslator\&.visit_warning = \fB_visit_named_admonition\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
