.TH "sphinx.util.cfamily.BaseParser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.cfamily.BaseParser
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsphinx\&.domains\&.c\&._parser\&.DefinitionParser\fP, and \fBsphinx\&.domains\&.cpp\&._parser\&.DefinitionParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBdefinition\fP, *\fBnodes\&.Node\fP|tuple[str, int]|str \fBlocation\fP, \fBConfig\fP \fBconfig\fP)"
.br
.ti -1c
.RI "str \fBlanguage\fP (self)"
.br
.ti -1c
.RI "None \fBstatus\fP (self, str msg)"
.br
.ti -1c
.RI "NoReturn \fBfail\fP (self, str msg)"
.br
.ti -1c
.RI "None \fBwarn\fP (self, str msg)"
.br
.ti -1c
.RI "bool \fBmatch\fP (self, re\&.Pattern[str] regex)"
.br
.ti -1c
.RI "bool \fBskip_string\fP (self, str string)"
.br
.ti -1c
.RI "bool \fBskip_word\fP (self, str word)"
.br
.ti -1c
.RI "bool \fBskip_ws\fP (self)"
.br
.ti -1c
.RI "bool \fBskip_word_and_ws\fP (self, str word)"
.br
.ti -1c
.RI "bool \fBskip_string_and_ws\fP (self, str string)"
.br
.ti -1c
.RI "bool \fBeof\fP (self)"
.br
.ti -1c
.RI "str \fBcurrent_char\fP (self)"
.br
.ti -1c
.RI "str \fBmatched_text\fP (self)"
.br
.ti -1c
.RI "str \fBread_rest\fP (self)"
.br
.ti -1c
.RI "None \fBassert_end\fP (self, *bool allowSemicolon=False)"
.br
.ti -1c
.RI "Sequence[str] \fBid_attributes\fP (self)"
.br
.ti -1c
.RI "Sequence[str] \fBparen_attributes\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdefinition\fP"
.br
.ti -1c
.RI "\fBlocation\fP"
.br
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBpos\fP"
.br
.ti -1c
.RI "\fBend\fP"
.br
.ti -1c
.RI "\fBallowFallbackExpressionParsing\fP"
.br
.ti -1c
.RI "\fBotherErrors\fP"
.br
.ti -1c
.RI "\fBlast_match\fP"
.br
.ti -1c
.RI "\fBcurrent_char\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDefinitionError\fP \fB_make_multi_error\fP (self, list[Any] errors, str header)"
.br
.ti -1c
.RI "str \fB_parse_balanced_token_seq\fP (self, list[str] \fBend\fP)"
.br
.ti -1c
.RI "\fBASTAttribute\fP|None \fB_parse_attribute\fP (self)"
.br
.ti -1c
.RI "\fBASTAttributeList\fP \fB_parse_attribute_list\fP (self)"
.br
.ti -1c
.RI "\fBASTBaseParenExprList\fP|None \fB_parse_paren_expression_list\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_previous_state\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.util\&.cfamily\&.BaseParser\&.__init__ ( self, str definition, *\fBnodes\&.Node\fP | tuple[str, int] | str location, \fBConfig\fP config)"

.SH "Member Function Documentation"
.PP 
.SS " \fBDefinitionError\fP sphinx\&.util\&.cfamily\&.BaseParser\&._make_multi_error ( self, list[Any] errors, str header)\fC [protected]\fP"

.SS " \fBASTAttribute\fP | None sphinx\&.util\&.cfamily\&.BaseParser\&._parse_attribute ( self)\fC [protected]\fP"

.SS " \fBASTAttributeList\fP sphinx\&.util\&.cfamily\&.BaseParser\&._parse_attribute_list ( self)\fC [protected]\fP"

.SS " str sphinx\&.util\&.cfamily\&.BaseParser\&._parse_balanced_token_seq ( self, list[str] end)\fC [protected]\fP"

.SS " \fBASTBaseParenExprList\fP | None sphinx\&.util\&.cfamily\&.BaseParser\&._parse_paren_expression_list ( self)\fC [protected]\fP"

.PP
Reimplemented in \fBsphinx\&.domains\&.c\&._parser\&.DefinitionParser\fP, and \fBsphinx\&.domains\&.cpp\&._parser\&.DefinitionParser\fP\&.
.SS " None sphinx\&.util\&.cfamily\&.BaseParser\&.assert_end ( self, *bool  allowSemicolon = \fCFalse\fP)"

.SS " str sphinx\&.util\&.cfamily\&.BaseParser\&.current_char ( self)"

.SS " bool sphinx\&.util\&.cfamily\&.BaseParser\&.eof ( self)"

.SS " NoReturn sphinx\&.util\&.cfamily\&.BaseParser\&.fail ( self, str msg)"

.SS " Sequence[str] sphinx\&.util\&.cfamily\&.BaseParser\&.id_attributes ( self)"

.PP
Reimplemented in \fBsphinx\&.domains\&.c\&._parser\&.DefinitionParser\fP, and \fBsphinx\&.domains\&.cpp\&._parser\&.DefinitionParser\fP\&.
.SS " str sphinx\&.util\&.cfamily\&.BaseParser\&.language ( self)"

.PP
Reimplemented in \fBsphinx\&.domains\&.c\&._parser\&.DefinitionParser\fP, and \fBsphinx\&.domains\&.cpp\&._parser\&.DefinitionParser\fP\&.
.SS " bool sphinx\&.util\&.cfamily\&.BaseParser\&.match ( self, re\&.Pattern[str] regex)"

.SS " str sphinx\&.util\&.cfamily\&.BaseParser\&.matched_text ( self)"

.SS " Sequence[str] sphinx\&.util\&.cfamily\&.BaseParser\&.paren_attributes ( self)"

.PP
Reimplemented in \fBsphinx\&.domains\&.c\&._parser\&.DefinitionParser\fP, and \fBsphinx\&.domains\&.cpp\&._parser\&.DefinitionParser\fP\&.
.SS " str sphinx\&.util\&.cfamily\&.BaseParser\&.read_rest ( self)"

.SS " bool sphinx\&.util\&.cfamily\&.BaseParser\&.skip_string ( self, str string)"

.SS " bool sphinx\&.util\&.cfamily\&.BaseParser\&.skip_string_and_ws ( self, str string)"

.SS " bool sphinx\&.util\&.cfamily\&.BaseParser\&.skip_word ( self, str word)"

.SS " bool sphinx\&.util\&.cfamily\&.BaseParser\&.skip_word_and_ws ( self, str word)"

.SS " bool sphinx\&.util\&.cfamily\&.BaseParser\&.skip_ws ( self)"

.SS " None sphinx\&.util\&.cfamily\&.BaseParser\&.status ( self, str msg)"

.SS " None sphinx\&.util\&.cfamily\&.BaseParser\&.warn ( self, str msg)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.util\&.cfamily\&.BaseParser\&._previous_state\fC [protected]\fP"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.allowFallbackExpressionParsing"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.config"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.current_char"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.definition"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.end"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.last_match"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.location"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.otherErrors"

.SS "sphinx\&.util\&.cfamily\&.BaseParser\&.pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
