.TH "sphinx.writers.xml.PseudoXMLWriter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.writers.xml.PseudoXMLWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseXMLWriter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBBuilder\fP \fBbuilder\fP)"
.br
.ti -1c
.RI "None \fBtranslate\fP (self)"
.br
.ti -1c
.RI "bool \fBsupports\fP (self, str format)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbuilder\fP"
.br
.ti -1c
.RI "\fBoutput\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBsupported\fP = ('pprint', 'pformat', 'pseudoxml')"
.br
.ti -1c
.RI "str \fBconfig_section\fP = 'pseudoxml writer'"
.br
.ti -1c
.RI "tuple \fBconfig_section_dependencies\fP = ('writers',)"
.br
.ti -1c
.RI "str \fBoutput\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.__init__ ( self, \fBBuilder\fP builder)"

.SH "Member Function Documentation"
.PP 
.SS " bool sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.supports ( self, str format)"

.PP
.nf
All format-specific elements are supported\&.
.fi
.PP
 
.SS " None sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.translate ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.builder"

.SS "str sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.config_section = 'pseudoxml writer'\fC [static]\fP"

.SS "tuple sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.config_section_dependencies = ('writers',)\fC [static]\fP"

.SS "str sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.output\fC [static]\fP"

.SS "sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.output"

.SS "tuple sphinx\&.writers\&.xml\&.PseudoXMLWriter\&.supported = ('pprint', 'pformat', 'pseudoxml')\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
