.TH "sphinx.util.requests._IgnoredRedirection" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.util.requests._IgnoredRedirection
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBdestination\fP, int \fBstatus_code\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdestination\fP"
.br
.ti -1c
.RI "\fBstatus_code\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Sphinx-internal exception raised when an HTTP redirect is ignored
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.util\&.requests\&._IgnoredRedirection\&.__init__ ( self, str destination, int status_code)"

.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.util\&.requests\&._IgnoredRedirection\&.destination"

.SS "sphinx\&.util\&.requests\&._IgnoredRedirection\&.status_code"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
