.TH "sphinx.ext.intersphinx._load" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.ext.intersphinx._load
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_InvConfig\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBvalidate_intersphinx_mapping\fP (\fBSphinx\fP app, \fBConfig\fP config)"
.br
.ti -1c
.RI "None \fBload_mappings\fP (\fBSphinx\fP app)"
.br
.ti -1c
.RI "bool \fB_fetch_inventory_group\fP (*\fB_IntersphinxProject\fP project, dict[InventoryURI, InventoryCacheEntry] cache, int now, \fB_InvConfig\fP config, Path srcdir)"
.br
.ti -1c
.RI "Inventory \fBfetch_inventory\fP (\fBSphinx\fP app, InventoryURI uri, str inv)"
.br
.ti -1c
.RI "\fB_Inventory\fP \fB_fetch_inventory\fP (*InventoryURI target_uri, str inv_location, \fB_InvConfig\fP config, Path srcdir)"
.br
.ti -1c
.RI "tuple[bytes, str] \fB_fetch_inventory_url\fP (*InventoryURI target_uri, str inv_location, \fB_InvConfig\fP config)"
.br
.ti -1c
.RI "bytes \fB_fetch_inventory_file\fP (*str inv_location, Path srcdir)"
.br
.ti -1c
.RI "str \fB_get_safe_url\fP (str url)"
.br
.ti -1c
.RI "str \fB_strip_basic_auth\fP (str url)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This module contains the code for loading intersphinx inventories\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " \fB_Inventory\fP sphinx\&.ext\&.intersphinx\&._load\&._fetch_inventory (*InventoryURI target_uri, str inv_location, \fB_InvConfig\fP config, Path
 srcdir)\fC [protected]\fP"

.PP
.nf
Fetch, parse and return an intersphinx inventory file\&.
.fi
.PP
 
.SS " bytes sphinx\&.ext\&.intersphinx\&._load\&._fetch_inventory_file (*str inv_location, Path srcdir)\fC [protected]\fP"

.SS " bool sphinx\&.ext\&.intersphinx\&._load\&._fetch_inventory_group (*\fB_IntersphinxProject\fP project, dict[InventoryURI, InventoryCacheEntry] cache, int now, \fB_InvConfig\fP config, Path srcdir)\fC [protected]\fP"

.SS " tuple[bytes, str] sphinx\&.ext\&.intersphinx\&._load\&._fetch_inventory_url (*InventoryURI target_uri, str inv_location, \fB_InvConfig\fP
 config)\fC [protected]\fP"

.SS " str sphinx\&.ext\&.intersphinx\&._load\&._get_safe_url (str url)\fC [protected]\fP"

.PP
.nf
Gets version of *url* with basic auth passwords obscured\&. This function
returns results suitable for printing and logging\&.

E\&.g\&.: https://user:12345@example\&.com => https://user@example\&.com

:param url: a url
:type url: ``str``

:return: *url* with password removed
:rtype: ``str``

.fi
.PP
 
.SS " str sphinx\&.ext\&.intersphinx\&._load\&._strip_basic_auth (str url)\fC [protected]\fP"

.PP
.nf
Returns *url* with basic auth credentials removed\&. Also returns the
basic auth username and password if they're present in *url*\&.

E\&.g\&.: https://user:pass@example\&.com => https://example\&.com

*url* need not include basic auth credentials\&.

:param url: url which may or may not contain basic auth credentials
:type url: ``str``

:return: *url* with any basic auth creds removed
:rtype: ``str``

.fi
.PP
 
.SS " Inventory sphinx\&.ext\&.intersphinx\&._load\&.fetch_inventory (\fBSphinx\fP app, InventoryURI uri, str inv)"

.PP
.nf
Fetch, parse and return an intersphinx inventory file\&.
.fi
.PP
 
.SS " None sphinx\&.ext\&.intersphinx\&._load\&.load_mappings (\fBSphinx\fP app)"

.PP
.nf
Load all intersphinx mappings into the environment\&.

The intersphinx mappings are expected to be normalized\&.

.fi
.PP
 
.SS " None sphinx\&.ext\&.intersphinx\&._load\&.validate_intersphinx_mapping (\fBSphinx\fP app, \fBConfig\fP config)"

.PP
.nf
Validate and normalise :confval:`intersphinx_mapping`\&.

Ensure that:

* Keys are non-empty strings\&.
* Values are two-element tuples or lists\&.
* The first element of each value pair (the target URI)
  is a non-empty string\&.
* The second element of each value pair (inventory locations)
  is a tuple of non-empty strings or None\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
