.TH "sphinx.builders.latex.theming.BuiltInTheme" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.builders.latex.theming.BuiltInTheme
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsphinx\&.builders\&.latex\&.theming\&.Theme\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBname\fP, \fBConfig\fP config)"
.br
.in -1c

Public Member Functions inherited from \fBsphinx\&.builders\&.latex\&.theming\&.Theme\fP
.in +1c
.ti -1c
.RI "None \fBupdate\fP (self, \fBConfig\fP config)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdocclass\fP"
.br
.ti -1c
.RI "\fBwrapperclass\fP"
.br
.ti -1c
.RI "\fBtoplevel_sectioning\fP"
.br
.in -1c

Public Attributes inherited from \fBsphinx\&.builders\&.latex\&.theming\&.Theme\fP
.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBdocclass\fP"
.br
.ti -1c
.RI "\fBwrapperclass\fP"
.br
.ti -1c
.RI "\fBpapersize\fP"
.br
.ti -1c
.RI "\fBpointsize\fP"
.br
.ti -1c
.RI "\fBtoplevel_sectioning\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBsphinx\&.builders\&.latex\&.theming\&.Theme\fP
.in +1c
.ti -1c
.RI "list \fBLATEX_ELEMENTS_KEYS\fP = ['\fBpapersize\fP', '\fBpointsize\fP']"
.br
.ti -1c
.RI "list \fBUPDATABLE_KEYS\fP = ['\fBpapersize\fP', '\fBpointsize\fP']"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A built-in LaTeX theme\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None sphinx\&.builders\&.latex\&.theming\&.BuiltInTheme\&.__init__ ( self, str name, \fBConfig\fP config)"

.PP
Reimplemented from \fBsphinx\&.builders\&.latex\&.theming\&.Theme\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.builders\&.latex\&.theming\&.BuiltInTheme\&.docclass"

.SS "sphinx\&.builders\&.latex\&.theming\&.BuiltInTheme\&.toplevel_sectioning"

.SS "sphinx\&.builders\&.latex\&.theming\&.BuiltInTheme\&.wrapperclass"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
