.TH "sphinx.addnodes.production" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.addnodes.production
.SH SYNOPSIS
.br
.PP
.PP
Inherits nodes\&.Part, nodes\&.Inline, and nodes\&.FixedTextElement\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Node for a single grammar production rule\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
