.TH "sphinx.parsers.Parser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.parsers.Parser
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdocutils\&.parsers\&.Parser\fP\&.
.PP
Inherited by \fBsphinx\&.parsers\&.RSTParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fBset_application\fP (self, \fBSphinx\fP app)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.parsers\&.Parser\fP
.in +1c
.ti -1c
.RI "\fBparse\fP (self, \fBinputstring\fP, \fBdocument\fP)"
.br
.ti -1c
.RI "\fBsetup_parse\fP (self, \fBinputstring\fP, \fBdocument\fP)"
.br
.ti -1c
.RI "\fBfinish_parse\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.Component\fP
.in +1c
.ti -1c
.RI "\fBsupports\fP (self, format)"
.br
.in -1c

Public Member Functions inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "\fBget_transforms\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBenv\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.parsers\&.Parser\fP
.in +1c
.ti -1c
.RI "\fBinputstring\fP"
.br
.ti -1c
.RI "\fBdocument\fP"
.br
.in -1c

Public Attributes inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "\fBdefault_transforms\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBConfig\fP \fBconfig\fP"
.br
.ti -1c
.RI "\fBBuildEnvironment\fP \fBenv\fP"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.parsers\&.Parser\fP
.in +1c
.ti -1c
.RI "tuple \fBsettings_spec\fP"
.br
.ti -1c
.RI "str \fBcomponent_type\fP = 'parser'"
.br
.ti -1c
.RI "str \fBconfig_section\fP = 'parsers'"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.Component\fP
.in +1c
.ti -1c
.RI "\fBcomponent_type\fP = None"
.br
.ti -1c
.RI "tuple \fBsupported\fP = ()"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.SettingsSpec\fP
.in +1c
.ti -1c
.RI "tuple \fBsettings_spec\fP = ()"
.br
.ti -1c
.RI "\fBsettings_defaults\fP = None"
.br
.ti -1c
.RI "\fBsettings_default_overrides\fP = None"
.br
.ti -1c
.RI "tuple \fBrelative_path_settings\fP = ()"
.br
.ti -1c
.RI "\fBconfig_section\fP = None"
.br
.ti -1c
.RI "\fBconfig_section_dependencies\fP = None"
.br
.in -1c

Static Public Attributes inherited from \fBdocutils\&.TransformSpec\fP
.in +1c
.ti -1c
.RI "tuple \fBdefault_transforms\fP = ()"
.br
.ti -1c
.RI "tuple \fBunknown_reference_resolvers\fP = ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_app\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A base class of source parsers\&.

The additional parsers should inherit this class
instead of ``docutils\&.parsers\&.Parser``\&.
Compared with ``docutils\&.parsers\&.Parser``,
this class improves accessibility to Sphinx APIs\&.

The subclasses can access sphinx core runtime objects (app, config and env)\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " None sphinx\&.parsers\&.Parser\&.set_application ( self, \fBSphinx\fP app)"

.PP
.nf
set_application will be called from Sphinx to set app and other instance variables

:param sphinx\&.application\&.Sphinx app: Sphinx application object

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "sphinx\&.parsers\&.Parser\&._app\fC [protected]\fP"

.SS "\fBConfig\fP sphinx\&.parsers\&.Parser\&.config\fC [static]\fP"

.SS "sphinx\&.parsers\&.Parser\&.config"

.SS "\fBBuildEnvironment\fP sphinx\&.parsers\&.Parser\&.env\fC [static]\fP"

.SS "sphinx\&.parsers\&.Parser\&.env"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
