.TH "sphinx.domains.python._annotations" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.domains.python._annotations
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_TypeParameterListParser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "tuple[str, str, str, bool] \fBparse_reftarget\fP (str reftarget, bool suppress_prefix=False)"
.br
.ti -1c
.RI "\fBaddnodes\&.pending_xref\fP \fBtype_to_xref\fP (str target, \fBBuildEnvironment\fP env, *bool suppress_prefix=False)"
.br
.ti -1c
.RI "list[\fBNode\fP] \fB_parse_annotation\fP (str annotation, \fBBuildEnvironment\fP env)"
.br
.ti -1c
.RI "\fBaddnodes\&.desc_type_parameter_list\fP \fB_parse_type_list\fP (str tp_list, \fBBuildEnvironment\fP env, bool multi_line_parameter_list=False, bool trailing_comma=True)"
.br
.ti -1c
.RI "\fBaddnodes\&.desc_parameterlist\fP \fB_parse_arglist\fP (str arglist, \fBBuildEnvironment\fP env, bool multi_line_parameter_list=False, bool trailing_comma=True)"
.br
.ti -1c
.RI "\fBaddnodes\&.desc_parameter\fP \fB_positional_only_separator\fP ()"
.br
.ti -1c
.RI "\fBaddnodes\&.desc_parameter\fP \fB_keyword_only_separator\fP ()"
.br
.ti -1c
.RI "None \fB_pseudo_parse_arglist\fP (\fBdesc_signature\fP signode, str arglist, bool multi_line_parameter_list=False, bool trailing_comma=True)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " \fBaddnodes\&.desc_parameter\fP sphinx\&.domains\&.python\&._annotations\&._keyword_only_separator ()\fC [protected]\fP"

.SS " list[\fBNode\fP] sphinx\&.domains\&.python\&._annotations\&._parse_annotation (str annotation, \fBBuildEnvironment\fP env)\fC [protected]\fP"

.PP
.nf
Parse type annotation\&.
.fi
.PP
 
.SS " \fBaddnodes\&.desc_parameterlist\fP sphinx\&.domains\&.python\&._annotations\&._parse_arglist (str arglist, \fBBuildEnvironment\fP env, bool  multi_line_parameter_list = \fCFalse\fP, bool  trailing_comma = \fCTrue\fP)\fC [protected]\fP"

.PP
.nf
Parse a list of arguments using AST parser
.fi
.PP
 
.SS " \fBaddnodes\&.desc_type_parameter_list\fP sphinx\&.domains\&.python\&._annotations\&._parse_type_list (str tp_list, \fBBuildEnvironment\fP env, bool  multi_line_parameter_list = \fCFalse\fP, bool  trailing_comma = \fCTrue\fP)\fC [protected]\fP"

.PP
.nf
Parse a list of type parameters according to PEP 695\&.
.fi
.PP
 
.SS " \fBaddnodes\&.desc_parameter\fP sphinx\&.domains\&.python\&._annotations\&._positional_only_separator ()\fC [protected]\fP"

.SS " None sphinx\&.domains\&.python\&._annotations\&._pseudo_parse_arglist (\fBdesc_signature\fP signode, str arglist, bool  multi_line_parameter_list = \fCFalse\fP, bool  trailing_comma = \fCTrue\fP)\fC [protected]\fP"

.PP
.nf
'Parse' a list of arguments separated by commas\&.

Arguments can have 'optional' annotations given by enclosing them in
brackets\&.  Currently, this will split at any comma, even if it's inside a
string literal (e\&.g\&. default argument value)\&.

.fi
.PP
 
.SS " tuple[str, str, str, bool] sphinx\&.domains\&.python\&._annotations\&.parse_reftarget (str reftarget, bool  suppress_prefix = \fCFalse\fP)"

.PP
.nf
Parse a type string and return (reftype, reftarget, title, refspecific flag)
.fi
.PP
 
.SS " \fBaddnodes\&.pending_xref\fP sphinx\&.domains\&.python\&._annotations\&.type_to_xref (str target, \fBBuildEnvironment\fP env, *bool  suppress_prefix = \fCFalse\fP)"

.PP
.nf
Convert a type string to a cross reference node\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
