.TH "sphinx.directives" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphinx.directives
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBadmonitions\fP"
.br
.ti -1c
.RI "namespace \fBcode\fP"
.br
.ti -1c
.RI "namespace \fBother\fP"
.br
.ti -1c
.RI "namespace \fBpatches\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDefaultDomain\fP"
.br
.ti -1c
.RI "class \fBDefaultRole\fP"
.br
.ti -1c
.RI "class \fBObjectDescription\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int|None \fBoptional_int\fP (str argument)"
.br
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsetup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBnl_escape_re\fP = re\&.compile(r'\\\\\\n')"
.br
.ti -1c
.RI "\fBstrip_backslash_re\fP = re\&.compile(r'\\\\(\&.)')"
.br
.ti -1c
.RI "\fBObjDescT\fP = TypeVar('ObjDescT')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handlers for additional ReST directives\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " int | None sphinx\&.directives\&.optional_int (str argument)"

.PP
.nf
Check for an integer argument or None value; raise ``ValueError`` if not\&.
.fi
.PP
 
.SS " \fBExtensionMetadata\fP sphinx\&.directives\&.setup (\fBSphinx\fP app)"

.SH "Variable Documentation"
.PP 
.SS "sphinx\&.directives\&.nl_escape_re = re\&.compile(r'\\\\\\n')"

.SS "sphinx\&.directives\&.ObjDescT = TypeVar('ObjDescT')"

.SS "sphinx\&.directives\&.strip_backslash_re = re\&.compile(r'\\\\(\&.)')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
