.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/writers/texinfo.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/writers/texinfo.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.writers\&.texinfo\&.TexinfoWriter\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.writers\&.texinfo\&.TexinfoTranslator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.writers\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.writers\&.texinfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "list[nodes\&.section] \fBsphinx\&.writers\&.texinfo\&.find_subsections\fP (\fBElement\fP section)"
.br
.ti -1c
.RI "str \fBsphinx\&.writers\&.texinfo\&.smart_capwords\fP (str s, str|None sep=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsphinx\&.writers\&.texinfo\&.logger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "str \fBsphinx\&.writers\&.texinfo\&.COPYING\fP"
.br
.ti -1c
.RI "str \fBsphinx\&.writers\&.texinfo\&.TEMPLATE\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
