.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/writers/text.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/writers/text.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.writers\&.text\&.Cell\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.writers\&.text\&.Table\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.writers\&.text\&.TextWrapper\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.writers\&.text\&.TextWriter\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.writers\&.text\&.TextTranslator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.writers\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.writers\&.text\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "list[str] \fBsphinx\&.writers\&.text\&.my_wrap\fP (str text, int width=\fBMAXWIDTH\fP, **Any kwargs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBsphinx\&.writers\&.text\&.MAXWIDTH\fP = 70"
.br
.ti -1c
.RI "int \fBsphinx\&.writers\&.text\&.STDINDENT\fP = 3"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
