.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/builders/latex/transforms.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/sphinx/builders/latex/transforms.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.FootnoteDocnameUpdater\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.SubstitutionDefinitionsRemover\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.ShowUrlsTransform\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.FootnoteCollector\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.LaTeXFootnoteTransform\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.LaTeXFootnoteVisitor\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.BibliographyTransform\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.CitationReferenceTransform\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.MathReferenceTransform\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.LiteralBlockTransform\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.DocumentTargetTransform\fP"
.br
.ti -1c
.RI "class \fBsphinx\&.builders\&.latex\&.transforms\&.IndexInSectionTitleTransform\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsphinx\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.builders\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.builders\&.latex\fP"
.br
.ti -1c
.RI "namespace \fBsphinx\&.builders\&.latex\&.transforms\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBExtensionMetadata\fP \fBsphinx\&.builders\&.latex\&.transforms\&.setup\fP (\fBSphinx\fP app)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBsphinx\&.builders\&.latex\&.transforms\&.URI_SCHEMES\fP = ('mailto:', 'http:', 'https:', 'ftp:')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
