.TH "typing_extensions._SpecialForm" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typing_extensions._SpecialForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits typing\&._Final, _root, and True\&.
.PP
Inherited by \fBtyping_extensions\&._TypedDictSpecialForm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, getitem)"
.br
.ti -1c
.RI "\fB__getattr__\fP (self, item)"
.br
.ti -1c
.RI "\fB__mro_entries__\fP (self, bases)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__reduce__\fP (self)"
.br
.ti -1c
.RI "\fB__call__\fP (self, *args, **kwds)"
.br
.ti -1c
.RI "\fB__or__\fP (self, other)"
.br
.ti -1c
.RI "\fB__ror__\fP (self, other)"
.br
.ti -1c
.RI "\fB__instancecheck__\fP (self, obj)"
.br
.ti -1c
.RI "\fB__subclasscheck__\fP (self, cls)"
.br
.ti -1c
.RI "\fB__getitem__\fP (self, parameters)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_getitem\fP"
.br
.ti -1c
.RI "\fB_name\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "typing_extensions\&._SpecialForm\&.__init__ ( self,  getitem)"

.SH "Member Function Documentation"
.PP 
.SS "typing_extensions\&._SpecialForm\&.__call__ ( self, * args, ** kwds)"

.PP
Reimplemented in \fBtyping_extensions\&._TypedDictSpecialForm\fP\&.
.SS "typing_extensions\&._SpecialForm\&.__getattr__ ( self,  item)"

.SS "typing_extensions\&._SpecialForm\&.__getitem__ ( self,  parameters)"

.SS "typing_extensions\&._SpecialForm\&.__instancecheck__ ( self,  obj)"

.SS "typing_extensions\&._SpecialForm\&.__mro_entries__ ( self,  bases)"

.PP
Reimplemented in \fBtyping_extensions\&._TypedDictSpecialForm\fP\&.
.SS "typing_extensions\&._SpecialForm\&.__or__ ( self,  other)"

.SS "typing_extensions\&._SpecialForm\&.__reduce__ ( self)"

.SS "typing_extensions\&._SpecialForm\&.__repr__ ( self)"

.SS "typing_extensions\&._SpecialForm\&.__ror__ ( self,  other)"

.SS "typing_extensions\&._SpecialForm\&.__subclasscheck__ ( self,  cls)"

.SH "Member Data Documentation"
.PP 
.SS "typing_extensions\&._SpecialForm\&._getitem\fC [protected]\fP"

.SS "typing_extensions\&._SpecialForm\&._name\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
