.TH "typing_extensions._LiteralForm" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typing_extensions._LiteralForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtyping_extensions\&._ExtensionsSpecialForm\fP, _root, and True\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, str \fBdoc\fP)"
.br
.ti -1c
.RI "\fB__getitem__\fP (self, parameters)"
.br
.in -1c

Public Member Functions inherited from \fBtyping_extensions\&._ExtensionsSpecialForm\fP
.in +1c
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_name\fP"
.br
.ti -1c
.RI "\fB_doc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "typing_extensions\&._LiteralForm\&.__init__ ( self, str doc)"

.SH "Member Function Documentation"
.PP 
.SS "typing_extensions\&._LiteralForm\&.__getitem__ ( self,  parameters)"

.SH "Member Data Documentation"
.PP 
.SS "typing_extensions\&._LiteralForm\&._doc\fC [protected]\fP"

.SS "typing_extensions\&._LiteralForm\&._name\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
