.TH "typing_extensions._TypedDictSpecialForm" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typing_extensions._TypedDictSpecialForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtyping_extensions\&._SpecialForm\fP, _root, and True\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__call__\fP (self, typename, fields=\fB_marker\fP, *total=True, closed=None, extra_items=\fBNoExtraItems\fP, **kwargs)"
.br
.ti -1c
.RI "\fB__mro_entries__\fP (self, bases)"
.br
.in -1c

Public Member Functions inherited from \fBtyping_extensions\&._SpecialForm\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, getitem)"
.br
.ti -1c
.RI "\fB__getattr__\fP (self, item)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__reduce__\fP (self)"
.br
.ti -1c
.RI "\fB__or__\fP (self, other)"
.br
.ti -1c
.RI "\fB__ror__\fP (self, other)"
.br
.ti -1c
.RI "\fB__instancecheck__\fP (self, obj)"
.br
.ti -1c
.RI "\fB__subclasscheck__\fP (self, cls)"
.br
.ti -1c
.RI "\fB__getitem__\fP (self, parameters)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBtyping_extensions\&._SpecialForm\fP
.in +1c
.ti -1c
.RI "\fB_getitem\fP"
.br
.ti -1c
.RI "\fB_name\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "typing_extensions\&._TypedDictSpecialForm\&.__call__ ( self,  typename,  fields = \fC\fB_marker\fP\fP, * total = \fCTrue\fP,  closed = \fCNone\fP,  extra_items = \fC\fBNoExtraItems\fP\fP, ** kwargs)"

.PP
Reimplemented from \fBtyping_extensions\&._SpecialForm\fP\&.
.SS "typing_extensions\&._TypedDictSpecialForm\&.__mro_entries__ ( self,  bases)"

.PP
Reimplemented from \fBtyping_extensions\&._SpecialForm\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
