.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/platformdirs/unix.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/platformdirs/unix.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._vendor\&.platformdirs\&.unix\&.Unix\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.platformdirs\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.platformdirs\&.unix\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "NoReturn \fBpip\&._vendor\&.platformdirs\&.unix\&.getuid\fP ()"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.platformdirs\&.unix\&._get_user_media_dir\fP (str env_var, str fallback_tilde_path)"
.br
.ti -1c
.RI "str|None \fBpip\&._vendor\&.platformdirs\&.unix\&._get_user_dirs_folder\fP (str key)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
