.TH "urllib3.contrib.pyopenssl.WrappedSocket" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.contrib.pyopenssl.WrappedSocket
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, OpenSSL\&.SSL\&.Connection \fBconnection\fP, socket_cls \fBsocket\fP, bool \fBsuppress_ragged_eofs\fP=True)"
.br
.ti -1c
.RI "int \fBfileno\fP (self)"
.br
.ti -1c
.RI "bytes \fBrecv\fP (self, *typing\&.Any args, **typing\&.Any kwargs)"
.br
.ti -1c
.RI "int \fBrecv_into\fP (self, *typing\&.Any args, **typing\&.Any kwargs)"
.br
.ti -1c
.RI "None \fBsettimeout\fP (self, float timeout)"
.br
.ti -1c
.RI "None \fBsendall\fP (self, bytes data)"
.br
.ti -1c
.RI "None \fBshutdown\fP (self, int how)"
.br
.ti -1c
.RI "None \fBclose\fP (self)"
.br
.ti -1c
.RI "dict[str, list[typing\&.Any]]|None \fBgetpeercert\fP (self, bool binary_form=False)"
.br
.ti -1c
.RI "str \fBversion\fP (self)"
.br
.ti -1c
.RI "str|None \fBselected_alpn_protocol\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconnection\fP"
.br
.ti -1c
.RI "\fBsocket\fP"
.br
.ti -1c
.RI "\fBsuppress_ragged_eofs\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBmakefile\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "None \fB_decref_socketios\fP (self)"
.br
.ti -1c
.RI "int \fB_send_until_done\fP (self, bytes data)"
.br
.ti -1c
.RI "None \fB_real_close\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_io_refs\fP"
.br
.ti -1c
.RI "\fB_closed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
API-compatibility wrapper for Python OpenSSL's Connection-class\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.__init__ ( self, OpenSSL\&.SSL\&.Connection connection, socket_cls socket, bool  suppress_ragged_eofs = \fCTrue\fP)"

.SH "Member Function Documentation"
.PP 
.SS " None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&._decref_socketios ( self)\fC [protected]\fP"

.SS " None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&._real_close ( self)\fC [protected]\fP"

.SS " int urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&._send_until_done ( self, bytes data)\fC [protected]\fP"

.SS " None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.close ( self)"

.SS " int urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.fileno ( self)"

.SS " dict[str, list[typing\&.Any]] | None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.getpeercert ( self, bool  binary_form = \fCFalse\fP)"

.SS " bytes urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.recv ( self, *typing\&.Any args, **typing\&.Any kwargs)"

.SS " int urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.recv_into ( self, *typing\&.Any args, **typing\&.Any kwargs)"

.SS " str | None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.selected_alpn_protocol ( self)"

.SS " None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.sendall ( self, bytes data)"

.SS " None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.settimeout ( self, float timeout)"

.SS " None urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.shutdown ( self, int how)"

.SS " str urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.version ( self)"

.SH "Member Data Documentation"
.PP 
.SS "urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&._closed\fC [protected]\fP"

.SS "urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&._io_refs\fC [protected]\fP"

.SS "urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.connection"

.SS "urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.makefile\fC [static]\fP"

.SS "urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.socket"

.SS "urllib3\&.contrib\&.pyopenssl\&.WrappedSocket\&.suppress_ragged_eofs"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
