.TH "urllib3.exceptions.NameResolutionError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.exceptions.NameResolutionError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBurllib3\&.exceptions\&.NewConnectionError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, str host, \fBHTTPConnection\fP \fBconn\fP, socket\&.gaierror reason)"
.br
.ti -1c
.RI "\fB_TYPE_REDUCE_RESULT\fP \fB__reduce__\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBurllib3\&.exceptions\&.NewConnectionError\fP
.in +1c
.ti -1c
.RI "\fBHTTPConnection\fP \fBpool\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_host\fP"
.br
.ti -1c
.RI "\fB_reason\fP"
.br
.in -1c

Protected Attributes inherited from \fBurllib3\&.exceptions\&.NewConnectionError\fP
.in +1c
.ti -1c
.RI "\fB_message\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBurllib3\&.exceptions\&.NewConnectionError\fP
.in +1c
.ti -1c
.RI "\fBconn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raised when host name resolution fails\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "urllib3\&.exceptions\&.NameResolutionError\&.__init__ ( self, str host, \fBHTTPConnection\fP conn, socket\&.gaierror reason)"

.PP
Reimplemented from \fBurllib3\&.exceptions\&.NewConnectionError\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " \fB_TYPE_REDUCE_RESULT\fP urllib3\&.exceptions\&.NameResolutionError\&.__reduce__ ( self)"

.PP
Reimplemented from \fBurllib3\&.exceptions\&.NewConnectionError\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "urllib3\&.exceptions\&.NameResolutionError\&._host\fC [protected]\fP"

.SS "urllib3\&.exceptions\&.NameResolutionError\&._reason\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
