.TH "urllib3.contrib.socks._TYPE_SOCKS_OPTIONS" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.contrib.socks._TYPE_SOCKS_OPTIONS
.SH SYNOPSIS
.br
.PP
.PP
Inherits typing\&.TypedDict\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsocks_version\fP"
.br
.ti -1c
.RI "str \fBproxy_host\fP | None"
.br
.ti -1c
.RI "str \fBproxy_port\fP | None"
.br
.ti -1c
.RI "str \fBusername\fP | None"
.br
.ti -1c
.RI "str \fBpassword\fP | None"
.br
.ti -1c
.RI "bool \fBrdns\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "str urllib3\&.contrib\&.socks\&._TYPE_SOCKS_OPTIONS\&.password | None\fC [static]\fP"

.SS "str urllib3\&.contrib\&.socks\&._TYPE_SOCKS_OPTIONS\&.proxy_host | None\fC [static]\fP"

.SS "str urllib3\&.contrib\&.socks\&._TYPE_SOCKS_OPTIONS\&.proxy_port | None\fC [static]\fP"

.SS "bool urllib3\&.contrib\&.socks\&._TYPE_SOCKS_OPTIONS\&.rdns\fC [static]\fP"

.SS "int urllib3\&.contrib\&.socks\&._TYPE_SOCKS_OPTIONS\&.socks_version\fC [static]\fP"

.SS "str urllib3\&.contrib\&.socks\&._TYPE_SOCKS_OPTIONS\&.username | None\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
