.TH "urllib3.exceptions.TimeoutStateError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.exceptions.TimeoutStateError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBurllib3\&.exceptions\&.HTTPError\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Raised when passing an invalid state to a timeout
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
