.TH "urllib3.util.connection" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.util.connection
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBis_connection_dropped\fP (\fBBaseHTTPConnection\fP conn)"
.br
.ti -1c
.RI "socket\&.socket \fBcreate_connection\fP (tuple[str, int] address, _TYPE_TIMEOUT timeout=_DEFAULT_TIMEOUT, tuple[str, int]|None source_address=None, \fB_TYPE_SOCKET_OPTIONS\fP|None socket_options=None)"
.br
.ti -1c
.RI "None \fB_set_socket_options\fP (socket\&.socket sock, \fB_TYPE_SOCKET_OPTIONS\fP|None options)"
.br
.ti -1c
.RI "socket\&.AddressFamily \fBallowed_gai_family\fP ()"
.br
.ti -1c
.RI "bool \fB_has_ipv6\fP (str host)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_TYPE_SOCKET_OPTIONS\fP = list[tuple[int, int, typing\&.Union[int, bytes]]]"
.br
.ti -1c
.RI "bool \fBHAS_IPV6\fP = \fB_has_ipv6\fP('::1')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " bool urllib3\&.util\&.connection\&._has_ipv6 (str host)\fC [protected]\fP"

.PP
.nf
Returns True if the system can bind an IPv6 address\&.
.fi
.PP
 
.SS " None urllib3\&.util\&.connection\&._set_socket_options (socket\&.socket sock, \fB_TYPE_SOCKET_OPTIONS\fP | None
 options)\fC [protected]\fP"

.SS " socket\&.AddressFamily urllib3\&.util\&.connection\&.allowed_gai_family ()"

.PP
.nf
This function is designed to work in the context of
getaddrinfo, where family=socket\&.AF_UNSPEC is the default and
will perform a DNS search for both IPv6 and IPv4 records\&.
.fi
.PP
 
.SS " socket\&.socket urllib3\&.util\&.connection\&.create_connection (tuple[str, int] address, _TYPE_TIMEOUT  timeout = \fC_DEFAULT_TIMEOUT\fP, tuple[str, int] | None  source_address = \fCNone\fP, \fB_TYPE_SOCKET_OPTIONS\fP | None  socket_options = \fCNone\fP)"

.PP
.nf
Connect to *address* and return the socket object\&.

Convenience function\&.  Connect to *address* (a 2-tuple ``(host,
port)``) and return the socket object\&.  Passing the optional
*timeout* parameter will set the timeout on the socket instance
before attempting to connect\&.  If no *timeout* is supplied, the
global default timeout setting returned by :func:`socket\&.getdefaulttimeout`
is used\&.  If *source_address* is set it must be a tuple of (host, port)
for the socket to bind as a source address before making the connection\&.
An host of '' or port 0 tells the OS to use the default\&.

.fi
.PP
 
.SS " bool urllib3\&.util\&.connection\&.is_connection_dropped (\fBBaseHTTPConnection\fP conn)"

.PP
.nf
Returns True if the connection is dropped and should be closed\&.
:param conn: :class:`urllib3\&.connection\&.HTTPConnection` object\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "urllib3\&.util\&.connection\&._TYPE_SOCKET_OPTIONS = list[tuple[int, int, typing\&.Union[int, bytes]]]\fC [protected]\fP"

.SS "bool urllib3\&.util\&.connection\&.HAS_IPV6 = \fB_has_ipv6\fP('::1')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
