.TH "urllib3.contrib.emscripten.fetch._JSPIReadStream" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.contrib.emscripten.fetch._JSPIReadStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits io\&.RawIOBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, Any \fBjs_read_stream\fP, float \fBtimeout\fP, EmscriptenRequest \fBrequest\fP, \fBEmscriptenResponse\fP \fBresponse\fP, Any \fBjs_abort_controller\fP)"
.br
.ti -1c
.RI "None \fB__del__\fP (self)"
.br
.ti -1c
.RI "bool \fBis_closed\fP (self)"
.br
.ti -1c
.RI "bool \fBclosed\fP (self)"
.br
.ti -1c
.RI "None \fBclose\fP (self)"
.br
.ti -1c
.RI "bool \fBreadable\fP (self)"
.br
.ti -1c
.RI "bool \fBwritable\fP (self)"
.br
.ti -1c
.RI "bool \fBseekable\fP (self)"
.br
.ti -1c
.RI "int \fBreadinto\fP (self, \fBBuffer\fP byte_obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjs_read_stream\fP"
.br
.ti -1c
.RI "\fBtimeout\fP"
.br
.ti -1c
.RI "\fBcurrent_buffer\fP"
.br
.ti -1c
.RI "\fBcurrent_buffer_pos\fP"
.br
.ti -1c
.RI "\fBjs_abort_controller\fP"
.br
.ti -1c
.RI "\fBread_len\fP"
.br
.ti -1c
.RI "\fBread_pos\fP"
.br
.ti -1c
.RI "\fBrequest\fP"
.br
.ti -1c
.RI "\fBresponse\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fB_get_next_buffer\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_is_closed\fP"
.br
.ti -1c
.RI "\fB_is_done\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A read stream that uses pyodide\&.ffi\&.run_sync to read from a JavaScript fetch
response\&. This requires support for WebAssembly JavaScript Promise Integration
in the containing browser, and for pyodide to be launched via runPythonAsync\&.

:param js_read_stream:
    The JavaScript stream reader

:param timeout:
    Timeout in seconds

:param request:
    The request we're handling

:param response:
    The response this stream relates to

:param js_abort_controller:
    A JavaScript AbortController object, used for timeouts

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.__init__ ( self, Any js_read_stream, float timeout, EmscriptenRequest request, \fBEmscriptenResponse\fP response, Any js_abort_controller)"

.SS " None urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.__del__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&._get_next_buffer ( self)\fC [protected]\fP"

.SS " None urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.close ( self)"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.closed ( self)"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.is_closed ( self)"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.readable ( self)"

.SS " int urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.readinto ( self, \fBBuffer\fP byte_obj)"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.seekable ( self)"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.writable ( self)"

.SH "Member Data Documentation"
.PP 
.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&._is_closed\fC [protected]\fP"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&._is_done\fC [protected]\fP"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.current_buffer"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.current_buffer_pos"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.js_abort_controller"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.js_read_stream"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.read_len"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.read_pos"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.request"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.response"

.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._JSPIReadStream\&.timeout"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
