.TH "urllib3.connection" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.connection
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_WrappedAndVerifiedSocket\fP"
.br
.ti -1c
.RI "class \fBBaseSSLError\fP"
.br
.ti -1c
.RI "class \fBDummyConnection\fP"
.br
.ti -1c
.RI "class \fBHTTPConnection\fP"
.br
.ti -1c
.RI "class \fBHTTPSConnection\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_WrappedAndVerifiedSocket\fP \fB_ssl_wrap_socket_and_match_hostname\fP (socket\&.socket sock, *None|str|int cert_reqs, None|str|int ssl_version, int|None ssl_minimum_version, int|None ssl_maximum_version, str|None cert_file, str|None key_file, str|None key_password, str|None ca_certs, str|None ca_cert_dir, None|str|bytes ca_cert_data, None|str|typing\&.Literal[False] assert_hostname, str|None assert_fingerprint, str|None server_hostname, ssl\&.SSLContext|None ssl_context, bool tls_in_tls=False)"
.br
.ti -1c
.RI "None \fB_match_hostname\fP (\fB_TYPE_PEER_CERT_RET_DICT\fP|None cert, str asserted_hostname, bool hostname_checks_common_name=False)"
.br
.ti -1c
.RI "\fBProxyError\fP \fB_wrap_proxy_error\fP (Exception err, str|None proxy_scheme)"
.br
.ti -1c
.RI "str \fB_get_default_user_agent\fP ()"
.br
.ti -1c
.RI "str \fB_url_from_connection\fP (\fBHTTPConnection\fP|\fBHTTPSConnection\fP conn, str|None path=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBaseSSLError\fP = ssl\&.SSLError"
.br
.ti -1c
.RI "\fBssl\fP = None"
.br
.ti -1c
.RI "\fBConnectionError\fP = ConnectionError"
.br
.ti -1c
.RI "\fBBrokenPipeError\fP = BrokenPipeError"
.br
.ti -1c
.RI "\fBlog\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "dict \fBport_by_scheme\fP = {'http': 80, 'https': 443}"
.br
.ti -1c
.RI "\fBRECENT_DATE\fP = datetime\&.date(2025, 1, 1)"
.br
.ti -1c
.RI "\fB_CONTAINS_CONTROL_CHAR_RE\fP = re\&.compile(r'[^\-!#$%&'*+\&.^_`|~0\-9a\-zA\-Z]')"
.br
.ti -1c
.RI "\fBHTTPSConnection\fP = \fBDummyConnection\fP"
.br
.ti -1c
.RI "\fBVerifiedHTTPSConnection\fP = \fBHTTPSConnection\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " str urllib3\&.connection\&._get_default_user_agent ()\fC [protected]\fP"

.SS " None urllib3\&.connection\&._match_hostname (\fB_TYPE_PEER_CERT_RET_DICT\fP | None cert, str asserted_hostname, bool  hostname_checks_common_name = \fCFalse\fP)\fC [protected]\fP"

.SS " \fB_WrappedAndVerifiedSocket\fP urllib3\&.connection\&._ssl_wrap_socket_and_match_hostname (socket\&.socket sock, *None | str | int cert_reqs, None | str | int ssl_version, int | None ssl_minimum_version, int | None ssl_maximum_version, str | None cert_file, str | None key_file, str | None key_password, str | None ca_certs, str | None ca_cert_dir, None | str | bytes ca_cert_data, None | str | typing\&.Literal[False] assert_hostname, str | None assert_fingerprint, str | None server_hostname, ssl\&.SSLContext | None ssl_context, bool  tls_in_tls = \fCFalse\fP)\fC [protected]\fP"

.PP
.nf
Logic for constructing an SSLContext from all TLS parameters, passing
that down into ssl_wrap_socket, and then doing certificate verification
either via hostname or fingerprint\&. This function exists to guarantee
that both proxies and targets have the same behavior when connecting via TLS\&.

.fi
.PP
 
.SS " str urllib3\&.connection\&._url_from_connection (\fBHTTPConnection\fP | \fBHTTPSConnection\fP conn, str | None  path = \fCNone\fP)\fC [protected]\fP"

.PP
.nf
Returns the URL from a given connection\&. This is mainly used for testing and logging\&.
.fi
.PP
 
.SS " \fBProxyError\fP urllib3\&.connection\&._wrap_proxy_error (Exception err, str | None proxy_scheme)\fC [protected]\fP"

.SH "Variable Documentation"
.PP 
.SS "urllib3\&.connection\&._CONTAINS_CONTROL_CHAR_RE = re\&.compile(r'[^\-!#$%&'*+\&.^_`|~0\-9a\-zA\-Z]')\fC [protected]\fP"

.SS "\fBurllib3\&.connection\&.BaseSSLError\fP = ssl\&.SSLError"

.SS "urllib3\&.connection\&.BrokenPipeError = BrokenPipeError"

.SS "urllib3\&.connection\&.ConnectionError = ConnectionError"

.SS "\fBurllib3\&.connection\&.HTTPSConnection\fP = \fBDummyConnection\fP"

.SS "urllib3\&.connection\&.log = logging\&.getLogger(__name__)"

.SS "dict urllib3\&.connection\&.port_by_scheme = {'http': 80, 'https': 443}"

.SS "urllib3\&.connection\&.RECENT_DATE = datetime\&.date(2025, 1, 1)"

.SS "urllib3\&.connection\&.ssl = None"

.SS "urllib3\&.connection\&.VerifiedHTTPSConnection = \fBHTTPSConnection\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
