.TH "urllib3.exceptions.NewConnectionError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.exceptions.NewConnectionError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBurllib3\&.exceptions\&.ConnectTimeoutError\fP, and \fBurllib3\&.exceptions\&.HTTPError\fP\&.
.PP
Inherited by \fBurllib3\&.exceptions\&.NameResolutionError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBHTTPConnection\fP \fBconn\fP, str message)"
.br
.ti -1c
.RI "\fB_TYPE_REDUCE_RESULT\fP \fB__reduce__\fP (self)"
.br
.ti -1c
.RI "\fBHTTPConnection\fP \fBpool\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconn\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_message\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Raised when we fail to establish a new connection\&. Usually ECONNREFUSED\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None urllib3\&.exceptions\&.NewConnectionError\&.__init__ ( self, \fBHTTPConnection\fP conn, str message)"

.PP
Reimplemented in \fBurllib3\&.exceptions\&.NameResolutionError\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " \fB_TYPE_REDUCE_RESULT\fP urllib3\&.exceptions\&.NewConnectionError\&.__reduce__ ( self)"

.PP
Reimplemented in \fBurllib3\&.exceptions\&.NameResolutionError\fP\&.
.SS " \fBHTTPConnection\fP urllib3\&.exceptions\&.NewConnectionError\&.pool ( self)"

.SH "Member Data Documentation"
.PP 
.SS "urllib3\&.exceptions\&.NewConnectionError\&._message\fC [protected]\fP"

.SS "urllib3\&.exceptions\&.NewConnectionError\&.conn"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
