.TH "urllib3.poolmanager" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.poolmanager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoolKey\fP"
.br
.ti -1c
.RI "class \fBPoolManager\fP"
.br
.ti -1c
.RI "class \fBProxyManager\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPoolKey\fP \fB_default_key_normalizer\fP (type[\fBPoolKey\fP] key_class, dict[str, typing\&.Any] request_context)"
.br
.ti -1c
.RI "\fBProxyManager\fP \fBproxy_from_url\fP (str url, **typing\&.Any kw)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlog\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "tuple \fBSSL_KEYWORDS\fP"
.br
.ti -1c
.RI "int \fB_DEFAULT_BLOCKSIZE\fP = 16384"
.br
.ti -1c
.RI "dict \fBkey_fn_by_scheme\fP"
.br
.ti -1c
.RI "dict \fBpool_classes_by_scheme\fP = {'http': \fBHTTPConnectionPool\fP, 'https': \fBHTTPSConnectionPool\fP}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " \fBPoolKey\fP urllib3\&.poolmanager\&._default_key_normalizer (type[\fBPoolKey\fP] key_class, dict[str, typing\&.Any]
 request_context)\fC [protected]\fP"

.PP
.nf
Create a pool key out of a request context dictionary\&.

According to RFC 3986, both the scheme and host are case-insensitive\&.
Therefore, this function normalizes both before constructing the pool
key for an HTTPS request\&. If you wish to change this behaviour, provide
alternate callables to ``key_fn_by_scheme``\&.

:param key_class:
    The class to use when constructing the key\&. This should be a namedtuple
    with the ``scheme`` and ``host`` keys at a minimum\&.
:type  key_class: namedtuple
:param request_context:
    A dictionary-like object that contain the context for a request\&.
:type  request_context: dict

:return: A namedtuple that can be used as a connection pool key\&.
:rtype:  PoolKey

.fi
.PP
 
.SS " \fBProxyManager\fP urllib3\&.poolmanager\&.proxy_from_url (str url, **typing\&.Any kw)"

.SH "Variable Documentation"
.PP 
.SS "int urllib3\&.poolmanager\&._DEFAULT_BLOCKSIZE = 16384\fC [protected]\fP"

.SS "dict urllib3\&.poolmanager\&.key_fn_by_scheme"
\fBInitial value:\fP.PP
.nf
1 =  {
2     "http": functools\&.partial(_default_key_normalizer, PoolKey),
3     "https": functools\&.partial(_default_key_normalizer, PoolKey),
4 }
.fi

.SS "urllib3\&.poolmanager\&.log = logging\&.getLogger(__name__)"

.SS "dict urllib3\&.poolmanager\&.pool_classes_by_scheme = {'http': \fBHTTPConnectionPool\fP, 'https': \fBHTTPSConnectionPool\fP}"

.SS "tuple urllib3\&.poolmanager\&.SSL_KEYWORDS"
\fBInitial value:\fP.PP
.nf
1 =  (
2     "key_file",
3     "cert_file",
4     "cert_reqs",
5     "ca_certs",
6     "ca_cert_data",
7     "ssl_version",
8     "ssl_minimum_version",
9     "ssl_maximum_version",
10     "ca_cert_dir",
11     "ssl_context",
12     "key_password",
13     "server_hostname",
14 )
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
