.TH "urllib3.contrib.emscripten.fetch" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.contrib.emscripten.fetch
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_JSPIReadStream\fP"
.br
.ti -1c
.RI "class \fB_ReadStream\fP"
.br
.ti -1c
.RI "class \fB_RequestError\fP"
.br
.ti -1c
.RI "class \fB_StreamingError\fP"
.br
.ti -1c
.RI "class \fB_StreamingFetcher\fP"
.br
.ti -1c
.RI "class \fB_TimeoutError\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "JsProxy \fB_obj_from_dict\fP (dict[str, Any] dict_val)"
.br
.ti -1c
.RI "bool \fBis_in_browser_main_thread\fP ()"
.br
.ti -1c
.RI "bool \fBis_cross_origin_isolated\fP ()"
.br
.ti -1c
.RI "bool \fBis_in_node\fP ()"
.br
.ti -1c
.RI "bool \fBis_worker_available\fP ()"
.br
.ti -1c
.RI "\fBEmscriptenResponse\fP|None \fBsend_streaming_request\fP (EmscriptenRequest request)"
.br
.ti -1c
.RI "None \fB_show_timeout_warning\fP ()"
.br
.ti -1c
.RI "None \fB_show_streaming_warning\fP ()"
.br
.ti -1c
.RI "\fBEmscriptenResponse\fP \fBsend_request\fP (EmscriptenRequest request)"
.br
.ti -1c
.RI "\fBEmscriptenResponse\fP \fBsend_jspi_request\fP (EmscriptenRequest request, bool streaming)"
.br
.ti -1c
.RI "Any \fB_run_sync_with_timeout\fP (Any promise, float timeout, Any js_abort_controller, EmscriptenRequest|None request, \fBEmscriptenResponse\fP|None response)"
.br
.ti -1c
.RI "bool \fBhas_jspi\fP ()"
.br
.ti -1c
.RI "bool \fB_is_node_js\fP ()"
.br
.ti -1c
.RI "bool|None \fBstreaming_ready\fP ()"
.br
.ti -1c
.RI "bool \fBwait_for_streaming_ready\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBHEADERS_TO_IGNORE\fP = ('user\-agent',)"
.br
.ti -1c
.RI "int \fBSUCCESS_HEADER\fP = \-1"
.br
.ti -1c
.RI "int \fBSUCCESS_EOF\fP = \-2"
.br
.ti -1c
.RI "int \fBERROR_TIMEOUT\fP = \-3"
.br
.ti -1c
.RI "int \fBERROR_EXCEPTION\fP = \-4"
.br
.ti -1c
.RI "tuple \fB_STREAMING_WORKER_CODE\fP"
.br
.ti -1c
.RI "\fB_StreamingFetcher\fP \fB_fetcher\fP = None"
.br
.ti -1c
.RI "tuple \fBNODE_JSPI_ERROR\fP"
.br
.ti -1c
.RI "bool \fB_SHOWN_TIMEOUT_WARNING\fP = False"
.br
.ti -1c
.RI "bool \fB_SHOWN_STREAMING_WARNING\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Support for streaming http requests in emscripten\&.

A few caveats -

If your browser (or Node\&.js) has WebAssembly JavaScript Promise Integration enabled
https://github\&.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview\&.md
*and* you launch pyodide using `pyodide\&.runPythonAsync`, this will fetch data using the
JavaScript asynchronous fetch api (wrapped via `pyodide\&.ffi\&.call_sync`)\&. In this case
timeouts and streaming should just work\&.

Otherwise, it uses a combination of XMLHttpRequest and a web-worker for streaming\&.

This approach has several caveats:

Firstly, you can't do streaming http in the main UI thread, because atomics\&.wait isn't allowed\&.
Streaming only works if you're running pyodide in a web worker\&.

Secondly, this uses an extra web worker and SharedArrayBuffer to do the asynchronous fetch
operation, so it requires that you have crossOriginIsolation enabled, by serving over https
(or from localhost) with the two headers below set:

    Cross-Origin-Opener-Policy: same-origin
    Cross-Origin-Embedder-Policy: require-corp

You can tell if cross origin isolation is successfully enabled by looking at the global crossOriginIsolated variable in
JavaScript console\&. If it isn't, streaming requests will fallback to XMLHttpRequest, i\&.e\&. getting the whole
request into a buffer and then returning it\&. it shows a warning in the JavaScript console in this case\&.

Finally, the webworker which does the streaming fetch is created on initial import, but will only be started once
control is returned to javascript\&. Call `await wait_for_streaming_ready()` to wait for streaming fetch\&.

NB: in this code, there are a lot of JavaScript objects\&. They are named js_*
to make it clear what type of object they are\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&._is_node_js ()\fC [protected]\fP"

.PP
.nf
Check if we are in Node\&.js\&.

:return: True if we are in Node\&.js\&.
:rtype: bool

.fi
.PP
 
.SS " JsProxy urllib3\&.contrib\&.emscripten\&.fetch\&._obj_from_dict (dict[str, Any] dict_val)\fC [protected]\fP"

.SS " Any urllib3\&.contrib\&.emscripten\&.fetch\&._run_sync_with_timeout (Any promise, float timeout, Any js_abort_controller, EmscriptenRequest | None request, \fBEmscriptenResponse\fP | None response)\fC [protected]\fP"

.PP
.nf
Await a JavaScript promise synchronously with a timeout which is implemented
via the AbortController

:param promise:
    Javascript promise to await

:param timeout:
    Timeout in seconds

:param js_abort_controller:
    A JavaScript AbortController object, used on timeout

:param request:
    The request being handled

:param response:
    The response being handled (if it exists yet)

:raises _TimeoutError: If the request times out
:raises _RequestError: If the request raises a JavaScript exception

:return: The result of awaiting the promise\&.

.fi
.PP
 
.SS " None urllib3\&.contrib\&.emscripten\&.fetch\&._show_streaming_warning ()\fC [protected]\fP"

.SS " None urllib3\&.contrib\&.emscripten\&.fetch\&._show_timeout_warning ()\fC [protected]\fP"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&.has_jspi ()"

.PP
.nf
Return true if jspi can be used\&.

This requires both browser support and also WebAssembly
to be in the correct state - i\&.e\&. that the javascript
call into python was async not sync\&.

:return: True if jspi can be used\&.
:rtype: bool

.fi
.PP
 
.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&.is_cross_origin_isolated ()"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&.is_in_browser_main_thread ()"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&.is_in_node ()"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&.is_worker_available ()"

.SS " \fBEmscriptenResponse\fP urllib3\&.contrib\&.emscripten\&.fetch\&.send_jspi_request (EmscriptenRequest request, bool
 streaming)"

.PP
.nf
Send a request using WebAssembly JavaScript Promise Integration
to wrap the asynchronous JavaScript fetch api (experimental)\&.

:param request:
    Request to send

:param streaming:
    Whether to stream the response

:return: The response object
:rtype: EmscriptenResponse

.fi
.PP
 
.SS " \fBEmscriptenResponse\fP urllib3\&.contrib\&.emscripten\&.fetch\&.send_request (EmscriptenRequest request)"

.SS " \fBEmscriptenResponse\fP | None urllib3\&.contrib\&.emscripten\&.fetch\&.send_streaming_request (EmscriptenRequest request)"

.SS " bool | None urllib3\&.contrib\&.emscripten\&.fetch\&.streaming_ready ()"

.SS " bool urllib3\&.contrib\&.emscripten\&.fetch\&.wait_for_streaming_ready ()"

.SH "Variable Documentation"
.PP 
.SS "urllib3\&.contrib\&.emscripten\&.fetch\&._fetcher = None\fC [protected]\fP"

.SS "bool urllib3\&.contrib\&.emscripten\&.fetch\&._SHOWN_STREAMING_WARNING = False\fC [protected]\fP"

.SS "bool urllib3\&.contrib\&.emscripten\&.fetch\&._SHOWN_TIMEOUT_WARNING = False\fC [protected]\fP"

.SS "tuple urllib3\&.contrib\&.emscripten\&.fetch\&._STREAMING_WORKER_CODE\fC [protected]\fP"
\fBInitial value:\fP.PP
.nf
1 =  (
2     files(__package__)
3     \&.joinpath("emscripten_fetch_worker\&.js")
4     \&.read_text(encoding="utf\-8")
5 )
.fi

.SS "int urllib3\&.contrib\&.emscripten\&.fetch\&.ERROR_EXCEPTION = \-4"

.SS "int urllib3\&.contrib\&.emscripten\&.fetch\&.ERROR_TIMEOUT = \-3"

.SS "tuple urllib3\&.contrib\&.emscripten\&.fetch\&.HEADERS_TO_IGNORE = ('user\-agent',)"

.SS "tuple urllib3\&.contrib\&.emscripten\&.fetch\&.NODE_JSPI_ERROR"
\fBInitial value:\fP.PP
.nf
1 =  (
2     "urllib3 only works in Node\&.js with pyodide\&.runPythonAsync"
3     " and requires the flag \-\-experimental\-wasm\-stack\-switching in "
4     " versions of node <24\&."
5 )
.fi

.SS "int urllib3\&.contrib\&.emscripten\&.fetch\&.SUCCESS_EOF = \-2"

.SS "int urllib3\&.contrib\&.emscripten\&.fetch\&.SUCCESS_HEADER = \-1"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
