.TH "urllib3.exceptions.PoolError" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.exceptions.PoolError
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBurllib3\&.exceptions\&.HTTPError\fP\&.
.PP
Inherited by \fBurllib3\&.exceptions\&.ClosedPoolError\fP, \fBurllib3\&.exceptions\&.EmptyPoolError\fP, \fBurllib3\&.exceptions\&.FullPoolError\fP, and \fBurllib3\&.exceptions\&.RequestError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, \fBConnectionPool\fP \fBpool\fP, str message)"
.br
.ti -1c
.RI "\fB_TYPE_REDUCE_RESULT\fP \fB__reduce__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpool\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_message\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base exception for errors caused within a pool\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None urllib3\&.exceptions\&.PoolError\&.__init__ ( self, \fBConnectionPool\fP pool, str message)"

.PP
Reimplemented in \fBurllib3\&.exceptions\&.MaxRetryError\fP, \fBurllib3\&.exceptions\&.HostChangedError\fP, and \fBurllib3\&.exceptions\&.RequestError\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " \fB_TYPE_REDUCE_RESULT\fP urllib3\&.exceptions\&.PoolError\&.__reduce__ ( self)"

.PP
Reimplemented in \fBurllib3\&.exceptions\&.RequestError\fP, and \fBurllib3\&.exceptions\&.MaxRetryError\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "urllib3\&.exceptions\&.PoolError\&._message\fC [protected]\fP"

.SS "urllib3\&.exceptions\&.PoolError\&.pool"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
