.TH "urllib3.connectionpool.HTTPConnectionPool" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.connectionpool.HTTPConnectionPool
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBurllib3\&.connectionpool\&.ConnectionPool\fP, and \fBurllib3\&._request_methods\&.RequestMethods\fP\&.
.PP
Inherited by \fBurllib3\&.connectionpool\&.HTTPSConnectionPool\fP, and \fBurllib3\&.contrib\&.socks\&.SOCKSHTTPConnectionPool\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, str \fBhost\fP, int|None \fBport\fP=None, \fB_TYPE_TIMEOUT\fP|None \fBtimeout\fP=_DEFAULT_TIMEOUT, int maxsize=1, bool \fBblock\fP=False, typing\&.Mapping[str, str]|None \fBheaders\fP=None, \fBRetry\fP|bool|int|None \fBretries\fP=None, \fBUrl\fP|None _proxy=None, typing\&.Mapping[str, str]|None _proxy_headers=None, \fBProxyConfig\fP|None _proxy_config=None, **typing\&.Any \fBconn_kw\fP)"
.br
.ti -1c
.RI "None \fBclose\fP (self)"
.br
.ti -1c
.RI "bool \fBis_same_host\fP (self, str url)"
.br
.ti -1c
.RI "\fBBaseHTTPResponse\fP \fBurlopen\fP (self, str method, str url, _TYPE_BODY|None body=None, typing\&.Mapping[str, str]|None \fBheaders\fP=None, \fBRetry\fP|bool|int|None \fBretries\fP=None, bool redirect=True, bool assert_same_host=True, \fB_TYPE_TIMEOUT\fP \fBtimeout\fP=_DEFAULT_TIMEOUT, int|None pool_timeout=None, bool|None release_conn=None, bool chunked=False, _TYPE_BODY_POSITION|None body_pos=None, bool preload_content=True, bool decode_content=True, **typing\&.Any response_kw)"
.br
.in -1c

Public Member Functions inherited from \fBurllib3\&.connectionpool\&.ConnectionPool\fP
.in +1c
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.ti -1c
.RI "Self \fB__enter__\fP (self)"
.br
.ti -1c
.RI "typing\&.Literal[False] \fB__exit__\fP (self, type[BaseException]|None exc_type, BaseException|None exc_val, TracebackType|None exc_tb)"
.br
.in -1c

Public Member Functions inherited from \fBurllib3\&._request_methods\&.RequestMethods\fP
.in +1c
.ti -1c
.RI "\fBBaseHTTPResponse\fP \fBrequest\fP (self, str method, str url, _TYPE_BODY|None body=None, _TYPE_FIELDS|None fields=None, typing\&.Mapping[str, str]|None \fBheaders\fP=None, typing\&.Any|None json=None, **typing\&.Any urlopen_kw)"
.br
.ti -1c
.RI "\fBBaseHTTPResponse\fP \fBrequest_encode_url\fP (self, str method, str url, \fB_TYPE_ENCODE_URL_FIELDS\fP|None fields=None, typing\&.Mapping[str, str]|None \fBheaders\fP=None, **str urlopen_kw)"
.br
.ti -1c
.RI "\fBBaseHTTPResponse\fP \fBrequest_encode_body\fP (self, str method, str url, _TYPE_FIELDS|None fields=None, typing\&.Mapping[str, str]|None \fBheaders\fP=None, bool encode_multipart=True, str|None multipart_boundary=None, **str urlopen_kw)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtimeout\fP"
.br
.ti -1c
.RI "\fBretries\fP"
.br
.ti -1c
.RI "\fBblock\fP"
.br
.ti -1c
.RI "\fBproxy\fP"
.br
.ti -1c
.RI "\fBproxy_headers\fP"
.br
.ti -1c
.RI "\fBproxy_config\fP"
.br
.ti -1c
.RI "\fBnum_connections\fP"
.br
.ti -1c
.RI "\fBnum_requests\fP"
.br
.ti -1c
.RI "\fBconn_kw\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBscheme\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBpool\fP"
.br
.in -1c

Public Attributes inherited from \fBurllib3\&.connectionpool\&.ConnectionPool\fP
.in +1c
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.in -1c

Public Attributes inherited from \fBurllib3\&._request_methods\&.RequestMethods\fP
.in +1c
.ti -1c
.RI "\fBheaders\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBscheme\fP = 'http'"
.br
.ti -1c
.RI "type \fBConnectionCls\fP = \fBHTTPConnection\fP"
.br
.in -1c

Static Public Attributes inherited from \fBurllib3\&.connectionpool\&.ConnectionPool\fP
.in +1c
.ti -1c
.RI "str \fBscheme\fP = None"
.br
.ti -1c
.RI "\fBQueueCls\fP = queue\&.LifoQueue"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseHTTPConnection\fP \fB_new_conn\fP (self)"
.br
.ti -1c
.RI "\fBBaseHTTPConnection\fP \fB_get_conn\fP (self, float|None \fBtimeout\fP=None)"
.br
.ti -1c
.RI "None \fB_put_conn\fP (self, \fBBaseHTTPConnection\fP|None conn)"
.br
.ti -1c
.RI "None \fB_validate_conn\fP (self, \fBBaseHTTPConnection\fP conn)"
.br
.ti -1c
.RI "None \fB_prepare_proxy\fP (self, \fBBaseHTTPConnection\fP conn)"
.br
.ti -1c
.RI "\fBTimeout\fP \fB_get_timeout\fP (self, \fB_TYPE_TIMEOUT\fP \fBtimeout\fP)"
.br
.ti -1c
.RI "None \fB_raise_timeout\fP (self, \fBBaseSSLError\fP|OSError|SocketTimeout err, str url, \fB_TYPE_TIMEOUT\fP|None timeout_value)"
.br
.ti -1c
.RI "\fBBaseHTTPResponse\fP \fB_make_request\fP (self, \fBBaseHTTPConnection\fP conn, str method, str url, _TYPE_BODY|None body=None, typing\&.Mapping[str, str]|None \fBheaders\fP=None, \fBRetry\fP|None \fBretries\fP=None, \fB_TYPE_TIMEOUT\fP \fBtimeout\fP=_DEFAULT_TIMEOUT, bool chunked=False, \fBBaseHTTPConnection\fP|None response_conn=None, bool preload_content=True, bool decode_content=True, bool enforce_content_length=True)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBurllib3\&.connectionpool\&.ConnectionPool\fP
.in +1c
.ti -1c
.RI "\fB_tunnel_host\fP"
.br
.in -1c

Static Protected Attributes inherited from \fBurllib3\&._request_methods\&.RequestMethods\fP
.in +1c
.ti -1c
.RI "dict \fB_encode_url_methods\fP = {'DELETE', 'GET', 'HEAD', 'OPTIONS'}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Thread-safe connection pool for one host\&.

:param host:
    Host used for this HTTP Connection (e\&.g\&. 'localhost'), passed into
    :class:`http\&.client\&.HTTPConnection`\&.

:param port:
    Port used for this HTTP Connection (None is equivalent to 80), passed
    into :class:`http\&.client\&.HTTPConnection`\&.

:param timeout:
    Socket timeout in seconds for each individual connection\&. This can
    be a float or integer, which sets the timeout for the HTTP request,
    or an instance of :class:`urllib3\&.util\&.Timeout` which gives you more
    fine-grained control over request timeouts\&. After the constructor has
    been parsed, this is always a `urllib3\&.util\&.Timeout` object\&.

:param maxsize:
    Number of connections to save that can be reused\&. More than 1 is useful
    in multithreaded situations\&. If ``block`` is set to False, more
    connections will be created but they will not be saved once they've
    been used\&.

:param block:
    If set to True, no more than ``maxsize`` connections will be used at
    a time\&. When no free connections are available, the call will block
    until a connection has been released\&. This is a useful side effect for
    particular multithreaded situations where one does not want to use more
    than maxsize connections per host to prevent flooding\&.

:param headers:
    Headers to include with all requests, unless other headers are given
    explicitly\&.

:param retries:
    Retry configuration to use by default with requests in this pool\&.

:param _proxy:
    Parsed proxy URL, should not be used directly, instead, see
    :class:`urllib3\&.ProxyManager`

:param _proxy_headers:
    A dictionary with proxy headers, should not be used directly,
    instead, see :class:`urllib3\&.ProxyManager`

:param \\\\**conn_kw:
    Additional parameters are used to create fresh :class:`urllib3\&.connection\&.HTTPConnection`,
    :class:`urllib3\&.connection\&.HTTPSConnection` instances\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.__init__ ( self, str host, int | None  port = \fCNone\fP, \fB_TYPE_TIMEOUT\fP | None  timeout = \fC_DEFAULT_TIMEOUT\fP, int  maxsize = \fC1\fP, bool  block = \fCFalse\fP, typing\&.Mapping[str, str] | None  headers = \fCNone\fP, \fBRetry\fP | bool | int | None  retries = \fCNone\fP, \fBUrl\fP | None  _proxy = \fCNone\fP, typing\&.Mapping[str, str] | None  _proxy_headers = \fCNone\fP, \fBProxyConfig\fP | None  _proxy_config = \fCNone\fP, **typing\&.Any conn_kw)"

.PP
Reimplemented from \fBurllib3\&.connectionpool\&.ConnectionPool\fP\&.
.PP
Reimplemented in \fBurllib3\&.connectionpool\&.HTTPSConnectionPool\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " \fBBaseHTTPConnection\fP urllib3\&.connectionpool\&.HTTPConnectionPool\&._get_conn ( self, float | None  timeout = \fCNone\fP)\fC [protected]\fP"

.PP
.nf
Get a connection\&. Will return a pooled connection if one is available\&.

If no connections are available and :prop:`\&.block` is ``False``, then a
fresh connection is returned\&.

:param timeout:
    Seconds to wait before giving up and raising
    :class:`urllib3\&.exceptions\&.EmptyPoolError` if the pool is empty and
    :prop:`\&.block` is ``True``\&.

.fi
.PP
 
.SS " \fBTimeout\fP urllib3\&.connectionpool\&.HTTPConnectionPool\&._get_timeout ( self, \fB_TYPE_TIMEOUT\fP timeout)\fC [protected]\fP"

.PP
.nf
Helper that always returns a :class:`urllib3\&.util\&.Timeout`
.fi
.PP
 
.SS " \fBBaseHTTPResponse\fP urllib3\&.connectionpool\&.HTTPConnectionPool\&._make_request ( self, \fBBaseHTTPConnection\fP conn, str method, str url, _TYPE_BODY | None  body = \fCNone\fP, typing\&.Mapping[str, str] | None  headers = \fCNone\fP, \fBRetry\fP | None  retries = \fCNone\fP, \fB_TYPE_TIMEOUT\fP  timeout = \fC_DEFAULT_TIMEOUT\fP, bool  chunked = \fCFalse\fP, \fBBaseHTTPConnection\fP | None  response_conn = \fCNone\fP, bool  preload_content = \fCTrue\fP, bool  decode_content = \fCTrue\fP, bool  enforce_content_length = \fCTrue\fP)\fC [protected]\fP"

.PP
.nf
Perform a request on a given urllib connection object taken from our
pool\&.

:param conn:
    a connection from one of our connection pools

:param method:
    HTTP request method (such as GET, POST, PUT, etc\&.)

:param url:
    The URL to perform the request on\&.

:param body:
    Data to send in the request body, either :class:`str`, :class:`bytes`,
    an iterable of :class:`str`/:class:`bytes`, or a file-like object\&.

:param headers:
    Dictionary of custom headers to send, such as User-Agent,
    If-None-Match, etc\&. If None, pool headers are used\&. If provided,
    these headers completely replace any pool-specific headers\&.

:param retries:
    Configure the number of retries to allow before raising a
    :class:`~urllib3\&.exceptions\&.MaxRetryError` exception\&.

    Pass ``None`` to retry until you receive a response\&. Pass a
    :class:`~urllib3\&.util\&.retry\&.Retry` object for fine-grained control
    over different types of retries\&.
    Pass an integer number to retry connection errors that many times,
    but no other types of errors\&. Pass zero to never retry\&.

    If ``False``, then retries are disabled and any exception is raised
    immediately\&. Also, instead of raising a MaxRetryError on redirects,
    the redirect response will be returned\&.

:type retries: :class:`~urllib3\&.util\&.retry\&.Retry`, False, or an int\&.

:param timeout:
    If specified, overrides the default timeout for this one
    request\&. It may be a float (in seconds) or an instance of
    :class:`urllib3\&.util\&.Timeout`\&.

:param chunked:
    If True, urllib3 will send the body using chunked transfer
    encoding\&. Otherwise, urllib3 will send the body using the standard
    content-length form\&. Defaults to False\&.

:param response_conn:
    Set this to ``None`` if you will handle releasing the connection or
    set the connection to have the response release it\&.

:param preload_content:
  If True, the response's body will be preloaded during construction\&.

:param decode_content:
    If True, will attempt to decode the body based on the
    'content-encoding' header\&.

:param enforce_content_length:
    Enforce content length checking\&. Body returned by server must match
    value of Content-Length header, if present\&. Otherwise, raise error\&.

.fi
.PP
 
.SS " \fBBaseHTTPConnection\fP urllib3\&.connectionpool\&.HTTPConnectionPool\&._new_conn ( self)\fC [protected]\fP"

.PP
.nf
Return a fresh :class:`HTTPConnection`\&.

.fi
.PP
 
.PP
Reimplemented in \fBurllib3\&.connectionpool\&.HTTPSConnectionPool\fP\&.
.SS " None urllib3\&.connectionpool\&.HTTPConnectionPool\&._prepare_proxy ( self, \fBBaseHTTPConnection\fP conn)\fC [protected]\fP"

.PP
Reimplemented in \fBurllib3\&.connectionpool\&.HTTPSConnectionPool\fP\&.
.SS " None urllib3\&.connectionpool\&.HTTPConnectionPool\&._put_conn ( self, \fBBaseHTTPConnection\fP | None conn)\fC [protected]\fP"

.PP
.nf
Put a connection back into the pool\&.

:param conn:
    Connection object for the current host and port as returned by
    :meth:`\&._new_conn` or :meth:`\&._get_conn`\&.

If the pool is already full, the connection is closed and discarded
because we exceeded maxsize\&. If connections are discarded frequently,
then maxsize should be increased\&.

If the pool is closed, then the connection will be closed and discarded\&.

.fi
.PP
 
.SS " None urllib3\&.connectionpool\&.HTTPConnectionPool\&._raise_timeout ( self, \fBBaseSSLError\fP | OSError | SocketTimeout err, str url, \fB_TYPE_TIMEOUT\fP | None timeout_value)\fC [protected]\fP"

.PP
.nf
Is the error actually a timeout? Will raise a ReadTimeout or pass
.fi
.PP
 
.SS " None urllib3\&.connectionpool\&.HTTPConnectionPool\&._validate_conn ( self, \fBBaseHTTPConnection\fP conn)\fC [protected]\fP"

.PP
.nf
Called right before a request is made, after the socket is created\&.

.fi
.PP
 
.PP
Reimplemented in \fBurllib3\&.connectionpool\&.HTTPSConnectionPool\fP\&.
.SS " None urllib3\&.connectionpool\&.HTTPConnectionPool\&.close ( self)"

.PP
.nf
Close all pooled connections and disable the pool\&.

.fi
.PP
 
.PP
Reimplemented from \fBurllib3\&.connectionpool\&.ConnectionPool\fP\&.
.SS " bool urllib3\&.connectionpool\&.HTTPConnectionPool\&.is_same_host ( self, str url)"

.PP
.nf
Check if the given ``url`` is a member of the same host as this
connection pool\&.

.fi
.PP
 
.SS " \fBBaseHTTPResponse\fP urllib3\&.connectionpool\&.HTTPConnectionPool\&.urlopen ( self, str method, str url, _TYPE_BODY | None  body = \fCNone\fP, typing\&.Mapping[str, str] | None  headers = \fCNone\fP, \fBRetry\fP | bool | int | None  retries = \fCNone\fP, bool  redirect = \fCTrue\fP, bool  assert_same_host = \fCTrue\fP, \fB_TYPE_TIMEOUT\fP  timeout = \fC_DEFAULT_TIMEOUT\fP, int | None  pool_timeout = \fCNone\fP, bool | None  release_conn = \fCNone\fP, bool  chunked = \fCFalse\fP, _TYPE_BODY_POSITION | None  body_pos = \fCNone\fP, bool  preload_content = \fCTrue\fP, bool  decode_content = \fCTrue\fP, **typing\&.Any response_kw)"

.PP
.nf
Get a connection from the pool and perform an HTTP request\&. This is the
lowest level call for making a request, so you'll need to specify all
the raw details\&.

\&.\&. note::

   More commonly, it's appropriate to use a convenience method
   such as :meth:`request`\&.

\&.\&. note::

   `release_conn` will only behave as expected if
   `preload_content=False` because we want to make
   `preload_content=False` the default behaviour someday soon without
   breaking backwards compatibility\&.

:param method:
    HTTP request method (such as GET, POST, PUT, etc\&.)

:param url:
    The URL to perform the request on\&.

:param body:
    Data to send in the request body, either :class:`str`, :class:`bytes`,
    an iterable of :class:`str`/:class:`bytes`, or a file-like object\&.

:param headers:
    Dictionary of custom headers to send, such as User-Agent,
    If-None-Match, etc\&. If None, pool headers are used\&. If provided,
    these headers completely replace any pool-specific headers\&.

:param retries:
    Configure the number of retries to allow before raising a
    :class:`~urllib3\&.exceptions\&.MaxRetryError` exception\&.

    If ``None`` (default) will retry 3 times, see ``Retry\&.DEFAULT``\&. Pass a
    :class:`~urllib3\&.util\&.retry\&.Retry` object for fine-grained control
    over different types of retries\&.
    Pass an integer number to retry connection errors that many times,
    but no other types of errors\&. Pass zero to never retry\&.

    If ``False``, then retries are disabled and any exception is raised
    immediately\&. Also, instead of raising a MaxRetryError on redirects,
    the redirect response will be returned\&.

:type retries: :class:`~urllib3\&.util\&.retry\&.Retry`, False, or an int\&.

:param redirect:
    If True, automatically handle redirects (status codes 301, 302,
    303, 307, 308)\&. Each redirect counts as a retry\&. Disabling retries
    will disable redirect, too\&.

:param assert_same_host:
    If ``True``, will make sure that the host of the pool requests is
    consistent else will raise HostChangedError\&. When ``False``, you can
    use the pool on an HTTP proxy and request foreign hosts\&.

:param timeout:
    If specified, overrides the default timeout for this one
    request\&. It may be a float (in seconds) or an instance of
    :class:`urllib3\&.util\&.Timeout`\&.

:param pool_timeout:
    If set and the pool is set to block=True, then this method will
    block for ``pool_timeout`` seconds and raise EmptyPoolError if no
    connection is available within the time period\&.

:param bool preload_content:
    If True, the response's body will be preloaded into memory\&.

:param bool decode_content:
    If True, will attempt to decode the body based on the
    'content-encoding' header\&.

:param release_conn:
    If False, then the urlopen call will not release the connection
    back into the pool once a response is received (but will release if
    you read the entire contents of the response such as when
    `preload_content=True`)\&. This is useful if you're not preloading
    the response's content immediately\&. You will need to call
    ``r\&.release_conn()`` on the response ``r`` to return the connection
    back into the pool\&. If None, it takes the value of ``preload_content``
    which defaults to ``True``\&.

:param bool chunked:
    If True, urllib3 will send the body using chunked transfer
    encoding\&. Otherwise, urllib3 will send the body using the standard
    content-length form\&. Defaults to False\&.

:param int body_pos:
    Position to seek to in file-like body in the event of a retry or
    redirect\&. Typically this won't need to be set because urllib3 will
    auto-populate the value when needed\&.

.fi
.PP
 
.PP
Reimplemented from \fBurllib3\&._request_methods\&.RequestMethods\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.block"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.conn_kw"

.SS "type urllib3\&.connectionpool\&.HTTPConnectionPool\&.ConnectionCls = \fBHTTPConnection\fP\fC [static]\fP"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.host"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.num_connections"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.num_requests"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.pool"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.port"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.proxy"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.proxy_config"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.proxy_headers"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.retries"

.SS "str urllib3\&.connectionpool\&.HTTPConnectionPool\&.scheme = 'http'\fC [static]\fP"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.scheme"

.SS "urllib3\&.connectionpool\&.HTTPConnectionPool\&.timeout"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
