.TH "urllib3.util.ssl_match_hostname" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urllib3.util.ssl_match_hostname
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCertificateError\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typing\&.Match[str]|None|bool \fB_dnsname_match\fP (typing\&.Any dn, str hostname, int max_wildcards=1)"
.br
.ti -1c
.RI "bool \fB_ipaddress_match\fP (str ipname, IPv4Address|IPv6Address host_ip)"
.br
.ti -1c
.RI "None \fBmatch_hostname\fP (\fB_TYPE_PEER_CERT_RET_DICT\fP|None cert, str hostname, bool hostname_checks_common_name=False)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The match_hostname() function from Python 3\&.5, essential when using SSL\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS " typing\&.Match[str] | None | bool urllib3\&.util\&.ssl_match_hostname\&._dnsname_match (typing\&.Any dn, str hostname, int  max_wildcards = \fC1\fP)\fC [protected]\fP"

.PP
.nf
Matching according to RFC 6125, section 6\&.4\&.3

http://tools\&.ietf\&.org/html/rfc6125#section-6\&.4\&.3

.fi
.PP
 
.SS " bool urllib3\&.util\&.ssl_match_hostname\&._ipaddress_match (str ipname, IPv4Address | IPv6Address host_ip)\fC [protected]\fP"

.PP
.nf
Exact matching of IP addresses\&.

RFC 9110 section 4\&.3\&.5: 'A reference identity of IP-ID contains the decoded
bytes of the IP address\&. An IP version 4 address is 4 octets, and an IP
version 6 address is 16 octets\&. [\&.\&.\&.] A reference identity of type IP-ID
matches if the address is identical to an iPAddress value of the
subjectAltName extension of the certificate\&.'

.fi
.PP
 
.SS " None urllib3\&.util\&.ssl_match_hostname\&.match_hostname (\fB_TYPE_PEER_CERT_RET_DICT\fP | None cert, str hostname, bool  hostname_checks_common_name = \fCFalse\fP)"

.PP
.nf
Verify that *cert* (in decoded format as returned by
SSLSocket\&.getpeercert()) matches the *hostname*\&.  RFC 2818 and RFC 6125
rules are followed, but IP addresses are not accepted for *hostname*\&.

CertificateError is raised on failure\&. On success, the function
returns nothing\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
