.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/waitress/utilities.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/waitress/utilities.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwaitress\&.utilities\&.Error\fP"
.br
.ti -1c
.RI "class \fBwaitress\&.utilities\&.BadRequest\fP"
.br
.ti -1c
.RI "class \fBwaitress\&.utilities\&.RequestHeaderFieldsTooLarge\fP"
.br
.ti -1c
.RI "class \fBwaitress\&.utilities\&.RequestEntityTooLarge\fP"
.br
.ti -1c
.RI "class \fBwaitress\&.utilities\&.InternalServerError\fP"
.br
.ti -1c
.RI "class \fBwaitress\&.utilities\&.ServerNotImplemented\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBwaitress\fP"
.br
.ti -1c
.RI "namespace \fBwaitress\&.utilities\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwaitress\&.utilities\&.find_double_newline\fP (s)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.concat\fP (*args)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.join\fP (seq, field=' ')"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.group\fP (s)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.unpack_rfc822\fP (m)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.unpack_rfc850\fP (m)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.build_http_date\fP (when)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.parse_http_date\fP (d)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.undquote\fP (value)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.cleanup_unix_socket\fP (path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBwaitress\&.utilities\&.logger\fP = logging\&.getLogger('waitress')"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.queue_logger\fP = logging\&.getLogger('waitress\&.queue')"
.br
.ti -1c
.RI "list \fBwaitress\&.utilities\&.short_days\fP = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']"
.br
.ti -1c
.RI "list \fBwaitress\&.utilities\&.long_days\fP"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.short_day_reg\fP = \fBgroup\fP(\fBjoin\fP(\fBshort_days\fP, '|'))"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.long_day_reg\fP = \fBgroup\fP(\fBjoin\fP(\fBlong_days\fP, '|'))"
.br
.ti -1c
.RI "dict \fBwaitress\&.utilities\&.daymap\fP = {}"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.hms_reg\fP = \fBjoin\fP(3 * [\fBgroup\fP('[0\-9][0\-9]')], ':')"
.br
.ti -1c
.RI "list \fBwaitress\&.utilities\&.months\fP"
.br
.ti -1c
.RI "dict \fBwaitress\&.utilities\&.monmap\fP = {}"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.months_reg\fP = \fBgroup\fP(\fBjoin\fP(\fBmonths\fP, '|'))"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.rfc822_date\fP"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.rfc822_reg\fP = re\&.compile(\fBrfc822_date\fP)"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.rfc850_date\fP"
.br
.ti -1c
.RI "\fBwaitress\&.utilities\&.rfc850_reg\fP = re\&.compile(\fBrfc850_date\fP)"
.br
.ti -1c
.RI "list \fBwaitress\&.utilities\&.weekdayname\fP = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']"
.br
.ti -1c
.RI "list \fBwaitress\&.utilities\&.monthname\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
