.TH "waitress.rfc7230" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waitress.rfc7230
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBHEXDIG\fP = '[0\-9a\-fA\-F]'"
.br
.ti -1c
.RI "str \fBDIGIT\fP = '[0\-9]'"
.br
.ti -1c
.RI "str \fBWS\fP = '[ \\t]'"
.br
.ti -1c
.RI "str \fBOWS\fP = \fBWS\fP + '{0,}?'"
.br
.ti -1c
.RI "str \fBRWS\fP = \fBWS\fP + '{1,}?'"
.br
.ti -1c
.RI "str \fBBWS\fP = \fBOWS\fP"
.br
.ti -1c
.RI "str \fBTCHAR\fP = r'[!#$%&'*+\\\-\&.^_`|~0\-9A\-Za\-z]'"
.br
.ti -1c
.RI "str \fBOBS_TEXT\fP = r'\\x80\-\\xff'"
.br
.ti -1c
.RI "str \fBTOKEN\fP = \fBTCHAR\fP + '{1,}'"
.br
.ti -1c
.RI "str \fBVCHAR\fP = r'\\x21\-\\x7e'"
.br
.ti -1c
.RI "str \fBQDTEXT\fP = '[\\t \\x21\\x23\-\\x5b\\\\\\x5d\-\\x7e' + \fBOBS_TEXT\fP + ']'"
.br
.ti -1c
.RI "str \fBQUOTED_PAIR\fP = r'\\\\' + '([\\t ' + VCHAR + \fBOBS_TEXT\fP + '])'"
.br
.ti -1c
.RI "str \fBQUOTED_STRING\fP = ''(?:(?:' + QDTEXT + ')|(?:' + \fBQUOTED_PAIR\fP + '))*''"
.br
.ti -1c
.RI "str \fBFIELD_VCHAR\fP = '[' + \fBVCHAR\fP + \fBOBS_TEXT\fP + ']'"
.br
.ti -1c
.RI "str \fBFIELD_CONTENT\fP = \fBFIELD_VCHAR\fP + '+(?:[ \\t]+' + FIELD_VCHAR + '+)*'"
.br
.ti -1c
.RI "str \fBFIELD_VALUE\fP = '(?:' + \fBFIELD_CONTENT\fP + ')?'"
.br
.ti -1c
.RI "str \fBCHUNK_EXT_NAME\fP = \fBTOKEN\fP"
.br
.ti -1c
.RI "str \fBCHUNK_EXT_VAL\fP = '(?:' + \fBTOKEN\fP + ')|(?:' + \fBQUOTED_STRING\fP + ')'"
.br
.ti -1c
.RI "tuple \fBCHUNK_EXT\fP"
.br
.ti -1c
.RI "\fBONLY_HEXDIG_RE\fP = re\&.compile(('^' + \fBHEXDIG\fP + '+$')\&.encode('latin\-1'))"
.br
.ti -1c
.RI "\fBONLY_DIGIT_RE\fP = re\&.compile(('^' + \fBDIGIT\fP + '+$')\&.encode('latin\-1'))"
.br
.ti -1c
.RI "\fBHEADER_FIELD_RE\fP"
.br
.ti -1c
.RI "\fBQUOTED_PAIR_RE\fP = re\&.compile(\fBQUOTED_PAIR\fP)"
.br
.ti -1c
.RI "\fBQUOTED_STRING_RE\fP = re\&.compile(\fBQUOTED_STRING\fP)"
.br
.ti -1c
.RI "\fBCHUNK_EXT_RE\fP = re\&.compile(('^' + \fBCHUNK_EXT\fP + '$')\&.encode('latin\-1'))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This contains a bunch of RFC7230 definitions and regular expressions that are
needed to properly parse HTTP messages\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "str waitress\&.rfc7230\&.BWS = \fBOWS\fP"

.SS "tuple waitress\&.rfc7230\&.CHUNK_EXT"
\fBInitial value:\fP.PP
.nf
1 =  (
2     "(?:;(?P<extension>" + CHUNK_EXT_NAME + ")(?:=(?P<value>" + CHUNK_EXT_VAL + "))?)*"
3 )
.fi

.SS "str waitress\&.rfc7230\&.CHUNK_EXT_NAME = \fBTOKEN\fP"

.SS "waitress\&.rfc7230\&.CHUNK_EXT_RE = re\&.compile(('^' + \fBCHUNK_EXT\fP + '$')\&.encode('latin\-1'))"

.SS "str waitress\&.rfc7230\&.CHUNK_EXT_VAL = '(?:' + \fBTOKEN\fP + ')|(?:' + \fBQUOTED_STRING\fP + ')'"

.SS "str waitress\&.rfc7230\&.DIGIT = '[0\-9]'"

.SS "str waitress\&.rfc7230\&.FIELD_CONTENT = \fBFIELD_VCHAR\fP + '+(?:[ \\t]+' + FIELD_VCHAR + '+)*'"

.SS "str waitress\&.rfc7230\&.FIELD_VALUE = '(?:' + \fBFIELD_CONTENT\fP + ')?'"

.SS "str waitress\&.rfc7230\&.FIELD_VCHAR = '[' + \fBVCHAR\fP + \fBOBS_TEXT\fP + ']'"

.SS "waitress\&.rfc7230\&.HEADER_FIELD_RE"
\fBInitial value:\fP.PP
.nf
1 =  re\&.compile(
2     (
3         "^(?P<name>" + TOKEN + "):" + OWS + "(?P<value>" + FIELD_VALUE + ")" + OWS + "$"
4     )\&.encode("latin\-1")
5 )
.fi

.SS "str waitress\&.rfc7230\&.HEXDIG = '[0\-9a\-fA\-F]'"

.SS "str waitress\&.rfc7230\&.OBS_TEXT = r'\\x80\-\\xff'"

.SS "waitress\&.rfc7230\&.ONLY_DIGIT_RE = re\&.compile(('^' + \fBDIGIT\fP + '+$')\&.encode('latin\-1'))"

.SS "waitress\&.rfc7230\&.ONLY_HEXDIG_RE = re\&.compile(('^' + \fBHEXDIG\fP + '+$')\&.encode('latin\-1'))"

.SS "str waitress\&.rfc7230\&.OWS = \fBWS\fP + '{0,}?'"

.SS "str waitress\&.rfc7230\&.QDTEXT = '[\\t \\x21\\x23\-\\x5b\\\\\\x5d\-\\x7e' + \fBOBS_TEXT\fP + ']'"

.SS "str waitress\&.rfc7230\&.QUOTED_PAIR = r'\\\\' + '([\\t ' + VCHAR + \fBOBS_TEXT\fP + '])'"

.SS "waitress\&.rfc7230\&.QUOTED_PAIR_RE = re\&.compile(\fBQUOTED_PAIR\fP)"

.SS "str waitress\&.rfc7230\&.QUOTED_STRING = ''(?:(?:' + QDTEXT + ')|(?:' + \fBQUOTED_PAIR\fP + '))*''"

.SS "waitress\&.rfc7230\&.QUOTED_STRING_RE = re\&.compile(\fBQUOTED_STRING\fP)"

.SS "str waitress\&.rfc7230\&.RWS = \fBWS\fP + '{1,}?'"

.SS "str waitress\&.rfc7230\&.TCHAR = r'[!#$%&'*+\\\-\&.^_`|~0\-9A\-Za\-z]'"

.SS "str waitress\&.rfc7230\&.TOKEN = \fBTCHAR\fP + '{1,}'"

.SS "str waitress\&.rfc7230\&.VCHAR = r'\\x21\-\\x7e'"

.SS "str waitress\&.rfc7230\&.WS = '[ \\t]'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
