.TH "waitress.buffers.TempfileBasedBuffer" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waitress.buffers.TempfileBasedBuffer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwaitress\&.buffers\&.FileBasedBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, from_buffer=None)"
.br
.ti -1c
.RI "\fBnewfile\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBwaitress\&.buffers\&.FileBasedBuffer\fP
.in +1c
.ti -1c
.RI "\fB__len__\fP (self)"
.br
.ti -1c
.RI "\fB__bool__\fP (self)"
.br
.ti -1c
.RI "\fBappend\fP (self, s)"
.br
.ti -1c
.RI "\fBget\fP (self, numbytes=\-1, \fBskip\fP=False)"
.br
.ti -1c
.RI "\fBskip\fP (self, numbytes, allow_prune=0)"
.br
.ti -1c
.RI "\fBprune\fP (self)"
.br
.ti -1c
.RI "\fBgetfile\fP (self)"
.br
.ti -1c
.RI "\fBclose\fP (self)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBwaitress\&.buffers\&.FileBasedBuffer\fP
.in +1c
.ti -1c
.RI "\fBfile\fP"
.br
.ti -1c
.RI "\fBremain\fP"
.br
.in -1c

Static Public Attributes inherited from \fBwaitress\&.buffers\&.FileBasedBuffer\fP
.in +1c
.ti -1c
.RI "int \fBremain\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "waitress\&.buffers\&.TempfileBasedBuffer\&.__init__ ( self,  from_buffer = \fCNone\fP)"

.PP
Reimplemented from \fBwaitress\&.buffers\&.FileBasedBuffer\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "waitress\&.buffers\&.TempfileBasedBuffer\&.newfile ( self)"

.PP
Reimplemented from \fBwaitress\&.buffers\&.FileBasedBuffer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
