.TH "waitress.wasyncore.file_wrapper" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waitress.wasyncore.file_wrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBfd\fP)"
.br
.ti -1c
.RI "\fB__del__\fP (self)"
.br
.ti -1c
.RI "\fBrecv\fP (self, *args)"
.br
.ti -1c
.RI "\fBsend\fP (self, *args)"
.br
.ti -1c
.RI "\fBgetsockopt\fP (self, level, optname, buflen=None)"
.br
.ti -1c
.RI "\fBclose\fP (self)"
.br
.ti -1c
.RI "\fBfileno\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfd\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBread\fP = \fBrecv\fP"
.br
.ti -1c
.RI "\fBwrite\fP = \fBsend\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "waitress\&.wasyncore\&.file_wrapper\&.__init__ ( self,  fd)"

.SS "waitress\&.wasyncore\&.file_wrapper\&.__del__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "waitress\&.wasyncore\&.file_wrapper\&.close ( self)"

.SS "waitress\&.wasyncore\&.file_wrapper\&.fileno ( self)"

.SS "waitress\&.wasyncore\&.file_wrapper\&.getsockopt ( self,  level,  optname,  buflen = \fCNone\fP)"

.SS "waitress\&.wasyncore\&.file_wrapper\&.recv ( self, * args)"

.SS "waitress\&.wasyncore\&.file_wrapper\&.send ( self, * args)"

.SH "Member Data Documentation"
.PP 
.SS "waitress\&.wasyncore\&.file_wrapper\&.fd"

.SS "waitress\&.wasyncore\&.file_wrapper\&.read = \fBrecv\fP\fC [static]\fP"

.SS "waitress\&.wasyncore\&.file_wrapper\&.write = \fBsend\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
