.TH "waitress.proxy_headers" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waitress.proxy_headers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMalformedProxyHeader\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBproxy_headers_middleware\fP (app, trusted_proxy=None, trusted_proxy_count=1, trusted_proxy_headers=None, clear_untrusted=True, log_untrusted=False, logger=logger)"
.br
.ti -1c
.RI "\fBparse_proxy_headers\fP (environ, trusted_proxy_count, trusted_proxy_headers, logger=logger)"
.br
.ti -1c
.RI "\fBstrip_brackets\fP (addr)"
.br
.ti -1c
.RI "\fBclear_untrusted_headers\fP (environ, untrusted_headers, log_warning=False, logger=logger)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPROXY_HEADERS\fP"
.br
.ti -1c
.RI "\fBForwarded\fP = namedtuple('Forwarded', ['by', 'for_', 'host', 'proto'])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "waitress\&.proxy_headers\&.clear_untrusted_headers ( environ,  untrusted_headers,  log_warning = \fCFalse\fP,  logger = \fClogger\fP)"

.SS "waitress\&.proxy_headers\&.parse_proxy_headers ( environ,  trusted_proxy_count,  trusted_proxy_headers,  logger = \fClogger\fP)"

.SS "waitress\&.proxy_headers\&.proxy_headers_middleware ( app,  trusted_proxy = \fCNone\fP,  trusted_proxy_count = \fC1\fP,  trusted_proxy_headers = \fCNone\fP,  clear_untrusted = \fCTrue\fP,  log_untrusted = \fCFalse\fP,  logger = \fClogger\fP)"

.SS "waitress\&.proxy_headers\&.strip_brackets ( addr)"

.SH "Variable Documentation"
.PP 
.SS "waitress\&.proxy_headers\&.Forwarded = namedtuple('Forwarded', ['by', 'for_', 'host', 'proto'])"

.SS "waitress\&.proxy_headers\&.PROXY_HEADERS"
\fBInitial value:\fP.PP
.nf
1 =  frozenset(
2     {
3         "X_FORWARDED_FOR",
4         "X_FORWARDED_HOST",
5         "X_FORWARDED_PROTO",
6         "X_FORWARDED_PORT",
7         "X_FORWARDED_BY",
8         "FORWARDED",
9     }
10 )
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
