.TH "waitress.utilities" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waitress.utilities
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBadRequest\fP"
.br
.ti -1c
.RI "class \fBError\fP"
.br
.ti -1c
.RI "class \fBInternalServerError\fP"
.br
.ti -1c
.RI "class \fBRequestEntityTooLarge\fP"
.br
.ti -1c
.RI "class \fBRequestHeaderFieldsTooLarge\fP"
.br
.ti -1c
.RI "class \fBServerNotImplemented\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfind_double_newline\fP (s)"
.br
.ti -1c
.RI "\fBconcat\fP (*args)"
.br
.ti -1c
.RI "\fBjoin\fP (seq, field=' ')"
.br
.ti -1c
.RI "\fBgroup\fP (s)"
.br
.ti -1c
.RI "\fBunpack_rfc822\fP (m)"
.br
.ti -1c
.RI "\fBunpack_rfc850\fP (m)"
.br
.ti -1c
.RI "\fBbuild_http_date\fP (when)"
.br
.ti -1c
.RI "\fBparse_http_date\fP (d)"
.br
.ti -1c
.RI "\fBundquote\fP (value)"
.br
.ti -1c
.RI "\fBcleanup_unix_socket\fP (path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger('waitress')"
.br
.ti -1c
.RI "\fBqueue_logger\fP = logging\&.getLogger('waitress\&.queue')"
.br
.ti -1c
.RI "list \fBshort_days\fP = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']"
.br
.ti -1c
.RI "list \fBlong_days\fP"
.br
.ti -1c
.RI "\fBshort_day_reg\fP = \fBgroup\fP(\fBjoin\fP(\fBshort_days\fP, '|'))"
.br
.ti -1c
.RI "\fBlong_day_reg\fP = \fBgroup\fP(\fBjoin\fP(\fBlong_days\fP, '|'))"
.br
.ti -1c
.RI "dict \fBdaymap\fP = {}"
.br
.ti -1c
.RI "\fBhms_reg\fP = \fBjoin\fP(3 * [\fBgroup\fP('[0\-9][0\-9]')], ':')"
.br
.ti -1c
.RI "list \fBmonths\fP"
.br
.ti -1c
.RI "dict \fBmonmap\fP = {}"
.br
.ti -1c
.RI "\fBmonths_reg\fP = \fBgroup\fP(\fBjoin\fP(\fBmonths\fP, '|'))"
.br
.ti -1c
.RI "\fBrfc822_date\fP"
.br
.ti -1c
.RI "\fBrfc822_reg\fP = re\&.compile(\fBrfc822_date\fP)"
.br
.ti -1c
.RI "\fBrfc850_date\fP"
.br
.ti -1c
.RI "\fBrfc850_reg\fP = re\&.compile(\fBrfc850_date\fP)"
.br
.ti -1c
.RI "list \fBweekdayname\fP = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']"
.br
.ti -1c
.RI "list \fBmonthname\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "waitress\&.utilities\&.build_http_date ( when)"

.SS "waitress\&.utilities\&.cleanup_unix_socket ( path)"

.SS "waitress\&.utilities\&.concat (* args)"

.SS "waitress\&.utilities\&.find_double_newline ( s)"

.PP
.nf
Returns the position just after a double newline in the given string\&.
.fi
.PP
 
.SS "waitress\&.utilities\&.group ( s)"

.SS "waitress\&.utilities\&.join ( seq,  field = \fC' '\fP)"

.SS "waitress\&.utilities\&.parse_http_date ( d)"

.SS "waitress\&.utilities\&.undquote ( value)"

.SS "waitress\&.utilities\&.unpack_rfc822 ( m)"

.SS "waitress\&.utilities\&.unpack_rfc850 ( m)"

.SH "Variable Documentation"
.PP 
.SS "dict waitress\&.utilities\&.daymap = {}"

.SS "waitress\&.utilities\&.hms_reg = \fBjoin\fP(3 * [\fBgroup\fP('[0\-9][0\-9]')], ':')"

.SS "waitress\&.utilities\&.logger = logging\&.getLogger('waitress')"

.SS "waitress\&.utilities\&.long_day_reg = \fBgroup\fP(\fBjoin\fP(\fBlong_days\fP, '|'))"

.SS "list waitress\&.utilities\&.long_days"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "sunday",
3     "monday",
4     "tuesday",
5     "wednesday",
6     "thursday",
7     "friday",
8     "saturday",
9 ]
.fi

.SS "dict waitress\&.utilities\&.monmap = {}"

.SS "list waitress\&.utilities\&.monthname"
\fBInitial value:\fP.PP
.nf
1 =  [
2     None,
3     "Jan",
4     "Feb",
5     "Mar",
6     "Apr",
7     "May",
8     "Jun",
9     "Jul",
10     "Aug",
11     "Sep",
12     "Oct",
13     "Nov",
14     "Dec",
15 ]
.fi

.SS "list waitress\&.utilities\&.months"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "jan",
3     "feb",
4     "mar",
5     "apr",
6     "may",
7     "jun",
8     "jul",
9     "aug",
10     "sep",
11     "oct",
12     "nov",
13     "dec",
14 ]
.fi

.SS "waitress\&.utilities\&.months_reg = \fBgroup\fP(\fBjoin\fP(\fBmonths\fP, '|'))"

.SS "waitress\&.utilities\&.queue_logger = logging\&.getLogger('waitress\&.queue')"

.SS "waitress\&.utilities\&.rfc822_date"
\fBInitial value:\fP.PP
.nf
1 =  join(
2     [
3         concat(short_day_reg, ","),  # day
4         group("[0\-9][0\-9]?"),  # date
5         months_reg,  # month
6         group("[0\-9]+"),  # year
7         hms_reg,  # hour minute second
8         "gmt",
9     ],
10     " ",
11 )
.fi

.SS "waitress\&.utilities\&.rfc822_reg = re\&.compile(\fBrfc822_date\fP)"

.SS "waitress\&.utilities\&.rfc850_date"
\fBInitial value:\fP.PP
.nf
1 =  join(
2     [
3         concat(long_day_reg, ","),
4         join([group("[0\-9][0\-9]?"), months_reg, group("[0\-9]+")], "\-"),
5         hms_reg,
6         "gmt",
7     ],
8     " ",
9 )
.fi

.SS "waitress\&.utilities\&.rfc850_reg = re\&.compile(\fBrfc850_date\fP)"

.SS "waitress\&.utilities\&.short_day_reg = \fBgroup\fP(\fBjoin\fP(\fBshort_days\fP, '|'))"

.SS "list waitress\&.utilities\&.short_days = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']"

.SS "list waitress\&.utilities\&.weekdayname = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
