.TH "waitress.parser.HTTPRequestParser" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waitress.parser.HTTPRequestParser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBadj\fP)"
.br
.ti -1c
.RI "\fBreceived\fP (self, data)"
.br
.ti -1c
.RI "\fBparse_header\fP (self, \fBheader_plus\fP)"
.br
.ti -1c
.RI "\fBget_body_stream\fP (self)"
.br
.ti -1c
.RI "\fBclose\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBheaders\fP"
.br
.ti -1c
.RI "\fBadj\fP"
.br
.ti -1c
.RI "\fBheader_bytes_received\fP"
.br
.ti -1c
.RI "\fBcompleted\fP"
.br
.ti -1c
.RI "\fBempty\fP"
.br
.ti -1c
.RI "\fBheaders_finished\fP"
.br
.ti -1c
.RI "\fBheader_plus\fP"
.br
.ti -1c
.RI "\fBfirst_line\fP"
.br
.ti -1c
.RI "\fBrequest_uri\fP"
.br
.ti -1c
.RI "\fBcommand\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBproxy_scheme\fP"
.br
.ti -1c
.RI "\fBproxy_netloc\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBquery\fP"
.br
.ti -1c
.RI "\fBfragment\fP"
.br
.ti -1c
.RI "\fBurl_scheme\fP"
.br
.ti -1c
.RI "\fBconnection_close\fP"
.br
.ti -1c
.RI "\fBchunked\fP"
.br
.ti -1c
.RI "\fBexpect_continue\fP"
.br
.ti -1c
.RI "\fBcontent_length\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBcompleted\fP = False"
.br
.ti -1c
.RI "bool \fBempty\fP = False"
.br
.ti -1c
.RI "bool \fBexpect_continue\fP = False"
.br
.ti -1c
.RI "bool \fBheaders_finished\fP = False"
.br
.ti -1c
.RI "str \fBheader_plus\fP = b''"
.br
.ti -1c
.RI "bool \fBchunked\fP = False"
.br
.ti -1c
.RI "int \fBcontent_length\fP = 0"
.br
.ti -1c
.RI "int \fBheader_bytes_received\fP = 0"
.br
.ti -1c
.RI "int \fBbody_bytes_received\fP = 0"
.br
.ti -1c
.RI "\fBbody_rcv\fP = None"
.br
.ti -1c
.RI "str \fBversion\fP = '1\&.0'"
.br
.ti -1c
.RI "\fBerror\fP = None"
.br
.ti -1c
.RI "bool \fBconnection_close\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A structure that collects the HTTP request\&.

Once the stream is completed, the instance is passed to
a server task constructor\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "waitress\&.parser\&.HTTPRequestParser\&.__init__ ( self,  adj)"

.PP
.nf
adj is an Adjustments object\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "waitress\&.parser\&.HTTPRequestParser\&.close ( self)"

.SS "waitress\&.parser\&.HTTPRequestParser\&.get_body_stream ( self)"

.SS "waitress\&.parser\&.HTTPRequestParser\&.parse_header ( self,  header_plus)"

.PP
.nf
Parses the header_plus block of text (the headers plus the
first line of the request)\&.

.fi
.PP
 
.SS "waitress\&.parser\&.HTTPRequestParser\&.received ( self,  data)"

.PP
.nf
Receives the HTTP stream for one request\&.  Returns the number of
bytes consumed\&.  Sets the completed flag once both the header and the
body have been received\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "waitress\&.parser\&.HTTPRequestParser\&.adj"

.SS "int waitress\&.parser\&.HTTPRequestParser\&.body_bytes_received = 0\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.body_rcv = None\fC [static]\fP"

.SS "bool waitress\&.parser\&.HTTPRequestParser\&.chunked = False\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.chunked"

.SS "waitress\&.parser\&.HTTPRequestParser\&.command"

.SS "bool waitress\&.parser\&.HTTPRequestParser\&.completed = False\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.completed"

.SS "bool waitress\&.parser\&.HTTPRequestParser\&.connection_close = False\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.connection_close"

.SS "int waitress\&.parser\&.HTTPRequestParser\&.content_length = 0\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.content_length"

.SS "bool waitress\&.parser\&.HTTPRequestParser\&.empty = False\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.empty"

.SS "waitress\&.parser\&.HTTPRequestParser\&.error = None\fC [static]\fP"

.SS "bool waitress\&.parser\&.HTTPRequestParser\&.expect_continue = False\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.expect_continue"

.SS "waitress\&.parser\&.HTTPRequestParser\&.first_line"

.SS "waitress\&.parser\&.HTTPRequestParser\&.fragment"

.SS "int waitress\&.parser\&.HTTPRequestParser\&.header_bytes_received = 0\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.header_bytes_received"

.SS "str waitress\&.parser\&.HTTPRequestParser\&.header_plus = b''\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.header_plus"

.SS "waitress\&.parser\&.HTTPRequestParser\&.headers"

.SS "bool waitress\&.parser\&.HTTPRequestParser\&.headers_finished = False\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.headers_finished"

.SS "waitress\&.parser\&.HTTPRequestParser\&.path"

.SS "waitress\&.parser\&.HTTPRequestParser\&.proxy_netloc"

.SS "waitress\&.parser\&.HTTPRequestParser\&.proxy_scheme"

.SS "waitress\&.parser\&.HTTPRequestParser\&.query"

.SS "waitress\&.parser\&.HTTPRequestParser\&.request_uri"

.SS "waitress\&.parser\&.HTTPRequestParser\&.url_scheme"

.SS "str waitress\&.parser\&.HTTPRequestParser\&.version = '1\&.0'\fC [static]\fP"

.SS "waitress\&.parser\&.HTTPRequestParser\&.version"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
