.TH "waitress.task.ErrorTask" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waitress.task.ErrorTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwaitress\&.task\&.Task\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecute\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBwaitress\&.task\&.Task\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBchannel\fP, \fBrequest\fP)"
.br
.ti -1c
.RI "\fBservice\fP (self)"
.br
.ti -1c
.RI "\fBhas_body\fP (self)"
.br
.ti -1c
.RI "None \fBset_close_on_finish\fP (self)"
.br
.ti -1c
.RI "\fBbuild_response_header\fP (self)"
.br
.ti -1c
.RI "\fBremove_content_length_header\fP (self)"
.br
.ti -1c
.RI "\fBstart\fP (self)"
.br
.ti -1c
.RI "\fBfinish\fP (self)"
.br
.ti -1c
.RI "\fBwrite\fP (self, data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatus\fP"
.br
.ti -1c
.RI "\fBcontent_length\fP"
.br
.in -1c

Public Attributes inherited from \fBwaitress\&.task\&.Task\fP
.in +1c
.ti -1c
.RI "\fBchannel\fP"
.br
.ti -1c
.RI "\fBrequest\fP"
.br
.ti -1c
.RI "\fBresponse_headers\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBclose_on_finish\fP"
.br
.ti -1c
.RI "\fBchunked_response\fP"
.br
.ti -1c
.RI "\fBstart_time\fP"
.br
.ti -1c
.RI "\fBwrote_header\fP"
.br
.ti -1c
.RI "\fBlogged_write_excess\fP"
.br
.ti -1c
.RI "\fBlogged_write_no_body\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBcomplete\fP = True"
.br
.in -1c

Static Public Attributes inherited from \fBwaitress\&.task\&.Task\fP
.in +1c
.ti -1c
.RI "bool \fBclose_on_finish\fP = False"
.br
.ti -1c
.RI "str \fBstatus\fP = '200 OK'"
.br
.ti -1c
.RI "bool \fBwrote_header\fP = False"
.br
.ti -1c
.RI "int \fBstart_time\fP = 0"
.br
.ti -1c
.RI "\fBcontent_length\fP = None"
.br
.ti -1c
.RI "int \fBcontent_bytes_written\fP = 0"
.br
.ti -1c
.RI "bool \fBlogged_write_excess\fP = False"
.br
.ti -1c
.RI "bool \fBlogged_write_no_body\fP = False"
.br
.ti -1c
.RI "bool \fBcomplete\fP = False"
.br
.ti -1c
.RI "bool \fBchunked_response\fP = False"
.br
.ti -1c
.RI "\fBlogger\fP = logger"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An error task produces an error response
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "waitress\&.task\&.ErrorTask\&.execute ( self)"

.SH "Member Data Documentation"
.PP 
.SS "bool waitress\&.task\&.ErrorTask\&.complete = True\fC [static]\fP"

.SS "waitress\&.task\&.ErrorTask\&.content_length"

.SS "waitress\&.task\&.ErrorTask\&.status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
