.TH "waitress.adjustments.Adjustments" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waitress.adjustments.Adjustments
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, **kw)"
.br
.ti -1c
.RI "\fBparse_args\fP (cls, argv)"
.br
.ti -1c
.RI "\fBcheck_sockets\fP (cls, \fBsockets\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlisten\fP"
.br
.ti -1c
.RI "\fBsockets\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBhost\fP = \fB_str_marker\fP('0\&.0\&.0\&.0')"
.br
.ti -1c
.RI "\fBport\fP = \fB_int_marker\fP(8080)"
.br
.ti -1c
.RI "list \fBlisten\fP = [f'{\fBhost\fP}:{\fBport\fP}']"
.br
.ti -1c
.RI "int \fBthreads\fP = 4"
.br
.ti -1c
.RI "\fBtrusted_proxy\fP = None"
.br
.ti -1c
.RI "\fBtrusted_proxy_count\fP = None"
.br
.ti -1c
.RI "\fBtrusted_proxy_headers\fP = set()"
.br
.ti -1c
.RI "bool \fBlog_untrusted_proxy_headers\fP = False"
.br
.ti -1c
.RI "bool \fBclear_untrusted_proxy_headers\fP = True"
.br
.ti -1c
.RI "str \fBurl_scheme\fP = 'http'"
.br
.ti -1c
.RI "str \fBurl_prefix\fP = ''"
.br
.ti -1c
.RI "str \fBident\fP = 'waitress'"
.br
.ti -1c
.RI "int \fBbacklog\fP = 1024"
.br
.ti -1c
.RI "int \fBrecv_bytes\fP = 8192"
.br
.ti -1c
.RI "int \fBsend_bytes\fP = 1"
.br
.ti -1c
.RI "int \fBoutbuf_overflow\fP = 1048576"
.br
.ti -1c
.RI "int \fBoutbuf_high_watermark\fP = 16777216"
.br
.ti -1c
.RI "int \fBinbuf_overflow\fP = 524288"
.br
.ti -1c
.RI "int \fBconnection_limit\fP = 100"
.br
.ti -1c
.RI "int \fBcleanup_interval\fP = 30"
.br
.ti -1c
.RI "int \fBchannel_timeout\fP = 120"
.br
.ti -1c
.RI "bool \fBlog_socket_errors\fP = True"
.br
.ti -1c
.RI "int \fBmax_request_header_size\fP = 262144"
.br
.ti -1c
.RI "int \fBmax_request_body_size\fP = 1073741824"
.br
.ti -1c
.RI "bool \fBexpose_tracebacks\fP = False"
.br
.ti -1c
.RI "\fBunix_socket\fP = None"
.br
.ti -1c
.RI "int \fBunix_socket_perms\fP = 0o600"
.br
.ti -1c
.RI "list \fBsocket_options\fP"
.br
.ti -1c
.RI "int \fBasyncore_loop_timeout\fP = 1"
.br
.ti -1c
.RI "bool \fBasyncore_use_poll\fP = False"
.br
.ti -1c
.RI "bool \fBipv4\fP = True"
.br
.ti -1c
.RI "bool \fBipv6\fP = True"
.br
.ti -1c
.RI "list \fBsockets\fP = []"
.br
.ti -1c
.RI "int \fBchannel_request_lookahead\fP = 0"
.br
.ti -1c
.RI "str \fBserver_name\fP = 'waitress\&.invalid'"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "tuple \fB_params\fP"
.br
.ti -1c
.RI "\fB_param_map\fP = dict(\fB_params\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class contains tunable parameters\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "waitress\&.adjustments\&.Adjustments\&.__init__ ( self, ** kw)"

.SH "Member Function Documentation"
.PP 
.SS "waitress\&.adjustments\&.Adjustments\&.check_sockets ( cls,  sockets)"

.SS "waitress\&.adjustments\&.Adjustments\&.parse_args ( cls,  argv)"

.PP
.nf
Pre-parse command line arguments for input into __init__\&.  Note that
this does not cast values into adjustment types, it just creates a
dictionary suitable for passing into __init__, where __init__ does the
casting\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "waitress\&.adjustments\&.Adjustments\&._param_map = dict(\fB_params\fP)\fC [static]\fP, \fC [protected]\fP"

.SS "tuple waitress\&.adjustments\&.Adjustments\&._params\fC [static]\fP, \fC [protected]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.asyncore_loop_timeout = 1\fC [static]\fP"

.SS "bool waitress\&.adjustments\&.Adjustments\&.asyncore_use_poll = False\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.backlog = 1024\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.channel_request_lookahead = 0\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.channel_timeout = 120\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.cleanup_interval = 30\fC [static]\fP"

.SS "bool waitress\&.adjustments\&.Adjustments\&.clear_untrusted_proxy_headers = True\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.connection_limit = 100\fC [static]\fP"

.SS "bool waitress\&.adjustments\&.Adjustments\&.expose_tracebacks = False\fC [static]\fP"

.SS "waitress\&.adjustments\&.Adjustments\&.host = \fB_str_marker\fP('0\&.0\&.0\&.0')\fC [static]\fP"

.SS "str waitress\&.adjustments\&.Adjustments\&.ident = 'waitress'\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.inbuf_overflow = 524288\fC [static]\fP"

.SS "bool waitress\&.adjustments\&.Adjustments\&.ipv4 = True\fC [static]\fP"

.SS "bool waitress\&.adjustments\&.Adjustments\&.ipv6 = True\fC [static]\fP"

.SS "list waitress\&.adjustments\&.Adjustments\&.listen = [f'{\fBhost\fP}:{\fBport\fP}']\fC [static]\fP"

.SS "waitress\&.adjustments\&.Adjustments\&.listen"

.SS "bool waitress\&.adjustments\&.Adjustments\&.log_socket_errors = True\fC [static]\fP"

.SS "bool waitress\&.adjustments\&.Adjustments\&.log_untrusted_proxy_headers = False\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.max_request_body_size = 1073741824\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.max_request_header_size = 262144\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.outbuf_high_watermark = 16777216\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.outbuf_overflow = 1048576\fC [static]\fP"

.SS "waitress\&.adjustments\&.Adjustments\&.port = \fB_int_marker\fP(8080)\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.recv_bytes = 8192\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.send_bytes = 1\fC [static]\fP"

.SS "str waitress\&.adjustments\&.Adjustments\&.server_name = 'waitress\&.invalid'\fC [static]\fP"

.SS "list waitress\&.adjustments\&.Adjustments\&.socket_options\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
=  [
        (socket\&.SOL_TCP, socket\&.TCP_NODELAY, 1),
    ]
.fi

.SS "list waitress\&.adjustments\&.Adjustments\&.sockets = []\fC [static]\fP"

.SS "waitress\&.adjustments\&.Adjustments\&.sockets"

.SS "int waitress\&.adjustments\&.Adjustments\&.threads = 4\fC [static]\fP"

.SS "waitress\&.adjustments\&.Adjustments\&.trusted_proxy = None\fC [static]\fP"

.SS "waitress\&.adjustments\&.Adjustments\&.trusted_proxy_count = None\fC [static]\fP"

.SS "waitress\&.adjustments\&.Adjustments\&.trusted_proxy_headers = set()\fC [static]\fP"

.SS "waitress\&.adjustments\&.Adjustments\&.unix_socket = None\fC [static]\fP"

.SS "int waitress\&.adjustments\&.Adjustments\&.unix_socket_perms = 0o600\fC [static]\fP"

.SS "str waitress\&.adjustments\&.Adjustments\&.url_prefix = ''\fC [static]\fP"

.SS "str waitress\&.adjustments\&.Adjustments\&.url_scheme = 'http'\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
