.TH "webob.exc.HTTPException" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.exc.HTTPException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBwebob\&.exc\&.WSGIHTTPException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, message, \fBwsgi_response\fP)"
.br
.ti -1c
.RI "\fB__call__\fP (self, environ, start_response)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwsgi_response\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "webob\&.exc\&.HTTPException\&.__init__ ( self,  message,  wsgi_response)"

.PP
Reimplemented in \fBwebob\&.exc\&.WSGIHTTPException\fP, and \fBwebob\&.exc\&._HTTPMove\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "webob\&.exc\&.HTTPException\&.__call__ ( self,  environ,  start_response)"

.PP
Reimplemented in \fBwebob\&.exc\&.WSGIHTTPException\fP, and \fBwebob\&.exc\&._HTTPMove\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "webob\&.exc\&.HTTPException\&.wsgi_response"

.PP
Reimplemented in \fBwebob\&.exc\&.WSGIHTTPException\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
