.TH "webob.cachecontrol.exists_property" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.cachecontrol.exists_property
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBprop\fP, \fBtype\fP=None)"
.br
.ti -1c
.RI "\fB__get__\fP (self, obj, \fBtype\fP=None)"
.br
.ti -1c
.RI "\fB__set__\fP (self, obj, value)"
.br
.ti -1c
.RI "\fB__delete__\fP (self, obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprop\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a property that either is listed in the Cache-Control
header, or is not listed (has no value)

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "webob\&.cachecontrol\&.exists_property\&.__init__ ( self,  prop,  type = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "webob\&.cachecontrol\&.exists_property\&.__delete__ ( self,  obj)"

.SS "webob\&.cachecontrol\&.exists_property\&.__get__ ( self,  obj,  type = \fCNone\fP)"

.SS "webob\&.cachecontrol\&.exists_property\&.__set__ ( self,  obj,  value)"

.SH "Member Data Documentation"
.PP 
.SS "webob\&.cachecontrol\&.exists_property\&.prop"

.SS "webob\&.cachecontrol\&.exists_property\&.type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
