.TH "webob.multidict" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.multidict
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGetDict\fP"
.br
.ti -1c
.RI "class \fBMultiDict\fP"
.br
.ti -1c
.RI "class \fBNestedMultiDict\fP"
.br
.ti -1c
.RI "class \fBNoVars\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_hide_passwd\fP (items)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_dummy\fP = object()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Gives a multi-value dictionary object (MultiDict) plus several wrappers

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "webob\&.multidict\&._hide_passwd ( items)\fC [protected]\fP"

.SH "Variable Documentation"
.PP 
.SS "webob\&.multidict\&._dummy = object()\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
