.TH "webob.static.FileIter" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.static.FileIter
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBfile\fP)"
.br
.ti -1c
.RI "\fBapp_iter_range\fP (self, seek=None, limit=None, block_size=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfile\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "webob\&.static\&.FileIter\&.__init__ ( self,  file)"

.SH "Member Function Documentation"
.PP 
.SS "webob\&.static\&.FileIter\&.app_iter_range ( self,  seek = \fCNone\fP,  limit = \fCNone\fP,  block_size = \fCNone\fP)"

.PP
.nf
Iter over the content of the file\&.

You can set the `seek` parameter to read the file starting from a
specific position\&.

You can set the `limit` parameter to read the file up to specific
position\&.

Finally, you can change the number of bytes read at once by setting the
`block_size` parameter\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "webob\&.static\&.FileIter\&.file"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
