.TH "webob.cookies.Morsel" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.cookies.Morsel
.SH SYNOPSIS
.br
.PP
.PP
Inherits dict\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBname\fP, \fBvalue\fP)"
.br
.ti -1c
.RI "\fB__setitem__\fP (self, k, v)"
.br
.ti -1c
.RI "\fBserialize\fP (self, full=True)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBvalue\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBpath\fP = \fBcookie_property\fP(b'path')"
.br
.ti -1c
.RI "\fBdomain\fP = \fBcookie_property\fP(b'domain')"
.br
.ti -1c
.RI "\fBcomment\fP = \fBcookie_property\fP(b'comment')"
.br
.ti -1c
.RI "\fBexpires\fP = \fBcookie_property\fP(b'expires', \fBserialize_cookie_date\fP)"
.br
.ti -1c
.RI "\fBmax_age\fP = \fBcookie_property\fP(b'max\-age', \fBserialize_max_age\fP)"
.br
.ti -1c
.RI "\fBhttponly\fP = \fBcookie_property\fP(b'httponly', bool)"
.br
.ti -1c
.RI "\fBsecure\fP = \fBcookie_property\fP(b'secure', bool)"
.br
.ti -1c
.RI "\fBsamesite\fP = \fBcookie_property\fP(b'samesite', \fBserialize_samesite\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "webob\&.cookies\&.Morsel\&.__init__ ( self,  name,  value)"

.SH "Member Function Documentation"
.PP 
.SS "webob\&.cookies\&.Morsel\&.__repr__ ( self)"

.SS "webob\&.cookies\&.Morsel\&.__setitem__ ( self,  k,  v)"

.SS "webob\&.cookies\&.Morsel\&.serialize ( self,  full = \fCTrue\fP)"

.SH "Member Data Documentation"
.PP 
.SS "webob\&.cookies\&.Morsel\&.comment = \fBcookie_property\fP(b'comment')\fC [static]\fP"

.SS "webob\&.cookies\&.Morsel\&.domain = \fBcookie_property\fP(b'domain')\fC [static]\fP"

.SS "webob\&.cookies\&.Morsel\&.expires = \fBcookie_property\fP(b'expires', \fBserialize_cookie_date\fP)\fC [static]\fP"

.SS "webob\&.cookies\&.Morsel\&.httponly = \fBcookie_property\fP(b'httponly', bool)\fC [static]\fP"

.SS "webob\&.cookies\&.Morsel\&.max_age = \fBcookie_property\fP(b'max\-age', \fBserialize_max_age\fP)\fC [static]\fP"

.SS "webob\&.cookies\&.Morsel\&.name"

.SS "webob\&.cookies\&.Morsel\&.path = \fBcookie_property\fP(b'path')\fC [static]\fP"

.SS "webob\&.cookies\&.Morsel\&.samesite = \fBcookie_property\fP(b'samesite', \fBserialize_samesite\fP)\fC [static]\fP"

.SS "webob\&.cookies\&.Morsel\&.secure = \fBcookie_property\fP(b'secure', bool)\fC [static]\fP"

.SS "webob\&.cookies\&.Morsel\&.value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
