.TH "webob.multidict.MultiDict" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.multidict.MultiDict
.SH SYNOPSIS
.br
.PP
.PP
Inherits MutableMapping\&.
.PP
Inherited by \fBwebob\&.headers\&.ResponseHeaders\fP, \fBwebob\&.multidict\&.GetDict\fP, and \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, *args, **kw)"
.br
.ti -1c
.RI "\fBview_list\fP (cls, lst)"
.br
.ti -1c
.RI "\fBfrom_fieldstorage\fP (cls, fs)"
.br
.ti -1c
.RI "\fB__getitem__\fP (self, key)"
.br
.ti -1c
.RI "\fB__setitem__\fP (self, key, value)"
.br
.ti -1c
.RI "\fBadd\fP (self, key, value)"
.br
.ti -1c
.RI "\fBgetall\fP (self, key)"
.br
.ti -1c
.RI "\fBgetone\fP (self, key)"
.br
.ti -1c
.RI "\fBmixed\fP (self)"
.br
.ti -1c
.RI "\fBdict_of_lists\fP (self)"
.br
.ti -1c
.RI "\fB__delitem__\fP (self, key)"
.br
.ti -1c
.RI "\fB__contains__\fP (self, key)"
.br
.ti -1c
.RI "\fBclear\fP (self)"
.br
.ti -1c
.RI "\fBcopy\fP (self)"
.br
.ti -1c
.RI "\fBsetdefault\fP (self, key, default=None)"
.br
.ti -1c
.RI "\fBpop\fP (self, key, *args)"
.br
.ti -1c
.RI "\fBpopitem\fP (self)"
.br
.ti -1c
.RI "\fBupdate\fP (self, *args, **kw)"
.br
.ti -1c
.RI "\fBextend\fP (self, other=None, **kwargs)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__len__\fP (self)"
.br
.ti -1c
.RI "\fBiterkeys\fP (self)"
.br
.RI "All the iteration: "
.ti -1c
.RI "\fBkeys\fP (self)"
.br
.ti -1c
.RI "\fBiteritems\fP (self)"
.br
.ti -1c
.RI "\fBitems\fP (self)"
.br
.ti -1c
.RI "\fBitervalues\fP (self)"
.br
.ti -1c
.RI "\fBvalues\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBhas_key\fP = \fB__contains__\fP"
.br
.ti -1c
.RI "\fBkeys\fP = \fBiterkeys\fP"
.br
.ti -1c
.RI "\fBitems\fP = \fBiteritems\fP"
.br
.ti -1c
.RI "\fBvalues\fP = \fBitervalues\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_items\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    An ordered dictionary that can have multiple values for each key\&.
    Adds the methods getall, getone, mixed and extend and add to the normal
    dictionary interface\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "webob\&.multidict\&.MultiDict\&.__init__ ( self, * args, ** kw)"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP, and \fBwebob\&.multidict\&.GetDict\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "webob\&.multidict\&.MultiDict\&.__contains__ ( self,  key)"

.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP, and \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.__delitem__ ( self,  key)"

.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP, and \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.__getitem__ ( self,  key)"

.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP, and \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.__len__ ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.__repr__ ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.__setitem__ ( self,  key,  value)"

.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP, and \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.add ( self,  key,  value)"

.PP
.nf
Add the key and value, not overwriting any previous value\&.

.fi
.PP
 
.PP
Reimplemented in \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.clear ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.copy ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.GetDict\fP, and \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.dict_of_lists ( self)"

.PP
.nf
Returns a dictionary where each key is associated with a list of values\&.

.fi
.PP
 
.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.extend ( self,  other = \fCNone\fP, ** kwargs)"

.PP
Reimplemented in \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.from_fieldstorage ( cls,  fs)"

.PP
.nf
Create a dict from a cgi\&.FieldStorage instance

.fi
.PP
 
.SS "webob\&.multidict\&.MultiDict\&.getall ( self,  key)"

.PP
.nf
Return a list of all values matching the key (may be an empty list)

.fi
.PP
 
.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP, and \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.getone ( self,  key)"

.PP
.nf
Get one value matching the key, raising a KeyError if multiple
values were found\&.

.fi
.PP
 
.SS "webob\&.multidict\&.MultiDict\&.items ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.iteritems ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.iterkeys ( self)"

.PP
All the iteration: 
.SS "webob\&.multidict\&.MultiDict\&.itervalues ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.keys ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.mixed ( self)"

.PP
.nf
Returns a dictionary where the values are either single
values, or a list of values when a key/value appears more than
once in this dictionary\&.  This is similar to the kind of
dictionary often used to represent the variables in a web
request\&.

.fi
.PP
 
.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.pop ( self,  key, * args)"

.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP, and \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.popitem ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.setdefault ( self,  key,  default = \fCNone\fP)"

.PP
Reimplemented in \fBwebob\&.headers\&.ResponseHeaders\fP, and \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.update ( self, * args, ** kw)"

.PP
Reimplemented in \fBwebob\&.multidict\&.GetDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.values ( self)"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.view_list ( cls,  lst)"

.PP
.nf
Create a dict that is a view on the given list

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "webob\&.multidict\&.MultiDict\&._items\fC [protected]\fP"

.SS "webob\&.multidict\&.MultiDict\&.has_key = \fB__contains__\fP\fC [static]\fP"

.SS "webob\&.multidict\&.MultiDict\&.items = \fBiteritems\fP\fC [static]\fP"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.keys = \fBiterkeys\fP\fC [static]\fP"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.
.SS "webob\&.multidict\&.MultiDict\&.values = \fBitervalues\fP\fC [static]\fP"

.PP
Reimplemented in \fBwebob\&.multidict\&.NestedMultiDict\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
