.TH "webob.cachecontrol" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.cachecontrol
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCacheControl\fP"
.br
.ti -1c
.RI "class \fBexists_property\fP"
.br
.ti -1c
.RI "class \fBUpdateDict\fP"
.br
.ti -1c
.RI "class \fBvalue_property\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBserialize_cache_control\fP (properties)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtoken_re\fP"
.br
.ti -1c
.RI "\fBneed_quote_re\fP = re\&.compile(r'[^a\-zA\-Z0\-9\&._\-]')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents the Cache-Control header

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "webob\&.cachecontrol\&.serialize_cache_control ( properties)"

.SH "Variable Documentation"
.PP 
.SS "webob\&.cachecontrol\&.need_quote_re = re\&.compile(r'[^a\-zA\-Z0\-9\&._\-]')"

.SS "webob\&.cachecontrol\&.token_re"
\fBInitial value:\fP.PP
.nf
1 =  re\&.compile(
2     r'([a\-zA\-Z][a\-zA\-Z_\-]*)\\s*(?:=(?:"([^"]*)"|([^ \\t",;]*)))?')
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
