.TH "webob.request.Transcoder" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.request.Transcoder
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBcharset\fP, \fBerrors\fP='strict')"
.br
.ti -1c
.RI "\fBtranscode_query\fP (self, q)"
.br
.ti -1c
.RI "\fBtranscode_fs\fP (self, fs, content_type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcharset\fP"
.br
.ti -1c
.RI "\fBerrors\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_trans\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "webob\&.request\&.Transcoder\&.__init__ ( self,  charset,  errors = \fC'strict'\fP)"

.SH "Member Function Documentation"
.PP 
.SS "webob\&.request\&.Transcoder\&.transcode_fs ( self,  fs,  content_type)"

.SS "webob\&.request\&.Transcoder\&.transcode_query ( self,  q)"

.SH "Member Data Documentation"
.PP 
.SS "webob\&.request\&.Transcoder\&._trans\fC [protected]\fP"

.SS "webob\&.request\&.Transcoder\&.charset"

.SS "webob\&.request\&.Transcoder\&.errors"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
