.TH "webob.static.FileApp" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webob.static.FileApp
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBfilename\fP, **\fBkw\fP)"
.br
.ti -1c
.RI "\fB__call__\fP (self, req)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBkw\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_open\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An application that will send the file at the given filename\&.

Adds a mime type based on `mimetypes\&.guess_type()`\&.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "webob\&.static\&.FileApp\&.__init__ ( self,  filename, ** kw)"

.SH "Member Function Documentation"
.PP 
.SS "webob\&.static\&.FileApp\&.__call__ ( self,  req)"

.SH "Member Data Documentation"
.PP 
.SS "webob\&.static\&.FileApp\&._open\fC [protected]\fP"

.SS "webob\&.static\&.FileApp\&.filename"

.SS "webob\&.static\&.FileApp\&.kw"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
