.TH "webtest.app.TestApp" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webtest.app.TestApp
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBapp\fP, \fBextra_environ\fP=None, \fBrelative_to\fP=None, \fBuse_unicode\fP=True, \fBcookiejar\fP=None, parser_features=None, json_encoder=None, \fBlint\fP=True)"
.br
.ti -1c
.RI "\fBget_authorization\fP (self)"
.br
.ti -1c
.RI "\fBset_authorization\fP (self, value)"
.br
.ti -1c
.RI "\fBcookies\fP (self)"
.br
.ti -1c
.RI "\fBset_cookie\fP (self, name, value)"
.br
.ti -1c
.RI "\fBreset\fP (self)"
.br
.ti -1c
.RI "\fBset_parser_features\fP (self, parser_features)"
.br
.ti -1c
.RI "\fBget\fP (self, url, params=None, headers=None, \fBextra_environ\fP=None, status=None, expect_errors=False, xhr=False)"
.br
.ti -1c
.RI "\fBpost\fP (self, url, params='', headers=None, \fBextra_environ\fP=None, status=None, upload_files=None, expect_errors=False, content_type=None, xhr=False)"
.br
.ti -1c
.RI "\fBput\fP (self, url, params='', headers=None, \fBextra_environ\fP=None, status=None, upload_files=None, expect_errors=False, content_type=None, xhr=False)"
.br
.ti -1c
.RI "\fBpatch\fP (self, url, params='', headers=None, \fBextra_environ\fP=None, status=None, upload_files=None, expect_errors=False, content_type=None, xhr=False)"
.br
.ti -1c
.RI "\fBdelete\fP (self, url, params='', headers=None, \fBextra_environ\fP=None, status=None, expect_errors=False, content_type=None, xhr=False)"
.br
.ti -1c
.RI "\fBoptions\fP (self, url, headers=None, \fBextra_environ\fP=None, status=None, expect_errors=False, xhr=False)"
.br
.ti -1c
.RI "\fBhead\fP (self, url, params=None, headers=None, \fBextra_environ\fP=None, status=None, expect_errors=False, xhr=False)"
.br
.ti -1c
.RI "\fBencode_multipart\fP (self, params, files)"
.br
.ti -1c
.RI "\fBrequest\fP (self, url_or_req, status=None, expect_errors=False, **req_params)"
.br
.ti -1c
.RI "\fBdo_request\fP (self, req, status=None, expect_errors=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBapp\fP"
.br
.ti -1c
.RI "\fBlint\fP"
.br
.ti -1c
.RI "\fBrelative_to\fP"
.br
.ti -1c
.RI "\fBextra_environ\fP"
.br
.ti -1c
.RI "\fBuse_unicode\fP"
.br
.ti -1c
.RI "\fBcookiejar\fP"
.br
.ti -1c
.RI "\fBJSONEncoder\fP"
.br
.ti -1c
.RI "\fBauthorization_value\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBRequestClass\fP = \fBTestRequest\fP"
.br
.ti -1c
.RI "\fBpost_json\fP = \fButils\&.json_method\fP('POST')"
.br
.ti -1c
.RI "\fBput_json\fP = \fButils\&.json_method\fP('PUT')"
.br
.ti -1c
.RI "\fBpatch_json\fP = \fButils\&.json_method\fP('PATCH')"
.br
.ti -1c
.RI "\fBdelete_json\fP = \fButils\&.json_method\fP('DELETE')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_check_status\fP (self, status, res)"
.br
.ti -1c
.RI "\fB_check_errors\fP (self, res)"
.br
.ti -1c
.RI "\fB_make_environ\fP (self, \fBextra_environ\fP=None)"
.br
.ti -1c
.RI "\fB_remove_fragment\fP (self, url)"
.br
.ti -1c
.RI "\fB_gen_request\fP (self, method, url, params=\fButils\&.NoDefault\fP, headers=None, \fBextra_environ\fP=None, status=None, upload_files=None, expect_errors=False, content_type=None)"
.br
.ti -1c
.RI "\fB_get_file_info\fP (self, file_info)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_add_xhr_header\fP (headers)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBauthorization\fP = property(\fBget_authorization\fP, \fBset_authorization\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Wraps a WSGI application in a more convenient interface for
testing\&. It uses extended version of :class:`webob\&.BaseRequest`
and :class:`webob\&.Response`\&.

:param app:
    May be an WSGI application or Paste Deploy app,
    like ``'config:filename\&.ini#test'``\&.

    \&.\&. versionadded:: 2\&.0

    It can also be an actual full URL to an http server and webtest
    will proxy requests with `WSGIProxy2
    <https://pypi\&.org/project/WSGIProxy2/>`_\&.
:type app:
    WSGI application
:param extra_environ:
    A dictionary of values that should go
    into the environment for each request\&. These can provide a
    communication channel with the application\&.
:type extra_environ:
    dict
:param relative_to:
    A directory used for file
    uploads are calculated relative to this\&.  Also ``config:``
    URIs that aren't absolute\&.
:type relative_to:
    string
:param cookiejar:
    :class:`cookielib\&.CookieJar` alike API that keeps cookies
    across requests\&.
:type cookiejar:
    CookieJar instance

\&.\&. attribute:: cookies

    A convenient shortcut for a dict of all cookies in
    ``cookiejar``\&.

:param parser_features:
    Passed to BeautifulSoup when parsing responses\&.
:type parser_features:
    string or list
:param json_encoder:
    Passed to json\&.dumps when encoding json
:type json_encoder:
    A subclass of json\&.JSONEncoder
:param lint:
    If True (default) then check that the application is WSGI compliant
:type lint:
    A boolean

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "webtest\&.app\&.TestApp\&.__init__ ( self,  app,  extra_environ = \fCNone\fP,  relative_to = \fCNone\fP,  use_unicode = \fCTrue\fP,  cookiejar = \fCNone\fP,  parser_features = \fCNone\fP,  json_encoder = \fCNone\fP,  lint = \fCTrue\fP)"

.SH "Member Function Documentation"
.PP 
.SS "webtest\&.app\&.TestApp\&._add_xhr_header ( headers)\fC [static]\fP, \fC [protected]\fP"

.SS "webtest\&.app\&.TestApp\&._check_errors ( self,  res)\fC [protected]\fP"

.SS "webtest\&.app\&.TestApp\&._check_status ( self,  status,  res)\fC [protected]\fP"

.SS "webtest\&.app\&.TestApp\&._gen_request ( self,  method,  url,  params = \fC\fButils\&.NoDefault\fP\fP,  headers = \fCNone\fP,  extra_environ = \fCNone\fP,  status = \fCNone\fP,  upload_files = \fCNone\fP,  expect_errors = \fCFalse\fP,  content_type = \fCNone\fP)\fC [protected]\fP"

.PP
.nf
Do a generic request\&.

.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&._get_file_info ( self,  file_info)\fC [protected]\fP"

.SS "webtest\&.app\&.TestApp\&._make_environ ( self,  extra_environ = \fCNone\fP)\fC [protected]\fP"

.SS "webtest\&.app\&.TestApp\&._remove_fragment ( self,  url)\fC [protected]\fP"

.SS "webtest\&.app\&.TestApp\&.cookies ( self)"

.SS "webtest\&.app\&.TestApp\&.delete ( self,  url,  params = \fC''\fP,  headers = \fCNone\fP,  extra_environ = \fCNone\fP,  status = \fCNone\fP,  expect_errors = \fCFalse\fP,  content_type = \fCNone\fP,  xhr = \fCFalse\fP)"

.PP
.nf
Do a DELETE request\&. Similar to :meth:`~webtest\&.TestApp\&.get`\&.

:returns: :class:`webtest\&.TestResponse` instance\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.do_request ( self,  req,  status = \fCNone\fP,  expect_errors = \fCNone\fP)"

.PP
.nf
Executes the given webob Request (``req``), with the expected
``status``\&.  Generally :meth:`~webtest\&.TestApp\&.get` and
:meth:`~webtest\&.TestApp\&.post` are used instead\&.

To use this::

    req = webtest\&.TestRequest\&.blank('url', \&.\&.\&.args\&.\&.\&.)
    resp = app\&.do_request(req)

\&.\&. note::

    You can pass any keyword arguments to
    ``TestRequest\&.blank()``, which will be set on the request\&.
    These can be arguments like ``content_type``, ``accept``, etc\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.encode_multipart ( self,  params,  files)"

.PP
.nf
Encodes a set of parameters (typically a name/value list) and
a set of files (a list of (name, filename, file_body, mimetype)) into a
typical POST body, returning the (content_type, body)\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.get ( self,  url,  params = \fCNone\fP,  headers = \fCNone\fP,  extra_environ = \fCNone\fP,  status = \fCNone\fP,  expect_errors = \fCFalse\fP,  xhr = \fCFalse\fP)"

.PP
.nf
Do a GET request given the url path\&.

:param params:
    A query string, or a dictionary that will be encoded
    into a query string\&.  You may also include a URL query
    string on the ``url``\&.
:param headers:
    Extra headers to send\&.
:type headers:
    dictionary
:param extra_environ:
    Environmental variables that should be added to the request\&.
:type extra_environ:
    dictionary
:param status:
    The HTTP status code you expect in response (if not 200 or 3xx)\&.
    You can also use a wildcard, like ``'3*'`` or ``'*'``\&.
:type status:
    integer or string
:param expect_errors:
    If this is False, then if anything is written to
    environ ``wsgi\&.errors`` it will be an error\&.
    If it is True, then non-200/3xx responses are also okay\&.
:type expect_errors:
    boolean
:param xhr:
    If this is true, then marks response as ajax\&. The same as
    headers={'X-REQUESTED-WITH': 'XMLHttpRequest', }
:type xhr:
    boolean

:returns: :class:`webtest\&.TestResponse` instance\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.get_authorization ( self)"

.PP
.nf
Allow to set the HTTP_AUTHORIZATION environ key\&. Value should look
like one of the following:

* ``('Basic', ('user', 'password'))``
* ``('Bearer', 'mytoken')``
* ``('JWT', 'myjwt')``

If value is None the the HTTP_AUTHORIZATION is removed

.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.head ( self,  url,  params = \fCNone\fP,  headers = \fCNone\fP,  extra_environ = \fCNone\fP,  status = \fCNone\fP,  expect_errors = \fCFalse\fP,  xhr = \fCFalse\fP)"

.PP
.nf
Do a HEAD request\&. Similar to :meth:`~webtest\&.TestApp\&.get`\&.

:returns: :class:`webtest\&.TestResponse` instance\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.options ( self,  url,  headers = \fCNone\fP,  extra_environ = \fCNone\fP,  status = \fCNone\fP,  expect_errors = \fCFalse\fP,  xhr = \fCFalse\fP)"

.PP
.nf
Do a OPTIONS request\&. Similar to :meth:`~webtest\&.TestApp\&.get`\&.

:returns: :class:`webtest\&.TestResponse` instance\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.patch ( self,  url,  params = \fC''\fP,  headers = \fCNone\fP,  extra_environ = \fCNone\fP,  status = \fCNone\fP,  upload_files = \fCNone\fP,  expect_errors = \fCFalse\fP,  content_type = \fCNone\fP,  xhr = \fCFalse\fP)"

.PP
.nf
Do a PATCH request\&. Similar to :meth:`~webtest\&.TestApp\&.post`\&.

:returns: :class:`webtest\&.TestResponse` instance\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.post ( self,  url,  params = \fC''\fP,  headers = \fCNone\fP,  extra_environ = \fCNone\fP,  status = \fCNone\fP,  upload_files = \fCNone\fP,  expect_errors = \fCFalse\fP,  content_type = \fCNone\fP,  xhr = \fCFalse\fP)"

.PP
.nf
Do a POST request\&. Similar to :meth:`~webtest\&.TestApp\&.get`\&.

:param params:
    Are put in the body of the request\&. If params is an
    iterator, it will be urlencoded\&. If it is a string, it will not
    be encoded, but placed in the body directly\&.

    Can be a :class:`python:collections\&.OrderedDict` with
    :class:`webtest\&.forms\&.Upload` fields included::

        app\&.post('/myurl', collections\&.OrderedDict([
            ('textfield1', 'value1'),
            ('uploadfield', webapp\&.Upload('filename\&.txt', 'contents'),
            ('textfield2', 'value2')])))

:param upload_files:
    It should be a list of ``(fieldname, filename, file_content)``\&.
    You can also use just ``(fieldname, filename)`` and the file
    contents will be read from disk\&.
:type upload_files:
    list
:param content_type:
    HTTP content type, for example `application/json`\&.
:type content_type:
    string

:param xhr:
    If this is true, then marks response as ajax\&. The same as
    headers={'X-REQUESTED-WITH': 'XMLHttpRequest', }
:type xhr:
    boolean

:returns: :class:`webtest\&.TestResponse` instance\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.put ( self,  url,  params = \fC''\fP,  headers = \fCNone\fP,  extra_environ = \fCNone\fP,  status = \fCNone\fP,  upload_files = \fCNone\fP,  expect_errors = \fCFalse\fP,  content_type = \fCNone\fP,  xhr = \fCFalse\fP)"

.PP
.nf
Do a PUT request\&. Similar to :meth:`~webtest\&.TestApp\&.post`\&.

:returns: :class:`webtest\&.TestResponse` instance\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.request ( self,  url_or_req,  status = \fCNone\fP,  expect_errors = \fCFalse\fP, ** req_params)"

.PP
.nf
Creates and executes a request\&. You may either pass in an
instantiated :class:`TestRequest` object, or you may pass in a
URL and keyword arguments to be passed to
:meth:`TestRequest\&.blank`\&.

You can use this to run a request without the intermediary
functioning of :meth:`TestApp\&.get` etc\&.  For instance, to
test a WebDAV method::

    resp = app\&.request('/new-col', method='MKCOL')

Note that the request won't have a body unless you specify it,
like::

    resp = app\&.request('/test\&.txt', method='PUT', body='test')

You can use :class:`webtest\&.TestRequest`::

    req = webtest\&.TestRequest\&.blank('/url/', method='GET')
    resp = app\&.do_request(req)
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.reset ( self)"

.PP
.nf
Resets the state of the application; currently just clears
saved cookies\&.

.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.set_authorization ( self,  value)"

.SS "webtest\&.app\&.TestApp\&.set_cookie ( self,  name,  value)"

.PP
.nf
Sets a cookie to be passed through with requests\&.
.fi
.PP
 
.SS "webtest\&.app\&.TestApp\&.set_parser_features ( self,  parser_features)"

.PP
.nf
Changes the parser used by BeautifulSoup\&. See its documentation to
know the supported parsers\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "webtest\&.app\&.TestApp\&.app"

.SS "webtest\&.app\&.TestApp\&.authorization_value"

.SS "webtest\&.app\&.TestApp\&.cookiejar"

.SS "webtest\&.app\&.TestApp\&.delete_json = \fButils\&.json_method\fP('DELETE')\fC [static]\fP"

.SS "webtest\&.app\&.TestApp\&.extra_environ"

.SS "webtest\&.app\&.TestApp\&.JSONEncoder"

.SS "webtest\&.app\&.TestApp\&.lint"

.SS "webtest\&.app\&.TestApp\&.patch_json = \fButils\&.json_method\fP('PATCH')\fC [static]\fP"

.SS "webtest\&.app\&.TestApp\&.post_json = \fButils\&.json_method\fP('POST')\fC [static]\fP"

.SS "webtest\&.app\&.TestApp\&.put_json = \fButils\&.json_method\fP('PUT')\fC [static]\fP"

.SS "webtest\&.app\&.TestApp\&.relative_to"

.SS "webtest\&.app\&.TestApp\&.RequestClass = \fBTestRequest\fP\fC [static]\fP"

.SS "webtest\&.app\&.TestApp\&.use_unicode"

.SH "Property Documentation"
.PP 
.SS "webtest\&.app\&.TestApp\&.authorization = property(\fBget_authorization\fP, \fBset_authorization\fP)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
