.TH "webtest.forms" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webtest.forms
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCheckbox\fP"
.br
.ti -1c
.RI "class \fBEmail\fP"
.br
.ti -1c
.RI "class \fBField\fP"
.br
.ti -1c
.RI "class \fBFile\fP"
.br
.ti -1c
.RI "class \fBForm\fP"
.br
.ti -1c
.RI "class \fBHidden\fP"
.br
.ti -1c
.RI "class \fBMultipleSelect\fP"
.br
.ti -1c
.RI "class \fBNoValue\fP"
.br
.ti -1c
.RI "class \fBRadio\fP"
.br
.ti -1c
.RI "class \fBSelect\fP"
.br
.ti -1c
.RI "class \fBSubmit\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.ti -1c
.RI "class \fBTextarea\fP"
.br
.ti -1c
.RI "class \fBUpload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Helpers to fill and submit forms\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
