.TH "webtest.debugapp" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webtest.debugapp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugApp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmake_debug_app\fP (global_conf, **local_conf)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdebug_app\fP = \fBDebugApp\fP(form=b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "webtest\&.debugapp\&.make_debug_app ( global_conf, ** local_conf)"

.PP
.nf
An application that displays the request environment, and does
nothing else (useful for debugging and test purposes)\&.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "webtest\&.debugapp\&.debug_app = \fBDebugApp\fP(form=b)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
