.TH "webtest.forms.Radio" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webtest.forms.Radio
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwebtest\&.forms\&.Select\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvalue__get\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBwebtest\&.forms\&.Select\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, *args, **\fBattrs\fP)"
.br
.ti -1c
.RI "\fBforce_value\fP (self, \fBvalue\fP)"
.br
.ti -1c
.RI "\fBselect\fP (self, \fBvalue\fP=None, text=None)"
.br
.ti -1c
.RI "\fBvalue__set\fP (self, \fBvalue\fP)"
.br
.in -1c

Public Member Functions inherited from \fBwebtest\&.forms\&.Field\fP
.in +1c
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBvalue\fP = property(\fBvalue__get\fP, \fBSelect\&.value__set\fP)"
.br
.in -1c

Properties inherited from \fBwebtest\&.forms\&.Select\fP
.in +1c
.ti -1c
.RI "\fBvalue\fP = property(\fBvalue__get\fP, \fBvalue__set\fP)"
.br
.in -1c

Properties inherited from \fBwebtest\&.forms\&.Field\fP
.in +1c
.ti -1c
.RI "\fBvalue\fP = property(\fBvalue__get\fP, \fBvalue__set\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBwebtest\&.forms\&.Select\fP
.in +1c
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBoptionPositions\fP"
.br
.ti -1c
.RI "\fBselectedIndex\fP"
.br
.in -1c

Public Attributes inherited from \fBwebtest\&.forms\&.Field\fP
.in +1c
.ti -1c
.RI "\fBform\fP"
.br
.ti -1c
.RI "\fBtag\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBpos\fP"
.br
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBattrs\fP"
.br
.in -1c

Static Public Attributes inherited from \fBwebtest\&.forms\&.Field\fP
.in +1c
.ti -1c
.RI "dict \fBclasses\fP = {}"
.br
.in -1c

Protected Member Functions inherited from \fBwebtest\&.forms\&.Select\fP
.in +1c
.ti -1c
.RI "\fB_get_value_for_text\fP (self, text)"
.br
.in -1c

Protected Attributes inherited from \fBwebtest\&.forms\&.Select\fP
.in +1c
.ti -1c
.RI "\fB_forced_value\fP"
.br
.in -1c

Protected Attributes inherited from \fBwebtest\&.forms\&.Field\fP
.in +1c
.ti -1c
.RI "\fB_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Field representing ``<input type='radio'>``
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "webtest\&.forms\&.Radio\&.value__get ( self)"

.PP
Reimplemented from \fBwebtest\&.forms\&.Select\fP\&.
.SH "Property Documentation"
.PP 
.SS "webtest\&.forms\&.Radio\&.value = property(\fBvalue__get\fP, \fBSelect\&.value__set\fP)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
