.TH "webtest.compat" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webtest.compat
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBto_bytes\fP (value, charset='latin1')"
.br
.ti -1c
.RI "\fBprint_stderr\fP (value)"
.br
.ti -1c
.RI "\fBescape_cookie_value\fP (value)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSimpleCookie\fP = cookies\&.SimpleCookie"
.br
.ti -1c
.RI "\fBCookieError\fP = cookies\&.CookieError"
.br
.ti -1c
.RI "dict \fBCOOKIE_ESCAPE_CHAR_MAP\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "webtest\&.compat\&.escape_cookie_value ( value)"

.PP
.nf
Escapes a value so that it can be safely stored in a cookie\&.
.fi
.PP
 
.SS "webtest\&.compat\&.print_stderr ( value)"

.SS "webtest\&.compat\&.to_bytes ( value,  charset = \fC'latin1'\fP)"

.SH "Variable Documentation"
.PP 
.SS "dict webtest\&.compat\&.COOKIE_ESCAPE_CHAR_MAP"

.SS "webtest\&.compat\&.CookieError = cookies\&.CookieError"

.SS "webtest\&.compat\&.SimpleCookie = cookies\&.SimpleCookie"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
