.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/distlib/wheel.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/distlib/wheel.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._vendor\&.distlib\&.wheel\&.Mounter\fP"
.br
.ti -1c
.RI "class \fBpip\&._vendor\&.distlib\&.wheel\&.Wheel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.distlib\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.distlib\&.wheel\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&._derive_abi\fP ()"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&._get_suffixes\fP ()"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&._load_dynamic\fP (name, path)"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&._get_glibc_version\fP ()"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.compatible_tags\fP ()"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.is_compatible\fP (wheel, tags=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.logger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.cache\fP = None"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.distlib\&.wheel\&.IMP_PREFIX\fP = 'pp'"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.VER_SUFFIX\fP = sysconfig\&.get_config_var('py_version_nodot')"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.distlib\&.wheel\&.PYVER\fP = 'py' + \fBVER_SUFFIX\fP"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.distlib\&.wheel\&.IMPVER\fP = \fBIMP_PREFIX\fP + \fBVER_SUFFIX\fP"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.ARCH\fP = get_platform()\&.replace('\-', '_')\&.replace('\&.', '_')"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.ABI\fP = sysconfig\&.get_config_var('SOABI')"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.FILENAME_RE\fP"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.NAME_VERSION_RE\fP = re\&.compile(, re\&.IGNORECASE | re\&.VERBOSE)"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.SHEBANG_RE\fP = re\&.compile(br'\\s*#![^\\r\\n]*')"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.SHEBANG_DETAIL_RE\fP = re\&.compile(br'^(\\s*#!('[^']+'|\\S+))\\s+(\&.*)$')"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.distlib\&.wheel\&.SHEBANG_PYTHON\fP = b'#!python'"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.distlib\&.wheel\&.SHEBANG_PYTHONW\fP = b'#!pythonw'"
.br
.ti -1c
.RI "o \fBpip\&._vendor\&.distlib\&.wheel\&.to_posix\fP = lambda o"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.imp\fP = None"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&._hook\fP = \fBMounter\fP()"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.COMPATIBLE_TAGS\fP = \fBcompatible_tags\fP()"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.major\fP"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.major_minor\fP"
.br
.ti -1c
.RI "\fBpip\&._vendor\&.distlib\&.wheel\&.string\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
