.TH "/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/platformdirs/windows.py" 3 "Version 1.0" "Minilog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/umar/Desktop/WorkShop/GLL/Minilog/dist/lib/python3.13/site-packages/pip/_vendor/platformdirs/windows.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpip\&._vendor\&.platformdirs\&.windows\&.Windows\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpip\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.platformdirs\fP"
.br
.ti -1c
.RI "namespace \fBpip\&._vendor\&.platformdirs\&.windows\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBpip\&._vendor\&.platformdirs\&.windows\&.get_win_folder_from_env_vars\fP (str csidl_name)"
.br
.ti -1c
.RI "str|None \fBpip\&._vendor\&.platformdirs\&.windows\&.get_win_folder_if_csidl_name_not_env_var\fP (str csidl_name)"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.platformdirs\&.windows\&.get_win_folder_from_registry\fP (str csidl_name)"
.br
.ti -1c
.RI "str \fBpip\&._vendor\&.platformdirs\&.windows\&.get_win_folder_via_ctypes\fP (str csidl_name)"
.br
.ti -1c
.RI "Callable[[str], str] \fBpip\&._vendor\&.platformdirs\&.windows\&._pick_get_win_folder\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpip\&._vendor\&.platformdirs\&.windows\&.get_win_folder\fP = lru_cache(maxsize=None)(\fB_pick_get_win_folder\fP())"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minilog from the source code\&.
